### ISSUE TITLE
Econ API implementation challenges

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeAPI#1002]
`Account#resetBalances` has a few problems:
 - [ ] `TransactionResult` is linked to `Currency`, so what does `resetBalances` return? It may have modified multiple currencies
 - [ ] What if there are (for no particular reason) no currencies? What do you put in `TransactionResult`?
 - [ ] `Currency` has no identifier - it can't be serialized without risking things like package refactors or slight display name changes breaking it

**Comment by kenzierocks** [comment]
I propose changing the return value to `Map<Currency, TransactionResult>` or changing `TransactionResult` to have a `Set` of related currencies instead of a singular one.

**Comment by gabizou** [comment]
@Aaron1011 Status update?

**Comment by Aaron1011** [comment]
@kenzierocks: Sorry for the huge delay in dealing with this. I'll be addressing these issues in a couple upcoming PRs.

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeAPI/commit/c6fa6a62961784a7ca7e0e047c8071544ca770d4.
