### ISSUE TITLE
Cause builder

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#1004]
Creating `Cause` is a pain right now. You have the option of `Cause.of(Object, Object...)` or `Cause.ofNullable(Object, Object...)` currently, both of which don't make constructing a `Cause` easy or clean (see https://github.com/SpongePowered/SpongeVanilla/blob/master/src/main/java/org/spongepowered/server/mixin/world/MixinExplosion.java#L62-L93 for an example).

**Comment by gabizou** [comment]
What is so hard about making a `List`?

In the hot fix branch, I've made it possible to do the following:
```java
        final List<String> fooList = ImmutableList.of("foo", "bar", "baz", "floof");
        final Cause cause = Cause.of(fooList);
        final List<String> stringList = cause.allOf(String.class);
        assertThat(stringList.isEmpty(), is(false));
        assertThat(stringList.equals(fooList), is(true));
```

**Comment by kashike** [comment]
That's an acceptable fix, thanks.
