### ISSUE TITLE
Composite text is broken

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeAPI#1005]
Previously the following would produce white text just for the buy and sell texts. Now the text color is ignored all together and all text after TextColors.YELLOW is forced yellow.

````java
        Text buyText = Text.of(TextColors.WHITE, buy);
        Text sellText = Text.of(TextColors.WHITE, sell);

        return Text.of(
                TextColors.BLUE, entry.getKey().toUpperCase(),
                TextColors.YELLOW, " (Quick Price: ", buyText, " - ", sellText, ")"
        );
````

**Comment by kashike** [comment]
https://gist.github.com/kashike/3dff9eae4861c4a19fc4

**Comment by ST-DDT** [comment]
IMO the current behaviour is correct.
The method uses all input (regardless of type) and applies the specified format on it.
Creating an exception for `Text`s only is wrong.

Which result do you expect if use see the following code
````java
Text someColorText = Text.of(TextColors.WHITE, "bar");

Text yellowText = Text.of(TextColors.YELLOW, someColorText);
````

IMO you specified `YELLOW` and thus the `Text` should be yellow.

Another example:

````java
Text arenaText = Text.of("MyArena");

Text invitationText = Text.of(TextActions.sendCommand("/join MyArena"), "Click here to join ", arenaText , " and fight others.");
````
Do you really expect `arenaText` to have no `TextAction` applied to it?

However I agree that this might be useful in some cases.
Maybe we could add a `FORMAT_OFF` constant that can be used to disable formatting of `Text` instances. (Maybe even with a more fine grained control ( `TextFormat` or `TextAction` only).)

**Comment by DarkArc** [comment]
I strongly disagree with your analysis. Anytime you explicitly specify something, you should get that. 

I do expect arena text to have that text action, because the arenaText variable didn't specify a conflicting text action. Furthermore, if you're just going to concatenate a string, use a string, not text.

**Comment by ST-DDT** [comment]
> Anytime you explicitly specify something, you should get that. 

This is exactly my opinion. If I explicitly  specify `YELLOW` then everything that follows should be painted yellow.

> Furthermore, if you're just going to concatenate a string, use a string, not text. 

IMO the general behaviour of the method should not alter regardless of the input I pass to it.

**Comment by kashike** [comment]
> This is exactly my opinion. If I explicitly specify `YELLOW` then everything that follows should be painted yellow.

Except that the `Text` provided explicitly sets the colour to `WHITE`.

> IMO the general behaviour of the method should not alter regardless of the input I pass to it.

That is **EXACTLY** what the method is currently doing. It's stripping the colour provided.

**Comment by DarkArc** [comment]
````java
Text arenaText = Text.of(TextActions.sendCommand("/a"), MyArena"); 
Text invitationText = Text.of(TextActions.sendCommand("/join MyArena"), "Click here to join ", arenaText , " and fight others.");
````
What does this do? You're making the contract here that we should strip all specializations from the text in favor of making it a raw string which we inject, in which case you should simply use a string.

**Comment by ST-DDT** [comment]
@DarkArc It handles all input the same and if there a format/action conflicts it uses the latest one specified = `TextActions.sendCommand("/join MyArena")`.

**Comment by DarkArc** [comment]
Assuming that what you're saying is more clear, -- and I'm not saying it is -- is it actually more useful? In how many cases am I going to want to overwrite my old formatting, and in how many cases am I going to want to inject my old formatting into the string? 

To take this even further, what's easier to remedy, removing text information for the outlair I'm inserting (fix for yours) , or duplicating potentially long text information on both sides of the string to restore the behavior I want (fix for mine)?

In all of the plugins I've written, and worked on only once that I can recall have I wanted to strip the information -- and I can't even recall why. On the other hand, many times I've wanted to "put this special text in here."

**Comment by ST-DDT** [comment]
Here the format indicators I have proposed as a solution above:
#808 [Format indicators](https://github.com/ST-DDT/SpongeAPI/commit/fa76c80c376884d7cbc48bd65bb565ff2acdd4de)

````java
Text.of(Text.APPEND_TEXT, TextColors.YELLOW, "Hello", whiteText, Text.FORMAT_TEXT, " and now in yellow:" , whiteText)
````
IMO if you just want to append some `Text` without wanting it to be change use `TextBuilder.append(X)`.

**Comment by kashike** [comment]
@ST-DDT It should really default to true in my opinion.

**Comment by TheRaspPie** [comment]
@ST-DDT You have do differentiate between overwriting style and adding one.
Here your previous example with `TextAction`s:

```java
Text arenaText = Text.of("MyArena");

Text invitationText = Text.of(TextActions.sendCommand("/join MyArena"), "Click here to join ", arenaText , " and fight others.");
```

Here `TextAction` isn't overwriting anything and thus can be applied to `arenaText`.
BUT if you had a style applied to it, say RED, you shouldn't silently overwrite it.

What I want to say is that there is a reason for having a style on `arenaText`.

For example with your argument we can't do this:
```java
Text playerName = Text.of(RED, player.getName());

Text message = Text.of(GREEN, "Player ", playerName, GREEN, " died");
```

or even this:
```java
Text message = Text.of(GREEN, "Player ", playerName, " died");
```

**Comment by ST-DDT** [comment]
Of course you can. You just have to set the color to `NONE` before setting the playerName.

> Here `TextAction` isn't overwriting anything and thus can be applied to `arenaText`.
BUT if you had a style applied to it, say RED, you shouldn't silently overwrite it.

IMO if a format is specified it should be applied. Always. No "only if not specified on the target". Think about having two different text actions (hover and click). Do you want the hover action to stay the same while the text action changes on the arena object only?

But I am repeating myself.

**Comment by TheRaspPie** [comment]
I propose to flatten the `Text` into the varargs array in `Text.of`.

```java
Text playerName = Text.of(RED, player.getName());

Text message = Text.of(GREEN, "Player ", playerName, GREEN, " died");
```

would be reduced to
```java
Text message = Text.of(GREEN, "Player ", RED, player.getName(), GREEN, " died");
```

**Comment by ST-DDT** [comment]
Following your example if you drop the second `GREEN` then "died" would be red in that case.

I don't want to strip the formatting. I only want the specified format applied.

**Comment by ryantheleach** [comment]
Specific should beat the general color. if this was nested html what would you expect from

``<span color="yellow">Quick Price: <span color="white">buyprice</span> - <span color="white">sellPrice</span>)</span>``

**Comment by ST-DDT** [comment]
@ryantheleach Sorry to correct you but you are a little bit off here. 
Since the method actually returns something like this:
(Based on the data structure, span = `Text` instance)
````html
<span>
<span color="yellow">Quick Price: </span>
<span color="white">buyprice</span> <-- should be yellow
<span color="yellow"> - </span>
<span color="white">sellPrice</span> <-- should be yellow
<span color="yellow">)</span>
</span>
````

**Comment by ryantheleach** [comment]
I was basing the example off of dark's original code.
```
     return Text.of(
                TextColors.BLUE, entry.getKey().toUpperCase(),
                TextColors.YELLOW, " (Quick Price: ", buyText, " - ", sellText, ")"
        );
```
But you helped me to realize, that we both had the example tree structure wrong for what should be happening.

```
<span>
<span color="yellow">Quick Price: </span>
<span color="yellow"><span color="white">buyprice</span></span>
<span color="yellow"> - </span>
<span color="yellow"><span color="white">sellPrice</span></span>
<span color="yellow">)</span>
</span>
```

Which could be flattened to my original example.

**Comment by kashike** [comment]
I agree with @ryantheleach.

**Comment by ST-DDT** [comment]
@ryantheleach Do I get you right that for `Text`s the following code should be used somewhere around [here](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/Text.java#L853)

````java
childBuilder = builder();
childBuilder.append(((TextRepresentable) obj).toText())
````

**Comment by TheRaspPie** [comment]
@ST-DDT

What I meant was that
```java
Text playerName = Text.of(RED, player.getName());
Text message = Text.of(GREEN, "Player ", playerName, GREEN, " died");
```

would be REDUCED to
```java
Text message = Text.of(GREEN, "Player ", RED, player.getName(), GREEN, " died");
```

NOT that you would write the last one.

You could simply write
```java
Text message = Text.of(GREEN, "Player ", Text.of(RED, player.getName()), " died");
```

to get the following representation:
```
"Player " (green) +
player.getName() (red) +
" died" (green)
```

So if you have a composite `Text`, there's a reason you have formatting on the children `Text`.
If you just strip that and apply the outer formatting, we don't even need composite `Text`s because then you could simply copy the contents of that `Text` (as an array) into the passed argument list (`Text.of(Object...)`).

The only reason why there is a way to put `Text`s into other `Text`s is the fact that the inner one can have formatting and that this formatting can be opaque to the outer `Text` in order to be truly modular.

**Comment by TheRaspPie** [comment]
@DarkArc Can you tell me the commit hash that made this change? I'm not sure if I found the right one...

**Comment by DarkArc** [comment]
@TheRaspPie as I recall it was part of this https://github.com/SpongePowered/SpongeAPI/commit/6ee796d6f3e53f155976f485a030ed8c7848985f

**Comment by TheRaspPie** [comment]
@DarkArc Thanks.

@ST-DDT and others:
I just want to make a quick note here:

Mojang's internal JSON ("Mojangson") representation, after which `Text` is modelled, has specific inheritance properties. These state that if inheritance occurs, the inner - most specific - text formatting **overwrites** the outer one.

Just for documentation. I noticed that this is *already accepted*.

**Comment by TheRaspPie** [comment]
Right now I ended up copying the method and modifying it so it works correctly. However that is kind of messy, so I would recommend fixing it so that everyone knows about it.

**Comment by kashike** [comment]
@Minecrell

**Comment by Minecrell** [comment]
Fixed in bleeding: https://github.com/SpongePowered/SpongeAPI/commit/4e03ee20a8c6e96dae5eb350da826acac43de2be
