### ISSUE TITLE
Problems with Explosive Hierarchy

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeAPI#1008]
The [Explosive](https://jd.spongepowered.org/3.0.0/index.html?org/spongepowered/api/entity/explosive/Explosive.html) Interface gives the following contract:
1. `Explosive`s can be detonated at will
2. `Explosive`s have a freely configurable explosion radius
3. `Explosive`s result in an `org.spongepowered.api.world.explosion.Explosion` (?)

Now let's take a look at which entities are `Explosive`. From the javadocs I've found [Creeper](https://jd.spongepowered.org/3.0.0/index.html?org/spongepowered/api/entity/living/monster/Creeper.html), [PrimedTNT](https://jd.spongepowered.org/3.0.0/?org/spongepowered/api/entity/explosive/PrimedTNT.html), [MineCartTNT](https://jd.spongepowered.org/3.0.0/?org/spongepowered/api/entity/vehicle/minecart/MinecartTNT.html), [LargeFireball](https://jd.spongepowered.org/3.0.0/?org/spongepowered/api/entity/projectile/explosive/fireball/LargeFireball.html), [SmallFireball](https://jd.spongepowered.org/3.0.0/?org/spongepowered/api/entity/projectile/explosive/fireball/SmallFireball.html), [WitherSkull](https://jd.spongepowered.org/3.0.0/?org/spongepowered/api/entity/projectile/explosive/WitherSkull.html) and [Firework](https://jd.spongepowered.org/3.0.0/?org/spongepowered/api/entity/projectile/Firework.html).

Of these, `Creeper` and `LargeFireball` are the only one that, in minecraft code, have a freely configurable explosion radius / power that is also stored in NBT.

`PrimedTNT` and `WitherSkull` create their explosions with a hard-coded explosion radius of 4 and 1 respectively. It would be possible to provide mixin to these entities that simulate this functionality, but the change would have to be written to NBT as well. `MinecartTNT` has the same issues plus the fact that its explosion radius is determined *randomly* based on the minecart's speed during explosion (`4.0 + rand.nextDouble() * 1.5 * Math.min(speed, 5.0))`).

`SmallFireball` should not be `Explosive` at all as it is a mere projectile capable of lighting blocks on fire. No explosions here.

`Firework` is a problem of some other sort. Technically, it does not cause `Explosions`. If we were to treat firework effects as explosions, we would run into two new problems:
* The explosiveRadius is not configurable freely as the radius depends solely on the [FireworkShape](https://jd.spongepowered.org/3.0.0/?org/spongepowered/api/item/FireworkShape.html)
* Any `Firework` can have an arbitrary number of `FireworkEffect`s and therefore any arbitrary combination of the possible explosive radii.

Another big problem with some of these is that while they do not have a (freely) configurable explosion power, they can be detonated at will. However the API assumes that these traits only occur simultaneously. It seems like a rework of these hierarchies is in order.

**Comment by Deamon5550** [comment]
>its explosion radius is determined randomly based on the minecart's speed during explosion

Could possible be a [SeededVariableAmount](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/weighted/SeededVariableAmount.java#L35)

**Comment by simon816** [comment]
While we're talking about explosions, @gabizou what happened to `setExplosionPower`? https://github.com/SpongePowered/Cookbook/pull/12#discussion_r48689435

**Comment by Zidane** [comment]
Closed in @windy1 's explosions refactor.
