### ISSUE TITLE
Add `AITask.getRequirements()` aka mutex bits

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeAPI#1014]
Currently it is not possible to check which components are affected by an [`AITask`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/ai/task/AITask.java#L38) thus implementing 

``` java
boolean canRunConcurrentWith(AITask<O> other)
```

is quite horrible.

``` java
public class HeadShakerAITask extends AbstractAITask<Agent> {

    private final Set<AITaskType> typeWhitelist = ImmutableSet.<AITaskType>builder()
            .add(AITaskTypes.AVOID_ENTITY)
            .add(AITaskTypes.RUN_AROUND_LIKE_CRAZY)
            .add(AITaskTypes.SWIMMING)
            .add(AITaskTypes.WANDER)
            .add(AITaskTypes.FOLLOW_PARENT)
            .add(AITaskTypes.FOLLOW_PLAYER)
            .add(AITaskTypes.WALKING_HOME)
            .add(AITaskTypes.PICK_FLOWER)
            .add(AITaskTypes.HARVEST_FIELD)
            .add(AITaskTypes.BREED)
            .add(AITaskTypes.ATTACK)
            .add(AITaskTypes.SHOOT_ARROW)
            .add(MyAITaskTypes.WALK_TO_MUSIC)
            .add(MyAITaskTypes.DANCE)
            .add(MyAITaskTypes.JUMPSTYLE)
            .add(MyAITaskTypes.HUG_FRIENDS)
            .add(MyAITaskTypes.SHAKE_COCKTAIN)
            .add(darkReflectionMagic("org.example.OtherAITaskTypes", "FILL_SHELVES_WITH_GOODS"))
            .add(darkReflectionMagic("org.example.OtherAITaskTypes", "PICKUP_GOODS_FROM_THE_STORE"))
// Add other plugins tasks here somehow and more vanilla types maybe via classnames/config?
// And I have to know their impl as well since otherwise I don't know whether they would conflict or not.
            .build();

    public HeadShakerAITask(AITaskType type) {
        super(type);
    }

    @Override
    public boolean canRunConcurrentWith(AITask<Agent> other) {
        return this.typeWhitelist.contains(other.getType());
    }

}
```

`HeadShakerAITask` does nothing complex at all, but it has to know ALL other `AITask`s including impl. 

There must be a simplification for that.

Adding the following to either `AITask` or `AITaskType` will solve the problem. 

``` java
Set<AIRequirement> getRequirements();
```

Because we no longer have to keep track of ALL compatible tasks anymore because we can simply ask them ourselves.
- A: "Hey B. What do you need?"
- B: "Hey I need `LOOK` and `MOVEMENT`."
- A: "Sorry, B. We cannot run concurrently since I need `LOOK` myself."

Now the impl would probably look like this:

``` java
public class HeadShakerAITask extends AbstractAITask<Agent> {

    private final Set<AIRequirement> requirements = ImmutableSet.of(AIRequirements.LOOK);

    public HeadShakerAITask(AITaskType type) {
        super(type);
    }

    @Override
    public Set<AIRequirement> getRequirements() {
        return requirements ;
    }

    @Override
    public boolean canRunConcurrentWith(AITask<Agent> other) {
        // return other.getRequirements().stream().noneMatch(requirements::contains); // Generic solution
        return !other.getRequirements().contains(AIRequirements.LOOK); // Simple solution
    }

}
```

The implementation could still skip the check for compatibility, but then they should not wonder if something strange happens. It could also add additional checks. Like "Don't run away like crazy while I'm active!"

Why a `CatalogType` instead of an `int`? 
`Int` is an implementation detail, other impls may use a `EnumSet` or a `long` to allow more values.
Also plugins could add their own values/constants if only some tasks may not work together and you don't have to care whether plugin X or Y uses your bit mask already/as well.

Moved here from : https://github.com/SpongePowered/SpongeAPI/pull/1012#issuecomment-169410717
@Zidane

**Comment by Zidane** [comment]
Again, the API AITask IS NOT JUST FOR VANILLA TASKS. My job as SpongeAPI is to give you the ability to dictate, 100%, how you want concurrent running to work.

This isn't an API problem.

**Comment by Zidane** [comment]
Seriously, if you read the other issue I said a child interface, called VanillaAITask, could be added in-which these "requirements" can be added.

Its not getting added to the base AITask.

**Comment by liach** [comment]
Well we need something for `AbstractAITask` to implement to function like vanilla mutex in order to prevent conflicts. `AIRequirement` or `AITaskCategory` might be a way to do that in the API, and the conversion between mutex and such categories will be only done in implementations such as SpongeCommon. Will that be acceptable? **Mutex no longer exists in the api** but only `AIRequirement` or `AITaskCategory`.

**Comment by ST-DDT** [comment]
@Zidane You told us that the other issue should not be polluted with the discussion, but by the time I create a new issue to start said discussion you close it? I don't get you.

> I said a child interface, called VanillaAITask, could be added in-which these "requirements" can be added (if you want Vanilla's).

First of all: I would be glad if that interface could be added at all. Although I wouldn't go for the name because I will implement it in all my AI classes to ensure interoperability with default minecraft AI tasks.

> Its not getting added to the base AITask.

Could you please explain why?

Please correct me if I'm wrong, but we use a [superclass transformer](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/entity/ai/SpongeEntityAICommonSuperclass.java) to make `AbstractAITask` implement/extend `EntityAIBase` (the minecraft equivalent of `AITask`) thus we have mutex bits there whether we want them or not. On the other side we have a mixin [`MixinEntityAIBase`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/ai/MixinEntityAIBase.java#L68) that checks whether the mutex bits are distinct. `0 & mask == 0` => Distinct. So all vanilla task can run concurrently with plugin created ai tasks, with no way to prevent this (except nms).

**Comment by Zidane** [comment]
@ST-DDT 

I may be wrong but an issue being closed doesn't stop discussion on it (or it may for non-org members...let me know).

Let me make this simple...the only reason why we make AbstractAITask an EntityAIBase child in OUR impl is so mods can interact with it without needing to unwrap some "SpongeEntityAIBaseAPIWrapper". This isn't some invitation for you to impose mutex bits on my API when that is just a Minecraft concept.

What you ought to do is...

1. (For the third time now...) Add a VanillaAITask interface that extends AITask and you'll have all the mutex goodness you desire from Vanilla tasks.
2. Toss AIRequirement and just use AITaskType. For each AI in Vanilla, they'll all have an AITaskType (just the same as AbstractAITask s do). If you want the type to define its "categories" then I'll brainstorm but I won't make it a requirement at the top end.

```Could you please explain why?```
For the reasons above but I'll reiterate again. It is not my desire to make the AI framework 100% Vanilla. Dealing with mutexes (or your sugarcoated "requirements") are a bear and tie the hands of the developer extremely. Give me time to think of a better solution or present one to me but realize I will not impose this onto the root AITask.

**Comment by Zidane** [comment]
Re-opened so you don't think I have completely wrote this off :p.

**Comment by liach** [comment]
:+1: Waiting for your better solution on that.

**Comment by liach** [comment]
The entity artificial intelligence of Minecraft has some assigned bits. Different bits are actually available under different entity conditions.

**Comment by liach** [comment]
In fact, we might consider implementing this in a fashion similar to that of BlockChangeFlag.

**Comment by Zidane** [comment]
Closing in favor of the AI v2 branch. I'll open a PR and discussion can be made there.
