### ISSUE TITLE
SpongeAPI versioning OCD

### ISSUE THREAD

**Issue by kinggoesgaming** [SpongePowered/SpongeAPI#1017]
Currently the way SpongeAPI versioning works is that we have the SemVer layout + "-SNAPSHOT" at the end. Everytime there is a build released to the maven repo it continues that format with the date/time stamp as it is supposed to work.

However an important guideline for SemVer is not at all considered:

> Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version.

Any "-SNAPSHOT" file is continuously being replaced, at least for the person who is going to download the API.

---

### My solution for this

Since a version is bumped only when releasing an update or a patch, it should be released without the "-SNAPSHOT". This will ensure the original release version when the bump was made remains untouched. After the release a "-SNAPSHOT" can be added for continuing development.

For example 3.1.0 provides you the bump version and any one wanting to stay with the release versions instead of the latest snapshot can use 3.1.0-SNAPSHOT

**Comment by liach** [comment]
There is no issue: 3.1.0 has not released yet! When it is released devs will remove `-SNAPSHOT` as you've considered.

**Comment by kinggoesgaming** [comment]
That was an example...

**Comment by liach** [comment]
So the preparation for 3.1.0 is in `3.1.0-SNAPSHOT`, and the formal content of 3.1.0 is in `3.1.0`. The next version of `3.1.0` is simply `3.2.0-SNAPSHOT`. Right? This is what sponge developers are doing.

**Comment by liach** [comment]
> Once a versioned package has been released

Again your explaination is nonsense, **3.1.0 has not released yet!**

**Comment by Deamon5550** [comment]
`-SNAPSHOT` is a special build qualifier for maven specifying that this build is not a release build and hence should not be cached for any reasonable amount of time ([read more here](https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401).
