### ISSUE TITLE
A way to 'filter' a cuboid region for block content

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeAPI#1019]
A cuboid region such as an Extentview or just being defined by a corner and lwh or two corners, however is easiest...

To be able to get a boolean result for "is there an x block in the region" or "is there a non-air block in the region"... where the actual location of it doesn't matter, just that there is such a block instance present in the region or not, or that there are no non-air blocks in the region.. or no non-liquid...  to help quickly assess if the region is empty space or has something present, is pure water, or has blocks present, or if there is a diamondore anywhere somewhere within that space, though perhaps returning the position of the first block that 'breaks' the need to continue checking would make sense.

The "if any" would be able to bail out ASAP as one is detected - any diamond ore = bail with yes, while "are all air" or "are all liquid"  or "are all solid" would require testing all blocks.

**Comment by ryantheleach** [comment]
There might even be a quicker check depending on the region for "is this region empty" due to the lighting system keeping track of column / height map data. So exposing the "Is this region empty" separately might be a good idea.

**Comment by DDoS** [comment]
This is a planned feature for the view API, I just need free time to work on it.

**Comment by DDoS** [comment]
Mostly done in https://github.com/SpongePowered/SpongeAPI/pull/1030, it just doesn't have early iteration ending, but that could be added easily.
