### ISSUE TITLE
Setting the weather in a world

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeAPI#1025]
The current method name -- forecast(weather) and its alternate form forecast(weather, time) -- is not clear in its function as a SETTING function...

It would imply 'what is it going to be right now' query, or 'what is it going to be in x more time units' querying, rather than "Make it this" and "Make it this For a duration of x time units"

Can a renaming be considered?

**Comment by Zidane** [comment]
Closed in bleeding.
