### ISSUE TITLE
StairShapeData

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1026]
There is a data for stairshape, however the shape of the stair (apart from direction, and upside down) is controlled by the blocks surrounding it. 

As far as I'm aware, this would discount it from being a Data, and would be more likely to be a Property.

http://minecraft.gamepedia.com/Stairs#Block_data

**Comment by ryantheleach** [comment]
Maybe not, but I think we definitely need a way of telling the difference between virtual and non virtual traits/data/state

**Comment by simon816** [comment]
It's possible in `BlockSnapshot`, there's a method [`getExtendedState()`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/block/BlockSnapshot.java#L69) which includes virtual states.
It would be useful to have that on `Extent` too. Current work-around is to do `location.createShapshot().getExtendedState()`

**Comment by ryantheleach** [comment]
I know you can get the extended state, I just think it's kind of hard to tell the difference API wise on what you can actually set on a block.

**Comment by gabizou** [comment]
@ryantheleach The difficulty is when exposing that it's a virtual data, you could very well say "oh, virtual data shouldn't be serialized", but how do you exactly know whether it's virtual? Add a `isVirtual()` to `DataManipulator` and `ImmutableDataManipulator`? Add an annotation `@VirtualData`?

**Comment by ryantheleach** [comment]
That's assuming that virtual traits should be exposed via the Data API...

I don't have a solution, but it doesn't look clean to me.

**Comment by gabizou** [comment]
> That's assuming that virtual traits should be exposed via the Data API...

What may be virtual today, may no longer be virtual in the future though ;) For the mean time, I'd imagine it should still be exposed nonetheless as in the event there is some sort of client API for telling clients to render an extended block state, this would in effect be a certain use case. For now at least, since `BlockState`s are immutable anyways, it's easy to expose that they have their extended data values.
