### ISSUE TITLE
ShapedRecipie builder

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#1028]
The [ShapedRecipe.Builder](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/recipe/ShapedRecipe.java#L71) is a bit annoying/odd to use.
Current: 

``` java
builder
    .width(2)
    .height(2)
    .ingredient(2, 2, ItemStack.builder().build());
```

In my opinion, something like this (as seen in vanilla/forge to a point) would be nice:

``` java
builder
    .aisle("~~~", "~~~", "~~X")
    .where('~', ItemStack.builder().build())
    .where('X', ItemStack.builder().build());
```

**Comment by Zidane** [comment]
Closing as there is now a PR for this. Comment on it.
