### ISSUE TITLE
Minor mistake in javadoc of Order enum

### ISSUE THREAD

**Issue by blablubbabc** [SpongePowered/SpongeAPI#1034]
Coincidentally noticed while reading the javadocs on https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/Order.java:

Order#BEFORE_POST and Order#POST both state 'is read only but can cancel events', but the javadoc in the file header states that cancellation is not allowed for those.

**Comment by Zidane** [comment]
Closing as this is now on the OCD list. Thanks!
