### ISSUE TITLE
World.setGameRule missing.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1035]
World has defined methods for getting a single gamerule, getting a map of gamerules, but has no setting to set gamerules.

I was hoping to create a plugin that would auto-setup worlds for UltraHardcore which involves setting gamerule settings.

At the moment the only alternative is to run commands with a given input.

**Comment by simon816** [comment]
You can use the `WorldProperties` `world.getProperties().setGameRule(rule, value)`
