### ISSUE TITLE
Cause Inconsistency

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeAPI#1039]
I find it awkward that for some events I can say something like:

``` java
Optional<Player> optPlayer = event.getCause().first(Player.class);
```

And this will always let me know if there's any player involved. Then for other events I have to use something like this:

``` java
Optional<EntityDamageSource> optDamageSource = event.getCause().first(EntityDamageSource.class);
if (optDamageSource.isPresent()) {
    Entity srcEntity;
    if (optDamageSource.isPresent() && optDamageSource.get() instanceof IndirectEntityDamageSource) {
        srcEntity = ((IndirectEntityDamageSource) optDamageSource.get()).getIndirectSource();
    } else {
        srcEntity = optDamageSource.get().getSource();
    }

    if (!(srcEntity instanceof Player)) {
        return;
    }
...
```

I think Cause.first() and related methods should always include all involved objects for cases such as this where there's, what I would call a metaobject. So in this case, the indirect source would also be returned by Cause.first(). That way I can replace this entire thing with one simple line (identical to the original):

``` java
Optional<Player> optPlayer = event.getCause().first(Player.class);
```

While I also maintain the ability to use the more in depth version for derivation of the cause.

**Comment by Deamon5550** [comment]
I like the concept I'm just trying to think how this can cleanly be supported.

**Comment by DarkArc** [comment]
@Deamon5550 I was actually thinking about it some, the simplest thing we could do is add a MetaCause interface.
````java
public interface MetaCause {
    Collection<Object> getSubObjects();
}
````

Then when an object which is an instance of MetaCause is added to a cause object, we just pull in everything from the getSubObjects method. This would of course require that things like DamageSource implement the MetaCause interface, but that shouldn't be a big deal.

I'm also open to other suggestions if someone has another, but I think this is the most straight forward approach.
