### ISSUE TITLE
Add a way to set the entity that a guardian's beam is targeting

### ISSUE THREAD

**Issue by TypicalDarkness** [SpongePowered/SpongeAPI#1045]
It would be really cool if there was a way to specify the target of a guardian's beam.
I asked someone on the forums how this would be possible and they told me this was the way to do it in NMS:  `((Entity)guardian).getDataWatcher().updateObject(17, ((Entity)someEnity).getEntityId());`

**Comment by kashike** [comment]
This is a job for the data api. `GuardianBeamTargetData` or so

**Comment by gabizou** [comment]
No, @kashike, it isn't. Anything that is targeting a live `Entity` instance isn't Data API's place to dictate. Especially since the target isn't serialized.
