### ISSUE TITLE
Get the block the player is targetting.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1049]
Add the block the player is currently targeting.

You can not currently use blockrays for this, as they do not use the bounding boxes.

Example: Use UseItemStack event instead of InteractBlockEvent in order to control the amount of durability that the item stack takes. However now you have no access to the block the user may be interacting with.

**Comment by DDoS** [comment]
Duplicate.

**Comment by kashike** [comment]
@DDoS duplicate of which?

**Comment by DDoS** [comment]
@kashike Edited my reply. I shouldn't be addressing issues as the first thing in the morning...
