### ISSUE TITLE
Add events for hoppers accessing an inventory

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeAPI#1051]
There doesn't appear to be any event that captures hopper interaction with an inventory.

**Comment by Zidane** [comment]
@bloodmc 

Pretty sure these were being captured when testing inventory in the past...

**Comment by Bammerbom** [comment]
Any updates on this issue? There are still no events for it are there?

**Comment by kmecpp** [comment]
I would think this action should fire the ChangeInventoryEvent.Transfer but it does not.

**Comment by Faithcaio** [comment]
ChangeInventoryEvent.Transfer.Pre/Post are implemented in API 7
