### ISSUE TITLE
Add ability to make armor stand a "Marker"

### ISSUE THREAD

**Issue by MichaelPriebe** [SpongePowered/SpongeAPI#1052]
Marker: 1 or 0 (true/false) - if true, ArmorStand's size will be set to 0, have a tiny hitbox and disable interactions with it. May not exist.

http://minecraft.gamepedia.com/Chunk_format#ArmorStand

**Comment by phroa** [comment]
Is that 1 negative or positive? Other data values for that entity use positive 1 or 0

**Comment by JBYoshi** [comment]
All boolean-like tags (byte tags that represent boolean values) are restricted to 0 and positive 1.

**Comment by MichaelPriebe** [comment]
I just copied it from the wiki, seems they accidentally put that negative sign. Ill fix it.
