### ISSUE TITLE
RespawnPlayerEvent that is fired when player's are fully loaded

### ISSUE THREAD

**Issue by hsyyid** [SpongePowered/SpongeAPI#1053]
As the title implies, I feel as though we need an event that is fired when a player has respawned AND is fully loaded into the world.

**Comment by Zidane** [comment]
Not seeing an issue, listen to RespawnPlayerEvent with a Listener that is at the LAST Order. If you need for the Player to be at the location that was specified in the event, schedule a task for a tick later.
