### ISSUE TITLE
Add Vehicle interface as a base for Boat, Minecart

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeAPI#1055]
It seems like this was the intention, given the package name is `vehicle`, but it would helpful to group Boat/Minecart/etc vehicles together with a parent `Vehicle` interface.

**Comment by gabizou** [comment]
We can't since there is no shared interface between the two underlying entities (plus any mods that act like vehicles couldn't be mixed in).

**Comment by Zidane** [comment]
Closing this until someone can provide further information allowing us to do so.
