### ISSUE TITLE
Per Player Weather and Time

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeAPI#1059]
Add an API to set the weather and time (#393) for a specific player.

**Comment by modwizcode** [comment]
yet another duplicate? https://github.com/SpongePowered/SpongeAPI/issues/665

**Comment by Faithcaio** [comment]
only the time part
but i was told to put em both in the issue

**Comment by MattBDev** [comment]
This is a duplicate. I previous issue #665 for the exact same thing was already merged into #393.
