### ISSUE TITLE
Allow determination of whether or not a command execution has failed

### ISSUE THREAD

**Issue by minecrafter** [SpongePowered/SpongeAPI#1073]
I am working on the new official plugin for [Buycraft](https://www.buycraft.net). An integral and required part of the plugin is to determining whether or not an external plugin command has generated an exception or has otherwise failed to execute so that the command execution can be delayed and retried at a later time. Currently, Sponge does not provide this functionality, leaving us to simply execute the command and hope it successfully completed.

**Comment by minecrafter** [comment]
As it turns out, `InvocationCommandException` is mostly what I need. However, it doesn't handle uncaught exceptions from commands.

**Comment by me4502** [comment]
> As it turns out, InvocationCommandException is mostly what I need. However, it doesn't handle uncaught exceptions from commands.

Would it not make more sense to have it just handle all exceptions? @SpongePowered/developers ?

**Comment by ImMorpheus** [comment]
https://github.com/SpongePowered/SpongeAPI/blob/94d7fb22fcc0b77e5af44b9f9e7dc68534ecc3da/src/main/java/org/spongepowered/api/command/CommandException.java#L31-L32

API wise, this is handled by `CommandException`
