### ISSUE TITLE
Plugin Annotation Fix

### ISSUE THREAD

**Issue by EliterScripts** [SpongePowered/SpongeAPI#1077]
I would like the plugin annotation to have the attribute, "author" with it. This would be great for my plugin, because its one more place for the hard working developer to get credit. Also, I'd like to be able to get the author from the Plugin Container, to accommodate this attribute. For example: PluginContainer.getAuthor(), just like PluginContainer.getId() works.

I really hope this is detailed and informative enough to add! Thanks!

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/tree/feature/plugin-meta
related: #624

**Comment by EliterScripts** [comment]
Coppied from the IRC channel, after Clienthax said "<clienthax> tbh it would serve no functional purpose
<clienthax> why not just put a log message in when its loaded?
<clienthax> @Eliter"

"
<Eliter> clienthax, I see it having a purpose. One more place for developer's name. I spend hours on something, I damn well might want to write my name anywhere possible!
<Eliter> clienthax, also, what's to lose by adding it? Two minutes, adding the feature?
<Eliter> clienthax, it's also easier, and more central for me.
<Eliter> I can do MainPluginFile.getContainer().getAuthor() to get the author, in case I want to change my pseudo name.
"
