### ISSUE TITLE
cannot send formatted text to player

### ISSUE THREAD

**Issue by hunter688** [SpongePowered/SpongeAPI#1078]
I need send formatted text to player, eg: §c §r§5 §r§1 §r§f, but when use 

player.sendMessage(Text.of("§c §r§5 §r§1 §r§"));

all characters § are stripped. Howto send ? In the v2 API worked...

**Comment by Minecrell** [comment]
You should use a text builder or `Text.of(...)` for constructing formatted text, see https://docs.spongepowered.org/en/plugin/text/text.html

Alternatively, if your input is coming e.g. from a configuration you should use one of the text serializers, see https://docs.spongepowered.org/en/plugin/text/representations/index.html (in your case, the legacy/formatting code text serializer).

As of Text API 3, sending color codes directly (without going through the text serializer) is no longer supported.
