### ISSUE TITLE
Thaumic Shielding not functioning on Forge Server utilizing Sponge API

### ISSUE THREAD

**Issue by Quiiliitiila** [SpongePowered/SpongeAPI#1082]
The community that I am part of uses (what I believe to be) the latest version of Sponge on our Forge server. I've come to find that for some reason or another one (that I've found) component of a mod we run (Thaumcraft 5) no longer functions with Sponge installed.

I've tested it on my end, using the function in SP with no issues but all the mods installed except Sponge. The moment Sponge gets added, we loose the component. 

For the moment it appears that Thaumic Shielding is the only thing not working in TC, but honestly I haven't had time to test everything that TC has to offer. I played for quite some time before getting the shielding and never noticed anything amiss with any other TC features, so hopefully the issue is contained to just the Thaumic Shielding.

**Comment by Zidane** [comment]
Can you go into more detail of what isn't functioning?

**Comment by Quiiliitiila** [comment]
Sure!
So basically Thaumic shielding works like this; the player gets an item that is equipped using Thaumcraft's Baubles system and that item grants Thaumic shielding, which is essentially extra health. The Thaumic Shielding appears as additional yellow hearts above your normal HP bar and as per normal, the yellow Thaumic Shielding hearts are supposed to be drawn from first if the player is damaged. However it seems that for whatever reason, Sponge is having the damage bypass the additional HP entirely and just go to normal HP.

Everything else seems to function with the Thaumic Shielding, there are no inconsistencies with the amount of shielding one should get, all of the graphical effects are still in place. The HP just doesn't get drawn from first as it should be.

**Comment by Quiiliitiila** [comment]
I realize I put this issue in the wrong section, I'm moving the issue to the Sponge-Forge section and closing this report.
