### ISSUE TITLE
Allow unlimited ItemStacks

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/SpongeAPI#1086]
It would be useful to let us set an ItemStack to be "unlimited," like *Essentials*'s `/unlimited` command, or *NEI*'s "111" infinite stacks.

This should:
- Be separate than the stack size (toggle at any time).
- Prevent the stack size from changing.
- Prevent the durability from changing (even mods' electrical tools' batteries).

**Comment by gabizou** [comment]
This is really for a plugin to implement. For the underlying implementation, it's a giant hack that is surely going to break with mod compatibility for unforeseen corner cases. A plugin can easily do this by listening to specific events and reverting the `ItemStack` to the previous snapshot before use.
