### ISSUE TITLE
Hide factory methods of primitive properties

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/SpongeAPI#1087]
Primitive properties like `org.spongepowered.api.data.property.BooleanProperty` currently have their ~~`of(Object)`~~ factory methods set to **public**. This may cause confusion when people more specific properties such as `org.spongepowered.api.data.property.block.SolidCubeProperty`, and get confused when they expect the `of(Object)` method, and others, of _that_ class to work properly.

A suggestion would to make the ~~`of(Object)`~~ factory methods **protected** in all primitive properties, and have the specific properties override this method _only when_ they support it. If devs require this method for a generic property that does not yet have a class, a class named like `SimpleBooleanProperty` can be created that wraps ~~`super.of(Object)`~~ the current behaviour. There should also be a `fromPrimitive()` value made that is public, that only accepts that specific primitive, for creating objects to compare (such as with `matches()`).

**Comment by gabizou** [comment]
This isn't so much of an issue of primitive properties more so than the static methods being their functional equivalents to *just calling a constructor*. In any case, they can be hidden by simply writing new `of()` methods for every `Property` in the Data API.
