### ISSUE TITLE
Add a way to Configurate-Serialize Text

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/SpongeAPI#1089]
It would be useful is plugins could have the messages they output into chat be able to stored **directly in their config** like `cfg.getNode(path).setValue(Text.of("hi"))`, instead of being stored as a plain string or having their own systems of serialization.

**Comment by windy1** [comment]
This is implemented in https://github.com/SpongePowered/SpongeAPI/pull/1079
