### ISSUE TITLE
Offering should fail with an error if the key doesn't apply

### ISSUE THREAD

**Issue by Techcable** [SpongePowered/SpongeAPI#1094]
Most programming languages throw exceptions if an operation doesn't apply to a type, especially if they don't have type safety.
Please throw an exception when `offer()` fails, as most programmers expect code to throw exceptions on failure.
If you _really_ don't want to deal with exceptions and you do want to ignore errors, you could add a `tryOffer()` method.
Code should _never_ fail silently, and java has exceptions for a reason.

**Comment by Zidane** [comment]
@Techcable 

I think you confuse the semantics of the term "offer" and "set". If this was ```set()``` I'd completely see your point. I do ask though how...

This:
```
try {
    something.offer();
} catch (I'mNotSureWhatException ex) {}
```

is better than...

```
DataTransactionResult result = something.offer();
if (result.blah) ...
```

The result method is superior in that offering data is no longer a "Did it succeed or fail?". Result allows you to see "Did some of the data succeed? If so, what failed?".

**Comment by Techcable** [comment]
@Zidane 
You may check if it can accept the key before you try to set it.
Code rarely checks the result of the 'transaction', especially if that is the default.
The code should throw an (unchecked) exception, and plugins should check if the key should apply if they think it might not apply.

The first one is better because it _forces_ code to handle errors (or check before).
Also, remember that exceptions are objects that can be filled with data about the error ;)

**Comment by Zidane** [comment]
@Techcable 

We do have https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/value/mutable/CompositeValueStore.java#L148 to cover checking the key beforehand so that isn't a valid argument.

I think we can both agree on your statement that we should force code to handle errors and we can even further compromise on a solution to this:

```
default DataTransactionResult set() {
    final DataTransactionResult result = offer();
    if (result.fail) {
        // Throw some data exception
    }
}
```

This would throw a data exception and that exception would contain the DataTransactionResult so you can query it to see what data failed.

**Comment by gabizou** [comment]
The primary reason why I decided against throwing exceptions is to avoid crashing a server, regardless whether it's in production or a test environment. It may be acceptable to *add* a set method that will throw an exception if the data is not supported, but offer is staying as it is.

**Comment by Techcable** [comment]
@gabizou 
Alright, its fine to keep the old one. I'd just rather have code to fail with an error than to fail silently.

**Comment by Zidane** [comment]
@Techcable 

Yours is a fair point and its simply enough to compromise with my above suggestion. We'll do so and both of us will be happy then :P.
