### ISSUE TITLE
Add Value API overloaded method for itemData() in ItemStack.Builder

### ISSUE THREAD

**Issue by DotDashh** [SpongePowered/SpongeAPI#1096]
Pretty much summed up in the title.

If not, I am requesting that there be such method in ItemStack.Builder:
`itemData(Keys<? extends BaseValue<E>> key, E value)`

That way it is easier to add say enchantments in one fell swoop.

**Comment by gabizou** [comment]
Duplicate of https://github.com/SpongePowered/SpongeAPI/issues/1093
