### ISSUE TITLE
A projectile can not be sourced to an entity that would not fire projectiles in Vanilla

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeAPI#1097]
There is currently no way to set a projectile's source to a entity which does not shoot projectiles in Vanilla Minecraft such as a Zombie.

**Comment by simon816** [comment]
That makes sense though, A zombie is not a projectile source so you can't expect a method like `zombie.launchProjectile` to work

**Comment by DarkArc** [comment]
That make sense in that scope, but if I throw a snowball from a plugin, and I want to say that Bob the evil Zombie did it, I can't. There's no way to establish that relationship. 

Annother place where this may happen is something adds a slingshot item for instance, and said slignshot item allows any mob to launch a projectile if held, there is no way to handle that relationship in Sponge right now.

**Comment by kashike** [comment]
I doubt every single mod entity that shoots projectiles follows vanilla's entity class structure, either.

**Comment by DarkArc** [comment]
Well I think @gabizou pointed out to me on IRC the other night, that Vanilla doesn't have a concept of ProjectileSource.

**Comment by gabizou** [comment]
The problem stems from most vanilla projectiles being hard coded to their expected sources, which in most cases is a `Living` entity. Mods may do this as well, but the likelihood that all projectiles support being sourced from any `ProjectileSource` in our API is varying based on the mods installed.

**Comment by simon816** [comment]
The thing is that marking a zombie as being the source is not really true. It's your plugin that's actually firing the projectile on behalf of the zombie so having a zombie projectile source doesn't work. You'd expect that a projectile source is able to fire projectiles, but as zombies can't do that then it's not the source.

**Comment by DarkArc** [comment]
@simon816 I don't really think ownership is quite that simple. Yes, my plugin is the creator, but as far as the game is concerned, and as far as any players know, the projectile shooter is the Zombie.
