### ISSUE TITLE
There should be non-center upright Directions

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/SpongeAPI#1105]
*SpongeAPI* is an API for *Minecraft*. In *Minecraft* there **26 neighbors** for a block, 6 away from the faces of the cube, 8 away from the vertices, and 12 away from the edges. The `Direction` class should represent this.

~~The secondary ordinal directions should be removed because it is **impossible** for a block to be something like **"NORTH_NORTHEAST" from a block**. They are also unused in SpongeForge, SpongeVanilla, SpongeCommon, and even SpongeAPI itself.~~ Edit: Seems like they are used indeed in item frames and other things.

Sideways up and down directions (vertex normal directions) should be added as a way to **describe blocks** next to another block that **isn't directly up or down**. It also allows creative voxel manipulation plugins (like *WorldEdit*) to use `GenericArguments.enumValue(Text.of("direction"), Direction.class)`. Edit: Also, secondary ordinal up/down directions should also be added for consistency that directions pointing up/down be as accurate as directions on a compass.

**Comment by simon816** [comment]
They _are_ used. For things like rotation - items in an item frame, skull tileentity head rotation etc

**Comment by gravityfox** [comment]
But I have to ask...

Why would you ever need this?

Could you provide a use case?

**Comment by liach** [comment]
Custom plugin that create tools that destroy connected blocks.

**Comment by kinggoesgaming** [comment]
@liach did you mean mods :P

**Comment by gravityfox** [comment]
I still don't see that as a valid use case.

Tell my why SPONGEAPI would have a use for those directions.

**Comment by CrystalMageX** [comment]
@gravityfox A use case would be, as described in the original issue, a worldedit plugin that accepts directions to be specified using chat, like `//expand halfup_northeast 10`, and have it processed easily using `GenericArguments.enumValue(Text.of("direction"), Direction.class)`.

> Tell my why SPONGEAPI would have a use for those directions.

SpongeAPI does not use *anything*. It is an API, it provides stuff for plugins to use.

**Comment by gravityfox** [comment]
Let me give you two different perspectives...

From a user perspective, `halfup_northeast` makes absolutely no sense to me, and I could never be bothered to type that out. i would just type `north`, `east`, and then `up`.

From a plugin dev perspective, If you really wanted to do something like that, you would be using your own command parser/engine, and you wouldn't be using generic arguments. Generic arguments is a general purpose convenient way of making commands. If you want to do something crazy and out there, do it yourself.

My conclusion is that this is just clutter in SpongeAPI and is mostly unhelpful. I need a REAL use case about how some random plugin dev can use this in a way that makes everything better for the user.

**Comment by CrystalMageX** [comment]
If you exclude the use of these directions in commands, then there isn't any actual use case. The other reason this should be implemented is to **add flexibility** to the API. Why is there only two upright directions, `UP` and `DOWN`, for the `NONE` direction instead of for all directions or none at all? The only apparent reason is that nobody bothered to add all 96 other ones. Why should we add them? Again, as described in the original issue, we should be able to **describe things** in Minecraft, and if  it's not possible it should be made possible, just like words are invented to talk about new things. Another use would be preparing `NotifyNeighborBlockEvent` for mods/Minecraft updates that update in a 3*3 cube instead of only the blocks adjacent to the faces.

> My conclusion is that this is just clutter in SpongeAPI and is mostly unhelpful.

Like any API, only pick the parts you need, and ignore the rest of the clutter. These new directions are just for **convenience and consistency**, to avoid the question from future developers: "How do I get a direction that points towards an upwards diagonal block???" Right now, if you pass in a upright vector, the `Direction` class gives you either the `UP` or `DOWN` direction, and that is *not accurate*.

**Comment by gravityfox** [comment]
SpongeAPI is an API for plugins to INTERFACE WITH THE UNDERLYING IMPLEMENTATION.
Those extra directions are not used in minecraft or forge or spongeforge or spongevanilla or anything really. There are a few exceptions like the EconService, but that arose due to the desire to not require a plugin like vault to exist.

FlowMath is part of sponge dependencies. If you really needed a special vector that badly, just make it yourself.

**Comment by wizjany** [comment]
From a user perspective, no one will ever type ``//expand halfup_northeast 10``. The usability of direction names like that is non-existent, no one will ever remember or type it. Instead, they will use ``//expand north,east,up 10``, because usability should be part of plugin design.

From a developer perspective, if I want a vector "that points towards an upwards diagonal block", the last thing I think of is "halfup_northeast". I would be more likely to add two simple, known vectors (``UP.add(NORTHEAST)``), or manually type out the directional components (``Vec3i(1,1,0)`` assuming I remembered MC axis directions, which I don't).

**Comment by gravityfox** [comment]
thank you wizjany for agreeing with me.

**Comment by CrystalMageX** [comment]
Closed this because there is no use for the proposed directions, and everyone doesn't seem to want it yet. Once a mod/version adds things that require these directions, then it can be re-opened.
