### ISSUE TITLE
add method spawn entity naturally

### ISSUE THREAD

**Issue by rexbut** [SpongePowered/SpongeAPI#1107]
Hi,
this is impossible to spawn a entity with the item (a bow for skeleton or a sword for wither skeleton)
Can you add a method to spawn a entity naturally ?

**Comment by rexbut** [comment]
SpongeCommon : https://github.com/SpongePowered/SpongeCommon/pull/526

**Comment by ST-DDT** [comment]
Having a flag/snapshot data tag for this would be nice. We definitly need both versions the raw and the natural one.

**Comment by ryantheleach** [comment]
What about a EntitySnapshot factory that could use the vanilla logic for creating the entity snapshot, giving the plugin the last say, with possible events firing so other plugins can make their modification to the entity being constructed?

**Comment by gabizou** [comment]
@Aaron1011 I remember we spoke about adding a new method to perform the additional "spawn naturally". Correct me if I'm wrong but that would be added as a new method, not merged into spawnEntity.

**Comment by rexbut** [comment]
I agree that would be better to create a new function

**Comment by Aaron1011** [comment]
@rexbut: Would you mind opening an API PR that adds that method (to go along with your SpongeCommon PR)?

**Comment by Zidane** [comment]
Closing as a PR now exists for this.
