### ISSUE TITLE
BlockRay Issue

### ISSUE THREAD

**Issue by mcglonelevi** [SpongePowered/SpongeAPI#1108]
Hello Sponge Devs,

I believe there is an issue with BlockRay.  Here is a video where I showcase my code and some weird behavior I am experiencing.  First of all, I cannot get the BlockRay to target anything but air.  Second, the block collision is not detected when standing really close to a block.  Here is a video showcasing my code:

https://www.youtube.com/watch?v=DZs-uU7T_t4&feature=youtu.be

Sorry for the lack of audio in the video.

**Comment by ryantheleach** [comment]
It would really help to see your code.

**Comment by mcglonelevi** [comment]
Thanks Ryan,

I will post my code when I get to my PC.  I know that it should return air, but the fact that it doesn't when I am close to another block is a little weird.  I think it is odd behavior, and I think BlockRay has an issue.

Levi

**Comment by mcglonelevi** [comment]
I should also mention that I was in the process of debugging, and that code was implemented to show some weird behavior that I was experiencing.

**Comment by mcglonelevi** [comment]
Here is a copy/paste of my code:

```
public class WitExecutor implements CommandExecutor {
    public CommandResult execute(CommandSource src, CommandContext args) throws CommandException {
        if (src instanceof Player) {
            Player player = (Player) src;
            Optional block = BlockRay.from(player).filter(hit -> { //Java 8 Lamda
                Extent extent = hit.getExtent(); //Get the extent from the ray hit
                Vector3i pos = hit.getBlockPosition(); //Get the block pos of the ray hit
                BlockType bType = extent.getBlockType(pos); //Get the type of block at the position
                return bType.equals(BlockTypes.AIR); //If it's air, exclude, otherwise its cool
            }).blockLimit(100).build().end();
            if (block.isPresent()) {
                BlockRayHit defBlock = (BlockRayHit) block.get();
                BlockType type = player.getWorld().getLocation(defBlock.getPosition()).getBlockType();
                src.sendMessage(Text.of("You are looking at a " + type.getName()));
            } else {
                src.sendMessage(Text.of("You are looking at the sky."));
            }
        } else {
            src.sendMessage(Text.of("Must be a player to use this command."));
        }
        return CommandResult.success();
    }
}
```

**Comment by ryantheleach** [comment]
`return bType.equals(BlockTypes.AIR); //If it's air, exclude, otherwise its cool`

should be 

`return !bType.equals(BlockTypes.AIR); //If it's air, exclude, otherwise its cool`

as for the other issue I'm not 100% sure what's happening.

**Comment by DDoS** [comment]
All of this behaviour is correct. The block ray only returns blocks that pass the filter test. If you only allow air, the last block returned will be the last valid air. The block ray also only returns blocks it entered. If you start in a block, it won't be returned because it was already entered before the block ray started. That's why you don't anything when using the only-air filter and standing right next to a wall.

What I need to add is an optional filter wrapper to extend an existing filter by a number of blocks after the last valid hit. This way you can create a filter `continueAfterFilter(onlyAirFilter(), 1)`, which will trace one more block after the only-air filter ends (that would return the first wall block).

**Comment by Minecrell** [comment]
@DDoS Wouldn't it be a good idea to keep this issue open or open another issue for that so that can be added for the next API release?

**Comment by DDoS** [comment]
I'm doing that today, so I'll remember.

**Comment by DDoS** [comment]
For reference, this was fixed in https://github.com/SpongePowered/SpongeAPI/commit/4818c96c069e843b9097732c6ccb75f076e52381

**Comment by mcglonelevi** [comment]
Thank you!
