### ISSUE TITLE
Value transform Optional

### ISSUE THREAD

**Issue by ewized** [SpongePowered/SpongeAPI#1109]
For the `Value#transform(Function<E, E> function);` should it be `Function<Optional<E>, E>` function this way we interact with an optional instead of null.

https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/value/mutable/Value.java

**Comment by gabizou** [comment]
You're guaranteed there's going to be a value... Why would it take an `Optional`?

**Comment by ewized** [comment]
The JavaDoc states it could be null.

**Comment by gabizou** [comment]
Then the javadoc needs to be fixed.
