### ISSUE TITLE
Food saturation/level drain event

### ISSUE THREAD

**Issue by jk-5** [SpongePowered/SpongeAPI#1124]
Currently there is no clean way to cancel the food saturation or food level going down. An event for this would be nice

**Comment by Rain336** [comment]
I think that's what `ChangeDataHolderEvent` is for.

**Comment by JBYoshi** [comment]
It's not implemented, though.

**Comment by Zidane** [comment]
Closing this as it is encompassed into ChangeDataHolderEvent.
