### ISSUE TITLE
Serializable BlockMatchers

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1130]
It would be good to have a universal class that can match against blockSnapshots.

By allowing it to be DataSerializable it will give users a common format to provide "blocks" to plugins that can ignore certain data values, ranges of traits, or even entity data.

**Comment by 20zinnm** [comment]
This would be extremely useful. +1

**Comment by ImMorpheus** [comment]
`BlockStateMatcher` is `DataSerializable` in api-8 

https://github.com/SpongePowered/SpongeAPI/blob/992ef50c171183070bede2d234379052613d830e/src/main/java/org/spongepowered/api/block/BlockStateMatcher.java#L45
