### ISSUE TITLE
duplicate mcmod.info files in plugin jar

### ISSUE THREAD

**Issue by kinggoesgaming** [SpongePowered/SpongeAPI#1134]
If I have a mcmod.info file in `src/main/resources` and then compile the plugin, the Plugin  <-> mcmod.info generator creates another mcmod.info file. Then results in 2 mcmod.info files in the resulting jar. 

![deepinscreenshot20160310155406](https://cloud.githubusercontent.com/assets/15664607/13692561/64e03ccc-e6f7-11e5-9063-0edbd0e48951.png)

I think this a job for @Minecrell?

**Comment by liach** [comment]
So you do not put one in resources.

**Comment by kinggoesgaming** [comment]
Consider it a request for that the generator first attempts to find the mcmod.info in resources... And if not found then generate it.

Gradle has built in functionality for resource filtering which is why I want this enhancement

**Comment by Minecrell** [comment]
Annotation processors have no access to resources, you'll either need to tell it manually where to find them or use SpongeGradle which automatically detects extra files in your resource folder.

For SpongeGradle: See https://cdn.rawgit.com/Spongy/SpongeDocs-PRs/02a9be94/plugin/project/gradle.html
For manual "telling the plugin annotation processor how to find it": You need to add a Java compile argument with the full path to your resource, e.g. `-AextraMetadataFiles=/path/to/mcmod.info`
