### ISSUE TITLE
SnapshotVolume for Schematic API usage

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#1137]
Currently, we have a pending issue for working on a proper Schematics API where by an interface is needed to extend `BlockVolume` and have the ability represent non-live `Entity` objects (possibly as alternates of `EntitySnapshot`s) and non-live `TileEntity` objects.

The limitation for both is that the `SnapshotVolume` (working name for now) cannot extend `Extent`. This is partially related to the #546 issue that has been sitting for a while now.

Some of the objects proposed needed for Schematics in general (And overall usability for plugin developers):

- `SnapshotVolume`: A volume that has blocks at coordinates, has a pseudo mutable `BlockSnapshot` like object at each position (optionally, as air is not represented)
- `FabricatedBlock`: A mutable `DataHolder` that has a `BlockState` and possibly `DataManipulator`s and a high possibility of directly supporting *current* NBT compound access and modification of `BlockEntity` information
- `FabricatedEntity`: A mutable `DataHolder` that has an `EntityType` and likely all related optional data to set on the entity (including inventory).

More to come as it is discussed.

**Comment by 20zinnm** [comment]
Can you reference the pending issue with the Schematic design? I'd like to get a feel for the format (if a sample is provided).

**Comment by 20zinnm** [comment]
Any update on this? It's critical to a plugin I'm writing. Might put a bounty on it.

**Comment by kenzierocks** [comment]
There's a spec if you look at the SpongePowered repos.

**Comment by 20zinnm** [comment]
I don’t need a spec, I need an implementation.

**Comment by gabizou** [comment]
> I don’t need a spec, I need an implementation.



> Any update on this? It's critical to a plugin I'm writing. Might put a bounty on it.

Patience is a virtue. It'll get done when it gets done.

**Comment by gabizou** [comment]
@20zinnm If you're up for it, give it a shot of writing up the `SnapshotVolume`, the premise would be of course that it has a bounds, adds a new sort of `BlockBlueprint` of sorts that has various info, such as the raw `DataContainer` for the tile entity information, the `BlockType`, and any relative `DataManipulator`s can be used (or optionally `BlockState would suffice)`. As it cannot be using a `Location` object, it must use a customized `Vector3i` for the position *relative to a certain point*. Likewise, the same treatment would have to be applied for `Entity` objects as they cannot be `EntitySnapshot`s. It may be possible to explore the `Inventory` suffice that there's a way to implement custom inventories for such things. 

Preferably you'd also use some sort of `BlockBuilderPalette` that is attached to said `SnapshotVolume` for key'ed blocks to positions, this way you can ultimately save space memory wise (and likely includes easing up the implementation on applying the volume since most blocks tend to need to be applied in specific orders).

**Comment by Deamon5550** [comment]
This was fixed with #1330
