### ISSUE TITLE
Add shouldDamageEntities to ExplosionBuilder

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeAPI#1140]
`ExplosionBuilder` should provide a `shouldDamageEntities` method to allow disabling entity damage.

**Comment by windy1** [comment]
Can't you just cancel the `EXPLOSIVE` `DamageType` to achieve the same thing?

**Comment by viveleroi** [comment]
I have no idea, and wouldn't have considered that has any impact. `shouldDamageEntities` is much clearer to a user and is consistent with the existing methods.
