### ISSUE TITLE
Teleporter and TeleporterTeleportCause

### ISSUE THREAD

**Issue by 20zinnm** [SpongePowered/SpongeAPI#1141]
For Nucleus to implement /back correctly, Teleporter and TeleporterTeleportCause need to be implemented. @gabizou I think it was something you were doing and forgot about :3. How long would it take to implement? I presume it's not a snap-fix but you never know!

**Comment by Zidane** [comment]
This is implemented fully in 1.8.9 :).

**Comment by 20zinnm** [comment]
Could you reference a PR? @Zidane

**Comment by gabizou** [comment]
@20zinnm there was no PR, there was a push in the implementation ;)
