### ISSUE TITLE
Support for serializing sections of the world to disk

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/SpongeAPI#1142]
We would like to add support for serializing sections of the world to disk. This issue is to gather comments on the layout of the data.

This is a mockup of the updated variant of the MCEdit scheamtic format, this variant would not be backwards compatible. The key changes here are the inclusion of a version tag to assist with future content updates and the inclusion of an id palette to both increase compression and allow a much larger range of block states. The format of the block state palette is mostly inspired from the 1.9 chunk data protocol.

The format is mocked out here in json although the preferred serialization format for this data would be NBT.

``` json
"Schematic": {
    "Metadata": {
        "Name": "my_schematic",
        "Author": "Deamon",
        "RequiredMods":[
            "a_mod",
            "another_mod"
        ],
        ...
    },
    "Version": 1,
    "Width": 1,
    "Height": 1,
    "Length": 1,
    "Offset": [0, 0, 0],
    "PaletteLength": 1,
    "Palette": {
        "minecraft:air": 0
    },
    "BlockData":[0],
    "TileEntities":[
        {
            "ContentVersion": 0,
            "x": 0,
            "y": 0,
            "z":0,
            ...
        }
    ],
    "Entities":[
        {
            "ContentVersion": 0,
            "x": 0,
            "y": 0,
            "z":0,
            ...
        }
    ]
}
```

### Usage
Usage of this format within sponge depends on #1137 and would likely consist of a Builder pattern of some sort.

**Comment by 20zinnm** [comment]
YES! Finally! I'm actually happy right now :smile:

**Comment by 20zinnm** [comment]
As for the Name tag, how about
```json
"Schematic": {
  ...
  "Info": {
    "Name": "The Magical Build",
    "Author": "AniSkywalker",
    "Date": "TIMESTAMP"
    ...
  }
}
```
Where everything in Info (and Info itself) is optional? It would then be loaded as an `Optional<Properties>` in a `Schematic` object. The builder could use a `.property("Name", "The Magical Build")` and we could then add an ENUM containing universally recognized properties.

**Comment by gabizou** [comment]
Some thoughts:
- What about possible version for the entity/tileentity tag information? Since 1.9 takes the precaution of upgrading the tags as it's being read from disk, I'd likely see that schematics for different versions of MC would eventually be supported as such. (this would likely require not a `"SchematicVersion"` but also a `"ContentVersion"` that is shared between Mojang's new content versions and future ones.
- This will likely need to be supported where snapshots of things can be recreated directly from the NBT formatted data, since after all, we're not trying to re-invent the wheel, but we'd likely need to do so regardless.

I'm sure that at some point, we'd want to get some input from the overall Minecraft community as well (probably shout out to some forge models using schematics and such).

**Comment by 20zinnm** [comment]
Is this _completely_ incompatible with the old Schematic format or is an automated conversion possible?

**Comment by Deamon5550** [comment]
@20zinnm Yeah having a generic `Metadata` compound tag would probably be a good way to handle it. Could use it to specify a lot of things like:
- Name
- Author
- URL
- Required Mods
etc.

**Comment by 20zinnm** [comment]
It would be completely independent from structure. You can store anything in there, and it will come back out as a Properties object.

**Comment by Deamon5550** [comment]
@gabizou Yeah a content version on all the entity and tile entity data would probably be for the best, especially with the DataFixer now.

@20zinnm Auto conversion from legacy schematics to this variant (and back again) are possible provided you have a mapping of block states to their original id + data value pairs.

**Comment by 20zinnm** [comment]
@Deamon5550 I can assume vanilla IDs because the old format only supported them, no? Or am I forgetting it.

**Comment by 20zinnm** [comment]
I'd like to see a website with the proposal in a separate repo (maybe just a GitHub site, it's not that big a deal) so we can submit PRs and discuss individual talking points.

**Comment by Deamon5550** [comment]
@20zinnm Yeah the legacy format just used the vanilla ids, of course in the presence of mods this was very fragile especially if mods are added/removed between the time of saving and loading the schematic.

**Comment by 20zinnm** [comment]
Make sure the implementations respect https://jd.spongepowered.org/4.0.3/org/spongepowered/api/data/key/Keys.html#PERSISTS

**Comment by 20zinnm** [comment]
I asked this in IRC but it should be a good question for here. So, let's say I want to make a T out of dirt. Forgive the terrible drawings, and assume the structure is made of dirt.
![T](https://s3.amazonaws.com/aww-imagedata/91e0f960-314e-43ea-a825-df31b9bda076.png)
That should come out to be this:
```
"schematic": {
    "metadata": {
        "name": "dirt_t",
        "author": "AniSkywalker",
    },
    "version": 1, 
    "length": 3,
    "width": 1,
    "height": 3,
    "offsetX": 0,
    "offsetY": 0,
    "offsetZ": 0,
    "paletteLength": 2,
    "palette": {
        "minecraft:air": 0,
        "minecraft:dirt": 1
    },
    "blockData":[0,1,0,0,1,0,1,1,1],
    "tileEntities":[],
    "entities":[]
}
```

I adjusted the names to follow the Google JSON standards + some misc. changes from IRC.

**Comment by Deamon5550** [comment]
@20zinnm The names are case sensitive so changing them in that way is not valid (and I'd rather they stayed in their current casing).

Your blockdata array is not quite correct as it should be using 1 bit per block packed tightly so your array would be `[0x4B, 0x80]`

**Comment by kenzierocks** [comment]
What happens when palette IDs break the byte limit (easily done with mods, maybe even vanilla)? As you stated, the block data is stored as a `byte array` that is `width * height * length`, so there wouldn't be room for such a large ID.

**Comment by Deamon5550** [comment]
@kenzierocks The indices are not stored directly in a byte array but are packed tightly using and many (or as few) bits as needed, the palette can therefore expand infinitely.

**Comment by kenzierocks** [comment]
So the entries in the array are not the same as the index in the array, ok.

**Comment by modwizcode** [comment]
Just tagging myself so I this gets flagged as participating @modwizcode

**Comment by Deamon5550** [comment]
I've placed a draft of a more formal specification [here](https://github.com/SpongePowered/Schematic-Specification/blob/master/versions/schematic-1.md).

**Comment by skinny121** [comment]
Khroki/MCEdit-Unified#341 is the MCEdit feature request about a schematic format that support block names.

**Comment by gravityfox** [comment]
I would like to make a feature request to this.

Inscrutable and I had been discussing the idea of a "null" block. Essentially what it means is that for all intents and purposes, that particular block position is ignored.

So when you paste a schematic somehow, null blocks are just ignored, but air blocks are actually placed.

In the past, pasting a schematic could carve out sections of your world with air blocks, which was undesirable, or leave terrain inside of buildings, where air is supposed to be, which is also undesirable. It would be nice to be able to say in a schematic to explicitly include the air block, or just leave that space alone.

A use case of this is a schematic for an underground bunker. You want the schematic to explicitly include the air blocks INSIDE the bunker, but not include the blocks outside of it. That way when you paste, the inside would be open with air blocks, and the outside would be whatever terrain was already there.

I'm not entirely sure what the best way to implement this is, but it would be VERY useful to have.

**Comment by gabizou** [comment]
In the implementation, it is very easy to not apply a block state if there is no data to apply in the first place. What could be interesting is the idea that it'd be supported in the schematic specification @Deamon5550 already wrote up. Whether a Schematic applies air blocks of not can be a simple Boolean flag for the specific API methods.

**Comment by Deamon5550** [comment]
yeah I like the idea, I'll look at what we can do to the spec

**Comment by gravityfox** [comment]
That might not actually be enough though. The point is that in a schematic, there might be certain blocks that MUST be air. Whereas there are others that can be whatever was already there in the first place. I was thinking we could just reserve block id 0 as the null block, and allow air to take up like id 1 or something.

**Comment by Deamon5550** [comment]
I was just going to add a null entry to the palette. It should be that simple.

**Comment by gravityfox** [comment]
that sounds great. Thanks :3

**Comment by gabizou** [comment]
@gravityfox Yeah, the idea is that you could trim the schematic yourself (if a visual GUI application was developed to display the difference between air blocks and null blocks, or simply to visually represent the schematics themselves). The issue with *creating* schematics with trimmed area is when you want to specifically state that say a specific range (or volume) of air blocks are "irrelevant" or "unneeded". At the end though, the implementation should very well be capable of accepting `null` blocks for specific positions where the current block that resides at the location will remain.

**Comment by gravityfox** [comment]
Right. And that trimming mechanism is something I will have worked out. I just need a way in the schematic spec to differentiate between the two.

**Comment by Inscrutable** [comment]
I have a few questions:
* Is the plan to use the new .schem format in future versions of _WorldEdit_ for Sponge?
* Will Sponge or _WorldEdit_ contain methods for converting to & from legacy .schematic files?
* Can this be extended to cover the .BO3 objects used by _TerrainControl_? (They'd have to add it on their end if they wanted to use it, but we could, in theory, import BO3's).
* To properly create, view, and understand the new .schem objects, new 3rd-party plugins/mods/software will be needed (especially for ones using _null_ blocks). What can we do to fulfill that need?

**Comment by Deamon5550** [comment]
> Is the plan to use the new .schem format in future versions of WorldEdit for Sponge?

Up to them

> Will Sponge or WorldEdit contain methods for converting to & from legacy .schematic files?

Sponge will

> Can this be extended to cover the .BO3 objects used by TerrainControl? (They'd have to add it on their end if they wanted to use it, but we could, in theory, import BO3's).

We can import them for the purpose of conversion to schematics

> To properly create, view, and understand the new .schem objects, new 3rd-party plugins/mods/software will be needed (especially for ones using null blocks). What can we do to fulfill that need?

Yeah 3rd party tools won't support this format without updating, hopefully some level of adoption/PRs can aid this.
