### ISSUE TITLE
Entity collision filtering

### ISSUE THREAD

**Issue by SupaHam** [SpongePowered/SpongeAPI#1143]
Preface: I'm very ignorant with Sponge, so please excuse any mistakes made in this ticket.

# Introduction

As of the time of writing, I believe SpongeAPI provides a few events that involve entity collision. Regardless, I am writing this issue to provide a different view of how entity collision might be better handled.

Currently, listening to CollideEvent/CollideEntityEvent should provide the functionality for what is proposed here.

If one is to want to disable all collision for one Entity, they must do something along the following lines:
```java
private Entity entity;

public void setEntity(Entity entity) {
    this.entity = entity;
}

@Listener
public void onCollide(CollideEntityEvent event) {
    Entity eventEntity = event.getOriginalEntities().get(0); // This assumes get(0) is our "pushing" entity.
    if (eventEntity.equals(this.entity)) {
        event.setCancelled(true);
    }
}
```

Functionality wise, it might be reliable, though I'm not sure about get(0).

However, it could be made more efficient in writing where each entity holds **collision filter data**.

# Proposal

**Filters**. I'm not sure if there's some sort of filter API in Sponge, but the key behind this whole idea is filters for entities. The Entity would hold a data object that stores a collection of filters which determines whether an entity meets the requirements for collision or not (represented via boolean).

The collection would only need to meet one `true` value when invoking filters in order for it proceed with collision code.

The following block of code is the `EntityFilter` type which is simply a `boolean`-returning function. This is what the `CollisionFilters` data class would be utilizing:

```java
public interface EntityFilter {
    /**
      * Return true to collide, false to terminate collision code.
      */
    boolean test(Entity pusher, List<Entity> entities);
}
```

The following code creates an `EntityFilter` which always returns false, meaning the pushing entity will never collide with any other given entity.

```java
public void setEntity(Entity entity) {
    // ...
    this.entity.getOrCreate(CollisionFilters.class).get().add( (e, el) -> false )); // always disable
}
```

The following would disable collision with pigs:
```java
public void setEntity(Entity entity) {
    this.entity.getOrCreate(CollisionFilters.class).get().add((e, el) -> {
        return !el.stream().anyMatch(e2 -> e2 instanceof Pig);
    });
}
```

When a collision is about to occur, the `EntityFilters` are called first prior to any collision processing, if all entity filters fail to return `true`, then all collision code is terminated. However, if one returns true, then the code proceeds onto event triggering, and so on.

Needless to say, this opens up possibilities to create a mini library of EntityFilters that makes it easier to combine certain filters together.

**Disclaimer**: As mentioned before, limitation wise, there's no discussion. However this makes writing collision handlers more focused on entities themselves rather than listeners then the entities themselves.

**Comment by Zidane** [comment]
I don't really see any advantage over just listening and cancelling event appropriately.

Also, the entities in CollideEntityEvent are who you are colliding with, the source doing the colliding is in the Cause. There is a filter method on the event that would do what you want.
