### ISSUE TITLE
Vague usage of Keys.INVISIBLE

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#1151]
A few things to state:

- `Keys.INVISIBLE` is meant to render the entity completely invisible. Completely invisible such that packets are not sent to players for the invisible entity, sounds are not played, particles aren't spawned, etc. The reasoning why it calls the internal `setInvisible(boolean)` is to maintain compatibility with not only vanilla functionality, but also mod compatibility.
- Mojang's invisibility is a boolean toggle, but it should be treated separately in my opinion, not where it's called `INVISIBLE` but some other functional word that will relate that the entity is not *completely* invisible, but only *rendered* invisible.
- Changing the functionality where `Keys.INVISIBILITY` doesn't completely render the entity invisible with packet/particle/sound handling is a breaking change, even though the API doesn't actually break, the intended behavior does break with various plugins, such as @mbax's Vanish plugin. So, if anything, the choice of changing the implementation of `Keys.INVISIBILTY` to only call the internal method, and `Keys.VANISHED` performs the current functionality would have to go into the `bleeding` branch of the API and implementation.
- @modwizcode There's no real issue, it's intended functionality as the javadoc states, and as Bukkit's previous implementation used. 

I'm open to suggestions on whether a change of the key's name is decided or whether an addition of an alternative "simple invisibility" key is added.

**Comment by gabizou** [comment]
@clucky I'm pinging you here as you're the original poster having the issue.

**Comment by modwizcode** [comment]
I agree that any changes to this would be breaking. @gabizou I am somewhat
confused by your response, which outcome are you looking to see? I can tell
you that I myself need the separate type of invisibility to be added.

**Comment by kashike** [comment]
The existing functionality of `INVISIBILITY` should be moved to `VANISHED`, and `INVISIBILITY` to handle things like armour stands.

**Comment by simon816** [comment]
(reposted)
I would just like to point out that complete invisibility was never the intention of InvisibilityData. I can only assume that at some point the definition was changed (not in writing? I don't remember this)
Before the data API it was simply a boolean render toggle
https://github.com/SpongePowered/SpongeAPI/blob/2046c95cb1fb689133f9bd7f2d110cce112d5546/src/main/java/org/spongepowered/api/entity/living/Living.java#L285-L316
Which I believe would toggle a particular bit in the entity metadata (http://wiki.vg/Entities#Entity_Metadata_Format)

Then when DataAPI 1.0 came out InvisibilityData still seemed to reference 'rendering' invisible only https://github.com/SpongePowered/SpongeAPI/blob/c2da2f690f590f7c1c428d8bfc3fc22279fdb9a0/src/main/java/org/spongepowered/api/data/manipulators/InvisibilityData.java

Even today in dataapi 2.0 it still mentions rendering
https://github.com/SpongePowered/SpongeAPI/blob/6a975e7d97d8f523905a880ef85cdb53f4d25761/src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/InvisibilityData.java#L34

I assume that one day it was changed and no proper replacement for the existing functionality was added

**Comment by clucky** [comment]
I would like to mention that having `Keys.INVISIBLE` referencing the preventation of rendering would be confusing to many, being that is the name of the key which Minecraft uses. `Keys.VANISHED` would be far less confusing as a naming convention, or better yet `Keys.UNRENDERED`.

**Comment by mbax** [comment]
`Keys.DISAPPEAR`
`Keys.UNTRACK`
`Keys.REMOVE_FROM_CLIENT`
`Keys.CLIENT_HIDE`
`Keys.HIDE`

**Comment by ryantheleach** [comment]
>I would like to mention that having Keys.INVISIBLE referencing the preventation of rendering

I believe you mis-read Gabizou's post.

> Mojang's invisibility is a boolean toggle, but it should be treated separately in my opinion, not where it's called INVISIBLE but some other functional word that will relate that the entity is not completely invisible, but only rendered invisible.

**Comment by modwizcode** [comment]
`Keys.RENDER_HIDDEN`? That seems to summarize fairly well what people would expect from a client side invisible entity. I think we should leave `Keys.INVISIBLE` as is. Unless someone feels strongly that `Keys.VISIBLE` is truly a required change to establish clearly the meaning of the `Key`

**Comment by randombyte-developer** [comment]
I suggest `INVISIBLE` behaving like the vanilla entitydata and `VANISHED` the no-packets-sending invisibility. Until there is a way to achieve the vanilla behavior through the api I have to use [this workaround](https://github.com/randombyte-developer/holograms/blob/c632eac552fbb671c2dd1e2defd924c9edcc84bc/src/main/kotlin/de/randombyte/holograms/Hologram.kt#L68) which itself uses a workaround.

**Comment by JBYoshi** [comment]
I also prefer `VANISHED` for packet hiding. However, I'd probably go with `HIDDEN` for sending packets but not rendering.

**Comment by clucky** [comment]
I like `vanished` as well. I agree with @randombyte-developer though, in that standard invisibility should be left as the vanilla name `invisible`. Sponge is confusing enough as is (Think InventoryAPI), let's not make it worse.

**Comment by gabizou** [comment]
Closing with https://github.com/SpongePowered/SpongeAPI/commit/55296c12edc804a64009379d20b6779e1fe71147

**Comment by Yeregorix** [comment]
I got a question, when a player is using gamemode 3, he is just invisible or vanished ?

**Comment by ZephireNZ** [comment]
@Yeregorix AFAIK the player isn't vanished, because the client still hows the player name in italics it must also know about the player - hence it is not vanish. Looking at the game's source seems to confirm this, as it tells all connected players that the player is in spectator mode,

**Comment by Aaron1011** [comment]
As @ZephireNZ said, spectator invisibility, as well as other features, are handled specially through the gamemode set in the tab list.
