### ISSUE TITLE
[Discussion] OptBool vs Tristate

### ISSUE THREAD

**Issue by liach** [SpongePowered/SpongeAPI#1153]
Currently there are two classes available in Sponge's utilities that seem to have duplicate usages. They are `[org.spongepowered.api.util.OptBool] `(https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/OptBool.java) and `[org.spongepowered.api.util.Tristate] `(https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/Tristate.java). May we merge these two? I suggest to retain `Tristate` since it is more detailed and more useful.

EDIT: Somehow I messed up the link... Hope some devs could fix the link.

**Comment by kashike** [comment]
:-1: 
`OptBool`:
> This also saves memory by holding three static instances of {@code Optional&lt;Boolean&gt;} which represents the possible states it can have.

**Comment by Minecrell** [comment]
They're separate on purpose, `Tristate` works differently from OptBool and these are used in two different contexts: Permissions (Tristate) and OptBool (Text styles), which have different behaviour for the `and` method for example.

**Comment by modwizcode** [comment]
I don't see the value of the use of `OptBool` as we use it, currently it seems we just use it as a false value in `TextStyle` so that `TextStyles` can use null instead of false. As usual I tend to miss the obvious, but how are we benefiting from using an `OptBool` instead of a simple boolean?

**Comment by Minecrell** [comment]
@modwizcode It's not. There is a clear difference between `false` and `null` in this case, as shown by the [field names in OptBool](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/OptBool.java#L41-L57). Null is equal to `ABSENT` which means the `TextStyle` does not define whether it is **bold** or not for example.

Texts are entirely independent from each other, so if you have a root `Text` object which has the style `bold = TRUE`, then all children texts will be bold, except for those that have `bold` explicitely set to `FALSE`.

As I said, `OptBool` works differently in `TextStyle` from `Tristate`, therefore we can't easily combine them.
