### ISSUE TITLE
Event for left clicking in air

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1161]
As described [here](https://forums.spongepowered.org/t/leftclickevent-in-air/12047) I would like to have a left click in the air event. :smiley:

Thanks!
RandomByte

**Comment by kashike** [comment]
Duplicate of https://github.com/SpongePowered/SpongeForge/issues/480 and https://github.com/SpongePowered/SpongeAPI/issues/1054

**Comment by randombyte-developer** [comment]
Thanks

@Zidane Hoping this is in work. 😀

**Comment by kashike** [comment]
...this should be closed, it's a duplicate.
