### ISSUE TITLE
NotifyNeighborBlockEvent should use Positions not Directions

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/SpongeAPI#1163]
The [`NotifyNeighborBlockEvent`](https://github.com/SpongePowered/SpongeAPI/blob/f2f7a9cf58fb9b3796dcb4da337ad961ba672488/src/main/java/org/spongepowered/api/event/block/NotifyNeighborBlockEvent.java#L32) event uses `Directions` to specify which block was changed. The `net.minecraft.block.BlockSponge` block updates neighbors up to **7 blocks, taxicab in each direction**! The `Direction` class, which only supports up to 6 directions in each face, is not enough to determine which block the event is referring to.

Possible solutions would be:
- Replace the `Direction`s with `Locations`s.
- Replace them with relative `Vector3i`s.
- Replace them with absolute `Vector3i`s.

**Comment by gabizou** [comment]
I count 6 blocks getting notified:

1) `NORTH`
2) `SOUTH`
3) `EAST`
4) `WEST`
5) `UP`
6) `DOWN`

Where is the 7th?

**Comment by phroa** [comment]
Maybe counting `Direction.NONE`?

**Comment by CrystalMageX** [comment]
I meant any blocks in the 8 by 8 by 8 octahedron [(2d example)](http://minecraft.gamepedia.com/File:LightEmittingBlocks.png) surrounding the sponge can be notified, up to **65 blocks max**, **512 blocks** to describe, and would be affected if it wasn't restricted by Mojang.

Videos:

- https://youtu.be/EGVDB_qHZtw?t=39s
- https://youtu.be/p8CI7AcH3h4?t=34s

Wiki:

- http://minecraft.gamepedia.com/index.php?title=Sponge&oldid=957301#Usage

Source Code:

- `mcp/src/minecraft/net/minecraft/block/BlockSponge.java:97` (Restrict to 7 blocks away)
- `mcp/src/minecraft/net/minecraft/block/BlockSponge.java:104` (Restrict to 65 blocks total)
- `mcp/src/minecraft/net/minecraft/block/BlockSponge.java:112` (Update neighbor blocks)

**Comment by ryantheleach** [comment]
Maybe some refactoring is needed then, I find it hard pressed to call blocks updating further then immediately next to the block a neighbour.

Parent event/interface that has the position of the block updating (NotifyBlockEvent), making notifyNeighbour a sub event?

Or remove notifyNeighbor in favour of the other event?

**Comment by gabizou** [comment]
So, having worked on block notifications yesterday in the cause tracking refactor, I can safely say that the event is intended for when blocks simply tell the world to notify neighbors at a certain position. In a sense, this is a pre-notification event to determine whether the blocks will be notified and their logic is processed.

Having that said, possibly the javadoc should be clearer?

**Comment by ryantheleach** [comment]
The problem is though, is that BlockSponge changes the nearby blocks, and then notifies all the blocks it changes.

If you cancel the sponge changing the water to air, how do you then prevent the sponge from updating that water source if you can't tell what block is being notified?

>the event is intended for when blocks simply tell the world to notify neighbors at a certain position.

So this even shouldn't belong to sponges, and a new event for blocks updating a block at a distance needs to be made? Or that this is the correct event, it just needs an added field or something?

**Comment by gabizou** [comment]
@ryantheleach Again, for each block position the sponge is changing to air, the world is still being told to notify neighbors, which evidently is going to throw the `NotifyNeighborBlockEvent` for *that specific block position* (again, all the block positions that the sponge has changed water to air). That being said, `NotifyNeighborBlockEvent` is not a `ChangeBlockEvent` but determines whether other blocks are neighbor notified. For the supposed up to 64 blocks being changed by a sponge, you'll end up getting 64 individual `NotifyNeighborBlockEvent`s thrown for the 64 positions.

**Comment by ryantheleach** [comment]
Yeah, sorry I understand now.

@CrystalMageX It's not that the sponge block is notifying the water/surrounding blocks, but is triggering the water/air to notify it's neighbours.

What needs to happen is to cancel the updates of those neighbours, if the cause was the sponge block, as opposed to cancelling neighbour notifies originating from the sponge block.
