### ISSUE TITLE
Command usage displayed incorrectly

### ISSUE THREAD

**Issue by Flibio** [SpongePowered/SpongeAPI#1165]
Command arguments for sub-commands do not display at all in the help message when a user types in a sub-command without the required arguments. A detailed explanation can be found below.

Command `/main` has a sub-command `set`. The sub-command `set` has a required argument, called `arg1`. Running `/main set`, without submitting the required argument, displays an unhelpful usage message: `Usage: /main set`. It fails to display the required argument, `arg1` in the usage message.

The command was created by implementing the `CommandExecutor` and registering a `CommandSpec`.

**Comment by liach** [comment]
How does a `SimpleDispatcher` work? Does it work incorrectly in the same way?

**Comment by dualspiral** [comment]
In the latest SF for API 7 snapshot, I've added method `childArgumentParseExceptionFallback` to the `CommandSpec`. You need to set this to `false` to get the behaviour you expect above, I opted to make this a non-breaking change for API 7.
