### ISSUE TITLE
Fake Book GUI & Book Builder

### ISSUE THREAD

**Issue by clucky** [SpongePowered/SpongeAPI#1167]
Sponge currently implements an Inventory API, which as you know can be used to open a custom inventory (possibly created by a plugin) on the player's screen. This idea would be very similar to that, except using the Book GUI instead, and instead of a custom inventory, allow for a custom book (created by a plugin). One of the many benefits of this feature would be **the ability for help commands to be shown from a plugin onto a player's screen, without spamming their chatbox** (which should be used for chat/notifications). I'm not entirely certain if this could be done, or how, but it has been done in the past by CanaryMod (Reference CanaryMod/api/inventory/helpers/BookHelper).

The idea would be similar to CanaryMod's way of doing it. You would essentially first supply the Book builder with a Text object (or several text objects, a new one for each page), the Text would be converted into a book-friendly format (word wrapping). Sponge would then take that built Book object, generate a temporary book, force a client to open the book, and then remove the book (which would keep the GUI open still on the client-end).

Although it would be ideal for the book to be forced to open on the client, if it isn't possible, I would still like to see the ability to create a book using some form of builder, which would take into account word wrapping, new pages, etc.

**Comment by windy1** [comment]
This was surprisingly really easy to implement. You can check out the API at https://github.com/SpongePowered/SpongeAPI/commit/96fc5773d9515149a372b665e22e74c84e088021 and implementation at https://github.com/SpongePowered/SpongeCommon/commit/682b6345373c8d76f06a23ba3f189853c1b6ee8e.

The way it works is relatively simple.

* Send a "fake" book item stack to the player's hand with the `BookView` contents and author
* Send a custom payload packet to the client telling it to open the book UI for the currently held item
* Remove the fake book from the player's hand

The best part is you can't even tell the fake book is added, it's not even visible to my eye at least. There might be a flicker or something but I couldn't notice it.

**Comment by clucky** [comment]
Thanks for the addition @windy1 :smile:

**Comment by windy1** [comment]
No problem! I would like to also explore the possibility of sending a `PaginationList` as a `BookView` in the future.

**Comment by clucky** [comment]
That would be awesome!
