### ISSUE TITLE
Custom Data Factory

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#1168]
It should be possible at this point to provide a class factory that will create given a certain set of parameters (or simply using a manipulator generator blueprint of sorts) to have Sponge generate a custom class with some unique identification that gives minimal code base requirements from plugin developers. Effectively, this can eliminate the need altogether for plugin developers to need to create at least 3 classes for each custom data themselves.

What it could look like:
```java

public class MyDataStuff {

  public static final Key<Value<String>> FOO = KeyFactory.create(String.class, Value.class, DataQuery.of("myData"));

  public static Class<? extends DataManipulator<?, ?>> MUTABLE_FOO = CustomDataGenerator.builder()
    .id("FooData")
    .withString(FOO)
    .version(1)
    .create(PluginClass.getInstance());
  public static Class<? extends ImmutableDataManipulator<?, ?>> IMMUTABLE_FOO = CustomDataGenerator.immutableOf(MUTABLE_FOO);
 
}

```

The only issue of course is that usability of the manipulator as a class itself is completely useless since it's type erased to a wild carded class. The advantage is that what takes 3 lines of code from a developer is all it would take to get started using custom data relatively easily.

The disadvantage of this all is that of course the plugin would not be able to see the data class itself, unless in the implementation. 

My idea is that the class name generated itself would utilize the plugins' id as a root and the ending being retrieved from the id provided though the generator.

I'm hoping that the community could see this for what it is as an addition and not a replacement of some serious custom data.

A note: The generator would only be able to accept some default serializable/supported objects like primitives, strings, and potentially other `DataSerializable`s.

**Comment by gabizou** [comment]
Pinging @Aaron1011 and @viveleroi as I've seen both to have some potential interest in such a thing being discussed.

**Comment by viveleroi** [comment]
I think this would be great. It's still a bit lengthy for situations where we're only storing a boolean or a single primitive value but it's quite a lot better than the three class files I had to a) learn and b) implement just to store a single boolean. Not only is this example more compact but it's a lot more understandable.

**Comment by gabizou** [comment]
@viveleroi The only loss here though is that the factory will not be able to provide you with a nice generic class to use with data manipulators themselves. The fortunate part is that you'll still be able to generate the generic keys to interact with that way.

**Comment by kashike** [comment]
@gabizou `withString`? Why not just `string`? No other builders use `with`, and it'll be weird to start doing so

**Comment by gabizou** [comment]
@kashike leave the nit picking of method naming when it's actually being PR'ed ;)

**Comment by simon816** [comment]
Yes. This is a good idea. I was thinking about something like generating the classes when I was doing a bit of refactoring to the data processors.

**Comment by gabizou** [comment]
@simon816 It's something that can be done for simple custom data, but for supported vanilla data, class generation is definitely not the way we want to go about it due to tracking potential issues.
