### ISSUE TITLE
@Command annotation system (on top of existing, lower-level, command API)

### ISSUE THREAD

**Issue by vorburger** [SpongePowered/SpongeAPI#1171]
I hope it's OK if I open this ENHANCEMENT ticket for a new discussion about a @Command annotation system in the Sponge API?

Apparently there were previous takes on this, I've found https://github.com/SpongePowered/SpongeAPI/issues/276 and https://github.com/SpongePowered/SpongeAPI/pull/561, both closed - yet still nada.

This does seem to be something people want - via a quick search I've found 4 (!) different separate outside implementations of this idea, see:

1. https://github.com/sk89q/Intake (@sk89q is that for Sponge? or do you have something else somewhere to use Intake with Sponge?)

2. https://github.com/minnymin3/Directive/ from https://forums.spongepowered.org/t/directive-a-light-weight-annotation-based-command-system/8325

3. https://github.com/WesJD/CommandManager from https://forums.spongepowered.org/t/commandmanager-an-annotation-based-command-system/11529

4. my very own https://github.com/vorburger/SwissKnightMinecraft/tree/ad5954212cc4f1bda3596d13db2e53a6d3ebb3f3/SpongePowered/MyFirstSpongePlugIn/src/main/java/ch/vorburger/minecraft/command (WIP, NOK)

At the very least, perhaps the Sponge documentation could... say something about this? As in "Planned, watch (this ticket?)" or "We'll never, but perhaps you would like to use (sk89q/Intake, with usage example?)"

**Comment by kashike** [comment]
Intake is quite good, I'd be :+1: for including it (or a modified version) in SpongeAPI.

**Comment by kenzierocks** [comment]
I'd love to have a non-annotation based option, personally I think annotations are too much magic w/ commands and also can't be configured easily by a config file.

**Comment by JonathanxD** [comment]
I'm implementing my own Command API https://github.com/JonathanxD/WCommands/, but i need to finish javadoc first.

**Comment by ryantheleach** [comment]
>I'd love to have a non-annotation based option

Isn't that what we already have?

**Comment by me4502** [comment]
I agree with the inclusion of Intake. The way it's written means that it'd be super easy to implement.

**Comment by zml2008** [comment]
Currently we've pointed people towards Intake, and I think some people have done glue work for it, though it might make sense to support annotated commands in Sponge's commands API at some point as well. Directly including Intake into sponge is probably not a good idea though -- we have argument handling code for Sponge's commands API already and Intake has its own argument parsing system. It would probably be easiest to set up an annotation system that builds on top of the existing argument handlers in Sponge.

**Comment by jamierocks** [comment]
I might make a pr based on my work with https://github.com/jamierocks/Zinc

**Comment by zml2008** [comment]
That's a good start and definitely going in the right direction, but I'd prefer that any command handling system would do more to apply argument parsers to specific method arguments (similar to what Intake and ToHPluginUtils do).

**Comment by Zidane** [comment]
Closing this as its a part of @jamierocks 's PR:

https://github.com/SpongePowered/SpongeAPI/pull/1186
