### ISSUE TITLE
BlockState command element

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#1174]
Since `BlockStates` are given ids (e.g. `minecraft:dirt[snowy=false,variant=grassless]`) by Sponge, it would be nice to have a `BlockState`-specific `CommandElement`.

The command element could also support tab-completion of the properties of the `BlockState`. In the example above, a user would be able to tab complete the property names (e.g. `snowy`) and the property value, if the type has a fixed number of values (boolean or `Enum`).

**Comment by Aaron1011** [comment]
Pinging @zml2008 for feedback.

**Comment by Zidane** [comment]
@Aaron1011 This is un-needed as BlockState is a CatalogType and that element already exists.

**Comment by ryantheleach** [comment]
I think it was more a issue to create one specific to blockstate that had handling for tab completion of traits.

**Comment by Aaron1011** [comment]
Yes, @ryantheleach is correct.

**Comment by gravityfox** [comment]
Just a bit of feedback. tab-completing traits is going to be a PITA if you really want to do it. MC client replaces everything connected to the current string, which means your tab completion is going to look really ugly really fast.

**Comment by Aaron1011** [comment]
Even if tab completion won't work out, it would be nice to have something which at least parses a string like `minecraft:dirt[snowy=false,variant=grassless]`

**Comment by gravityfox** [comment]
I will agree with that.

It would also be really nice to be able to look at a block, and have tab completion insert that block state.

**Comment by ryantheleach** [comment]
> This is un-needed as BlockState is a CatalogType and that element already exists.

There was talk in a different issue that BlockState's Shouldn't be a CatalogType? Just because of the sheer number of them?

Experimentation needed, but Brigadier may make this crazy easy.

**Comment by gabizou** [comment]
Pretty sure the fuzzy matching to auto completion on block state properties is the end goal, but seeing as 1.13’s auto completion already handles this, it will be exposed. 

@ryantheleach they shouldn’t be cataloged as fields, because there’s over 7 Thousand last I counted. But BlockState will always be a first class citizen of CatalogType.

**Comment by ryantheleach** [comment]
Yeah that makes sense and removes my confusion, thanks.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/commit/e086c46c6cddbbcd7f0444a7718caaf9b8f82eb3
