### ISSUE TITLE
Make a command element with broader testing than permission

### ISSUE THREAD

**Issue by Katrix** [SpongePowered/SpongeAPI#1177]
Currently you can set a specific command element to require a specific permission. This is fine for most cases. Sometimes however you might want to do some test that depends on the return value or the source. What I'm proposing is that you can pass a `BiPredicate<Object, CommandSource>` to a `CommandElement` wrapper in that same way as is done with permissions at the moment.

Using this you could for example test permissions for the player in relation to return value. You could also use it to disallow selecting yourself for commands taking a player.

So an actual use of this could look something like this:

``` java
CommandSpec.builder()
                .arguments(GenericArguments.testValue(
                        GenericArguments.player(Text.of("player")),
                        (obj, player) -> obj != player))
```

The reason I think this would be useful is that it would move permission checking away from the executor when using `CommandSpec`. Let's say that we have a command that lets the user force a target to use the command. The permission check is done for the user, not the target. However, if some permission checks were done in the executor, checking the permissions using `testPermission` wouldn't do all the tests required.

**Comment by dualspiral** [comment]
This will be available in API 8. 

https://github.com/SpongePowered/SpongeAPI/blob/0520f48b05bc026c083f490991cdf3a39fd58cbf/src/main/java/org/spongepowered/api/command/parameter/Parameter.java#L911-L939
