### ISSUE TITLE
Add item despawn time data

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1179]
Add an item despawn time data like the [old method](https://github.com/SpongePowered/SpongeCommon/blob/3def9ccc172b312b81a0677386a5b8a8105d6dd9/src/main/java/org/spongepowered/common/mixin/core/entity/item/MixinEntityItem.java#L138). Also support undespawnable items.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/1197
