### ISSUE TITLE
MessageChannel.combined is no such thing

### ISSUE THREAD

**Issue by EliterScripts** [SpongePowered/SpongeAPI#1185]
As I am developing my code, my IDE (Eclipse) tells me that there is no such method as "MessageChannel.combined". I am using SpongeAPI 4.1.0-SNAPSHOT; here is my code: https://github.com/EliterScripts/AnnouncerPlus more specifically, here is WHERE the issue is in my code: https://github.com/EliterScripts/AnnouncerPlus/blob/master/main/com/gmail/eliterscripts/MainPluginFile.java#L103 (please ignore the "..." part of that line, I know it's not correct in Java, but you get the point).

If I was the one who screwed up: you should probably take another look at the docs page for this ( https://docs.spongepowered.org/master/en/plugin/messagechannels.html ) and possibly change it.

**Comment by kenzierocks** [comment]
I don't know what you're doing wrong, because here is `MessageChannel.combined`: https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/channel/MessageChannel.java#L90. You must not have the latest snapshot.

**Comment by EliterScripts** [comment]
I have tried 4.1.0-20160312.230259-5 as well.

**Comment by kenzierocks** [comment]
Have you re-imported from the POM? Eclipse doesn't magically update when the `pom.xml` changes.

**Comment by EliterScripts** [comment]
I hit  maven -> update project
selected "Force Update of Spapshots/Releases" (keeping the other options as-is by defaults)
hit "ok"

**Comment by kashike** [comment]
The `combined` method certainly exists: https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/channel/MessageChannel.java#L82-L104

**Comment by EliterScripts** [comment]
I had to define a variable as static before it worked. The docs need to change.

**Comment by kashike** [comment]
There's nothing wrong with the documentation. This issue can be closed.

**Comment by EliterScripts** [comment]
Please add to the documentation that you need to set a variable with the type MessageChannel as static, or else it will not work.

**Comment by simon816** [comment]
@EliterScripts It definitely works, maybe something else in your code is wrong.
```java
    @Listener
    public void onClientConnectionJoin(ClientConnectionEvent.Join event) {
        MessageChannel originalChannel = event.getOriginalChannel();
        MessageChannel newChannel = MessageChannel.combined(originalChannel, others...);
    }

```
