### ISSUE TITLE
Add new SpawnType to distinguish dispenser-placed items

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeAPI#1191]
The SpawnType "CUSTOM" seems to be used for every placeable entity (item frames, paintings, armor stands, every minecart type, dropping boat into water, and cracking mob-spawn eggs -- why "Custom" when this is a pure-vanilla as it gets, custom makes sense for plugin and mod based changes but I digress...)

All of the minecart types, boats into water, and mob-spawn egg cracking can also be spawned as full entities when produced by dispensers (into the appropriate landing area, or else they are just manefested as item drops), but the "CUSTOM" type is also thrown in these cases.

Can there please be a division in types as a way to distinguish Player-based introduction of an entity into the map from the Dispenser-based introduction?

**Comment by theboomer** [comment]
Actually, considering that the system throws "Custom" for Flame-cube spawning of mobs, that wont help distinguish things any further unless flame-cube spawning can also be granted a spawn-type.  Please add a spawn type as well for flame-cube spawner based spawning mobs

**Comment by ST-DDT** [comment]
Just for reference: [Existing SpawnTypes](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/cause/entity/spawn/SpawnTypes.java#L44)

**Comment by theboomer** [comment]
To follow on that reference, it appears there is a type that was declared in the notes to be put aside for dispensers spawning things (DISPENSE), but I can not get that type to appear - just Custom - for different mob eggs , boats, and carts.  At least in the SpongeForge-1276 build, this is the result.  
As well, MOB_SPAWNER appears in the list now, but, "Custom" is still the actual thrown result for spawner cubes.

**Comment by parlough** [comment]
@theboomer Are the SpawnTypes for these still just giving the spawn type `CUSTOM`?

**Comment by theboomer** [comment]
For which api version are you requesting, since things are different but kinda similar with cause/context refactor.

**Comment by ryantheleach** [comment]
@theboomer What API version are you currently having issues with, I'm going to assume @Meronat is only going to work on API7 unless someone specifically requests it for API 5, due to the cause tracking changes they would essentially need to write it twice.

**Comment by ImMorpheus** [comment]
> To follow on that reference, it appears there is a type that was declared in the notes to be put aside for dispensers spawning things (DISPENSE), but I can not get that type to appear - just Custom - for different mob eggs , boats, and carts. At least in the SpongeForge-1276 build, this is the result.
> As well, MOB_SPAWNER appears in the list now, but, "Custom" is still the actual thrown result for spawner cubes.

That's an issue with the implementation. 
If you feel like those events are using the wrong `SpawnType`, open an issue in SpongeCommon
The issue with missing `SpawnType`s is fixed
