### ISSUE TITLE
GenericArguments.choices is case sensitive.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1192]
GenericArguments.choices is currently case sensitive. any chance of getting either a case insensitive version, or modifying choices to be case insensitive by default?

Maybe it should select the choice if there is no other casing, but bail if there are 2 choices with the same case.

**Comment by modwizcode** [comment]
Couldn't you just register two choices, one uppercase and one lowercase?

**Comment by kashike** [comment]
@modwizcode So you want someone to register all of these? :laughing: 
`"SPONGE", "SPONGe", "SPONgE", "SPONge", "SPOnGE", "SPOnGe", "SPOngE", "SPOnge", "SPoNGE", "SPoNGe", "SPoNgE", "SPoNge", "SPonGE", "SPonGe", "SPongE", "SPonge", "SpONGE", "SpONGe", "SpONgE", "SpONge", "SpOnGE", "SpOnGe", "SpOngE", "SpOnge", "SpoNGE", "SpoNGe", "SpoNgE", "SpoNge", "SponGE", "SponGe", "SpongE", "Sponge", "sPONGE", "sPONGe", "sPONgE", "sPONge", "sPOnGE", "sPOnGe", "sPOngE", "sPOnge", "sPoNGE", "sPoNGe", "sPoNgE", "sPoNge", "sPonGE", "sPonGe", "sPongE", "sPonge", "spONGE", "spONGe", "spONgE", "spONge", "spOnGE", "spOnGe", "spOngE", "spOnge", "spoNGE", "spoNGe", "spoNgE", "spoNge", "sponGE", "sponGe", "spongE", "sponge"` etc

**Comment by modwizcode** [comment]
Good point. Maybe a `uncasedChoices` would make more sense.

**Comment by windy1** [comment]
It should just be case insensitive by default IMO if we want to match the behavior of bash which seems to be the trend within the command API.

**Comment by modwizcode** [comment]
Choices is used in a few places besides flags IIRC, I think a few of those uses would be best to remain case sensitive. Additionally command line programs often use multiple cases in flags, which I think is a sane default.

**Comment by zml2008** [comment]
Yeah, I think both case-sensitive and -insensitive variants are needed for choices -- there are valid use cases for case-sensitive but case-insensitive is a reasonable default.

**Comment by dualspiral** [comment]
8976964c1038066d3555ac6fb613ed3839037090
