### ISSUE TITLE
Remove TextSerializerFactory in API 5+

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#1194]
As it stands, it's been deprecated since API 3.x and remains deprecated in 4.x. It's current uses are strictly for the legacy formatting code usages, which honestly should be done in the implementation alone, not in the API. 

I suppose @Minecrell would have more to say about its removal.

**Comment by kashike** [comment]
@gabizou I disagree on legacy formatting codes being implementation-only. Not everything uses `§` or `&`, and there should be a way to create a new `FormattingCodeTextSerializer`:
```java
public interface FormattingCodeTextSerializer extends SafeTextSerializer {

    static FormattingCodeTextSerializer create(char character) {
        return Sponge.getRegistry().createFormattingCodeTextSerializer(character);
    }
```

**Comment by Minecrell** [comment]
It has always been deprecated in terms of that it is not recommended to use for new projects, however that is not an indicator that it should be removed. It's provided for plugins to use for converting older configurations etc.

**Comment by simon816** [comment]
Isn't is deprecated because the equivalent functionality can be achieved with `TextSerializers.formattingCode`?
```java
Sponge.getRegistry().getTextSerializerFactory().getFormattingCodeTextSerializer('&');
// Same as
TextSerializers.formattingCode('&');
```

**Comment by Minecrell** [comment]
Oh, if you're referring to that, then yes - it is. The factory itself is deprecated because it is only the accessor for the implementation, it shouldn't be used by plugins directly.
