### ISSUE TITLE
TextMessageException has nullable method return values

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#1196]
https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/TextMessageException.java#L80-L102

**Comment by Minecrell** [comment]
Since `Exception` itself has several `@Nullable` methods, it would be quite confusing if only some of them used optional. So basically it would be confusing if you would have to check for null for some methods, and the optional for the others.
