### ISSUE TITLE
Interaction between GenericArguments.playerOrSource() and GenericArguments.requiringPermission()

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeAPI#1203]
@zml2008 (Zidane said to tag you)
Currently, when using GenericArguments.requiringPermission(GenericArguments.playerOrSource(...), ...), it throws an exception if the user does not have permission to use that element. Often, I find myself wanting to make a command console-friendly, yet applicable to oneself without a .self permission. I propose that there be a way to require a permission for playerOrSource() that does not get applied if the player is the source.

**Comment by kashike** [comment]
@pie-flavor Please don't remove the content from your issue when you resolve it yourself.
