### ISSUE TITLE
GenericArguments.userOrSource()

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeAPI#1205]
@zml2008 (Zidane said to tag you)
We have GenericArguments.playerOrSource() and GenericArguments.entityOrSource(). The next logical step is GenericArguments.userOrSource(), which would be very useful.

**Comment by ryantheleach** [comment]
Source,User, or UserFuture?

**Comment by pie-flavor** [comment]
@ryantheleach Not sure what you mean. GenericArguments.userOrSource() would return a User if the player did not specify the argument, throw an exception if the console did not specify the argument, and act as GenericArguments.user() otherwise.

**Comment by Zidane** [comment]
Merged in master.
