### ISSUE TITLE
SpongeAPI level in mcmod.info?

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/SpongeAPI#1212]
With Ore in rapid development, I think automatically including target SpongeAPI version (4, 5, 6, etc) in mcmod.info would be beneficial for everyone. It removes any ambiguity about compatibility and whenever plugin is most likely outdated or not.

P.S. I'm talking about default Sponge annotation processor, not about SpongeGradle plugin.
P.P.S. I'm sorry if it's already can be detected.

**Comment by ryantheleach** [comment]
Do you think it's possible to scan to make sure that people actually need a certain API version using something like https://github.com/mojohaus/animal-sniffer ?

**Comment by VcSaJen** [comment]
I'm not sure, but it's seems like PR #1214 covers it.

**Comment by ryantheleach** [comment]
It does, but the idea behind using something like animal sniffer is the ability to determine whether a plugin actually needs 4.10 or if 4.0 will work.

**Comment by ST-DDT** [comment]
There is still the issue with incomplete implementation. Like statistic API is there since API v1 but not yet implemented.
