### ISSUE TITLE
Change ? extends Text to Text.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1213]
![image](https://cloud.githubusercontent.com/assets/141554/14962647/0f7eb56c-10df-11e6-9045-9a3c52172c77.png)

![image](https://cloud.githubusercontent.com/assets/141554/14962635/fca7de14-10de-11e6-9179-7a57b34cc259.png)

https://github.com/SpongePowered/SpongeAPI/blob/74a6311b865e2ecc35e6e7851ccbc681e0119f97/src/main/java/org/spongepowered/api/command/CommandCallable.java#L106

https://github.com/SpongePowered/SpongeAPI/blob/74a6311b865e2ecc35e6e7851ccbc681e0119f97/src/main/java/org/spongepowered/api/command/CommandCallable.java#L89

Text is a sealed class, no one outside of the API can extend it. Additionally, optional can only contain a single element. So why is it typed as ? extends Text?

It causes errors, and means that you can't do the following.

```
callable.getHelp(commandSource).orElse(Text.EMPTY);
```
As getHelp returns ``Optional<? extends Text>`` there is no way to know what type it contains, just that it's a descendent of Text, so Java prevents you from matching against subtypes.

**Comment by kashike** [comment]
@Minecrell Thoughts on this? It seems okay to me to switch the signature to `Optional<Text>` instead of `Optional<? extends Text`.

**Comment by modwizcode** [comment]
What was the original reason for `Optional<? extends Text>`? Seems to me that there was little point in having the wildcard in the signature in the first place. In face the guidelines for wildcard use seem to recommend not returning a wildcard type in an API. 
> Using a wildcard as a return type should be avoided because it forces programmers using the code to deal with wildcards.

**Comment by Deamon5550** [comment]
I would assume its so that subclasses can override the method and narrow the definition, however all of them simply override it as `Optional<Text>` anyway so there is little point.

**Comment by modwizcode** [comment]
Shouldn't the different subclasses override with their specific type?

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/1239

**Comment by liach** [comment]
Could someone close this now?
