### ISSUE TITLE
New Annotation for Events that should NEVER be thrown by themselves

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#1225]
There are a few events that shouldn't be generating methods in the SpongeEventFactory because the events themselves are far too ambiguous to be called otherwise.

A short list of events that are immediately coming to mind:
- `InteractEntityEvent`
- `InteractEntityEvent.Secondary` ( this is 1.9's addition where MainHand and OffHand are added, but Secondary alone shouldn't be thrown)

There are bound to be more examples that come to mind, but @Aaron1011 should know what to do.

**Comment by Aaron1011** [comment]
Merged in https://github.com/SpongePowered/SpongeAPI/commit/d7552947081b23e9e2689689b623116420d33a61.
