### ISSUE TITLE
PlayerJoinEvent in spongeapi-6.0.0-20160315.153811-2

### ISSUE THREAD

**Issue by YmiYugy** [SpongePowered/SpongeAPI#1230]
I just tried to program my first Sponge Plugin, watched some videos and looked in the Documentation, but i can't find PlayerJoinEvent.

**Comment by windy1** [comment]
This is not really the place for these types of questions, please try IRC or the forums next time. Thanks.

https://jd.spongepowered.org/4.0.3/org/spongepowered/api/event/network/ClientConnectionEvent.html

**Comment by YmiYugy** [comment]
sorry, i never used github before
