### ISSUE TITLE
Clean up straggling Entity/TileEntity interfaces not yet handled by Data API

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#1233]
- [ ] [`Boat`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/vehicle/Boat.java)
- [ ] [`Minecart`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/vehicle/minecart/Minecart.java)
  I'm sure there are more to come as I go through the entity interfaces.

Separately, convenience methods that need to be ironed out and javadoced:
- [ ] [`MobSpawnerMinecart`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/vehicle/minecart/MobSpawnerMinecart.java#L32)

**Comment by parlough** [comment]
There's some other additions recently added to the game I plan on handling as well, especially relating to the _illagers_.

**Comment by liach** [comment]
yeah, it really helps a lot to handle minecart stuff with data api (good for mods that provide extra functionalities)

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/pull/2077 (?)

There isn't much information in the original issue but I suppose this doesn't apply anymore.
