### ISSUE TITLE
GenericArguments.world tab-completion fails when preceded by another GenericArgument

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#1238]
Under a very specific set of circumstances, `WorldPropertiesCommandElement` will [throw an exception](https://github.com/SpongePowered/SpongeAPI/blob/0c1d6c33d83d2b6fc909d611775b21185c76a6ce/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L1146) during tab completion.

To reproduce:
1. Create a `CommandSpec` with two `CommandElements`. The first one can be anything (I've tested with 'player` and `longNum`), while the second should be a `world. See [WorldsTest](https://github.com/SpongePowered/Cookbook/blob/master/Plugin/WorldsTest/src/main/java/org/spongepowered/cookbook/plugin/WorldsTest.java#L56) for an example - though note that this issue affects both `master` and `bleeding`.
2. Start entering in a command, including a valid argument for the first `CommandElement`. With WorldsTest, this would be `/tpworld <username> ` (note the space)
3. Press 'tab'
4. Note the exception thrown at [the aforementioned line]((https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L1096))

From what I can tell, the issue seems to be caused by the `#me` value from `WorldPropertiesCommandElement#getChoices` being passed directly to `WorldPropertiesCommandElement#getValue`. Normally, this doesn't happen, with the special options such as `#me` and `#first` being handled by `WorldPropertiesCommandElement#parseValue`

Pinging @zml2008 on this.

**Comment by zml2008** [comment]
Your "throw an exception" link just links to a blank line in the file -- was that what it was supposed to be a stacktrace? I think it should be possible based on the rest of the description to repro and fix anyways, but would be helpful.

**Comment by Aaron1011** [comment]
@zml2008: Oops - I should have linked to that line on a specific revision. [Here's the correct link](https://github.com/SpongePowered/SpongeAPI/blob/0c1d6c33d83d2b6fc909d611775b21185c76a6ce/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L1146) (I've also updated the issue).
