### ISSUE TITLE
Add Silent key

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1240]
Please add the "Silent" key. I have to work around as you can see in [this commit](https://github.com/randombyte-developer/holograms/commit/2608fb635cc9428b14d11ca84ebc21b973fca6aa).

**Comment by gravityfox** [comment]
That's a dead link. Also you should provide more context.

**Comment by randombyte-developer** [comment]
Oh, sorry. 

The current workaround is `/summon Silverfish ~ ~1 ~ {Silent:1b}`.

**Comment by ST-DDT** [comment]
Correct me if I'm wrong but you would like to have a new field in [`Keys`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/key/Keys.java#L73).
````java
public static final Key<Value<Boolean>> SILENT = KeyFactory.fake("SILENT");
````
You want to apply this key to set it on silverfishs like this:
````java
silverfish.set(Keys.SILENT, true);
````

**Comment by randombyte-developer** [comment]
Thanks for the clarification 😊

In general this tag should silence an entity. But there is an issue open which describes unintended behavior: https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-64242
