### ISSUE TITLE
Add new MessageChannels to help create better interaction between chat plugins

### ISSUE THREAD

**Issue by Katrix-** [SpongePowered/SpongeAPI#1245]
Copying this from the forums so that discussion can continue here. 

Link to post: https://forums.spongepowered.org/t/lets-get-chat-formatting-right/12613/17?u=katrix 

Copy-Paste: 
One of the thing that ryantheleach mentioned was to apply the existing `MessageChannel#transformMessage` on top of yours if you are providing a new one. Problem at the moment (unless i missed something somewhere) is you can't just merge two `MessageChannel`s to get both of their transformers as that will also merge all of their members. An easy way to solve this is to maybe include a few other `MessageChannel`s like one that only combines the transformers for example.

You could also have a `MessageChannel` that behaves the opposite of `CombinedMessageChannel`. This message channel would only send a message to players that are in all message channels. This would also (from my point of view at least) make it so that plugins that provide custom channels won't step on each others toes as much. Say for example that you have some sort of minigame plugin on the server that places everyone inside of a minigame in a new `MessageChannel`. In addition to that you also had a chat plugin that had different channels on the server. With this setup, there wouldn't be any message that went outside of the minigame channel, while still allowing the chat plugin to operate as it did.

**Comment by kashike** [comment]
@Katrix- So what are you wanting from this? Could you describe what you want?

**Comment by Katrix-** [comment]
What I'm proposing here is a few more `MessageChannel`s much like `CombinedMessageChannel` to encourage not stepping on other peoples feet when manipulating them.

Currently `CombinedMessageChannel` works like an OR `MessageChannel`. One of the things I propose here is an AND `MessageChannel` where a `MessageReciever` needs to be a member of both channels to get the message.

The other idea I bring up here is a `MessageChannel` that combines only the transform method of the `MessageChannel`s passed in. This again allows for less stepping on other people's feet.

**Comment by kashike** [comment]
`CombinedMessageChannel` takes a `Collection` (or array) of `MessageChannel`s - there is no limit. The member list for a `CombinedMessageChannel` comes from all `MessageChannel`s which have been combined, and transformations are applied through all channels provided.
Does that clarify `CombinedMessageChannel`? If not, what behaviour are you expecting from it?

As for your `MessageChannel` which does transforming, you can extend `DelegateMessageChannel` and override the `transformMessage` method.

**Comment by Katrix-** [comment]
I understand that it takes a collection and then combines the members of all the channels passed in. What I'm suggesting is a similar `MessageChannel`, but instead of just combining the members of all the channels passed in, only the members that are in all the channels passed in get sent the message from this channel.

Say that you have two `MessageChannel`s, and you want to combine them. Here is how it would do it.

Channel1 has the members: 1,2,3,4
Channel2 has the members 3,4,5,6

Using `CombinedMessageChannel` you get a channel that has the members: 1,2,3,4,5,6,
Using what I'm proposing you get a channel that has the members: 3,4

You only get those two members because that's the only ones that are in both the `MessageChannel`s.

I understand that you could easily do this yourself, but you could also easily have made a `CombinedMessageChannel` yourself too. This is more about encouraging not stepping on other plugins toes with little effort.

**Comment by kashike** [comment]
Something that modifies the members of a `MessageChannel` is best left to plugins, in my opinion. We can't know what people will want to do, and what you're suggesting isn't something I could see being used very often. To do it yourself you'd just need to extend an implementation of your choice and filter as you desire.

A `CombinedMessageChannel` does exactly what it's named - combines multiple message channels.

**Comment by ryantheleach** [comment]
I think that plugins should be expected to know how to extend / implement and use DelegateChannels.

The largest complaints from that thread seem to be non-destructively merging text styles, some minor issues about templating / MessageFormatters, and placeholders being removed from the API / no way to see the templates from a MessageChannel.

**Comment by kashike** [comment]
A `MessageChannel` isn't supposed to have a way to obtain information other than a transformed `Text` and a collection of `MessageReceiver` - placeholders/templates are just a `Text` "builder" to a point.

**Comment by Zidane** [comment]
Closing this as I agree with @kashike . The use case is quite limited and the facilities are in place to do it yourself as a plugin.
