### ISSUE TITLE
Add a way to control other properties of an Explosion

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/SpongeAPI#1251]
Currently we expose many of the properties of an explosion, some unusual ones such as yield (used when explosions determine the probability of a block drop, sound, and control over particle effects are not exposed. I will add these properties unless someone has an objection to their addition.

**Comment by ryantheleach** [comment]
I remember Yield being exposed in some form, can't seem to find where or when though.

**Comment by modwizcode** [comment]
I though it was too. But I don't see a patch or anything. If it's that hard to find that I'm searching the implementation, then it needs to be exposed better.

**Comment by DarkArc** [comment]
Exposing whether or not the explosion creates fire would be a plus. This is missing in contrast to Bukkit (as well as the ability to offer a new/modified Explosion to PrimedTNT).

**Comment by kashike** [comment]
The radius (yield) and whether or not it can create fire is in the API. I don't think this needs to remain open.
