### ISSUE TITLE
API should provide block position to CommandCallable for tab completion.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeAPI#1253]
Minecraft sends block positions in the tab completion packet, however this information is not available to plugins.

An argument against this was previously made, stating that SpongeAPI's raytrace takes care of it.

However, the raytrace does not properly take custom bounding boxes into account. In addition, it is useful to simply know what the client is reporting as the highlighted block.

This could just be added to CommandCallable, and not CommandSpec, for people who really want the feature (like me). It's just lame that vanilla minecraft gets to play with features like this and I don't. So if this could be added that would be nice.

**Comment by Aaron1011** [comment]
Pinging @zml2008 for input.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/14fab8a1a9c8cb13b964814028e9bda949224d53
