### ISSUE TITLE
Asset API improvement

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1255]
This is a proposition to improvement on the Asset API.

At the moment the copy method on the Asset only copies to a provided file, given as a path.

I'd like to see an improved method, that creates directories if they don't exist already, as well as preserves the filename of the Asset.

e.g.
asset = container.getAsset("myConfig.conf")
asset.easyCopy(Path pathToConfigDir)

Would create the config directory if it didn't already exist, and copy using the filename if the file didn't already exist.

I believe this would offer a choice to users who do not want to use the default as a fallback, in cases where using it as a fallback makes it impossible to remove configuration nodes in the config files.

**Comment by Zidane** [comment]
Closing this, feedback should go on  PR.
