### ISSUE TITLE
ItemStack equality

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeAPI#1257]
In commit https://github.com/SpongePowered/SpongeAPI/commit/0c1d6c33d83d2b6fc909d611775b21185c76a6ce an additional check for item quantity was exposed. However, there is still a lack of a check to see if two ItemStacks are of the same variant, but with different damage/quantity. 

I currently use the following Forge code to check to see if my ItemStacks have the same variant, with a disregard to the damage value if the item is undamageable. It would be nice to see a similar easy to use check for Sponge.

``` java
import org.spongepowered.api.item.inventory.ItemStack;

import static com.skelril.nitro.transformer.ForgeTransformer.tf;
import static net.minecraft.item.ItemStack.areItemStackTagsEqual;
import static net.minecraft.item.ItemStack.areItemsEqual;

public class ItemComparisonUtil {
    public static boolean isSimilar(ItemStack a, ItemStack b) {
        net.minecraft.item.ItemStack stackA = tf(a);
        net.minecraft.item.ItemStack stackB = tf(b);

        if (stackA.isItemStackDamageable()) {
            return a.getItem() == b.getItem() && areItemStackTagsEqual(stackA, stackB);
        }

        return areItemsEqual(stackA, stackB) && areItemStackTagsEqual(stackA, stackB);
    }
}
```

**Comment by liach** [comment]
I think we should mainly focus the comparison on `ItemStackSnapshot`s since they are immutable, making them safe for usages in a sorted data structure, etc.

**Comment by DarkArc** [comment]
It seems silly to have to allocate all the structures required to make a snapshot, just to do a valid comparison.

**Comment by gabizou** [comment]
It boils down to sponge needing to ditch the implemented comparators and move them to implementation where we can compare for mentioned use case. Likewise in 1.13, damage values are going away entirely, and tags will be a thing.

**Comment by Faithcaio** [comment]
If there are specific comparators you want make a new issue.
In future API8+ they will NOT be implemented in API.
