### ISSUE TITLE
Make methods which fire events take Cause param

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#1259]
All methods mutating a world where entities spawn already take a cause, and all Data methods already have `DataTransactionResult`s, but only a few of our `setBlock` methods take a `Cause` currently, and even then, there are many that are overloaded and implemented through `Location` to set a block and the issue with 1.9's system is that the `CauseTracker` is in an empty state most of the time, either when tasks are being executed, or when there are various state events being called.

The larger issue is that plugins are not able to change the world without the `CauseTracker` knowing about it, and the `CauseTracker` will flip out about unknown changes when there are no expected phases in the stack.

As in the past, we've added many requirements to spawning entities, creating entities, and setting blocks to bypass the `CauseTracker`, but I feel (and @Zidane is in partial agreement) that plugins should provide a `Cause` when changing blocks. Even if the cause is a rudimentary `Cause` that only includes a `PluginContainer`, it would fair better with the sort of changes in place with the tracking system.

**Comment by pie-flavor** [comment]
I think that regardless of what is required, _everything_ that does an event able action should have an overloaded method that accepts one.

**Comment by Favorlock** [comment]
I agree that a cause should be required.

**Comment by modwizcode** [comment]
This would make things a lot clearer, and would prevent plugins from creating so many "we did this as this plugin, not as a natural event" type secondary events. You could just check for the plugin's cause, which could contain any data they wanted to add with it.

**Comment by JBYoshi** [comment]
> gabizou assigned Zidane and gabizou 6 hours ago

Looks like GitHub added a new feature... :+1:

**Comment by Zidane** [comment]
I've updated this issue to reflect better the upcoming change. Any event which triggers an event needs to have an overload that lets you provide a Cause. Otherwise, we'll provide one that has your plugin container.

**Comment by Deamon5550** [comment]
This is not going to be a thing after #1370

**Comment by gabizou** [comment]
I believe we've resolved this issue over the last few months with various method changes. Closing.
