### ISSUE TITLE
Feature request / Query: Sponge chunk generation methods

### ISSUE THREAD

**Issue by DraksterAU** [SpongePowered/SpongeAPI#1262]
Hi All,

I'm a relatively new Bukkit and Forge developer and am currently searching for methods to generate/regenerate chunks within Sponge to support a ported version of my plugin, but do not seem to be able to find any. 

Apologies if this is due to being relatively new to Java and Sponge itself... just point me in the right direction and I'll close the issue. If not, please consider it a low priority-ish feature request.

I'm slowly getting my head around how to work in Sponge in order to port my plugins across, however 
I'm having trouble finding any equivalent methods or ways to perform actions:

- Regenerate (or generate) a chunk if it is already generated (based on the world seed) - Similar to Bukkit's world.regenerateChunk(x,y,z) methods.

- Way to populate a freshly generated chunk.
Previously I could iterate through the BlockPopulators on the server and action them  against a chunk.

- Refresh chunks? If this is even required anymore ?

PS: My Bukkit plugin is here, for reference: https://github.com/DraksterAU/Regenerator

**Comment by Deamon5550** [comment]
Duplicate of #574

**Comment by DraksterAU** [comment]
Sweet, so it's being looked at. Thanks.
