### ISSUE TITLE
Offline server return "null" instead of name of player ?

### ISSUE THREAD

**Issue by Flashback083** [SpongePowered/SpongeAPI#1267]
Hello ! Since i updated sponge, we have an issue, i think the uuid is break , for example, i use foxguard plugin and when a add member to region , the member wasnt add and in list, we see : "null" instead of name of player, any idea for this problem or you need more information ? thanks!!

**Comment by Aaron1011** [comment]
I believe the issue is that `User` doesn't account for the fact that the underlying GameProfile name [can be null](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/profile/GameProfile.java#L63)

**Comment by JBYoshi** [comment]
@Aaron1011 I thought the `GameProfile` was always `fill()`ed before passing it into a `User`?

**Comment by Flashback083** [comment]
More info for this issue ?^^ thanks !

**Comment by kashike** [comment]
@JBYoshi Not on offline servers.

**Comment by kashike** [comment]
Is this still an issue?

**Comment by gravityfox** [comment]
I'm not sure. When this came up in my plugin, I had trouble reproducing it personally, but when i joined someone's server, name was clearly coming up null.

**Comment by kashike** [comment]
If this is still an issue someone can open a new ticket.
