### ISSUE TITLE
Key Absorption

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeAPI#1268]
hi,
can you create a key to return absorption heart ?

**Comment by JBYoshi** [comment]
Would `Keys.MAX_HEALTH` work? It returns the total number of health available (in half-hearts, so it's 20 with 10 hearts).

**Comment by kashike** [comment]
@JBYoshi No, there should be an `ABSORPTION` key/data.

**Comment by Aaron1011** [comment]
This is important to have, as mods can and do set absorption without applying the potion effect (see Thaumcraft's Runic Shielding).

**Comment by gabizou** [comment]
This is pending an Attributes API as absorption is handled through Attributes last I recall.
