### ISSUE TITLE
arguments for fallback executors vs parents is ambiguous.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1272]
Given:

```
CommandExecutor pageExecutor = (src, args) -> {
                args.<ActivePagination>getOne("pagination-id").get().specificPage(args.<Integer>getOne("page").get());
                return CommandResult.success();
            };
            SpongeImpl.getGame().getCommandManager().register(SpongeImpl.getPlugin(), CommandSpec.builder()
                .description(t("Helper command for paginations occurring"))
                .arguments(new ActivePaginationCommandElement(t("pagination-id")))
                //fallback
                .executor(pageExecutor)
                .child(CommandSpec.builder()
                           .description(t("Go to the next page"))
                           .executor((src, args) -> {
                               args.<ActivePagination>getOne("pagination-id").get().nextPage();
                               return CommandResult.success();
                           }).build(), "next", "n")
                .child(CommandSpec.builder()
                           .description(t("Go to the previous page"))
                           .executor((src, args) -> {
                               args.<ActivePagination>getOne("pagination-id").get().previousPage();
                               return CommandResult.success();
                           }).build(), "previous", "prev", "p")
                .child(CommandSpec.builder()
                           .description(t("Go to a specific page"))
                           .arguments(integer(t("page")))
                           .executor(pageExecutor).build(), "page")
                .build(), "pagination", "page");
```

Results in

![image](https://cloud.githubusercontent.com/assets/141554/16030668/ae712820-3232-11e6-95d7-a1e43c574056.png)

Because the arguments of the parent command are assumed to be belonging to the fallback and not the parent command.

What would have been expected is 

Usage: /page [pagination-id] next|previous|page

The issue is that there is no concept of arguments belonging to a fallback executor separately to that of the parent.

Some ideas I have floating around is introducing an explicit .fallback() to the builder, and deprecating the use of parent executors for fallbacks. that way the fallback could additionally require additional commands?

Maybe I'm wrong and the fallback I'm attempting to create could be covered in another way.

https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/command/spec/CommandSpec.java#L249

Changing 
`arguments(firstParsing(childDispatcher, this.args));`
to  `arguments(this.args, firstParsing(childDispatcher, fallbackArgs));`
would fix this somewhat, but probably break someone's existing plugin somewhere.

After looking at this some more, it's currently not possible to set a child without an alias.

So maybe the functionality I'm thinking of would fit that better? 

Or maybe the child command element arguments could be specified, and if found replaced rather then pre/appended?

**Comment by dualspiral** [comment]
In the latest SF for API 7 snapshot, I've added method `childArgumentParseExceptionFallback` to the `CommandSpec`. You need to set this to `false` to get the behaviour you expect above, I opted to make this a non-breaking change for API 7.
