### ISSUE TITLE
Add Dragon Phase API

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#1273]
With 1.9, the end dragon fight was completely reworked. The dragon's actions are now controlled in distinct phases (sitting, charging player, etc.). It should be possible to expose this to plugins.

**Comment by Cybermaxke** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/b4c50c9755dbf1c474854fbcc279d9ba003f0aa7
