### ISSUE TITLE
Notify client of biome changes

### ISSUE THREAD

**Issue by dags-** [SpongePowered/SpongeAPI#1275]
When using `setBiome(..)` on a location, the changes aren't sent to nearby players.
In order to see the changed biome, users have to re-log, or travel far-enough away that the affected chunk gets re-sent to them when they return to the area.

Ideally, plugins could re-send specific chunks that they've modified so that clients see the biome changes more instantaneously.

Bukkit's `world.refreshChunk(..)` made painting biomes with voxelsniper possible, which was pretty neat

**Comment by Zidane** [comment]
@Deamon5550 

Think you could slip this in sometime?

**Comment by JBYoshi** [comment]
@Zidane I'll do this. I've already got some code ready, just waiting for a `setupDecompWorkspace` to finish so I can update my Minecraft JAR for new access transformer changes.

**Comment by JBYoshi** [comment]
PR is up: SpongePowered/SpongeCommon#802

**Comment by Zidane** [comment]
Closing as PR made.
