### ISSUE TITLE
Add JavaDocs for TOTAL_EXPERIENCE and HELD_EXPERIENCE

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1277]
I can imagine that Keys.HELD_EXPERIENCE is the experience the player currently has. But what is Keys.TOTAL_EXPERIENCE? Does it even belong to the player? The explanation should be added to the JavaDocs.

**Comment by JBYoshi** [comment]
`TOTAL_EXPERIENCE` is for players. `HELD_EXPERIENCE` is for XP orbs.

**Comment by randombyte-developer** [comment]
Thanks. Now this should be added to the JavaDocs.

**Comment by Bammerbom** [comment]
And add a javadoc CONTAINED_EXPERIENCE too, I have no idea what it is for.

**Comment by stephan-gh** [comment]
Fixed in https://github.com/SpongePowered/SpongeAPI/pull/1484
