### ISSUE TITLE
Add a getter to InteractBlockEvent for the hand used.

### ISSUE THREAD

**Issue by me4502** [SpongePowered/SpongeAPI#1280]
Currently to get an instance of the HandType used in an interact, you need to use the following code:

`HandType hand = event instanceof InteractBlockEvent.Secondary.MainHand ? HandTypes.MAIN_HAND : HandTypes.OFF_HAND;
`

Providing a getter in the event would allow for it to be a lot simpler. It could also be done in the break event, and other events that reference the type of hand.

**Comment by theboomer** [comment]
There are many issues posted and problems on the forum that require the hand-type used in the interact, place, and break events.

Can this please get included?

**Comment by JBYoshi** [comment]
Every `InteractEvent` is an instance of `HandInteractEvent`; just cast to that and you have your getter.

**Comment by theboomer** [comment]
Does that include place and break?

**Comment by JBYoshi** [comment]
<s>Yes.</s>

**EDIT:** Wait, did you mean `ChangeBlockEvent.Place` and `ChangeBlockEvent.Break`? In that case, no. Just the `Interact_____Event`s.

**Comment by ryantheleach** [comment]
If this hasn't been resolved for place/break it could be a part of the cause context if people still need this.

**Comment by ImMorpheus** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/1969
