### ISSUE TITLE
Add event for when a player toggles sneak

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeAPI#1281]
This event should be thrown when a player starts holding, or stops holding the sneak key.

**Comment by randombyte-developer** [comment]
[`ChangeDataHolderEvent`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/data/ChangeDataHolderEvent.java) in combination with [`IS_SNEAKING`](https://github.com/SpongePowered/SpongeAPI/blob/835294849eddf481aa672d6fb6d784452dd4a396/src/main/java/org/spongepowered/api/data/key/Keys.java#L530). I think `ChangeDataHolderEvent` isn't  fired yet.

**Comment by Bammerbom** [comment]
I didn't know about the event, thanks. I will wait for the implementation.

Closed.
