### ISSUE TITLE
Missing 1.9 events

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1282]
- An event for toggling on and off dual wield
- An event for swapping items between main and off hand.

Would it be possible to add those?

**Comment by Daniel12321** [comment]
I need this badly.

**Comment by NeumimTo** [comment]
Any progress so far? It still seems to be unimplemeted

**Comment by ryantheleach** [comment]
@Faithcaio has implemented this in API7 / 1.12 stable builds.

**Comment by ImMorpheus** [comment]
Tested on 1.12 (bleeding branch)

> An event for swapping items between main and off hand. 

Is implemented: ChangeInventoryEvent.SwapHand

> An event for toggling on and off dual wield

I have no idea what that is
