### ISSUE TITLE
Platform dependent event listeners

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#1289]
It'd be beneficial for sponge plugins to be able to have sided event listeners, where by default, the listeners are both sides, but a sided listener would be stripped from client or server depending on which platform that listener is enabled for.

This would help with event listeners and can easily be transformed at runtime by Sponge's implementation.

**Comment by kashike** [comment]
Similar to `SideOnly` and `Side` in Forge? Decorate with `@PlatformOnly(Platform.Type.SERVER)`, defaulting to `UNKNOWN`?

**Comment by Zidane** [comment]
@gabizou 

Very very few events fire on both sides currently. I don't see the benefit of this until that changes. In the meantime, you can easily check your platform#getType.

**Comment by Aaron1011** [comment]
We should keep in mind that currently, <i>no</i> events are fired on the client side at all.

**Comment by Zidane** [comment]
Closing as I still see no benefit of this. Use Forge's Proxy system as if you're doing client stuff you have Forge.
