### ISSUE TITLE
Add support for ordinal block offsets in Direction enum

### ISSUE THREAD

**Issue by DDoS** [SpongePowered/SpongeAPI#1291]
Getting relative blocks with cardinal directions works fine because the vectors have unit length on x, y, or z, which displaces by exactly one block. This is not the case with ordinal directions because they do not displace by a full block on each axis, which when floored causes no changes on positive offsets.

For cardinals: `new Location<World>(world, 1, 2, 3).getRelative(Direction.SOUTH).getBlock()` is equivalent to `world.getBlock(new Vector3d(1, 2, 3).add(0, 0, 1).toInt())`. `toInt()` is equivalent to `floor()` but also returns the results as a `Vector3i`. So the final call is `world.getBlock(new Vector3i(1, 2, 4))`. This is correct.

But for ordinals, when using `Direction.SOUTHEAST`, we obtain `world.getBlock(new Vector3d(1, 2, 3).add(0.70710678118655, 0, 0.70710678118655).toInt())`, which is equivalent to `world.getBlock(new Vector3i(1, 2, 3))`. While this can be seen as correct, it is not very useful.

I propose adding a `asBlockOffset()` method to `Direction` that returns a non-normalized vector, and renaming `toVector3i` to `asOffset()`. The `Location` class will also gain a new method `getBlockRelative()`, which will use the block offset instead.

Furthermore, other incorrect usages of ordinals might exist in the API and need to be located and corrected.

Secondary ordinals are not affected here since they cannot be used as block offsets. They will be considered as invalid arguments.

See also: https://forums.spongepowered.org/t/southeast-direction-incorrect/13392

**Comment by ryantheleach** [comment]
I support asBlockOffset() as it implies that it is going to be non normalized.
but asOffset instead of toInt? I believe this will cause people to get it confused with asBlockOffset more readily.

**Comment by DDoS** [comment]
It's not toInt()...

**Comment by ryantheleach** [comment]
I edited the post but it didn't come through on email. I was meaning toVector3i.

**Comment by DDoS** [comment]
asOffset is Vector3d. I'm just keeping the naming scheme consistent.
