### ISSUE TITLE
GenericArguments.entity can not parse playernames, parsing errors confusing

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1294]
GenericArguments.entity is supposed to be able to handle, uuid's, playernames, and selectors, but at the moment trying to parse UUID's fails with. 

No values matching pattern '39669d04-e02e-47e3-bf53-084d6fd7a6fc' present for uuid!

and attempting to parse player names results in 

Error occurred while executing command 'delball Player636' for source EntityPlayerMP['Player636'/361, l='spawntest', x=-78.28, y=68.37, z=244.06]: Invalid UUID string: Player636
java.lang.IllegalArgumentException: Invalid UUID string: Player636

**Comment by ryantheleach** [comment]
Not a bug, just confusing error handling.

**Comment by kashike** [comment]
Is this still an issue?

**Comment by kashike** [comment]
@ryantheleach

**Comment by ryantheleach** [comment]
Sorry been out of it for a while.

Tested just now, on Bleeding 726992c2595aab5d2fa9d80a5efb4bf52033035b.

![image](https://cloud.githubusercontent.com/assets/141554/25006604/b6486014-209c-11e7-967a-6cd5ae31e46a.png)

**Comment by dualspiral** [comment]
8976964c1038066d3555ac6fb613ed3839037090
