### ISSUE TITLE
Have Scala Runtime available for SpongeVanilla.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1296]
Added as an API issue as it would potentially affect other platforms should they exist.

SpongeForge already has the Scala Runtime available due to it being available on Forge, I'd like to see the Scala runtime available on vanilla so I can package plugins written in Scala and not have to worry about users installing libraries for SpongeVanilla only.

Ideally I'd like to see them shaded and relocated, so that I could use 2.12 on both platforms But I could see this being a step too far and have people disagreeing.

The best I think I can hope for is having whatever version forge is bundling also provided on SpongeVanilla.

**Comment by pie-flavor** [comment]
Also Kotlin.

**Comment by Mumfrey** [comment]
Yeah and groovy while we're at it`</sarcasm>`

Honestly this seems like a terrible idea. Forge basically regret ever bundling the scala runtime because of the pain it causes them, in terms of distribution payload and support headaches.

**Comment by ryantheleach** [comment]
What support headaches did it cause them?

**Comment by pie-flavor** [comment]
@mumfrey inb4 someone writes an entire complicated plugin in build.gradle

**Comment by Mumfrey** [comment]
> What support headaches did it cause them?

Search "scala" on the forge forums. Honestly, bundling scala is just asking for problems, with any luck forge will drop support for it in the future and then the issue goes away.

**Comment by ryantheleach** [comment]
The most common issues I seem to find are the fact that the download stalled. hardly a Scala specific problem, or people assuming that ForgeMultiPart was a part of Forge?

**Comment by me4502** [comment]
Is it worth considering having a list of libraries that will be downloaded on demand, if a plugin requests it?

**Comment by ST-DDT** [comment]
Up to a certain extend plugins are libaries itself.
If worst comes to worst you can still do yourself / in yor plugin:
Search for scala class in classloader and download/attach it if it is not there yet.

**Comment by progwml6** [comment]
@me4502 deploading on demand is a terrible idea.

In the past I believe we floated internally having official language binding plugins that can be depended on by developers, however I can't remember what the exact conclusion we came to the last time we discussed this was.

**Comment by randombyte-developer** [comment]
If one wants to use Kotlin/Scala/Groovy they always can shade the runtime into their jar. All of my plugins I have written so far are made with Kotlin. I shade the runtime and the standard library into the plugin jar. They are currently altogether only 1,8MB. I think memory isn't the issue in these times.

**Comment by Zidane** [comment]
I don't see any point of this. If a plugin wants it, shade it.
