### ISSUE TITLE
ChangeEntityPotionEffect modifications.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1302]
ChangeEntityPotionEffect currently doesn't have a way to set the final potion effect to apply to the entity, resulting in code like https://github.com/pie-flavor/Plguin/blob/master/src/main/java/flavor/pie/plguin/ShakePotions.java#L79

should this event instead have a Transaction<PotionEffect> allowing changes? or would the appropriate place to do per entity changes to the duration (different potion resistances?) be on a different event?

**Comment by ImMorpheus** [comment]
Added by https://github.com/SpongePowered/SpongeAPI/pull/1249
