### ISSUE TITLE
Enchanting Events

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1303]
There is a lack of Enchanting Events available in SpongeAPI

Needed:
EnchantItemEvent: an event that fires when an item's enchantments are being changed either through an anvil or enchanting table.

PreEnchantEvent an event that fires when the choices are given to a player when they insert an item into the enchanting table or anvil, giving them feedback on what happens next.

Usecase:
1. On my old Bukkit server I would add lore onto items that had been enchanted, with the players names. This made stealing items more interesting, because you could potentially see who the last person who upgraded or cared for an item was. I don't think this is currently possible without enchanting events.
2. Limiting higher level enchants to a magical crafters RPG class.

**Comment by nihiluis** [comment]
agree

**Comment by nihiluis** [comment]
bump
