### ISSUE TITLE
PvP balancing.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1304]
Heavy PvP servers often use custom builds of minecraft / mods / plugins in order to re-balance what gear is possible to obtain in Minecraft.

To make Sponge more appealing to those servers, I suggest that API(or mixin configuration) be available that can accomplish the following.
- [ ] Limiting the max natural enchanting level of enchantments.
- [ ] Being able to modify the enchanting pools to remove certain enchants, or enchanting levels completely.
- [x] Being able to limit what potions are obtainable to players, possibly via removing their recipes, or cancelling their recipe events.
- [ ] Change AttackSpeed attributes back to pre 1.9 behavior

This would make SpongeAPI more attractive to heavy PvP servers who feel the need to re-balance the game or "kits".

**Comment by Meronat** [comment]
For my future guild server this would be extremely beneficial. We've looked into ways of limiting enchantments in other fashions but none would work as well as what is mentioned here. Enchantment events would be a step in the right direction.

**Comment by gabizou** [comment]
What is this train wreck of an issue description?

**Comment by AlphaModder** [comment]
This seems like two seperate issues: Modifying the enchantment pool / generation algorithm, and changing the properties of objects supplied by vanilla.

**Comment by ryantheleach** [comment]
I've tried to reword the description to make more sense.

**Comment by ryantheleach** [comment]
@AlphaModder You are correct, it was meant more as a tracking issue much like events or data.

**Comment by liach** [comment]
I suggest putting them in the extra package.

**Comment by parlough** [comment]
Part of this will covered by attributes which is already an open PR by Kashike. It's on my list to update and merge.

**Comment by ImMorpheus** [comment]
Closed by https://github.com/SpongePowered/SpongeAPI/pull/2085 https://github.com/SpongePowered/SpongeAPI/pull/1898 https://github.com/SpongePowered/SpongeAPI/pull/1954
