### ISSUE TITLE
Text Serialization Issues

### ISSUE THREAD

**Issue by theneedforsneed** [SpongePowered/SpongeAPI#1309]
I'm trying to serialize Text from a MessageChannel so that I can filter through the string without dealing with TextColors, TextStyles, actions, etc.

If I input a new Text object using the Text.of() method, I get a normal looking JSON output. Example (I've expanded the outputted strings into proper JSON for easier reading.): https://thepb.in/p/GZhWNGOvKEEUV

But if I input the Text object from the MessageChannel (which gets the Text directly from the in-game console), I get a really funky string that seems to have a lot of empty "extra" tags.
https://thepb.in/p/P1hv1MomJXKsl

Anyone know why this is happening, and what I/we can do to fix it?

Plugin Code:  https://thepb.in/p/xGhm5w9YqPYHM

**Comment by ryantheleach** [comment]
I can't get your paste site to load, But I'm guessing the reason why you are getting extra tags is due to the templates used to make it easier for chat plugins to insert variables at the correct locations.

**Comment by Starza4TW** [comment]
Using a text object: http://pastebin.com/VuRGa3Sq
Using text from the MessageChannel: http://pastebin.com/v7RRY9tB
Code: http://pastebin.com/jMeiKyiH

That paste site is whichever one is used with the online IRC client that is linked on the sponge website.

**Comment by ZephireNZ** [comment]
Vanilla MC will add some hover and click events to player names for easy reply messaging. As a result the text JSON will be much more complex to allow this. This can be seen in the first part of the message.

However, it's certainly a bit over-complex at the end, likely due to the source code having some wacky appending of the chat message contents (or lack of).

**Comment by ImMorpheus** [comment]
As of API 8 we are now using [Adventure](https://github.com/KyoriPowered/adventure). 

This means the old Text api is gone and all the related issues (especially those involving breaking changes) are no longer relevant, therefore I'm closing this.

Specifically for this issue:

Adventure has 3 different serializers (legacy, plain and gson).
