### ISSUE TITLE
Configurate (Related) Issue

### ISSUE THREAD

**Issue by hsyyid** [SpongePowered/SpongeAPI#1310]
_I'm unsure where this issue belongs. I don't know if it's a Sponge issue or a Configurate Issue_

I am saving a `List<ItemStackSnapshot>` to a config here:

https://github.com/NucleusPowered/Nucleus/blob/7c54cccf54ced00802baf04f994ce3b269510e38/src/main/java/io/github/nucleuspowered/nucleus/configurate/datatypes/KitDataNode.java#L20

It should be saving like this:
https://gist.github.com/hsyyid/f7277757533259c90d66f945531e1068#file-general-json-L19

However instead, it's doing this:
https://gist.github.com/hsyyid/8d29310addd67b2a7d9a014f9a3927bf#file-general-json-L19

Those quotation marks around the level and id of the enchantment is causing it to be deserialized as Strings, not Integers. This then causes this issue:

https://github.com/NucleusPowered/Nucleus/issues/181

**Comment by Minecrell** [comment]
I can't reproduce this on 1.10.2, so this was either already fixed or exists only on 1.8.9 (or I'm doing something wrong).
