### ISSUE TITLE
Operator bypass whitelist

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeAPI#1311]
Hi,
with a permissions service, operators can bypass the whitelist. It's possible to disable this ?
It's possible to disable this ?

**Comment by Aaron1011** [comment]
This can be accomplished by listening to `ClientConnectionEvent.Login`, and manually cancelling the event for players who would otherwise be able to join.

**Comment by lesbleu** [comment]
I don't know the list of operator ? 
The goals of the permissions service is to not used the operators ?

**Comment by Aaron1011** [comment]
@lesbleu: Hmm, I didn't think about that. If you just want to ignore the player's operator status, you could check the `WhitelistService` yourself in the event handler, and always cancel the event if the player isn't whitelisted. That would override the Vanilla operator bypass mechanic.

@zml2008: Would it be worth exposing operator information for this specific usecase?

**Comment by zml2008** [comment]
What I think the issue here is that we haven't overridden the op check for whitelist bypass so it's still done by op rather than by permission. I'll look into fixing that, it should be quick.

**Comment by Zidane** [comment]
Actually, I'm closing this as this is a SpongeCommon issue. Re-open it there.
