### ISSUE TITLE
Spelling mistake.

### ISSUE THREAD

**Issue by ConnorHartley** [SpongePowered/SpongeAPI#1314]
https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/world/ChunkTicketManager.java#L289

Not sure if this is intentional?

It says "dickets" more than once in the class javadocs too.

**Comment by DDoS** [comment]
Not it is not. I have mentioned it to blood, who wrote this code. It should be fixed in the next formatting/warning fix commit.

**Comment by kashike** [comment]
#1000
