### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by loveyanbei** [SpongePowered/SpongeAPI#1316]
Could not pass LightningEvent$Strike$Impl to org.spongepowered.mod.plugin.SpongeModPluginContainer@32817e1e
java.lang.NoSuchMethodError: org.spongepowered.api.world.explosion.Explosion$Builder.world(Lorg/spongepowered/api/world/World;)Lorg/spongepowered/api/world/explosion/Explosion$Builder;

code:
Explosion.Builder bu = Explosion.builder();
bu.world(entity.getWorld()); //error thrown here

**Comment by loveyanbei** [comment]
SpongeForge 1.9.4
API:4.1.0

**Comment by gabizou** [comment]
1.9.4 is not supported. API 5.0.0 has a few breaking changes and supports Minecraft 1.10.2.
