### ISSUE TITLE
Data API Key: Invulnerable

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1317]
I am requesting that an Invulnerable key is added to the data api's keys. I am thinking of the exact same thing as the vanilla way to do it: `/summon Cow ~ ~ ~ {Invulnerable:1}` or `/entitydata uuid {Invulnerable:1}`.

**Comment by ST-DDT** [comment]
@randombyte-developer : isn't that covered by [`Keys.INVULNERABILITY_TICKS`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/key/Keys.java#L504)? At least as a short time solution.

**Comment by randombyte-developer** [comment]
@ST-DDT the temporary solution would be calling the entitydata command. I was looking for the exact same thing as the vanilla invulnerability.

**Comment by randombyte-developer** [comment]
Is it safe to use `entity.offer(Keys.INVULNERABILITY_TICKS, Integer.MAX_VALUE)`?

**Comment by parlough** [comment]
This will be solved by https://github.com/SpongePowered/SpongeAPI/pull/1688

**Comment by parlough** [comment]
Fixed in 827f9009bb36d68c3de9f58b844f036a86c35fba
