### ISSUE TITLE
Unnecessary optional for createEntity

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeAPI#1319]
It doesn't seem that there are any circumstances in which createEntity() could possibly return Empty, it should always be creating an entity, and the SPAWNING is where the failure would occur

Should be non optional.

Posting per blood recommendation

**Comment by simon816** [comment]
createEntity would fail if you attempt to create a `EntityTypes.PLAYER`. Would also fail if the position is not valid (e.g. not on a block for hanging entities)

**Comment by Yeregorix** [comment]
Throwing an exception with a description of the error may be more usefull and devfriendly than returning an optional.

**Comment by gravityfox** [comment]
I like the optional better, as that signifies there are conditions to creating entities, and one won't be created if those conditions aren't met.

**Comment by Yeregorix** [comment]
If we just return `Optional.empty()` when conditions are not respected, we will not know what is missing to create the entity. You will see lot of new devs asking for help in the forum because they can't create an entity and they don't know why.

**Comment by theboomer** [comment]
When posted, we hadn't realized that A case did exist for a failure, the Player entity.  Even an invalid location was believed to only throw errors during the spawning process.  But since there is this fringe case that could produce a null, in accordance to Rule #1 make sure any null can never be exposed, keeping this wrapped in optional is fine, and given the knowledge, I for one will just take it straight to the get() without worrying about checking and unwrapping when creating every other entity except a player...

I wash my hands of the complaint/observation on the grounds that one case was presented that we could not think of that counterproved it, thus defeating the reason for posting;  but if others wish to run with this idea for discussing optional vs a thrown exception feel free, but I give the devs the power to shut this open issue down when they want, and will not close it myself.

**Comment by gabizou** [comment]
I hate to say this, but, I have had this method in mind to add a required `Cause`, much like the reasoning that `spawnEntity` requires a `Cause`. The reasoning is that plugins may decide to cancel the entities construction, likewise, spawn limits can be enforced by plugins, and a whole lot of other reasons.

**Comment by theboomer** [comment]
Yegegorix - to be honest, 99% of the optional.empty returns could have that same argument - "Why?"
Instead say "hmm, think of that like a null, why can it be null in this case after all?"  I dont see it as any special situation different from any other empty returning a failure or empty.

**Comment by gabizou** [comment]
What I'm gathering though, is that we could very well return a sort of tristate object with the optional entity, so you can get the resulting entity still wrapped in an `Optional`, AND still get the *reason* why your entity is null, namely from an event, position, etc.

**Comment by Zidane** [comment]
Closing as the API is as it is intended to be.

**Comment by Deamon5550** [comment]
I do not agree. `createEntity` failing will never happen during normal use, it is only in exceptional cases indicative of some failure in the plugins logic (namely trying to spawn players and if an exception is thrown in the entity ctor) and hence should be error cases.

There is no case where a call to `createEntity` is going to fail 'some of the time'. Either it will work every time or the plugin has an error and it will fail every time.

**Comment by Zidane** [comment]
@Deamon5550 

Very well but not acceptable to let a server crash happen (and any damage that occurs cause of it) when the creation of said Entity can be safely performed. The only drawback is developer feedback on why their EntityTypes.PLAYER failed to spawn (lol).

I simply will never accept crashing the server intentionally if an API is used wrongly. That is when API is re-visited and re-designed.

**Comment by Deamon5550** [comment]
Something like 99% of uses originate from event listeners or scheduled tasks which catch and report exceptions rather than crashing the server. An API being wrongly used is a developer error and is exactly when you want to throw errors (hence why we use `checkNotNull`/`checkArgument` rather than just putting a little log message and returning).

**Comment by gabizou** [comment]
@Zidane while removing the optional would result in an exception being thrown, it would definitely not throw an exception that would crash the server. If we wanted to avoid exceptions altogether, we'd never `checkNotNull` etc. Using the API wrongly in this case is valid to say that the only time we'd never return a created entity is if the API was used wrongly, in which case we most definitely want to print an exception. In essence, let bad code fail.

**Comment by Zidane** [comment]
@gabizou @Deamon5550 

Good points from both of you' I've reconsidered and this can be added to 5.0's changelog.
