### ISSUE TITLE
Allow location to createEntity

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeAPI#1320]
Often one has a location where they want to spawn an entity, but we then have to break that up into the extent and position in order to feed back into one line - extractedExtent.createEntity(type, Extractedposition) , which is .. overkill?

Please consider   location.createEntity(type)  since it knows the extent AND position already
and optionally location.spawnEntity(entity, cause) so that we dont still have to break out the extent part separately after all that savings :)

**Comment by DDoS** [comment]
Have you looked at Location.map()? Just pass it any functional interface that takes an Extent and a Vector3d to have it called on the location. Try `location.map((e, p) -> e.spawnEntity(p, type));`.

**Comment by theboomer** [comment]
Thats a heck of a trick to consider in the meantime, and for some other situations :) But a location spawnEntity method should also be able to do that behind the scenes for us.
