### ISSUE TITLE
Error : ItemTypes.STONE_STAIRS supports Keys.STONE_TYPE

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeAPI#1322]
Hi,
The stone stairs supports the key "Stone_Type" but there are only one type of stone stairs. All stairs have different ID.

Example:
minecraft:stone_stairs
minecraft:stone_brick_stairs

**Comment by gabizou** [comment]
Why is this an error? It switches between different `BlockState`s for a reason.
