### ISSUE TITLE
DataWatcher Wither

### ISSUE THREAD

**Issue by Lezzio** [SpongePowered/SpongeAPI#1324]
I'm new to Sponge and I used some hacky code to modify DataWatcher for some extra stuff.
I'm looking for a good way to do this in Sponge about the wither.

Setting the Invulnerable time (see: http://wiki.vg/Entities#Wither) to a large number turns the Wither into a "baby". How to implement it properly ?

Thanks!

**Comment by kashike** [comment]
Is [`Keys.INVULNERABILITY_TICKS `](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/key/Keys.java#L505) what you are looking for?

**Comment by Lezzio** [comment]
This is not exactly the same "invulnerability" see the link. The invulnerability I'm talking about happens when you invoke the wither, it puts the Wither in a special state (with effects).

**Comment by windy1** [comment]
You can actually control this through the `FusedExplosive` interface which the Wither implements. See [`Keys.FUSE_DURATION`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/key/Keys.java#L401).

**Comment by Lezzio** [comment]
Ok thanks! It's working but I cannot update it while primed yet
(Pseudo code: http://pastebin.com/bHpKAtmh)
