### ISSUE TITLE
Event for changed selected hotbar slot 

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1334]
Currently there is `Player#getHeldItem(...)`. But I would like to know which slot is selected, the index from 0 to 8. Ideally also an event that is fired when the selection changes.

**Comment by ST-DDT** [comment]
@randombyte-developer 

> But I would like to know which slot is selected, the index from 0 to 8.

Mind explaining why you need this feature? What is the usecase?

**Comment by randombyte-developer** [comment]
@ST-DDT My plugin should detect when the user is scrolling(and so changing the selected slot).

**Comment by ST-DDT** [comment]
> @ST-DDT My plugin should detect when the user is scrolling(and so changing the selected slot). 

I can understand the event part of this request. But I don't get why you need the actual slot (index). Isn't the `Slot` instance enough?

**Comment by randombyte-developer** [comment]
The direction of scrolling defines whether a value should increment or decrement. And how many slots are scrolled through defines how much the value gets de/incremented.

**Comment by randombyte-developer** [comment]
@ST-DDT So is this implemented: https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/item/inventory/entity/Hotbar.java ? That's what it need.
An event fired when the selected slot changes would be nice. Otherwise I would constantly recheck the selected index. I'll edit the title of this issue.

**Comment by ryantheleach** [comment]
This would also be useful for a plugin where spells could be casted by using the numbers 1234 on the keyboard.

Resetting the hotbar position to 9, then listening for when it's set to 1234

**Comment by randombyte-developer** [comment]
@ryantheleach Actually I wanted to use instead of scrolling another method of control: Using the numpad numbers 2, 4, 6, 8 for down, left, right, up. But I didn't find a packet that sets the selected slot. So I thought it was impossible. Do you know if the implementation uses a workaround?

**Comment by ryantheleach** [comment]
http://wiki.vg/Protocol#Held_Item_Change_.28clientbound.29

**Comment by Faithcaio** [comment]
ChangeInventoryEvent.Held exists and works afaik

**Comment by randombyte-developer** [comment]
@Faithicaio That's right but it's not the same as "change selected slot". The held event gets only fired when the actual item you are holding changes. If you don't have anything in your hotbar the held event is useless. I had to workaround by filling the player's hotbar with some garbage items to detect scrolling.
