### ISSUE TITLE
Time-measurement inconsistency

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeAPI#1336]
While in most of the Sponge API `java.time` is used for time measurement, in a couple of places the `java.util` time measurement appears. In `GameProfileCache`, `Date` is used instead of `Instant`. Additionally, in `Task.Builder#delay` and `#interval`, `TimeUnit` is used instead of `TemporalUnit`. I feel like the `java.time` time measurement should be used throughout the API.

**Comment by stephan-gh** [comment]
Our scheduler API is not really capable of scheduling in years or even eras so I'm not sure if it really makes sense to use `TemporalUnit` for it. `TimeUnit` limits it to units that make sense.

**Comment by Cybermaxke** [comment]
Can this issue be closed? Or is it still desired to use `TemporalUnit`s in the scheduler API?

**Comment by kashike** [comment]
We could simply add a sanity check to ensure only "valid" `TemporalUnit`s are used.

**Comment by pie-flavor** [comment]
@kashike What is "valid"?

**Comment by kashike** [comment]
not one of (or so):
- `ChronoUnit.CENTURIES`
- `ChronoUnit.DECADES`
- `ChronoUnit.ERAS`
- `ChronoUnit.FOREVER`
- `ChronoUnit.MILLENNIA`
- `ChronoUnit.YEARS`

**Comment by pie-flavor** [comment]
Seems legit. Maybe keep it to a blacklist, though, since the point of TemporalUnit is that people can define their own.

**Comment by ryantheleach** [comment]
`return unit.getDuration().compare(maxDuration) > 0`

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/commit/c9feb4af7d63024b78cde54d3dbbc9c3bb3c25d8 and https://github.com/SpongePowered/SpongeAPI/commit/b8625de73a51d463b07823ed277fb1bea1e5b0e6
