### ISSUE TITLE
ItemEnchantment level overflow

### ISSUE THREAD

**Issue by mbax** [SpongePowered/SpongeAPI#1338]
`ItemEnchantment` throws an exception in the constructor for negative levels, but allows values greater than `Short.MAX_VALUE` which is pretty much the Minecraft limit. This results in the value overflowing to a negative level, which causes other problems in SpongeAPI (see #1337)

I'm not sure if this is a SpongeAPI concern or an implementation concern, but I'm starting this issue out here.

tl;dr
![overflow](http://i.imgur.com/xHS23iq.gif)

**Comment by kinggoesgaming** [comment]
Love the tldr

**Comment by JBYoshi** [comment]
Just understood the tldr. It's not just a funny picture, it has a real meaning.

Spoiler ([base64 decode it](http://base64decode.net/)): b3ZlcmZsb3c=

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/eb4a79b997e44d7ebd3e4b9144cb06bf2b6c01fa
