### ISSUE TITLE
ItemStack equality issue

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeAPI#1339]
@gabizou 

Can't call `net.minecraft.item.ItemStack.equals(org.spongepowered.api.item.inventory.ItemStack)` and vice versa

**Comment by Zidane** [comment]
@Nentify 

What is the issue...?

Your IDE doesn't understand that Minecraft's ItemStack is mixed with Sponge's API interface. So do the following:

```
nmsStack.equals((net.minecraft.item.ItemStack) (Object) apiStack);
```

You need to also be warned about calling the nms equals method. It can NPE for blocks that do NOT have an actual Item representation. Instead, use the static util methods in either our ItemStack interface or Minecraft's ItemStack class.

**Comment by Zidane** [comment]
Also, how is this an API issue? This is Minecraft's code, not ours.

**Comment by Nentify** [comment]
Sorry - gabizou asked me to make an issue regarding this.

Is ItemStack.equalTo(ItemStack) safe? It's the only equality method that seems to take NBT data into account. None of the comparators/other methods I found worked. I will take a look at the static util methods in the ItemStack classes as well.

**Comment by Zidane** [comment]
@Nentify 

equalTo calls:

```
        return net.minecraft.item.ItemStack.areItemStacksEqual(
                (net.minecraft.item.ItemStack) (Object) this, (net.minecraft.item.ItemStack) that
```

**Comment by gabizou** [comment]
@Zidane the reason why I had him open an issue is so that we can expose the different types of equality methods available (such as item type and compound only, versus full equality, versus item type only).

**Comment by ryantheleach** [comment]
Would they just end up being convenience methods for https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/item/inventory/ItemStackComparators.java ?
