### ISSUE TITLE
Lists in config get set to null

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeAPI#1341]
This is my code: http://pastebin.com/9XZzPnV4

On first load, `limit-to-worlds=[]`. However, when I restart, it gets set to `limit-to-worlds=null` if the list is left empty. If there are entries in the list, it loads fine.

The same happens with:

```
        config = loader.load();
        
        CommentedConfigurationNode listNode = config.getNode("list-node");

        if (listNode.isVirtual()) {
            listNode.setValue(new ArrayList<String>()).setComment("test b node");
        }

        loader.save(config);
```

**Comment by Zidane** [comment]
@Nentify 

https://github.com/zml2008/configurate

Post your issue there.
