### ISSUE TITLE
Add implementation entity AreaEffectCloud

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeAPI#1343]
Hi,
Please can you implement the entity "AreaEffectCloud" to access to this values : 
  private PotionType potion;
  private final List<PotionEffect> effects;
  private int duration;
  private int waitTime;
  private int reapplicationDelay;
  private boolean colorSet;
  private int durationOnUse;
  private float radiusOnUse;
  private float radiusPerTick;

It's very usefull for holograms

**Comment by Zidane** [comment]
Open this ticket on SpongeCommon. API doesn't do implementation.

**Comment by lesbleu** [comment]
He needs to create the keys and functions in SpongeAPI because there are no functions in [https://github.com/SpongePowered/SpongeAPI/blob/fa7ce8e776691966b64a893ee09820799dfaa4df/src/main/java/org/spongepowered/api/entity/AreaEffectCloud.java](AreaEffectCloud)
