### ISSUE TITLE
Event : PlayerRenameEntityEvent ?

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeAPI#1345]
Hi,
It is possible to create this event ? 
Or I must check the event "InteractEntityEvent" and check if the player interact with the entity with nametag ?
Or I must check the event "ChangeDataHolderEvent" ?

**Comment by gabizou** [comment]
I believe this event would best fit in the `ChangeValueEvent`, at which point can be subclassed specifically for the type of data being changed. Closing as it's yet another event to add with #596
