### ISSUE TITLE
Canceling DropItemEvent.Dispense removes the item from inventory. 

### ISSUE THREAD

**Issue by games647** [SpongePowered/SpongeAPI#1346]
If someone tries to drop an item and the event is cancelled, the item stack will be reduced and the item won't be dropped (as it should). I tried to relogin in order to test if this a client side bug, but it appears that it isn't. I still have the reduced stack count.

Tested using 
forge-1.10.2-12.18.1.2073-universal
and spongeforge-1.10.2-2073-5.0.0-BETA-1689

**Comment by Zidane** [comment]
Not an API issue. Check if tickets exists on SpongeCommon and create one if it doesn't.
