### ISSUE TITLE
Expose TeleportHelper's safe floor/body material checks to plugins

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#1349]
Thanks to @dualspiral's rewrite of `SpongeTeleportHelper`, the class's code is now much cleaner. However, it uses a hardcoded list of Vanilla materials. This means that mod blocks may either be erroneously detected as an unsafe body material, or erroneously detected as a safe floor material.

It would be nice to expose this information through the API, such that a plugin could mark a particular `BlockType`/`BlockState` as safe or unsafe for head/floor locations for safe teleportation.

**Comment by ryantheleach** [comment]
If we are going as far as this, configuration option? Otherwise how is mod support going to work?

**Comment by bloodmc** [comment]
It would have to be a config that we register on startup. Can't expect mods to do anything with our API.

**Comment by ImMorpheus** [comment]
Closed by https://github.com/SpongePowered/SpongeCommon/commit/5a35b18813d49d583c53a9eb2afcf2e30663eb36

**Comment by ryantheleach** [comment]
Reflecting on this in 1.16 / 2020, the answer would be to register some block tags, akin to `valid_spawn`
