### ISSUE TITLE
No way to check clicked button for general InteractEvent

### ISSUE THREAD

**Issue by Redrield** [SpongePowered/SpongeAPI#1351]
I was trying to make use of something similar to InteractBlockEvent.Secondary, except for a general InteractEvent (Where I don't care if the client clicked a block, an entity, etc) and I found that there was no such event

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/SpongeAPI/blob/fa7ce8e776691966b64a893ee09820799dfaa4df/src/main/java/org/spongepowered/api/event/action/InteractEvent.java#sourcegraph&def=JavaArtifact/org.spongepowered/SpongeAPI/-/org/spongepowered/api/event/action/InteractEvent:type&L36-43

**Comment by Redrield** [comment]
@ryantheleach My point is that there's no way to check whether it was the primary or secondary button clicked in the event.

**Comment by Aaron1011** [comment]
@Redrield: You can check if it's an instance of `InteractBlockEvent.Primary` or `InteractEntityEvent.Secondary` in your listener.

If you want to, you can use an [`event filter`](https://docs.spongepowered.org/master/en/plugin/event/filters.html#event-type-filters) to accomplish this.

**Comment by Redrield** [comment]
@Aaron1011 As I said, I want the event to fire no matter if they're clicking on a block, or not. Is the InteractBlockEvent fired on clicking something like an entity, or air?

**Comment by Deamon5550** [comment]
@Redrield so listen to `InteractEvent` and if its an instance of `InteractBlockEvent.Primary` or `InteractEntityEvent.Primary` then its a primary click, otherwise its a secondary click.

**Comment by Zidane** [comment]
Closing as this is a none issue and @Deamon5550 is spot on the mark.
