### ISSUE TITLE
GenericArguments.entity is difficult to use

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeAPI#1353]
Since `GenericArguments.entity` has selector support, it can return a `List<Entity>` when a selector is used, or just an `Entity` if a UUID is used. This makes it difficult to extract the argument. I propose that the official type be made `List<Entity>`, or that a separate method be created for using selectors vs. uuids.

**Comment by ryantheleach** [comment]
I was wondering why I was having issues with this.

Isn't this why we have CommandContext::getOne and CommandContext::getAll

**Comment by kenzierocks** [comment]
Hmm, you actually might be right about that. I'm looking at the implementation and it looks like it specially handles Iterables. I'm going to double-check.

**Comment by kenzierocks** [comment]
`getAll` does indeed handle this. I misread the implementation.
