### ISSUE TITLE
API for scoreboard tags

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeAPI#1355]
It looks like there's no API for [scoreboard tags](http://minecraft.gamepedia.com/Scoreboard#Tags_commands). I'd like to have one added before #1270 is merged, since there's also a new selector type based on it.

**Comment by AlphaModder** [comment]
Is there any reason to attach this to the scoreboard API in any way rather than just a `DataManipulator` on entities? As far as I can tell, other than sharing a base command, these tags have nothing to do with scoreboards whatsoever.

**Comment by ryantheleach** [comment]
@AlphaModder The multiple scoreboard support maybe? How else would you handle people potentially creating tags in multiple scoreboards.

**Comment by AlphaModder** [comment]
@ryantheleach That's the only thing I could think of as well, but as you say, it doesn't really have a meaning, since the reason for multiple scoreboards is that we can show different scoreboards to different players, but tags are not visible to players.

**Comment by ryantheleach** [comment]
Yeah, the only thing I can really think of is if it's used for client side prediction anywhere, doubtful though.
