### ISSUE TITLE
Provide the way for modifying DisabledSlots flags of ArmorStand

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/SpongeAPI#1358]
ArmorStand have modifiable DisabledSlots NBT tag. It's used for locking specific slot's interaction. For example, disabling placing a helmet, or replacing boots, or removing chestplate or held items, etc.

This issue is for providing the way for reading and changing this data through API.

**Comment by parlough** [comment]
I completely forgot about this and I had two solutions ready to go API wise. I will try to get to this soon once summer starts and before 7.1 is released!

**Comment by ImMorpheus** [comment]
Added by https://github.com/SpongePowered/SpongeAPI/pull/2010
