### ISSUE TITLE
Causeable Interface

### ISSUE THREAD

**Issue by kmecpp** [SpongePowered/SpongeAPI#1366]
It would be nice if there was a `Causable` interface, or something of a similar name, that contained a default `asCause()` method that wrapped the current object in a Cause. Classes such as Entity could implement it and plugin authors could use it on their main plugin classes, or any other class they use as a cause. It would improve clarity as classes marked as Causable are clearly intended to be used as a Cause, and would also make current code more concise.

```
Cause.of(NamedCause.source(getPlugin()));
vs.
getPlugin().asCause();
```

If it sounds like a good idea I'd be happy to submit a PR.

**Comment by ryantheleach** [comment]
Doing this as per your example you lose the "names" part of the cause.

**Comment by kmecpp** [comment]
@ryantheleach It would be easy to provide overloaded methods to support more functionality.

```
	default Cause asCause() {
		return asCause(NamedCause.SOURCE);
	}

	default Cause asCause(String name) {
		return Cause.of(NamedCause.of(name, this));
	}
```

**Comment by gabizou** [comment]
Could you clarify what the point of it is? None of the methods that currently use `Cause`s are meant to have single objects within the `Cause`...

**Comment by kmecpp** [comment]
Originally I thought this would be useful as just the root of the cause, but with more causes its impact becomes less significant.
```
Cause.of(NamedCause.of("root", getPlugin()), NamedCause.of("second", second), NamedCause.of("third", third));
vs.
getPlugin().asCause(NamedCause.of("second", second), NamedCause.of("third", third));
```

So I'm not really sure its worth it anymore. as the relative amount of code saved decreases the longer the cause chain is.

**Comment by gabizou** [comment]
I feel like people also forget that the `Cause.Builder` literally provides easier methods to avoid having to make `NamedCause`s every time:

```
Cause.source(getPlugin()).named("second", second).named("third", third).build();
```

**Comment by kmecpp** [comment]
Did not realize that sorry, closing the issue.
