### ISSUE TITLE
Overhaul BlockTraits System

### ISSUE THREAD

**Issue by AlphaModder** [SpongePowered/SpongeAPI#1368]
I was looking through the block traits, and noticed that for some reason, for traits that are shared between several blocks, we have a specific version for each type of block with the trait. For example, the trait for an open fence gate has six versions for some reason: `ACACIA_FENCE_GATE_OPEN`, `BIRCH_FENCE_GATE_OPEN`, `DARK_OAK_FENCE_GATE_OPEN`, and so on. (Also, the oak one is just `FENCE_GATE_OPEN` with no prefix, which is confusing.) 

There doesn't seem to be any point in separating out these traits, especially considering in vanilla's code they are not separate. 

While it's clearly wrong that they are being separated by the type of wood, this also brings up the question of more general traits. Is a fence gate being open a different trait than a door being open? What about the shown parts for many objects that join together like fences and glass panes and such?

**Comment by kashike** [comment]
>There doesn't seem to be any point in separating out these traits, especially considering in vanilla's code they are not separate.

Exactly.
```java
public class BlockFenceGate extends BlockHorizontal
{
    public static final PropertyBool field_176466_a = PropertyBool.func_177716_a("open");
    public static final PropertyBool field_176465_b = PropertyBool.func_177716_a("powered");
    public static final PropertyBool field_176467_M = PropertyBool.func_177716_a("in_wall");
```

**Comment by AlphaModder** [comment]
The `BlockTrait` rabbit hole deepens! 
I can't see the point of `EnumTrait`s at all currently. 
With a few exceptions, like `Direction`, we tend to avoid enums entirely in Sponge.

Since there are no exposed enums, there is no useful way to do anything with the values of `EnumTraits`. They do seem to have corresponding `CatalogType`s, for example `DIRT_VARIANT` and `DirtType` (inconsistent naming!), but `CatalogType`s are not enums, so this doesn't really help. Perhaps we need a `CatalogTypeTrait` in addition to `EnumTrait`?

**Comment by ImMorpheus** [comment]
AFAIK this was fixed by the data API.

> For example, the trait for an open fence gate has six versions for some reason: ACACIA_FENCE_GATE_OPEN, BIRCH_FENCE_GATE_OPEN, DARK_OAK_FENCE_GATE_OPEN, and so on. (Also, the oak one is just FENCE_GATE_OPEN with no prefix, which is confusing.)

We now have `Keys#IS_OPEN` which handles doors, fences and trap doors.
