### ISSUE TITLE
Target location events

### ISSUE THREAD

**Issue by liach** [SpongePowered/SpongeAPI#1369]
Several events in the API have `Location<World>`s in which they are fired. Here I suggest the addition of an event interface, probably named `TargetLocationEvent`, which will have a method available for getting the list of `Location<World>`s involved in the event. In my opinion, this can be just done by adding default methods in interfaces that get the location from blocks or entities available, or redirect from existing methods giving the location.

**Comment by liach** [comment]
I just post this for discussion instead of asking for implementation.

**Comment by ryantheleach** [comment]
I think the problem is when multiple locations are involved in a single transaction, whether that be entities, or blocks.

**Comment by liach** [comment]
> getting the list of `Location<World>`s
have `Location<World>`s in which they are fired.

They are already plural.

**Comment by windy1** [comment]
You can just have the events implement `Locatable` instead. No need for YetAnotherInterface<sup>™️</sup>

**Comment by liach** [comment]
@windy1 Well in some events like a batch of block change, one location is obviously not enough.

**Comment by liach** [comment]
Could anyone help add a tag [Events]?

**Comment by ImMorpheus** [comment]
We've moved away from TargetXXXX events.
