### ISSUE TITLE
No API to retrieve a world's sea level

### ISSUE THREAD

**Issue by DemonWav** [SpongePowered/SpongeAPI#1371]
Unless I'm blind, there isn't an API for it. @Deamon5550 wasn't able to find one either, so blame him if I'm wrong.

**Comment by ST-DDT** [comment]
Is this changeable?

**Comment by Deamon5550** [comment]
@ST-DDT In theory, mojang made an effort to replace all hard codings of it with a field in the `1.9` update (although they missed a few places). No reason why it can't be settable though.

**Comment by Zidane** [comment]
@Deamon5550 

What are some of the things that this is used for in the Vanilla code?

**Comment by DemonWav** [comment]
Looks like it's used in some mob AI / spawning checks (bats, ocelots, and squids from what I saw). It's used in BiomeMesa as well for terrain gen, and in chunk for lighting checks, and in a few ChunkProviders. Just the few usages I found after a quick search in IntelliJ.
