### ISSUE TITLE
Introduce #targetplace (or equivalent)

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1373]
https://github.com/SpongePowered/SpongeAPI/pull/1360 being merged means that the old behaviour of #target being the coordinates of the block 

![image](https://cloud.githubusercontent.com/assets/141554/18980607/34ff3ac6-8715-11e6-929d-b55cf9df7ca9.png)

Will now do 

![image](https://cloud.githubusercontent.com/assets/141554/18980617/4a43a4b2-8715-11e6-9c72-0c0de79c7b62.png)

Should #target have the original behaviour of being the location of where you would place a block or should a new target selector be used for the old behaviour?
# targetplace #targetbreak ?

**Comment by DDoS** [comment]
I think that the "#target" behaviour should be that of image number 2 (what it was corrected to). A second target kind called "#targetplace" can be added for the behaviour in image number 1 (what it was previously).

The "#targetplace" position can be computed from "#target" position by adding to it the offsets obtained from `BlockHit.getFaces()`.

**Comment by ImMorpheus** [comment]
"#target" and "#me" were removed in API 8
