### ISSUE TITLE
Boolean command choices

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1386]
[Code](https://github.com/SpongePowered/SpongeAPI/blob/d3240cb977f65b67e39f58ae739bfa887d71b007/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L825)
I understand that's funny(`vermuchso`, `notatall`) but I feel that's confusing and unnecessary when seen in tab completion.

**Comment by ryantheleach** [comment]
Honestly 1 and 0 are more confusing to people that havn't programmed before then verymuchso and notatall
