### ISSUE TITLE
ItemStackBuilder does not accept negative quantities

### ISSUE THREAD

**Issue by ZephireNZ** [SpongePowered/SpongeAPI#1392]
`ItemStack`s are allowed to have negative quantities, and `Inventory#query(ItemStack)` relies on quantity being -1 to ignore stack size differences.

`ItemStack` itself does not set a lower limit, however its builder does. This should be change to make like a bit easier when querying inventories.

**Comment by Mumfrey** [comment]
Actually, given that "item stack with negative size" is actually a bit of a weird concept, and - as you identified - only certain negative values have meaning, effectively making those values semaphores. It would seem to make more sense for the builder to support setting the semaphore via an `ItemStackBuilder::anySize()` or similar setter which _internally_ sets the quantity to -1, but decouples this detail from the consumer code.

**Comment by simon816** [comment]
An issue was made on spongecommon regarding negative stack sizes
SpongePowered/SpongeCommon#150
