### ISSUE TITLE
Custom inventory with archetype MENU_GRID do not implements GridInventory

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/SpongeAPI#1394]
Hi, I'm creating a custom inventory using this method:
`Inventory.builder().of(InventoryArchetypes.MENU_GRID).property("inventorydimension", new InventoryDimension(width, height)).property("inventorytitle", new InventoryTitle(title)).build(myPlugin);`
and I get an ClassCastException when I try to cast the inventory to GridInventory. I was thinking that since the archetype is MENU_GRID, the result would be an instance of GridInventory, but it's not. It's normal ?

**Comment by ST-DDT** [comment]
@Yeregorix Can you include the stacktrace please?

**Comment by Yeregorix** [comment]
http://pastebin.com/Sfd645nf

**Comment by Faithcaio** [comment]
You should be able to query for a GridInventory.
`inventory.query(GridInventory.class)`

**Comment by Yeregorix** [comment]
I did not know, its working thanks !
