### ISSUE TITLE
Expose method to make a player spectate an entity.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1395]
Kane_Hart on IRC was requesting a plugin to allow admins to be able to spectate and scroll through players.

For best results a plugin should probably use the vanilla spectator mechanic as opposed to vanishing people and constantly updating their position.

```
/**
Attempts to make player spectate entity.
returns whether the method was successful.
this method will fail if the player is not in the correct Gamemode.
*/
bool player.setSpectating(@Nullable Entity entity);

Optional<Entity> player.getSpectating();
```

**Comment by gravityfox** [comment]
I think there could be use cases for this beyond just for a spy plugin. Minigames could make use of this.

Like how in some games when you die, you can spectate your teammates.

**Comment by parlough** [comment]
Is this ready to be closed with https://github.com/SpongePowered/SpongeAPI/pull/1422 in or are you looking for more/other functionality @ryantheleach?

**Comment by ryantheleach** [comment]
The only other potential thing is events? if a player is in spectator, is there currently any way of preventing them from settings their own spectate target, or filtering the targets shown to them, if that's unwanted?
