### ISSUE TITLE
ExperienceOrb from mob_spawners problem

### ISSUE THREAD

**Issue by TheoKah** [SpongePowered/SpongeAPI#1400]
When breaking a spawner, we get the SpawnEntityEvent event of the EntityXPOrb BEFORE we get the ChangeBlockEvent.Break event of the mob_spawner, meaning if we cancel the break, experience is still spawned.

Moreover, the source cause of the ExperienceOrbs event in that case is considered a "Placement" from the EntityPlayerMP that breaked the spawner instead of the spawner itself, making it hard to cancel the drop manually.

would it be possible for your to make sure no EntityXPOrb spawns if the break event is cancelled?
also, could you change the cause of the EntityXPOrb spawn to be the spawner and not the player?

thanks :)

**Comment by kashike** [comment]
Could you re-open this on the [SpongeCommon issue tracker](https://github.com/SpongePowered/SpongeCommon/), please?
