### ISSUE TITLE
Cherry-pick: Add methods to ChannelRegistrar for getting existing channels

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeAPI#1401]
The PR https://github.com/SpongePowered/SpongeAPI/pull/1354 still needs to be cherry-picked and merged back into the `bleeding` branch from the `release-4.2.0`. This came up a while ago on the irc, but it hasn't been resolved yet, this is just as a reminder.

**Comment by simon816** [comment]
oh I wrongly assumed bleeding would get merged into master and therefore inherit the commit

**Comment by ZephireNZ** [comment]
There is no master anymore - all changes go to bleeding and then any relevant to older API versions go into stable-x branches.

**Comment by kashike** [comment]
@simon816 Are you going to handle this?

**Comment by simon816** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/bd88c9166c9625e2c7500c1c02a9187523d7d266
