### ISSUE TITLE
Cancelling DropItemEvent.Dispense destroys item

### ISSUE THREAD

**Issue by dogboy21** [SpongePowered/SpongeAPI#1403]
When cancelling the dispense event the item doesn't drop but it is also being removed from the player inventory.

I'm currently using the latest SpongeForge version from Github

**Comment by windy1** [comment]
I cannot reproduce this, are you still experiencing this?

**Comment by dogboy21** [comment]
Yes, I'm still experiencing this

**Comment by gabizou** [comment]
Why has this persisted so long in the API repository. This should've been made on SpongeCommon ages ago...
