### ISSUE TITLE
Player.closeInventory() does not close inventory.

### ISSUE THREAD

**Issue by Musician101** [SpongePowered/SpongeAPI#1404]
As the title states, running Player.closeInventory() does not close an opened inventory despite the method returning True. Currently affects Vanilla and Custom inventories both in 5.1.0-SNAPSHOT and 6.0.0 bleeding.

My method for recreating this is, create a command that closes all players' open inventories and print the result in the console for each player.

**Comment by windy1** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/a0e0fb0c302df092af762c1d2e8b41379f037730
