### ISSUE TITLE
Typo in the InventoryDimension?

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeAPI#1405]
https://github.com/SpongePowered/SpongeAPI/blob/ec86e3c83311490d482cb038f1d09101efa411ca/src/main/java/org/spongepowered/api/item/inventory/property/InventoryDimension.java#L39

Maybe typo?

**Comment by windy1** [comment]
This should go in the OCD list: https://github.com/SpongePowered/SpongeAPI/issues/1000
