### ISSUE TITLE
ClickInventoryEvent.Drop and all subclasses are never fired

### ISSUE THREAD

**Issue by caseif** [SpongePowered/SpongeAPI#1406]
To my knowledge, all sub-events of `ClickInventoryEvent` are implemented besides subclasses of `ClickInventoryEvent.Drop`. This particular event type seems to never be triggered.

**Comment by Deamon5550** [comment]
This should be on SpongeCommon as it is not an api issue.

**Comment by caseif** [comment]
Sorry, wasn't thinking when I made the issue.
