### ISSUE TITLE
Proper Horse, Mule, Donkey and Llama structure.

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeAPI#1412]
The current Horse api expansion (in the 1.11 branch) is done in a way that allows it to backwards compatible. But with the introduction of the Llama's, I don't really the like the structure that the api ends up with: `Llama extends Horse`, and this doesn't make a lot of sense in the way that Llama's aren't even a part of the horse family. So I propose the following structure changes:

![untitled diagram 1](https://cloud.githubusercontent.com/assets/1364375/20284328/e89c92d4-aabc-11e6-8c97-586d7111a3ea.png)

@gabizou

**Comment by Deamon5550** [comment]
> Llama's aren't even a part of the horse family

They are in minecraftia.

**Comment by gabizou** [comment]
@Cybermaxke the goal of the API has never been to say what _should be_ versus _what is_. If Minecraft's base engine is dictating that `Llama`s are extensions of `Horse`s, then so be it. This is what we had to decide on a year and a half ago with regards to our entity hierarchy structures diverging from the vanilla base game. @Zidane and myself spoke about this at length and agreed on the decision that we eventually made then, and this is a decision we make now.

**Comment by gravityfox** [comment]
This is amazing.

Can we pin this issue?

It has a flowchart.

I like flowcharts.

**Comment by Cybermaxke** [comment]
@gabizou There can always be an additional interface which represents the `Horse`s, `Donkey`s, `Mule`s and `Llama`s. Naming the base class `Horse` seems like a bad idea and may lead to confusion.

**Comment by gravityfox** [comment]
@Cybermaxke This is a design decision that has been made multiple times, and will not be reversed.

If you have a problem with hierarchies, go complain to Mojang.

**Comment by gabizou** [comment]
> Naming the base class Horse seems like a bad idea and may lead to confusion.

There's a very good reason to keep it named `Horse`: Backwards compatibility and exact representation of the underlying structure. As I said before closing the issue, this was a decision made in the past that isn't going to be changed.
