### ISSUE TITLE
Long flags not working for non-valued flags

### ISSUE THREAD

**Issue by windy1** [SpongePowered/SpongeAPI#1418]
Long flags only seem to work with values attached

I am unable to create a simple boolean long flag (i.e `--myflag` vs `--myflag=true`). You should be able to. I registered the flag as the documentation says you should (pseudo-code):

```java
CommandSpec.builder()
    .arguments(flags().flag("-myflag").buildWith(none())
    .build();
```

I tried the following executions.

`mycommand --myflag`
`mycommand -myflag`

But the flags is never picked up with

```java
context.hasAny("myflag");
```

However when I change the flag to a single character it works as expected.

**Comment by windy1** [comment]
Whoops ignore this, 'twas an error on my end.

**Comment by kashike** [comment]
What was your error?

**Comment by windy1** [comment]
I had stored the flag in a static variable and was trying to receive it with the `-` lol :P
