### ISSUE TITLE
Send BookView

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeAPI#1420]
When sending a bookview to a player in 1.11 nothing appears.
Code I used to test:
```java
((Player)commandSource).sendBookView(BookView.builder().author(Text.of("Server Staff")).title(Text.of("Welcome")).addPage(Text.of("Welcome to Our server!")).build())
```

**Comment by ST-DDT** [comment]
This is an implementation issue as far as I can tell.
Which server implementation do you use? SpongeForge or SpongeVanilla
If you used SpongeForge reopen the issue there. If you used SpongeVanilla reopen the issue there.
If its affects both reopen it in SpongeCommon. Please also add the build versions that you used for testing.

Is there a stacktrace or anything in the logs that might help fixing this issue?
I assume it has something to do with: [BookFaker](https://github.com/SpongePowered/SpongeCommon/blob/1.11/src/main/java/org/spongepowered/common/util/BookFaker.java) -> Common

**Comment by ghost** [comment]
I will move this over to spongevanilla. Closing issue.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeVanilla/issues/285
