### ISSUE TITLE
Method to check if a player is real

### ISSUE THREAD

**Issue by Xfel** [SpongePowered/SpongeAPI#1431]
There should be a method to check if a `Player` is real or a fake player. Right now, there is no reliable, efficient way to do this in sponge.
There is a method for this in SpongeCommon (https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/SpongeImplHooks.java#L79), but unfortunately this isn't exposed to the API.

**Comment by Maxqia** [comment]
I'd like to add that I'd like the method to be moved to the Player (EntityPlayerMP) class while anyone's at it. (I might take a crack at it myself)

**Comment by bloodmc** [comment]
FakePlayer is a forge only concept, use internals if you want to check for it.
