### ISSUE TITLE
Entity AI should always have an owner

### ISSUE THREAD

**Issue by liach** [SpongePowered/SpongeAPI#1432]
In vanilla Minecraft, entity AIs are constructed with an owner. Currently, in Sponge API, an `AITask`'s method for accessing the owner only gives an `Optional` one.

Reasons to always give an owner:
1. In the API, AIs are always built with owners. The owner always exists from the API's side.
2. Some careless modders may assign an AI from one entity to another of the same type (horrible experience). An always-exist owner necessarily prevents such faults.

**Comment by liach** [comment]
Although in `EntityAIBase` in MCP, there isn't a field containing the owner of the AI, all vanilla AIs have a field for its owner. For mods, most of them do because modders learn from vanilla.

**Comment by gabizou** [comment]
> Although in EntityAIBase in MCP, there isn't a field containing the owner of the AI, all vanilla AIs have a field for its owner. For mods, most of them do because modders learn from vanilla.

While vanilla is somewhat true, 

> For mods, most of them do because modders learn from vanilla.

This is where you wholeheartedly can never make assumptions, ever.
