### ISSUE TITLE
Some keys for ArmorStand are missing.

### ISSUE THREAD

**Issue by Limeth** [SpongePowered/SpongeAPI#1435]
As [this utility](http://haselkern.com/Minecraft-ArmorStand/) suggests, there should be an `Invulnerable` and `DisabledSlots` key in the `Keys` catalog.

**Comment by gabizou** [comment]
Is this for 1.11 or 1.10.2? 1.10.2 doesn't show any of this currently.

**Comment by parlough** [comment]
This will be partially solved by https://github.com/SpongePowered/SpongeAPI/pull/1688

**Comment by parlough** [comment]
Taking care of `DisabledSlots` as well.

**Comment by parlough** [comment]
With InvulnerabilityData supporting this, refer to https://github.com/SpongePowered/SpongeAPI/issues/1358 for supporting disabled slots. Will finish my work on it soon.
