### ISSUE TITLE
API 6.0.0 .. ShulkerBoxes not in BlockTypes

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeAPI#1441]
Using Api 6.0.0 (Shaded #28) for porting plugins to 1.11 server...
There are no shulker-boxes listed as the enum/constant list for BlockTypes, yet there are shulker-boxes returned as block-type data in sponge.

**Comment by stephan-gh** [comment]
It was added in https://github.com/SpongePowered/SpongeAPI/commit/da8e70012f96bab9891ac391eba573584005807b, we will update the builds on the Maven repository and downloads page as soon as possible. You can build SpongeAPI locally if there are changes that haven't been pushed to the Maven repository yet.

**Comment by stephan-gh** [comment]
A new build with the latest commits is available now.
