### ISSUE TITLE
Can't set inventory's name

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/SpongeAPI#1443]
It's impossible to set an Inventory's name unless you create an entirely new Inventory through an InventoryBuilder. This is kind of delaying development of one of my plugins, and I don't see an actual reason why we couldn't change the inventory's name on demand.

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/43d84967ccc730c54015dcedde612ad4d43424ee
