### ISSUE TITLE
TextStyle#negate has incorrect order of parameters

### ISSUE THREAD

**Issue by Favorlock** [SpongePowered/SpongeAPI#1445]
https://github.com/SpongePowered/SpongeAPI/blob/871fcd1b9cddc82fefce9fdecc1ac690ae6762dd/src/main/java/org/spongepowered/api/text/format/TextStyle.java#L326

The order should be:

1. bold
2. italic
3. underline
4. strikethrough
5. obfuscated

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/402597804d55404e59dbdaabda8516a0656eb6e6
