### ISSUE TITLE
JoinData is this the first time the player joined?

### ISSUE THREAD

**Issue by JonathanBrouwer** [SpongePowered/SpongeAPI#1446]
I would like a method, which returns whether the current connection of a player is the first one.
So in other words, whether the player joined for the first time.

I think the JoinData class would be best for this. Maybe JoinData#isFirstTime?

**Comment by simon816** [comment]
There's a method in `Player`, [`hasPlayedBefore`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/entity/living/player/Player.java#L224)

**Comment by JonathanBrouwer** [comment]
Couldnt find it, I am stupid. Better searching next time.
