### ISSUE TITLE
GenericArguments: Long Command Flags not tab completing.

### ISSUE THREAD

**Issue by drakmirv** [SpongePowered/SpongeAPI#1447]
SpongeAPI/src/main/java/org/spongepowered/api/command/args/CommandFlags.java

On line 271, I can see my long command being added to the retStrings collection.

However, that is never returned.  Instead, after the if check passes to line 280, it moves down to a "return null" statement.

My proposal is to add a "return retStrings;" after line 279.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/320df402f83d6a75da2715e8a2a9cb1598413543
