### ISSUE TITLE
When a world directory is deleted, the world's gets config is reset!

### ISSUE THREAD

**Issue by xcube16** [SpongePowered/SpongeAPI#1451]
When a world directory is deleted, the next time the server is started, that world's config in config/sponge/worlds gets reset!
This can be very annoying for admins that want to reset there world, only to have to reconfigure it also.
And it gets worse! Configurations that effect generation will not be applied to the spawn chunks, as they are generated before the admin has a chance to modify the new config.
As a work-a-round, one can delete all the region files to reset the terrain without triggering a config **** up.

This bug happens on both SpongeForge and SpongeVanilla.

**Comment by xcube16** [comment]
I should add that I am using the stable-5 branch (MC 1.10.2).

**Comment by Zidane** [comment]
This is the API. If still an issue, re-open on SpongeCommon.
