### ISSUE TITLE
Confusion of arguments and parameters in TextTemplate

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1452]
I think there is a confusion of arguments and parameters in [TextTemplates](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/text/TextTemplate.java).
As [this SO answer](http://stackoverflow.com/a/1788926) says, arguments are the values and parameters are the variables.
Now seeing that an [`Arg`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/text/TextTemplate.java#L381) is a variable that gets filled later and parameters are [applied](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/text/TextTemplate.java#L190), I think this is not right. The naming should be switched.

**Comment by randombyte-developer** [comment]
Is this simple but breaking change planned for API 6?

**Comment by ImMorpheus** [comment]
As of API 8 we are now using [Adventure](https://github.com/KyoriPowered/adventure). 

This means the old Text api is gone and all the related issues (especially those involving breaking changes) are no longer relevant, therefore I'm closing this.
