### ISSUE TITLE
Initializing EntitySnapShot Error. 

### ISSUE THREAD

**Issue by axle2005** [SpongePowered/SpongeAPI#1453]
I'm trying to grab an EntitySnapShot from inside a listener (Block Drop). I have the order set to Order.Pre, as required by initializing the snapshot and it constantly errors saying it can not be initialized after Pre. 

Error: http://pastebin.com/DDAfvUnH
Code: http://pastebin.com/RhR2MBwh
FML Log: https://gist.github.com/axle2005/605350a7fdb01ac909a31e3d09eebaf1

I used SpongeAPI 5.0.0, and also tried to compile with SpongeForge 2022.

**Comment by XakepSDK** [comment]
Try DropItemEvent.Pre event

**Comment by axle2005** [comment]
DropItemEvent.Pre worked fine.
