### ISSUE TITLE
Experience desync when cancelling ClickInventoryEvent in Anvil.

### ISSUE THREAD

**Issue by Musician101** [SpongePowered/SpongeAPI#1454]
When clicking the result slot in an Anvil and cancelling the click via an event that extends ClickInventoryEvent doesn't update the experience on the client. If the player disconnects and reconnects, the desync will be fixed.

**Comment by Musician101** [comment]
I neglected to mention this occurs in the SpongeVanilla 1.10.2-5.1.0 Beta 366 jar.

**Comment by Zidane** [comment]
This is the API. If still an issue, reopen on SpongeCommon.
