### ISSUE TITLE
Virtual Anvil Does Detect Result.

### ISSUE THREAD

**Issue by Musician101** [SpongePowered/SpongeAPI#1455]
Using SpongeVanilla 1.10.2-5.1.0 Beta 366.

Using the Inventory Builder to create a custom Anvil Inventory and opening it for a player does not properly calculate the final result of any items put into it. The client is able to see what the result is supposed to be, but when it is clicked, the inventory acts as if the click event is cancelled and the text field to change an item's name is reset to it's previous state.

**Comment by Faithcaio** [comment]
This happens because the logic for setting the output is inside the Container.
Currently all custom inventories are using a custom container without any logic.

**Comment by Musician101** [comment]
I'm guessing the logic is on the TODO list.

**Comment by Faithcaio** [comment]
this was fixed quite some time ago
