### ISSUE TITLE
API does not expose block or item metadata, heavily limits modded minecraft oriented plugins.

### ISSUE THREAD

**Issue by kosakriszi** [SpongePowered/SpongeAPI#1456]
A precursor: I understand that the developers of the API decided to not expose the above information due to their dwindling usage in the Minecraft game proper, but please hear me out.

I am working on an ore alert plugin, one that notifies certain permission holders if an ore is mined, and would like to make it configurable. I am writing the plugin to primarily be used in a heavily modded environment (but would also like it to work on a SpongeVanilla server), and would like to allow the user to specify the exact block they would like to listen for. Unfortunately, the modded scene seems to be lacking when it comes to named variants of blocks, and many mod ores are only identifiable via block meta values.

Is there any way for me to obtain this data with a purely Sponge API based plugin?

**Comment by Zidane** [comment]
https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/block/BlockState.java#L140

There is no way a mod can NOT use BlockStates 1.8+. You can literally know all the BlockStates at any time by printing:

```
Sponge.getRegistry().getAllOf(BlockState.class); // Take the collection returned and pipe it to where-ever
```

By reading the feedback of that above code and the link I linked you, you can get the properties easily. As for Items, we expose:

https://github.com/SpongePowered/SpongeAPI/blob/5a6709d2ea3be5424c9bf8d871a237df03f0e576/src/main/java/org/spongepowered/api/data/manipulator/mutable/item/DurabilityData.java

You have everything you need. There is literally no reason to have hard ids ever.

**Comment by kosakriszi** [comment]
Awesome, thank you!

**Comment by gabizou** [comment]
Just be prepared that if you try to get all `BlockState` instances, you will have a giant list: https://gist.github.com/gabizou/679d8b5946b319928215 as an example with 3 mods added to the game ;)
