### ISSUE TITLE
World Save Method not implemented

### ISSUE THREAD

**Issue by JessiahC** [SpongePowered/SpongeAPI#1458]
Class org.spongepowered.api.world.World;

save() Method is not implemented, results in:

`java.lang.AbstractMethodError: Method net/minecraft/world/WorldServer.save()Z is abstract
        at net.minecraft.world.WorldServer.save(SourceFile) ~[ls.class:?]`

**Comment by gabizou** [comment]
Re-open in SpongeCommon, not SpongeAPI.
