### ISSUE TITLE
coveralls.io leaks your information

### ISSUE THREAD

**Issue by aviaoh** [SpongePowered/SpongeAPI#1459]
hi @Zidane,
I recently saw your commits in my coveralls.io account:
![image](https://cloud.githubusercontent.com/assets/22256371/21893720/f4438d26-d8e4-11e6-965e-eb7b3630dd0f.png)

I also opened issue: https://github.com/lemurheavy/coveralls-public/issues/909
FYI.

**Comment by stephan-gh** [comment]
I don't know why these commits show up on your coveralls.io account, but it is definitely not a commit from a private repository: https://github.com/SpongePowered/SpongeVanilla/commit/b51d36c. 

It's also quite interesting that the commit of https://github.com/kainosnoema/rack-lineprof/issues/5 was on exactly the same day as our commit above.
