### ISSUE TITLE
Per-Player Viewing/Spawning

### ISSUE THREAD

**Issue by Jimmeh94** [SpongePowered/SpongeAPI#1461]
I'm coming from a couple years of developing on Bukkit and Spigot, and must say, I really like what Sponge is doing! One thing that I think would be amazing is having per-player viewing and spawning. Let me give an example:

In Spigot, there was a Player#hidePlayer(Player toHide). The "toHide" player then couldn't be seen specifically by the first Player object. This is incredibly handy. I think it'd also be amazing to do the same thing with entity spawning (I haven't currently looked much into Sponge's handling of entity spawning). Being able to do something like:
Entity#spawn(Location, Collection<Player>) would be amazing! The Collection<Player> being the players that the entity spawn packet is sent to. 

I know all of this could be achieved via NMS, and that's normally how I'd do it, but I was recommended by a couple people to submit this idea first. I hope this makes sense! :D

Oh, I was directed to this issue: https://github.com/SpongePowered/SpongeAPI/pull/1046

I don't know if this would be doing the same thing that I suggested, but there really hasn't been an update that, so I thought I'd submit my idea anyways.

**Comment by Deamon5550** [comment]
Yeah this should be covered by #1046 which will eventually get some love.

**Comment by Jimmeh94** [comment]
Ah okay. Here's hoping it's sometime soon! Until then, back to NMS

**Comment by ryantheleach** [comment]
I thought this was already covered by the vanish API's? I'm probably wrong though, been out of it a while.

**Comment by Deamon5550** [comment]
@ryantheleach yes the vanish apis handle this if you want to hide someone from every player but this is about hiding one player specifically another player while still letting them be visible to others.
