### ISSUE TITLE
TextTemplate args should have actions

### ISSUE THREAD

**Issue by Wundero** [SpongePowered/SpongeAPI#1462]
`TextTemplate` has the `Arg` subclass, which represents an argument that can be replaced. `Arg` currently stores the key, the open and close strings, the format (color and style), whether it is optional, and a `@Nullable` default value (as a `Text`). I think that it should also include a `ClickAction<?>`, `HoverAction<?>` and `ShiftClickAction<?>` as well, to make it more customizable. This shouldn't affect any implementations as it is a class in the API.

**Comment by windy1** [comment]
Adding an empty `Text` object (or adding these actions to the supplied text) should achieve what you're looking for.

**Comment by Wundero** [comment]
Perhaps it might be effective to have a `TextOptions` class, which holds both a `TextFormat` and the actions for a text, as optionals.

**Comment by ImMorpheus** [comment]
As of API 8 we are now using [Adventure](https://github.com/KyoriPowered/adventure). 

This means the old Text api is gone and all the related issues (especially those involving breaking changes) are no longer relevant, therefore I'm closing this.
