### ISSUE TITLE
Get the hand state

### ISSUE THREAD

**Issue by Katrix** [SpongePowered/SpongeAPI#1464]
It would be nice if there was some way to get the hand state of a player. What I mean with this is to get if a hand is being used (rightclicking). In forge you have stuff like `player.isHandActive()` or `player.getActiveItemStack()`. One example of a use for this would be to do something special if a player is using a shield.

While it is possible to do something similar using `UseItemStackEvent` it feels cubersome, and also doesn't give you information about which hand the action happened in.

**Comment by Cybermaxke** [comment]
I would add a key `Key<OptionalValue<HandType>>` to represent the active hand and you should be able to get the `ItemStack` through the inventory api. A helper method would still be nice though.

**Comment by Katrix** [comment]
What I was thinking as well. Even though from what I've seen vanilla keep the two concepts seperate I can't think of any case where that would really matter.

**Comment by kashike** [comment]
related:
https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/entity/ArmorEquipable.java#L125-L145
https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/property/entity/DominantHandProperty.java
https://github.com/SpongePowered/SpongeAPI/search?utf8=%E2%9C%93&q=HandType&type=Code

@ZephireNZ was working on hand stuff, maybe will continue?

**Comment by ImMorpheus** [comment]
PR merged (https://github.com/SpongePowered/SpongeAPI/pull/1969)
