### ISSUE TITLE
Get all blockstates valid for a set of traits

### ISSUE THREAD

**Issue by Katrix** [SpongePowered/SpongeAPI#1466]
At the moment if you create a blockstate and assign a few (not all) traits to it, the rest of the fields stay as their default value. This is fine when we are talking about two concrete blockstates, but when we are comparing them it doesn't always work as well. For example if you are looking at leaves, and want to only get all the leaves in the area that check if they can decay and also doesn't decay, ignoring the variant of the leaves, there are four different blockstates that you might have to check against.

The big use case for this I feel is in configs. Sure we can use Keys for many of these cases, but keys are hard to specify in a config.

I think the simplest way to get something like this is to have some class maybe named `BlockStateCollection` (or similar) which then contains methods like `matches(BlockState state)` which checks if a given state is contained in the collection and `getCollection()` which returns something like `Collection<BlockState>`

**Comment by gabizou** [comment]
Closing as it's been added to both API 5.1.0-SNAPSHOT and API 6.
