### ISSUE TITLE
ItemStack#setQuantity(int) thrown IllegalArgumentException

### ISSUE THREAD

**Issue by rexbut** [SpongePowered/SpongeAPI#1473]
Since commit https://github.com/SpongePowered/SpongeCommon/commit/629b59f3c1bf57a2c6df57a179b2473965713f72,

The exception IllegalArgumentException which is thrown by the "[ItemStack#setQuantity(int)](https://github.com/SpongePowered/SpongeCommon/commit/629b59f3c1bf57a2c6df57a179b2473965713f72)" function  became useless.

Would it be possible to remove it?

**Comment by gabizou** [comment]
Stacktrace?

**Comment by rexbut** [comment]
I meant that it was now useless to leave the exception "IllegalArgumentException" in the header of the function because it is never launched.

**Comment by kashike** [comment]
this should go in the OCD issue
