### ISSUE TITLE
No way to set the location of an offline player

### ISSUE THREAD

**Issue by Dragoncall** [SpongePowered/SpongeAPI#1475]
Currently there is only one way to alter the position of an offline player, which is by writing to the NBT's. As this is really unhandy and (IMO) unspongy, I would request another option to do this.
I've looked into the User class, which is the class that resembles an offline player. In this class there are ways to set/get the inventory,... but no way to alter the location of the player. If this is a deliberate choice, would someone explain to me why you chose not to?
Other contributions are welcome too! 😃

**Comment by Dragoncall** [comment]
Is there any update on this? :)

**Comment by Faithcaio** [comment]
@gabizou shouldn't this be data?

**Comment by Eufranio** [comment]
`User#getLocation()` and `User#setLocation()` would be nice.

**Comment by gabizou** [comment]
Thought about this for a bit, we can't realistically use a `Location` since you can have a player in an unloaded world (let's think about multi-dimensions). At most we can provide a position and world id, but certainly not a `Location` for offline Users. And @Faithcaio I'd rather it not be data, but it was an intention long ago when first writing the Data API and @Zidane shot me down on the idea :P

**Comment by Faithcaio** [comment]
so smth like `setLocation(Vector3d, WorldProperties)` `WorldProperties getOfflineWorld` `Vector3d getPosition`?

**Comment by ryantheleach** [comment]
WorldProperties or would it be a dimension id :-S

**Comment by gabizou** [comment]
Why world properties? I thought you could get a world or world properties or whatever you wanted with just a uuid, so why wouldn't we want to use a `UUID`? It doesn't make sense to me to use anything different (especially how world properties can be created without having an actual world of which to focus on setting a player location for a world that doesn't exist.

**Comment by Faithcaio** [comment]
I guess UUID would be fine.
But UUIDs can also be created without having a world backing it up and the UUID is also not what is saved in the Player.

**Comment by gabizou** [comment]
What is saved on the player for their location?

**Comment by Faithcaio** [comment]
```java
NBTTagList nbttaglist = compound.getTagList("Pos", 6);
this.posX = nbttaglist.getDoubleAt(0);
this.posY = nbttaglist.getDoubleAt(1);
this.posZ = nbttaglist.getDoubleAt(2);
this.dimension = compound.getInteger("Dimension");
```

**Comment by Faithcaio** [comment]
how about this @gabizou ? ^
