### ISSUE TITLE
Deprecate key changes properly

### ISSUE THREAD

**Issue by mcmonkey4eva** [SpongePowered/SpongeAPI#1485]
In 6.0.0 some keys were changed.
EG, `armor_stand_marker` is now `is_marker`.

Those should be deprecated safely in such a way that the old keys still exist and point at the new keys.
That way code compiled for 5.0.0 can still run on 6.0.0 - or also just code authors using 6.0.0 can use the only documentation that is publicly available, IE 5.0.0 documentation.

**Comment by ghost** [comment]
@gabizou should I do this in #1484 or would that broaden my scope too much?

**Comment by gabizou** [comment]
@saladoc As long as you can solve it soon. I was going to work on merging the check style changes into stable-5 and bleeding tomorrow.

**Comment by gabizou** [comment]
Just going to close this out as our deprecation policy has been applied and API 6 is no longer supported.
