### ISSUE TITLE
JoinData should be available from Users as well

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeAPI#1488]
Currently `JoinData` can only be obtained from a logged in `Player`. 
However that information would be useful for plugin functions like a `/lastseen` command or automatically cleaning up player-related structures after they have not connected to the server for a time, so it should be made available from `User` objects as well.

**Comment by parlough** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @ghost! I've moved your issue to [SpongePowered/SpongeCommon#1890](https://github.com/SpongePowered/SpongeCommon/issues/1890).
