### ISSUE TITLE
Negative number arguments are interpreted as flags

### ISSUE THREAD

**Issue by dogboy21** [SpongePowered/SpongeAPI#1489]
Numeric arguments in commands, such as `GenericArguments.doubleNum` or `GenericArguments.integer` with a negative number are interpreted as a short flag, not as a negative number. This causes the command to throw an exception.

**Example:**
![Example](https://ss.myftb.de/FQs2y_8R.png)

**Comment by zml2008** [comment]
Did the setUnknownFlagBehavior method on the flag builder ever make it in? You'd have to set that to ignore for negative number arguments to work with flags.

**Comment by ghost** [comment]
Maybe it would be wise though to disallow flags starting with a number. I can see how this would be confusing.
