### ISSUE TITLE
Expose 1.10+ added DamageSources

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#1496]
In 1.10-1.10.2, a few new internal `DamageSource`s have been added. I'll put up a table for both versions as they need to be added to each API branch respectively.

1.10.2 | Description
------ | -------
`FLY_INTO_WALL` | Flying into a wall horizontally
`DRAGON_BREATH` | EnderDragon specific damage (currently not used however)

1.11.2 | Description
------ | -------
`FIREWORKS` | Apparently, fireworks now deal damage if exploding while still being ridden

All of these may need to be evaluated as to how they're being used internally and through the API, much like how there is the representation of `BlockDamageSource` versus a flat `DamageSource` without a location.

Relatively easy to implement, just marking this as an issue before it is forgotten.

**Comment by parlough** [comment]
The following is connected: https://github.com/SpongePowered/SpongeAPI/issues/1287 (magma from walking on)
