### ISSUE TITLE
No way to check if an item stack will fit in an inventory

### ISSUE THREAD

**Issue by parlough** [SpongePowered/SpongeAPI#1498]
I think a useful addition to the `Inventory` interface would be `willFit(ItemStack stack)`, `hasSpace(ItemStack stack)`, or some similar method to see if an an item stack you want to offer will fit in the inventory. Right now you actually have to offer it and then check if all of them fit, then if not take them back out.

**Comment by Cybermaxke** [comment]
I would prefer `peek` methods to get all the `SlotTransaction`s that would occur when perform `set`, `offer`, etc. And also give it methods to check if it was successful, the rest items that weren't added and maybe a method to easily apply the complete result or a specific `SlotTransaction`.

**Comment by parlough** [comment]
@dualspiral suggested the idea of introducing a `revert` method to `InventoryTransactionResult`, which I think could be a great alternative solution. The problem here is I imagine duplication could occur somehow, so I think the "theoretical" methods are still a better choice.

**Comment by parlough** [comment]
Replaced by https://github.com/SpongePowered/SpongeAPI/issues/1849
