### ISSUE TITLE
Cancelled ClickInventoryEvent still sends a packet to client

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1503]
- Create an inventory and fill it with some items
- Listen to InventoryClickEvent and cancell the event

```Java
   public void onOptionSelect(ClickInventoryEvent event, @First(typeFilter = Player.class) Player player) {
   List<SlotTransaction> transactions = event.getTransactions();
	   for (SlotTransaction t : transactions) {
		   if (t.getOriginal().get(NKeys.MENU_INVENTORY).isPresent()) {
			   event.setCancelled(true);
   		}
	}
}
```
- Player shiftclicks the item in opened inventory. Event is cancelled but player still receives packet which informs the client about item transfer. 
- For a tiny fraction of second the clicked item is present in player's inventory. 
- If the player hits escape (close the inventory) in a correct time the clicked item remains in player's inventory. 

The player cannot interact with the item (drop it on the ground)
 If the player opens eg, chest the item dissapears.

Build used Sponge vanilla 1.11.2-6.0.0-BETA-224

**Comment by Aaron1011** [comment]
> Event is cancelled but player still receives packet which informs the client about item transfer.

That's not the result of the client receiving a packet. The container click logic gets executed on both the client and server, meaning that the client will have already performed the shift-click action locally before the server even receives the packet. To see this in action, try setting a thread-only breaking in the server click packet handler, and shift-click an item. You'll notice that the item still transfers, despite the server thread being suspended.

**Comment by Limeth** [comment]
Maybe this is something the client-side Sponge mod would help with in the future. Would be great getting rid of these little nuisances.
