### ISSUE TITLE
ChangeBlockEvent.Place Doesn’t Detect Block Changes Caused By Pluggin

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/SpongeAPI#1506]
So I'm trying to track block changes, specifically when blocks are placed, so I can later undo them. I have an executioner that creates blocks in a specified location, but those block changes are not being detected by my listener. In the listener below, I expected to receive spam messages telling me what blocks were being changed by my executioner, but the event was not fired.

    private final static Set<Transaction<BlockSnapshot>> snapshots = new HashSet<>();
	
    @Listener
    public void onBlockAlteration(ChangeBlockEvent.Place event) {

		snapshots.addAll(event.getTransactions());
		
		Sponge.getServer().getBroadcastChannel().send(Text.of(TextColors.GOLD,snapshots));
    
    }

**Comment by Zidane** [comment]
Closing as this isn't an API issue and needs to be tested again in one of our implementations and reported there.
