### ISSUE TITLE
API Request -Add event for fed mob ready-for-love

### ISSUE THREAD

**Issue by Noobslayer09** [SpongePowered/SpongeAPI#1507]
The State of Sponge video says to get the api requests in pronto...

Can an event be added to the api that is thrown when a mob is fed and the heart-particles get thrown?  That prevents from having to track interactions with entities and checking the hand being held being right food, etc by catching the mob being fed with the correct material at right time; event trigger when particle-throwing trigger occurs..
Note, please do not say "Thats why we have PRs, write it yourself and we'll add - I do not have the codeskills required to add such things

**Comment by liach** [comment]
There is already one...

https://github.com/SpongePowered/SpongeAPI/blob/a4aaeec0007ebd9c3570e41382454e81f875e0a1/src/main/java/org/spongepowered/api/event/entity/BreedEntityEvent.java#L43

**Comment by Noobslayer09** [comment]
That event is thrown when a new mob is about to be born - I mean if I feed a single lone sheep he eventually is heart-ready even without other sheep around to spawn a baby

**Comment by Deamon5550** [comment]
Duplicate #1382
