### ISSUE TITLE
Crafting Events

### ISSUE THREAD

**Issue by malte-laukoetter** [SpongePowered/SpongeAPI#1515]
Currently there is no easy way to do something if an item is crafted in a crafting table or burned in a furnace. 

The only way i found to do something similar is by using the AffectSlotEvent but that only really works for blocking the crafting but doesn't allow to get the items that are crafted, because its already fired in the moment the items are in the grid and not in the moment the items are collected from the Output slot.

**Comment by RobertHerhold** [comment]
Is there any progress on this? It seems pretty important for a lot of plugins (including one I'm working on)

**Comment by MarkHerhold** [comment]
$50 Bounty created: https://www.bountysource.com/issues/42904385-crafting-events

**Comment by Rubbertjuh** [comment]
Added $25 to the Bounty
Would love to see this being added asap ^^

**Comment by Brend-Smits** [comment]
Added 25$ on top of the 50$ bounty. 
Would love to see this being added soon. This is currently holding us back from completing a project that we're working on.

**Comment by Schuwi** [comment]
Am I correct in assuming that this issue has been addressed in bfd7f774a040448907b816f446f331d3cd84710b as it was closed without further comment?

**Comment by ryantheleach** [comment]
There's been several commits relating to crafting events over the past month, and I was involved with testing several of them with faith. This should be well and truly addressed and fixed.
