### ISSUE TITLE
Proposal - Use ASM to generate classes required for custom data

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1519]
..asm or javassist, or any other bytecode manipulation framework, which is sponge/forge already using
Every "custom data" requires you to write ridiculous amount of code which is almost always +- same. 

It would be helpful to have some kind of preprocessing, which generates required classes during sponge startup. (data builder, immutable(builder),. .., Keys...)

It should be enough to specify only one interface which will be used as a proxy and one key variable for a class representing custom data.

eg

    @Persistant //optional annotation, whenever the data will be persistant during server restarts
    public interface SomeCustomData {

        List<String> getSomeStringList();	

        void setSomeStringList(...);	
    }

    public class SomeKeys {

		@DataProxy(SomeCustomData.class)
                @DataQuery("SomeList") //same as current DataQuery#of       
		Key<Value<SomeCustomData>> KEY;
    }

`Sponge.getDataManager().generateDataManipulators(SomeKeys.class, pluginInstance);`all fields annotated with dataproxy would be initialized, basically calls `Sponge.getDataManager().register(SomeCustomDataProxy.class,SomeCustomDataProxy.Immutable.class, new SomeCustomDataProxy.Builder());` (*Proxy classes would be created by asm)

In a next step method `#register` would inject all keys in the class `SomeKeys class` under the hood -
        `SomeKeys.KEY = KeyFactory.makeSingleKey(<typetoken>, <valueof @DataQuery>, "<pluginid>:<classname>, <classname>);`

    DataManipulator a = Sponge.getDataManager().getDataManipulator(SomeKeys.class); //returns instance of previously created datamanipulator
    someEntity.offer(a);
    SomeCustomData data;
    if (!someEntity.get(SomeKeys.KEY).isPresent()) {
        data = Sponge.getDataManager().getProxy(SomeCustomData.class).getClass().newInstance(); //getProxy method would return implementation of SomeCustomData which was created previously, during `#generateDataManipulators call`
    } else {
        data = get(SomeKeys.KEY).get();
    }
     data.setSomeStringList<...>;
     someEntity.offer(SomeKeys.KEY, someCustomData)

**Comment by Deamon5550** [comment]
I swear there is an issue somewhere for this already but I can't find it. But yes this is something we've planned for a long time and have been working towards building the required parts for.

**Comment by kashike** [comment]
@Deamon5550 #1168 / #1198

**Comment by gabizou** [comment]
As @kashike already mentioned, there's a PR that has this already, there's a few steps I need to take for the implementation prior to it being achievable (since it does break a lot of things).
