### ISSUE TITLE
Difference between ItemStack.Builder#add and ItemStack.Builder#keyValue

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeAPI#1523]
What's the difference between [ItemStack.Builder#add(..)](https://github.com/SpongePowered/SpongeAPI/blob/a4aaeec0007ebd9c3570e41382454e81f875e0a1/src/main/java/org/spongepowered/api/item/inventory/ItemStack.java#L210) and [ItemStack.Builder#keyValue(...)](https://github.com/SpongePowered/SpongeAPI/blob/a4aaeec0007ebd9c3570e41382454e81f875e0a1/src/main/java/org/spongepowered/api/item/inventory/ItemStack.java#L179)? Sponge doesn't make any difference and just calls `keyValue()` from `add()` [here](https://github.com/SpongePowered/SpongeCommon/blob/9e6acff2f9c25f346151420d368a26a0e3578a5b/src/main/java/org/spongepowered/common/item/inventory/SpongeItemStackBuilder.java#L115).

**Comment by parlough** [comment]
This is a great question. @gabizou You changed `#add` to just call `#keyValue`. Should we deprecate one of them, maybe `#add` due to its lesser Javadocs and not being the method with the logic?

**Comment by Cybermaxke** [comment]
I would say, lets use the `add` method and remove `keyValue` to be consistent with other data builders. 
`add` is for example also used in (there are probably more cases, and `add` is in general more used in builders):
https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/ImmutableDataBuilder.java#L69
