### ISSUE TITLE
A few issues with SpongeEventFactory

### ISSUE THREAD

**Issue by simon816** [SpongePowered/SpongeAPI#1526]
The following events are unable to be created with the factory:
`achievement.GrantAchievementEvent`
`data.ChangeDataHolderEvent`
`entity.ExpireEntityEvent`
`entity.HarvestEntityEvent`
`statistic.ChangeStatisticEvent`

The following events have `createX()` methods but shouldn't (these are 'base' events):
`action.InteractEvent`
`action.CollideEvent.Impact`
`block.TargetBlockEvent`
`entity.AffectEntityEvent`
`entity.TargetEntityEvent`
`entity.explosive.TargetExplosiveEvent`
`entity.explosive.TargetFusedExplosiveEvent`
`entity.item.TargetItemEvent`
`entity.living.TargetAgentEvent`
`entity.living.TargetLivingEvent`
`entity.living.humanoid.HandInteractEvent`
`entity.living.humanoid.TargetHumanoidEvent`
`entity.living.humanoid.player.TargetPlayerEvent`
`entity.projectile.TargetProjectileEvent`
`game.state.GameStateEvent`
`item.inventory.AffectItemStackEvent`
`item.inventory.AffectSlotEvent`
`item.inventory.TargetContainerEvent`
`item.inventory.TargetInventoryEvent`
`server.ClientPingServerEvent.Response`
`server.ClientPingServerEvent.Response.Players`
`user.TargetUserEvent`
`world.TargetWorldEvent`
`world.chunk.TargetChunkEvent`

**Comment by liach** [comment]
Which ones are still valid? `GrantAchievementEvent`, for example, no longer exists.

**Comment by liach** [comment]
Given `server.ClientPingServerEvent.Response` and `server.ClientPingServerEvent.Response.Players` are not even events, are they still created by the factory?

**Comment by ImMorpheus** [comment]
PR merged
