### ISSUE TITLE
StopSound integration

### ISSUE THREAD

**Issue by Magi1053** [SpongePowered/SpongeAPI#1527]
There is functionality for playSound, found in the Viewer interface, however searching the entire project I was unable to find any mention of it's counterpart stopSound.
http://minecraft.gamepedia.com/Commands#stopsound

**Comment by Magi1053** [comment]
Any update on this feature?

**Comment by Deamon5550** [comment]
We accept pull requests, otherwise you'll just have to wait for a contributor to find the time to add this.

**Comment by Magi1053** [comment]
bump
