### ISSUE TITLE
Config Serializable State Matchers

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1528]
https://github.com/SpongePowered/SpongeAPI/commit/abd6fa8fee5c0f86845e80dd4f9980395aaa0388#diff-c00b1420115c3cf9601763262c66ddbdR307

Awesome work guys, StateMatchers are a good step towards making better configs for blocks :)

Would you consider accepting a PR that made them config serializable in some form, so we had a standard way of specifying "loose blocks" in configs?

**Comment by gabizou** [comment]
Potentially, yes. It would be interesting to see if it can work based on either traits or data keys as well.

**Comment by ImMorpheus** [comment]
PR merged
