### ISSUE TITLE
ItemStack#set(Keys.TREE_TYPE, TreeType) throws failure result.

### ISSUE THREAD

**Issue by gaeqs** [SpongePowered/SpongeAPI#1535]
When I try to edit the TreeType of a ItemStack the DataTransactionResult throws FAILURE even if the ItemStack supports the key TREE_TYPE.

Proof: 
http://prntscr.com/evn0n1
http://prntscr.com/evn0xa

**Comment by gabizou** [comment]
Use gist.github.com instead of screenshots..... And, this isn't an issue for the API, this is an issue for SpongeCommon.
