### ISSUE TITLE
Child command argument parse error handling

### ISSUE THREAD

**Issue by Xfel** [SpongePowered/SpongeAPI#1542]
If using a command spec with child commands and a fallback handler, the behaviour in case of an argument parse error is confusing. If I specify the child command name correctly, but have an error in the child command's arguments, the argument parser will fall back to parse the arguments for the fall back handler.

**Comment by dualspiral** [comment]
In the latest SF for API 7 snapshot, I've added method `childArgumentParseExceptionFallback` to the `CommandSpec`. You need to set this to `false` to get the behaviour you expect above, I opted to make this a non-breaking change for API 7.
