### ISSUE TITLE
Thread safety and Context Calculators

### ISSUE THREAD

**Issue by lucko** [SpongePowered/SpongeAPI#1546]
According to the SpongeDocs, "there are a few parts of Minecraft [and the API] that you can work with asynchronously". One of the given examples is "**permissions handling**".

It was also stated by zml in a permissions implementation document that:
>The plan was to require permissions plugins to be thread-safe

That was certainly also my understanding until now. 

However, it was perhaps overlooked that the permissions API also depends on other systems within Sponge, namely contexts.

Fundamentally, if the permissions API is deemed to be thread safe, then all [`ContextCalculator`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/service/context/ContextCalculator.java) implementations must be thread safe too.

The call tree for most permissions checks will look something like this:
1. Plugin checks for permission using Subject#hasPermission (possibly making this call from an async thread)
2. The permission plugin queries the ContextCalculators it [has registered to it](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/service/context/ContextualService.java#L36) in order to determine the subjects "current context".
3. Permission plugin does whatever it needs to do to work out what the result of the check should be.

Obviously, in this process, it's possible that the calculators are called async. Therefore, the calculators should also be thread safe, and can therefore only access a very limited range of data and API functions.

Options to resolve this (unless anyone else has any ideas):

1. Declare that the permissions API is absolutely **not thread safe**, and that ALL permissions checks, lookup operations, or anything which involves contexts MUST be done on the main server thread.

2. Require that ContextCalculators are thread safe, and do not access any non-thread safe aspect of Sponge or the server.

I personally lean towards option no 2. It should be relatively straight forward for implementations to cache the data they need, so it can be accessed.

For example, if I wanted a calculator which simply returned the name of the block a player was standing (a pretty standard request for a context system, I would say), then it would require that I cache that data in a Concurrent Map, and then return values from there when the calculator is called. I'd then update this cache map on the move event.

Either way, it needs to be addressed & then documented.

I'd like to know what other people think, or if a better solution can be found. :)

**Comment by bloodmc** [comment]
@zml2008 please review

**Comment by bloodmc** [comment]
@lucko I agree with option 2

`Require that ContextCalculators are thread safe, and do not access any non-thread safe aspect of Sponge or the server.`

For GriefPrevention, I make a ton of permission calls async that require active contexts in order to make sure the proper permission are checked. It wouldn't make sense to only support permission calls async without active contexts.

The plugins implementing their own context calculators would just have to make sure they are thread-safe as you stated.

Are you able to address the changes so we can merge them?
