### ISSUE TITLE
Sponge Tracking crashing servers at late hours needs fixing ASAP

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeAPI#1548]
[New folder (2).zip](https://github.com/SpongePowered/SpongeAPI/files/966330/New.folder.2.zip)

**Comment by parlough** [comment]
What is inside the zip? That's not the best method for including relevant information as some devices cannot open zipped folders and some will not feel comfortable downloading it. 

I recommend including more information on when this happened, the crash log, your Sponge version, information about the server's environment all within this issue and using gist or pastebin for the logs.

**Comment by stephan-gh** [comment]
Additionally, implementation related issues should be opened on https://github.com/SpongePowered/SpongeForge or https://github.com/SpongePowered/SpongeCommon (depending on the type of problem).

Please re-upload the logs (or whatever is in the ZIP) to http://gist.github.com, share some information about your environment (e.g. Sponge version, installed mods, ...) and re-open it on one of the implementation repositories.
