### ISSUE TITLE
A way to: getPluginDirectory

### ISSUE THREAD

**Issue by axle2005** [SpongePowered/SpongeAPI#1551]
Much like the getSaveDirectory. 

Since server owner's can define where plugins exist, a simple way of getting that directory without having hoops to jump through would be wonderful.

**Comment by parlough** [comment]
I'm curious what is your use case for accessing the plugins/mods folder?

**Comment by axle2005** [comment]
I personally am using it to check timestamps on certain files within it, more or less for clean up purposes... I also just realized this very thing can be obtained by injecting the Default config direction and using the Path...

**Comment by simon816** [comment]
You can do something like
`MyPlugin.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath()`
to get the jar file path of your plugin
