### ISSUE TITLE
[SpongeAPI 7.0] Add TeleportTypes for Chorus Fruit

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeAPI#1556]
Hi,
when player eat chorus fruit, the TeleportCause return TeleportTypes.UNKNOW
Can you add a new TeleportTypes for chorus fruit ?

**Comment by parlough** [comment]
@JBYoshi Maybe you could take this?

**Comment by parlough** [comment]
Once I have time to update the PR it will be expanded to support more items than just chorus, for example ender pearls.

**Comment by ImMorpheus** [comment]
PR merged
