### ISSUE TITLE
ChangeBlockEvent.Break event hava some problem

### ISSUE THREAD

**Issue by PorPit** [SpongePowered/SpongeAPI#1559]
when i break a ore block and evert setCancelled
the ore block cant to broken ,but falling experience。
look like this

http://i2.muimg.com/508137/d6d7ae64969da44d.png

this is a bug?

spongeapi 5.2.0 - 2322

**Comment by gabizou** [comment]
This isn't a bug with the API, re-open in SpongeCommon with a bit more detail, like your event listener code, any debugging information as well.
