### ISSUE TITLE
Request: Rain-reachable Y-location  

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeAPI#1560]
There is no clean way to determine if a player is being rained on (or any location is recieving any precipitation on it) 

The Extent#getHighestYAt() will return the highest solid block that is recieving light, aka, grass blocks under tree canopies, or anything under a glass roof just above or high in the sky.   {At least on SpongeVanilla 6.0.0-Beta-1 this is the implimentation...}

Yet minecraft must know if a location is capable of recieving precipitation or not, since the client will or wont render drops (and splashes on the first block encountered down from the sky) - which may just be a client side thing - BUT, one of the conditions for ICE is that water only freezes if the entire column of air above it is empty and it is able to see precipitation - put tree leaves or glass blocks over, it wont freeze.
As well, the rain-based hydration of soil requires knowing if it is rain-exposed, soil under glass wont hydrate in a rainstorm, soil in the open will.

Please add a Y-position reporter for the block in the column which will recieve rain // is the topmost block in the column solid or transparent, which blocks precipitation from forming in the column below.

**Comment by parlough** [comment]
You should be good now with https://github.com/SpongePowered/SpongeAPI/pull/1572 merged :)
