### ISSUE TITLE
Setting spectator mode is incomplete(?)

### ISSUE THREAD

**Issue by widd** [SpongePowered/SpongeAPI#1561]
`player.offer(Keys.GAME_MODE, GameModes.SPECTATOR);`
will result in a somewhat "incomplete" spectator state:
* Player is entirely invisible rather than a transparent head box being shown
* Player does **_not_** have no-clipping ability

Setting the gamemode manually via `/gamemode 3` works normally even if the player is in this pseudo-spectator state.

**Comment by Deamon5550** [comment]
This should be opened in https://github.com/SpongePowered/SpongeCommon/issues
