### ISSUE TITLE
Cancellable Sound + effect events.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1562]
I'd like to see events for when a server side effect / sound is sent to the client, it would make it possible to cancel the boss sounds to clients outside a configurable radius, among other use cases.

**Comment by gabizou** [comment]
This would potentially flood a metric ton of events. I'm not quite sure whether I like the idea of the amount of events potentially being thrown, especially when it has to combine a full list of entities being sent the sound event.

What would you propose as an event structure?

**Comment by ryantheleach** [comment]
On the assumption that vanished players don't make noise already, and that any contextual entities / vanished entities, / hiding specific entities from specific entieies won't leak sounds.

Maybe the sounds the events are thrown for could be a limited sub-set?

E.g. global sounds, thunder, wither boss sounds, dragon sounds, player caused sounds, explosions?

Or maybe introduce a silent data, that could be applied to entities.

**Comment by ryantheleach** [comment]
Related: https://github.com/SpongePowered/SpongeAPI/issues/1752

**Comment by parlough** [comment]
Added in https://github.com/SpongePowered/SpongeAPI/pull/2028
