### ISSUE TITLE
Security concerns with the API

### ISSUE THREAD

**Issue by PaulBGD** [SpongePowered/SpongeAPI#1571]
Basically, #1570 solved multiple security issues that are currently present in the software. I run it on my server and it works great, so I think closing it without discussion was very immature.

**Comment by parlough** [comment]
It's not funny at all, just annoying. Does not help anyone and wastes the time of project developers and maintainers.

**Comment by Meronat** [comment]
![dikufzsuqaeksvu](https://user-images.githubusercontent.com/18372958/35315275-1f433466-0091-11e8-893e-c57c5317a786.jpg)
