### ISSUE TITLE
Provide DataManipulator to control player's SleepTimer NBT

### ISSUE THREAD

**Issue by OffLuffy** [SpongePowered/SpongeAPI#1575]
Players have an NBT tag called SleepTimer (I believe generally ranges from 0 to 100) representing the ticks a player has been in a bed. At the end of the SleepTimer's range, the player wakes up.

In order to control how long the player can stay in a bed or when to kick the player out of bed, it'd be helpful to allow modification to this value.

**Comment by johnfg2610** [comment]
you can edit any NBT data using DataFormat nbt would be DataFormat df = DataFormats.NBT then you can convert to and from data containers

**Comment by ryantheleach** [comment]
@Meronat This should be relatively straight forward right?

**Comment by parlough** [comment]
@ryantheleach Never have looked at sleep but from Off's description it should be. We could add it to `SleepingData`. Feel free to take this or assign me and I'll get it done.

**Comment by ImMorpheus** [comment]
PR merged
