### ISSUE TITLE
Inventories and slot indexes

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1576]
I need to check if a player has item on exactly n. th slot in hotbar. 

With current api i can access the first slot (from left side) with slot index of 0
Optional<Slot> slot1 = hotbar.getSlot(new SlotIndex(0)); 
the second with slotindex of 1 and so on. 

However if there is at least one empty slot accessing items in hotbar like this simply stops work.

See pic related

![2017-06-11_19 44 56](https://user-images.githubusercontent.com/4391346/27013170-18bbae48-4edf-11e7-95de-a245c802619c.png)

With inventory like this i want to check which item is at the slot with id 7

Optional<Slot> slot1 = hotbar.getSlot(new SlotIndex(7)); 

In this case slot1.get().peek() will return an empty optional.

**Comment by XakepSDK** [comment]
In this screen only slots with index 1,2,8 are non-empty. Its ok.
