### ISSUE TITLE
Fishing Broke with Latest 1.12-7.0.0-BETA-281

### ISSUE THREAD

**Issue by jmiahman** [SpongePowered/SpongeAPI#1579]
Looks like the latest sea level changes has broke Fishing. I can cast once and after I catch something can no longer cast. I have to log out and back in.

[00:18:14 INFO]: Plugins (8): Minecraft, SpongeVanilla, GriefPrevention, LuckPerms, SpongeAPI, Nucleus, Mod Coder Pack, Total Economy

If you would like me to run in a debug mode or something let me know.

**Comment by stephan-gh** [comment]
Please report implementation problems on [the SpongeCommon issue tracker](https://github.com/SpongePowered/SpongeCommon/issues) the next time. Thanks!
