### ISSUE TITLE
AffectItemStackEvent/AffectSlotEvent calling all slots in inventory

### ISSUE THREAD

**Issue by johnfg2610** [SpongePowered/SpongeAPI#1581]
Hey,

whilst developing a block tracking plugin i noticed something a little weird it seems that every time you change anything in your inventory all inventory slots call the AffectItemStackEvent event im fairly sure this isnt intended behaviour as it makes very little sense to me. below i have the first 4 pages out of 10 where it calls the AffectItemStackEvent without the stack actuly being touched
http://i.imgur.com/2neifGq.png
http://i.imgur.com/lHJcIJG.png
http://i.imgur.com/GhKn3TF.png
http://i.imgur.com/3teJ0DZ.png

thanks
johnfg10

**Comment by Faithcaio** [comment]
I'm not sure what to do with this plugin output.
Anyways if this problem still happens reopen an Issue on SpongeCommon
with more information.
e.g. include a copy-pasteable Listener for us to reproduce it with.
