### ISSUE TITLE
player.getOpenInventory() returning unexpected values (never an empty optional)

### ISSUE THREAD

**Issue by Xenmai** [SpongePowered/SpongeAPI#1583]
I've been working on inventory stuff lately and I've encountered a somewhat unexpected behavior when using "player.getOpenInventory()". Since it returns an optional, I'd assume it'd be an empty optional if the player doesn't have an open inventory.
What I've noticed, on the other hand, weirdly enough, is that the optional is never empty, even when the player is not currently seeing any inventory. In this case (the player not having an open inventory), the method returns the player's own inventory.
I feel this is pretty weird, since it gives me no way of knowing if the player is actually seeing an inventory or not. Is this intended? Could it be changed or fixed?
Thanks for your time and support beforehand.

**Comment by JBYoshi** [comment]
See SpongePowered/SpongeCommon#1011.
