### ISSUE TITLE
[Request] New Key to mark entities as transient - not saved after unload

### ISSUE THREAD

**Issue by Wolfizen** [SpongePowered/SpongeAPI#1584]
This feature would add a new `Key` that controls whether an entity is saved after it is unloaded. Practically, this key would be read when serializing an in-memory chunk. This flag is useful for plugin-created entities that do not (or should not) need to be saved on the world. Examples are: pets, marker armor stands, quest NPCs. When the flag is present, the entity will exist until after `ChunkUnloadEvent` (or `WorldUnloadEvent`) finishes, at which point the entitiy simply won't be saved to disk.

Currently, plugins need to "clean up" entities on chunk/world unload to ensure that their dynamically created entities aren't left there. If the plugin is removed, or the world is moved to another server, those entities would remain saved in the world and may cause problems now that they are not "managed" by their plugin.

@gabizou has asked to be notified from previous IRC conversation.

**Comment by ImMorpheus** [comment]
PR merged

**Comment by Wolfizen** [comment]
:D
wow!! Thank you so much!
