### ISSUE TITLE
Region Regeneration with World Edit?

### ISSUE THREAD

**Issue by Meibisu** [SpongePowered/SpongeAPI#1589]
So..There is still no improvements to api for region regeneration working to 1.10 Sponge Server? Tried World Edit Sponge from http://builds.enginehub.org/job/worldedit/last-successful?branch=feature/sponge-1.10.2 and SpongeForge 1.10.2-2281-5.2.0-BETA-2407. //regen still not working :C

**Comment by wizjany** [comment]
have you tried with forge worldedit? it's not even implemented in sponge worldedit, regardless of what the api supports.

**Comment by Meibisu** [comment]
I tried forge worldedit too, regen is working, but very badly, regenerate only very small (20x20 blocks) region, when you take bigger it just crash server with error (tick=60 seconds)

**Comment by yannicklamprecht** [comment]
How many ram did you assign to the server?

**Comment by Deamon5550** [comment]
Duplicate #574

For issues with worldedit you should take that to their issue tracker.
