### ISSUE TITLE
Include fastutil as API dependency?

### ISSUE THREAD

**Issue by parlough** [SpongePowered/SpongeAPI#1590]
Since Minecraft is including the full, original fastutil(version 7.1.0) library now, it would be nice to have it in the API as a dependency like Guava so we can have a guarantee as a plugin developer that all Sponge implementations are including it, so we can use it safely ourselves.

**Comment by parlough** [comment]
@Cybermaxke I know you use fastutil in LanternServer, but don't bundle the whole thing at the moment I believe. What is your opinion on including the entire library in the API and then as a result, your implementation.

**Comment by Cybermaxke** [comment]
I think developers can take benefit from the fastutil library. The libraries are in the LanternServer included in the final jar, and the fastutil is currently being minimized to only include the used classes.
But when we start deploying artifacts to a maven repo, I am going to change the system a bit that all the libraries are also uploaded and downloaded from this repo. Reducing the size of the LanternServer jar, updates of dependencies will only be pulled when necessary. This will decrease the benefit of minimizing, so in the end you don't have to look at adding big libraries. If it can benefit the developers why not add it.

**Comment by jamierocks** [comment]
Since 1.12 Minecraft has the whole thing - the API should reflect that.

**Comment by parlough** [comment]
Let's reconsider this with 1.13 once it is shown they will stick with the library for sure(especially since we're so far into the development of 1.12).

**Comment by kashike** [comment]
They are sticking with it.

**Comment by parlough** [comment]
@kashike Fair enough, do you think it would still be worth adding now in API 7?

**Comment by kashike** [comment]
I've been :+1: for it from the start.

**Comment by parlough** [comment]
The current stance is that this is going to happen for now, due to the immense size of the library, and it not being desirable to require an implementation to include fastutil.

This may be revisited in the future if there is enough desire.
