### ISSUE TITLE
No method to retrieve(or set in builder) increase in exhaustion from DamageSource

### ISSUE THREAD

**Issue by parlough** [SpongePowered/SpongeAPI#1592]
In Minecraft `DamageSource`s can cause an increase in exhaustion in the attacked player, but this amount does not seem to be accessible from Sponge's `DamageSource`. I think it should even be possible to set this with the builder as well.

**Edit:** So this actually increases exhaustion, so MCP's name of hunger damage is a little misconceiving. See attached picture:

![image](https://user-images.githubusercontent.com/18372958/27519522-52f56018-59bb-11e7-8619-4addd3f42f11.png)

**Comment by ryantheleach** [comment]
@Meronat I've assigned this to you, as you already have commits in your SpongeAPI I presume there is a PR somewhere pending?

**Comment by parlough** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/1674 will solve this is you want to review it :)
