### ISSUE TITLE
Post events to a specific plugin

### ISSUE THREAD

**Issue by parlough** [SpongePowered/SpongeAPI#1593]
This would need a slight addition to the API, but most of the work would be in common.

I could not find an issue for this already there, so I think it would be useful to be able to post events to a specific plugin. An example directly related to Sponge would be it allowing the reload event to be dispatched to only the plugin the user specifies.

**Comment by ryantheleach** [comment]
I'm not sure if this should be exposed. 

Yes it could be useful for the reload plugin, but that's a pretty niche usecase that could be covered by exposing methods to send a reload event to a specific plugin.

vs the amount of trouble it could cause if people sent other events to hard coded plugins.

**Comment by gabizou** [comment]
Specifically for reloading yes, it can be exposed, but allowing specific plugin registered listeners being called non-expectantly is a good way to break plugins. Sponge non-specific, what is the use case here?

**Comment by parlough** [comment]
I do agree with you guys now thinking about it more. It would best be left alone as an internal function for reloading. Plugins should not have to worry about stray events they are not necessarily expecting to occur, and just for them.
