### ISSUE TITLE
Add missing InstrumentTypes

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeAPI#1595]
A lot of new instrument types were added in 1.12 and the `InstrumentTypes` enumeration should be updated.
http://minecraft.gamepedia.com/Note_Block
https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/type/InstrumentTypes.java

**Comment by parlough** [comment]
Along with this I think it would be good to add an `InstrumentTypeProperty` for blocks to show-case what kind of instrument type they are that note-blocks use.

**Comment by Cybermaxke** [comment]
I am currently working on this, also implementing `InstrumentType`s in general.
