### ISSUE TITLE
Cannot check if an enchantment is a "treasure" enchantment

### ISSUE THREAD

**Issue by parlough** [SpongePowered/SpongeAPI#1596]
There are some Minecraft enchantments that cannot be obtained from enchanting in an enchantment table. Internally there is a method to check this and I think it would be good to expose this in the Enchantment interface, so plugin developers can check if vanilla or forge added enchantments are of this type.

I'd PR this, just looking for some input to see if it should be exposed. It would probably be just Enchantment#isTreasureEnchantment

**Comment by gabizou** [comment]
I'd be willing to add such a method. Since it's abstract enough, we don't need to expose which enchantments are treasures specifically, but the method will expose it to plugin developers. Good shout.
