### ISSUE TITLE
No simple way to apply NBT data to an item, entity, etc.

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/SpongeAPI#1597]
After looking through the forums and documentation for a long time, there seems to be no easy way to apply a valid NBT JSON object to something that should be able to take it. This is rather annoying because to do this you need to interact with containers, which really isn’t the best when you’re working with entities that already exist. Allowing developers to directly write to and read the NBT tags of an entity, item or tile entity would be very valuable for developers.

Yes, we do have the Data API, but having standard, traditional NBT access is incredibly useful in the case where, for some reason, something isn’t implemented quite the way it should be for whatever reason.

It allows for laziness but it’s better to have cleaner code than messy code in the long run. Jumping through hoops to interact with NBT tags shouldn’t be a requirement.

**Comment by ST-DDT** [comment]
Just to be sure: You want to use NBT and not something similar to it as DataContainers?

If you use pure Impl stuff like NBT why don't you use pure impl stuff to apply it to the objects as well?

If it is merely about applying json data, then [DataTranslator](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/persistence/DataTranslator.java)s might be useful for you. (JSON->DataContainer->Target)

**Comment by gabizou** [comment]
Set raw data should be usable. It has been available since the original Data API. I wouldn't think using unsafe data is too much trouble and doesn't really do anything different than using underlying NBT.

**Comment by codeHusky** [comment]
The only way I’m aware of is translating the object into a container, interacting with the unsafe data object and pushing it back into an object, then replacing it with the old one. It’s just annoying and it would be better if you could just interact with the NBT without having to duplicate the entity.

**Comment by Zidane** [comment]
Modifying NBT with the API is un-supported and the Data API is meant exactly for this. If something doesn't work or isn't implemented then it needs to be addressed.
