### ISSUE TITLE
HealEntityEvent is not fired.

### ISSUE THREAD

**Issue by gaeqs** [SpongePowered/SpongeAPI#1599]
I'm trying to call the event HealEntityEvent, but it seems it's not fired!

I'm not the only one who is having this issue: https://forums.spongepowered.org/t/cancel-any-entity-healing-excluding-healing-by-my-plugin/15926

**Comment by gabizou** [comment]
Not really an API issue. Refer to the SpongePowered/SpongeCommon#41. If you're willing to make a PR to implement said event, we do accept PR's for it.
