### ISSUE TITLE
Ambiguous Inventory Results?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1600]
https://github.com/SpongePowered/SpongeAPI/blob/a4aaeec0007ebd9c3570e41382454e81f875e0a1/src/main/java/org/spongepowered/api/item/inventory/transaction/InventoryTransactionResult.java

    /**
         * The actual result of the operation is undefined, this probably
         * indicates that something went wrong with the operation that the
         * inventory couldn't handle or didn't expect. The state of the
         * inventory is undefined.
         */
        UNDEFINED,

        /**
         * The inventory operation succeeded.
         */
        SUCCESS,

        /**
         * The inventory operation failed for an <em>expected</em> reason (such
         * as the inventory being full or not accepting items of a supplied
         * type. The condition of the inventory is unchanged.
         */
        FAILURE,

        /**
         * The inventory operation failed because an <em>unexpected</em>
         * condition occurred. The state of the inventory is undefined.
         */
        ERROR,

        /**
         * An operation was cancelled by a third party (eg. an inventory event
         * was cancelled). The condition of the inventory is unchanged.
         */
        CANCELLED

There are 5 different results for an inventory transaction. 

- [x] Cancelled, "`The condition of the inventory is unchanged`" self evident.

- [ ] Error, "`The condition of the inventory is ambiguous?`" Should nearly never come up, but leaving it in an ambiguous state? I guess there is no other option.

- [x] Failure "`full or not accepting items of a supplied type.` " Makes sense, you only offer a single item type at a time after all. "`Condition of inventory is unchanged.`"

- [ ] Success "`The inventory operation succeeded.`" Not a whole lot of info, but elsewhere it states that a 
success is returned for a partial success, I believe that this isn't entirely honest, and could be split into SuccessFull and SuccessPartial? SuccessPartial can't be a fail, as that says that fail means no change.

- [ ] Undefined .... This AND Error?

Also various javadocs state that the InventoryTransactionResult is returned as a boolean, which isn't quite true.

So am I right in thinking that Undefined could be removed, and just use Error, and that Success could have a stronger version, indicating full success?

Otherwise we are relying on plugin devs seeing Success, not reading the JD, and assuming that they don't need to do anything with the remainder.

@Faithcaio Thoughts?

**Comment by Faithcaio** [comment]
will get adressed in https://github.com/SpongePowered/SpongeAPI/pull/1848
