### ISSUE TITLE
Change createEntity to use generics?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1604]
At the moment using createEntity from EntityTypes gives you an Entity back.

Is it feasible / a good idea to generic that so that the return type reflects the type of entity being created?

Otherwise you need to cast, and rely upon the programmers knowledge in order to access methods on the entity specific interfaces, or even set their handslots / armor.

I'm guessing the need for this will be reduced somewhat, once some inventory keys / data are created?

**Comment by gabizou** [comment]
I distinctly remember EntityType generics being discussed at some point. We elected to avoid it since the raw type usage throughout would be necessary in many cases (think about looking up Keys through the registry). I have to find it somewhere at some point to be able to link it to you, unless someone else can find it. I believe I was discussing it with @ST-DDT, but this discussion had to have taken place between a year and two years ago now :/

**Comment by ST-DDT** [comment]
I searched for that discussion too, but could not find it.

There is one problem with the above proposal, the generic type would be derived and not explicit.

* `<T extends Entity> T createEntity(EntityType type)`

So both of the following would compile, but only one would work.

````
Zombie zombie = foo.createEntity(EntityType.ZOMBIE);
Horse horse = foo.createEntity(EntityType.ZOMBIE);
````

The code would then display a ClassCastException on either the `return` line of the method in (Sponge's code) or in the using line (plugin's code). Which might cause

You can achieve the same "(in)security"/result with just the current one plus an unchecked cast.

> Otherwise you need to cast, and rely upon the programmers knowledge in order to access methods on the entity specific interfaces, or even set their handslots / armor.

The main issue is that the EntityType alone does not contain any type information that could be used by the IDE to suggest better interface matches. So the developer still needs to know them. For that to work we would have to change the API of EntityType to include the generic information we need.

* `public static final EntityType<Zombie> ZOMBIE`
* `<T extends Entity> T createEntity(EntityType<T> type)`

This suggestion would work, but I'm not sure about generic `CatalogType`s. Is there such a class for all `EntityType`s? How about `AREA_EFFECT_CLOUD`, `WEATHER` or `UNKNOWN`?

**Comment by simon816** [comment]
Don't know if this is the issue you're thinking of but I made a PR a couple years ago https://github.com/SpongePowered/SpongeAPI/pull/496 where it was decided this wouldn't happen.

**Comment by ryantheleach** [comment]
with the example : `<T extends Entity> T createEntity(EntityType type)` is there any other difference then the syntax to the current API with these 2 code examples?


```
Zombie zombie = foo.<Zombie>createEntity(EntityType.ZOMBIE);
Zombie zombie = ((Zombie) foo.createEntity(EntityType.ZOMBIE));

```

**Comment by gabizou** [comment]
But you're forgetting that it would turn into:

```java
Zombie zombie = foo.createEntity(EntityType.ZOMBIE); 
```
due to it being `static final EntityType<Zombie> ZOMBIE = DummyObjectProvider.foo;`

I'm less lean on the strict generics than with the cast.

**Comment by Zidane** [comment]
Any approach with generics is muddy. While the cast is annoying, the sub interfaces and the data-like methods in them are for convenience. In most cases, not being of the type of sub-interface isn't an issue.
