### ISSUE TITLE
TextStyles.RESET does not work properly

### ISSUE THREAD

**Issue by parlough** [SpongePowered/SpongeAPI#1611]
For example this code - 

```java
private static Text getDescription(CommandSource source, CommandMapping mapping) {
    final Optional<Text> description = mapping.getCallable().getShortDescription(source);
    final Text.Builder text = Text.builder("/" + mapping.getPrimaryAlias());
    text.color(TextColors.GREEN);
    text.style(TextStyles.UNDERLINE);
    text.onClick(TextActions.suggestCommand("/" + mapping.getPrimaryAlias() + ""));
    mapping.getCallable().getHelp(source).ifPresent(t -> text.onHover(TextActions.showText(t)));
    text.append(Text.of( " ", TextStyles.RESET, TextColors.WHITE, description.orElse(mapping.getCallable().getUsage(source)))).build();
}
```

Causes the underline to remain on the following white text

![chat](https://cdn.discordapp.com/attachments/334992597779218433/335617478187024386/unknown.png)

While this code causes there to be no underline, using `Text.of()` instead and not resetting the style.

```java
private static Text getDescription(CommandSource source, CommandMapping mapping) {
    final Optional<Text> description = mapping.getCallable().getShortDescription(source);
    final Text.Builder text = Text.builder("/" + mapping.getPrimaryAlias());
    text.color(TextColors.GREEN);
    text.style(TextStyles.UNDERLINE);
    text.onClick(TextActions.suggestCommand("/" + mapping.getPrimaryAlias() + ""));
    mapping.getCallable().getHelp(source).ifPresent(t -> text.onHover(TextActions.showText(t)));
    return Text.of(text, " ", description.orElse(mapping.getCallable().getUsage(source)));
}
```

**Comment by ST-DDT** [comment]
The issue of the code here is that the white text is structually inside of the  underlined Text thus inherits that properties. (The reset does not know that there have been underlines in the first place.) The second example properly gives the Text an equal hierarchy.

The RESET would work if everything is created in one `Text.of()`.

**Comment by ryantheleach** [comment]
As far as I was aware, this is works as intended. 

> `text.append(Text.of( " ", TextStyles.RESET, TextColors.WHITE, description.orElse(mapping.getCallable().getUsage(source)))).build();`

You are appending a child composite text. If you were appending each of those, without constructing a child text it would be fine.
