### ISSUE TITLE
About experience

### ISSUE THREAD

**Issue by 5igm** [SpongePowered/SpongeAPI#1619]
The event ChangeEntityExperienceEvent had not fired when a player gains EXP.And never been fired.

**Comment by 5igm** [comment]
Hi! Is there anyone who can help me with this question?

**Comment by DenWav** [comment]
Patience doesn't appear to be a virtue of yours is it.

**Comment by ryantheleach** [comment]
@5igm The only method to speed this up, is to provide test plugins demonstrating that it's not fired, as well as debug logs to back up your claim including versions tested.

Github Issues are not a support forum. 

If you have happened across a bug, or something unimplemented, This is also the wrong GitHub repository.

**SpongeAPI** Repository contains only the API, reporting issues and bugs here is largely for _Design_ issues in the API, or future feature requests.

**SpongeCommon** is shared code between **Sponge** **Vanilla** & **Forge**. If you can replicate the issue on both **Sponge** **Vanilla**, and on **Sponge** **Forge**, post an issue there. If the issue only occurs on one platform, post it in the relevant repository issue tracker.
