### ISSUE TITLE
Add a way to force fluids to flow during world generation

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/SpongeAPI#1621]
Currently, blocks of water or lava set by a populator are not flowing.
To fix this issue, we should either force `Extent#setBlock()` and `Extent#setBlockType()` methods to tick the new block or either add a new method in SpongeAPI similar to `World#immediateBlockTick()` called by vanilla fluid populators.

**Comment by gabizou** [comment]
The absolute biggest problem is that fluids in the edges of chunks to generate more chunks, since the fluid logic does not differentiate between world generation and standard block placement. I’m curious why the plugin generated fluid placement does not function as vanilla fluid placement when the chunk is finished generating and actually ticking.

**Comment by Yeregorix** [comment]
Vanilla populators don't care if they will generate new chunks or not when they call `World#immediateBlockTick()` and it seems that this is not a problem so it should be the same for plugins. Are you sure calling `Extent#setBlock()` is ticking the new block during world generation ? If vanilla populators explicitly call `World#immediateBlockTick()` it would means that `World#setBlockState()` does not tick any block by default during the generation.

**Comment by ryantheleach** [comment]
@Deamon5550 I havn't looked into this, but my initial thoughts would be:

don't populators run on an 8 block offset? Shouldn't it be fine to expose a method to tick blocks after a chunk has finished populating?

**Comment by Yeregorix** [comment]
Depending on the terrain, water can flow much further but it's rare.

**Comment by ryantheleach** [comment]
Not in a single tick.

**Comment by Yeregorix** [comment]
The aim of `World#immediateBlockTick()` is precisely to flow the water in a single tick, whatever the distance.

**Comment by Zidane** [comment]
@Deamon5550 Can I get your thoughts on the above?

**Comment by Deamon5550** [comment]
The only way to support this is adding an analogy for `immediateBlockTick` to the api. I should note that using something like `RandomBlockPolulator` through the api will already flow liquids in the same way as vanilla [see here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/world/gen/populators/RandomBlockPopulator.java#L84).

**Comment by Yeregorix** [comment]
I did new tests with a recent git clone of spongeforge and setting blocks to BlockTypes.FLOWING_WATER or BlockTypes.FLOWING_LAVA seems to flow fine. I let you decide if this issue should be closed or not.

**Comment by Deamon5550** [comment]
Sounds good to me, I didn't really want to add an `immediateBlockTick` to the api as we already have similar but not quite the same concepts that could get confusing. But if it works already then great.
