### ISSUE TITLE
Get current world time/moon phase

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1623]
Seems like we cannot get/or set current world time, nor phase of the moon.

**Comment by gabizou** [comment]
Duplicate of https://github.com/SpongePowered/SpongeAPI/issues/393

**Comment by parlough** [comment]
Also I would like to note you can currently get and set world time through the `WorldProperties` class. So you could do `world.getProperties().setWorldTime(500)`.
