### ISSUE TITLE
Filter StartsWithPredicate first?

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeAPI#1625]
https://github.com/SpongePowered/SpongeAPI/blob/300807f0c87a17a611effb74125d7cf4af595b98/src/main/java/org/spongepowered/api/command/dispatcher/SimpleDispatcher.java#L346

I'd say filtering out the commands starting with another string is way faster than doing permission checks.

**Comment by Zidane** [comment]
Closing this as it needs to be brought up on commands PR.
