### ISSUE TITLE
Improve getNearbyEntities calls

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1626]
comment from https://github.com/SpongePowered/SpongeCommon/pull/1479

add a method 
World#getNearbyEntities(Position, radius, loadChunks)
Location#getNearbyEntities(radius, loadChunks) could be possible as well.
So far we have a method Entity#getNearbyEntities(Position, radius) this method is quite insufficient because sometimes we might want to get a list of entities, which are around  a location, rather than around another entity. 

Currently similar thing can be achieved by World#getIntersectingEntities(AABB) but i believe that having methods as described above would be still quite helpful.

**Comment by Zidane** [comment]
@NeumimTo Interested in giving me a PR? I'd appreciate it.

**Comment by NeumimTo** [comment]
Yep, I could code it during the weekend.

**Comment by JBYoshi** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/1e8eecda2e651ed12f8fadb33b272461fea291e4
