### ISSUE TITLE
Implement Attribute Modifiers

### ISSUE THREAD

**Issue by Limeth** [SpongePowered/SpongeAPI#1628]
Attribute modifiers, as the name suggests, modify various attributes of the affected entity. They may be bound directly to a spawned entity, or to an item that the entity wears/uses. It would be nice to have access to attribute modifiers from the API.

More details on the wiki:
https://minecraft.gamepedia.com/Attribute#Applying_attributes

**Comment by parlough** [comment]
@kashike Started some work on this earlier - https://github.com/SpongePowered/SpongeAPI/pull/1428

**Comment by gabizou** [comment]
@Limeth if you wish and are willing, you can continue the work on attributes to get it into the API and implementation, otherwise it'll sit on a todo list that will eventually be reached in the future.
