### ISSUE TITLE
Get sender of MessageChannelEvent.Chat?

### ISSUE THREAD

**Issue by spide-r** [SpongePowered/SpongeAPI#1637]
I am trying to make a chat filter. How do I get the source of the chat message sent using MessageChannelEvent.Chat, and check if it was caused by a player? this is what I have so far: 

```
@Listener
    public void onChat(MessageChannelEvent.Chat event) {
        regExFilter filterThisMessage = new regExFilter();
            Text message = event.getRawMessage();
            boolean messageHasSwear = filterThisMessage.filter(message);
            if (messageHasSwear == true){
            	event.setMessageCancelled(true);
            	
            }
        }
```

I am using Sponge API 5.1.0.

**Comment by spide-r** [comment]
Clarification:
It has worked ingame. However it filters messages sent by the console as well. I would like for the plugin to only filter chat messages sent by the player.

**Comment by kashike** [comment]
https://docs.spongepowered.org/stable/en-GB/plugin/event/causes.html
