### ISSUE TITLE
[API 7] Listeners added via InventoryBuilder don't get called.

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/SpongeAPI#1646]
I'm currently in the process of updating a plugin from API 5 to API 7, during this process I found that when adding a InteractInventoryEvent listener using the following results in it not being called in API 7.
```
Inventory.builder().listener(InteractInventoryEvent.class, evt -> {
    getLogger().info("HelloWorld");
});
```

Tested on the following:
- SpongeVanilla-1.12.1-7.0.0-BETA-327
- SpongeForge-1.12.1-2479-7.0.0-BETA-2624 with Forge-1.12.1-14.22.1.2480

Example plugin source code: https://gist.github.com/LXGaming/2364689efd0244ae9169e06cbc740cb5

**Comment by VapidLinus** [comment]
I have noticed this issue as well. I wrote about it on the forum here:
https://forums.spongepowered.org/t/inventory-builder-listener-not-firing/21001

Sample code to reproduce the issue:

```java
@Listener
public void onTest(MessageChannelEvent.Chat event, @First Player player) {
	if (!event.getRawMessage().toPlain().equalsIgnoreCase("!test")) return;

	Inventory custom = Inventory.builder()
			.of(InventoryArchetypes.CHEST)
			.property(InventoryTitle.PROPERTY_NAME, InventoryTitle.of(Text.of("Fancy custom inventory")))
			// Log to the console whenever something in the inventory is clicked on
			.listener(ClickInventoryEvent.class, e -> logger.info("Click inside custom inventory"))
			.build(plugin);

	custom.query(GridInventory.class)
			.query(SlotPos.of(1, 1))
			.offer(ItemStack.of(ItemTypes.DIAMOND, 1));

	player.openInventory(custom);
}
```

> spongevanilla-1.12.2-7.0.0-BETA-341

**EDIT:**
A temporary workaround is to use `InventoryArchetypes.MENU_GRID` instead and it works.

**Comment by LXGaming** [comment]
This issue may have been fixed by https://github.com/SpongePowered/SpongeCommon/commit/b22c02d2e0cde0e94e62b1b125a4d14aed8b0625 

Currently waiting for a Sponge build with the changes to be able to test/confirm this.

**Comment by parlough** [comment]
@LXGaming This has been fixed correct?

**Comment by LXGaming** [comment]
I can confirm that this issue is fixed.

Tested on the following:
* SpongeVanilla-1.12.2-7.0.0-BETA-365
* SpongeForge-1.12.2-2555-7.0.0-BETA-2756 with Forge-1.12.2-14.23.1.2555
