### ISSUE TITLE
Make it easier to send localized messages to a message channel

### ISSUE THREAD

**Issue by Katrix** [SpongePowered/SpongeAPI#1653]
Not really sure how you would do this, however I feel like it's something that should be looked into as if not it might be tempting to just circumvent the message channels completely.

As I see it, one approach would be to add a few extra methods on the MessageChannel object that takes a key and a translation dictionary from https://github.com/SpongePowered/SpongeAPI/pull/1224.

**Comment by ImMorpheus** [comment]
As of API 8 we are now using [Adventure](https://github.com/KyoriPowered/adventure). 

This means the old Text api is gone and all the related issues (especially those involving breaking changes) are no longer relevant, therefore I'm closing this.

Regarding this issue: `MessageChannel`s are gone, Adventure has `Audience`
