### ISSUE TITLE
Player.getInventory.offer() behavior...

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeAPI#1654]
(Asked to make an issue here by Faithcaio for discussion)

Currently, if a player has a 'full' inventory, full of items in the hotbar and full of items in the 'pocket' slots, and offhand, but is not wearing any armor:
 the  .offer() of itemstacks such as sticks or coal or stone will be successful, and the itemstacks are found placed on the feet.   
While this makes sense from a perspective of "there was another slot available to use" it is inconsistent with the game mechanic as if said itemstack of coal or sticks were a drop on the ground, the game does not pick it up and place on my feet.  
Being able to place blocks in the armor slots --- yes, that is good behavior to have for the inventory methods that specifically identify that type of slot/location of slot  as a target.  But for the generic offer, should not the function be like the game mechanic, as those slots 'are unused' but are also 'not usable for the drop being evaluated to pickup

Should player.getInventory().offer(stack)  really be successful as the generic stack offering, or should it be game-mechanic sensitive, but with the optional ability to override mechanic and use any available slot?

**Comment by Zidane** [comment]
player.getInventory is going to net you a view of all the slots of the player. If you are worried about this scenario, then you should be getting a view of the main inventory + hotbar inventory

WITH THAT SAID offer does not mean "You're going to take it whether you like it or not". Offer should be checking if the "equipment" slot says this can go in there (whereas the set methods would force it there). Sounds like a bug honestly @Faithcaio .

**Comment by Faithcaio** [comment]
Inventories have no check if the item is allowed.
These checks are done in Slots (which in MC only exists in Containers).

So while we could maybe duplicate the logic for vanilla inventory/containers with modded inventories we are out of luck.

**Comment by Zidane** [comment]
Great point by @Faithcaio . It is extremely easy to blur the line between the view model (container) and the backend (inventory). For the purposes of the API, they are the same but, in this case, the behavior is going to be different because your view of the inventory is different.

**Comment by ryantheleach** [comment]
"the purposes of the API, they are the same"

That's the problem plugin users have issue with and is the core point.

I know faith has put in a ton of work, and this would be potentially modifying the spec :( but can this logic (at all, possibly) be exposed on the server? or does it practically just not exist?

If there isn't API for it, there needs to be, if there IS API for this, then people arn't finding it or understanding it.

The people who _need_ this behavior don't necessarily care about the current API, or how elegant the API seems on the surface for viewing the Inventory Model, they just need a method to do this via the ViewModels so the possibility of rejection happens.

**Comment by Faithcaio** [comment]
> or does it practically just not exist?

Exactly currently there is no logic on vanilla Inventories that dictate what can go into a Slot.
The Logic is only defined on actual Slots which only exist in Containers.

While it could be possible for us to just duplicate vanilla behaviour we wont be able to do it for modded inventories.

**Comment by ryantheleach** [comment]
Sure, but can we create or use the container?

**Comment by Faithcaio** [comment]
There is not one way to get a Container for an Inventory.
e.g. horse containers need the horse entity it belongs to.
