### ISSUE TITLE
Can't get InventoryTitle of inventories

### ISSUE THREAD

**Issue by VapidLinus** [SpongePowered/SpongeAPI#1657]
`Inventory.getInventoryProperty(InventoryTitle.class)` always returns empty.

Code to reproduce:

```java
@Listener
public void onTest(MessageChannelEvent.Chat event, @First Player player) {
	if (!event.getRawMessage().toPlain().equalsIgnoreCase("!test")) return;

	Inventory custom = Inventory.builder()
			.of(InventoryArchetypes.CHEST)
			.property(InventoryTitle.PROPERTY_NAME, InventoryTitle.of(Text.of("Fancy custom inventory")))
			.build(plugin);

	custom.query(GridInventory.class)
			.query(SlotPos.of(1, 1))
			.offer(ItemStack.of(ItemTypes.DIAMOND, 1));

	player.openInventory(custom);
}

@Listener
public void onClickInventory(ClickInventoryEvent.Primary event) {
	logger.info("Click in inventory: {}",
	            event.getTargetInventory().getInventoryProperty(InventoryTitle.class)
			            .map(t -> t.getValue().toPlain())
			            .orElse("Unknown"));
}
```

1. Type `!test` in chat to open the custom inventory with the title "Fancy custom inventory"
2. Click on the diamond that is placed in the inventory
3. The `onClickInventory` method will log _Click in inventory: Unknown_.

This seems to also affect non-custom inventories and other properties.

> spongevanilla-1.12.2-7.0.0-BETA-342

**EDIT**
I also tried the following because I suspect `getTargetInventory` returns both the custom inventory, the player's 9x3 inventory and their Hotbar:

```java
@Listener
public void onClickInventory(ClickInventoryEvent.Primary event) {
	event.getTargetInventory()
			.forEach(inventory -> {
				logger.info(inventory.getInventoryProperty(InventoryTitle.class)
						            .map(t -> t.getValue().toPlain())
						            .orElse("Unknown"));
			});
}
```

This just prints _Click in inventory: Unknown_ three times instead.

**Comment by Faithcaio** [comment]
Inventory properties should be mostly working with latest build.

Note:
I've added `Inventory.Builder#property(..)` without name as its currently not used with any other name than the default.

Most properties only work for custom inventories and containers viewing them.
I've only implemented `InventoryTitle` for all inventories. (might not work for some modded inventories yet)
