### ISSUE TITLE
Misspelling in org.spongepowered.api.scoreboard.critieria packages

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeAPI#1669]
The correct spelling is criteria, not critieria.

**Comment by kashike** [comment]
...how on earth has no one else noticed this yet?

**Comment by pie-flavor** [comment]
@kashike That's what I thought. Seems to have always been there.

**Comment by XakepSDK** [comment]
Another breaking change :P

**Comment by kinggoesgaming** [comment]
That sounds like something I would type

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/commit/bcff2263e8dedeff5af2e2fe6b21c104c4cd4156
