### ISSUE TITLE
ItemEnchantment missing `of(Enchantment,int)` method.

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeAPI#1670]
Most of sponge api uses builders or static methods to get an instance.
Class `ItemEnchantment` doesn't have `.of(Enchantment,int)` method, to get its instance.
I think, this must be fixed.

**Comment by parlough** [comment]
I suppose this is true sometimes and I'm not really sure it is needed here, but maybe. For now just use the constructor which has the same arguments.
