### ISSUE TITLE
Decaying items not firing events

### ISSUE THREAD

**Issue by n00b42** [SpongePowered/SpongeAPI#1680]
A decaying item is removed from the world without firing one of the expected events:
While ExpireEntityEvent seems logical, I was told at least an DestructEntityEvent should fire, but neither did that (at least not for decaying items)

For clarification: An decaying item is an item whose lifetime is over and is removed from the game. E.g. drops/sapling/... laying on the ground.

**Setup**
- Tried both:
  - spongeforge-1.12.2-2503-7.0.0-BETA-2716, Forge version: forge-1.12.2-14.23.0.2515
  - spongevanilla-1.12.2-7.0.0-BETA-349
- Java version: 1.8.0_144
- Operating System:  Windows

**Comment by n00b42** [comment]
Maybe related #1681

**Comment by JBYoshi** [comment]
Reopen in https://github.com/SpongePowered/SpongeCommon.
