### ISSUE TITLE
ExpireEntityEvent not firing

### ISSUE THREAD

**Issue by n00b42** [SpongePowered/SpongeAPI#1681]
According to its documentation, ExpireEntityEvent should fire when an Entity expires from the world.

I tried both given examples: "when an Endermite expires", "Lightning expires".
I watched them expire but my listener did not catch any ExpireEntityEvent, more suprisingly it did not catch an DestructEntityEvent either.

**Setup**
- Tried both:
  - spongeforge-1.12.2-2503-7.0.0-BETA-2716, Forge version: forge-1.12.2-14.23.0.2515
  - spongevanilla-1.12.2-7.0.0-BETA-349
- Java version: 1.8.0_144
- Operating System: Windows

**Comment by JBYoshi** [comment]
Reopen in https://github.com/SpongePowered/SpongeCommon.
