### ISSUE TITLE
Entity Ghast not visible in Monster.Class when doing a getRegistry.getallof(Monster.class)

### ISSUE THREAD

**Issue by Cleardragonf** [SpongePowered/SpongeAPI#1689]
Hi So I'm using the new spongeforge - 1.12.2-2503-7.0.0- BETA - 2710.jar

When i use the following code I notice that for some reason Ghast is not listed.

List<Class<? extends Entity>> classes = ImmutableList.of(Monster.class);
List list = Sponge.getRegistry().getAllof(EntityType.class).stream()
.fiter(x -> classes.stream().anyMatch(y -> y.isAssignableFrom(x.getEntityClass()))).collect(Collectors.toList());

Here's the list

> [13:04:56] [Server thread/INFO]: This is the list: [SpongeEntityType{id=minecraft:giant, name=giant, translation=SpongeTranslation{id=entity.Giant.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityGiantZombie}, SpongeEntityType{id=minecraft:guardian, name=guardian, translation=SpongeTranslation{id=entity.Guardian.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityGuardian}, SpongeEntityType{id=minecraft:wither, name=wither, translation=SpongeTranslation{id=entity.WitherBoss.name}, modid=minecraft, class=net.minecraft.entity.boss.EntityWither}, SpongeEntityType{id=minecraft:witch, name=witch, translation=SpongeTranslation{id=entity.Witch.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityWitch}, SpongeEntityType{id=minecraft:wither_skeleton, name=wither_skeleton, translation=SpongeTranslation{id=entity.WitherSkeleton.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityWitherSkeleton}, SpongeEntityType{id=minecraft:husk, name=husk, translation=SpongeTranslation{id=entity.Husk.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityHusk}, SpongeEntityType{id=minecraft:cave_spider, name=cave_spider, translation=SpongeTranslation{id=entity.CaveSpider.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityCaveSpider}, SpongeEntityType{id=minecraft:enderman, name=enderman, translation=SpongeTranslation{id=entity.Enderman.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityEnderman}, SpongeEntityType{id=minecraft:evocation_illager, name=evocation_illager, translation=SpongeTranslation{id=entity.EvocationIllager.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityEvoker}, SpongeEntityType{id=minecraft:vindication_illager, name=vindication_illager, translation=SpongeTranslation{id=entity.VindicationIllager.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityVindicator}, SpongeEntityType{id=minecraft:vex, name=vex, translation=SpongeTranslation{id=entity.Vex.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityVex}, SpongeEntityType{id=minecraft:blaze, name=blaze, translation=SpongeTranslation{id=entity.Blaze.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityBlaze}, SpongeEntityType{id=minecraft:skeleton, name=skeleton, translation=SpongeTranslation{id=entity.Skeleton.name}, modid=minecraft, class=net.minecraft.entity.monster.EntitySkeleton}, SpongeEntityType{id=minecraft:elder_guardian, name=elder_guardian, translation=SpongeTranslation{id=entity.ElderGuardian.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityElderGuardian}, SpongeEntityType{id=minecraft:zombie_pigman, name=zombie_pigman, translation=SpongeTranslation{id=entity.PigZombie.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityPigZombie}, SpongeEntityType{id=minecraft:magma_cube, name=magma_cube, translation=SpongeTranslation{id=entity.LavaSlime.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityMagmaCube}, SpongeEntityType{id=minecraft:spider, name=spider, translation=SpongeTranslation{id=entity.Spider.name}, modid=minecraft, class=net.minecraft.entity.monster.EntitySpider}, SpongeEntityType{id=minecraft:creeper, name=creeper, translation=SpongeTranslation{id=entity.Creeper.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityCreeper}, SpongeEntityType{id=minecraft:illusion_illager, name=illusion_illager, translation=SpongeTranslation{id=entity.IllusionIllager.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityIllusionIllager}, SpongeEntityType{id=minecraft:slime, name=slime, translation=SpongeTranslation{id=entity.Slime.name}, modid=minecraft, class=net.minecraft.entity.monster.EntitySlime}, SpongeEntityType{id=minecraft:silverfish, name=silverfish, translation=SpongeTranslation{id=entity.Silverfish.name}, modid=minecraft, class=net.minecraft.entity.monster.EntitySilverfish}, SpongeEntityType{id=minecraft:stray, name=stray, translation=SpongeTranslation{id=entity.Stray.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityStray}, SpongeEntityType{id=minecraft:endermite, name=endermite, translation=SpongeTranslation{id=entity.Endermite.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityEndermite}, SpongeEntityType{id=minecraft:zombie, name=zombie, translation=SpongeTranslation{id=entity.Zombie.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityZombie}, SpongeEntityType{id=minecraft:zombie_villager, name=zombie_villager, translation=SpongeTranslation{id=entity.ZombieVillager.name}, modid=minecraft, class=net.minecraft.entity.monster.EntityZombieVillager}]

Please let me know once this has been fixed...or what class Ghast now resides under? thank you

**Comment by ryantheleach** [comment]
The reason why Ghast doesn't appear is that it's not technically a Monster, but a Hostile.

Although, our API has nearly no contract on what is what, apart from the built in vanilla classes.

If someone could come up with a definition on what a Monster is, vs a Hostile, and add it as a contract to the API that would be awesome, I don't know what it is personally, otherwise I would do it myself.

**Comment by ImMorpheus** [comment]
> The reason why Ghast doesn't appear is that it's not technically a Monster, but a Hostile.

Correct.

> Although, our API has nearly no contract on what is what, apart from the built in vanilla classes.
> 
> If someone could come up with a definition on what a Monster is, vs a Hostile, and add it as a contract to the API that would be awesome, I don't know what it is personally, otherwise I would do it myself.

`Monster` is `EntityMob` in vanilla
https://github.com/SpongePowered/SpongeCommon/blob/616d927817e9d2f64411afedbbcefad11de4f3fb/src/main/java/org/spongepowered/common/mixin/api/mcp/entity/monster/EntityMobMixin_API.java#L33

`EntityGhast` does not extend `EntityMob` so this is working as intended.
