### ISSUE TITLE
EntitySpawning

### ISSUE THREAD

**Issue by Cleardragonf** [SpongePowered/SpongeAPI#1691]
Hello I'm requesting an method to check for a safe area to spawn mobs using their AABB's.  Sort of like how teleporthelper uses GetsafeLocation...I'd like to see something like that on here...as spawning things is all fun and what not...but there's not quick methods.

**Comment by ryantheleach** [comment]
Do you need additional room around the mob? Now I'm thinking about it again there might be something in the API already.

**Comment by ryantheleach** [comment]
Sorry for leading you on a bum steer on the forums. I suspect this method is what you want.

https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/world/extent/EntityUniverse.java#L201

Emphasis mine

 /**
     * Create an entity instance at the given position with the **default
     * equipment.**
     *
     * <p>Creating an entity does not spawn the entity into the world. An entity
     * created means the entity **can be spawned at the given location**. If
     * {@link Optional#empty()} was returned, the entity is **not able to spawn at
     * the given location**. Furthermore, this allows for the {@link Entity} to be
     * customized further prior to traditional "ticking" and processing by core
     * systems.</p>
     *

**Comment by Cleardragonf** [comment]
Woot!!!! YES!!!! :+1:  lol after all i've already gotten the position i just needed to make sure when i used CreateEntity that it was safe for them to be placed there :+1:  Thank you!
