### ISSUE TITLE
Can't get item with itemMeta

### ISSUE THREAD

**Issue by MkSavin** [SpongePowered/SpongeAPI#1694]
I'm writing a plugin that gives the player a block / item from the **DataBase**. **DataBase** returns string like "stone:1" where stone - block / item name and 1 - metadata. I have already implemented this plugin for **Spigot**, but due to the lack of its version for **1.10.2** I switched to **Sponge**.
How i implemented it in **Spigot**:
`
m = Bukkit.getUnsafe().getMaterialFromInternalName(blockName);
ItemStack is = new ItemStack(m);
if(!blockMeta.equals(""))
   is.setDurability(Short.parseShort(blockMeta));
`

It's have **three** steps:
1. Creating Material from item/block name;
2. Creating ItemStack from Material;
3. Adding Durability for ItemStack.

But I have no idea how to implement it on **Sponge**. 
I tried to use this:
`
Optional<ItemType> itemType = Sponge.getRegistry().getType(ItemType.class, blockName);
if(itemType.isPresent()){
...
   ItemStack itemStack = ItemStack.of(itemType.get(), qty);
   if (is != null) {
      DataContainer cntr = itemStack.toContainer().set(DataQuery.of("UnsafeDamage"), blockMeta);
      itemStack = Sponge.getRegistry()
                        .createBuilder(ItemStack.Builder.class)
                        .fromContainer(cntr)
                        .build();
   }
...
}
`
but it returns an error "Data doesn't match".
Also I tried to use setRawData(...) and it don't works too. (But already without an error)

I know that Sponge does not use the old kind of ID.

I using:
1. spongeforge - 1.10.2-2477-5.2.0-BETA-2731
2. spongeapi - 5.0.0-20161223.142907-29
3. forge - 1.10.2-12.18.3.2477
[Text translated from Russian to English with Google Translator. Translation may not be 100% accurate]

**Comment by Zerthick** [comment]
Would it be possible to store the HOCON representation of the item in the database instead? That way you wouldn't have to deal with trying to reconstruct the item after reading it out. You can view how I serialize and deserailize itemstacks to strings here: https://github.com/Zerthick/PlayerShopsRPG/blob/master/src/main/java/io/github/zerthick/playershopsrpg/utils/config/serializers/ItemStackHOCONSerializer.java  This method also has the benefit of being able to handle items with metadata like custom lore/enchantments or titles.

**Comment by MkSavin** [comment]
Zerthick, yes, it really helped, thanks.

For visitors
--
Standard tools of Sponge API does not support meta data, more precisely this "magic" number has been replaced by types. A huge number of types for all multiple blocks. However, this is a minecraft, and it is very difficult to translate all the data in this way, so the meta remained, but "inside" the item. If you get from the ItemStack container and try to convert it into a string and display it on the screen, you'll notice that it is represented as just a few lines. For example, an egg:

> ContentVersion=1
Count=1
ItemType="minecraft:egg"
UnsafeDamage=0

Knowledgeable people will see a clue. 

> UnsafeDamage = 0 

is the meta data of the item. Everything, we found what we were looking for.

> declare itemstack with material of item + stack.toContainer().set(DataQuery.of("UnsafeDamage"), meta)

it would seem that everything, we could get the right thing ... Minute of silence ... 

> Error: Data does not match

What's wrong, I did the right thing? But no, you can not do this.
All because you are trying to remake an already existing ItemStack (as I understand it). Next, you have a month (or more) to search for answers.

ANSWERS
--
But .. finally, you find them. You need to create ItemStack from scratch. To do this, you only need HOCON of your item (this is the representation of item that was described earlier). HOCON allows you to twist the item as you want. To do this, you create a string: HOCON and try to deserialize it using the configuration node.
> your_matname - first part of "egg:0" (egg);
your_meta - second part of "egg:0" (0);

> s = "ContentVersion=1\nCount="+your_count+"\nItemType=(slash)""
+your_matname+"(slash)"\nUnsafeDamage="+your_meta;
Replace (slash) with slash

> ItemStackSnapshot iss = ItemStackHOCONSerializer.deserializeSnapShot(s);
ItemStack is = Sponge.getRegistry().createBuilder(ItemStack.Builder.class)
.fromSnapshot(iss).build();

is - our output ItemStack.

the deserializeSnapShot itself looks like this (Zerthick's code):

> public static ItemStackSnapshot deserializeSnapShot(String serializedSnapshot) throws ObjectMappingException, IOException {
ConfigurationNode node = HoconConfigurationLoader.builder().setSource(() -> new BufferedReader(new StringReader(serializedSnapshot))).build().load();
return node.getValue(TypeToken.of(ItemStackSnapshot.class));
}

If to sum up, HOCON is actually even more powerful than the old bukkit data type of the item. HOCON allows you to store an item in a database or in separate files, in addition, you can even enchant an item

>I used:
spongeforge - 1.10.2-2477-5.2.0-BETA-2731
spongeapi - 5.0.0-20161223.142907-29
forge - 1.10.2-12.18.3.2477

[Text translated from Russian to English with Google Translator. Translation may not be 100% accurate]

**Comment by gabizou** [comment]
Seeing as we're at a standstill due to how mods treat damage values, the item meta is accessible through the `DataContainer` if you were to deserialize with an appropriate damage value as shown [here in the implementation](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/item/inventory/SpongeItemStackBuilder.java#L172). Fortunately, 1.13 is bringing an end to damage values, and as such I think I can close this issue as the workaround has suited developers in the past, and present, and I don't necessarily feel that making changes to the API to support an already long deprecated system is worth the effort.
