### ISSUE TITLE
Feature: dynamic MOTD.

### ISSUE THREAD

**Issue by RiftomeR** [SpongePowered/SpongeAPI#1696]
Add way to dynamically modify MOTD and animate using API.

**Comment by stephan-gh** [comment]
Are you referring to the MOTD of the status ping? If so:
https://jd.spongepowered.org/6.0.0/org/spongepowered/api/event/server/ClientPingServerEvent.Response.html#setDescription-org.spongepowered.api.text.Text-

**Comment by ryantheleach** [comment]
Also note, that it gives all the information required to customize per client.

https://jd.spongepowered.org/6.0.0/org/spongepowered/api/network/status/StatusClient.html

**Comment by ryantheleach** [comment]
@RiftomeR If the above doesn't solve your problem please respond and I will reopen, but at this point this looks solved on our end.

**Comment by ryantheleach** [comment]
@Minecrell On second read, I think they want to be able to keep sending additional responses in order to animate the MOTD, I've edited this to make it more clear.

**Comment by stephan-gh** [comment]
Animated MOTDs were disabled in Minecraft 1.8.3, therefore this is no longer relevant.
