### ISSUE TITLE
EntityUniverse::spawnEntities should return a list of entities spawned.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1701]
As per https://github.com/SpongePowered/SpongeCommon/issues/1365

> The return is actually useless regardless of what it is changed to return. It should instead return a list of entities that were actually spawned.

https://github.com/SpongePowered/SpongeAPI/blob/9aeb46721b8bcaa45c96e1b73ef0ddd18c4d78ff/src/main/java/org/spongepowered/api/world/extent/EntityUniverse.java#L268

Needs to be modified to return a list of entities.

**Comment by parlough** [comment]
This is a simple enough fix but it will be breaking.

**Comment by parlough** [comment]
Should the `EntityUniverse#spawnEntity` method return an `Optional<Entity>` as well?

**Comment by ryantheleach** [comment]
I'd say so. Even if it's solely for consistency sake.

**Comment by liach** [comment]
I would prefer a list of some sort of transaction results in this case. Sorting out which ones are not spawned is somewhat painful and difficult.

**Comment by ryantheleach** [comment]
@liach you may want to comment that here or it will be missed: https://github.com/SpongePowered/SpongeAPI/pull/1705
