### ISSUE TITLE
Entity.transferToWorld inconsistency with Javadocs

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeAPI#1719]
https://github.com/SpongePowered/SpongeAPI/issues/1000#issuecomment-346660025

https://github.com/SpongePowered/SpongeAPI/blob/cc44fdf0088c65d69883b3510b30321e1aac2a0e/src/main/java/org/spongepowered/api/entity/Entity.java#L336

https://github.com/SpongePowered/SpongeAPI/blob/cc44fdf0088c65d69883b3510b30321e1aac2a0e/src/main/java/org/spongepowered/api/entity/Entity.java#L360

The Javadocs state that these methods will load the target world, so these should be `loadWorld()` instead of `getWorld()`.

@Deamon5550
> @JBYoshi open an issue for that one, if that is the decided case then it needs to be moved to common to check the enabled state properly.

**Comment by Deamon5550** [comment]
The reason I suggested an issue to track and discuss this is because it cannot simply be `loadWorld` to follow the javadoc as there needs to be an additional check for if that world is enabled.

It is a simple change though if someone wants to grab it.

**Comment by JBYoshi** [comment]
I thought `loadWorld()` already handles that check.

https://github.com/JBYoshi/SpongeCommon/blob/79410aa688649c96d60507df7e190f5985906379/src/main/java/org/spongepowered/common/world/WorldManager.java#L613-L617

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/commit/13dce1d9be847d11336e737a643f9c2cdb9e9c03 (Impl moved to common)
