### ISSUE TITLE
Inconsistent build methods in builders.

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeAPI#1721]
The `build` methods in builders should be more consistent in the API. Some take the `PluginContainer` and have a separate `id` method, some take `id` and `plugin`object, some take a `pluginId` and `id`, etc. This is mostly related to catalog type builders.

https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/DataRegistration.java#L196
https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/item/recipe/crafting/ShapelessCraftingRecipe.java#L123
https://github.com/SpongePowered/SpongeAPI/pull/1554/files#diff-6b59fb55f52c7b4b35192af6063e37fcR97

**Comment by ryantheleach** [comment]
@gabizou Is this a big enough change to worth breaking plugins that already use these builders for the sake of consistency?

**Comment by Cybermaxke** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/d40b52e9a046a02d072af660b52f589d46f87e0c
