### ISSUE TITLE
Allow deleting of a specific child of a Text.Builder

### ISSUE THREAD

**Issue by ShortCircuit908** [SpongePowered/SpongeAPI#1727]
Currently, there is no way to remove a specific child of a `Text.Builder`. This is particularly bothersome when creating delimited lists, where one would normally remove the trailing delimiter after the list is built. This could be achieved by introducing a `Builder.remove(int index)` method, or by making `Builder.getChildren()` return a mutable list.
Something like
```Text.Builder textBuilder;
int i;
for (Something s : listOfSomethings) {
    textBuilder.append(Text.of(s));
    if(i < listOfSomethings.size() - 1){
         textBuilder.append(Text.of(", "));
    }
}
```
could be simplified to
```Text.Builder textBuilder;
for (Something s : listOfSomethings) {
    textBuilder.append(Text.of(s))
            .append(Text.of(", "));
}
textBuilder.remove(textBuilder.getChildren().size() - 1);
```

**Comment by ST-DDT** [comment]
What would be your usecase for this change/feature?

**Comment by ST-DDT** [comment]
As an alternative you could use [`Text#joinWith(Text separator, Text... texts)`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/text/Text.java#L1212).

````java
textBuilder.append(Text.joinWith(Text.of(", "), listOfSomethings.stream().map(Text::of).iterator());
````

**Comment by ryantheleach** [comment]
Text and String joiners are the widely accepted answer for the use-case described, however there may be some utility in having the ability to drop text components.
