### ISSUE TITLE
Remove SpawnEntityEvent.Spawner in favor of using Causes

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/SpongeAPI#1732]
With the new cause system it is quite easy to determine when an entity spawn event is a result of a mobspawner, unless additional methods are added specifically to the SpawnEntityEvent.Spawner event, I propose it should be dropped in favor of just analyzing the cause of the base SpawnEntityEvent.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/commit/0e64d43e7aedfe53de5abc07b4d3d3b02fe8ff70#diff-7b95d9059c4d49f3333295fd676ad64d
