### ISSUE TITLE
Expose enchanting seed to plugins?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1734]
I'd like to see `XpSeed: The seed used for the next enchantment in enchantment tables.` exposed in some form to Sponge Plugins.

This would allow plugins to have (safe) access to allow rerolling of enchantments, or change the enchanting behavior as they wish.

**Comment by ImMorpheus** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/1954
