### ISSUE TITLE
Bat and Ghast implementation inconsistent with other entities

### ISSUE THREAD

**Issue by ShortCircuit908** [SpongePowered/SpongeAPI#1735]
Sponge API version: 7.0.0-SNAPSHOT

`org.spongepowered.api.entity.living.Bat` and `org.spongepowered.api.entity.living.monster.Ghast` do not implement `org.spongepowered.api.entity.living.Creature`, and Ghast should(?) also implement `org.spongepowered.api.entity.living.monster.Monster`. In addition, Bat implements `org.spongepowered.api.entity.living.Ambient`, which "Represents an entity that can not be interacted with and only adds to the ambiance of the environment," which is incorrect in the case of the Bat as it can be interacted with.

**Comment by SimonFlash** [comment]
It's a reflection of how their implemented in Minecraft. Neither `EntityGhast` nor `EntityBat` extend `EntityCreature`, and although `EntityGhast` is within the `monster` package it extends `EntityFlying`, not `EntityMonster`. Likewise, `EntityBat` extends `EntityAmbientCreature`.

As much as I agree with your logic behind thinking that, it's unfortunately not something under Sponge's control.

**Comment by ryantheleach** [comment]
It's an issue of naming. The problem is working out what Creature means, or what defines a creature differently.

Ambient is an odd name as well.

My suspicion is that one of these is for 'ground based things' and the other is for 'custom physics' But I don't really know all that much about it.

**Comment by ShortCircuit908** [comment]
`Aerial` is already an interface apparently designating flying creatures, including `EnderDragon`, `Bat`, `Ghast`, `Wither`, and `Blaze`, but not `Parrot`. It seems there is inconsistency there as well.

**Comment by gabizou** [comment]
If Mojang were to get rid of the class inheritance and make entities data driven, then we wouldn't have the silly entity hierarchy as it currently is. I think @Zidane and I at one point argued about how entities were to be represented, the cleaned up normal way, or the true to the implementation mapping of their classes and interfaces.

**Comment by Zidane** [comment]
Its an implementation leak but we elected to follow Mojang's decisions on what constitute as what. Its a hand we've been dealt with the logic behind the base game.

We really need data driven Entities finally..
