### ISSUE TITLE
Data Keys/Manipulator for RepairCost NBT for Anvil 'recipes'

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1767]
Im facing another problem when trying to work with anvil. i want to create a "recipe". Depending on the items in first and second anvil's slot i want to set itemstack to output slot

The item is set to the output slot but the player cannot interact with it. 
- The event ClickInventoryEven is not even fired when clicking on the item in output slot. 

I think i might have a clue:
When you try to repair an item theres a nbt tag called "RepairCost", which represents required amount of levels a player has to have
See: https://i.gyazo.com/b55a9b1e9207af16dd90e49f396d85dd.png
The Datamanipulator & key seems to be completly missing in api (v 7.1)

Test code:

    @Listener
    public void onItemForge(ClickInventoryEvent event, @First Player player) {
        Container i = event.getTargetInventory();
        if (i.getArchetype() == InventoryArchetypes.ANVIL) {
            if (i instanceof BlockCarrier) {
                BlockCarrier b = (BlockCarrier) i;
                Optional<ItemStack> peek = event.getTargetInventory().query(QueryOperationTypes.INVENTORY_PROPERTY.of(SlotIndex.of(0))).peek();
                Optional<ItemStack> peek1 = event.getTargetInventory().query(QueryOperationTypes.INVENTORY_PROPERTY.of(SlotIndex.of(1))).peek();
                if (peek.isPresent() && peek1.isPresent()) {
                    ItemStack itemStack = ItemStack.of(ItemTypes.PAPER, 1);
                    event.getTargetInventory().query(QueryOperationTypes.INVENTORY_PROPERTY.of(SlotIndex.of(2))).offer(itemStack);
                }
            }
        }
    }

**Comment by ryantheleach** [comment]
@Faithcaio Considering this involves containers, has this been generalized by Mojang to make this possible? Is RepairCost really suitable to being data? It's my guess that Repair Cost is only used in the 'preview' and not the 'result' of the recipe as well. So maybe there is an argument to having separate previews and results?

**Comment by Cybermaxke** [comment]
Maybe `Container`s (`Inventory`s) could also be some kind of `DataHolder` to support data?

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/pull/1898

(The PR used an event instead of the keys proposed in this issue but the result is the same)
