### ISSUE TITLE
ClickInventoryEvent is missing location information

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/SpongeAPI#1772]
As of API7.1, I can't find an predictable way to find Locatable from the inventory attached to the SlotTransaction.
Sometime, the root inventory is a CarriedInventory which may contain an optional Carrier which may implement Locatable which gives us a location.
That's a lot of conditions and for everything else, I don't know how to get it.

Example 1: AE2 crafting terminal is a block, but Carrier is empty:
root/parent is: appeng.container.implementations.ContainerCraftingTerm@bb13b95

SlotTransaction{slot=org.spongepowered.common.item.inventory.adapter.impl.slots.SlotAdapter@3a86b4ad, original=SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}, default=SpongeItemStackSnapshot{itemType=draconicevolution:draconic_ingot, quantity=7}, custom=Optional.empty, valid=true}

Example 2: crafting from player inventory isn't considered a CarriedInventory?
root/parent is: org.spongepowered.common.item.inventory.adapter.impl.comp.MainPlayerInventoryAdapter@64711d47

SlotTransaction{slot=org.spongepowered.common.item.inventory.adapter.impl.slots.SlotAdapter@6b181d4e, original=SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}, default=SpongeItemStackSnapshot{itemType=thermalfoundation:material, quantity=2}, custom=Optional.empty, valid=true}

Example 3: fusion crafting with Draconic Evolusion (?) has an empty carrier
root/parent is: com.brandon3055.draconicevolution.inventory.ContainerFusionCraftingCore@5c5a75cc

SlotTransaction{slot=org.spongepowered.common.item.inventory.adapter.impl.slots.SlotAdapter@48d9b809, original=SpongeItemStackSnapshot{itemType=minecraft:nether_star, quantity=61}, default=SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}, custom=Optional.empty, valid=true}

Example 4: dropping from hotbar returns org.spongepowered.common.item.inventory.adapter.impl.comp.HotbarAdapter which doesn't implements CarriedInventory

**Comment by Faithcaio** [comment]
The problem with modded containers is that we don't really have a way to know what block they belong to.
I already try finding it:
https://github.com/SpongePowered/SpongeCommon/blob/921d2295a31fd06bb3f0c4dd525ec0baf807dc64/src/main/java/org/spongepowered/common/item/inventory/util/ContainerUtil.java#L480-L501

I quickly looked at the Containers:
AE2 ContainerCraftingTerm: no idea how to get a Location
DE ContainerFusionCraftingCore: chould get Location by looking at all slots for Tileentity instead of only first one.

Player CraftingInventory:
Are you sure you got the root? Root should be ContainerPlayer which is then has the Carrier.
Hotbar:
Same thing the root should be ContainerPlayer/InventoryPlayer and should have a Carrier.

**Comment by LemADEC** [comment]
Turns out the existing approach in prism was only looking for CarrierInventory on parent. I've modified it to check if parent and root are Locatable instances before looking for if root is a CarrierInventory.
This new approach solved 2 cases (player dropping from hotbar and crafting from inventory).

After one day usage, I've collected the following behaviors:
**Case 1:** some blocks have carriers that aren't Locatable, including vanilla
Vanilla crafting table
carrier is Locatable net.minecraft.inventory.ContainerWorkbench@1a9c87c7
with root is net.minecraft.inventory.ContainerWorkbench@1a9c87c7

Vanilla double chest (?)
carrier is net.minecraft.inventory.InventoryLargeChest@418d3cf3
root is net.minecraft.inventory.ContainerChest@610eaa9

A sponge wrapper?
carrier isn't Locatable org.spongepowered.common.item.inventory.util.ContainerUtil$1@58ae6e2d
transaction is SlotTransaction{slot=org.spongepowered.common.item.inventory.adapter.impl.slots.SlotAdapter@1dae369e, original=SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}, default=SpongeItemStackSnapshot{itemType=minecraft:sand, quantity=50}, custom=Optional.empty, valid=true}
root is nc.container.processor.ContainerManufactory@69411b5


**Case 2:** items used from inventory (like backpacks, books or tools) have a CarrierInventory root with no carrier
Chisel chisel
root is team.chisel.common.inventory.ContainerChisel@120456fb

Forestry backpack
root is forestry.storage.gui.ContainerBackpack@32124e05

Iron Backpack
root is gr8pefish.ironbackpacks.container.ContainerBackpack@6da2f68f

Cooking for blockheads book
root is net.blay09.mods.cookingforblockheads.container.ContainerRecipeBook@5df5791c


**Case 3:** various mod containers have CarrierInventory root with no carrier
Applied Energistics2 blocks
root is appeng.container.implementations.ContainerCraftingTerm@109785e6
root is appeng.container.implementations.ContainerGrinder@48ec4842
root is appeng.container.implementations.ContainerInscriber@17b10522
root is appeng.container.implementations.ContainerInterface@61eb26d1
root is appeng.container.implementations.ContainerSkyChest@3057cf34
root is appeng.container.implementations.ContainerUpgradeable@2b45513a
root is appeng.container.implementations.ContainerVibrationChamber@3b61505c

Actually Additions blocks
root is de.ellpeck.actuallyadditions.mod.inventory.ContainerBreaker@39259aa4
root is de.ellpeck.actuallyadditions.mod.inventory.ContainerCoalGenerator@14b5c858
root is de.ellpeck.actuallyadditions.mod.inventory.ContainerGiantChest@14d112cd

Bibliocraft bookcase
root is jds.bibliocraft.containers.ContainerBookcase@eb21918

BigReactors
root is erogenousbeef.bigreactors.gui.container.ContainerReactorAccessPort@7275f0b1

Immersive engineering
root is blusunrize.immersiveengineering.common.gui.ContainerFermenter@10bcc349
root is blusunrize.immersiveengineering.common.gui.ContainerRefinery@4673ae94
root is blusunrize.immersiveengineering.common.gui.ContainerRevolver@6569255b
root is blusunrize.immersiveengineering.common.gui.ContainerToolbox@63f73065

EnderStorage
root is codechicken.enderstorage.container.ContainerEnderItemStorage@6d0897a4

ExtraUtilities2 Trash can
root is com.rwtema.extrautils2.tile.TileTrashCan$ContainerTrashCan@6676e8e4

IndustrialCraft 2
root is ic2.core.gui.dynamic.DynamicContainer@232fa339

Pam's shipping bin
root is com.pam.harvestcraft.gui.ContainerShippingBin@48db7835

ThermalExpansion machines
root is cofh.thermalexpansion.gui.container.machine.ContainerCharger@6e3baddd
root is cofh.thermalexpansion.gui.container.machine.ContainerCrucible@1c43413d
root is cofh.thermalexpansion.gui.container.machine.ContainerExtruder@90d3c38
root is cofh.thermalexpansion.gui.container.machine.ContainerFurnace@a99e79e
root is cofh.thermalexpansion.gui.container.machine.ContainerPulverizer@232432b2
root is cofh.thermalexpansion.gui.container.machine.ContainerSawmill@50a5cf5
root is cofh.thermalexpansion.gui.container.machine.ContainerTransposer@18c6c211

Tinker's blocks
root is slimeknights.tconstruct.smeltery.inventory.ContainerSmeltery@1651c806
root is slimeknights.tconstruct.tools.common.inventory.ContainerCraftingStation@1d130c9a
root is slimeknights.tconstruct.tools.common.inventory.ContainerToolForge@d48cb13
root is slimeknights.tconstruct.tools.common.inventory.ContainerToolStation@7d15a74b


**Case 4:** Draconic Evolution fusion crafting
root is com.brandon3055.draconicevolution.inventory.ContainerFusionCraftingCore@5c5a75cc
=> I'll try your proposal of scanning all slots


**Case 5:** Elulib inventory slot's root isn't a CarriedInventory
transaction is SlotTransaction{slot=elucent.elulib.container.SlotInventoryDefault@1685e7cc, original=SpongeItemStackSnapshot{itemType=gadgetrycore:silicon, quantity=64}, default=SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}, custom=Optional.empty, valid=true}
root is org.spongepowered.common.item.inventory.adapter.impl.comp.OrderedInventoryAdapter@3756c66f
=> is there an API being that OrderedInventoryAdapter class?

**Comment by LemADEC** [comment]
Does the cause tracker include the block that was activated by the player? could we recover it from the ClickInventoryEvent and ChangeInventoryEvent.Pickup events?

**Comment by Faithcaio** [comment]
CarriedInventory is mixed into all Containers because in some cases we can provide a Carrier.
All we can do with those modded inventories is trying to find the TileEntity so that we can extract the location from it.

BlockCarrier and MultiblockCarrier should be present for the Vanilla Inventories that are not TileEntities (Workbench, Anvil) and the DoubleChest.

For all opened inventories the root should always be some Container.

ChangeInventoryEvent.Pickup is not an interaction with a block.

As for saving the activated block for ClickInventoryEvents that might be possible.

**Comment by LemADEC** [comment]
I see BlockCarrier has a getLocation() method but doesn't implement Locatable. Any reason for that?

EnderChest doesn't seem to have BlockCarrier for the slot parent nor root nor carrier.

**Comment by Faithcaio** [comment]
~I forgot to add Locatable.~ fixed

EnderChests are not BlockCarriers. The player should be carrier for an EnderChest Inventory.

**Comment by Faithcaio** [comment]
added location for BlockCarrier on block interact / inventory open
also BlockCarrier is Locatable now
So this should work in most cases now.
