### ISSUE TITLE
THROWER and PROJECTILE_SOURCE EventContextKeys

### ISSUE THREAD

**Issue by RedNesto** [SpongePowered/SpongeAPI#1774]
During the implementation of the LaunchProjectileEvent, I saw there were two `EventContextKeys` that can be used for the same event: `THROWER` and `PROJECTILE_SOURCE`.

What is the difference between these? 

I don't see any to be honest. For me, `PROJECTILE_SOURCE` is more general than `THROWER` (which may imply a projectile launched by hand to me, but still a _projectile_), so if we need to remove one, I would remove `THROWER`.

**Comment by ImMorpheus** [comment]
From what I see, `PROJECTILE_SOURCE` is only used [here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java#L736) as the second parameter of the method `handleCollideImpactEvent`.
This method is called:
[MixinEntityThrowable](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/projectile/MixinEntityThrowable.java#L98) with the argument `this.getShooter()`
[MixinEntityArrow](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/projectile/MixinEntityArrow.java#L116) with the argument `getShooter()`
[MixinEntityFireball](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/projectile/MixinEntityFireball.java#L90) with the argument `this.getShooter()`

But, when added as a context key in the CSM `getShooter()` is always the `EventContextKeys.THROWER`: [MixinEntityLargeFireball](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/projectile/MixinEntityLargeFireball.java#L88), [MixinEntityWitherSkull](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/projectile/MixinEntityWitherSkull.java#L127), [MixinEntityFireworkRocket](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/item/MixinEntityFireworkRocket.java#L159), ...

So, yeah... They represent the same thing.

**Comment by Zidane** [comment]
We need to just go with Projectile_Source for API 8.

**Comment by ryantheleach** [comment]
Should we deprecate thrower asap then, with the note that Projectile_Source replaces it in API 8 ?

**Comment by parlough** [comment]
This has been solved with https://github.com/SpongePowered/SpongeAPI/pull/1779
