### ISSUE TITLE
Meager documentation for loadChunk and loadChunkAsync

### ISSUE THREAD

**Issue by tylerbucher** [SpongePowered/SpongeAPI#1775]
**Issue**
Meager documentation for [loadChunk](https://github.com/SpongePowered/SpongeAPI/blob/d5f1171eb1ede4fe12efe731271eb3ad5a7cf48d/src/main/java/org/spongepowered/api/world/World.java#L178) and [loadChunkAsync](https://github.com/SpongePowered/SpongeAPI/blob/d5f1171eb1ede4fe12efe731271eb3ad5a7cf48d/src/main/java/org/spongepowered/api/world/World.java#L220)

**Explanation**
As the title says, there is insufficient documentation about `loadChunk` or `loadChunkAsync` to properly or safely use these two functions in other threads. As it stands neither of the two functions state much about thread safety or thread use. Although, one could conclude by the difference in function names, `loadChunk` would be unsafe for threads and `loadChunkAsync` would be safe for use in another thread however, per the implementations that is not the case.

**Noteworthy Remarks**
- The documentation for `loadChunkAsync` does not sate when the `shouldGenerate` boolean flag is `true` the function acts like `loadChunk`, there by making it unsafe for thread use.
- @bloodmc Seemed to try and alleviate the issue stated above with this commit [here](https://github.com/SpongePowered/SpongeCommon/commit/9aebb5b80d1760ec5715cd6f99fe3e301685ec5f) which just returns an empty default chunk if `loadChunkAsync` with `shouldGenerate = true` is called on another thread.

**Closing Thoughts**
I know I brought up implementation specific issues but I believe it is important to state how the function should work under the hood or be implemented so the functions are not miss / improperly used.

**Comment by ImMorpheus** [comment]
`loadChunkAsync` is gone in API 8
