### ISSUE TITLE
Provide a LanguageAdapter that plugins can use to customize how to get Plugin instance

### ISSUE THREAD

**Issue by Katrix** [SpongePowered/SpongeAPI#1783]
Currently, all `Plugin`s have to be a class annotated with `@Plugin`. This is fine for Java which only has `class`, but for languages like Scala and Kotlin which has things like `object`, this can be inconvenient. The goal here is something similar to Forge's `ILanguageAdapter`. This would allow plugins made in such languages to use an `object` for their `@Plugin` instance, instead of a `class`.

One possible way to do this could be something like this.

```java
public interface LanguageAdapter {

	/**
	 * Gets or creates a custom plugin instance.
	 * @param container The plugin container for this plugin.
	 * @param pluginClass The class which the {@link Plugin} annotation was found on.
	 * @param classLoader The classLoader for this plugin.
	 * @param factoryMethod If the {@link PluginProvider} annotation was placed 
	 * on a static method, returns that method. This method acts as a factory for the plugin instance.
	 * @return A optional plugin instance, signalling that a custom object will be used. 
	 * If no value was returned, uses the class like normal.
	 */
	Optional<Object> getInstance(PluginContainer container, Class<?> pluginClass, ClassLoader classLoader, @Nullable Method factoryMethod);
}

/**
 * Provides a custom way to get a plugin instance.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface PluginProvider {

	Class<? extends LanguageAdapter> value();
}
```

If a custom plugin instance is returned, a Guice provider could be used instead of the default behavior.

**Comment by SimonFlash** [comment]
As someone who has limited experience with Kotlin and Forge (and none with Scala), I'd like to ask for some clarification on how this would affect existing Java plugins as well as any design changes to new ones. Is this a breaking change? What would our plugin classes look like if this were to be merged?

Additionally, I would recommend touching on how this would benefit developers working with Kotlin/Scala - I'm not particularly concerned with it since I don't use them, but I'm nonetheless interested on why this is an issue. Including some before and after examples might be a good idea.

**Comment by kashike** [comment]
Rough outline:
https://github.com/SpongePowered/SpongeAPI/compare/feature/plugin-construction
https://github.com/SpongePowered/SpongeCommon/compare/feature/plugin-construction
https://github.com/SpongePowered/SpongeForge/compare/feature/plugin-construction

**Comment by Katrix** [comment]
It would change nothing for existing plugins using what exists today. The main advantage for Scala and Kotlin devs is that they can treat a class which is a Singleton as an actual Singleton.

For the simplest case, just switch out class with object when defining the plugin entry point. This would then mean that you don't need to bother with a static field to refer to the plugin from outside as well.

For example, instead of `thing.doThing(MyPlugin.plugin, <otherVars>)` you would write `thing.doThing(MyPlugin, <otherVars>)`

Another advantage is that it will decrease the friction felt when coming from forge to sponge. I remember personally not really understanding why I couldn't use object when first coming from forge.

**Comment by Katrix** [comment]
BTW, do you make sure that stuff is still classloaded in the correct order when doing it that way? I think I remember Forge having some problems there.

**Comment by ItsDoot** [comment]
PR for reference: #1990

**Comment by ImMorpheus** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/1990#issuecomment-650779079
