### ISSUE TITLE
Incorrect work of the event MoveEntityEvent.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/SpongeAPI#1789]
`      @Listener

	public void playerMoveEvent(MoveEntityEvent e){ 

		Player player = (Player) e.getTargetEntity(); 

               // We do something with the player, for example, teleport when a certain position is reached. }`

When the sphere of experience appears, the following error appears in the console. https://pastebin.com/tJaxvDJ9

I do not understand why it reacts to the sphere of experience, if the listener explicitly points to the player.
I apologize for my english, I used google translate.

**Comment by kashike** [comment]
You aren't checking if the `Entity` is actually a `Player` before casting.

**Comment by SawFowl** [comment]
I also tried this option.
Living living = (Living) e.getTargetEntity();
		if(living instanceof Player) {
                //Action.
}

**Comment by liach** [comment]
@Mr-Krab a minecart can move, too!

**Comment by SawFowl** [comment]
Yes, but I'm trying to track only the player.

**Comment by liach** [comment]
@Mr-Krab I mean if the target entity is a minecart, your "alternative option" would crash.
Do this instead:
```java
@Listener
public void playerMoveEvent(MoveEntityEvent e) {
    if (e.getTargetEntity() instanceof Player) {
        Player player = (Player) e.getTargetEntity();
        // do your stuff
    }
}
```

**Comment by SawFowl** [comment]
Thanks, works as it should. There are no errors. I think after finalizing I'll make a public version of my plugin.

**Comment by liach** [comment]
That is what @kashike said at first. I suggest you go to discord or Russian forums for help in the future for such minor issues.
