### ISSUE TITLE
Unable to Give RespawnLocationData to a Player

### ISSUE THREAD

**Issue by Xenmai** [SpongePowered/SpongeAPI#1790]
Hi there. I'm having a problem when giving respawn locations to a player in version 1.12.2 and API 7.1.0.

I've tried two methods: using the RESPAWN_LOCATIONS data keys, and the RespawnLocationData manipulator. Both methods can be summarized as getting the current respawn locations from the player, transforming it, and offering it back to the same player. After doing this, I get the respawn location data from the player again, but it is still empty, so no changes went through.

When using the data manipulator way, I also get a "FAILURE" data transaction result, which means the changes failed due to an expected reason (such as the player not supporting this data).

I've no idea about what could be causing this problem, so any help is appreciated. Thanks a lot!

**Comment by gabizou** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Xenmai! I've moved your issue to [SpongePowered/SpongeCommon#1824](https://github.com/SpongePowered/SpongeCommon/issues/1824).
