### ISSUE TITLE
Build TextTemplate just like Text

### ISSUE THREAD

**Issue by Eufranio** [SpongePowered/SpongeAPI#1792]
Right now, TextTemplates can only have 1 color, more colors should be specified within children texts. It'd be nice if TextTemplate was able to build a Text like the `Text.of()`, on `TextTemplate.of()`. So, we would be able to do `TextTemplate.of(TextColors.RED, "Hello ", TextColors.GREEN, " world!")` instead `TextTemplate.of(TextColors.RED, "Hello ", Text.of(TextColors.GREEN, "world"))`.

**Comment by ImMorpheus** [comment]
As of API 8 we are now using [Adventure](https://github.com/KyoriPowered/adventure). 

This means the old Text api is gone and all the related issues (especially those involving breaking changes) are no longer relevant, therefore I'm closing this.
