### ISSUE TITLE
Fly event

### ISSUE THREAD

**Issue by mosemister** [SpongePowered/SpongeAPI#1793]
Just a quick report that ChangeDataHolderEvent.ValueChange is not fired with some data values. Ill create a list here of what keys work with it. 

- [ ] IS_FLYING

**Comment by parlough** [comment]
There's quite a few keys it still does not fire for, but it is on our radar to implement the event for more keys as time goes on.

**Comment by parlough** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @mosemister! I've moved your issue to [SpongePowered/SpongeCommon#1829](https://github.com/SpongePowered/SpongeCommon/issues/1829).

**Comment by mosemister** [comment]
Thanks
