### ISSUE TITLE
Language File Service

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/SpongeAPI#1794]
A common request users have of plugin developers is to provide some kind of language file where they can translate all of the strings of a plugin.  As far as I know, there is currently no standard way to do this and all plugin developers must implement their own solution.  I think it would be very useful for Sponge to provide a uniform API and file format specification for accessing and defining language files.  This would both make it easier on developers trying to add multi-language support to their plugins as well as potential translators who would be able to have a consistent file format.

I believe some discussion of this idea was made in https://github.com/SpongePowered/SpongeAPI/issues/564 but it does not seem to have materialized.

**Comment by kashike** [comment]
This is coming with the new version of the text api.

**Comment by Zerthick** [comment]
@kashike Is there a link to a relevant discussion somewhere on this topic?
