### ISSUE TITLE
Apply order to Inventory#offer

### ISSUE THREAD

**Issue by SimonFlash** [SpongePowered/SpongeAPI#1795]
[This commit](https://github.com/SpongePowered/SpongeCommon/commit/ca2896841a9b3aa2008208af99c4a20199929874) changed the order of the `GridInventory` to be before the `Hotbar` in the `Main PlayerInventory`. As a result, offering an item to the player's inventory now tries to send it to their storage first rather than the hotbar. This has been reported as a bug a couple of times, as even though it's correct by implementation it's not what players expect (and not what Vanilla does either).

One solution to this is the following:
```java
public InventoryTransactionResult offer(ItemStack item, Class<? extends Inventory> types) {
    Inventory inventory = //some empty inventory. Would be nice to have Inventory.empty() in the API
    for (Class<? extends Inventory> type : types) {
        inventory = inventory.union(this.query(QueryOperationTypes.INVENTORY_TYPE.of(type)));
    }
    inventory = inventory.union(this);
    return inventory.offer(item);
}
```

This method constructs a new inventory that reorders the slots based on the given types. This means that a call of `inventory.offer(item, Hotbar.class)`, will construct a new inventory containing all of the slots in the hotbar followed by any remaining slots in the inventory (as per `Inventory#union`).

This does not provide an easy way to include the hand of a player first, and I don't have a solution for this in the API (though it is easy enough to do as a utility method if a developer chooses to).

**Comment by codeHusky** [comment]
As it is right now, you currently need to use work-around code to get this ordering functionality that was incidentally present API 6 and before. Major props to whoever is able to take this up.

**Comment by Faithcaio** [comment]
You can now get an inventory with different ordering using `Inventory#transform`.
