### ISSUE TITLE
Abstract methods in 'spongepowered.api.world.extent.InteractableVolume.java'

### ISSUE THREAD

**Issue by Evolht** [SpongePowered/SpongeAPI#1796]
Found a few abstract methods during development.

`
    boolean digBlockWith(int x, int y, int z, ItemStack itemStack,GameProfile profile);
`

`java.lang.AbstractMethodError: Method net/minecraft/world/WorldServer.digBlockWith(IIILorg/spongepowered/api/item/inventory/ItemStack;Lorg/spongepowered/api/profile/GameProfile;)Z is abstract
	at net.minecraft.world.WorldServer.digBlockWith(WorldServer.java) ~[oo.class:?]
	at org.spongepowered.api.world.extent.InteractableVolume.digBlockWith(InteractableVolume.java:182) ~[InteractableVolume.class:?]`

**Comment by gabizou** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Evolht! I've moved your issue to [SpongePowered/SpongeCommon#1841](https://github.com/SpongePowered/SpongeCommon/issues/1841).
