### ISSUE TITLE
Command Arguments causing ClassCastException

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/SpongeAPI#1797]
**Related Changes**
- https://github.com/SpongePowered/SpongeAPI/commit/6059354741a815cd2a86b63274ba97f8530de84c#diff-325508c3a8ee152cf222a18a16566a37R1137
  - Also this commit in general. Pushed in ~4 days ago as of writing.

This is affecting versions since **1.12.2-2611-7.1.0-BETA-2984** at the earliest reported.

Error log one.
https://gist.github.com/codeHusky/8831213c5224022e11dacc89d8d10695

Second error here.
https://gist.github.com/codeHusky/0960e169eb931bec54179ab56c6c274c

The second error log reports a mismatch between the person running the command and the person who's the "source" of the command, iirc.
`KBearZen ran the command` meanwhile `source EntityPlayerMP['runescapejon'/157...`

I confirmed with the reporter that these are, in fact, very different people, and KBearZen is the person who ran the command in game.

**Comment by codeHusky** [comment]
Relates to #1660

**Comment by dualspiral** [comment]
FYI: that second problem is a different one to the first and wasn't linked to #1660 - that part of the code wasn't touched. It's probably an informational error but I'd have to take a closer look to know what is going on. I'm gonna open a new issue with it to remind me to look at it.
