### ISSUE TITLE
Event when user changes selected hotbar slot?

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1799]
Is there any event for this action?
Tried those but they seems to be not implemented, or are not firing.
ChangeEntityEquipmentEvent.TargetPlayer
ClickInventoryEvent.NumberPress

**Comment by Faithcaio** [comment]
try `ChangeInventoryEvent.Held`

**Comment by NeumimTo** [comment]
that worked. 

the class name NumberPress - it will be possible in future to distinguish between mouse scroll and number key press?

**Comment by Faithcaio** [comment]
ClickInventoryEvent.NumberPress is a ClickInventoryEvent those happen on open containers.

**Comment by NeumimTo** [comment]
Answered, closing
