### ISSUE TITLE
Passing invalid username to optional user arg causes error while parsing command

### ISSUE THREAD

**Issue by Lemmmy** [SpongePowered/SpongeAPI#1802]
Somewhere between SpongeForge 2990 and 2996, this code:
```java
    private static final CommandElement TARGET_ELEMENT = firstParsing(
        user(Text.of("user")),
        string(Text.of("address"))
    );
```
no longer works as it should. 

## Before updating Sponge
`/pay Lemmmy` - works properly. `user` arg is set.
`/pay foo@bar` - works properly. `address` arg is set.

## After updating Sponge
`/pay Lemmmy` - works properly. `user` arg is set.
`/pay foo@bar` - errors - says `Error occured while executing command: Invalid username foo@bar` to the user, and logs [this exception](https://hastebin.com/volacafeta) to the console.

This does not seem like intended behaviour for firstParsing.

**Comment by dualspiral** [comment]
Yep, that needs to be wrapped up in an `ArgumentParseException`.

**Comment by Faithcaio** [comment]
Or maybe not throw exceptions when getting a user by invalid name?
We have Optional.empty.

**Comment by Lemmmy** [comment]
@Faithcaio it used to return `Optional.empty()`; I believe a recent commit changed this behaviour (possibly accidentally).

**Comment by dualspiral** [comment]
Yeah, it's accidental. It's because I try to get an exact match before doing pattern matching to improve performance. I'm working on it now.
