### ISSUE TITLE
Readme could list implementations

### ISSUE THREAD

**Issue by mbroomfield-r7** [SpongePowered/SpongeAPI#1803]
It would be nice if the readme mentioned all known implementations of the Sponge API.

I know there's SpongeVanilla and SpongeForge, but I remember someone in the community was making an open source server which was Sponge compatible

**Comment by Lemmmy** [comment]
https://github.com/LanternPowered

**Comment by ryantheleach** [comment]
I think it would be fair to mention Lantern, just make sure that it's clearly specified as not a 'Sponge Powered' Project.
