### ISSUE TITLE
`OptionalValue` is missing `.asImmutable()`

### ISSUE THREAD

**Issue by Dykam** [SpongePowered/SpongeAPI#1806]
`OptionalValue` seems to be missing `.asImmutable()`, while `ImmutableOptionalValue.asMutable()` exists.

The implementation however seems correct, as the returned `ImmutableValue<Optional<*>>` can be casted to `ImmutableOptionalValue<*>`.

**Comment by gabizou** [comment]
What? An Immutable value is already immutable... And no, your second sentence **can** be casted, but it won't work directly in production as they are two different types....
