### ISSUE TITLE
World generator crashes at large world sizes!

### ISSUE THREAD

**Issue by githubl0ver69** [SpongePowered/SpongeAPI#1809]
[Referred to you from the Nucleus team @  #1136](https://github.com/NucleusPowered/Nucleus/issues/1136)

**My problem:**
> Short version: Can't generate large worlds because the server crashes.
> 
> Long version: I can only generate a world so large before the server inevitably crashes with an "java.lang.OutOfMemoryError" exception. I don't understand programming so I'm wondering if there's a possible resolution to this.
> 
> The following commands I'm attempting to type with Nucleus:
> ```
> world border set "Survival" 0 0 102400
> world border gen "Survival"
> 
> ```

**Nucleus's response:**
> 
> Nucleus simply invokes the Sponge world pre generator, so it's down to that, it's not Nucleus. It tries to manage the memory but sometimes it just can't....
> 
> ...Ultimately, not a Nucleus problem.

**Comment by phit** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @githubl0ver69! I've moved your issue to [SpongePowered/SpongeCommon#1883](https://github.com/SpongePowered/SpongeCommon/issues/1883).
