### ISSUE TITLE
Allow mapping RemoteConnection to Player

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#1816]
Currently, Sponge's [MessageHandler](https://github.com/SpongePowered/SpongeAPI/blob/8d7ef614ec38b00099a5d33b5bf14175465fe044/src/main/java/org/spongepowered/api/network/MessageHandler.java#L44) only provides the `RemoteConnection` that was responsible for the message being handled. On the server, it's often useful to determine which player sent a custom message. However, Sponge currently requires plugins to manually maintain a mapping between `RemoteConnection`s and `Player`s in order to determine the source of a `Message`.

Sponge should provide a method such as:

```java
public interface Server {

Optional<Player> getPlayer(RemoteConnection connection)

}
```

to make it easy for plugins to perform this lookup.

**Comment by Zidane** [comment]
@Aaron1011 

They cast to PlayerConnection then

**Comment by Aaron1011** [comment]
Well, this is a little embarrassing :)
