### ISSUE TITLE
Scoreboard team

### ISSUE THREAD

**Issue by ya-evgeniy** [SpongePowered/SpongeAPI#1817]
I'm creating a team using this code.
`Team redTeam = Team.builder()`
`                    .name("red")`
`                    .color(TextColors.RED)`
`                    .allowFriendlyFire(false)`
`                    .prefix(Text.builder(" ").color(TextColors.RED).build())`
`                    .build();`

And I add players to it. They can not beat each other, as expected. BUT after the first death, a player who has died can beat allies, just like they do him.

Perhaps because of the same problem, the nickname of the player in the chat is not dyed in the corresponding color.
![image](https://user-images.githubusercontent.com/17035475/39225464-2e629066-4855-11e8-8b8c-10dfbc40ba1b.png)

Server spongevanilla-1.12.2-7.1.0-BETA-41
The problem was noticed on spongevanilla-1.12.2-7.1.0-BETA-33
API v7

p.s. The text is translated by an interpreter.

**Comment by Aaron1011** [comment]
@JekaRUS: This should be fixed in the latest SpongeForge and SpongeVanilla. For future reference, any issues that occur in-game should be opened in an implementation repository (SpongeVanilla, SpongeForge, or SpongeCommon).
