### ISSUE TITLE
Move Living#lookAt implementation to SpongeCommon

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#1820]
Recently, [I fixed a bug in `Living#lookAt`](https://github.com/SpongePowered/SpongeAPI/commit/1a24d8f17e37d337fd8f42aa198a892fa1b9965b) which caused an entity's rotation values to be set to `NaN` if the source and target positions overlapped. 

It turns out that `Living#lookAt` also appears to have a yaw-related bug - if the z-distance between the two locations is 0, then [the method will end up dividing by 0](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/entity/living/Living.java#L180), eventually leading to a `NaN`.

With these issues in mind, I think it would be a good idea to move the implementation of this method out of the API. Someone more familiar with the details of Minecraft rotation value should take a close look at the implementation, to see if any more bugs are lurking.

**Comment by kashike** [comment]
The implementation of this method should also be moved to SpongeCommon.

**Comment by liach** [comment]
is that method even necessary? i recall windy added it.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/commit/77753cdcf0208c78744c925778b290651d463bf9
