### ISSUE TITLE
Missing Key `Keys.POTION_TYPE`

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/SpongeAPI#1822]
I'm missing a key to set the potion type (`Potion` NBT tag) of a potion, as very weird things happen when the tag is missing.

Also it should be set to `minecraft:water` by default.

Also the potion effect types are missing:

- Empty
- Water
- Thick
- Awkward
- Mundane

See: https://minecraft.gamepedia.com/Potion#Item_data

**Comment by BrainStone** [comment]
Looking at the NBT data, I think it would be worth to create another data type for the potion types.

As extended and amplified potions have their own type (See attached screenshot). So I'd suggest adding a `PotionType` interface and `Keys.POTION_TYPE`.

![ss 2018-05-10 at 01 43 44](https://user-images.githubusercontent.com/4106544/39845186-b60fe6da-53f4-11e8-89e0-5db2d9751ef0.png)

**Comment by gabizou** [comment]
> So I'd suggest adding a PotionType interface and Keys.POTION_TYPE.

But we already have `PotionType`, just not data as such. Would you say then that each potion type should have it's own potion item tag? Does it get affected by the potion list in game if you change the types? Does it add on to it?

**Comment by BrainStone** [comment]
Currently there's only `PotionEffectType`. And I suggest adding `PotionType`, for all items that support it (I think that's Potion, Splash Potion, Lingering Potion and Tipped Arrow). When the `Potion` tag is set it determines the name of the potion and also adds an effect. The PotionEffects in the `CustomPotionEffects` tag are added on top of it.

**Comment by Cybermaxke** [comment]
Yeah, `PotionType` isn't available in the API. I already implemented it in lantern, in case someone wants to port it over:
https://github.com/LanternPowered/LanternServer/blob/master/src/main/java/org/lanternpowered/server/effect/potion/PotionType.java
https://github.com/LanternPowered/LanternServer/blob/master/src/main/java/org/lanternpowered/server/effect/potion/PotionTypes.java

**Comment by BrainStone** [comment]
@Cybermaxke would you mind making a PR? Considering most of the code is already available.

**Comment by BrainStone** [comment]
Any update on this? @Cybermaxke

**Comment by Cybermaxke** [comment]
No, it's not a high priority right now.

**Comment by BrainStone** [comment]
You are awesome <3
