### ISSUE TITLE
Upgrade Guice from version 4.1.0 to 4.2.0

### ISSUE THREAD

**Issue by Defman** [SpongePowered/SpongeAPI#1823]

**Comment by parlough** [comment]
This is planned for the API 8 release. Could maybe move it forward to 7.1 if someone has a good enough reason.

**Comment by Defman** [comment]
The only reason i brought it up was that I shadowed multibindings 4.2, and noticed the readme that informed me that it was empty due to the fact it is included in guice by default. Happened to be guice 4.2 and not 4.1, so just had to change the version of multibindings. Just thought I might mention it here, since theres no "breaking" changes.

**Comment by dualspiral** [comment]
#2122 duplicated this, but as it's much newer, I'm closing this as I hadn't realised this was here.
