### ISSUE TITLE
Is there no BlockType ORANGE_GLAZED_TERRACOTTA in BlockTypes ?

### ISSUE THREAD

**Issue by Himmelt** [SpongePowered/SpongeAPI#1825]
I can get the BlockType of minecraft:orange_glazed_terracotta in game by `BlockState#getType` , but why there is no constant field for this type ?

**Comment by BrainStone** [comment]
I just checked myself and infact this particular one is missing.

**Comment by BrainStone** [comment]
@kashike Who would be bes suited for this?

**Comment by parlough** [comment]
Fixed in 9ce554433725f204aebd9b6d2daa5eeaa6a03ef6
