### ISSUE TITLE
Allow accessing and modifying of NBT data (through a DataContainer)

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/SpongeAPI#1829]
I am missing the possibility modify data of objects that is not built in the API. For example if I wanted to modify ItemStacks of modded items, then there's no easy way to modify their NBT data without having to cast them to MC ItemStacks.

I suggest adding a key like `Keys.RAW_DATA` that returns the NBT of the object as a DataContainer (should also allow setting).

Possibly related: SpongePowered/SpongeCommon#950

**Comment by gabizou** [comment]
@BrainStone and I think @pie-flavor I think it's time to officially call [DataHolder#setRawData()](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/DataHolder.java#L68) to officially work properly. Considering that the API is not designed to re-invent the storage query wheels, I'd be willing to expose the raw data container output such that the full NBT values can be re-set through the `DataContainer` passed in. This means however that developers taking advantage of the system to set all the raw data values wouldn't necessarily work out well enough to support manipulating all of vanilla's raw data.

That being said, I'm considering of making the `setRawData` to accept the Sponge formatted containers, where some obvious options will be excluded (like the entity type if it's being set back on an entity), while some other options may include re-setting things like damage values for item stacks will be quasi supported as it's pulled from the container. 

Thoughts @kashike and @Zidane? As far as I'm concerned, the Data API is already well used and I can support offering this setting back for customized items and developers abusing it can be told they're abusing it if there's problems ;) Pinging @Meronat @Cybermaxke @JBYoshi and @Aaron1011 for additional input.

**Comment by ImMorpheus** [comment]
On the API side data has been revamped in API 8. setRawData is still there https://github.com/SpongePowered/SpongeAPI/blob/992ef50c171183070bede2d234379052613d830e/src/main/java/org/spongepowered/api/data/SerializableDataHolder.java#L81 so as far as the API is concerned this needs to be fixed in the implementation.

There's already a spongecommon issue very similar to this so I'm closing this.

https://github.com/SpongePowered/SpongeCommon/issues/1694

**Comment by BrainStone** [comment]
Awesome! Thank you very much!
