### ISSUE TITLE
BlockState.MatcherBuilder#build() throws a NegativeArraySizeException when no traits are specified

### ISSUE THREAD

**Issue by 14mRh4X0r** [SpongePowered/SpongeAPI#1835]
This can be fixed by removing the ` - 1` part in `new BlockTrait<?>[this.traits.size() - 1]`.

(Creating an issue instead of a PR because it is a trivial change)

**Comment by ryantheleach** [comment]
@gabizou ~fixed this in bleeding 14 days ago when it was~ moved to implementation in bleeding.

However this is still a bug in the API on stable.

https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/block/BlockState.java#L287-L291
