### ISSUE TITLE
EntityArchetypes not accepting Data Keys properly

### ISSUE THREAD

**Issue by Xenmai** [SpongePowered/SpongeAPI#1838]
Hi there.

I'm having an issue when giving keys to entity archetypes. I've tried both inside the builder using `EntityArchetype.Builder#set(Key, Value)` and with an already built **EntityArchetype** using `DataHolder#offer(Key, Value)`. The latter returns an **unsuccessful DataTransaction**, even though I'm checking if the **DataHolder supports the key** first (and it does).
So it seems **EntityArchetypes are not accepting Data Keys** at all.

Also on a side note, when creating an entity with `EntityArchetype#apply(Location<World>)` and then spawning it, I get an error about Minecraft not being able to **track the entity** properly. The full error can be found here: https://pastebin.com/0Y0Tnwhz

Thanks a lot for your help and have a nice day!

Note: I'm using **spongevanilla-1.12.2-7.1.0-BETA-48.jar**.

Note 2: I've checked some **SpongeCommon** code (this issue should probably be moved there, sorry), and inside SpongeEntityArchetypeBuilder the `#set(Key, Value)` and `#set(Value)` methods seem to use a **NBT processor** of type "_Tile Entity_", not an "_Entity_" one. Could this be causing the issue? I'm confused as to why that method seems to be coded to work just for Tile Entities, can't I give keys to an Archetype of type Entity? Thanks again for your time!

**Comment by gabizou** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Xenmai! I've moved your issue to [SpongePowered/SpongeCommon#1927](https://github.com/SpongePowered/SpongeCommon/issues/1927).
