### ISSUE TITLE
Economy's Accounts still require a cause for their actions

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeAPI#1839]
While checking whether the code examples in SpongeDocs actually compile I stumbled upon some outdated parts. While trying to update these snippets I found that [Account](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/service/economy/account/Account.java#L58) still require an explicit cause (argument) for each action.
For the rest of the API this concept has been replaced by `Sponge.getCauseStackManager().pushCause(obj)`.

Is this intentional?

**Comment by parlough** [comment]
I believe this is intentional to allow economy stuff to be done off the main thread, but I'm not sure.

**Comment by gabizou** [comment]
Pretty sure it was for the ability to have off threaded ness for account management. Since for example, you can have a server account that is being altered by other servers (bungee networking) to get changes.

**Comment by ST-DDT** [comment]
Just to be sure how is this supposed to work, is the given code correct / the recommended way of doing it?

````java
EconomyService economyService = magic();
Account account = economyService.getOrCreateAccount("playerA").get();
Currency currency = economyService.getDefaultCurrency();
CauseStackManager csm = Sponge.getCauseStackManager();
try (StackFrame sf = csm.pushCauseFrame()) {
	csm.pushCause(this);
	economyService.getOrCreateAccount("sdf").get().deposit(currency, BigDecimal.ONE, csm.getCurrentCause());
}
````
This would only work on the main Thread.
For the async usage we would probably have to use this piece of code:

````java
economyService.getOrCreateAccount("sdf").get().deposit(currency, BigDecimal.ONE,
		Cause.of(EventContext.of(ImmutableMap.of(EventContextKeys.PLUGIN, this)), this));
````
