### ISSUE TITLE
Generate separate artifact for annotations processors

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#1840]
In Gradle 5.0, [any annotations processors on the compile classpath will be ignored](https://docs.gradle.org/4.7/userguide/java_plugin.html#sec:java_compile_avoidance). To ensure that plugins can choose to upgrade to Gradle 5.0, we should generate a separate jar containing our annotation processors.

For plugins using SpongeGradle, we can make this change completely transparent by adding the proper dependency in the Sponge gradle plugin.

**Comment by ImMorpheus** [comment]
API 8 uses gradle 5.6.4.

The ap (https://github.com/SpongePowered/SpongeAPI/tree/api-8/src/ap) seems to be separate from the api module so this shouldn't apply anymore.
