### ISSUE TITLE
Rename DataManipulator 'from' to 'fill' or 'fillFrom'

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeAPI#1842]
Data classes contains method named `from(...)`, maybe rename to `fill(...)` or `fillFrom(...)`?

**Comment by XakepSDK** [comment]
@gabizou

**Comment by ryantheleach** [comment]
I don't see significant difference between the names. Maybe better Java Docs?

I'm all for breaking the API necessarily, but at some point you need to draw the line.

**Comment by XakepSDK** [comment]
In my opinion, `from` will create new instance of something from DataView, but actually it just fills object with DataView.

**Comment by Cybermaxke** [comment]
I agree upon the fact that the `from` can be misleading. We can also keep the `from` method around and deprecate it, and we remove it in a later API version.

**Comment by Cybermaxke** [comment]
IMO just `fill` is also a bit confusing, what are you going to fill? This or the parameter manipulator? So I suggest renaming `from` and `fill` to `fillFrom` or `copyFrom` (to reflect `CompositeValueStore` methods).

@gabizou Thoughts?

**Comment by ImMorpheus** [comment]
Fixed by the Data API v4 PRs
