### ISSUE TITLE
Improve PlayerJoinData to support extra data.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1845]
History:

https://github.com/SpongePowered/SpongeCommon/issues/1282
https://github.com/SpongePowered/SpongeCommon/pull/1710

PlayerJoinData is inconsistent and impossible to fix correctly without API breaks due to badly named & semantics in API7.

It is planned, that the following data is going to be added to PlayerJoinData.

hasplayedbefore, firstjoined, lastjoined, lastplayed

This will clear up the ambiguity in the current data, as well as giving plugin developers the information they need.

**Comment by ImMorpheus** [comment]
PR merged
