### ISSUE TITLE
More inventory peek/poll/set actions.

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeAPI#1849]
In lantern I introduced new peek actions for inventories, this was added for the following actions:
* `offer` -> `peekOffer`
* `set` -> `peekSet`
* `poll` -> `peekPoll`

Using these actions would give a possible successful result that isn't applied to the inventory, but gives all the `SlotTransaction`s that would occurr if it was successful, and being able to apply these transactions afterwards.
This allows you to do operate on the inventory and test if the changes are successful before actual applying them. E.g. I want to offer a itemstack of 64 apples to the inventory,  but this should only happen if there is space enough for 64 apples, using `offer` would already add apples for the available space (e.g. 23 apples). Using `peekOffer` you would be able to test if it's possible, and then apply the changes if you are happy about them.

Code in lantern:
https://github.com/LanternPowered/LanternServer/blob/master/src/main/java/org/lanternpowered/server/inventory/IInventory.java#L114

**Comment by Cybermaxke** [comment]
@Faithcaio thoughts?

**Comment by parlough** [comment]
I would love something like this as it would allow for removing a lot of duplicated and bug-ridden code from plugins. I first brought it up here - https://github.com/SpongePowered/SpongeAPI/issues/1498

**Comment by Faithcaio** [comment]
Also stuff thats already on my list :)
I'd name it smth. like `tryOffer`
The TransactionResult will get all SlotTransactions that occured so that you can do stuff with it similar to the inv-events.

**Comment by ryantheleach** [comment]
tryOffer sounds like it's going to throw.

**Comment by Faithcaio** [comment]
Maybe just keeping the methods on Inventory like they are and instead make InventoryTransactionResults more usefull.
```
InventoryTransactionResult result1 = inventory.offer(notTooMuch)
result1.getSlotTransactions(); // Similar to Events

InventoryTransactionResult result2 = inventory.offer(tooMuch);
InventoryTransactionResult resultSum = result1.and(result2);
if (!resultSum.isSuccess()) resultSum.cancel() // Undo all SlotTransactions from both offer
```

**Comment by Faithcaio** [comment]
see https://github.com/SpongePowered/SpongeAPI/pull/1848 for improved InventoryTransactionResult

**Comment by Cybermaxke** [comment]
@Faithcaio This doesn't cover `peekPoll` operations, `poll` doesn't return a `InventoryTransactionResult` so you cannot restore it. And offering the stack back may result in putting the stack to different slots.

**Comment by Faithcaio** [comment]
I don't quite get what you want `peekPoll` to do.
Just do peek before poll if you want to know what you get.

If you want offer to not affect all slots of an inventory query for the slots that should be affected before.
