### ISSUE TITLE
GenericArguments.userOrSource never selects command source

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#1851]
Currently, `GenericArguments.userOrSource` always requires a username to be passed as an argument. Omitting the argument will never cause the running player to be chosen as a source.

Test plugin demonstrating the bug:

```java
package pw.aaron1011.bug;

import org.spongepowered.api.Sponge;
import org.spongepowered.api.command.CommandResult;
import org.spongepowered.api.command.CommandSource;
import org.spongepowered.api.command.args.GenericArguments;
import org.spongepowered.api.command.spec.CommandSpec;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.game.state.GameInitializationEvent;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.text.Text;

@Plugin(id = "user-or-source-bug")
public class UserOrSourceBug {

    @Listener
    public void onInit(GameInitializationEvent event) {
        Sponge.getCommandManager().register(this, CommandSpec.builder()
                .arguments(GenericArguments.userOrSource(Text.of("user")))
                .executor(((src, args) -> {
                    src.sendMessage(Text.of(args.getOne("user").get()));
                    return CommandResult.success();
                })).build(),
                "user-test");
    }

}
```

Running `/user-test` as a player produces the following output:

```
Not enough arguments!
Usage: /user-test <user>
```

**Comment by ST-DDT** [comment]
AFAICT the [`UserCommandElement#parseValue(CommandSource, CommandArgs)`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L1139) is missing the `args.hasNext() && this.returnSource` check that is present in [`PlayerCommandElement#parseValue(CommandSource, CommandArgs)`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L1200)

**Comment by dualspiral** [comment]
[That is being taken care of here](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L1143).

It's actually missing `!hasNext()` in the [if statement in the first line of `parse`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L1168). It's only failing when the element is at the end of the argument string - [there is an `args.next()` call here](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L1170) causing this error.

I'm about to push a fix, but I've also taken the time to implement what you saw too to make the error message consistent with `playerOrSource`.
