### ISSUE TITLE
Marker for classes that should not be referenced directly

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeAPI#1853]
Based on https://github.com/SpongePowered/SpongeCommon/issues/1956.

Currently the information about stale/leaked references is present only in the [Docs: Storing References](https://docs.spongepowered.org/stable/en/plugin/practices/bad.html#storing-references). It would be nice if we could add some kind of marker that the user will see during development time that references should not be stored.

### Suggestions

1. **Annotation**
  Has to be set only on the root/base class and can be inherited and will be visible in javadocs.
2. **JavaDocs**
  Add a clause to every affected class and all of its subclasses that references should not be stored.
3. **(Marker-) Interface**
  Add a marker interface that shows. Do not cache these references.  Unfortunately you won't see the marker interface unless you explicitly search for it. (Maybe with a method: `isValid()`)

What do you think? Which would work best with tooling/IDE-support?

**Comment by XakepSDK** [comment]
Annotation + support for that annotation in javac and/or support in idea plugin.
https://github.com/minecraft-dev/MinecraftDev

**Comment by ryantheleach** [comment]
Sounds good to me, maybe start this by creating a summary of what classes should be annotated, and people can bikeshed about the specifics later?

**Comment by ImMorpheus** [comment]
PR merged
