### ISSUE TITLE
TextTemplate needs simpler serialization structure.

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1856]
https://docs.spongepowered.org/stable/en/plugin/text/templates.html

If you dump current text template into a json string it outputs an unreadable mess, which is not suitable to use in any plugin configuration where you need to have parametrized text. 

Its simply too overcomplicated object structure, if you are having more parameters/different text styles in one TextTemplate the output string is almost unreadable. 

I would like to see much simpler approach.
eg.:

    TextTemplate.fromPlainString("Welcome &4${player}").apply(ImmutableMap.of("player", player.getName)).toText()

If the text template will be build from a single line ,instead of some json object structure, with legacy color codes and parameters it will become more suitable to use in eg.: plugin configuration files.

**Comment by ImMorpheus** [comment]
As of API 8 we are now using [Adventure](https://github.com/KyoriPowered/adventure). 

This means the old Text api is gone and all the related issues (especially those involving breaking changes) are no longer relevant, therefore I'm closing this.
