### ISSUE TITLE
Optional<ItemStack> to empty itemstack(ItemStack.empty())

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeAPI#1857]
ArmorEquipable interface has many methods to get/set items in armor slots and hand. These methods return optionals, but there is empty itemstack. Maybe change these methods to return just ItemStack, because api has empty itemstack?
Also, replace every Optional<ItemStack> in api to just ItemStack.

**Comment by gabizou** [comment]
Pretty sure #1848 is going to resolve a lot of that, right @Faithcaio?

Also, we can't blindly replace every `Optional<ItemStack>` with an `ItemStack.empty()` guarantee as the optional might mean something different now (like an inventory not having a slot).

**Comment by Faithcaio** [comment]
For API8 empty Optional means that the Slot does not exist. So replacing all Optional wont work.
E.g. `inv.peek(slotIndex)` is the same as `inv.getSlot(slotIndex).map(Slot::peek)`

So in theory I could remove the Optionals on ArmorEquipable. 
Will have to check if all implementing it actually have all those Slots.

Also `ArmorEquipable` should maybe be renamed. Its not only armor but also main and offhand

**Comment by XakepSDK** [comment]
Good point. Some mod can modify hand types or remove/add some slots in ArmorEquipable. I did not think about that.

**Comment by XakepSDK** [comment]
So, if you want to talk about `ArmorEquipable` renaming here, you can just reopen this issue.

**Comment by Faithcaio** [comment]
I'm actually fine with removing Optional on the ArmorEquipable.
Only stuff that provides all slots implements it.

**Comment by XakepSDK** [comment]
And what if some mod removes some armor slot?

**Comment by Faithcaio** [comment]
Then we have a problem anyways. But probably the mod would hide the slot instead.

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeCommon/pull/1946
