### ISSUE TITLE
GameProfileManager#getAll methods are nearly useless

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#1858]
`GameProfileManager#getAllById` and `GameProfileManager#getAllByName` return a collection of `GameProfiles`, despite the fact that not all UUIDs/names in the input may have associated `GameProfiles`. This makes it impossible to properly use the result of the method if any of the lookups fail.

These methods should be brought into line with their corresponding methods in `GameProfileCache` - they should return a `Map<UUID, Optional<GameProfile>>` or `Map<String, Optional<GameProfile>>`.

**Comment by ImMorpheus** [comment]
PR merged
