### ISSUE TITLE
BreedEntityEvent is entirely wrong

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeAPI#1868]
(This issue is being made to basically remind me to fix this for API 8).

Basically, the entire event composition is wrong. It assumes breeding starts at Player interaction which is correct from a Vanilla perspective but falls apart with Mods. While the Cause can have some interaction-specific information, such as item used, it cannot be enforced.

**Comment by ryantheleach** [comment]
Could this incorporate https://github.com/SpongePowered/SpongeAPI/issues/1382 Zidane?

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/commit/d5c16be2162fe6c43c6d9993e1d8a08c2ad1c7e4
