### ISSUE TITLE
org.spongepowered.api.item.inventory.Slot.getStackSize reporting incorrect size

### ISSUE THREAD

**Issue by virustotalop** [SpongePowered/SpongeAPI#1872]
The getStackSize method in Slot is reporting the wrong stack size. According to the documentation when a slot is empty the method should return -1, however when running a plugin on spongevanilla-1.12.2-7.1.0-BETA-93 the stack size that is being reported is 0. This occurred when referencing a player's main inventory and iterating through each slot. I would have opened a pull request but I am not sure what is the intended behavior. Thank you for your time and I hope this issue gets resolved. Sorry if I should have reported this on the SpongeVanilla repository, I wasn't sure. Reference code below.

```java
public static int getFreeInventorySlots(Player player)
{
     int emptySlots = 0;
     Iterable<Slot> slots = player.getInventory().query(QueryOperationTypes.INVENTORY_TYPE.of(MainPlayerInventory.class)).slots();
     for(Slot slot : slots)
     {
          if(slot.getStackSize() <= 0)
               emptySlots++;
     }
		
     return emptySlots;
}

**Comment by gabizou** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @virustotalop! I've moved your issue to [SpongePowered/SpongeCommon#2016](https://github.com/SpongePowered/SpongeCommon/issues/2016).
