### ISSUE TITLE
Make ChangeServiceProviderEvent generic

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeAPI#1873]
Make `ChangeServiceProviderEvent` generic event, so we can directly listen for specific provider change.

**Comment by ryantheleach** [comment]
I think this would be a well accepted change. However I have a few questions thinking about how this would work.

Would the existence of this event imply to plugins that they need to act when a service is swapped out?

Or should it be the services responsibility to correctly hand over / consume information from the service it replaced?

Whilst I welcome this event to catch edge cases, I think some deeper choices about service lifecycles needs to be thought about and proposed if it hasn't already.

**Comment by dualspiral** [comment]
This won't happen for API 7 for obvious reasons. API 8 will actually toss this event. Thus, I am closing this issue.
