### ISSUE TITLE
Cannot unregister Inventory listeners

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#1874]
Currently, Sponge allows registering inventory listeners with `Inventory.Builder#addListener`. However, there is no way to un-register these listeners, since the internal class `CustomInventoryListener` is actually registered on the event bus. Over time, this will lead to a large number of useless event listeners firing on every single `InteractInventoryEvent`

**Comment by gabizou** [comment]
Why is this an API issue? Wouldn't it make sense to have this in implementation handling the actual automatic unregistration once the custom inventory is closed or "finished"?

IT does make sense though that likewise the Key listeners that are created aren't being unregistered either or "allowed" for unregistration. 

What about the possibility of passing an object to find out if it's a listener so to speak so it can be unregistered? Or adding an additional method to keep the listener registered past the inventory code.

**Comment by Faithcaio** [comment]
You can open a custom inventory multiple times.

**Comment by Faithcaio** [comment]
`EventManager#unregisterListeners` now also unregisters listeners added for a custom inventory

**Comment by Cybermaxke** [comment]
@Faithcaio These inventory listeners should be cleaned up automatically when the inventories are no longer in use. This could potentionally cause memory leaks if listeners are added and never cleaned up. In that case will the inventories be kept into memory.

When creating a inventory with listeners I don't expect that they have to be cleaned up afterwards.

**Comment by Cybermaxke** [comment]
Maybe a Cache with a removalListener is a good solution, like I did in lantern:
https://github.com/LanternPowered/LanternServer/blob/master/src/main/java/org/lanternpowered/server/inventory/LanternInventoryBuilder.java#L87

**Comment by Faithcaio** [comment]
How would I detect that they are no longer used?
They would still be referenced in the listener so I don't think weakKeys would work.

**Comment by Cybermaxke** [comment]
@Faithcaio Modify the `inventory` field to be a `WeakReference`. I didn't think about that before.

**Comment by Cybermaxke** [comment]
@Faithcaio I fixed the impl in lantern: https://github.com/LanternPowered/LanternServer/blob/master/src/main/java/org/lanternpowered/server/inventory/LanternInventoryBuilder.java#L64
In `InventoryListeners` keeping a weak reference to the inventory, if the inventory object gets unloaded, then the next time the inventory listeners are handled, it will be unregistered.

**Comment by XakepSDK** [comment]
UP for Cyber solution.
