### ISSUE TITLE
Inconsistent behavior in Inventory API?

### ISSUE THREAD

**Issue by wysohn** [SpongePowered/SpongeAPI#1875]
Hi, I'm working on GUI menu ish thingy

I registered Listener to get InteractInventoryEvent.Open event.

And I want to manipulate the custom inventory via this event.

For example, I first create new custom inventory with Inventory.builder(), and I open it with player.openInventory(). I tested it, and it's working without a problem. I checked that getTargetInventory() correctly return the custom inventory I created (tested by invoking offer() method on the inventory. It added item on the inventory view which current player is looking at).

The problem was that if I query the GridInventory like below,

    inventory.query(QueryOperationTypes.INVENTORY_TYPE.of(GridInventory.class))

This would return EmptyInventory.

Yet, I randomly found that **inventory.first()** somehow return GridInventory correctly.

So my question is, aren't they have to be consistent in returning same 'GridInventory' instance?

Atm, I can go around with ((GridInventory) inventory.first()). blah blah, but this seems not ideal to me based on what I read about the Inventory API of Sponge.

Or please kindly guide me if I understood something incorrectly.

I barely can find detailed documentation about the Inventory API :(

Version:
![image](https://user-images.githubusercontent.com/8789836/43184697-53fed1be-8f9e-11e8-9695-5c5c832a955f.png)

**Comment by Faithcaio** [comment]
Please provide some example code so I can reproduce it easier.

**Comment by Faithcaio** [comment]
I cant reproduce the query returning an empty Inventory.

> So my question is, aren't they have to be consistent in returning same 'GridInventory' instance?

Because the GridInventory only exists if you query for it.

I'll try to explain a bit how this works:

When you create your inventory:
`Inventory inv = Inventory.builder().build(plugin);`
Based on an `InventoryArchetype` we create a custom inventory with a certain internal structure.
The default `CHEST` InventoryArchetype consists 27 slots.
In addition we provide access to Rows, Columns and the 9x3 Grid.
This custom inventory itself is NOT a grid. It provides one.

When you now query `inv` for a `GridInventory` we check the internal structure and provide the Inventory for that grid.
`inv.query(QueryOperationTypes.INVENTORY_TYPE.of(GridInventory.class)) instanceof GridInventory` is true

But when you a player opens that inventory you get a Container back.
The Container now has more than a single grid!

![](https://i.imgur.com/cO6sybL.png)
There are now 3 Grids. 
The diamonds (9x3), the iron ingots (9x3) and all ingots (9x4).
(4 grids in API7 because `MainPlayerInventory` itself is also a Grid - so the 9x4 one is in there twice)

So you get back an Inventory containing all those grids as sub-inventories. (calling `first()` on that gives you the first grid inventory that was found)

`inv.first()` gets you the grid inventory because it is the first (and only) child inventory of the custom inventory.
If you did `inv.first().first()` you would get the first row as it is the first child inventory in the grid.

**Comment by wysohn** [comment]
Hi, thank you for the detailed documentation! it helped me a lot. Specially, the part where inv.query would create a whole new Inventory instance with its items inside, not it already contains the child instance in it.

However, I conducted an experiment and faced a weird result.

---

Environment:

![image](https://user-images.githubusercontent.com/8789836/43231864-05c72aca-9023-11e8-8afd-ce33aa2b9561.png)

Code used in class with `@Plugin` annotation :


    @Listener
    public void onInitialize(GameAboutToStartServerEvent e) {
        Sponge.getCommandManager().register(this, new CommandCallable() {

            @Override
            public CommandResult process(CommandSource src, String args) throws CommandException {
                int num = Integer.parseInt(args);

                switch(num) {
                case 1:
                    Carrier dummy = new DummyCarrier();
                    Inventory inv = Inventory.builder()
                    .of(InventoryArchetypes.CHEST)
                    .withCarrier(dummy)
                    .property(InventoryDimension.PROPERTY_NAME, InventoryDimension.of(9, 6))
                    .property(InventoryTitle.PROPERTY_NAME, InventoryTitle.of(Text.of("test inv")))
                    .build(Test.this);

                    ((Player) src).openInventory(inv);

                    src.sendMessage(Text.of("InventoryInstance: "+inv.toString()));
                    break;
                }

                return CommandResult.success();
            }

            @Override
            public List<String> getSuggestions(CommandSource source, String arguments, Location<World> targetPosition)
                    throws CommandException {
                return new ArrayList<>();
            }

            @Override
            public boolean testPermission(CommandSource source) {
                return source.hasPermission("test");
            }

            @Override
            public Optional<Text> getShortDescription(CommandSource source) {
                return Optional.of(Text.of("test"));
            }

            @Override
            public Optional<Text> getHelp(CommandSource source) {
                return Optional.of(Text.of("test"));
            }

            @Override
            public Text getUsage(CommandSource source) {
                return Text.of("test");
            }

        }, "test", "t");
    }

    @Listener
    public void onOpen(InteractInventoryEvent.Open e, @First Player player) {
        Inventory inv = e.getTargetInventory();
        inv.offer(ItemStack.of(ItemTypes.STONE, 5));

        GridInventory grid = inv.query(QueryOperationTypes.INVENTORY_TYPE.of(GridInventory.class));
        Inventory first = inv.first();

        player.sendMessage(Text.of("Inventory Instance(Open) inv: "+inv.toString()));
        player.sendMessage(Text.of("Inventory Instance(Open) grid: "+grid));
        player.sendMessage(Text.of("Inventory Instance(Open) first: "+first.toString()));
    }


---

Result:

![image](https://user-images.githubusercontent.com/8789836/43231927-5935aeca-9023-11e8-8abd-f855a9c3b7c5.png)

![image](https://user-images.githubusercontent.com/8789836/43231964-74b33370-9023-11e8-999d-ed3fd80e93dd.png)

![image](https://user-images.githubusercontent.com/8789836/43231940-5e90560e-9023-11e8-88d2-b7cfe1f5aa2e.png)

---

As you can see, query(QueryOperationTypes.INVENTORY_TYPE.of(GridInventory.class)) on target inventory somehow raise the exception. I'm not sure why it's not an empty inventory this time, but it's happening.

Then I changed the source code a little:

    @Listener
    public void onOpen(InteractInventoryEvent.Open e, @First Player player) {
        Inventory inv = e.getTargetInventory();
        inv.offer(ItemStack.of(ItemTypes.STONE, 5));
        player.sendMessage(Text.of("Inventory Instance(Open) inv: "+inv.toString()));

        Inventory first = inv.first();
        player.sendMessage(Text.of("Inventory Instance(Open) first: "+first.toString()));

        GridInventory grid = inv.query(QueryOperationTypes.INVENTORY_TYPE.of(GridInventory.class));
        player.sendMessage(Text.of("Inventory Instance(Open) grid: "+grid));

    }

The result:

![image](https://user-images.githubusercontent.com/8789836/43232081-1290616c-9024-11e8-94ea-54a33dd415c0.png)

Still the same exception will be raised, yet I could find that first() method return some useful inventory other than empty inventory

So at this point, I'm really confused. My result would be a little different in the production code, but it's not ideal to change the code in the production code when the simple test code seems to be not working.

Thank you!

**Comment by Faithcaio** [comment]
You queried the open Container, the result contains multiple Grids but is itself not a grid.
```
Inventory grids = e.getTargetInventory().query(QueryOperationTypes.INVENTORY_TYPE.of(GridInventory.class));
for (Inventory grid : grids) { // Iterates through all sub-inventories
   // all grid should be GridInventory
}
```

VanillaAdapter is another pseudo inventory which wraps around each inventory viewed in the Container.
One for the top and one for the bottom inventory.
This is because a Container does not always view the entire inventory. 
Your armour and offhand slots are not available when viewing a chest.

**Comment by wysohn** [comment]
Wow that makes things very clear now

It was confusing as the return type seemed to be a Container, yet the method name was getTargetInventory()

Anyway, thank you!

**Comment by wysohn** [comment]
@Faithcaio 

Hi, Thank you for the reply last time

Do you mind help me out one more time?

So I was able to get the gridinventory I want

but it seems I can't set item in the slot that is already occupied

for the empty slot, I can set ItemStack without problem, but if I try to set it on the slot that is not empty, it doesn't work.

getSlot() on the non-empty slot would return Optional.empty, and setSlot(x, y, itemstack) returns FAILURE. 

Did I do something wrong?

Other empty slots are just working fine

**Comment by Faithcaio** [comment]
`getSlot` returns the slot. If its Optional.empty the slot does not exist.
Maybe you reversed x and y?

**Comment by wysohn** [comment]
You are right :/

I reversed x and y

I was thinking it as a matrix, but the method accepts x first

Thank you for the help!
