### ISSUE TITLE
MessageEvent does not implement Cancellable, but allows to cancel event

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeAPI#1877]
MessageEvent has 2 methods: `isMessageCancelled` and `setMessageCancelled`, but doesn't implement cancellable interface!
Should be fixed in 7.1 or 8.0.
Annotation `IsCancelled` will not work with this event, because event strictly must implement `Cancellable` interface.

**Comment by Cybermaxke** [comment]
MessageEvent is most of the time extended by a other event, this getter/setter is to only cancel the message, and not the whole event.
For example a advancement achieve event implements this one, cancelling the achieve event will cancel that. When a advancement is achieved, it will also display a message to that player, cancelling the message will only prevent that message event. Cancelling the whole event will also cancel the message.

**Comment by XakepSDK** [comment]
Understood. Thanks for explanation.
