### ISSUE TITLE
Simple question about DestructEntityEvent.Death

### ISSUE THREAD

**Issue by wysohn** [SpongePowered/SpongeAPI#1879]
https://github.com/SpongePowered/SpongeAPI/blob/dbe3cb0af588137bfd4fe2d6582ad1af8a87d234/src/main/java/org/spongepowered/api/event/entity/DestructEntityEvent.java#L65

So I can clearly see that the keepInventory method exists in the DestructEntityEvent.Death, but if I look at the javadoc, https://jd.spongepowered.org/7.0.0/org/spongepowered/api/event/entity/DestructEntityEvent.Death.html

I can't find such method.

Is it planned to be deleted?

If it is so, what will be the new method? I feel like EventContext might be a thing

**Comment by SimonFlash** [comment]
This method was added after 7.0.0 and is thus part of the 7.1.0 API.

https://jd.spongepowered.org/7.1.0-SNAPSHOT/org/spongepowered/api/event/entity/DestructEntityEvent.Death.html

GitHub issues aren't really the place to be asking questions like this. Instead, I would recommend sticking to the forums or joining the [Sponge Discord](https://discord.gg/PtaGRAs) (or irc, if that's your thing) for general support.
