### ISSUE TITLE
API8 Inventory: Adding offer(SlotIndex, ItemStack) to Inventory Interfaces.

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeAPI#1880]
New inverface has `offer(ItemStack)` but there is no `offer(SlotIndex, ItemStack)`.
@Faithcaio

**Comment by Faithcaio** [comment]
just get your Slot and offer to it

**Comment by mosemister** [comment]
While I agree on the fact you should get the slot and then set the itemstack to that slot. I would also like to see something like to see something like this added to the inventory api, even if it does just get the slot and set the itemstack to the slot in SpongeCommon or on the Inventories interface.

I personally think it would help new users (developer users) grasp the inventory api

**Comment by XakepSDK** [comment]
Current bleeding interface has `poll`, `peek`, `set` with SlotIndex, why not add `offer`?

**Comment by Cybermaxke** [comment]
@Faithcaio I feel like the `Inventory`is getting a bit bloated with all the `SlotIndex` methods, especially because they are also visible in `Slot`, but are useless for slots.

**Comment by Faithcaio** [comment]
True but I'd say its better than not having indexed access on all inventories.
It was near to impossible in API7 to get a single OrderedInventory consistently.

**Comment by XakepSDK** [comment]
Haha, then just redesign everything back. Current inventories seems be ok for me, but i have questions with events. I'll ask you bit later.

**Comment by Faithcaio** [comment]
see https://github.com/SpongePowered/SpongeAPI/issues/1847
