### ISSUE TITLE
Create new Extent subinterface to represent unloaded Worlds

### ISSUE THREAD

**Issue by benjaminmordaunt** [SpongePowered/SpongeAPI#1884]
When adding the `setLocation` and `getLocation` methods to the User interface, to allow offline players' locations to be changed, the implementation needed to be modified to accept a Vector3d and world UUID. I believe an UnloadedWorld interface would be more appropriate here, to represent a world on disk which is not currently loaded. Alternatively, the World interface could be adapted to cover both loaded and unloaded worlds.

**Comment by Zidane** [comment]
WorldProperties already exists.

**Comment by ryantheleach** [comment]
@subylan You may find this method on User helpful.

https://github.com/SpongePowered/SpongeAPI/blob/dbe3cb0af588137bfd4fe2d6582ad1af8a87d234/src/main/java/org/spongepowered/api/entity/living/player/User.java#L107

**Comment by benjaminmordaunt** [comment]
@ryantheleach Huh? This is the method I'm talking about in the issue, which I believe could be cleaner with an interface overhaul. But considering the issue is closed, never mind now.

**Comment by Zidane** [comment]
What interface overhaul? WorldProperties = world data on disk.

**Comment by benjaminmordaunt** [comment]
I understand that, but wouldn't it make sense if there were some container which represents a location in an unloaded world/chunk/extent? At the moment, passing `Vector3d` and `UUID` doesn't seem very clean. A new `Extent` subinterface or otherwise? We can't exactly do `Location<WorldProperties>` 😋
