### ISSUE TITLE
Add ways to check whether player is shielding or eating something

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeAPI#1885]
I couldn't find anything related to checking if player is currently shielding or eating something. It might helpful in the process of some sort of anti cheats or any other plugins creation that needs to for example calculate something differently if player is currently slowed down by either shielding or eating.

Methods (isShielding/isEating), Keys (IS_SHIELDING, IS_EATING) or any other viable ways to check that would be appreciated.

**Comment by ryantheleach** [comment]
You are muddying a few different issues.

Do you 

1. want a way to see if the current speed is different.

or 

2. want a way to see if the player is eating or shielding for some other purpose? (Plugins? Spells? Damage?)

**Comment by ghost** [comment]
I believe shielding and eating do change or at least should change `Keys.WALKING_SPEED` value.

As an example, I want to detect whether player is currently shielding/eating to properly block suspicious/impossible movement (like sprinting with shielding and so on). Someone from the staff showed me a workaround - listen to `UseItemStackEvent` and then do something if player is actually shielding/eating. This workaround have 2 issues though. It's over complicated for the thing that should be relatively easy to check and there are a lot of sub events and cases to consider so one mistake from me and the needed functionality will be gone.

**Comment by parlough** [comment]
The PR above that I created will handle this in a more generic fashion where you can check what the active item is, so that could be a shield or food or whatever. `player.get(Keys.ACTIVE_ITEM).orElse(ItemStackSnapshot.NONE).getType().equals(ItemTypes.SHIELD)` or something along those lines.

**Comment by ImMorpheus** [comment]
PR merged
