### ISSUE TITLE
Commands with TypeReaders and Preconditions

### ISSUE THREAD

**Issue by TheBrambleShark** [SpongePowered/SpongeAPI#1887]
This is a suggestion which will include its own PR. I'll edit this post once the PR is posted for convenience.

It should also be noted that, should this be accepted, this will be a **breaking change**. The recommendation is based on the system provided by the [Discord.NET API by RogueException](https://github.com/RogueException/Discord.Net), licensed under the MIT license.

Currently within the Sponge API, the command system is a little cumbersome and can be a bit of a learning curve for new developers, especially those coming over from Spigot. Fortunately, with a bit of time and effort, it's not that difficult to pick up.

One thing I've always disliked about the Sponge API is that, like our Spigot/Bukkit predecessor, argument parsing is left up to the plugin developer. This new system will not change that, though parsing for standard items will be built in much like we have now.

Parsing will be handled by a set of TypeReaders. These TypeReaders will perform, in advance, parsing of the command and casting into their appropriate types based on what the command calls for. Matching to a command will be done by its `Group` and `Command` annotations where Groups provide organization for your command structure and Commands represent Command Handlers.

TypeReaders for primitives and commonly used objects such as `Player`s and `Enum`s will be provided by this PR. However, custom TypeReaders can be created by the plugin developer for parsing additional items, such as region names or channels. This is done by building a class which inherits from `TypeReader`. These TypeReaders will return a `TypeReaderResult` containing the parsed value or a reason why parsing failed. This error message can be optionally returned to the player who issued the command.

Further flexibility and ease is given by the use of precondition attributes. These are defined as annotations and evaluate conditions before execution of the method itself. As an example, the `@Permission("node")` attribute evaluates whether the CommandSender has permission to run the command. Should this precondition fail, the command is not executed. This is a one-line approach to ensuring consistency throughout the command infrastructure.

These preconditions may also be placed on the command attributes to provide additional requirements or to tell the system how to handle incoming commands. For instance, the `@Remainder` attribute will take any and all command arguments past that point and combine them into a `String` or `String[]`, depending on the application required by the plugin developer. This is convenient for things like collecting messages from the player, as demonstrated in the example below. This system will also combine quoted items, so input such as `/nickname "Pizza Delivery Boy"` will take the entire quoted string with spaces and treat it as a single object.

Below, I have included an example of a command class. This does not demonstrate the full capabilities of the system, but does allow for a high-level overview of *some* of the possibilities. Overall, this is designed to be flexible, extensible, and user-friendly with a high focus on removing duplicate code.

The command below would be accessible through `/plugin mod ban Foxtrek64 1d griefing`. The `moderator` alias allows `mod` to be replaced with `moderator`. Unless otherwise specified, these annotations are case-insensitive.
```java
@Group("mod")
@Alias("moderator")
public class ModerationCommands implements ModuleBase
{
    ApplicationConfiguration applicationConfiguration;

    // Provide an overload for /plugin ,pd ban player
    @Command("ban")
    @Alias("permaban")
    @Permission("plugin.moderation.ban")
    public void BanUser(Player victim)
    {
        BanUser(player, Duration.Infinite, Context.User.Name + " banned " + player.Name);
    }

    // plugin mod ban user duration reason
    @Command("ban")
    @Alias("permaban")
    @Permission("plugin.moderation.ban")
    public void BanUser(Player victim, Duration duration, @Remainder String reason)
    {
        // Just dummy code to get the current config
        applicationConfiguration = Plugin.GetApplicationConfiguration();

        // Context is provided by the ModuleBase
        if (Context.User.Guid == victim.Guid)
        {
            // ReplyAsync lives in ModuleBase and provides a fast way to send a message to the command sender
            ReplyAsync("You cannot ban yourself.");
            return;
        }

        // No need to check if the victim is the console -
        // We already performed a TypeCast to Player
        // if (victim is Console)

        // dummy code to ban the user
        victim.Ban(duration, reason);
    }
}
```

If there is anything here that seems wrong (besides my placement of brackets - I'm a C# developer), please do let me know and I'll fix the example code if possible. A lot of this stuff, while easy in C#, is not so friendly in Java, so I'm only about 90% sure I'll be able to copy this over with any degree of success. The original code requires anonymous types and other tools which may not exist in Java, though I'll do my best to come up with a working system.

If you'd like to see the source for the C# version of this command system, take a look at the link provided at the top of the page. I'll be replicating that code as closely as possible.

**Comment by jamierocks** [comment]
Judging from your source example, what your after is an annotation-based command system.

One very similar to your example would be [ACF](https://github.com/aikar/commands), and there's an [existing pr here](https://github.com/SpongePowered/SpongeAPI/pull/1201) for one.

**Comment by TheBrambleShark** [comment]
I'll go ahead and close this issue then. Seems we already have something in the works.
