### ISSUE TITLE
TextTemplate Redesign

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1891]
# WIP - Work in Progress

I'm looking for feedback from plugin and Sponge devs to come up with the list of goals and usecases to effectively design this, and someone to champion this after / with the Text moving to implementation.

# Why Redesign?

Text Templates have numerous reported issues:

https://github.com/SpongePowered/SpongeAPI/issues/1856 Complex Serialization Structure, making them a pain for config / user editing.

https://github.com/SpongePowered/SpongeAPI/issues/1855 Having surprising behavior regarding colors.

https://github.com/SpongePowered/SpongeAPI/issues/1792 Their builders acting differently to TextBuilder & Text.of "magic" method.

https://github.com/SpongePowered/SpongeAPI/issues/1493 General serialization problems

https://github.com/SpongePowered/SpongeAPI/issues/1452 (OCD) Poor naming regarding arguments vs parameters.

https://github.com/SpongePowered/SpongeAPI/issues/1462 and Confusion surrounding 'meta' formatting options for Actions.

They are poorly understood, poorly used, and as such, people avoid them for their own solutions constantly, even implementing "search and replace" algorithms manually for Text's.

# Goals of a new TextTemplate:

1. Serialize very similarly to Texts, with a **standard** way of marking arguments, common to all plugins.
2. Leave evaluation of placeholders as LATE as possible, and allow plugins to determine the context. (Per player formatting? per receiver formatting?)
3. Have serializers that closely match the current Text Serializers.
4. Maybe incorporating / Promoting a 'global' arg registration system, akin to, https://ore.spongepowered.org/rojo8399/PlaceholderAPI
5. Use a similar parent interface as server side translations, so that a given TextTemplate can be 'resolved' for a given receivers Locale? 
6. Maintaining performance, by generating as much Text ahead of time as possible, TextTemplates should be reusable.

# Usecases.

1. Plugins specifying configurable text in configs, that also have tokens that need replacing by dynamic values at runtime.

2. Chat Formatting plugins would use TextTemplates to replace known variables, from other plugins.

# What Next?

If you disagree, or have further Usecases / Goals please add them.

If you have a strawman API to prototype with / play with, please make a pull request, EXPLAINING it's a prototype, and link it to this issue.

**Comment by XakepSDK** [comment]
I like how formatting code serializer works. Really simple and short output. Maybe somehow fit that serializer for text templates?

**Comment by ST-DDT** [comment]
It would be nice if the arguments itself can be context aware. Such as calculating a players groupname without providing it explicitly. This context needs to be aware of both the reciever and the values being send.

Example:

````java
Template.of("Hey {{reciever | sponge:playername}} you got an invitation from {{player | myperms:groupname brackets=true}} {{player | sponge:playername}} on {{date | sponge:date}} cause {{reason}}! ").send(reciever, Map.of(player, date, reason));
````
Everything after the pipe would be a globally registred transformation function which is reciever aware and can take static parameters.

The above example would then yield in something like this:
````txt
EN: Hey SuperSt4r you got an invitation from [OP] Dest1ny on 12/31/2018 cause End of World.
DE: Hey Superst4r du hast eine Einladung von [OP] Destiny für den 31.12.2018 bekommen! Grund: End of World
````

(Creating the template from an string directly should maybe be forbidden to encourage users to use translation files. Also this is not a proposal for a writing format.)

**Comment by NeumimTo** [comment]
Kind of related https://github.com/SpongePowered/SpongeAPI/issues/1856

@ST-DDT i quite disagree with your example. 

I see text templates as a *simple* way server administrators should be able to:
1) create new localizations
2) change some plugin messages via configuration files. 

Mainly this part "{{player | myperms:groupname brackets=true}}"

This is a clear example of something what i dont want to see. It has too high complexity, its hard to write, lots of characters to do a simple thing. Not all server administrators have good technical background. Keep in mind whos main target audience. 

1) TextTemplate needs to be represented as a single line when dumped into config. 

Imagine you are translating a plugin, with hundreds of messages. In current state of textemplate you would end in json garbage.  

On top of that translations in java world are usually handled via bunch of ResourceBundles. Simple key=value .property files. This format is not really well designed for multiline sutff

2) Dont try to turn TextTemplate into something like Velocity engine.
- Only replace simple keys encolsed in % { etc, which i (as a developer) defined for specific text template. 
- If i create the texttemplate with some pojo object, it doesnt mean that i want all its fields/getters to be accessible as parameters. Leave this for plugin developers to eventually write 3rd party library.

3) Bring back color codes. 
 "TEXT &4red text"  is a format which everyone in the minecraft world is familiar with. I

**Comment by ST-DDT** [comment]
I somewhat agree with you that its too complex for beginners. I have plenty experience with writing a template engine myself for Bukkut plugins. And from that i learnt the following.

A) beginners touch the config and mess it up lots of times regardless of complexity especially yaml or other indention based files.
B) if the config is complex they will tend to use the ingame config
C) advanced users are capable of understanding the structure of a template language easily
D) advanced users will ask for placeholders that the plugin author does not handle in his plugin like Perm groups, Factions or even some game role.

Thats why a complex logic is better suited for this because then the beginners could just use `Hello {{player}}` and the advanced users can use `Hello {{player | permgroup}} {{player}}` and that with no or almost no efford from the plugin developer.

If we dont provide the features the devs and their users need, then they will all use their own variants and we aren't any better off then just using String#replace.

As for using {{}} or %() i dont care as long as conflicts with text itself will be avoided.

As for color codes... we could give them their own syntax or just handle them the same. Advanced users will also rely on advanced text features such as hover or text actions (mainly if there is not enough space for all those prefixes) so they should be usable in a similar fashion.

**Comment by ryantheleach** [comment]
@NeumimTo Either Text itself, or Text templates needs to have late-resolving placeholders for plugins like PlaceholderAPI to work globally and efficiently, and show per-reciever / per-sender formatting / variables.

Working with MChat development on Bukkit, has taught me that any placeholders without a unique start, and unique end tag are painful, and make nesting difficult.

If you are talking about having arguments to text placeholders, Minecraft itself already does this in the tellraw command / json format for translations. That system works well, if a little verbose.

I agree that there is a compromise on usability vs verbosity vs features.

>Bring back color codes.
>"TEXT &4red text" is a format which everyone in the minecraft world is familiar with. I

They never went anywhere. You have always been able to choose a serialization format with color codes. It's just annoying to limit the scope of your colors, and control highlighting and composition of texts.

I also said in the original post, that the text template serialization should match the current text ones, so whilst I have a distaste for the color code method, it wouldn't be removed, and you could use them just fine.

**Comment by randombyte-developer** [comment]
I like the idea of having a global standard Sponge "PlaceholderAPI" built-in. Currently there's such a mess with all the placeholder enclosings like `%%`, `$`, `{}` just one `%`.

**Comment by ImMorpheus** [comment]
As of API 8 we are now using [Adventure](https://github.com/KyoriPowered/adventure). 

This means the old Text api is gone and all the related issues (especially those involving breaking changes) are no longer relevant, therefore I'm closing this.
