### ISSUE TITLE
TextSerializer isn't i18n aware

### ISSUE THREAD

**Issue by mmis1000** [SpongePowered/SpongeAPI#1904]
The `Translation` interface accept a `Locale` parameter to specify what language it should be translate to when format to plain text (although it is not used currently).

But `TextSerializer` does not accept `Locale` at all.

Which means, even after some day, the vanilla minecraft server finally supports multi language on server side, there is no where sponge plugin can use it, becuase the api does not care about it at all.

**Comment by ST-DDT** [comment]
AFAICT this is only a problem when using PLAIN & FORMATTING_CODE serialization, because their conversion is a lossy one. Json can restore the localized part.

**Comment by kashike** [comment]
What @ST-DDT said should be the case.

**Comment by mmis1000** [comment]
@ST-DDT @kashike it's still a problem, not everywhere in minecraft accept json format, item lore does not support that, so server side translation must be used.
And not in all use case you could send json to client.
JSON serilizer does not need that doesn't means you didn't need that completely.

Integration with external tool also require you to serialize it to plain.
Something like Minecraft to Discord brdige.
I believe there is no bot can accept json format on discord.

I know I can done it in my plugin, but I don't think it should be done by plugin's side.
This is obviously a function that should be done by API itself.
Even you don't intend to implement it, doesn't means API does not need to have it.
A default implementation to the english one is fine.

BTW, As far as I know, Although `Translation` has a `Locale` parameter, `Locale` parameter in `SpongeTranslation` is not used at all. That parameter is just left there for future override.
If you intentionally want to ban server side translation, why the method should even accept `Locale`?

**Comment by kashike** [comment]
1.13 lore does.

We don't ban server-side translation.

**Comment by mmis1000** [comment]
@kashike It does not, only name does, lore doesn't.

How could you translate it to other language on server side if `TextSerializer` does not care about `Locale` at all?
I don't think there is any way to present `translate this Text object to plain text in chinese` in current API.
As a non-english user, The `just translate everything to english` strategy looks really weird to me.

The reason I ask this here is, I am trying to fully implement the i18n things in sponge API that left unimplemented currently because I want to make our server really multi language compatible, And I soon realize that the `TextSerializer` is not i18n aware at all, which means, even I override everything in other part, I won't be able to use it in the sponge API.

The API for 1.12 is fixed at this moment, so I think it won't change. But the API for 1.13 haven't out, it should be the time to fix it now.
