### ISSUE TITLE
"Sponge" server crash with "LostCities" mod

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeAPI#1906]
In my modpack Using lost cities and spongeforge, the server shuts down with an error generation die.
I understand that I duplicate a bug report, but in a branch SpongePowered/SpongeForge#1815 it says the problem is solved, or I don't understand.
I apologize for the possible violation of the rules, I do not understand English and use a translator.

The server is using:

    Lost cities 2.0.10
    sponge 1.12.2-2705-7.1.0-beta-3361
    Version Forge-2740, but I tried it and recommended 2705
    Java 8 64-bit
    Linux, Windows

https://pastebin.com/kRWfpug1 - crash-report

The error indicates a problem with the world of mod Extra Utilities. I disable this world, but the same error appears with another mod

**Comment by ImMorpheus** [comment]
~move to sf

**Comment by limbo-app** [comment]
Hey @AndyDr! I've moved your issue to [SpongePowered/SpongeForge#2424](https://github.com/SpongePowered/SpongeForge/issues/2424).
