### ISSUE TITLE
ClickInventoryEvent getting Item with all data

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeAPI#1907]
Hi! I created custom inventory with ItemStack's with custom data. But ItemStackSnapshot don't have any data, which i put in ItemStack. How i can get original item with all puted data?
`
ItemStackSnapshot item = e.getCursorTransaction().getOriginal();
System.out.println(item.getKeys()); //Printed empty array
`

**Comment by ImMorpheus** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @NanitSoft! I've moved your issue to [SpongePowered/SpongeCommon#2093](https://github.com/SpongePowered/SpongeCommon/issues/2093).
