### ISSUE TITLE
MoveEntityEvent.teleport does not apply to spectator mode teleporting 

### ISSUE THREAD

**Issue by TheCrunchy** [SpongePowered/SpongeAPI#1908]
While in spectator mode you can middle click and use the icons to teleport to other people, the MoveEntityEvent.teleport event doesnt listen for this.

**Comment by ryantheleach** [comment]
~move to common

**Comment by limbo-app** [comment]
Hey @TheCrunchy! I've moved your issue to [SpongePowered/SpongeCommon#2099](https://github.com/SpongePowered/SpongeCommon/issues/2099).
