### ISSUE TITLE
API7 - Not possible to register custom damage type into the catalog registry

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1909]
The current way to register an element into any catalog registry is to listen to the event GameRegistryEvent.Register. 

I created some custom damage types, but cannot register them. The event GameRegistryEvent.Register<DamageType> event wont fire.

**Comment by Cybermaxke** [comment]
It may also be useful to support custom types for `HealingType`.

**Comment by gabizou** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @NeumimTo! I've moved your issue to [SpongePowered/SpongeCommon#2101](https://github.com/SpongePowered/SpongeCommon/issues/2101).
