### ISSUE TITLE
DataRegistration.Builder#manipulatorId() javadocs are hard to understand/broken

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeAPI#1912]
[`DataRegistration` Source](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/DataRegistration.java#L162) | [`DataRegistration` JavaDoc](https://jd.spongepowered.org/7.1.0/org/spongepowered/api/data/DataRegistration.Builder.html#manipulatorId-java.lang.String-)

> The id should be formatted according to the normal CatalogType standard: {manipulator-id| since the "pluginid" is gathered from buildAndRegister(PluginContainer) provided PluginContainer. 

There seems to be something missing after `{manipulator-id|` and the formatting of this snippet is hard to understand.

**Comment by ryantheleach** [comment]
@ST-DDT This should be solvable by looking through the git history, there's bound to have been a bad find replace or something somewhere. If not, reply and unassign.

**Comment by ImMorpheus** [comment]
DataRegistration.Builder#manipulatorId() has been deprecated (api 7) and removed (api 8) in favour of CatalogBuilder#id()
