### ISSUE TITLE
Broken/Suspicious AbstractSingleData/AbstractImmutableSingleData implementations in the API

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeAPI#1913]
The abstract implementations of `AbstractSingleData`/`AbstractImmutableSingleData` contain suspicious `ValueFactory#createValue()` calls.

**Method definition**

>    /**
>     * Creates a new {@link Value} with the provided {@link Key} and the
>     * <code>E</code> element and the provided <code>E</code> default value.
>     *
>     * @param key The key for the value
>     * @param element The element
>     * @param defaultValue The default value
>     * @param <E> The type of element
>     * @return The newly created value
>     */
>    <E> Value<E> createValue(Key<Value<E>> key, E element, E defaultValue);

**Mutable AbstractSingleData**

* org.spongepowered.api.data.manipulator.mutable.common.AbstractSingleCatalogData

> factory.createValue(this.usedKey, getValue(), getValue());

The current value is the default value? At least that behavior of the immutable variant is different.

**AbstractImmutableSingleData**

* org.spongepowered.api.data.manipulator.immutable.common.AbstractImmutableBooleanData
* org.spongepowered.api.data.manipulator.immutable.common.AbstractImmutableSingleEnumData
* org.spongepowered.api.data.manipulator.immutable.common.AbstractImmutableSingleCatalogData

> factory.createValue(usedKey, this.defaultValue, this.value)

Suddenly the default value and the value swap their positions?

--------------------------------

* AbstractSingleCatalogData
* AbstractSingleEnumData
* AbstractBooleanData
* AbstractImmutableSingleEnumData
* AbstractImmutableSingleCatalogData

Already implement the `toContainer()` method properly, but `AbstractImmutableBooleanData` does not. And that isn't documented anywhere.

---------------------------------

AbstractSingleData/AbstractImmutableSingleData allows using a `Key<? extends BaseValue<T>>` which technically allows `Key<ImmutableValue<X>>`. However all implementtions actually only use the mutable variants, and worse they don't restrict it in the constructor either.

* AbstractBooleanData
* AbstractMappedData
* AbstractSingleEnumData
* AbstractImmutableListData
* AbstractImmutableMappedData
* AbstractImmutableSingleCatalogData

---------------------------------

The usage of the final modifier for methods is inconsistent.

* AbstractImmutableSingleEnumData#getValueGetter() - final
* AbstractImmutableSingleCatalogData#getValueGetter() - not final
* AbstractImmutableMappedData#getValueGetter() - final
* ...

---------------------------------

AbstractImmutableSingleEnumData implements methods that are not part of any interface, but are redundant as is.

* protected final ImmutableValue<E> enumType()
* `@Override` protected final ImmutableValue<E> getValueGetter()

Maybe that method should have been called type and be part of the `ImmutableVariantData` interface?

---------------------------------

The `AbstractIntData` class is useless as is.

---------------------------------

AbstractListData contains method implementations that are redundant with the parent implementation.

---------------------------------

Duplicate or missing implementations of `hashCode()` and `equals()`:

* AbstractSingleData - existing
* AbstractMappedData - duplicate
* AbstractListData - duplicate
* AbstractBoundedComparableData - missing?
* AbstractImmutableSingleData - missing?
* AbstractImmutableBoundedComparableData - missing?

------------------------------

At this point I stopped searching for more errors, maybe I continue the search tomorrow.

**Comment by ST-DDT** [comment]
Is someone working on a fix for this API or has plans to refactor it (and thus invalidates the need of documentation for the current version)?

**Comment by ryantheleach** [comment]
@ST-DDT I've marked this as a data 'bug' for want of a better term.

@gabizou If you could provide some answers to a few of these questions, it will become possible for a member of the community to fix this in a PR.

**Comment by ItsDoot** [comment]
Pinging @Cybermaxke since he is the new data api caretaker.

**Comment by Cybermaxke** [comment]
I am going to fix the things that are possible for API 7, and a refactor will be done in API 8 (removing redundant methods, the values API refactor, etc.)

**Comment by Cybermaxke** [comment]
I have fixed a few of the issues in the above PR (for API 7), please comment there if I missed something.

**Comment by ST-DDT** [comment]
* [x] inconsistent/wrong usage of `createValue`
* [x] implement the toContainer() consistently
* [x] restrict key in constructor
* [ ] inconsistent final modifier for methods (API breaking)
* [x] undefined enumType() method
* [x] useless AbstractIntData class
* [x] redundant AbstractListData method implementations
* [x] missing/duplicate hashCode and equals implementations

**Comment by Cybermaxke** [comment]
* Where did I miss `inconsistent/wrong usage of createValue`?
* `inconsistent final modifier for methods`, I can only remove final modifiers to avoid breaking, this may not be desired.
* `implement the toContainer() consistently`, I will look into it

**Comment by ST-DDT** [comment]
* Where did I miss inconsistent/wrong usage of createValue?

  AFAICT only in a single instance

  * [AbstractImmutableBooleanData](https://github.com/SpongePowered/SpongeAPI/pull/1945/files#diff-1442b242468d5ffdae1cd5c3252dcfd4R61)
    ````java
    [...]createValue(usedKey, defaultValue, value)[...];
    ````

**Comment by Cybermaxke** [comment]
Alright, I resolved the issues you pointed out. (except the final method one)
I added the `fillContainer` method from the bleeding branch (as non abstract) to fix the `toContainer()` inconsistency.

**Comment by ST-DDT** [comment]
What is the benefit of the `fillContainer()` or where does it originate?

**Comment by Cybermaxke** [comment]
A lot of devs are currently forgetting to override the `toContainer` method to add their own data. That forces them to add it (which is currently not possible without breaking).

**Comment by Cybermaxke** [comment]
See https://github.com/SpongePowered/SpongeAPI/commit/67e79cbbac43159578444f5ba431a09c6be72c40

**Comment by ItsDoot** [comment]
What is the current status of this issue?

**Comment by Zidane** [comment]
Closing as this is getting tossed in api-8.
