### ISSUE TITLE
Document behavior of clientconnectionevent.login for banned users.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#1916]
https://github.com/SpongePowered/SpongeCommon/issues/1093

States that the events are pre-cancelled.

If this is expected to be consistent across platforms, then it should be documented in the API javadocs for the event as a part of the contract.

Suggestions on how best to word it? (I'm unable to do so at the moment, so that's why I created the issue)

**Comment by simon816** [comment]
It already is documented, see here: https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/event/network/ClientConnectionEvent.java#L94-L104
