### ISSUE TITLE
ChangeBlockEvent.Break.Pre fires on chest open

### ISSUE THREAD

**Issue by Shmeeb** [SpongePowered/SpongeAPI#1918]
Minecraft: 1.12.2
    SpongeAPI: 7.1.0-ff990df
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3477
    Minecraft Forge: 14.23.4.2705

**Comment by gabizou** [comment]
~move to sc

**Comment by limbo-app** [comment]
Hey @Shmeeb! I've moved your issue to [SpongePowered/SpongeCommon#2118](https://github.com/SpongePowered/SpongeCommon/issues/2118).
