### ISSUE TITLE
Player Stopped Using Item Event

### ISSUE THREAD

**Issue by KernelFreeze** [SpongePowered/SpongeAPI#1924]
Hello! Minecraft Vanilla has a method in Item.java, called `onPlayerStoppedUsing` in the latest MCP mappings. Experimenting with it, I see that it is called every time that a player stopped using the item, which is very useful for some checks, so I would like to know, is that possible to be integrated into the API? Thanks and best regards.

**Comment by Lignium** [comment]
If I understand correctly, you need the `org.spongepowered.api.event.item.inventory.UseItemStackEvent.Stop` event in SpongeAPI.

**Comment by gabizou** [comment]
That is the correct event to use.

**Comment by KernelFreeze** [comment]
Thanks!
