### ISSUE TITLE
Better cataloging of Game Locales / NamedLocales

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/SpongeAPI#1927]
These two classes have very poor functionality. They don't have access methods that would return all locales that are supported by the game.
List from any catalog can be obtained through the game registry. But these classes are not a catalog and not even an enumeration.

**Comment by ST-DDT** [comment]
What would be your usecase for the locale list?

**Comment by Lignium** [comment]
I create a root service plugin to easy localize my other plugins. This plugin loads the global locale configuration for all plugins in general and for individual plugins in particular. Having obtained the locale from the configuration, I need to check whether it is compatible with the game, and whether it makes sense to send messages in a language that may not be supported by the game client.

**Comment by ryantheleach** [comment]
@Lignium (if it's possible) would making Locales CatalogTyped work?

**Comment by Lignium** [comment]
I think the Locale class cannot be cataloged directly, a wrapper class is needed, which will be annotated "CatalogedBy" and named, for example, a GameLocale.

**Comment by ST-DDT** [comment]
Isn't is possible to just add a method to `Game` to return a list of all supported locales?
