### ISSUE TITLE
Improvements of Asset API

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/SpongeAPI#1928]
1. Need to rename the arguments "name" to "path" or "resourcePath". This name is confusing, because it is impossible to understand from its name whether it is possible to obtain resources located in separate directories. Same with the AssetId annotation.
2. The manager must have a directory scan method.

**Comment by Cybermaxke** [comment]
This will be covered in the datapack api pr: https://github.com/SpongePowered/SpongeAPI/pull/1706
