### ISSUE TITLE
MessageEvent MessageFormatter small suggestion

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/SpongeAPI#1937]
Example: i'm making simple plugin, that divides chat to local and global and adds prefix for global/local chats.

MessageFormatter contains `header`, `body` and `footer` of resulting message.
These 3 parts are `SimpleTextFormatter`'s. Every `SimpleTextFormatter` contains list of `SimpleTextTemplateApplier`. `SimpleTextTemplateApplier` is just a holder for `TextTemplate` and it's params. You can easily set/get parameters.
I can add/remove/get `SimpleTextTemplateApplier` to a any `SimpleTextFormatter` or even replace that `SimpleTextTemplateApplier`.
What i can't:
I can't tell, what added another plugin
I can't tell, what message under what position i got

Next example:
My plugin sends message to a local, if message starts with `!` char.
If any another plugin adds something to body's `SimpleTextFormatter`, i can't really tell, what `SimpleTextTemplateApplier` has player's message!

Maybe introduce some method, that can change/get/remove built-in(injected my MC itself) `SimpleTextTemplateApplier`(s)?

Also, `TextTemplateApplier#getParameter` may return null, but method isn't marked nullable or returns `Optional<TextElement>`

**Comment by ST-DDT** [comment]
Related: https://github.com/SpongePowered/SpongeAPI/issues/1891

**Comment by ImMorpheus** [comment]
As of API 8 we are now using [Adventure](https://github.com/KyoriPowered/adventure). 

This means the old Text api is gone and all the related issues (especially those involving breaking changes) are no longer relevant, therefore I'm closing this.

(MessageFormatter is gone)
