### ISSUE TITLE
Expose setDetonator to API

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1940]
https://github.com/SpongePowered/SpongeCommon/blob/a9423c7ec9f2b423b52c273f7e7a23818a8f3e41/src/main/java/org/spongepowered/common/mixin/core/entity/item/MixinEntityTNTPrimed.java#L75

the method setDetonator is on the mixin but is not exposed to tnt interface 

https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/entity/explosive/PrimedTNT.java

**Comment by ImMorpheus** [comment]
API8 has `Keys#DETONATOR`

Method is exposed here https://github.com/SpongePowered/SpongeAPI/blob/145b55135b894087eee96ec9268d9b8b94ff6691/src/main/java/org/spongepowered/api/entity/explosive/fused/PrimedTNT.java#L42
