### ISSUE TITLE
Adding sendTo method to Text builders

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeAPI#1947]
The PaginationList allows for a `sendTo()` method instead of `build()` and this would eliminate the need for having multiple lines when a builder is needed.

**Comment by ItsDoot** [comment]
Does this break the builder pattern? As in, are builders supposed to be reusable?

**Comment by ghost** [comment]
Well it could include both the `sendTo()` as well as a `build()` method. the `sentTo()` method could return the builder while also sending it. Similar to how the remove method in a list returns the value as well as actually removing it.
