### ISSUE TITLE
Api 7 chceck if itemtype may be put into one of vanilla armor slots. 

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1956]
@Faithcaio told me its already in the impl

**Comment by gabizou** [comment]
Get [`EquipmentType`](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/data/property/item/EquipmentProperty.java#L36) via property from the `ItemStack`, and check against the equipment slot property from the inventory slot.
