### ISSUE TITLE
TileEntity -> BlockEntity

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#1957]
What we call [`TileEntity`](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/block/tileentity/TileEntity.java) should be called `BlockEntity` for consistency:
- we have `BlockType`, not `TileType` - `Tile` was renamed to `Block` in Minecraft years ago
-  vanilla and the community refer to these as "BlockEntity"/"block entity", except in some legacy cases (`doTileDrops` gamerule, for example)

**Comment by Cybermaxke** [comment]
It's time for a revolution! We shouldn't hold on to old naming practices, especially for a modern minecraft API.

**Comment by liach** [comment]
yeah, it's no longer 4 years ago

**Comment by kashike** [comment]
#1994
