### ISSUE TITLE
testNoArgsFunctional failed

### ISSUE THREAD

**Issue by limbo-app** [SpongePowered/SpongeAPI#1962]
This issue was originally submitted by @sorrowloki in [SpongePowered/SpongeForge#2593](https://github.com/SpongePowered/SpongeForge/issues/2593).
___
Hello all! Just try to build through gradlew on my system. During building I had this: 

- SpongeForge version:  latest stable-7 branch
- Java version: openjdk version "1.8.0_171"
- Operating System: Debian 8 

org.spongepowered.api.command.CommandSpecTest > testNoArgsFunctional FAILED
    java.lang.IllegalStateException: Sponge has not been initialized!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
        at org.spongepowered.api.Sponge.check(Sponge.java:77)
        at org.spongepowered.api.Sponge.getCauseStackManager(Sponge.java:269)
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:338)
        at org.spongepowered.api.command.CommandSpecTest.testNoArgsFunctional(CommandSpecTest.java:57)

Full report: https://gist.github.com/sorrowloki/8a84b376c91735e648efdfa38daf63d8

**Comment by dualspiral** [comment]
I've moved the issue for you @sorrowloki!

I actually get this too running on a similar system. The test itself it technically fine, it just seems that the tests run in a different order on different systems... I guess?

Anyway, I advise just slapping `@Ignore` on it for now for your own workspace. The fix to this is simple but we'd need to confirm it doesn't mess with tests on other platforms (because the order may be incorrectly relied upon and it might break other tests).

**Comment by sorrowloki** [comment]
Hello, @dualspiral! Sorry, that answered so long. 

Thank that moved my issue here and again sorry for the mistake, this was my inattention. 

Maybe yes. How can I check it? Sorry, I am too new in Java and in sponge's plugin development in particular. I will be glad to provide you with all the information that you need.

The tempory fix is just to change `@Test` to `@Ignore`? I tried it but without any success. Maybe I do something wrong?

**Comment by dualspiral** [comment]
If you're developing plugins, you don't need to create a Sponge workspace, you just need to build against the API that you can get from our repositories. I suggest having a look at https://docs.spongepowered.org/stable/ru/plugin/workspace/index.html
(though I notice that you're Russian, so may find https://docs.spongepowered.org/stable/ru/plugin/workspace/index.html better). This should help you get a workspace set up that you can build against.

To answer your question, you'd find the `testNoArgsFunctional` method in the SpongeAPI test package and add the `@Ignore` annotation.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/604894e76464cd690d335f834bd5b82ccfe381ad
