### ISSUE TITLE
PIG_ZOMBIE should be ZOMBIE_PIGMAN

### ISSUE THREAD

**Issue by Pokechu22** [SpongePowered/SpongeAPI#1964]
ಠ_ಠ

https://github.com/SpongePowered/SpongeAPI/blob/a1418ae3fccbfa1fbc56e05d2f3375dcd1344e1c/src/main/java/org/spongepowered/api/entity/EntityTypes.java#L142

`PigZombie` became `zombie_pigman` in 1.11.  The ID should be cleaned up with the rest of the stuff in 1.13 at least.

This was brought up in [this combined issue](https://github.com/SpongePowered/SpongeAPI/issues/221#issuecomment-169065675) but the issue had already been closed at that point so I don't think it was noticed.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/93a134735955fb5a1f6752b26b986b01a23355de
