### ISSUE TITLE
No event to listen to when an item in hand breaks

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#1970]
^ There appears to be no event for that. 
If thats supposed to be DropItemEvent.Destruct, then its not called from appropriate place

**Comment by Faithcaio** [comment]
Its not `DropItemEvent.Destruct` for sure. 
https://github.com/SpongePowered/SpongeAPI/blob/81ce267dc845e37caf3bed3f3fdc9432a8b14bf6/src/main/java/org/spongepowered/api/event/item/inventory/DropItemEvent.java#L80-L81

Its either `InteractItemEvent` for the interaction 
or 
as the item is "equipped" in the inventory `ChangeEntityEquipmentEvent`

**Comment by NeumimTo** [comment]
ChangeEntityEquipmentEvent is called far too many times. - every time player places a block, or its item in hand changes durability
would it be possible to introduce ChangeEntityEquipmentEvent.Desctruct.

**Comment by ImMorpheus** [comment]
PR merged (https://github.com/SpongePowered/SpongeAPI/pull/2020)
