### ISSUE TITLE
Method to get blocks around a player based on a given radius

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeAPI#1974]
Currently you can use `Player#getNearbyEntities` to get all entities around a player within a radius. It would be extremely handy to be able to get all the blocks in an area around a player.

Something similar to `Player#getNearbyBlocks(radius)` and return a list.

**Comment by TSEcho** [comment]
Nevermind there is a method

**Comment by ghost** [comment]
It would also be nice to have a `isNearBlock` method in place or along side the above method that could be similar to this:

    public boolean isNearBlock(Player player, String block, int radius) {

        World world = player.getWorld();
        int px = player.getLocation().getBlockX();
        int py = player.getLocation().getBlockY();
        int pz = player.getLocation().getBlockZ();
        
        for(int x = (px - radius); x < (px + radius); x++)
            for(int y = (py - radius); y < (py + radius); y++)
                for(int z = (pz - radius); z < (pz + radius); z++)
                    if(world.getBlock(x, y, z).getType().getName().equalsIgnoreCase(block))
                        return true;
        return false;
    }

**Comment by gabizou** [comment]
A few considerations for this:
- To what limit do we get blocks for the radius?
- Is it better to give you an extent view (reduced view) of the world to the radius size?
- The first post mentions getting a list of block states, do you just want to know what type of blocks are around the player?
- The second post mentions checking if the player is near a specific block id, but you're doing that just fine...

What's the actual point of what you're wanting to do?

**Comment by ghost** [comment]
I think I can shine some light on a few of these:

* I am unaware of the impacts this sort of method would have but I'd imagine having a limit wouldn't be necessary if it was set to its own task. If it did end up causing a significant impact, a limit of some sort would need to be tested to find.
* Unsure of what the concern means here.
* I think it may be more beneficial to get the block states instead of the item types as this can provide more practical uses for developers that may want to perform actions on these various blocks.
* The second submission was more of an afterthought as a nice feature but I feel the first method is much more needed as its uses can be endless.

This sort of method could be great for several reasons. First, if you want to perform actions on many blocks in an area this provides a quick way to do so. Second, if you were to want to keep statistics on the blocks around a player such as figuring out how many "Farm Blocks" or something similar are near a player this creates a layer of abstraction so no one needs to manually set it up. Finally, with the help of some overloaded params, this type of method could be used for lots more. With the addition of allowing a vector as a parameter you could get the blocks within a box and go from there or even better having a Predicate as an option would be extremely helpful.

Overall I think this would make the process of dealing with player -> world/block interaction far easier and would save lots of headaches and time.
