### ISSUE TITLE
How do you feel about Kotlin for this repo?

### ISSUE THREAD

**Issue by LarsArtmann** [SpongePowered/SpongeAPI#1979]

**Comment by JBYoshi** [comment]
For the API itself, I’d lean against it. While I have nothing against Kotlin, many plugin developers use Java, and I wouldn’t want to run the risk of someone breaking Java-based plugins by adding a Kotlin-specific feature.

On the other hand, if you mean the Gradle scripts, I’m fine with that. I think there are some plans to port the Gradle scripts over to Kotlin sometime soon.

**Comment by LarsArtmann** [comment]
@JBYoshi if you use Kotlin in the right way, you have a 100% Java compatibility

PS: Sorry for my bad English. Greetings from Germany 😄

**Comment by gabizou** [comment]
Not to squash hopes, but, the API is written in Java for the simple reason of it's plain and simple. If we start writing in Kotlin, we have the issue of maintainability, upgrading Kotlin versions, implementation needing to handle Kotlin's dynamic code generation, etc. As a build system, it's fine, but as a language for our API, it's going to be a clear "No" for now.
