### ISSUE TITLE
Unable to adjust the Entity "power" tag for Fireballs.

### ISSUE THREAD

**Issue by Pulverizer** [SpongePowered/SpongeAPI#1981]
Description of the tag by the Official Minecraft Wiki:

> power: List of 3 doubles that adds to direction every tick. Act as the acceleration.
   ~ [Official Minecraft Wiki - Ghast](https://minecraft.gamepedia.com/Ghast#Ghast_fireball)

Just from reading this description you can see why, when altering the course of a Fireball entity, you would need to be able to adjust this tag.

**Comment by RedNesto** [comment]
What you would want to use is `Keys#VELOCITY`.
Also, `Entity` have `get/setVelocity` shortcuts methods.

**Comment by Pulverizer** [comment]
get/setVelocity only gets/sets the current velocity.

power is something different.

**Comment by Pulverizer** [comment]
To clarify, this is how the wiki would read if you used terms that you would see in SpongeAPI.

> power: Vector3d that is added to `velocity` every tick. Acts as the acceleration.

**Comment by Zidane** [comment]
So really this is just a modifier on velocity, correct?

**Comment by RedNesto** [comment]
Oh I see, I must have misunderstood the wiki and misread minecraft's code.

And yes, power is simply added to motion/velocity each tick.

**Comment by Pulverizer** [comment]
@Zidane Yes?

@RedNesto No problem.

It's one of those things where nobody would notice this unless they happened to be making some really awkward plugin that just happens to alter the course of fireballs.
