### ISSUE TITLE
Missing advancement positions

### ISSUE THREAD

**Issue by liach** [SpongePowered/SpongeAPI#1988]
Vanilla advancement system allow servers to define custom locations for an advancement in the advancement user interface through packets (not available through JSON).

https://github.com/SpongePowered/Snowman/blob/6c8bdc322e8e48c0c785cd88a44c8b5759cbb176/src/main/java/net/minecraft/advancements/DisplayInfo.java#L163-L164

However, sponge currently lacks such a hook for this access. A hook like https://github.com/SpongePowered/Snowman/blob/6c8bdc322e8e48c0c785cd88a44c8b5759cbb176/src/main/java/net/minecraft/advancements/DisplayInfo.java#L45 would do a giant favor for plugins and make the advancement UI way more beautiful.

Also, considering that vanilla has a builtin logic for arranging advancement positions, it may be a favor for sponge to add an event for advancement arrangement and add a catalog type for advancement arranger.

https://github.com/SpongePowered/Snowman/blob/named-bleeding/src/main/java/net/minecraft/advancements/AdvancementTreeNode.java (The MCP name is wrong; this is an arranger that has one instance for each advancement instead of some sort of tree node)

**Comment by Cybermaxke** [comment]
You can already modify the default layout with the `AdvancementTreeEvent.GenerateLayout` event.
