### ISSUE TITLE
UserStorageService, missing parts

### ISSUE THREAD

**Issue by Defman** [SpongePowered/SpongeAPI#1989]
It is currently impossible to implement UserStorageService to my knowledge. This is due to the fact there's no way to instantiate a User object.

There exists `GameProfile.of(uuid, username)` like wise there should be a `User.of(profile, container)` or similar.

Reason: I would like to replace UserStorageService with one that utilizes some other means of storage, ie Postgres.

**Comment by Defman** [comment]
I propose adding UserManager which is equivalent to GameProfileManager.

```java
public interface UserManager {
    User createUser(GameProfile profile, DataView data);
}
```

Furthermore there should be added `save` methods to `UserStorageService` instead of
[save()](https://github.com/SpongePowered/SpongeCommon/blob/b746d898ba03882d9db603b4ed5d9d048d3fd9dd/src/main/java/org/spongepowered/common/entity/player/SpongeUser.java#L340). And the "hack" of [forceRecreateUser()](https://github.com/SpongePowered/SpongeCommon/blob/9c4cd22544e01f407d04826b8405c72115e3501b/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L497) should allow Custom provided `UserStorageService` or a nicer solution should be found, like updating the `UserStorageSerivce` with the new username before the creation the Player Entity.

**Comment by XakepSDK** [comment]
It's better to use something checked instead of raw `DataView`

**Comment by Defman** [comment]
> It's better to use something checked instead of raw `DataView`

Instead of a UserManager the DataManager could be utilized as such, `Sponge.getDataManager().deserialize(UserData.class, container);`

**Comment by Defman** [comment]
However a User may contain data which sponge is not able to check, and we should therefor only check parts of the data (sub data like RespawnLocations).

**Comment by ImMorpheus** [comment]
Closed by https://github.com/SpongePowered/SpongeAPI/commit/14041cb0371046a190a3063994505241290abc57
