### ISSUE TITLE
During the item pickup event obtain the slot where the item is going to be placed

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#2000]
Is this possible? 

For example i would like to cancell the pickup event if the item would be assigned into a hotbar slot

**Comment by NeumimTo** [comment]
Eventually i solved it by getting  SlotTransaction Object `event.getTransactions().get(0)`, then transformed its Slot instance and checked whenever its value of `SlotIndex` is lesser than 8. There might be an easier method but this appears to work, at least in a non-modded environment

**Comment by Faithcaio** [comment]
`playerInv.query(Hotbar.class).containerInventory(slot.transform())` might work as well
