### ISSUE TITLE
Catalog types & AdditionalCatalogRegistryModule interface

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#2014]
Sometimes i would like to have a multiple CatalogType caches (ie AdditionalCatalogRegistryModule) to be managed by a single class/service. 

In java its not possible to do 
`public class SomeClass implements AdditionalCatalogRegistryModule<A>, AdditionalCatalogRegistryModule<B> `

Would it be possible to add an optional way to controll the flow with annotations? 

```Java
@Service
public class SomeService {

    @CatalogModule.getById(A.class)
    public Optional<A> getAById(String id);

    @CatalogModule.getById(B.class)
    public Optional<B> getBById(String id);

    @CatalogModule.registerCatalogType(A.class)
    public void registerAdditionalCatalog(A extraCatalog)

    @CatalogModule.registerCatalogType(B.class)
    public void registerAdditionalCatalog(B extraCatalog)

    @CatalogModule.getAll(A.class)
    public Collection<A> getAllOfA(A extraCatalog)

    @CatalogModule.getAll(B.class)
    public Collection<B> getAllOfB(B extraCatalog)
```

This would allow us to have multiple catalog caches within a single class, thus reducing boilerplate which is currently neccessary to create AdditionalCatalogRegistryModules.

**Comment by ST-DDT** [comment]
Do you want to create a cache or add a new registry module?
What would be your use-case?
Why do you need two or more different catalog classes in one class?
Have you considered creating delegating wrappers that each handle a single type?

**Comment by NeumimTo** [comment]
>Do you want to create a cache or add a new registry module?

Thats the same thing? At runtime all catalog types are cached.

>What would be your use-case?

Something like:

    public class SomeClass implements AdditionalCatalogRegistryModule<A>, AdditionalCatalogRegistryModule<B>

>Why do you need two or more different catalog classes in one class?

Why do i need to create a new class for each catalog type? 

>Have you considered creating delegating wrappers that each handle a single type?

boilerplate code which can be fixed only on sponge side

**Comment by ST-DDT** [comment]
> > Why do you need two or more different catalog classes in one class?
>
> Why do i need to create a new class for each catalog type?

Separation of concerns, or are they that closely related? Probably yes.

> > Have you considered creating delegating wrappers that each handle a single type?
>
> boilerplate code which can be fixed only on sponge side

Aside from the class declaration and the imports (that any IDE will generate and hide for you), you will still have the same amount of actual code.
You might be able to omit most of the code if you rely on inheritance / API provided `CatalogRegistryModule` implementations, though.

------------------

Would something like this help you?

**`GameRegistry`**
* `createImmutableCatalogModule(Class<T>, Collection<? extends T>) : CatalogRegistryModule`
* `createMutableCatalogModule(Class<T>) : AdditionalCatalogRegistryModule`

or have implementations of those two variants available in the API?

**Comment by NeumimTo** [comment]
>>>Why do you need two or more different catalog classes in one class?

>>Why do i need to create a new class for each catalog type?

>Separation of concerns, or are they that closely related? Probably yes.

The things are closely related, all of these CatalogTypes are handled by very similar logic in the same guice Singleton. 

>you will still have the same amount of actual code.
Yes same amount of code, but i wont be forced to create X implementations of AdditionalCatalogRegistryModules, => less class files in my project => simpler to find out the sutff. 

AdditionalCatalogRegistryModule is nothing more than a wrapper around a Map, or less likely a Collection. Do we have to create it every time? If i need 10 catalog types do i have to create the almost same class 10th times? Could there be easier way? 

As for the code sample: 

GameRegistry
    createImmutableCatalogModule(Class<T>, Collection<? extends T>) : CatalogRegistryModule
    createMutableCatalogModule(Class<T>) : AdditionalCatalogRegistryModule

Yes that would actually solve what i need as well, 

maybe add 
    createImmutableCatalogModule(Class<T>, Map<String, ? extends T>) : CatalogRegistryModule
since Map does not inherit from Collection

Or maybe even simpler would be:

    createCatalogModule(Class<T>, Supplier<Collection<? extends T)/Or Map<String, ? extends T)); void

Where T is defined as T extends CatalogType
then the usecase would be 
    
    registerCatalogModule(MyCatalogType.class, () -> referenceToAMapOrCollection);

In that case i can choose when, or if, the catalog module will be immutable/mutable by relying on the bussines logic in my code, and not within sponge.

**Comment by ST-DDT** [comment]
Here a previous attempt of mine:
https://github.com/SpongePowered/SpongeAPI/pull/1385

**Comment by ST-DDT** [comment]
Why would you use a Supplier?

**Comment by ImMorpheus** [comment]
Closed by https://github.com/SpongePowered/SpongeAPI/commit/98980a85e9c4f980da0d74665b181e745ac33859#diff-635f7cffdfc7e01562476fc29e79a663

`AdditionalCatalogRegistryModule` (and most of the registry framework) is gone
