### ISSUE TITLE
Active Page on PaginationList

### ISSUE THREAD

**Issue by TheBrambleShark** [SpongePowered/SpongeAPI#2023]
The `PaginationList` object (or rather, its builder) currently lacks a way to set the active or initial page, meaning that whenever the player is shown the list, it will always be on page 1. 

There should be an `activePage` or `initialPage` property which, when set to an int, will initially display on that page.

**Considerations**

* How do we handle numbers less than one? 
  * Round up to 1
  * Absolute value (could cause unexpected results)
  * Display an error message
* How do we handle numbers greater than the maximum number of pages?
  * Round down to last page
  * Round down to last page + 1 and show "no entries" or something similar (so it's clear the user messed up but it doesn't take forever with just clicking the previous page button to get to the initial page)

**Comment by WillBAnders** [comment]
`PaginationList` has a [`sendTo(MessageReceiver receiver, int page)`](https://github.com/SpongePowered/SpongeAPI/blob/a1418ae3fccbfa1fbc56e05d2f3375dcd1344e1c/src/main/java/org/spongepowered/api/service/pagination/PaginationList.java#L117-L129) method that can be used. 

However, because this sends an error message to the user if the page is out of bounds, you'd need to know if the page number exists for certain things. There doesn't seem to be a clean way to do this in the API, but it can be done with some math using the total size of the contents and the number of lines per page. I would not be opposed to adding a `getNumberOfPages` method or something either.

**Comment by dualspiral** [comment]
@Foxtrek64 I don't know if you're interested in this any more, but this has come up on our radar and so I'd like to understand this a little more.

Why do you want this? Specifically, why is it important to send a user to an initial specific page, which might be the last page?

Just trying to guage whether this is actually an XY problem and so your issue might actually be better solved in an entirely different way.

**Comment by TheBrambleShark** [comment]
So one of the plugins I am building allows a user to display a title - how it's displayed is not a concern of my plugin, it just passes it to PlaceholderAPI and the consumer decides from there.

In order to choose a title, the user uses `/title set <title>`. This title is chosen from a preconfigured list of titles as designated by users with authorization to create a title. As such, users need to be able to display a list of these titles which may have several hundred entries. My draft title list has over five hundred.

With most pagination systems, users can jump directly to a specific page. This capability is not available here with the current system.

I want to be able to allow a user to use `/titles list <pageNumber>` to be able to immediately show a specific page. My current list command looks like this:

```kt
@Subcommand("list")
@Description("Provides a list of titles available to you.")
@CommandPermission("luzfaltex.titles.list.base")
fun onList(player: Player, @Default("1") page: Int) {

	// Get a list of all titles
	val availableTitles = plugin.dataService.getAvailableTitles(player.uniqueId)

	val builder = PaginationList.builder()
	builder.title(Text.of(Message.TitlesList.getFormattedMessage()))
	builder.padding(Text.of(" "))
	builder.contents(availableTitles.values.map { title: TitleCatalog -> Text.of(Message.TitlesListEntry.getFormattedMessage(title.name)) })

	builder.sendTo(player)
}
```

You can see I've provided some initial setup for accepting a page number, though there is no direct way of providing that.

Does the `.sendTo()` overload @WillBAnders suggested live in a `PaginationListBuilder` or is this strictly a `PaginationList` member? If I can just call `builder.sendTo(player, page)` then this is a rather easy solution (that said I've not touched this project since I made the original post, so I don't know if that overload was added since then or if it existed and IntelliSense just didn't tell me).

**Comment by dualspiral** [comment]
No, but you could just `build().sendTo(player, page)`, which is what the `sendTo` on the builder does anyway.

**Comment by dualspiral** [comment]
Closing as we already have the requested behaviour.
