### ISSUE TITLE
Rotating of blocks (issue with RailDirection)

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/SpongeAPI#2026]
Hello! In my project, I needed to rotate some objects from blocks, that is, what the `//rotate` command of WorldEdit does, too. I have already found a way to transform the coordinates of blocks, however, some blocks have their own rotation (for example, a furnace or rails). Some blocks can be rotated right now, some can only be in API 8 (1.14), and some have problems.

Here is a small list of data that needs to be changed for the blocks that have them in order to rotate structures correctly (if I forgot something, please remind):

- **AxisData** - there are no problems.
- **ConnectedDirectionData** - here too. The `Direction` class is very well designed.
- **DirectionalData** - obviously everything is okay too.
- **LogAxisData** - logs can be rotated using `Axis` in API 8, although it would be nice to add a method `Optional<Axis> LogAxis#toAxis()` and `LogAxis#fromAxis(Axis axis)` to API 7.
- **RailDirectionData** - and here there are problems. The `RailDirection` class does not have any useful methods. Transforming of this data is not possible. There is an option to write own conversion code, but it will turn out to be very cumbersome and not beautiful.
- **WireAttachmentData** - I think there will be no problems.

As you can see the main problems with `RailDirection`... ~~Will it be possible to somehow improve this class in API 8 or maybe even in API 7?~~

**Comment by Lignium** [comment]
I have a suggestion on how to do this:

```java
public interface RailDirection extends CatalogType, Cycleable<RailDirection> {
    Optional<Direction> getAscendingDirection();
    
    default boolean isAscending() {
        return getAscendingDirection().isPresent();
    }
    
    Direction getBeginDirection();
    
    Direction getEndDirection();
}
```

With the help of these getters, I will be able to carry out transformation (transformation of directions obtained through these methods). And to convert transformed directions back to RailDirection, I can simply iterate over all registered constants of this type, and using the same getters, find the desired constant.

~~It is only necessary to think that there is a beginning and an end of rails. I think it can be viewed clockwise or counterclockwise.~~

~~Unfortunately I can’t create a PR, because I am having difficulty setting up Sponge projects in Eclipse (mainly due to Mixin and Gradle). I ask to help with this in order to include these changes to API 8 (or even possible to API 7.2). I think it will be very simple to implement this interface.~~

**Comment by VcSaJen** [comment]
I think in implementation there were problems with modifying rails direction when there's adjacent rails: SpongePowered/SpongeCommon#612 . 1.13+ may be fixed this issue, I'm not sure.

**Comment by Lignium** [comment]
@VcSaJen The fact that rails are distorted during transformations already suggests that this data is by no means ignored, and this is good. The PR allows me to manually set directions for rails in accordance with a transformation, as I do it with other blocks, and it works, I personally tested.
