### ISSUE TITLE
CustomData on an ItemStack is not preserved once added to an Inventory

### ISSUE THREAD

**Issue by LXGaming** [SpongePowered/SpongeAPI#2027]
**I am currently running**
- SpongeAPI version: 7.1.7-SNAPSHOT
- Java version: 1.8
- Operating System: Linux / Windows 10

- Plugins/Mods:
CustomPlugin

**Issue Description**
Adding an ItemStack with CustomData to an Inventory then later retrieving that item from the Inventory results in the CustomData getting lost. This works in API 7.1.6

Attached is a plugin source for testing
[SpongeDebug.zip](https://github.com/SpongePowered/SpongeAPI/files/3464587/SpongeDebug.zip)

**Comment by XakepSDK** [comment]
Dupe: https://github.com/SpongePowered/SpongeCommon/issues/1353
