### ISSUE TITLE
Fix no permission message

### ISSUE THREAD

**Issue by MoeBoy76** [SpongePowered/SpongeAPI#2048]
after https://github.com/SpongePowered/SpongeAPI/commit/b38390e1751fff802d355155c45b2eb4913f5817 when a player hasn't got permission they get a message saying the command doesn't exist, this is very frustrating when attempting to set up a new server/plugin as it appears that the plugin isn't loaded when you just don't have permission for the command(s)

**Comment by dualspiral** [comment]
I was discussing this with someone on the Nucleus Discord as to what the change was intended to do, message reproduced below.

I'll take this on over the next couple of days when I get a moment, I know how I want to fix this in a simple way, at least in the short term - mentioned below.

---

For background - that commit comes from this PR - https://github.com/SpongePowered/SpongeAPI/pull/2038. The idea was that it would prevent the commands appearing in /help and though tab completion - before this commit this was happening. This is something that a lot of people have been asking for and so makes sense. That method basically returns the command if the source should be able to use it - and is used during execution too. 

A solution would be to pass in `null` as the source during execution, it would then suppress tab completion and usage in /help, but allow for it to be executed if desired. Could use a config option too.
