### ISSUE TITLE
Despite block transactions from ChangeBlockEvent.Break are set invalid, they still drop the respective items while not breaking

### ISSUE THREAD

**Issue by eirikh1996** [SpongePowered/SpongeAPI#2090]
Hello. I am struggling with a problem with Block transactions from ChangedBlockEvent.Break. I set the transactions to not be valid to prevent the blocks from breaking. However, despite not breaking, the blocks affected by the transactions being set not valid, they still drop their respective items.

This also happens on 7.1.10

**Comment by Zidane** [comment]
This is not an API issue, please open this issue on the respective implementation.
