### ISSUE TITLE
Event to alter block blast resistance during explosion calculations

### ISSUE THREAD

**Issue by Pulverizer** [SpongePowered/SpongeAPI#2093]
This is a feature that I intend to make use of and would like to open a PR in the future.
However, I am not sure what would be the best way to implement this feature.

**Comment by dualspiral** [comment]
How would you make use of it? What would it do? We need to know a lot more about your use case before we can start to formulate an idea as to how to help you best.

**Comment by Pulverizer** [comment]
Changing the blast resistance of a block by a percentage based on the current size of the structure containing it.

**Comment by Pulverizer** [comment]
I intend to work on implementing this over the next few weeks so I would appreciate some advice on how and where this feature should be implemented in the code.

To ensure that I have explained my use case as best as possible I'll just run through it again;
1. An explosion is triggered.
2. Explosion code fetches the blast resistance of blocks to determine if they should be broken.
3. The new event intercepts the value before it is used and posts an event containing the block location, block type and the retrieved value.
4. My plugin uses the provided information to calculate a new value and provides it to the event.
5. The event finishes getting passed around and the new value is returned to the Explosion code.

**Comment by dualspiral** [comment]
From discussion on the PR, this is not something we wish to offer in the API, I am therefore closing this.
