### ISSUE TITLE
Error trying to get a datasource

### ISSUE THREAD

**Issue by TPNils** [SpongePowered/SpongeAPI#2113]
Hi,

I am encountering an issue to authenticate with a mysql server with the following error: https://pastebin.com/cmFbG2gj

Code:
```java
// The first line errors
DataSource dataSource = this.sqlService.getDataSource(String.format("jdbc:mysql://%s:%s/%s", this.host, this.port, this.databaseName));
// Code does not reach this line
Connection connection = dataSource.getConnection(this.user, this.password);
```

The issue to me seems that the authentication tries to happen before the user & password can be given.
I can get it to work with a mysql dependancy and using `DriverManager.getConnection(url, user, password)` but I would prefer to use the sponge solution if possible.

I am currently running **spongeforge-1.12.2-2838-7.2.0**

**Comment by ST-DDT** [comment]
As stated in the [javadocs](https://jd.spongepowered.org/7.2.0/org/spongepowered/api/service/sql/SqlService.html#getDataSource-java.lang.Object-java.lang.String-):

> A jdbc connection url is expected to be of the form: `jdbc:<engine>://[<username>[:<password>]@]**<host>/<database>` or an alias (available aliases are known only by the service provider)

Especially the `<username>[:<password>]@` part.

**Comment by TPNils** [comment]
Thanks for the help, that did solve the issue.
A question for my curiousity, is there a reason to call `DataSource.getConnection(user, password);`?

**Comment by ST-DDT** [comment]
That's a plain java class/interface. I don't know the exact purpose of it (because I don't remember ever calling it), but it might be a helper method for creating a connection with a different user for a privileged call. E.g. the normal user only has read access, but for a special action the applications switches to a different user and executes it.

**Comment by TPNils** [comment]
Alright, thank for the help :)

**Comment by XakepSDK** [comment]
Use `getConnectionUrlFromAlias`, so admins could control URL instead of hardcoded URL in plugin
