### ISSUE TITLE
Upgrade Guice to version 4.2.3

### ISSUE THREAD

**Issue by windy1** [SpongePowered/SpongeAPI#2122]
This will allow developers to utilize new features, namely `OptionalBinder`, which is really nice. <3

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/2182

We had to revert this for the reasons in that PR. We won't be updating until Mojang updates the version of Guava they use internally.

My apoligies, we should have realised this sooner.
