### ISSUE TITLE
Add flags to commands (again)

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/SpongeAPI#2157]
With the new command system and how Brig does client completions, we should be able to support "anchor flags", that is, flags at the beginning of a subcommand.

So, if we have the command `/foo <bar> <baz>`, we should be able to do `/foo -f <> --flag <> <bar> <baz>` I don't think it would be easy to do it anywhere in the command string without it getting messy and inflating the packet size.

**Comment by ImMorpheus** [comment]
PR merged
