### ISSUE TITLE
Configurate 4

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeAPI#2175]
Configurate is at the point where all the *essential* changes for v4 have made it in, but there are still a few very useful features I'd like to add -- check the Configurate issue tracker for an idea of what the roadmap looks like.

As soon as the Configurate 3.7 PR is merged into SpongeCommon-8, I'll get PRs going preparing the update to Configurate 4. My goal is that when we want to lock down the API, it's just a matter of spinning off a release and hitting the merge button on the API and Common PRs to get everything ready.

# API Questions

- Configurate is moving to [Geantyref's](https://github.com/leangen/geantyref) `TypeToken` and other reflection utilities over Guava. Does SpongeAPI want to follow for the places it refers to parameterized types?
- Since TypeSerializer collections are becoming immutable, Sponge will no longer be able to contribute to the global collection. Somewhere in the API there should be a place (beside Guice) to access this TypeSerializerCollection. Where makes sense? On `Game`?

# Implementation Questions

- How do people feel about [AutoValue](https://github.com/google/auto/tree/master/value), or something auto-value like to generate implementations for object-mapped configurations? I'd like to use some nice immutable data objects for SpongeCommon's config :)
- Is DFU compatibility interesting at all? It could maybe replace some of the `DataTranslator`s for other formats, and as we get into newer MC versions would make it super easy to connect Vanilla serialization with Sponge's data structures. However, Sponge's DataContainer's design doesn't really lend itself to working well with DynamicOps so this would want a more in-depth design discussion.

**Comment by ImMorpheus** [comment]
@zml2008 what's the status of this ? I see the [configurate 4 PR](https://github.com/SpongePowered/SpongeAPI/pull/2193) has been merged and the API is using geantyref now.

**Comment by zml2008** [comment]
ah yeah, this has been completed
