### ISSUE TITLE
KickPlayerEvent does not register kick due to spam and is not cancellable 

### ISSUE THREAD

**Issue by codestripper** [SpongePowered/SpongeAPI#2178]
**I am currently running**
- SpongeForge version: .12.2-2838-7.2.4-RC4054
- Java version: 1.8.0_251-b08
- Operating System: Windows 10

**Issue Description**
KickPlayerEvent does not register a player being kicked for spamming chat, and is not cancellable. I believe it should be cancellable to allow certain players the ability to bypass being kicked for various reasons.

One such example would be to prevent certain users from being kicked due to chat spamming. As it stands this does not seem possible to do.

```
    @Listener
    public void onPlayerKick(KickPlayerEvent event) {
        plugin.getLogger().info("Player kicked");
    }
```

**Comment by dualspiral** [comment]
`KickPlayerEvent` just isn't fired.

There are a couple of issues here:

* If this event was cancelled, the `Player#kick` event returns a `void` so there is no way for a user of this event to know if the kick was successful. We'll need to introduce a new method.
* The event *MessageChannel methods (from `MessageChannelEvent`) shouldn't exist, really. What use is a message channel on an event that sends a message to a disconnected client?

This can all be fixed properly in API 8, however there are challenges for API 7. We'd like to add this in 7.3, but we do need to consider how we work around the problems above - I'm noting them here so I can get some feedback from a couple of others.

**Comment by ImMorpheus** [comment]
PR merged
