### ISSUE TITLE
Add CompletableFutures to BanService

### ISSUE THREAD

**Issue by A248** [SpongePowered/SpongeAPI#2186]
The current `BanService` interface effectively requires all bans to be loaded in memory. While this is appropriate for the vanilla implementation in SpongeCommon ([SpongeBanService](https://github.com/SpongePowered/SpongeCommon/tree/stable-7/src/main/java/org/spongepowered/common/service/ban)) it does not match the behaviour of more elaborate plugins which store punishments in a backend requiring IO operations, such as a MySQL database. Should a ban's plugin receive an API request, would it need to perform a database call on the main thread?

I'm wondering whether the Sponge team would be open to revising the *BanService* interface to return `CompletableFuture`s of its current return types, as was similarly done for `PermissionService` per #1524 .

Should this be undertaken, it would be necessary to change some of the assumptions underlying the *BanService*. The [documentation](https://docs.spongepowered.org/stable/en/plugin/bans.html) suggests checking `isBanned` before calling `getBanFor`, but not only would this lead to 2 database queries, it is liable to race conditions. Accordingly, using *getBanFor* and checking if the returned Optional is present is more proper.

With this in mind, the use cases of `isBanned` dwindle to only determining whether a profile or address is banned without caring in the slightest for the `Ban` itself. Combined with the immense potential for abuse of *isBanned*, it should rather be scrapped entirely in favour of the presence of the *getBanFor* Optional. If it is worried amateur developers may call *getBanFor* twice, the documentation should emphasise the circumstances; if it is still worried, method names could even be changed to *findBanFor* to further hammer the point that such method is not necessarily a simple getter. The objective is to avoid wasteful API calls.

**Comment by Cybermaxke** [comment]
I've noticed as well that the `BanService` should use `CompletableFuture`s, and also the `WhitelistService.` Up to now I just never got around making a PR for it yet.

**Comment by jamierocks** [comment]
I'm not convinced that GH-2307 actually resolves this issue, as I've put on that pull request.

To reiterate:
1. A compeling case to remove `isBanned` was made here.
2. Its important that documentation is updated to reflect this change, as it changes greatly the semantics of many things. This was detailed well by @A248 here.

**Comment by ImMorpheus** [comment]
>     1. A compeling case to remove `isBanned` was made here.

Agreed. I've opened a new PR.

>     2\. Its important that documentation is updated to reflect this change, as it changes greatly the semantics of many things. This was detailed well by @A248 here.
I think that comes naturally as a consequence of using CompletableFuture. The same would apply to people calling `getBanFor` before either `addBan` or `pardon`.
Even when not dealing with `CompletableFutures` and possible race conditions, this kind of double lookup is still bad practice with `Map`s (contains + key, contains + remove, etc.).
I'd be tempted to say this is more appropriate for the `bad practice` section of the docs but I'm open to suggestion (hence the `input wanted` label).

**Comment by ImMorpheus** [comment]
PR merged
