### ISSUE TITLE
Missing criteria in scoreboard API

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/SpongeAPI#2187]
Hi!

-  SpongeVanilla version: 1.12.2-7.2.3
-  Java version: 8
-  Operating System: macOS
-  Plugins: only my plugin in development (cosmos)

According to Minecraft Vanilla 1.12.2, there is 1922 different criteria that can be used to define a scoreboard objective.

<img width="513" alt="Capture d’écran 2020-07-22 à 16 10 18" src="https://user-images.githubusercontent.com/25883318/88258998-b6738580-ccc1-11ea-8b26-ad8be36a4efd.png">

However, with Sponge API, I was able to retrieve only 6 + 1879 = 1885 of those criteria.

Indeed, there is 6 basic criteria in org.spongepowered.api.scoreboard.critieria.Criteria : **DEATH**, **DUMMY**, **HEALTH**, **PLAYER_KILLS**, **TOTAL_KILLS** and **TRIGGER**. 

The 1879 others someone helped me to find are avaible by requesting statistics in registry :

`Sponge.getRegistry().getAllOf(Statistic.class)
                .stream()
                .map(Statistic::getCriterion)
                .count())`

After few researches, I found out the 37 missing criteria that are not implemented in Sponge API :

<img width="1262" alt="Capture d’écran 2020-07-22 à 20 37 03" src="https://user-images.githubusercontent.com/25883318/88259315-4ca7ab80-ccc2-11ea-82da-811f1a1726f0.png">

**XP**, **LEVEL**, **FOOD**, **AIR**, **ARMOR**, should be added in org.spongepowered.api.scoreboard.critieria.Criteria in my opinion.

The 32 others I couldn't find in Sponge were those : 

<img width="1227" alt="Capture d’écran 2020-07-22 à 20 36 05" src="https://user-images.githubusercontent.com/25883318/88259401-85478500-ccc2-11ea-8dec-66c00ec48d07.png">

Thank you for reading this issue.

**Comment by ImMorpheus** [comment]
PR merged
