### ISSUE TITLE
Expose subcommands list in Command.Parameterized

### ISSUE THREAD

**Issue by ItsDoot** [SpongePowered/SpongeAPI#2224]
Currently you can only fetch the arguments of a `Command.Parameterized`, but not it's subcommands.

This would help with being able to auto-generate help commands.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/d10c3bb62814ef36039293154ebb14917879eb85

(ignore the fact I originally just posted a link to the API 8 branch...)
