### ISSUE TITLE
Missing locked field in scoreboard API

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/SpongeAPI#2230]
Hi!

    SpongeVanilla version: 1.12.2-7.3.0
    Java version: 8
    Operating System: macOS
    Plugins: only my plugin in development (cosmos)

Just a little ticket to inform that I can't find the Locked field in _org.spongepowered.api.scoreboard.Score_: 

<img width="225" alt="Capture d’écran 2020-09-11 à 19 23 56" src="https://user-images.githubusercontent.com/25883318/92955172-f9054300-f464-11ea-8d5e-1303b5d6572c.png">

This field is used for the /trigger command to enable a non-op player to modify his own score on the selected objective.

<img width="572" alt="Capture d’écran 2020-09-11 à 19 31 46" src="https://user-images.githubusercontent.com/25883318/92955454-703ad700-f465-11ea-9069-ee64543e6a10.png">

Thank you for reading this issue.

**Comment by ImMorpheus** [comment]
PR merged
