### ISSUE TITLE
Add option to set a custom version in the ClientPingServerEvent

### ISSUE THREAD

**Issue by AlexProgrammerDE** [SpongePowered/SpongeAPI#2251]
Ok so i was looking through the API lately and noticed that the option to set a minecraft servers version is missing. Doing this would allow us as an example to let the client think he is outdated and so always displaying the current minecraft version. And also setting a custom version name for the client to display. (This can be even coloured instead of the default red colour). 

Here is an example, which did make use of this functionality of minecraft: 
![](https://cloud.githubusercontent.com/assets/3035868/3996172/3cc81590-2932-11e4-800b-eb9be0b87890.png)

I hope this feature can get added to this awesome API. 

You can by the way already get the version that is sent, but not edit it yet:
https://github.com/SpongePowered/SpongeAPI/blob/66629378af29e796271ec09ef4b18ca46e8300ef/src/main/java/org/spongepowered/api/network/status/StatusClient.java#L50 

Useful links for devs:
https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/event/server/ClientPingServerEvent.java
https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/network/status/StatusClient.java

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/pull/2456
