### ISSUE TITLE
Rethink PlayerChatRouter

### ISSUE THREAD

**Issue by dualspiral** [SpongePowered/SpongeAPI#2259]
I'm putting it here because I don't have a single solution to this right now, but we _need_ to think about this, when I posted it in Discord a few days ago it got lost amongst the noise.

Basically - the notion of the `PlayerChatRouter` is a step back in our chat event based on what we have in API 7 and I think we need to properly address it.

## API 7 - Message Channels

In API 7 we have the notion of a message channel. They are a bit of a mess and have caused all sorts of compatibility issues. For example in Nucleus 1, I used Message Channels for things like staff chat, because they have the benefit of formatting chat as well as specifying who a message goes to. However, they very quickly got messy.

### Message Channels could only be used one at a time

A lot of users who used Nucleus at the time also used a plugin called Boop, which _also_ used message channels for their per player formatting functionality. It very quickly became apparent that there was no good way to chain message channels together on the formatting side.

### Message Channels hid the final form of a chat message

Another issue, particularly for protection plugins, is that while the chat event could alter a chat message, the message you were manipulating was, in fact, **not** the final message that would be sent to a player. This was necessarily the case because a message channel could customise the message for each player! However, there was no way for a plugin to inspect this, all a message channel could do was send the message - no event would be fired so the final message is shrouded in mystery.

For these reasons, I stopped using message channels in Nucleus as much as possible for formatting - both Boop and GriefDefender were having massive issues integrating with Nucleus because of these issues and I did not want the reduction in compatibility.

## API 8 - PlayerChatRouter

`PlayerChatRouter` inherits these problems, plus one more:

### PlayerChatRouters do not let plugins inspect which `Audience`s a message is going to

While Minecraft 1.16.4 is including the notion of ignoring player chat, 1.15.2 doesn't have this. This is a big issue for protection plugins and chat management plugins who want to know who a message is getting sent to and thus want to block or modify the chat destination outright, but not necessarily change the other formatting - again, think of something that has chat channels, and a plugin that highlights player names for a specific player. The `PlayerChatRouter` can only be used by one plugin at a time - if one plugin just wants to alter the destination audiences and another the formatting, you're stuck. At least with `MessageChannel`s you could chain them to that degree.

---

With this in mind, I think we need to either ditch or severely rework the notion of the chat router. Either:

* We create another event which fires on `ServerPlayer#sendMessage(sender, message, MessageType.CHAT)` that plugins can intercept with the finished chat result, that can then be cancelled. This could get spammy for larger servers, however.
* We split the router into two: chat targeting (collection of audiences?) and chat formatting ((sender, target, message) -> Optional.of(message)), such that they can play nicely together (chaining the formatting would be easier, plugins can see where their messages are going).

Thoughts?

**Comment by ryantheleach** [comment]
> We split the router into two: chat targeting (collection of audiences?) and chat formatting ((sender, target, message) -> Optional.of(message)), such that they can play nicely together (chaining the formatting would be easier, plugins can see where their messages are going).

Seems the (more difficult) but cleaner option. +1 to including both the target and the sender for formatting. Some care should be taken to make sure that messages sent are correctly routed to the correct 'channel' system or chat, for players who mute all chat.

**Comment by ejm** [comment]
This feels related but if it should be spun off into a new issue, let me know please!

One part of chat routing and formatting which is frustrating in API7 is that while `MessageEvent.MessageFormatter` exists, during parts of the event lifecycle the header will be merged into the body, making it difficult to separately format the player name and the message.

It would be nice, if, maybe in `MessageEvent.Chat` or somewhere else along the chat routing change, it was possible to independently format the player name and the message depending on the recipient. Other `MessageEvent`s don't need that of course, but for `Chat` it feels worthwhile.

**Comment by Wolfizen** [comment]
I personally think we should leverage the Event system to handle this. Why?
* Events are used by every plugin, devs are already familiar with how they work.
* Events already support ordering between plugins.
* Easy support for observers to see the final messages being sent.
* Plugins could edit whatever parts they needed - audience, message format, etc. through a single Event object.

For supporting formatting of messages to specific players, perhaps there could be two events - an incoming and an outgoing event. The incoming event would be our well known friend PlayerChatEvent, and the outgoing event would be a new one that happens after the incoming event finishes. The outgoing event would fire for each player/audience-like receiving the message. The incoming event sets the audience, and the outgoing events are fired for each final member of that audience.

The above would also allow plugins to catch and modify direct calls to Player#sendMessage, which would fire an outgoing event only.

**Comment by dualspiral** [comment]
@ejm I'd argue that it's a semi-different issue to this, but it comes with its own challenges as it is:

> One part of chat routing and formatting which is frustrating in API7 is that while MessageEvent.MessageFormatter exists, during parts of the event lifecycle the header will be merged into the body, making it difficult to separately format the player name and the message.

That's more down to mods and plugins than anything else. The notion of a message formatter is entirely a Sponge construct and it's Sponge that does this splitting. If a mod alters the message in the chat event, then it all gets merged into the body because we don't know what should be in the header and what should be in the body. Plugins that also just set the message without considering the formatter also ended up causing this.

If we only stuck with SV, that's not really an issue, but with us wanting to rebuild SpongeForge, this problem is just going to reoccur.

The goal of such a formatter is noble, but if mods come into play I'd argue that hacing such a construct is always going to suffer from this.

**Comment by ejm** [comment]
Yeah, I had a feeling SF (or other implementations) may be a problem, fair enough.

I guess we'll (plugin devs) just have to do some naive splitting and hope for the best. Thanks!

**Comment by dualspiral** [comment]
Anyone who has an interest in this, please take a look at https://github.com/SpongePowered/SpongeAPI/pull/2340 and note any thoughts or concerns on that, thanks!
