### ISSUE TITLE
Re-add API for async chunk loading/generation

### ISSUE THREAD

**Issue by pop4959** [SpongePowered/SpongeAPI#2287]
API 7 has the World#loadChunkAsync method which appears to have been removed in API 8: https://jd.spongepowered.org/7.3.0/org/spongepowered/api/world/World.html#loadChunkAsync-com.flowpowered.math.vector.Vector3i-boolean-

As I understand it, the reason why this API was removed was because SV/SF 1.12.2 did not support the implementation of asynchronous chunk loading. However, in more recent versions of the game (such as 1.15/1.16, which API 8 targets), it is supported in the vanilla server.

Because of this, I think it would be a good idea to consider re-adding it.

**Comment by Zidane** [comment]
This is removed because we do not support artificially loading chunks anymore, this needs to be done via tickets (dual has a branch for this).

https://github.com/SpongePowered/SpongeAPI/pull/2272

https://github.com/SpongePowered/SpongeAPI/pull/2274

**Comment by Zidane** [comment]
Feel free to comment on those PRs further, would really help him.

**Comment by pop4959** [comment]
Thank you
