### ISSUE TITLE
Inherite from default parameters in a more restrictive way

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/SpongeAPI#2290]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 3753b5e3630bb22f25402d1f8452f7eb8afb7ce2
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey, 

In the API-7, we had the possibility to extend GenericArguments to build our custom ones. Now it is no more possible because default parameters are exposed as static variables instead.

So my problem is: 

I want to build a ValueParameter that has the same behavior of a `ResourceKeyedValueParameters.MANY_ENTITIES`, but with these following restrictions:

- I want that `getValue` / `complete` only accepts entities from a specific world.
- I want this ValueParameter to be typed as `List<Component>` and not `List<Entity>` (uuids for entities and names for players) 

So I decided to build something like that, which is a poor workaround of inheritance :
 

```java
public class Test implements ValueParameter<List<Component>> {

    private final ValueParameter<List<Entity>> entitiesValueParameter;

    public Test() {
        this.entitiesValueParameter = ResourceKeyedValueParameters.MANY_ENTITIES.get();
    }

    @Override
    public Optional<? extends List<Component>> getValue(Parameter.Key<? super List<Component>> parameterKey, ArgumentReader.Mutable reader, CommandContext.Builder context) throws ArgumentParseException {
        return entitiesValueParameter.getValue(parameterKey, reader, context);
    }

    @Override
    public List<ClientCompletionType> getClientCompletionType() {
        return entitiesValueParameter.getClientCompletionType();
    }


    @Override
    public List<String> complete(CommandContext context, String currentInput) {
        return entitiesValueParameter.complete(context, currentInput);
    }
    
}
```

This does not work for many reasons :

- When using `entitiesValueParameter.getValue`, it expects to have a `Parameter.Key<? super List<Entity>>` for the first parameter but my ValueParameter is typed as `ValueParameter<List<Component>>` so I can't provide the required key.
Even if I manage to create a "fake" `List<Entity>` parameter key, this one will never be filled with any input.

- When using `entitiesValueParameter.complete`, I do not have a `List<Entity>` but a `List<String>` so I can't restrict to a specific world

- `entitiesValueParameter.getClientCompletionType()` is empty (but this is **[another issue](https://github.com/SpongePowered/Sponge/issues/3270)**)

Is there any way for me to achieve my goal ? 
I feel so restricted by what I can do now with parameters, comparing what we could do in API-7.

Thanks for reading this issue.

**Comment by thibaulthenry** [comment]
If I understand, you would implement some a ways to map or filter ?


```java
ResourceKeyedValueParameters.MANY_ENTITIES.get()
     .filter(entity -> onDesiredWorld(entity)
     .map(entity -> uuid or name)
```

**Comment by dualspiral** [comment]
Almost. It would basically be a method that would accept a modified `ValueParser` and a `ValueCompleter` that have an additional parameter - the result returned from the parser/completer. It would be on the `Parameter.builder()` chain.

**Comment by thibaulthenry** [comment]
That would be a good solution for this problem I think

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/660b7a40411d209546086cf839bbb508935c3cbc basically solves this for what you're wanting to do (had to do something a little different, basically look at `ValueParameterModifier`) - but please ensure you read the JDs carefully before using it, there are some caveats...
