### ISSUE TITLE
[API-8]Will API8 support java11? 1.17 seems to be mandatory to use java11

### ISSUE THREAD

**Issue by Hikari0964** [SpongePowered/SpongeAPI#2328]

**Comment by Hikari0964** [comment]
Maybe my question will be abrupt, but it is inevitable.

**Comment by zml2008** [comment]
SpongeVanilla supports Java 8 through 16 at the moment, and is expected to continue to support the latest.

However, this issue tracker is not a support forum -- feel free to come to our discord at https://discord.gg/sponge for more information.

**Comment by Hikari0964** [comment]
thanks!
