### ISSUE TITLE
Document check style setup in Contributing

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#2339]
File -> Settings -> Tools -> Checkstyle

Add a new `Configuration File`

![2020-12-01-211147_502x403_scrot](https://user-images.githubusercontent.com/24737505/100792501-035b2b80-341b-11eb-84e8-bd70acd68682.png)

It will ask you about the properties defined in the config:
set the suppressions.xml

![2020-12-01-211223_505x412_scrot](https://user-images.githubusercontent.com/24737505/100792504-03f3c200-341b-11eb-88d1-40ec3e7e1808.png)

Open a SpongeAPI class

Go in the CheckStyle tab, make sure you are using the `Sponge` rules and run `check module`

![2020-12-01-212207_520x210_scrot](https://user-images.githubusercontent.com/24737505/100792758-6cdb3a00-341b-11eb-9106-0f263f1f0993.png)

Note: the suppressions rules may not be updated

_Originally posted by @ImMorpheus in https://github.com/SpongePowered/SpongeAPI/pull/2237#issuecomment-736797213_

**Comment by ImMorpheus** [comment]
That's probably outdated, see https://github.com/SpongePowered/SpongeAPI/commit/305d9d5fa22ea1eed13657a2118ad4f8ae320217

**Comment by ImMorpheus** [comment]
This is not needed anymore, there is a checkstyle task now

**Comment by zml2008** [comment]
This is still probably worthehile at some level just for the real time feedback, but it doesn't have to be in depth at all
