### ISSUE TITLE
Sponge for newer Minecraft versions

### ISSUE THREAD

**Issue by Minionguyjpro** [SpongePowered/SpongeAPI#2373]
Can you please make Sponge also available for newer Minecraft versions?
Like 1.16 and 1.17.
And 1.17 now uses JDK 16.

**Comment by abstraq** [comment]
Already in progress, follow the forums to stay up to date https://forums.spongepowered.org/t/status-update-9th-june-2021-api-8-soft-freeze-and-spongevanilla-1-17-day-1-experimental-builds/39368

**Comment by Minionguyjpro** [comment]
Niceeee

**Comment by Minionguyjpro** [comment]
Is it also an high performance fork?

**Comment by dualspiral** [comment]
Github is not for questions - and as noted, our answers are already on the forums.
