### ISSUE TITLE
Correct Behavior of Keys.CUSTOM_NAME/DISPLAY_NAME in Javadocs

### ISSUE THREAD

**Issue by WillBAnders** [SpongePowered/SpongeAPI#2388]
In API 8, `Keys.CUSTOM_NAME` must be used for the display name of an `ItemStack` instead of `Keys.DISPLAY_NAME` (which currently seems to be a no-op) as in API 7. The Javadocs for these are below, which do not seem to match the current behavior.

https://github.com/SpongePowered/SpongeAPI/blob/111f9a4c35bf329f9aa9be9f2c2b92b65839dfa4/src/main/java/org/spongepowered/api/data/Keys.java#L625-L628

https://github.com/SpongePowered/SpongeAPI/blob/111f9a4c35bf329f9aa9be9f2c2b92b65839dfa4/src/main/java/org/spongepowered/api/data/Keys.java#L678-L684

A few questions:

 1. What is the intended behavior of these two keys?
 2. What motivation the change in behavior from API 7?
 3. Is there a way to draw attention to this change? It seems like a mistake a lot of developers would make.
      - If `Keys.DISPLAY_NAME` is computed for `Entity`s and is currently a no-op for `ItemStack`, could it made read-only for everything? This way trying to `add`/`offer` it would throw an error, which would help make this change more visible.

**Comment by Faithcaio** [comment]
I updated the javadocs. Hope its clearer now

 > What motivation the change in behavior from API 7?
 - In API7 you could not differentiate between the default `DISPLAY_NAME` and a custom one.
 - Offering a custom `DISPLAY_NAME` would not yield the same `DISPLAY_NAME` back because vanilla adds some decorations around it. 

As such `DISPLAY_NAME` is always readonly in API8. To modify it offer a `CUSTOM_NAME`.
`offer` will return a failed `DataTransactionResult` but not throw an error for `DISPLAY_NAME`

**Comment by WillBAnders** [comment]
It's likely a breaking change, but is there a reason it can't throw an exception instead? It's not just that the transaction failed, but there's no opportunity for there to be a transaction because the key cannot be offered. Are there other keys that do this, and is it feasible to have a separate interface for this distinction?

In particular, I was using `ItemStackBuilder.add(Key, Object)` for this, which doesn't give access to the result anyways. Perhaps for this case it should throw an exception if the transaction fails, or have some other approach if necessary?

**Comment by dualspiral** [comment]
> It's likely a breaking change, but is there a reason it can't throw an exception instead? It's not just that the transaction failed, but there's no opportunity for there to be a transaction because the key cannot be offered. 

It's not an exceptional condition though - it's a fundamental expectation of the Data API that offering data may fail, and the return type can encompass that. Thus, it should not throw an exception, you absolutely should be checking to see what the result is.

You may want to inspect `DataTransactionResult#type()` if you want a little more information on the failure (see [`DataTransactionResult.Type`](https://jd.spongepowered.org/spongeapi/8.0.0-SNAPSHOT/org/spongepowered/api/data/DataTransactionResult.Type.html). 

> In particular, I was using ItemStackBuilder.add(Key, Object) for this, which doesn't give access to the result anyways. Perhaps for this case it should throw an exception if the transaction fails, or have some other approach if necessary?

That's potentially worth looking at - though I guess that the values aren't applied at that point, but rather at build time, or perhaps specifying the behaviour when an invalid value is applied in the builder itself. I'd suggest opening another issue for that though -- it's more general than this key itself.
