### ISSUE TITLE
[API-8] Custom built enchantment inventory

### ISSUE THREAD

**Issue by Lunoro** [SpongePowered/SpongeAPI#2397]
function for building enchantment inventorys up to level 30

**Comment by Faithcaio** [comment]
Internally vanilla and forge look for blocks surrounding the enchantment table block summing it up to a power level (see `EnchantItemEvent.CalculateLevelRequirement#power()`) which is then used to calculate the actual enchantment levels.
After trying out a few options, I could not find any solution resulting in a satisfying API.

You can listen to `EnchantItemEvent.CalculateLevelRequirement` to override the level requirement when it gets calculated.
