### ISSUE TITLE
[API 8] Replace List with Set

### ISSUE THREAD

**Issue by sunmisc** [SpongePowered/SpongeAPI#2399]
_org.spongepowered.api.service.permission.SubjectData_
**Parents** method use List, but isn't it better to use _Set_:
1) We won't need to take care of duplicates
2) We will have much faster search/insert and remove

**Comment by zml2008** [comment]
no, order matters

**Comment by sunmisc** [comment]
> нет, вопросы заказа

you can take LinkedHashMap and wrap it in java.util.Collections.newSetFromMap()
Yes, well, it's inconvenient, but you can come up with a solution much more convenient and faster List

**Comment by sunmisc** [comment]
> > 
> 
> you can take LinkedHashMap and wrap it in java.util.Collections.newSetFromMap() Yes, well, it's inconvenient, but you can come up with a solution much more convenient and faster List

You can also take TreeSet and a lot of other options are much better than List
