### ISSUE TITLE
'mergeMetadata' has redundant getters: 'getMergeMetadata()' and 'isMergeMetadata()'

### ISSUE THREAD

**Issue by Jurredr** [SpongePowered/SpongeAPI#2402]
When trying to build a Sponge project with Java 16, Gradle, and the SpongeAPI, I seem to be getting the following build error:

```
Some problems were found with the configuration of task ':generateMetadata' (type 'GenerateMetadata').
  - In plugin 'org.spongepowered.gradle.meta.MetadataBasePlugin' type 'org.spongepowered.gradle.meta.GenerateMetadata' property 'mergeMetadata' has redundant getters: 'getMergeMetadata()' and 'isMergeMetadata()'.
```

Went back to try it on Java 11 and 13 and the exact same plugin builds fine. Not sure if I'm doing something stupid here, but this seems like a bug.

**Comment by tyhdefu** [comment]
I am also experiencing this issue after changing my gradle configuration and trying to build my plugin
I am running gradle 7.3, with kotlin build.gradle script with spongegradle version 0.8.1 and 0.9.0
I am also running:
- ForgeGradle 5
- MixinGradle
(Perhaps the reason you experienced the issue when running an ewer version of java
My build.gradle.kts and the resulting error
https://gist.github.com/tyhdefu/476b4b3d9b19ef0d82a71e77e375fe91

**Comment by zml2008** [comment]
legacy SpongeGradle is no longer supported, only 2.0.0 for API 8+. if you want to target API 7 while using a newer gradle version, just use the annotation processor in SpongeAPI to generate your mcmod.info and skip SpongeGradle entirely.
