### ISSUE TITLE
automatic parameterized registration of plugin derived permission sets

### ISSUE THREAD

**Issue by PaxJaromeMalues** [SpongePowered/SpongeAPI#2427]
### Major SpongeAPI version

1.12.2 7.4.7 + if possible
otherwise 8+

### Is this likely to be a breaking change?

I don't know

### What are you requesting?

Currently, the only way to get a (semi) complete list of permissions is to create a dummy user and assign all available permissions to it manually or running `lp tree` (in case of luckperms) after the server has been up for a long time.

It would be nice if (maybe also for API7.4) a functionality could be introduced, that automatically fetches all non argument based permission nodes and make them available as a list-file, callrequest or dbentry to the server admins.

**Comment by dualspiral** [comment]
`PermissionService#getDescriptions()` already exists, as does the ability to register them: https://jd.spongepowered.org/spongeapi/8.0.0/org/spongepowered/api/service/permission/PermissionService.html#newDescriptionBuilder(org.spongepowered.plugin.PluginContainer). The caveat is that plugins need to actually register their permissions - but ultimately it is up to the plugin devs to register them. They don't have to.

We cannot magically detect all permissions that plugins will use before they use them - so unless you can encourage all plugins to register all their permissions, I'm afraid you're out of luck.
