### ISSUE TITLE
DataTranslator registry

### ISSUE THREAD

**Issue by MrHell228** [SpongePowered/SpongeAPI#2434]
### Is this request specific to one implementation of Sponge?

No

### Sponge Version

1.16.5-36.2.5-8.1.0-RC1153

### What are you requesting?

https://github.com/SpongePowered/SpongeAPI/blob/9684a0ccc22507688626698c80d9c5e5f2a6ceda/src/main/java/org/spongepowered/api/data/DataManager.java#L159
DataManager needs a way to register additional data translators which are returned by that method.
Otherwise a plugin wanting to serialize an object that does not implement DataSerializeable cannot do so

**Comment by Faithcaio** [comment]
Found out why this is:

`DataManager#registerTranslator` was deprecated in API7 recommending to use `GameRegistryEvent.Register<DataTranslator<?>>`

But in API8 `DataTranslator` is no longer a `RegistryType` and as such we have no registration anymore :(
