### ISSUE TITLE
Compile API 9 in Java 8

### ISSUE THREAD

**Issue by amnoah** [SpongePowered/SpongeAPI#2439]
### Major SpongeAPI version

9.0.0

### Is this likely to be a breaking change?

No

### What are you requesting?

Hi there, I've been redirected to report this issue here from the Discord server.

I recently attempted to include Sponge compatibility within a plugin of mine, but I found that the API 9 dependency available on the Maven repository has been compiled with Java 17.

Compile log: https://pastebin.com/G9fBENBn
My pom.xml for the module: https://pastebin.com/CF8MXuGF

Unless things have changed, in which case you should update the text stating that Java 8 is required for the API and Java 16 is recommended for development in the ReadMe, then this doesn't seem right.

**Comment by A248** [comment]
SpongeAPI 9 requires Java 17 -- I've added the outdated text to the minor issues list for you. So, this issue can be closed.
