### ISSUE TITLE
[Suggestion] List of all generated chunks

### ISSUE THREAD

**Issue by El-minadero** [SpongePowered/SpongeAPI#256]
A plugin that I developed for bukkit requires me to create large structures across many chunks. These chunks have to have already been generated (whether they are loaded or not) and devoid of vanilla ores. I've also gotten requests that I make this plugin compatible with already generated worlds. To make doing this easier I request that the following methods be added to the world class:

```java
/*
* Returns whether a particular chunk has already generated structures, 'the layer', and 'decorations' 
* regardless of its load status.
*/
public boolean isGenerated(int x, int z)

/*
* Returns a List of all the chunk coordinates that have already been 'decorated' regardless of load 
* status. The list is a snapshot of the world as it was when the method was called. String can be 
* replaced by other objects more suited to coordinate retrieval, but otherwise only contain the x & z 
* coordinate data of the chunks within the world. 
*/
public List<String> getWorldChunkList()
```
Edit: clarified what I meant by 'generated' .@gratimax pointed out that during chunk generation structures are generated first, then the 'layer' (terrain landforms), and then 'decorators'.

**Comment by gabizou** [comment]
@SpongePowered/developers I believe this issue has been discussed well enough and a proper addition to the API was made with #272, specifically with [`ChunkIterator`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/storage/ChunkIterator.java#L45).

Correct me if I'm wrong.

**Comment by modwizcode** [comment]
This PR has morphed significantly from it's initial conception. Also @gabizou `ChunkIterator` doesn't include support for the data only asynchronous iterator. Similarly it's not asynchronous and there isn't an asynchronous read-only option.

**Comment by gabizou** [comment]
> Similarly it's not asynchronous and there isn't an asynchronous read-only option.

Why is it not asynchronous? What prevents the data from being read asynchronously? Constructing a `DataView` of chunk data has no relation to the actual server thread, let alone needing to really *utilize* the main thread. Granted calling the iterator while on the main thread *will* hold up the main thread to read the data, it still is perfectly viable to read the data from an asynchronous thread. The `DataView` is specifically not an instance of the data that is live for this very purpose.

Unless I'm misunderstanding this completely, the `ChunkIterator` can be used asynchronously for all intents and purposes related to *reading* data. Writing data is an entirely different story.

**Comment by modwizcode** [comment]
However the API doesn't specify an asynchronous relationship, which is different than being possibly asynchronous. The specifications are similar to asynchronous conditions, but not guaranteed asynchronous.

**Comment by gabizou** [comment]
@modwizcode I've changed up the nature of `ChunkIterator` in #420, It aims to achieve much of what this issue has requested.

**Comment by gratimax** [comment]
Now that #420 has merged(with added asynchronicity), I think I'll close this.

**Comment by DraksterAU** [comment]
Does anyone have a working code example for this? I'm looking to port my plugin across to Sponge and am having trouble dealing with ChunkDataStream... specifically how to get back to actually reading attributes of each chunk....
Definitely am missing something as simple as getWorld().getLoadedChunks() haha :)

Sorry for the post on the GitHub, but there doesn't seem to be any examples I can find at all... and this is very different from what I've experienced previously with Forge and Bukkit... add to that I've been doing java just a few months and bingo.... 

For ref, the plugin I am porting is here: https://github.com/draksterau/Regenerator
