### ISSUE TITLE
Make Block a proxy class in the API and move BlockLoc's accessor/mutator methods to Extent

### ISSUE THREAD

**Issue by sk89q** [SpongePowered/SpongeAPI#274]
As previously discussed, we want to:

* Move the block access/mutation methods to `Extent` (`extent.setBlock(coords, blockType)`, etc.)
* Turn `BlockLoc` into a API-side proxy like `Location`
* Do something about `teleport()` on `Extent` making zero sense (we may want to move it to `World`).

This should be done in a branch for further discussion.

**Comment by Zidane** [comment]
@sk89q 

Does your API PR resolve this?
