### ISSUE TITLE
Helper library for creation of CommandCallables

### ISSUE THREAD

**Issue by sk89q** [SpongePowered/SpongeAPI#276]
Currently, one can make a command by extending `CommandCallable`. However, we probably want to provide a helper library to go along with it to make the creation of commands easier.

**Comment by Aaron1011** [comment]
I'd be interested in taking this on.

**Comment by sk89q** [comment]
Someone in in the process in making some changes to the command code at the moment.

**Comment by Zidane** [comment]
Covered in zml's Commands Overhaul PR.

https://github.com/SpongePowered/SpongeAPI/pull/561
