### ISSUE TITLE
Allow per-player world borders

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#282]
This was discussed previously on IRC.

Currently, the World Border API follows Vanilla, in that only one border exists per world.

Allowing a different world border to set for each player, similar to setting a different scoreboard per player in Bukkit, would afford tremendous flexibility to plugins.

Potential use cases
- At the beginning of a match, players are given the same world border as their teammates, preventing interaction with the opposing team for some amount of time.
- Limiting individual players to specific regions, without resorting to teleporting them back when they attempt to leave.

@mbaxter and I agreed that this was technically possible (nothing in the protocol would prevent this).

However, @Kobata was against this, arguing that it would be difficult to implement.

Other ideas:
- Allow per-**entity** world borders. Without this, the problem arises of non-player entities being affected by different world borders.

(I apologize if I got any information wrong regarding the discussion in IRC)

**Comment by Aaron1011** [comment]
I think it's time to revisit this issue.

Mixins have changed significantly since I first brought this up. With injection support, it's much more feasible to accomplish this in the Forge implementation.

**Comment by boformer** [comment]
This feature is related to the following issue: http://issues.spongepowered.org/youtrack/issue/SPONGE-54

**Comment by Aaron1011** [comment]
@Kobata: Any thoughts on this?

**Comment by Kobata** [comment]
*Insert rant about overuse of injections*

(We should be being as non-invasive as possible for update reasons)

**Comment by modwizcode** [comment]
I'll update the Mixins you worry about good api.

**Comment by Aaron1011** [comment]
That's true, but the official implementation is only one of several. As much as possible, we shouldn't let the specific challenges for one particular implementation influence API design (assuming the idea is technically feasible protocol or client wise).

**Comment by Zidane** [comment]
@Kobata 

There is a strong difference between injections and overwrites. Were we just overwriting everything I'd understand your rant.

**Comment by Kobata** [comment]
@Zidane From the perspective of *just* updating MC, I'd put the order of 'ease of updating' source patch [forge/cauldron] -> overwrite -> injection. The first two are very easy to see exactly what changed on both sides, and not amazingly hard to update, if rather much grunt work. Injections on the other hand, while nice for other reasons, are very likely to break in strange ways and require more detailed knowledge on the part of the person updating them.

**Comment by Zidane** [comment]
@Kobata 

Injections are necessary to not break other mods. Your perspective is noted but we've come to terms a while back of the checks and balances of overwriting everything.

**Comment by MattBDev** [comment]
After looking at the World Border code, I understand why Kobata is against this. I feel this would be extremely difficult to implement and cause a decrease in performance due to the checks that will be constantly performed.

**Comment by ryantheleach** [comment]
Would it be possible to just send the effect to the client, and leave plugins to re-implement the actual cancelling of move events / damage events?

This would additionally give them more control.

**Comment by liach** [comment]
Should the world border be for different permission groups or scoreboard teams, so that even entities can have their own world border? The border may be stored in the permission or the scoreboard.

**Comment by gabizou** [comment]
> so that even entities can have their own world border

There's a point at which you must stop thinking whether you can and think about whether you should.

Seriously, this issue is summed up with `Player`s having the ability to have their own rendered `WorldBorder`, since it's perfectly able to control from the server as to what the world border is per player, just no one has written an API for it, nor an implementation.

**Comment by ghost** [comment]
How about the API be something like this (note that this hypothetical API would allow both per-player AND per-world borders):
* `Player`/`Entity` and maybe `World`/`Extent` inheriting from a supposed `Borderable` interface which contains some methods like `getBorder()` returning an `Optional<WorldBorder>` and `setBorder(WorldBorder)`, or a single method called `border()` returning some sort of `BorderData`, both cases would allow both getting and setting the border.
* If not the above, maybe a `getWorldBorder()` in `Player`/`Entity` which returns either a `WorldBorder` or an `Optional<WorldBorder>` (there is already a `getWorldBorder()` method in `World` which could be moved to `Extent`, if possible).
* `ChangeBorderEvent` to allow plugins to track the change of the world border. It would contain a `getPreviousBorder()` for the border that is in use (and is being replaced) and `getNewBorder()` for the border that is going to be used. It could have `Player`/`Entity` and `World`/`Extent` sub-events, which are fired depending on which border was changed.
