### ISSUE TITLE
broadcastMessage() Overloads

### ISSUE THREAD

**Issue by Soren025** [SpongePowered/SpongeAPI#287]
If I am not mistaken ```Game.broadcastMessage()``` just sends a message to every online player along with the console. So wouldn't it make sense to give it the same overload functionality as ```Player.sendMessage()```?

**Comment by Bammerbom** [comment]
I think the best is to have both a sendMessage for String, and Message

**Comment by Sannholm** [comment]
I agree with Zidane and think there should only be a sendMessage for Messages. And people can make their own helper methods for Strings, if they need to.

**Comment by gratimax** [comment]
Closing in favor of #425
