### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by gratimax** [SpongePowered/SpongeAPI#295]
The Sponge API is in need of maps. A potential map API would most likely look very similar to [bukkit](http://jd.bukkit.org/rb/apidocs/org/bukkit/map/package-summary.html)'s map API, although any improvements are welcome.

Some things to consider:
- How coupled is this to NBT/persistence? See the [map format](http://minecraft.gamepedia.com/Map_Item_Format). We may need to wait on persistence and then write map data as a persistence class.

**Comment by modwizcode** [comment]
Implemented by https://github.com/SpongePowered/SpongeAPI/pull/531
