### ISSUE TITLE
Player Disconnecting/Bans

### ISSUE THREAD

**Issue by gratimax** [SpongePowered/SpongeAPI#302]
This was brought up in https://forums.spongepowered.org/t/sponge-api-disconnecting-a-player-user/5197. Preferably a method to force disconnection of an online player coupled with some sort of ban system is best here, although I think having plain `setBanned` `getBanned` is not enough.

**Comment by hedgehog1029** [comment]
It'd be pretty easy to move the code to a seperate class (package org.spongepowered.api.service.bans exists now) and have a method for getting the bans service. Maybe it could pull data from the vanilla bans file on startup, modify internally, and then write to the vanilla bans file on shutdown.

**Comment by ST-DDT** [comment]
Is there any code implemented for the API yet?
The branch linked above seems outdated.

I like the concept, but you should not enforce any behaviour on a service or implementatio.
Maybe a init and shutdown method for the service is enough. Then the service can do whatever it wants.

**Comment by hedgehog1029** [comment]
hedgehog1029/SpongeAPI@22bb2fd1aa9007185faa97f3b16c93107b807b3d

That's the latest commit to my repo.

**Comment by gratimax** [comment]
Continued in #412
