### ISSUE TITLE
Persistence API with WorldStorage

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#307]
Currently, We have something for representing data from various sources with `DataView` and `DataContainer`. 

In Issue https://github.com/SpongePowered/SpongeAPI/issues/256, we have the request for some `WorldStorage` to get all existing generated chunks.

Loading chunks is a slow process, and certainly, loading ALL existing chunks into memory will likely slow down the JVM for actually loading and then storing massive objects (hint: the JVM will likely run out of memory first).

So, considering getting things like all existing chunks is something storage related, I've considered making the proposal to adding it to Persistence API.

Here's the proposal:

```java
/**
 * A chunk iterator represents a buffer for obtaining chunk data from
 * storage without having to explicitly load into memory all available
 * chunks.
 * <p>This avoid loading all chunks into memory at once, reducing the memory
 * footprint and persistence operations.</p>
 * <p>The chunks are loaded individually in sequence. Strong references to
 * the chunks represented by {@link DataContainer}s should be avoided
 * <strong>AT ALL COSTS</strong>. The data represented is a copy and
 * therefore shouldn't be considered synchronized to live data.</p>
 *
 */
public interface ChunkIterator extends Iterator<DataContainer> {

    /**
     * Chunks can not be removed by a ChunkIterator.
     *
     * @throws UnsupportedOperationException Not supported at all
     */
    @Override
    void remove() throws UnsupportedOperationException;

}

public interface WorldStorage {

    /**
     * Gets a {@link ChunkIterator}
     * @return
     */
    ChunkIterator getGeneratedChunks();

}


```

Essentially, this would allow getting all available chunks through this `WorldStorage` and a nifty `ChunkIterator` that allows you (the developer) to get all generated chunks according to storage, without having to stress the system of loading all available chunks.

Further additions will be made as the issue is discussed.

Tagging possibly interested parties: @mikeprimm @gratimax @el-minadero @modwizcode

**Comment by Azatik** [comment]
Idea. Add function:
removing Chunk. As if he did not generate.

**Comment by gabizou** [comment]
@SpongePowered/developers I think it is safe to say that since this is already added to the Persistence PR, this issue can be closed.

**Comment by modwizcode** [comment]
Agreed

**Comment by gabizou** [comment]
@modwizcode why is Persistence blocked added to the PR?
