### ISSUE TITLE
Entity persistence flag

### ISSUE THREAD

**Issue by blablubbabc** [SpongePowered/SpongeAPI#308]
Hey,
in the past there were various situations in which I spawn entities temporary in the world via plugins and later remove them again.

It would be useful to add some boolean flag to entities which determines whether or not an entity is going to be saved to disk together with the world data.
Maybe something like:
Entity.isPersistent()
Entity.setPersistent(boolean)

A concrete usecase:
- spawn an entity, remember it's uuid (for identification) and data like spawn location and entity type and plugin specific information
- do stuff when a player comes by and interacts with that entity
- on chunk unloads and plugin disable remove those customly spawned entities again, so that they are no longer in the world if the server owner should decide to no longer use the plugin
- on chunk loads and plugin enable respawn those entities again and store their new uuid

This works fine as long as the server does not crash or gets killed. If the server has saved those entities together with the world data to disk before crashing those entities will still be in the world on the next server restart. Something I originally wanted to prevent.

In the past I worked around this issue by trying to identify and then remove those remaining entities once the server starts up again. This however is/was tricky on craftbukkit because one couldn't be sure when the entity actually was saved to disk. Consider the following concrete scenario:
- plugin spawns entity A and remembers it's uuid
- server saves the world together with entity A
- the plugin for some reason decides to remove entity A
- the plugin decides to respawn the entity: entity B is spawned and it's uuid is remembered (saved)
- the server crashes/gets killed for some reason: no other world save was performed since entity B was spawned
- server starts again with entity A, plugin however has stored uuid of entity B therefore can't identify and remove entity A

NPC plugins usally created their own entity classes which extended minecraft's original entity classes for each entity type they want to support, and which simply don't save those entities to disk by overriding the methods which are responsible for that.

However if no other functionality is needed it would be far easier and cause less trouble to simply have the suggested flag and marking the entity to not be saved.

**Comment by systocrat** [comment]
What happened to this? I can't find any equivalent in 7.1.0

**Comment by gabizou** [comment]
> What happened to this? I can't find any equivalent in 7.1.0

It's available through [Keys](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/data/key/Keys.java#L1554).

**Comment by systocrat** [comment]
> > What happened to this? I can't find any equivalent in 7.1.0
> 
> It's available through [Keys](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/data/key/Keys.java#L1554).

Cheers, thanks
