### ISSUE TITLE
Command Stats / command block support

### ISSUE THREAD

**Issue by Kobata** [SpongePowered/SpongeAPI#326]
Much of the command block 'scripting' ability comes from the command stats concept.

There are five of these in vanilla, `SuccessCount`, `AffectedBlocks`, `AffectedEntities`, `AffectedItems`, and `QueryResult`. Of these, `SuccessCount` and `AffectedEntities` have special support inside the command processor.

When running a command, vanilla expands the main target selector, and then runs the command *once for each targeted entity.* During this process it keeps track of how many times the command succeeded (defined as 'did not throw an exception' because Mojang), this count becomes `SuccessCount` and also the return value of the method as command blocks store the count separately for comparator support. The expanded selector's full count becomes the value of `AffectedEntities`

The rest of the stats (and occasionally `AffectedEntities` for commands that do not use the standard selector expansion, see `/spreadplayers`) are set by each individual command by calling a function on the command sender.

The basic support for the non-special stats is fairly easy, but getting the automatic `SuccessCount`/`AffectedEntities` support requires a bunch of changes to the default command implementation in `SimpleCommandService`/`SimpleDispatcher`, and likely some changes to the command interfaces.

**Comment by modwizcode** [comment]
@Kobata are you working on a PR for this, or can I start working on this?

**Comment by zml2008** [comment]
I feel like this is something that should be handled internally to the command executor. Not all plugins need a success count or want to be repeatedly called when multiple matching entities are provided (because some plugins handle multiple targets *properly*). (and relatedly, this is handled for any minecraft ICommands registered in our wrapper executor)

**Comment by Kobata** [comment]
@zml2008 Don't touch this issue if you don't understand what it is about, and have not actually addressed that issue.
