### ISSUE TITLE
VillagerFactory redundant

### ISSUE THREAD

**Issue by AIOOB** [SpongePowered/SpongeAPI#337]
From what I can see the VillagerFactory class is useless as all the functionality it provides is also provided by GameRegistry and Career.

**Comment by gabizou** [comment]
If we are to remove VillagerFactory, then LivingMetaFactory would be removed as well, just in case you haven't considered that ramification as well.

**Comment by ST-DDT** [comment]
I dont see any benefits for this class/interface either.

**Comment by Minecrell** [comment]
This was fixed in https://github.com/SpongePowered/SpongeAPI/commit/e8c307a3f9cfc4bab19873fdf30da65b4e702d17
