### ISSUE TITLE
Improve Fireball hierarchy

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#339]
Currently, the `Fireball` interface has two subclasses: `SmallFireball` and `LargeFireball`. `SmallFireball` adds no new methods, while `LargeFireball` `getExplosionPower` and `setExplosionPower`. These methods affect the amount of block damage done.

`WitherSkull` is currently a subclass of `Fireball`. However, it can't really be considered a fireball, though it is an explosive projectile. Additionally, it has no methods its block damage, like `LargeFireball` does.

I propose that we create two new interfaces: 
* `ExplosiveProjectile`, which would inherit from the same interfaces as `Fireball` currently does.
* `BlockDamagingExplosive`.

`WitherSkull` and `LargeFireball` would each inherit from `ExplosiveProjectile` and `BlockDamagingExplosive`, while `SmallFireball` would only inherit from `ExplosiveProjectile`.

**Comment by gabizou** [comment]
@Aaron1011 would it be feasible to say that explosive projectiles do have explosion power but normally are not set?

**Comment by Aaron1011** [comment]
>@Aaron1011 would it be feasible to say that explosive projectiles do have explosion power but normally are nominal in terms of their explosion power?

I think it makes more sense to separate block-damaging explosions, and non-block-damaging explosions.

You *could* just make all non-block-damaging block-damaging explosions with a power 0. However, it think it makes more sense to have them logically separate. It also allows for increased granularity in event subscription.

**Comment by ryantheleach** [comment]
The only issue I see with that, is what happens if the power is adjusted for an explosion in an event? Suddenly it's gone from not doing block damage to doing block damage and the explosion type would need to change.

The other option is you make it impossible to change from one to the other, and cause people to cancel it and issue their own explosion causing it's own events which has it's own complications.

**Comment by filbert66** [comment]
Yes, please don't sesprate explosive projectile classes. One of my plugins is designed to permit users to adjust explosive power of ANY explosion, including skulls, fire charges, and ender dragons-- yes, they actually explode the blocks they fly through w 0 power. I don't want to have to change classes just to make it damage books or not.

**Comment by gratimax** [comment]
@Aaron1011 could you put this in a PR?

**Comment by Aaron1011** [comment]
@gratimax: Sure!

**Comment by gabizou** [comment]
@Aaron1011 did you write a PR for this yet?

**Comment by gratimax** [comment]
Continued in #468
