### ISSUE TITLE
Accessing offline inventories

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeAPI#344]
I don't know if this is planned in conjunction with the Inventory API, but I'd like a way to get the inventory of an offline player.

Use case: Sometimes I want to swap something from my inventory with another player's, but they are offline. With offline access, it could enable trading for offline players. This might be useful for web-based trading areas, which can offer a better UI than Minecraft for trading.

**Comment by jacklin213** [comment]
@gabizou You added this in #272 already right?

**Comment by gabizou** [comment]
No I did not. There's no inventory API yet, all #272 adds is the infrastructure to support it.

**Comment by Zidane** [comment]
This comes along with the inventory API.
