### ISSUE TITLE
Lightning effect has no setter

### ISSUE THREAD

**Issue by AIOOB** [SpongePowered/SpongeAPI#346]
In [Lightning.java] (https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/weather/Lightning.java) there is currently no way to set if the lighning bolt is just an effect.

**Comment by gabizou** [comment]
Adding to [OCD list](https://github.com/SpongePowered/SpongeAPI/issues/221).
