### ISSUE TITLE
Entity AI control

### ISSUE THREAD

**Issue by bensku** [SpongePowered/SpongeAPI#351]
Bukkit can't control entity AI, which is one of its biggest drawbacks in my opinion. I think we absolutely need that feature at some point, while maybe not at 1.1 or 1.2 releases.

I'm willing to PR that if this issue gets accepted. Then we can talk further about *how* to do it.

**Comment by sk89q** [comment]
Well, the use case is to make new mobs out of vanilla ones presumably, so it not working with third-party mobs isn't too big of a deal in my opinion.

**Comment by ST-DDT** [comment]
IMO custom entities arent a real problem.
First of all the AIHandler method could return an optional. As an alternative the EntityWithAI interface could be an interface that is not extended by any entity type in the API and only implementations implement it if they really support AI. Its a little bit sad that you always have to cast then but it is probably the safest way.

Next all entities are tick based so their AI is tick based as well. It does not matter that they execute their AI only every x ticks. Or twice a tick. We just have to state that in the javadocs.

Somethink i'm not sure about it is which interface it should extend. Plain Entity or Living/Agent? Modders always have some crazy ideas for example an ItemEntity or FallingBlock that follows a player similar to a missle.

**Comment by spaceemotion** [comment]
@ST-DDT Looking at the forge base, aren't living entities always capable of doing AI stuff? I might be mistaken, but if that's the case we could just add those methods to the `EntityLiving` interface.

**Comment by ST-DDT** [comment]
@spaceemotion The Sponge API has an own interface for this [Agent](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/Agent.java) and i won't object if it is added there. The issue might be custom entities so i listed two possible approaches. In addition to that Not-LivingEntities such as FireworkRocket, FallingBlock, Projectiles and DroppedEntites (in mods) may use/support an AI as well and i would like to address them as well with the default AI API. (Target tracking/following is AI stuff as well)

**Comment by spaceemotion** [comment]
@ST-DDT that's actually a very good point.

I wonder how one would add an AI system to an armour stand then - thanks to the graph you provided that seem impossible to do. Maybe not having an `EntityWithAI` interface, but a system that can "add" AI behaviour(s) to all kinds of entities (even item stacks if you so desire) would offer much more variety. 

This may just be a thought, but given that there's the entity component system talk going on as well, I would not really bind the AI system to certain entity types though.

Such a system would then just take an entity object, add that to some kind of registry. Developers would be able to add or modify behaviours based on a returned "EntityAITasks" object (or something similar, I just used the name from MCP here) regardless if the original object was a living or a "dead" entity.

**Comment by ST-DDT** [comment]
@spaceemotion You have to differentiate between the interface hierachy that is provided by the API and the really implemented interfaces, of course you can add AI to `ArmorStand`, but you have to implement a `BodyController`/`Navigator` then, so that you can freely execute various tasks (see my PR https://github.com/SpongePowered/SpongeAPI/pull/315 for example).
In your custom entity class you simply have to overwrite `Entity.tickEntity()` and call the AI method there. ( i tried the same for AI players, the AI goals worked, but the `BodyController` is the hard part)

I have not yet looked at the component system in detail, but there could be difficulties if you apply Ai to an entity that does not support AI. (Some entites like `ItemFrames` drop/break if they move/have bad locations). There might be other issues such as problems that occur due to internally applied AI (inside `tickEntity()`, default mobs) vs externally applied AI (outside `tickEntity()`, unsupported entities).

**Comment by gratimax** [comment]
In the API `Agent` most nearly equals equals `EntityLiving` in the Minecraft source, and `Living` is most nearly `EntityLivingBase`. Note that `EntityLivingBase` has no AI tasks or AI classes of any kind, these are instead on `EntityLiving`. For this reason we have duplicated it the same way in the Sponge API, and it will stay this way because doing otherwise would mean a whole lot of implementation. This means no "AI" interfaces for fireballs or what-have-you because they don't qualify as objects that can think in Minecraft.

**Comment by ryantheleach** [comment]
Is it possible to expose the methods to register an AI to minecraft to make a fireball think, or does it only take EntityLivings?

**Comment by Kobata** [comment]
`EntityLiving` is the base for all AI-related things -- nothing else has the variables for the AI, nor the processing code for them.

**Comment by ryantheleach** [comment]
So if someone wanted to make a custom Fireball, they could make an (glowstone/forge) Mod that made fireballs implement Agent/EntityLiving You would still be able to manipulate it's AI using sponge correct?

**Comment by modwizcode** [comment]
That's not quite right @Kobata, for instance, entities (I think derived from ```EntityLiving```) all have a method that gets called per tick it seems. I know to prove I knew what I was doing, I had to make an Ender Dragon riding plugin, which let you control the dragon similar to a horse. 

This overrode a non-ai based system from horse. Of course NMS was required, but the point still stands, you can do arbitrary processing every tick.

**Comment by Kobata** [comment]
Everything has a per-tick method yes, but only one base class handles the proper AI processing (which is a fairly complex thing, and one of the better-designed parts of the game's code)

**Comment by modwizcode** [comment]
Right but nothing says we can't artificially hook in, either in Sponge or
more properly in Forge. Seems like a change lex would be willing to take a
look at if we do it smart.

**Comment by ST-DDT** [comment]
@Kobata You are right that the AI methods itself are very complex. But AI method calling is not. It is basically a method `tickAI()` without any parameters. A cursed fireball probably dont need a complex AI so it does not matter if you use the base stuff from `EntityLiving`. Sure you could use a scheduller for that too, but has other drawbacks such as manual task cleanup on entitiy removal.

**Comment by Zidane** [comment]
I've did a lot of playing around with making Humans work on a local fork of SpongeCommon. More than a few of you have logged in and played around and it was just a blast.

My thoughts coming off of it is writing an AI layer is actually not hard and would be simple for Custom AI from a plugin's perspective. The annoying (not hard part) is "fixing" the Vanilla AI to stop making assumptions. It is a further goal of mine to interface out as much of the built in AI as possible.

For example, some of the AI tasks assume EntityAnimal/EntityHorse/etc for goals which are quite generic (The funniest one is EntityAIRunAroundLikeCrazy which a Horse does when un-tamed). Leveraging the Data API, there is no need for these assumptions.

Expect a branch to show up in the coming weeks.

**Comment by spaceemotion** [comment]
Awesome news @Zidane.
Does that mean it will also be possible to add custom AI goals?

**Comment by Zidane** [comment]
@spaceemotion 

Being able to do custom goals will happen quickly. Being able to use the Vanilla AI (but tweak it to your desires) will take some time.

**Comment by modwizcode** [comment]
My thoughts on this now, AI should be exposed through the Data API which will handle indicating support for AI modifications.

**Comment by AlphaModder** [comment]
@Zidane I was under the impression that we weren't going to use a purely goal-based system like vanilla, whether it uses the vanilla AI or otherwise.

**Comment by Zidane** [comment]
@AlphaModder 

You should have no assumptions because it has never been discussed at any length.

**Comment by AlphaModder** [comment]
@Zidane Alright, that's just the response I got when I asked about it a few months ago. I also managed to dig up my [old proposal](https://docs.google.com/document/d/1aiBIv1iSvpoHtdzVJNSmdmn6gtcmMUUXpKLpmUGPrsQ/edit#) for the AI system, maybe it will be of interest.

**Comment by ST-DDT** [comment]
The AI core basicakly a thing you can call something like `tickAI()`. Everything below that is just implementation dependend. However there should be an API for goal based AI management.

**Comment by Zidane** [comment]
I've added an AI framework in the branch feature/goals. Its being done in phases with phase 1 having the basic AI completely functional. I'll expose the PathFinder in phase 2. Closing this as its in progress and I'll open a PR for discussion shortly.

**Comment by liach** [comment]
I am curious that is the pathfinder the slowest part of the entity ai?
