### ISSUE TITLE
Operators Check

### ISSUE THREAD

**Issue by MrSparkzz** [SpongePowered/SpongeAPI#353]
There should be a boolean method in the Player class that checks to see if a player is an operator.

There should also be a Collection/Set/List of all Operators on the server, and it should be accessed somewhere in the Game class.

**Comment by Zidane** [comment]
No, that is for the Permissions API.

**Comment by MrSparkzz** [comment]
Soo.. will the Player class eventually extend a Permissable class or something? So you could easily do something like player.isOp();? If not that seems kind of foolish to leave it out because it seems very important and I know of a lot of plugins, including my own that would benefit from it.

Also, about the Operators list in the Game class. I think it makes sense. Something like game.getOperators(); would return the admins of the "game" or whatever.

You seemed rather stern in your response.. May I at least get a better understanding of how it *will* work?

**Comment by simon816** [comment]
@MrSparkzz You can see the current progress with the permissions API in PR https://github.com/SpongePowered/SpongeAPI/pull/340
