### ISSUE TITLE
Single Player /Lan Permissions

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#359]
Given the possibility of singleplayer/lan sponge plugins, will there be a default set of permissions for single player?

How does OP differ from the single player allow cheats world option, or the same option when opened to lan, do all players get the ability to use commands or just the host?

Sorry if this is already supported in the permissions API, I don't yet fully understand how that portion of the API works.

**Comment by gabizou** [comment]
I don't believe single player permissions are being considered *yet* since SpongeAPI is focusing on being a ***server*** API first and then seeing how we can fit single payer server into the mix.
Though, I could be wrong.

**Comment by progwml6** [comment]
@gabizou we aren't doing client side features just yet but the system should properly function for testing/playing w/ server sided plugins in ssp until then

**Comment by zml2008** [comment]
The permission system includes checks if a player is singleplayer server owner to give them op automatically.
