### ISSUE TITLE
Removing Chunk.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#360]
Idea. Add function:
removing Chunk. As if he did not generate. Alternative RegenerateChunk.

**Comment by Bammerbom** [comment]
https://github.com/SpongePowered/SpongeAPI/pull/361/files

**Comment by Deamon5550** [comment]
This already exists in World:

```java
    /**
     * Deletes the given chunk from the world. Returns a {@code boolean}
     * flag for whether the operation was successful.
     * 
     * @param chunk The chunk to delete
     * @return Whether the operation was successful
     */
    boolean deleteChunk(Chunk chunk);
```

@Bammerbom in regards to having a delete method in Chunk, this is just a recipe for memory leaks since as soon as you call Chunk.delete() the reference to the chunk that you have is invalid and needs to be dereferenced.
