### ISSUE TITLE
Implementation dependent modules

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/SpongeAPI#364]
In light of the decision to not provide a packet API and the difficulties that implementation specific code (which while unfortunate, does need to exist for some functionalities that would never belong in an api), I have come to the conclusion that a simple fix is possible.

While most will see this as excessive at bast and insane at worst, the inclusion of an actual system for loading these implementation specific classes at runtime strikes me as a good tradeoff between making things ridiculously complicated for plugins, and opening the cage of packet API's.

The system relies on both stable version information (snapshot or release, version number, possibly an implementation number, and a implementation specific identifier string), and the definition of a non dependent API + fallback implementation. This system is inspired by the handling of nms in Bukkit, but with the goal of making it cleaner and more dependable. 

And example use of this API might go like this

```java

public interface API {
    void setUUIDServer(String hostname);
}

public class SpongeForgeImpl implements API {
    public void setUUIDServer(String hostname) {
        // ... Actual implementation would go here.
    }
}

public class FallbackImpl implements API {
    public void setUUIDServer(String hostname) {
        throw new ImplMissingException("Sorry this SpongeAPI implementation isn't supported by Plugin Foo, seek support from developer Xyz");
    }
}

public class MyPlugin {
   @Inject
   ImplManager implManager;
   public void onInit(ServerInitializationEvent event) {
       implManager.registerAPI(API.class, new Fallback()); // Fallback must exist for clarity reasons
       ImplHandler spongeHandler = new HandlerBuilder(new SpongeForgeImpl(this), // pass the plugin reference to the instance
                                                      setProtocolRange(52, 52).
                                                      setAPIMin("1.6.20").
                                                      setImplName("Sponge"). // Either name, or class, or both. Need at least one
                                                      setImplClass("org.spongepowered.sponge.mod.SpongeMod").build());
       implManager.addHandler(API.class, spongeHandler);
    }
}
```

**Comment by kenzierocks** [comment]
If you do this you may want to take a look at [`ServiceLoader`](http://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html) from the JDK.

**Comment by modwizcode** [comment]
We have an existing service provider system in Sponge's API so that's not a problem. Its more the nature of what I'm proposing.

*NOTE: formattings is bad, I know, wrote this on my tablet. Will fix tomorrow with pc, feel free to edit if you like*

**Comment by kenzierocks** [comment]
Oh, okay.

**Comment by Zidane** [comment]
For the record, I NEVER said there won't be a Packet API. I said there won't be Packet Handlers (there is a huge difference).

You'll still be able to send channel messages.

**Comment by Zidane** [comment]
Also, you are going to have to elaborate a lot more on this. I completely don't see the point.

**Comment by modwizcode** [comment]
No confusion there, but a good clarification, as I'm not talking about
channel messages and didn't mean to suggest that I was.

**Comment by modwizcode** [comment]
@Zidane Not sure what you mean? This would be a way to define code that had to hook into the underlying implementation, but only load the correct version depending on specific parameters. Similar to native shared libraries that need a different version for each OS. This could define a clean way to load code that bypasses the API. 

Basically, people will probably end up bypassing the API any

**Comment by gabizou** [comment]
@modwizcode So somewhat like how some plugins that had to deal with the server internals for CraftBukkit had "versioning" support to do what they needed to do?

**Comment by modwizcode** [comment]
Yes, exactly like that.

**Comment by modwizcode** [comment]
Ping @SpongePowered/developers

**Comment by me4502** [comment]
Hmm.. I think it would be better to just make api to fill needs, rather than this.

**Comment by modwizcode** [comment]
As I have demonstrated/encountered, the API cannot contain everything, and
making handling those exceptions as safe as possible is in the project's
best interest.

**Comment by me4502** [comment]
Hmm.. This could be useful

**Comment by Zidane** [comment]
We are doing a Vanilla impl known as Granite. Covers this.

**Comment by modwizcode** [comment]
@Zidane How does a Vanilla implementation solve this issue? It's an issue with low level changes that don't belong in the API that might be desired on both version of Sponge's implementation.

**Comment by Zidane** [comment]
@modwizcode 

We aren't doing this in our API. It adds more support for us when x, y, z plugin breaks because of implementation-specific code and they come running to us.

Release separate binaries per implementation for your plugin.

**Comment by kenzierocks** [comment]
IRC relavance: https://gist.github.com/kenzierocks/4adb9a43331016d8e9d1
