### ISSUE TITLE
Tameable should extend Sittable

### ISSUE THREAD

**Issue by mproncace** [SpongePowered/SpongeAPI#370]
The vanilla MInecraft server does not have a discrete `EntitySittable` class. Instead, the AI for sitting is included in `EntityTameable` within the `aiSit` object. Therefore, because all tameable entities are also capable of sitting, it would make sense from an implementation standpoint for `Tameable` to extend `Sittable`, rather than vice versa as it currently stands.

**Comment by gabizou** [comment]
Sorry, but not all tamable entities are able to sit, Horses come to mind as an easy example. I wrote the interfaces knowing full well the structure of entities in the vanilla Minecraft code base and chose to avoid blindly following the precise structure (which included Tamable and Sittable).
