### ISSUE TITLE
Representation of Attributes

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#372]
Some entities in Minecraft have a feature called [Attributes](http://minecraft.gamepedia.com/Attribute). Unfortunately, I'm not familiar with any API that has properly supported said features. Attributes, in my opinion are very important to the gameplay of the vanilla server, and many plugins could very well use them for various reasons.

**Comment by Aaron1011** [comment]
It's interesting to note that potion effects like Speed and Slowness are implemented using attributes. The potion effect sent to the client only displays the potion effect name and time next to the player's inventory.

**Comment by bloodmc** [comment]
I think it would definitely be a good feature to include in our API.

**Comment by ST-DDT** [comment]
There are some things about attributes that are good to know. (There will be others as well but i haven't encountered them yet)

- Atttributes are generic as potion effects.
- They can be missing for an entity
- they have differente default values
- they have different max values (or critical values that should not be exceeded)
- they all seem to be double values
- they all seem to have a minimum of 0
- there is/may be a list of  `AttributeModifier`s that modify the current value
  - used by potions
  - get/alter the base value
  - get the current value
  - get the default value for that entity (type)

Some information i colleted about Attributes:
- FOLLOW_RANGE (min:0; default: ~40; (max: 128))
- MOVEMENT_SPEED (min: 0; default: ~0.2 - 0.4; (max: 3))
  - values > 1 cause issues with the pathfinder (never reach a certain spot)
  - values > 3 looks really odd
- KNOCKBACK_RESISTANCE (min: 0; max: 1)
  - seems to be a percentage
  - Knockback resistance chance. Resisted knockback is still knockback but far less.

**Comment by AlphaModder** [comment]
If no one minds, I'd like to try my hand at this.

**Comment by Deamon5550** [comment]
Added in 510a5639a87b2ca03f9649a4e01f1f8d2e2f1072
