### ISSUE TITLE
Mod Compatibility

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#375]
Throughout the API I see many enum like classes with static final fields.

Doesn't this prevent expansion? I propose that for any GameRegistry like class there should be a fallback of some kind.

Using string lookups would be slow, but would allow plugins to access implementation and mod specific information, without breaking the API. The API knows nothing about the mod, but that doesn't mean the user or plugin shouldn't be able to access this without relying on compiling against each mod.

Plugins could expose these as configuration to the user for example adding containers or weapons to be tracked, or entity types to /spawnmob or disguise type plugins.

**Comment by progwml6** [comment]
these classes are just holders for the known values. additional values are added at runtime to the registry from mods/plugins

**Comment by ryantheleach** [comment]
How do you access them?
