### ISSUE TITLE
Living has unimplementable methods

### ISSUE THREAD

**Issue by AzureusNation** [SpongePowered/SpongeAPI#382]
When trying to implement ArmorStand I came across a issue that may also affect other entities down the line. 
In minecraft EntityArmorStand extends EntityLivingBase where as in Sponge it extends EntityLiving. By having this you get methods that cannot possibly be implemented (https://imgur.com/phk3r1x).
Leashes cannot be used on ArmorStands, nor can it pickup items and nor does it need to be persistent.

One way around this would be to add an extra level in the interfaces between Entity and Living, effectively what minecraft has EntityLivingBase. This would also solve other issues that I have had to work around.

Input would be greaty appreciated.

**Comment by Kobata** [comment]
`EntityLivingBase` = `Living`, `EntityLiving` = `Agent`

**Comment by AzureusNation** [comment]
Can I say Agent is hideous for the name :P but if that is so then isLeashed, setLeashed, getCanPickupItems, setCanPickupItems, isPersistent and setPersistent need to be moeved from Living to Agent.

**Comment by gabizou** [comment]
I can see why picking up items can be moved to `Agent`, however the persistence is something we've discussed in IRC. Forcing persistence to remain in `Living` instead of `Agent` means we can force not just "AI-enabled" entities, but all living entities to become persistent or not. It's much more valuable to developers to decide whether any `Living` entity can be persisted or not vs any `Agent` that specifically conforms to Minecraft's AI enabled entities.

Of course, @bloodmc and I went back and forth between it for a while whether to force persistence for all Entities or just Living entities.

**Comment by Kobata** [comment]
@gabizou AI-enabled entities are the only ones for which 'persistence' in that sense is variable -- all other entities are always persistent

**Comment by AzureusNation** [comment]
In Minecraft though if a entity is not a LivingEntity it cannot be persistent. For example what would happen if you try to force a player to be persistent, it just wouldn't work.

**Comment by AzureusNation** [comment]
@Kobata I can confirm this aswell.

**Comment by gratimax** [comment]
Only commenting because @AzureusNation wants input(I don't mean this in a bad way though, I just have other stuff to work on :smile:):

When AI eventually comes, it should be good enough that in any foreseeable use case a plugin developer will want to use `Agent`. Persistence, in this case, refers to mobs that have a name tag on them if I understand correctly. Therefore, entities that cannot have name tags put on them(`Living` but not `Agent`) simply don't have these persistence methods defined, so implementing them would require changing vanilla behavior.

**Comment by gabizou** [comment]
@gratimax right about the persistence requiring to change some vanilla behavior, but that's what I'm referring to in an IRC convo some of us had, specifically when I was determining whether to house Entity or Living with persistence.

@Kobata I can see many reasons why we wouldn't want other entities to persist (all those arrows shot by players that can't be picked up, never getting removed from the world etc.).

**Comment by AzureusNation** [comment]
@gabizou The fact of the matter is, its all well thinking that this might work but when it comes to implementation it's got to work. If this is to stay how do you suggest that we change the vanilla behaviour. Bare in mind how the clients are going to react to this aswell.

**Comment by ryantheleach** [comment]
If it were up to me I would strip these out into separate interfaces.

ILeashable, IPersistent, IPickupable

**Comment by Mumfrey** [comment]
> IPickupable

Or maybe `ICollectable` lol, `IPickupable` just sounds kind of hilarious :)

**Comment by AzureusNation** [comment]
@ryantheleach these dont even need to be seperated, just moved from Living to Agent as what ive done in my pr.

**Comment by ryantheleach** [comment]
I feel calling this persistence is doing the users of the API a great dis-service as well persistence seems to imply whether they will be saved in the world as opposed to whether they can despawn.

**Comment by nightpool** [comment]
I agree with separating these out in to separate interfaces. Putting them
under Agent is just weird IMO.

**Comment by AzureusNation** [comment]
@nightpool even if they were put in their own interfaces, agent would still have to extend them.

@ryantheleach but that is what you can only do ingame. We can make a pig not have persistance. Or any living mob but not a player.

**Comment by ryantheleach** [comment]
@AzureusNation Unless sponge implementations intend on making sure that this works always in the future, no matter how the underlying implementation changes, it shouldn't be in the API for all entities/animals/mobs

Extract it to an interface, that way it can be implemented for the entities that sponge plans on supporting, I still think the anti-despawn property is different to not persisting.

A way to get the same functionality (and more) would be throwing an EntitySaveEvent when a entity is persisted to the world, this would also allow any plugins with metadata about those entities to persist them as appropriate, cancelling the EntitySaveEvent could make the entity not persist.

**Comment by Kobata** [comment]
@ryantheleach Mojang calls the flag 'PersistenceRequired' in the save format, which is where it got the name from

**Comment by AzureusNation** [comment]
Is it agreed though that the methods moved in my pr are correct and that they need to be moved up to agent as living does not support the?

**Comment by Zidane** [comment]
I'm not seeing a drawback to doing a separate interface as it seems odd to me too to put these into Agent.

**Comment by AzureusNation** [comment]
@Zidane So hows 3 interfaces such as Persistant, Leashable and something for pickingup items but as @Mumfrey said Pickupable sounds weird.
