### ISSUE TITLE
FishHook#getHookedItem doesn't reflect underlying implementation

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#398]
The `getHookedItem` method of the `FishHook` interfaces assumes that the hooked item is available at any time. However, this is not the case.

In Vanilla, the hooked item is only computed *after* the hook has been retracted. It involves both the enchantments of the fishing rod the player is holding, and a random value.

Additionally, fishhooks are supposed to be killed when a player switches away from the fishing rod. However, this is actually implemented in `onUpdate`, rather than when a Held Item Change packet is sent. It's conceivable that a player's held item slot could be switched quickly enough to avoid the check, thus potentially invalidating the result returned by `getHookedItem`.

I propose that. similar to Bukkit, the hooked item be made available only through an event. This need not apply to a hooked entity, however.

**Comment by Zidane** [comment]
Is this still an issue @Aaron1011 ?

**Comment by Aaron1011** [comment]
@Zidane: No, it's been resolved.
