### ISSUE TITLE
Variable damage amounts

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#399]
Certain entities, such as `Snowballs`, do different amount of damage depending on the entity they hit. In the case of a `Snowball`, damage is done if the `Snowball` hits a `Blaze`. Otherwise, 0 damage is dealt (different from not causing any damage).

This conflicts with the `Projectile` interface, which only allows for one damage value.

**Comment by gabizou** [comment]
There are a few projectiles that already break the contract in vanilla minecraft, snowballs are one of them, and WitherSkulls are another.

Perhapse `Projectile#getDamageTowardsEntityType(EntityType)`?

**Comment by Aaron1011** [comment]
I like that idea.

**Comment by Zidane** [comment]
@gabizou 

Maybe not EntityType and just Entity? That way your snowballs hurt Enderman A more than Enderman B?

**Comment by feikname** [comment]
Why not both?

**Comment by gabizou** [comment]
> Maybe not EntityType and just Entity? That way your snowballs hurt Enderman A more than Enderman B?

Doable, I do believe it's possible to "fake" the damage being calculated, but we'd have to make sure that we aren't actually applying the damage. This could become meddlesome with custom entities not having a "normal" damage calculation.

**Comment by gabizou** [comment]
@Aaron1011 are you going to apply this in a PR?

**Comment by gratimax** [comment]
Closing in favor of #467
