### ISSUE TITLE
EyeOfEnder should not extend Projectile

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#400]
`EyeOfEnder`'s behavior is very different from that of a projectile.

It travels towards the nearest stronghold, and not in any type of projectile motion. Additionally, it never deals any damage on contact.

Because of this, I believe that `EyeOfEnder` should extend `Entity` instead. It might make sense to add methods similar to `getProjectileSource` and `setProjectileSource` to it, with an adjusted return type.

**Comment by MeltedLux** [comment]
Agreed.

**Comment by MattBDev** [comment]
This makes a lot of sense. I agree with it.

**Comment by modwizcode** [comment]
I agree with this.

**Comment by AzureusNation** [comment]
I also agree but I cant see how we can get/set the source of the entity though in minecraft :/

**Comment by modwizcode** [comment]
After looking this up, projectiles describe more than freely falling projectiles.

**Comment by modwizcode** [comment]
And this is fixed in #424 so.
