### ISSUE TITLE
NoArgument Constructor in Exceptions is implemented inconsistently

### ISSUE THREAD

**Issue by Sleaker** [SpongePowered/SpongeAPI#402]
I only looked through a few of the exceptions, but I have a feeling this is the case in the entire project.  The No-argument constructors for Sponge's custom exceptions aren't consistent.

Examples:

Define an empty constructor:
ProvisioningException
ProviderExistsException
CommandException

Don't Define a Constructor at all:
InvalidDataException
InvocationCommandException - (possibly alright if CommandException is fixed)

**Comment by kenzierocks** [comment]
No-argument constructors are called implicitly.

**Comment by Sleaker** [comment]
@kenzierocks - they are overridden in the listed classes. please look before commenting.

**Comment by kenzierocks** [comment]
Yes, I understand, they are still called implicitly. Every subclass (even of Object) makes a `super` call, overriding is not possible in constructors.

**Comment by Sleaker** [comment]
@kenzierocks - fair enough, can we decide to be consistent then and either stop overriding the default constructor, or making sure we add in the super call so we are doing the same thing that java does?

**Comment by kenzierocks** [comment]
We are always doing the same thing, it's either explicit or implicit.


Considering the rest of the API, I think implicit is our style, does the style guide have anything to say?

**Comment by Sleaker** [comment]
Style guide doesn't say anything about an empty default constructor vs not including it.  Every single java Exception defines it and calls super();  and it looks like nearly all of the guava exceptions define an empty default constructor.

**Comment by gabizou** [comment]
So, another thing to add to the [OCD list](https://github.com/SpongePowered/SpongeAPI/issues/221)?

**Comment by Sleaker** [comment]
@gabizou - yup yup!
