### ISSUE TITLE
Use Collection<X> instead of List<X> for GameRegistry.getX()

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeAPI#408]
While thinking how to convert my plugins i encountered some inconsistencies from what java states and the API actually does.

Lets use `List<BlockType> getBlocks()` as example.

Java states that `List`s should have a defined order. This may be true of one call of that method, but not for the calls following the first call. Because the `List` is backed by a Hash based container (Map,Set). So every time i change the underlying containers (by adding a new `BlockType` or restarting the server the order is gone. Also it is never stated anywhere that it has any order.
So relying on an index or executing a binary search is a pretty bad idea for plugin authors. So I recommend changing it to a `Collection`. This will also reduce potential issues a none `RandomAccess` `List` may cause.

We furthermore will never have duplicate elements, so some implementations will probably want to use some kind of `Set` for that. Some sets can also keep their element ordering fixed. See `LinkedHashSet` or `SortedSet`. But thats up to the server impl. We should first downgrade to `Collection`s and then decide whether `Set`s are the right choices for our implementation. 

This are standalone changes, which will not affect the current Sponge server impl, unless they want to use the possibilities connected to it.

If this gets accepted i'll offer my help getting this implemented.

Features of a `List` in comparison to a `Collection`:
* Index access -> not needed
* Element order -> not defined -> not reliable -> not useful
* Duplicate elements -> not/never needed + should never happen
* Sub-Lists -> no order defined -> not useful

Features of a `Set` in comparison to a `Collection`:
* Unique elements -> probably needed/useful
* Fast contains check -> useful, but rarely usable

**Comment by Zidane** [comment]
They should be Sets as there should never be duplicates of anything in the GameRegistry.

@Minecrell @gabizou either of you want to make this change?

**Comment by ST-DDT** [comment]
I can help with that if this gets accepted.
