### ISSUE TITLE
Missing Events. (Explosion, block to entity event)

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#416]
There are currently no events that I can see that govern the effects given to an entity when it is exploded upon (knockback/physics, damage) or to blocks (blockDestroyEvent? but what about yield calculation?)

As well as an event for when a block is turned into an entity (Wither/golem spawn / primed tnt)

Or would these events already be covered by other events and not need to be added?

**Comment by modwizcode** [comment]
I agree that ExplosionEvent is completely missing and is a must-have for the API.

**Comment by gabizou** [comment]
I'll work on adding these in the morning.

**Comment by MattBDev** [comment]
I don't see the need for a block->entity event. I'm not sure what the use would be since you could just stop the gravity of the block if it falls and you can listen to ignition and explosions.

**Comment by gabizou** [comment]
Closing as it was fixed in 45c656f.
