### ISSUE TITLE
Entities have no velocity

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/SpongeAPI#417]
There is currently no way to get or set the velocity on an entity. While most (maybe all) entities have a velocity component, there is no representation in the API for this. This is especially troublesome for arrows and other projectiles that need velocities to be useful after spawn.

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeAPI/commit/3f2fc3dfce36087c4ded447ff6f974fc6ad31402
