### ISSUE TITLE
There is no way for the implementation to construct WorldGenerator object from plugin

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/SpongeAPI#418]
Currently they only way to change WorldGenerator is to explictly use world.setWorldGenerator() method by world generator plugin. There is no way to construct the WorldGenerator object from the outside (ie. by the server implementation or world management plugin)

Bukkit solved it by adding JavaPlugin.getDefaultWorldGenerator(worldName, id) method, that was implemented by plugins.

**Comment by bloodmc** [comment]
For implementation, I plan on using FML's registerWorldGenerator method

https://github.com/MinecraftForge/FML/blob/1.8/src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java#L71

Need to discuss further on how to represent this in API.

**Comment by Barteks2x** [comment]
But there is no way to get instance of that WorldGenerator. Only the world generator plugin can provide it, and it can provide it only by calling world.setWorldGenerator(). There is no way it could be possible configurable in server config.

**Comment by bloodmc** [comment]
@Barteks2x Like I just said, we need to discuss how to represent it in API. Be patient =)

**Comment by boformer** [comment]
I think that only one instance per server is necessary, because the seed is always passed to the generation methods.
I think what is needed is a simple ``WorldGeneratorRegistry`` where plugins can register world generators on initialization (generator-name ---> generator instance)

**Comment by Barteks2x** [comment]
What about WorldGenerator.areMapFeaturesEnabled()?
It's configured per world, not per generator. And there may be multiple worlds using the same generator. 
And since in 1.8 each world is in it's own thread, and populators would be shared between worlds - it would canse some issues.
Even vanilla generator has HashMaps or simillar things for StructureGenerators. It would mean that plugins would need to ensure that they use correct object for correct world. So plugins would probably end up with some thread safe collection of internal world generators in WorldGenerator class, and call correct one for each world.
So we need different generators for different worlds.

**Comment by boformer** [comment]
Good point ;)

**Comment by gabizou** [comment]
> There is no way to construct the WorldGenerator object from the outside (ie. by the server implementation or world management plugin)

I believe you're misunderstanding this as `WorldGenerator` is an interface, meant to be implemented by any means required.

> Bukkit solved it by adding JavaPlugin.getDefaultWorldGenerator(worldName, id) method, that was implemented by plugins.

Again, any plugin can implement it's own `WorldGenerator` and assign it to a world.

> I think that only one instance per server is necessary, because the seed is always passed to the generation methods.

Incorrect. Every world has it's own `WorldGenerator` implementation (the nether, the overworked, the end, the twilight forest, the aether, to name a few), so adding a "global" `WorldGenerator` to the API will not be added.



> I think what is needed is a simple WorldGeneratorRegistry where plugins can register world generators on initialization (generator-name ---> generator instance)

Plugins may ignore this and assign their own generators on server initialization. There isn't a need for `WorldGeneratorRegistrar` short of fetching `WorldGenerator`s for a given world.



> And since in 1.8 each world is in it's own thread,

Incorrect, worlds are still not per-thread in any possible form. There is groundwork to make it happen, however, it still is not the case.

> and populators would be shared between worlds - it would cause some threading related issues.

Again, incorrect. Each world has it's own `WorldGenerator` instance absolving of any sort of conception of "threading related issues".

> And even vanilla generator has HashMaps or simillar things for StructureGenerators. It would mean that plugins would need to ensure that they use correct data for each world (probably also using some thread safe collections).

Not sure how you're making that argument. A `WorldGenerator` only needs to place blocks as necessary. The API is not written according to the specifics of the Minecraft server, let alone requiring to use a particular data structure. 

> And ff we would use one generator object for all worlds using the generator, for plugins the easiest way to deal with it would probably be creating some thread safe collection of internal world generators in WorldGenerator class, and call different generator for each world.

See points above about worlds and their own generators.

**Comment by gabizou** [comment]
Closing as the argument has been explained above.

**Comment by Barteks2x** [comment]
> I believe you're misunderstanding this as WorldGenerator is an interface, meant to be implemented by any means required.

By constructing WorldGenerator object I probably oversimplified. There is no way to construct the implementation from the outside. 

> Again, any plugin can implement it's own WorldGenerator and assign it to a world.

Plugins can assign WorldGenerator implementations to worlds, but only the plugin that implements it has access to it. There is no way to world management plugin (like multiverse in bukkit) to construct the object that implements WorldGenerator and assign it to world. So all the information about which world has which generator may end up in several different world generator plugins.

> Incorrect, worlds are still not per-thread in any possible form. There is groundwork to make it happen, however, it still is not the case.

About the threading - I was wrong, sorry about that. Information I find about it is too inconsistent. There was some information that it will be threaded in 1.8 and I didn't read that it actually won't be threaded.
And what I was talking about was @boformer 's idea to use one generator object per server. It was my argument agains it (and I was wrong)

> Not sure how you're making that argument. A WorldGenerator only needs to place blocks as necessary. The API is not written according to the specifics of the Minecraft server, let alone requiring to use a particular data structure.

Again, it was an agrument against @boformer 's idea. But thismone is correct. Minecraft generator (and probably plugins like TerrainControl) use some data structures to store information about what is already generated - see MapGenStructure and MapGenStructureData classes. If the would be used between worlds - things wouldn't be good...

And I think there should be some way to set terrain generators in one configuration file. Current API doesn't make it possible - because only the plugin that adds the WorldGenerator can create instance of it's implementation if the interface.

In CraftBukkit there was bukkit.yml - if you used one world, and multiverse plugin (or other plugins) for multiple worlds. These could work becayse there was JavaPlugin.getDefaultWorldGenerator(...) method. With SpongeAPI I don't see any way to achieve it.
