### ISSUE TITLE
Ability to get EntityType from Class<? extends Entity>

### ISSUE THREAD

**Issue by Soren025** [SpongePowered/SpongeAPI#419]
There currently no way to convert an entity class into an entity type. Probably could be a method in GameRegistry called ```EntityType getEntity(Class<? extends Entity>)```

**Comment by Soren025** [comment]
My reasoning is that currently there is no reliable way to store a type of entity into an annotation. The only means are through its id (requires a string constant to exist), enum (out of the question by design), or by entity class (thuss a method to get the ```EntityType``` from its class).

**Comment by gabizou** [comment]
May I ask why you're trying to convert a `Creeper.class` to `EntityTypes.CREEPER`? Why are you trying to work with the classes themselves? 

If you have *instances* of `Entity` you can simply get the `EntityType` via `Entity#getType()`. 

With the case of using the interface classes themselves, you'll still end up with the same issue of the following:

```java

Class<? extends Entity> clazz = Creeper.class; // not sure how you intend to get the class of something
EntityType entityType = myMagicConverter.getEntityType(clazz);
if (entityType.equals(EntityTypes.CREEPER)) { // is this what you'd end up doing?
 // do stuff

**Comment by Soren025** [comment]
Like I said, to refer to a specific entity type in an annotation. Or where ever else you for what ever reason have the entity class but not the EntityType.

For example

@SomeAnnotation(Creeper.class)

EntityType has a method to get the entity class so there is already a class tied to each EntityType.

Doing this is not possible as annotations only accept primitives, strings, enums, and class types.

@SomeAnnotation(EntityTypes.CREEPER)

Doing this is not possible because the string must be a constant

@SomeAnnotation(EntityTypes.CREEPER.getId())

I could enter the id of creeper but I do not know it off the top of my head and would have to look it up, I requested ID string constants to be able to switch case entity and block types but the idea was turned down.

@SomeAnnotation("the-creeper-id")

So the only other option for annotation is the class it self shown in the first example.

**Comment by modwizcode** [comment]
EntityTypes.CREEPER.getClass()?

**Comment by Soren025** [comment]
@modwizcode I need that same conversion in the opposite direction.

**Comment by kenzierocks** [comment]
Why? What purpose does having a Entity class in an annotation do? Why can't you store the EntityType?

**Comment by modwizcode** [comment]
Actually getting the entity type from entity is possible [EntityState](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/EntityState.java), Entity extends this interface, meaning these methods are in EntityState.

**Comment by modwizcode** [comment]
@kenzierocks The Class<EntityType> is EntityType itself, it should be the Class<Entity> or the getId() of an EntityType.

**Comment by Soren025** [comment]
@kenzierocks I am in a situation ware I must spawn an entity with information from an annotation. As such the only thing I can store is the entity class. Ids would work as there is already a conversion for id in game registry but there are no id string constants to reference and the only other option is to look up the raw id online.

@modwizcode I do not have an instance of entity to get the type from. The conversion I require is this ```Class<? extends Entity> -----> EntityType```

**Comment by modwizcode** [comment]
Use the `EntityType.getId()` value. You can get it by doing `EntityTypes.CREEPER.getId()`

**Comment by Soren025** [comment]
As I said ```@SomeAnnotation(EntityTypes.CREEPER.getId())``` wont work. Annotation type values will only accept inline strings or those referenced from ```static final String``` fields.

**Comment by kenzierocks** [comment]
This seems like a very out-of-place use-case. Why would you need this data in an annotation anyways?

**Comment by gabizou** [comment]
@Soren025 So, correct me if I'm wrong, but you're simply wanting an annotation to keep reference of an entity class, correct?

How about we fix with the following:

```java
@MyAnnotation(entityType = EntityTypes.CREEPER) 
// stuff here
```
To which you can do the following with the annotation:
```java
MyAnnotation annotation = object.getAnnotation(MyAnnotation.class);
if (annotation != null) {
  EntityType type = annotation.getEntityType();
  Class<? extends Entity> entityClass = type.getEntityClass();
  // do stuff with entityClass
}
```
Does that not work?

**Comment by kenzierocks** [comment]
No, it does not work. Annotations won't accept `EntityType`.

**Comment by gabizou** [comment]
> No, it does not work. Annotations won't accept EntityType.

Ah right, annotations require primitive types.

**Comment by Soren025** [comment]
@kenzierocks My use case is that of dynamically loaded classes with connections with entities, all I would see is their Class type so annotations is my only solution for having information on weather to construct it or not.

However in my case this discussion has sparked an idea to avoid the issue entirely. Although my use case no longer applies. I still feel a way to convert ```Class<? extends Entity>``` into ```EntityType``` is something that should exist seeing as how ```EntityType``` has reference to a ```Class<? extends Entity>```. I'm sure a use case will appear again.

**Comment by ryantheleach** [comment]
Can't the classes have static methods that you could call without constructing them?

**Comment by Soren025** [comment]
@ryantheleach As they are dynamically loaded I do not know their types until run-time.

**Comment by gabizou** [comment]
@Soren025 while I do not believe the use case is valid and merits addition to the API, I'll leave this issue open for search on a valid use case where this would be necessary.

**Comment by Soren025** [comment]
Indeed, as I said above

> **However in my case this discussion has sparked an idea to avoid the issue entirely**. Although my use > case no longer applies. I still feel a way to convert Class<? extends Entity> into EntityType is 
> something that should exist seeing as how EntityType has reference to a Class<? extends Entity 
> and there already exists the connection. I'm sure a use case will appear again.

**Comment by Zidane** [comment]
Closing this until a use case presents itself.

**Comment by Soren025** [comment]
@Zidane Would https://github.com/SpongePowered/Sponge/pull/193 be a use case? It implements such a method in its PR.

**Comment by gabizou** [comment]
> It implements such a method in its PR.

It's an implementation detail, nothing that is used for plugins.
