### ISSUE TITLE
Allow registering a service without specifying a plugin.

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#426]
Currently, `ServiceManager` mandates that a plugin instance be passed in as a parameter when registering a service.

Aside from the fact that the plugin instance is never used, this creates problems for services which are provided by an implementation. Services like `ConfigService`, which the implementation provides, have no sensible value to pass as a plugin instance.

I propose that a method `setProvider(Class<T> service, T provider)` be added to `ServiceManager`. Additionally, the use (if any) of passing in a plugin instance should be clarified.

**Comment by AlphaModder** [comment]
Perhaps there should be an `ServiceProvider` interface which `Plugin` can implement, but so can other things like `SpongeServices` or something in the implementation. That way, they can be registered for something, so that plugins can enumerate services registered to things that aren't plugins.

**Comment by gratimax** [comment]
pinging @sk89q for this, he designed the API originally.

I agree with the sentiments here, except for `ServiceProvider`. I can't think of any specific interesting quality that something that "provides services" has, so passing in a plugin object should just be optional.

**Comment by AlphaModder** [comment]
@gratimax It's not really for special qualities, it's just some kind of ID for the registrar, so plugins could find all services registered by X, plugin or not.

**Comment by gratimax** [comment]
@AlphaModder Then wouldn't `Identifiable` be enough?

**Comment by Zidane** [comment]
@zml2008 

Did your changes allow this to happen?

**Comment by zml2008** [comment]
Since SpongeMod (and any other mod) is now a PluginContainer, I don't think there is any real reason to not require a plugin when registering. Additionally, it gives a reference to who owns the service in case that becomes useful later on
