### ISSUE TITLE
Simple addition for creepers.

### ISSUE THREAD

**Issue by AlphaModder** [SpongePowered/SpongeAPI#427]
By using EntityCreeper.setCreeperState(1) and changing the client-side fuse time of the creeper  and probably a few other things, you can manipulate creeper flashes. See EntityCreeper.getCreeperFlashIntensity().

**Comment by gabizou** [comment]
That's the whole point of [`Creeper#ignite()`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/explosive/IgnitableExplosive.java#L35) and [`Creeper#setFuseDuration(int)`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/explosive/FusedExplosive.java#L51).

**Comment by AlphaModder** [comment]
@gabizou Those methods actually make the creeper ready to detonate, do they not? This is an effect, where the server-side fuse time isn't affected, only the client-side. It makes the creeper flash as if it was ignited if it was not.

**Comment by gabizou** [comment]
I'd like to state that at this time, the API is NOT intended for client side manipulation just yet. 

In regards to the creeper fuse time, one can simply set the fuse duration to a negative number to cancel the fuse.
