### ISSUE TITLE
ConfigFile change detection broken 

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeAPI#428]
[Detecting for change](https://github.com/kenzierocks/SpongeAPI/blob/fix/warnings/src/main/java/org/spongepowered/api/util/config/ConfigFile.java#L167) uses `[\r\n]` in order to split the lines, but that may leave extra empty lines in the case of `\r\n`, as it splits on `\r` and then `\n`. The correct regex is `\n|\r\n|\r`, to handle any case.

**Comment by Aaron1011** [comment]
I don't see that specified as the way to check for changes. That sounds like a bug in a particular implementation.

**Comment by kenzierocks** [comment]
No longer an issue.
