### ISSUE TITLE
Make EnderPearl a DamagingProjectile

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#434]
When projectiles were refactored to add the `DamagingProjectile` interface, `EnderPearl` was made a `Projectile`, instead of a `DamagingProjectile`.

Like `Egg`, `EnderPearl` is hardcoded to do 0 damage - but it does do damage. I believe it should also be made a `DamagingProjectile`

**Comment by Aaron1011** [comment]
@gabizou: That's a separate concept. Damage is done:

* If the `EnderPearl` hits a block: damage is done to the thrower
* If the `EnderPearl` hits an entity: (0) damage is done to the hit entity.

**Comment by Zidane** [comment]
@Aaron1011 

Is this still a relevant issue?

**Comment by Aaron1011** [comment]
@Zidane: Yes, it hasn't been changed yet.
