### ISSUE TITLE
Convert Text API to classes

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeAPI#435]
We should consider making the Text API (especially the `Text`/`Message` interface) classes in the API directly as this would simplify implementing and accessing the Text API.

This is not an easy decision, as there are different things to consider:

- `Text`/`Message` can't be implemented as mixin as its design is different from the classes used by Minecraft internally.

- While the general structure doesn't depend on any implementation-specific needs, some parts depend on code that should be placed in the implementation instead of the API:
  - JSON serializing/deserializing
  - (Converting messages from/to legacy formatting codes?)

- As `Text`/`Message` is an immutable object we could efficiently store lazy-initialized serialized JSON strings in there. Additionally, in the implementation we would need to have a way to convert a `Text`/`Message` to the internal format and the other way around. Right now we store this directly in the implementation class.
  - We could add a mixin for the `Message` class to efficiently implement the methods and add the fields only needed for the implementation.

**Comment by Minecrell** [comment]
@SpongePowered/developers are there some other opinions on this? We tend to converting everything to classes right now.

**Comment by gratimax** [comment]
I concur. Using classes for Text makes working with it far easier.

**Comment by simon816** [comment]
If you can't implement the `Text` and `Message` interfaces as mixins then it could easily be classes in the API. (Could they be mixed-in with `ChatComponentStyle`/`ChatComponentText`?)

To avoid implementation-specific details being leaked through to the API, the classes could be `abstract` to allow the implementation to define things like serialization etc.

**Comment by Minecrell** [comment]
@simon816 The design of our API is very different from the internal Minecraft classes. Our API is completely immutable, and Minecraft's is not. So it would break if mods (or Minecraft itself) modify the chat component.

As for the abstract classes, this is a little bit difficult: the inner interfaces of `Text`/`Message` would be classes too and would extend the abstract parent class. This would mean you would need to implement the changes in the implementation for every type, and not just for one like when using mixins.

**Comment by me4502** [comment]
It would probably be best to have them standard classes, and encourage the implementation to override the serialisation methods, whilst we provide a default

**Comment by Minecrell** [comment]
Fixed in #425
