### ISSUE TITLE
ClassGenerator should check primities for null

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#439]
In `ClassGenerator`, values passed in through the `Map` are checked to be null if the proper `NullPolicy` is set, and thy're not a primitive

However, if a primitive property isn't specified in the passed in `Map`, calling `Map.remoe` will return `null`.

The JM changes this to the default value for the primitive (`0` for `int`s, `0.0` for `float`s and `double`s). However, this still represents an error, as the event generator method isn't allowing the parameter to be set.

I believe that the null check be expanded to include primitives, to catch forgetting to pass in primitive parameters, as well as reference types.

**Comment by ryantheleach** [comment]
How would you then tell the difference between an error, and a value inside the map as it's default value?

**Comment by ST-DDT** [comment]
ContainsKey is probably a good choice here.

**Comment by Aaron1011** [comment]
It doesn't matter - the check if only performed for parameters which *shouldn't* be null (a `@Nonnullable` annotated field with a `NULL_BY_DEFAULT` policy, or an unannotated field with a `NON_NULL_BY_DEFAULT` policy).

Whether it was explicitly set to null, or was never set, it's an error, and should be indicated.

**Comment by ST-DDT** [comment]
Primitives cannot be set to null.
Or did i miss the point here?

**Comment by Aaron1011** [comment]
Yes, they can't be set to null - but the entry for the field name can be null.

While setting the primitive to null in the bytecode causes the JVM to set it to its default value, it still represents a bug - the method never passed in a value for the primitive, just as passing in `null` for a non-nullable reference type represents a bug.

**Comment by Zidane** [comment]
@sk89q 

I'd like to see this taken care of.

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeAPI/commit/a5b241db0be511c914ff4f53994df66b09dcaa83
