### ISSUE TITLE
Gets a block from this chunk.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#441]
Gets a block from this chunk.

Block getBlock(int x,
               int y,
               int z);

Parameters:
x - 0-15
y - 0-255
z - 0-15
Returns:
the Block

**Comment by kenzierocks** [comment]
Chunk extends Extent extends BlockVolume.

[`BlockVolume.getBlock(int, int, int)`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/extent/BlockVolume.java#L52).

**Comment by Azatik** [comment]
Thank You.
