### ISSUE TITLE
Missing state event for stopping.

### ISSUE THREAD

**Issue by mbax** [SpongePowered/SpongeAPI#442]
[Server states can occur repeatedly while a Sponge implementation runs](https://docs.spongepowered.org/en/plugin/basics/lifecycle.html). That's a fabulous feature, but it results in a slight problem. Plugin states only fire once per implementation run but they only describe startup of the plugin, never shutdown. Some plugins may wish to keep chugging along regardless of the implementation's gameserver rebooting while the implementation is still running.

I propose the creation of an event (or multiple!) describing the final shutdown of the implementation, or perhaps a plugin state event for shutting down a particular plugin.

**Comment by progwml6** [comment]
@mbax the events related to stopping/stopped in here are probably what we need https://github.com/MinecraftForge/FML/tree/master/src/main/java/net/minecraftforge/fml/common/event

**Comment by mbax** [comment]
Those events lack javadocs, so who knows when they fire. Additionally, surely SpongeAPI should be a bit more implementation agnostic than only choosing from Forge methods to replicate?

**Comment by Kobata** [comment]
The state descriptions in docs (and the sponge state events) basically map to the FML ones entirely -- there is no FML generic 'process shutdown' event, and in most cases such an event would be unreliable.

**Comment by Zidane** [comment]
Even so @Kobata @progwml6 there is some merit in knowing when the game itself is closing. I think there is suitable arguments for a true StopEvent (?)

Also, lets try to not always throw out "what fml does" cause eventhough Sponge is our official implementation on Forge, it isn't the only implementation and SpongeAPI is not "the Forge abstraction layer"

**Comment by Zidane** [comment]
@gabizou I'm assigning this to you to do. GameStoppingEvent.

**Comment by Aaron1011** [comment]
Added in https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/game/state/GameStoppingServerEvent.java

**Comment by JBYoshi** [comment]
@Aaron1011 That's not what this is for. This is looking for an event running when the *game*, not the *server*, shuts down.

**Comment by Minecrell** [comment]
Yep, @JBYoshi is right. While this event is equal to shutting down the _game_ on the server, on the client servers can be started and stopped several times (e.g. when you leave and join a singleplayer world) and the client itself (-> the game) will stop independently from the server.
