### ISSUE TITLE
EyeOfEnder implementation issues

### ISSUE THREAD

**Issue by AzureusNation** [SpongePowered/SpongeAPI#446]
Hi All,

Just implementing EyeOfEnder and noticed that a few methods have been added that cannot be achieved.

```java
public ProjectileSource getShooter() {}

public void setShooter(ProjectileSource shooter) {}
```
EyeOfEnder is not actually classed as a projectile as it cannot deal damage and also you cannot get or set the shooter of the entity.

**Comment by gabizou** [comment]
> it cannot deal damage

Please re-read the commit [`on Projectile refactors`](https://github.com/SpongePowered/SpongeAPI/commit/ee30f64671d6b9f89e5d6608dcdc56891c5160c7). That is a non issue.



> you cannot get or set the shooter of the entity.

I can't stress this more than most, the API is not going to ever be a direct blueprint of Vanilla Minecraft's code base. We've already determined in other discussions that all projectiles have a `ProjectileSource`, regardless whether that source is a Player or a `Dispenser`. 

If you are having a problem implementing it, well, you'll have to ask for help to implement it. Don't ask for the API to change for the reason that Minecraft doesn't match our API.
