### ISSUE TITLE
(Idea) Instance Local EventCallbacks

### ISSUE THREAD

**Issue by Soren025** [SpongePowered/SpongeAPI#447]
Basically the idea is to have a method for entities, worlds, blocks, anything with their own event type that allows you to apply an event callback (or something similar) to that individual instance. Then when an event is fired it adds the event callbacks attached to that entity, world, whatever.

From above, I say "something similar" because the event callbacks on their own in this way would not have access to the event information making this rather limited. A new object that allows the event callback access to the event information would probably be necessary, or a wrapper of sorts.

The idea is that when an event such as ```PlayerInteractEvent``` is called. It would apply the event callbacks attached to the involved player to the event at some point (probably near the end). The same for all entities in general, World, Block, ect.

Here are a few reasons why someone would use this over a normal event listener.
* 1) The event is called alot (```PlayerMoveEvent```, ```PlayerUpdateEvent```, ```PlayerCollisionEvent```).
* 2) The action to perform on the event is unique to one or a few targets, weather it be a skill for an rpg plugin or accessing unique information that would otherwise require a Map<UUID, Object> lookup (reference the mapped object in the event callback to use instead).

**Comment by kenzierocks** [comment]
Sounds like a good idea, instead of listening globally you bind to each thing?

**Comment by Soren025** [comment]
Ya that's the general idea

**Comment by Soren025** [comment]
From what I said above
> A new object that allows the event callback access to the event information would probably be necessary, or a wrapper of sorts.

I came up with an idea with the following interface

``` java
public interface EventCallbackSupplier<T extends Event> {
    public void EventCallback get(T event);
}
```

The method to accept one would be

``` java
<T extends Event> void applyEventCallback(Class<T> eventType, EventCallbackSupplier<T> supplier, boolean ignoreCancelled);
```

And an example of its use with the following class

```` java
public class SkillCast implements EventCallbackSupplier<PlayerInteractEvent> {
    private Skill skill;
    public SkillCast(Skill skill) {
        this.skill = skill;
    }
    @Override
    public EventCallback get(PlayerInteractEvent event) {
        return new AbstractEventCallback() {
            @Override
            public void run() {
                skill.cast();
            }
        }
    }
}
```

With its use as

``` java
Player player;
Skill skill;
player.applyEventCallback(PlayerInteract.class, new SkillCast(skill), false);
```

**Comment by gratimax** [comment]
While the specifics of this idea are bit shaky(I don't like how the `applyEventCallback` semantics work), at the core it is sound. There should be a way to listen to events coming from only a specific instance.

**Comment by Soren025** [comment]
@gratimax I thought about changing ```EventCallback``` but was unsure because of its current current use. If ```EventCallback``` became generic then it would cause issues with ```CallbackList``` possibly needing to be generic and how that would effect the getter for it in ```EventBase```.

As for your two examples I like the first of the two the best (when comparing the registration on the source vs registering it on the callback). 1) for reasons mentioned above. 2) because when the source is removed, unloaded, whatever. Then its registered callbacks will naturally go with it. While registering them else-ware for the source would require it to search and remove them.

**Comment by Soren025** [comment]
@gratimax the rx-like system you talked about on the forums does look really nice.

**Comment by gabizou** [comment]
@Zidane Is this still a valid thing we should consider?

**Comment by gabizou** [comment]
@Zidane @Aaron1011 I believe that since event callbacks have been removed, this isn't really well possible to handle aside from the plugin throwing the event itself and handling the event as it sees fit.

**Comment by Aaron1011** [comment]
I agree - this no longer makes sense with the removal of the callback system.
