### ISSUE TITLE
Properly define the outcome of BlockVolume#getBlock() for invalid positions

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeAPI#448]
Right now, it is undefined how `BlockVolume.getBlock()` will behave if the position supplied is outside of the BlockVolume.
Since returning null is not possible according to Sponge code style, the only choice is to return a `BlockLoc` object pointing to that invalid location. This object would either be crippled, since it cannot perform any operations that would change the represented block (`dig()` would always return `false`, `replaceBlock()` would just fail silently or need to throw an Exception) or may at worst be misleading (invalid location on one `Chunk` points to valid location on a separate `Chunk` leading to two different `BlockLoc` Objects referring to the same block but providing different data).

**Option 1: Changing return Type to `Optional<BlockLoc>`**
I think this would be the preferrable option. If an illegal position is provided, `Optional.absent()` will be returned, thus signaling that the position is not accessible via the used BlockVolume.

**Option 2: Clarifying the status as an invalid BlockLoc**
For this it needs to be made clear
1. The type of the block is unknown, which requires a new `BlockType` to be added. This BlockType must then be returned by `BlockLoc.getType()`.
2. All operations that attempt to change the block fail. This already works on `BlockLoc.dig()` since it can just return true, but `BlockLoc.replaceBlock()` will probably need a boolean return value indicating success.

**Option 3: Throw an Exception**
As simon816 and gratimax stated, invalid calls to `BlockVolume.getBlock()` could also throw an `IndexOutOfBoundsException`.

**Comment by simon816** [comment]
Option 3: Throw an exception, for example `IndexOutOfBoundsException`

**Comment by gratimax** [comment]
@simon816 says exactly what I was going to say here. `IndexOutOfBoundsException` is the standard exception to throw when, well, an index is out of bounds

**Comment by Bammerbom** [comment]
I agree with option 3.

**Comment by gabizou** [comment]
So, just include it in the javadocs, not the actual method signature.
