### ISSUE TITLE
Add CustomEvent(String name, Map<String,Object> properties), CustomEvent transformer

### ISSUE THREAD

**Issue by blackalegator** [SpongePowered/SpongeAPI#450]
Whenever you want to integrate your plugin with othe plugins (even the simplest feature like listening to shop creation events) you have to add dependencies, import additional code, etc. Furthermore all the custom plugin events are available only to developers, not server owners.

Adding CustomEvent with a name and properties map would allow developers to provide a very simple and quick way of both notifying and listening to events.

Lets say we have a teleportation plugin which teleports any player to a specified location. We also have a ChetShop plugin and a Message plugin. Now, using CustomEvent and CustomEvent transformer this is possible:

CustomEvent tranformer config:
------
me.mychestshop.chestshopcreatedevent:
 name: "myteleportator.teleportation"
 properties: ["to=${{location}}","player=MainAdmin"]

me.mychestshop.chestshopcreatedevent:
 name: "mymessage.message"
 properties: ["message=Player ${{creator}.{getName()}} created chestshop"]

Now:
Player p1 creates a shop at location loc1 -> (custom event is called) CustomEvent("me.mychestshop.chestshopcreatedevent", Map["location"=loc, "creator"=p1]) -> (custom event transformer catches custom event and creates new events) CustomEvent transformer -> (custom events are caught by teleportation and messaging plugins) MainAdmin is teleported to shop creator and is told that player p1 has created it.

This is just a quick example. If sponge will have a CustomEvent like that and devs will be advised to use it it will be very easy for server owners to link events between plugins.

**Comment by Zidane** [comment]
I get the jist of your idea but others may not.

Put together a proper gist to explain the code better.

**Comment by ST-DDT** [comment]
If i got you right you want something like this:
````java
// Setup
registerEventTransformer({SomePluginEvent -> OtherPluginEvent});

// Called somewhy
callEvent(new SomePluginEvent());

// Triggered Result
callEvent(new OtherPluginEvent());
````

So basically you setup up some event transformations. (Code wise or config wise)
Somewhy the base event of the transformer is called, the transformer gets to know this, converts it to your event and calls this as well.

**Some things to consider:**
- When is that event called? (Priority)
- is the event called if the main event is cancelled?
- Which values are send to the new event in case its a mutable event?
````java
long someValue = 42;
Event mainEvent = new MyXEvent(42);
callEvent(mainEvent);
[..]
assert mainEvent.getValueX() == transformedEvent.getValueX();
mainEvent.setValueX(21);
assert mainEvent.getValueX() == transformedEvent.getValueX(); // Pass or fail?
assert transformedEvent.getValueX() == 21; // Pass or fail?
````
- are values exchanged between events if the result event is mutable?
````java
assert mainEvent.getValueX() == transformedEvent.getValueX();
transformedEvent.setValueX(42);
assert mainEvent.getValueX() == transformedEvent.getValueX(); // Pass or fail?
````

**Code**
Here some example code, how i image @blackalegator 's suggestion could look like:
(Please correct me if i got your suggestion wrong)

**EventTransformer**
````java
public interface EventTransformer<E extends Event> {

    Event transform(E event);

}
````
**EventRegistry**
````java
// Maybe GameRegistry or GameDictionary
public interface EventRegistry {

    <E extends Event> void registerEventTransformer(Class<E> eventClass, EventTransformer<? super E> transformer);

    // Maybe as EventTransformerBuilder
    <E extends Event> EventTransformer<E> from(String name, Class<E> baseClass, Class<? extends Event> targetEvent, Map<String, String> variableMapping, EventPriority triggerPriority, boolean ignoreCancelled);

}
````
**CustomEventTransformer**
````java
public final class CustomEventTransformer<E extends Event> extends EventTransformer<E> {

private final String name;
private final Class<E> baseClass;
private final Class<? extends Event> targetEvent;
private final Map<String, VariableResolver> variableMapping;

    public CustomEventTransformer(String name, Class<E> baseClass, Class<? extends Event>     targetEvent, Map<String, String> variableMapping) {
        this.name = name;
        this.baseClass = baseClass;
        this.targetEvent = targetEvent;
        for (Entry entry : variableMapping) {
            this.variableMapping.put ( entry.getKey(), createVariableResolver(baseClass, entry.getValue());
        }
    }

    public Event transform(E event) {
        try {
            Map<String,Object> variables = new Map();
            for (Entry entry : variableMapping) {
                variables.put ( entry.getKey(), entry.getValue().resolve(event));
            }
            return SpongeEventFactory.createEvent(targetClass, variables);
        }  catch (Exception e) {
            throw new EventTransformationException("Error in CustomEventTransformer " + name + " (" + baseClass.getName() + " -> " + targetClass.getName() + ")", e);
        }
    }

    static VariableResolver createVariableResolver(Class<?> clazz, String name) {
        String.split.each{field/method -> function}
    }

    // Only grants access to public methods, that are definitely available in the classes/interfaces.
    static class VariableResolver {
        private List<Function<Object,Event,Object>> functions;

        public Object resolve(Event event) {
            Object result = event;
            for (Function function : functions) {
                result = function(result , event);
                if (result == null) {
                    return null;
                } else if (result instanceof Optional) {
                    if (result.isPresent()) {
                        result = result.get();
                    } else {
                        return null;
                    }
                }
            }
            return result;
        }
    }

}
````

**Comment by Bammerbom** [comment]
I really like this idea, custom events made simple.

**Comment by gabizou** [comment]
Personally, this sounds a lot like a plugin based api more than a SpongeAPI idea. The functionality provided by having these `json` event transformers is entirely an implementation detail, and having this dynamic checking on events is something I'm not confident about being stable.

In my opinion, I'd rather see this as a plugin library than in SpongeAPI, regardless how well it works out.

@SpongePowered/developers for more comments.

**Comment by Aaron1011** [comment]
I really don't think this is necessary.

The reason Sponge uses interface for events is twofold:
* Forge events are able to implement Sponge events. This would otherwise require modifying the superclass of the Forge event, which would be problematic,
* More complicated class hierarchies are able to be created. For example, `EntityCollisionEvent` is able to extend `EntityEvent`, `CauseTracked,` and `Cancellable`.

Plugin developers are under no obligation to use interfaces for their events. In fact, it's usually simpler to just create an ordinary class which extends Event. This class can be posted on the event bus, just like a Sponge event is.

While I can see the benefits of allowing server owners easier access to events, this is best left up to a plugin. I don't feel that there's any need for a `CustomEvent` class, when plugins can simply create their own.

**Comment by Aaron1011** [comment]
Closing this issue, as I believe it's been resolved. If this is still a problem, feel free to re-open this, or create a new issue.
