### ISSUE TITLE
Add a simple way to copy and save a default configuration

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#457]
In Bukkit, the default plugin config was automatically backed by the default `config.yml` in the jar file.
To save the default config, only these **2 lines** were necessary:

``` java
plugin.getConfig().options().copyDefaults(true);
plugin.saveConfig();
```

It would be nice to have something similar in Sponge.

How it works right now (**13 long lines**):

``` java
@Inject
@DefaultConfig
ConfigurationLoader configLoader;

@Inject
@DefaultConfig
File configFile;
...
//load defaults
URL defaultsInJarURL = this.getClass().getResource("/defaults.conf");
ConfigurationLoader defaultsLoader = HoconConfigurationLoader.builder().setURL(defaultsInJarURL).build();
ConfigurationNode defaults = defaultsLoader.load();

//load config & merge defaults
if (!configFile.exists()) configFile.createNewFile();
ConfigurationNode config = configLoader.load();
config.mergeValues(defaults);
configLoader.save(config);
```

I think the best solution is to specify the `URL` to the defaults resource.
This could be a field of the `@DefaultConfig` annotation or the `@Plugin` annotation.

**Comment by Zidane** [comment]
@zml2008 

Could you look into this?

**Comment by Zidane** [comment]
@zml2008 any progress on this?

**Comment by zml2008** [comment]
Because of how Sponge handles configs, this can't be done the same way. I am thinking the best way to work with this is to add another annotation, possibly `@BundledConfig` that gets the bundled config from the plugin's jar (as a configuration loader). That shortens it to 3 lines.

By default, the default file would be at `<main class package>/default.conf`.

**Comment by MattBDev** [comment]
Are you sure there isn't a better way to do this than having an extra annotation? It would be a bit annoying to add another annotation for configs.

**Comment by SonarBeserk** [comment]
@MattBDev by my understanding you would use the BungledConfig instead of DefaultConfig. So not another always required, just another variant you can use.

**Comment by MattBDev** [comment]
@SonarBeserk I understand it wouldn't be required but I feel that a lot of plugins will be using a bundled config since it is what most of them have been doing in Bukkit. If the plugin wants to have it's own folder and other things you might want to do when loading the config, you will have most likely more than 3 annotations just to grab or load the config.

**Comment by SonarBeserk** [comment]
Or they will implement something different? For example im forgoing the whole system in favor of using configurate basically standalone so i can avoid implementation decencies.

**Comment by gabizou** [comment]
@zml2008 Is this still applicable? If I remember correctly, you can set defaults with configurate and such.

**Comment by gabizou** [comment]
Closing as this is a Configurate related issue more than SpongeAPI.

**Comment by gabizou** [comment]
Reopening as this can be easily handled.

**Comment by gabizou** [comment]
@Zidane You were saying this is easily handled?

**Comment by windy1** [comment]
I would like to propose a different approach. I think we should add a method in the API that standardizes plugin resource retrieval so I could do something like `plugin.getResource("default.conf")` and it would automatically resolve to `<package>/default.conf`.

**Comment by Minecrell** [comment]
@windy1 It would be probably a good idea to open a new issue for that together with the other points that were already mentioned in #1081.

**Comment by windy1** [comment]
Use Asset API for this.
