### ISSUE TITLE
Clarify behavior of multiple results for Recipe

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#463]
The `Recipe` interface (and the corresponding shaped and shapeless builders) allows multiple `ItemStack`s to me specified as the recipe result.

While it's entirely possible for a mod to define a behavior for this, Vanilla has no concept of multiple results for a recipe. While Cake is handled specially, with milk buckets being replaced by empty buckets, this can't be applied to recipes in general.

Some behavior, such as using the first `ItemStack` in the results list, should be defined and specified in the javadocs.

**Comment by JBYoshi** [comment]
Technically, there is only one output. It's just that filled buckets have the empty bucket specified as a "container item" that is returned once used in a crafting recipe.

**Comment by kenzierocks** [comment]
@JBYoshi that's why it's a special case. Some mods do have custom recipes that give two outputs, like the pulverizer in Thermal Expansion.

**Comment by JBYoshi** [comment]
@kenzierocks Oh. I guess I missed that part. Plus, there are brewing recipes - 2-4 inputs, 1-3 outputs.

**Comment by gabizou** [comment]
Perhaps the results as well need to change from using `ITemStack` to `ItemStackSnapshot` as well.

**Comment by Aaron1011** [comment]
I think this is addressed in @kashike's pr.

**Comment by gabizou** [comment]
> I think this is addressed in @kashike's pr.

From what I could read, it wasn't fully addressed in the PR. It addresses aisles for the locations of where `ItemStackSnapshot`s need to be placed for a recipe to be satisfied, but that's about it.

**Comment by parlough** [comment]
@faithcaio was this solved with your PR?
