### ISSUE TITLE
Tab complete - SimpleDispatcher

### ISSUE THREAD

**Issue by verbeto** [SpongePowered/SpongeAPI#472]
In SimpleDispatcher.java, we are getting a list of tab complete options but never actually adding them to the result list. We should change line [341](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/command/dispatcher/SimpleDispatcher.java#L341) from:
```java
mapping.get().getCallable().call(source, parts.length > 1 ? parts[1] : "", Collections.unmodifiableList(passedParents)));
```
to:
```java
suggestions.addAll(mapping.get().getCallable().call(source, parts.length > 1 ? parts[1] : "", Collections.unmodifiableList(passedParents));
```

**Comment by Bammerbom** [comment]
Why don't you create a PR?

**Comment by boformer** [comment]
That's right, but you forgot one thing:
We have to append ``parts[0] + " "`` to every suggestion the subcommand delivers, then add them to the list.
