### ISSUE TITLE
CommandSource for /execute and signs

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeAPI#473]
Right now we have `Player`, `ConsoleSource`, `CommandBlockSource` and `RemoteSource`, but there is no `CommandSource` for commands called with the execution of the `/execute` command.

There should be a special `CommandSource` for these senders with a method for getting the sender of the command (another `CommandSource`) as well as the entity the command is being executed for.

**Comment by AlphaModder** [comment]
Seems like we would only need an EntitySource, and the concept of a Command causing another might be implemented into CommandEvent somehow?

**Comment by Minecrell** [comment]
The `CommandSource` for `/execute` commands is special because it gets executed for an entity, but the permissions and messages sent to this command source are actually getting redirected to the original sender of the `/execute` command. So this couldn't be represented using a simple `EntitySource`.

**Comment by AlphaModder** [comment]
@Minecrell Ah, that is interesting. I'm not sure of a good way to solve it.

**Comment by ST-DDT** [comment]
I don't see a problem here. Java's Proxy feature will probably be good enough here to cover that up to a certain level. The Proxy would then just forward all method calls to the target entity except the permission ones.

IMO this can and should be included in the API. Maybe with the help of a static method.

````java
CommandSource rewardPermissions(Object target, CommandSource permissionHolder) {
    Set<?> spongeAPIInterfaces = getSpongeAPIInterfaces(target);
    spongeAPIInterfaces.add(CommandSource.class);
    return (CommandSource) Proxy.newProxyInstance(target.getClass().getClassLoader(), spongeAPIInterfaces.toArray(), new PermissionInvocationHandler(target, permissionHolder));
}
````

That way all (most) of the `instanceof` checks will still work.

**Comment by Minecrell** [comment]
Looks like we also need a `CommandSource` for commands executed by clicking a sign as these get executed with the name of the player who clicked the sign but with all permissions. Should have methods to get the sign and the player.

**Comment by zml2008** [comment]
On the topic of expanding CommandSources known to the API, I would like to have a LocationCommandSource that any command source attached to a location (player, commandblock, ExecuteAtCommand) would implement -- this gives added context to commands that wish to get the location of an arbitrary command source.

**Comment by zml2008** [comment]
So I think everything except signs have command sources, but signs are just weird, so that probably needs a redo?

**Comment by modwizcode** [comment]
I just fixed signs in SpongeCommon by making the implementation for Signs work just like CommandBlock. The provider for signs provides the entity for the player with a permission set to always return true. I believe signs can just be a CommandBlockSource (which needs to be made to be more generic) since signs actually work just like CommandBlocks in most cases, including a success store.

**Comment by JBYoshi** [comment]
See my PR #744.

**Comment by zml2008** [comment]
Yep, this was added with #744
