### ISSUE TITLE
Access to WorldType and usage of it in Server.createWorld()

### ISSUE THREAD

**Issue by dpatron** [SpongePowered/SpongeAPI#479]
Currently you don't have access to WorldType (AMPLIFIED, FLAT, LARGE_BIOMES, DEFAULT etc.) and can't set it in createWorld(). I think it is needed in order to grant a >basic< customized worldcreation (beside the usage of WorldGenerator).

Path in Minecraft: net.minecraft.world.WorldType

**Comment by kenzierocks** [comment]
You're looking for dimension types I think.

**Comment by dpatron** [comment]
DimensionTypes include End, Nether and Normal - not the WorldType.

**Comment by boformer** [comment]
That's right. Additionally, there is also no way to set the config string of the flat generator (x layers of stone, y layers of grass, villages...).

Is this something that can be set independently from the the world generator, or is every value bound to a specific vanilla generator?

I know that Bukkit had a WorldType enum. You even had to set it when using a custom generator, which was kind of senseless.

**Comment by uxsvent** [comment]
in 1.8 vanilla there is a limited generator that lets you choose biome and othe ore gen stuff. is there a way to tap into that code?

**Comment by Zidane** [comment]
@bloodmc You typically don't do API but you are focused on this currently. Thoughts?

**Comment by Zidane** [comment]
Closed as this is handled in Deamon's branch.
