### ISSUE TITLE
Add TextStypes Class 

### ISSUE THREAD

**Issue by frogocomics** [SpongePowered/SpongeAPI#486]
I believe the SpongePowered team should add a TextStyles class. This class would be used to make font obfuscated, bold or in italics. If I were to create a bold "Hello World" message in GREEN, this is what I would do:
```java
public Message createExampleMessage() {
    return Messages.builder("Hello World").style(TextStyles.BOLD).color(TexttColors.GREEN).build();
}
```

**Comment by boformer** [comment]
https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/format/TextStyles.java

**Comment by frogocomics** [comment]
How could I implement this into a Message? I dosen't say on the documentation!

**Comment by kenzierocks** [comment]
Check out the Text API 2. #425

**Comment by gabizou** [comment]
Also, you need to use a [`MessageBuilder`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/message/MessageBuilder.java#L68).
