### ISSUE TITLE
Rethink permissions

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#494]
I am suggesting 2 changes for the permission system:

**1. Allow explicit permission inheritance**
Use case: A plugin has 100+ permissions. Some of them are typically for admins, some for moderators, some for trusted and some for new players. The plugin dev wants to add some "super permissions" for these user types. Server admins can then decide if they want full control or use the predefined perm sets.

**2. Use ``node.*`` notation for implicit inheritance**
This gives plugin devs a lot more flexibility how to define their permissions. It makes implicit inheritance optional, which is better than forcing it.

More about this issue:
https://forums.spongepowered.org/t/permission-inheritance-and-command-flags/6255

**Comment by Minecrell** [comment]
This is probably something for @zml2008

**Comment by zml2008** [comment]
1. Allowing explicit permissions inheritance allows setting up nodes that may assign nodes to a user that would be unexpected.

If you want a specific node to default to false no matter what any parent nodes say, you can do that in your plugin using the default SubjectData (PermissionService#getDefaultData) 

2. Why have the .* -- In like >95% of cases this is what users want, and in the other <5%, manually force a permission to false using the default SubjectData -- users can override that on their own.

**Comment by boformer** [comment]
> Allowing explicit permissions inheritance allows setting up nodes that may assign nodes to a user that would be unexpected.

Why do you want to limit the system? 

> Why have the .* -- In like >95% of cases this is what users want

As a server admin, I want to limit the permissions of a player to the basics. When there is no ``.*`` notation, the system forces me to always use implicit inheritance. This will cause a lot of problems, when a server admin assigns ``example.cmd.tp``, which includes **``example.cmd.tp.self``** (What the admin actually wanted), ``example.cmd.tp.other`` (Teleport other player to target player)  and ``example.cmd.tp.here`` (Teleport other player to you).

It also makes the permission strings for basic command access longer: ``example.cmd.tp.self`` instead of ``example.cmd.tp``.

**Comment by zml2008** [comment]
It's not an artificial limit on the system -- It's a larger API, more complexity for permissions plugins, and if explicit inheritance were to be supported potential confusion for users.

There is nothing inherently more problematic about implicit inheritance -- you're just choosing example permissions that are bad. You could argue that explicit inheritance prevents plugin developers from using an explicit * in their permissions with your vision just as easily

**Comment by TheE** [comment]
@zml2008 While I get your point, the example permissions @boformer choose resemble a standard case that is present in various plugins. For example, see my question like above or the following example taken from CommandBook:

| Command  | Permission |
| ---- | ---- |
| /more [-a] [-i] [target] | commandbook.more <br/>commandbook.more.infinite |

With commandbook.more a user also gets access to the [i] flag witch is not intended. What is the best practice in such a case, should we use a permission such as commandbook.more.more instead?

**Comment by zml2008** [comment]
For commandbook.more.infinite, in your plugin initialization do:
```java
permissionService.getDefaultData().setPermission(SubjectData.GLOBAL_CONTEXT, "commandbook.more.infinite", Tristate.FALSE);
```

**Comment by ryantheleach** [comment]
@zml2008 , would registering the default permission that way interfere with permissions plugins persistence of permissions, or would it somehow be transient or overridden since it was called in the plugin initialization? And if so, at what lifecycle event should they be declared in?

**Comment by zml2008** [comment]
The default data exposed in the API is entirely transient, so won't persist. You can really register default perms at any time, so just do them with the rest of your plugin init.
