### ISSUE TITLE
Event on flight (possibly when it toggles?) for Player

### ISSUE THREAD

**Issue by Outfenneced** [SpongePowered/SpongeAPI#497]
I recently noticed while porting one of my previous plugins that there isn't an event that triggers when a player starts and/or stops flying. Currently, the only current method of constantly knowing a player's flying status is to check on a movement event. The addition of a flight toggle or activation and deactivation event would eliminate the need for constant checks.

Edit: From what I can tell from Bukkit's old code, the implementation of this originally came from listening for the abilities update packet and checking if the new value of flying is the same as the old flying value. This packet, I believe, is 0x39 and the data is in bit 1 of the Flags field, might also be 0x13.

**Comment by cheddar262** [comment]
From what I can tell from Bukkit's old code, the implementation of this originally came from listening for the abilities update NBT packet and checking if the new value of flying is the same as the old flying value.

**Comment by Zidane** [comment]
I don't see an issue with adding an event, especially if it means you no longer have to check the movement event (which is silly but I understand why).

Question is, how would the event look like? An event for just checking flight seems too focused; perhaps an event for when a human entity invokes an "ability"?

**Comment by gabizou** [comment]
I think we need to represent some sort of `HumanCapabilities` to have a proper event. This way too, when capabilities (such as canEditWorld) change, all plugins can handle properly.

**Comment by cheddar262** [comment]
The abilities packet, from what I can tell through my albiet small amount of research, is only sent to the server when the player starts or stops flying. Everything else is handled server-side as far as capabilities go except for jumping and there's a separate packet for that.

**Comment by ST-DDT** [comment]
Sure we need a proper API for jumping too but both abilities are quite different.
One is a single time jump event.
The other is a half permanent fling state which can be toggled.

**Comment by cheddar262** [comment]
I was just stating that a human capabilities event type thing would require separate triggers with my last post.

**Comment by ryantheleach** [comment]
If possible onGround events would be useful as well. allows for fall distance tracking and other flying checks.

**Comment by gabizou** [comment]
Closing as it will be implemented by #596 (Since flying is a data manipulator being added/removed from a data holder).
