### ISSUE TITLE
SignChangeEvent lacks information about Player causing it

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeAPI#498]
There are quite a lot of plugins which rely on signs containing a certain messsage, WirelessRedstone and TrainCarts being some more notable examples. Those plugins verify that only users permitted to do so can create those signs.

For those plugins it is invaluable that the SignChangeEvent provides which Player edited the sign - my proposal is that SignChangeEvent gets a `public Optional<Player> getPlayer()`, that will return an `Optional.of()` the player editing the sign if there is any or `Optional.absent()` if it was caused by something else.

This method should probably also be included in other events that can be caused by players.

**Comment by me4502** [comment]
Fixed in 0f3b893
