### ISSUE TITLE
Update events to use Inventory API

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#499]
Several events, instead of using the Inventory API, deal directly with `ItemStack`s and slots. They need to be updated to use the `Inventory` interface.

A non-exhaustive list:
* EntityEquipmentChangeEvent
* EntityEquipEvent

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeAPI/commit/c1be53498c9920ac3f9bd29a55e293ee160744bc
