### ISSUE TITLE
Teleportation API

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#504]
While [`Entity`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/Entity.java#L74) can be teleported to any location, there isn't any API to represent Portals and portal related teleportation.

What is needed is a form of `PortalType`(s), creation and destruction related events, and an actual interface to interact with the `Portal`.

More to come as the issue is discussed.

**Comment by phase** [comment]
I'd love this.
```java
Portal p = new Portal(x, y, z);
Location from = p.getFrom();
Location to = p.getTo();
```
Just some examples.

And for PortalType, how about a `TO` & `FROM`?
```java
public enum PortalType{
    NETHER_TO, NETHER_FROM, END_TO, END_FROM;
}
```

Just some thoughts on it.

**Comment by Xemiru** [comment]
@phase problem with instantiating a new portal is that assumes that creating the instance immediately generates it in the world, if it doesn't already exist, which shouldn't be assigned to creating an instance. plus, that's missing a world argument, and even if its fulfilled it should just be a location argument instead. the more probable thing to happen is for it to be a tile entity that holds `PortalData` representative of the target location to teleport to.

`PortalType` on the other hand, is in the same boat. having a from and to value doesn't seem so clean, and establishing an enum assumes that they'll be the only types of portals to exist. remember, sponge aims to support mods, so assuming such invalidates the goal.

**Comment by ST-DDT** [comment]
What are the benefits for FROM and TO?
Portal in the default world and in the nether?
Which portaltype would i use if i place it in the end to teleport me to a sky island? Or from one Nether to another nether?

On the other hand the new portal feature sounds cool although i would not us it the proposed way.
World.createPortal(Vector3i bound1, Vector3i bound2, @Nullable Location target, PortalType type) or using a builder pattern.
Creating the portal would autimatically create the portal blocks or asume the portal blocks already exist. The portal blocks would then store the target in their data. Anything else that can be stored in the `PortalData`?
This way plugin and mods could store portal targets inside the blocks and could be exchanged without loosing any portals.

@Xemiru
Is the NetherPortal a Tile too? I havent seen a Tile class for it yet.

**Comment by Xemiru** [comment]
@ST-DDT no, that was me giving a prediction as to how this is probably to be done. none of what i said exists (as of current time)

**Comment by ST-DDT** [comment]
I know. I was just wondering why NetherPortal does not exist yet. And if it isnt a Tile for any reason it is less likly to become one just because we would like to attach some data to the block.
But you are right there will be a PortalData class for sure.

**Comment by thomas15v** [comment]
@ST-DDT I wouldn't make that in the World class. Looks more like a service to me.
@Xemiru Can't we use a blockstate properties to store the location of the portal. So far I know every block has them.

**Comment by ryantheleach** [comment]
blockstate properties are immutable, and changing them would fundamentally change the block type.

Thery are more a way of describing and transforming one blockstate to another.

**Comment by ST-DDT** [comment]
Maybe he was referring to block data the mutable counter part of properties.
if the portal frame targets somewhere else it is actually a different behaviour of that block. And changing the target totally changes the properties/data of the block like opening a fence.
Im not sure but by the time the comment was made the data API did not exist or was introduced shortly before.

**Comment by ryantheleach** [comment]
I figured he was using it in the MCP/Mojang term.

**Comment by Gaelan** [comment]
I don't know much about Sponge at all, but I'd think this could be implemented as a event which was called when a portal was entered (immediately for end portals, after the delay for survival players in nether portals) which could override the default behavior and send the player anywhere.

**Comment by ST-DDT** [comment]
AFAIK you can already use an event to change the teleportation target, but this is more or less about permanently changing the target of a portal without modifying any events every time.

**Comment by JBYoshi** [comment]
Would it (could it?) support mod-added portals?

**Comment by gabizou** [comment]
We've already added something for this in the [refactor/event-names](https://github.com/SpongePowered/SpongeAPI/compare/refactor/event-names).

**Comment by gabizou** [comment]
This should've been closed with the addition of `TeleporterAgent`.
