### ISSUE TITLE
TranslationRegistry

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeAPI#512]
The `TranslationRegistry` serves three main goals.

- Collect all plugin's translations
  - Adds an export function, so you can put the generated language files in your resource packs without searching all your plugins for language files
  - Helps servers with a lot of plugins
  - Access point for the potential Sponge client plugin, to get all translation without using a resourcepack
- Avoid plugin code to show the right language's message to the user.
  - The plugin does not know whether the user has the translations file, so the plugin uses Text.Literal directly, to avoid issues. (Currently)
  - Helps small plugins and servers
  - Increases the likelihood to have more plugins with multi-language support
- Replace `Translation` with the real text on the server side to avoid issues with missing resource packs
  - In case the server owner did not include the translations in the resource pack (on purpose)
  - In case the user did not download the resource pack or there is none.
  - in case the user did not have the potential Sponge client plugin

Here is a small draft containing the methods i thought that could be included in the `TranslationRegistry`:

````java
/**
 * Stores translations
 */
public interface TranslationRegistry {

    // All translations registered via {@link #register(String, Locale, String)}
    Collection<Translation> getCustomTranslations();

    // The fallback order to use if a translation for a given language does not exist.
    // All languages with translations will be added to the given list (internally) if not present
    void setFallbackOrder(List<Locale> locales);

    // The fallback order to use if a translation for a given language does not exist.
    // includeUnspecified whether languages without specified order should be returned as well
    List<Locale> getFallbackOrder(boolean includeUnspecified);

    // Registers the translation Id with the replacement text for the given language
    Translation register(String translation, Locale language, String text);

    // Translates the given object to the given language using the given arguments
    // Throws IllegalArgumentException if Translation is not registered here
    Text.Literal/String translate(Translation translation, Locale language, Object... args) throws IllegalArgumentException;

    // Gets the registered translations for the language
    Map<Translation, Optional<String>> getTranslations(Locale locale);

    // Gets the registered translations for the language including fallback entries
    Map<Translation, String> getTranslationsWithFallback(Locale locale);

    // Gets the registered translations using the fallback
    Map<Translation, String> getFallbackTranslations();

    // Set whether the messages should be replaced on the server side with the real text, 
    // to avoid issues with missing resource packs in the client
    void setReplaceTranslations(Player player, boolean replace);

    boolean isReplaceTranslations(Player player);

    // The Default value for every new player
    void setDefaultReplaceTranslations(boolean replace);

}
````

**Comment by boformer** [comment]
This is very important and would solve many issues.

I also think that the fallback order should be specified in the ``sponge.conf``.

**Comment by Minecrell** [comment]
@boformer Right now it is more important to get a stable API with implementation, additional utilities for plugins have no real use if you can't make plugins for a stable server base/API.

**Comment by zml2008** [comment]
Translations should mostly be done through Text instances. I have some stuff for translations using ResourceBundles/Gettext that I'll put in a PR over the next few days.

**Comment by boformer** [comment]
@zml2008 very nice :+1:

**Comment by ST-DDT** [comment]
If we use Text.Literal instances directly we can use only one language at the same time, which makes it difficult to send the right messages to a list of players. 
But i'm looking forward to see your solution to this issue.

**Comment by zml2008** [comment]
Covered by #563
