### ISSUE TITLE
Invisble entity suggestions

### ISSUE THREAD

**Issue by Lightoner** [SpongePowered/SpongeAPI#513]
Hi,
I have two suggestions:
- We can just set a living entity invisible, it would be great if we could hide all entity likes projectiles, items on ground...
- It would be great also if we can choose that when we hide a player we can remove or keep the player in tablist.
I made these suggestions because some people and also me encountred these problems with bukkit api.
Thanks,

**Comment by AlphaModder** [comment]
@Lightoner There is already a tab list API.

**Comment by Lightoner** [comment]
It's a solution for the second point but I think it would be usefull and more simple if sponge can do this.

**Comment by simon816** [comment]
Pull request https://github.com/SpongePowered/SpongeAPI/pull/387 originally did this, but later changed to only set invisibility on Living entities because the vanilla renderer ignores the flag for non-living entities.
See https://github.com/SpongePowered/SpongeAPI/commit/4dd045122956e58ad8948cbf8da3dec9d11aa19a

**Comment by ST-DDT** [comment]
@Lightoner Why do you want to hide items/projectiles on the ground?
Some kind of hidden treasure?
If you just want to hide the projectiles after a big fight, then you should remove them directly.

**Comment by Lightoner** [comment]
I would like to do multiple fights in one arena.
So this why I don't want to hide the player in tablist and hide projectiles, items on ground...

**Comment by gabizou** [comment]
> I want to hide projectiles, items on ground.

You should remove entities when they're on the ground then.

**Comment by Lightoner** [comment]
In fight I would like to let's pick up item and see the projectile shot.

**Comment by gabizou** [comment]
As mentioned in the other PR, it isn't possible to set non-living entities to be invisible. It is not our intention to make changes such as this, let alone possible at this time.

**Comment by ryantheleach** [comment]
It sounds like instead of having multiple copies of an arena, Lightoner wishes to "shard" the world having players and entities only able to interact with players and entities in the same shard.http://www.wowwiki.com/Phasing

**Comment by Lightoner** [comment]
Yes.
Okay for the first point and the second ?

**Comment by AlphaModder** [comment]
@Lightoner Don't use invisibility for that, it's client side only. The entities are still seen by the client, they just aren't rendered.

**Comment by Xemiru** [comment]
@AlphaModder considering its packet manipulation, aren't they invisible to the client entirely? its not the same as applying thr potion effect. haven't worked with packets much, so excuse me if that's wrong.

**Comment by AlphaModder** [comment]
@Xemiru It's not packet manipulation. It's a flag on the entity that tells the vanilla renderer to ignore it.

**Comment by Lightoner** [comment]
For hide non living entity I am going to do likes EntityHider from protocolLib so. And for the tablist api, when I hide a player to another player I can re-add the player to the tablist and when I show the player I remove the player from the tablist and after sponge re-add the player to the tablist ?
But when I re-add the player to the tablist Can I Complete his name in chat or command ?
