### ISSUE TITLE
[ItemsAPI] Is it possible get custom data from mods?

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#514]
Is it possible get custom data from mods? Example: Bees from mod Forestry. Item Bees keeps the data about genes bee. I want to get these same data and write to the file. Next, create a bee with these genes.

**Comment by Zidane** [comment]
You can (multiple ways to go about it).

Care to comment @gabizou ?

**Comment by Azatik** [comment]
Right.

**Comment by gabizou** [comment]
It is very much possible, and I'll briefly explain two ways to go about the issue:

1) Someone creates a new `BeeGeneticsItemData` as a library that will handle bee data that plugin developers can now use to retrieve (highly recommended)

2) You read the raw data from `ItemStack#toContainer()` and then modify necessary data and use `ItemStack#setRawData(DataContainer)` to set it back.

**Comment by Azatik** [comment]
Thanks for the reply.

**Comment by ST-DDT** [comment]
@Azatik 
The magic keywords gabizou forgot to mention for 1) are:
`ItemStack`:
* `Optional<T> getData(Class<T> dataClass)`
* `Optional<T> getOrCreateItemData(Class<T> dataClass)`
* `ItemDataTransactionResult setItemData(T itemData)`

`T` always extends `ItemData<T>`

````java
public class BeeGeneticsItemData implements ItemData<BeeGeneticsItemData>
````

IIRC you have to register a serializer for your item data.
