### ISSUE TITLE
GameProfile custom component system

### ISSUE THREAD

**Issue by KieronWiltshire** [SpongePowered/SpongeAPI#517]
In Bukkit the Player object was really quite strict on what you could do, and you couldn't really customize it in any way, shape or form. There wasn't really any built-in methods to allow you to attach information to a user, so I decided to come up with a solution for Sponge.

The idea I came up with is the possibility to create custom components that you can attach to the GameProfile object so you can later retrieve the component when it is needed. The solution would be to attach it to the GameProfile object, an object which is specific to the Player.

I believe the idea of allowing custom components allows for a lot of flexibility in practise as well as clean and easy to work with code.

Here is how I could imagine the GameProfile handling the component system:
https://gist.github.com/KieronWiltshire/a0fc8094fa3b5919601f

Here is an example component that I created to maybe give you guys an idea of what a component could be used for:
https://gist.github.com/KieronWiltshire/f1700bdb7776c68460ec

**Comment by modwizcode** [comment]
Ping @SpongePowered/developers for input, not sure this is the best way, it's probably a common enough need, but I feel like a simple getData(PlayerExtension) would make more sense. Also I don't think this belongs on GameProfile, this is exactly what the User class is for.

**Comment by hypereddie** [comment]
Can multiple of the same type of component be added more than once to a player? Or is the idea to attach methods and functions to a player..?

**Comment by modwizcode** [comment]
@hypereddie Seems like the idea is attaching methods and functions, almost like the service API. If you notice, the example implementation uses a HashSet, so the concept would be that it's only attached a single instance.

**Comment by KieronWiltshire** [comment]
@hypereddie this all depends what developers need in general. I think in my opinion it would be better if only one type of component could be added to one player. It's exactly what @modwizcode said, it's for attaching methods and functions onto a User.

@modwizcode I thought about the User class but didn't really look into much of it. I thought the User class was the information stored on flat-file?

**Comment by hypereddie** [comment]
> I feel like a simple getData(PlayerExtension) would make more sense
I'm inclined to agree. If I understand correctly, getData does the same thing, so what difference would getComponent have compared to getData?

**Comment by KieronWiltshire** [comment]
@hypereddie I'm guessing it would work in a similar fashion to getData but the point was to make it obvious that it's a component, for example you could have a component which creates cool effects, but each player has different effects so you could attach a different EffectComponent to each player and just do something like what I've demonstrated below:

// on move event or whatever
player.getProfile().getComponent(EffectComponent.class).effect();

Now in my opinion, the name 'component' makes more sense here instead of data.

**Comment by modwizcode** [comment]
User is the class for information that is stored and available offline. If it only makes sense for online players than Player is the correct class. The implementation has nothing to do with what those classes are for. 

GameProfile is a particularly bad place, because it's remapped to Minecraft GameProfile objects in Sponge to solve a special case.

**Comment by hypereddie** [comment]
Yes but I feel like having a whole system dedicated to accomplish the same
task for just a name difference seems like a waste. I can see this as a
convenience method of the current getData system, but not a whole new
system...

**Comment by modwizcode** [comment]
I agree with @hypereddie on that point, it's really hard to see a use beyond something like adding getData. I cannot even deduce how to find a case where getData doesn't work just as well as this.

**Comment by KieronWiltshire** [comment]
@modwizcode Oh, I'm unaware really how Sponge works. I know that in Bukkit a new Player object was instantiated each respawn. I was under the impression that the Sponge implementation would work in a similar way.

@hypereddie I don't see how it's the same as getData()

**Comment by hypereddie** [comment]
@KieronWiltshire getData returns [data on the object that is not simply expressed by its basic type](https://github.com/SpongePowered/SpongeAPI/blob/838b3c7ef05278a72b1b3e5416cee237aa894e3b/src/main/java/org/spongepowered/api/service/persistence/data/DataHolder.java) which is similar to what the component system would do, it's just more generic.

**Comment by modwizcode** [comment]
I have no idea about Player object creation, but it's not a concern here.
GameProfile is fundamentally the wrong place. Also look at some of the
getData() things for Banners and Skulls and Books. They all do similar
stuff. Sure they may only shuffle values around, but that's not to say that
they cannot do more. What you're suggesting at it's core is a way to a
attach data to players.

**Comment by KieronWiltshire** [comment]
@modwizcode I guess so, you make a valid point.

@hypereddie but that interface only contains the getData method, it would be requirement that plugins be allowed to 'setData' as well as 'removeData' or whatever...

**Comment by modwizcode** [comment]
It seems clear you do not understand the data API. @gabizou did much of the
work with the data API, maybe they could provide an example of how you
would do this with the data API.

**Comment by gabizou** [comment]
There are several reasons why I'm marking this as `Invalid`:

- As @modwizcode has said, `GameProfile` is the wrong place for storing custom data associated with a Player. A `GameProfile` is exactly as it sounds, a profile with a UUID and last known name.
- There are better ways than just applying a "One-Size-Fits-All" solution of storing custom data to an element in the game, such as `User`.
- `User` would greatly benefit much more as the `DataHolder` for all extraneous special data that plugins would want to associate with a player since the `User` is always available, online and offline.
- There is a larger Data API plan that will vastly improve the usability of `DataHolder` and the attachment to Persistence API.

Overall, I appreciate the interest, but as @modwizcode has stated a few times now, your approach to the problem wasn't adequate.
