### ISSUE TITLE
Improve Javadocs: Project and Package descriptions

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#520]
To make the javadocs more self-explaining, there should be a project description that is displayed on the index page (overview.html).

The description can also include a link to the SpongeDocs.

Also, there should be a description for every package (package-info.java).

**Comment by phase** [comment]
Isn't that what the SpongeDocs are for?

**Comment by Xemiru** [comment]
@phase not necessarily, the docs are for explaining things in a way that's more user-friendly, for all the n00bies, whether its Sponge or development in general (to some extent). this is just for extra clarification of the project, and parts of it. not so important, but it doesn't hurt to add it either.

**Comment by gabizou** [comment]
Usually the packages are pretty self evident. What more description would a package gain?

**Comment by boformer** [comment]
@gabizou the Bukkit docs are a good example: http://www.javaminecraft.com/bukkitapi/overview-summary.html

The package description can contain a link of a related class (e.g. player events --> ``Player``) and describe the contents of a package.

I don't think that all package names are self-explaining.

**Comment by ST-DDT** [comment]
This overview is really nice. I would love to see something similiar for sponge as well.

Especially the following packages could benefit from this: 
* util.gen
* world.gen
* util.reflect
* text.translation.locale
* service.sql
* world.storage
* status
* persistance.data
* block.meta
* block.data

For some you can guess them but others may be confusing due to their similar names.

**Comment by AgentTroll** [comment]
I'd like to see this implemented

**Comment by ST-DDT** [comment]
Anyone willing to do this? Or is this something the team would do?

If not I would offer my help on this.

**Comment by boformer** [comment]
This is an open source project. Just go ahead ;)

**Comment by ST-DDT** [comment]
The current progress for package javadocs: ~50% ([Compare](https://github.com/SpongePowered/SpongeAPI/compare/master...ST-DDT:JavaDoc))

If you have any wishes or suggestions please tell me so i can add them soon.

**Comment by boformer** [comment]
"Classes" is maybe a bad word (though the Bukkit javadoc also uses the word). Many parts of the API are actually interfaces 

Very nice work! I think this really improves the quality of the javadoc!

**Comment by AgentTroll** [comment]
"Classes" describes Java-specific file best, i.e. you wouldn't say "This .java file does yadayada ydada" but "This class does yada yada yada".

**Comment by ST-DDT** [comment]
**Done**. Anyone wants to suggest some changes before i create a PR?
~130 package-info.java files

**Comment by AgentTroll** [comment]
Possibly highlight some important classes in that particular package possibly?

**Comment by ST-DDT** [comment]
I linked a lot of classes, but i could not export it to github. You can see the links when following the "Compare" link above the list.

**Comment by AgentTroll** [comment]
Ah I can understand that.

**Comment by ST-DDT** [comment]
Java only shows the first sentence in the listing so i focussed on writing that part.

I also thought about adding some examples for each paackage, but I'm lacking knowledge on some of the packages and i also don't know whether that will get appreciated.

[Data API Example](https://github.com/ST-DDT/SpongeAPI/blob/JavaDoc/src/main/java/org/spongepowered/api/data/package-info.java#L32-44)

**Comment by boformer** [comment]
Very nice!

**Comment by Deamon5550** [comment]
Don't include examples.

**Comment by ST-DDT** [comment]
I created a PR for this:
https://github.com/SpongePowered/SpongeAPI/pull/757

**Comment by Zidane** [comment]
Now apart of the OCD list.
