### ISSUE TITLE
CLA for protection?

### ISSUE THREAD

**Issue by phase** [SpongePowered/SpongeAPI#521]
Since one of the main goals of Sponge was to be more legally stable than Bukkit, hence the LLC, why not have a [CLA](https://www.clahub.com/pages/why_cla)? [`github/linguist`](https://github.com/github/linguist) uses it, and it makes contributions safer.

**Comment by simon816** [comment]
See https://github.com/SpongePowered/Meta/issues/19

**Comment by phase** [comment]
Ah, ok. :P
