### ISSUE TITLE
Update to MC 15w14a/1.10

### ISSUE THREAD

**Issue by sam4215** [SpongePowered/SpongeAPI#527]
Mojang's latest update has changed a few mechanics of Minecraft. I'd like some feedback to Sponge updating ASAP. First, a PR should be opened soon to support the love system. A PlayerDamageEvent is no longer needed, and the Entity Component System will need to update. Quite a few new Block Types will be needed.
Happy April Fools everyone :D

**Comment by gabizou** [comment]
You forgot #526
