### ISSUE TITLE
Add a way to control entity knockback

### ISSUE THREAD

**Issue by Xemiru** [SpongePowered/SpongeAPI#538]
Some plugins, like the ones that modify combat, want to be able to control the knockback of, or caused by the player(s). I think a method like `setKnockback(float)` and/or `setKnockback(float, Predicate<Cause>)` as ways to set the knockback of an entity against a specific situation or in general (the specific taking priority over the general case) would be good for this.

Use Cases:
  - The server owner thinks the default knockback of players are too small. The knockback is set to 1.2x the normal.

``` java
player.setKnockback(1.2F);
```
  This means that the player now takes 1.2x knockback from all non-specific cases.

  - A special weapon that disables knockback of the target now exists, thanks to a plugin. Targets are told to take 0 knockback from a cause that is an Entity of the type ArmorEquipable holding the special weapon.

``` java
target.setKnockback(0F, new Predicate<Cause>() {
    public boolean apply(Cause cause) {
        //let's pretend that item.matches exists as a method that checks whether or not its the special item.
        if(cause instanceof ArmorEquipable && item.matches(((ArmorEquipable) cause).getItemInHand()) {
            return true;
        }

        return false;
    }
});
```

Knockback values should not persist over server restarts; cleanup might be messy.

**Comment by gratimax** [comment]
Seems absolutely perfect as an event or event property, that's why we have them at all.

**Comment by Xemiru** [comment]
Perhaps maybe an `EntityVelocityEvent`? Damage isn't always causing knockback, walking into a cactus is an example.

**Comment by ryantheleach** [comment]
http://minecraft.gamepedia.com/Attribute generic.knockbackResistance would solve ``player.setKnockback(1.2F);``

**Comment by ST-DDT** [comment]
The Attribute API is already able to solve this issue:
https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/attribute/Attributes.java

**Comment by ryantheleach** [comment]
@ST-DDT That was my point.

The event specific stuff could be handled by the damage/knockback changes being introduced in [WIP] Cause Enchancements.

**Comment by gabizou** [comment]
Note that this can likely be included as a knockback modifier on the `EntityDamageEvent` in #712. Having worked on Data API, I don't think it's valid for this to be data, but rather an event based value.

**Comment by TheRaspPie** [comment]
Maybe we should really add an `EntityVelocityEvent` because plugins can assign velocity to an entity.
Then `EntityDamageEvent` would need to inherit from it.
@Xemiru Walking into a cactus would just give you a knockback of 0.

We should also consider that we are not talking about "knockback" here, but instead about "<b>knockback change</b>". If a player hits an entity that already has a velocity in another direction, <i>the two add up and now the entity's velocity is the sum of the two</i>.
Maybe we should include a method to turn this "adding" behaviour off?

**Comment by Xemiru** [comment]
@TheRaspPie Hence why I mentioned it as something that doesn't cause knockback, but still causes damage. `EntityDamageEvent` shouldn't inherit `EntityVelocityEvent` for that reason--fire damage is another example of the former.

The best way to disable vanilla's action of modifying the knockback result would probably be through the event callback system; although doesn't exactly give us control of the final resulting velocity _through the event._

**Comment by gabizou** [comment]
This can now be controlled by the new [`AttackEntityEvent#setKnockback`](https://github.com/SpongePowered/SpongeAPI/commit/ee405ed4cdc4fcf5e384e8682e6eb19dfa278309#diff-a083e8302939e7f80fab18c972d8cf2cR142).
