### ISSUE TITLE
More useful Extent hierarchy

### ISSUE THREAD

**Issue by maxov** [SpongePowered/SpongeAPI#546]
Issues like #319, #453, and #540 point to me that the extent system is rather ill-defined and could serve from some splitting-up in terms of behavior.

My idea of locations, extents, and worlds has solidified because of issues like the ones I have pointed out. There's several interesting properties that are served by extents, what follows is some thoughts I have on those properties, not necessarily in any order:
- All extents I can think of have a 3D cartesian coordinate system. In some cases, manhattan distance is used instead of euclidean distance to calculate certain things, like light level and AI.
- The "base" extent is World. Every extent currently available in the Sponge API is either grounded by or is a world (which makes me wonder if a schematic extent or ways to construct block buffers would be interesting...). Chunks belong in worlds, "Regions" belongs in worlds, and any kind of "selection" (think WorldEdit) also belongs in a world.
- Some sub-extents like chunks define coordinate transformations for convenience. So, for instance, blocks can be located based on some corner of the chunk. Other extents like selections do not.
- Some (if not most) sub-extents have a range defined to them. Outside this range, it doesn't make sense to manipulate blocks in terms of that extent. Note that worlds do not _conceptually_ have a range and are infinite (but practically worlds become useless after some large number of blocks, I think 32 million as a hard-coded limit).
- Some sub-extents (mainly chunks and technically locations, if you consider them to be 1x1x1 extents) are defined as "grids" upon their base extent. This means that all sub-extents of one type (Chunk as an example) cannot intersect with each other and so form a perfect grid across the containing world. Note that this requires these kinds of sub-extents to have a same-size range or bound defined to them.
- Some extents take up a whole column of y-values. Perhaps it is easier to visualize this when comparing a "column extent" to a cuboid selection; the selection is bounded by two x values, two y values, and two z values. Extents like chunks and "regions" are only bounded by two x values and two z values, and take up every possible y value (256 now, but some Spout experiments were able to simulate higher values).

Some interesting consequences of a system that could implement this:
- Locations (or perhaps BlockLoc) become 1x1x1 gridded, coordinate-shifted "nano"-extents, much like chunks. It still makes sense to call all the Extent methods on them, the coordinates just have to be (0, 0, 0). I'm not advocating removing Location altogether, but it can extend Extent (heh) as well as add a coordinate transformation. 
- Gridded extents can be looked up based on a position that lies within them. For gridded extents that are also columns (see Chunks), we only need to give two coordinates, an x and z position. For gridded extents that aren't columns (see Location), we need to give three coordinates. Note that this solves the "find chunk a block is in" problem based on vectors defined in terms of the world's coordinate system.

I still need to think about the possible properties and the hierarchy that results between them, but expect a PR.

**Comment by DDoS** [comment]
I'm all for Location being the unit Extent.

The problem I see with hierarchies are inconsistency and knowing what the Extent represents (chunk, world, block).

The original idea for Extent is just to provide a generalized concept for a section of the world, which lets you avoid things like separate methods to handle worlds and chunks.

This might be over complicating it.

**Comment by ST-DDT** [comment]
I guess your idea includes some kind of [Extend Parenting #322](https://github.com/SpongePowered/SpongeAPI/pull/322)?

**Comment by JBYoshi** [comment]
Maybe an `Extent.getWorld()` method?

**Comment by DDoS** [comment]
We have already rejected methods that return subclasses of Extent to prevent circular dependencies.

**Comment by JBYoshi** [comment]
Assuming `Extent.getWorld()` returns a `World`, the only problematic case would be `World.getWorld()`, and since only the implementation should implement `World` (I think), that shouldn't be a problem.

**Comment by ST-DDT** [comment]
What would you do if `Extend` does not have a `World` since it is a in memory snapshot of a region/selection (WorldEdit).

**Comment by JBYoshi** [comment]
Make it return `Optional<World>`? Although the method should probably explain why it's `Optional`, as I've had some trouble with `Optional` lately.

**Comment by DDoS** [comment]
Just no, it's not happening.

**Comment by JBYoshi** [comment]
@DDoS Close?

**Comment by DDoS** [comment]
No, there might be a better solution.

**Comment by ryantheleach** [comment]
The best way might be to analyse *why* people want the world from a location. 

Is it a convenience thing? Is it because it makes sense to get a parent extent from a unit extent?

Is it because people are incorrectly using location instead of a co-ordinate/transformation to represent a position?

**Comment by DDoS** [comment]
Closing this for now, it don't think it will be implemented. Part of the advantage of having sub-extents is delimiting a region of interest which the user is restricted to. Adding extent parenting would allow escaping out of the region, reducing the usefulness when trying to restrict the scope of the extent.

**Comment by DDoS** [comment]
Reopening because it's been quite a requested feature, and I think it needs to be investigated further.

**Comment by ryantheleach** [comment]
"Adding extent parenting would allow escaping out of the region, reducing the usefulness when trying to restrict the scope of the extent."


What's the usecase? Anything I can think of, someone grabbing the parent knows exactly what they are doing, and they are trying to escape on purpose, so should know the side effects, e.g. parts not being loaded or generated yet for chunks etc and be able to deal with them?

**Comment by DDoS** [comment]
Yeah, ungenerated parts can be an issue, especially for populators where they can cause an infinite loop.

**Comment by DDoS** [comment]
Don't think this will ever happen. Closing it.

**Comment by gabizou** [comment]
It's happening! #1896

**Comment by Zidane** [comment]
Closing as Extent is being re-wrote for 1.13
