### ISSUE TITLE
Add Text Paginator API

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeAPI#547]
API for formatted pagination of chat text
This allows long messages to be sent in a broken-up, user-friendly manner

Potential usage example:

API-side
```java
public void sendPaginated(CommandSource source, Text... lines) {
    PaginationService service = game.getServicesManager().provideUnchecked(PaginationService.class);
    service.send(source, msgs);
}
```

User-side:
```
line 1
line2
line3
Previous Page        Next Page
```
Where previous and next page are clickable (for non-click supporting clients, commands will exist)
Commands:
- `/paginator next` and `/paginator prev` will send next or previous pages of a player's current pagination
- `/paginator <uuid> next` and `/paginator <uuid> prev` will send next or previous pages of a given paginaton -- this will mostly be used by quoted text

These commands will have no assigned permission because they only have meaning when triggered by other plugins, which are expected to do and appropriate permissions checking for data

**Comment by boformer** [comment]
I would name the command ``/page [int|next|prev]``.
 Also, an optional header and footer ``Text`` would be nice.

**Comment by ryantheleach** [comment]
> Some lists may have 10000 entries.

Have an overload accepting an iterable or a stream?

**Comment by zml2008** [comment]
yeah, wouldn't be able to go back in pages with those though, but the best way to do it probably.

**Comment by TheE** [comment]
I have written a relative flexible [paginator](https://github.com/TheE/MyWarp/blob/master/mywarp-bukkit/src/main/java/me/taylorkelly/mywarp/bukkit/util/paginator/StringPaginator.java) using fluent interfaces for my MyWarp project that could probably be used as a base for a Sponge version. It is basically a front-end for Guava's `Lists.partition()`method.

Usage is pretty straightforward:
````JAVA
// Iterable of objects to paginate
Iterable <Foo> foos = ...;

PaginatedResults <Foo> results = StringPaginator
    .of("Header text", foos)
        .withEntrysPerPage(8)
        .withNote("Note shown at the bottom of each page.")
	.withNote("Multiple notes can be registered.")
	.withMapping(new Function <Foo, String> () {
	    @Override
	    public String apply(Foo input) {
	        //returns the string that is displayed for each entry
                return input.getName() + ", created by " + input.getCreator().getName();
	    }
        })
    .paginate();

try {
	// get a page as list of entries...
	List <String> page = results.getPage(4);

	// ...or a page as one String,
	String pageString = results.getPageAsString(4);

	// ...or directly send the page to somebody.
	results.display(player, 4);
} catch (NoResultsException e) {
	//thrown if the pagiantor is empty
} catch (UnknownPageException e) {
	//thrown if the page to display does not exist
}
````
`PaginatedResults` can be reused to display several different pages. `withEntrysPerPage()`, `withNote()`and `withMapping()` are all optional.

Obviously, `Text` should be sued instead of Strings for Sponge but that is a relatively trivial change.  Page changing can be implemented in top of `PaginatedResults`, similar to the `display()` method.

**Comment by Mumfrey** [comment]
[This guy pretty much takes the cake](https://forums.spongepowered.org/t/a-pagination-experiment-concept/6936) on pagination systems.

> **@mmonkey wrote:**
> I set out to make /list commands better inside of sponge plugins, and this is what I have come up with so far: [Video of pagination experiment](https://youtu.be/ze1Rdjd4vIw)
>
> You are welcome to try it out [download the Destinations plugin](https://github.com/mmonkey/Destinations/releases).
> You may also [steal the source code](https://github.com/mmonkey/Destinations). (MIT License)
> Or track the [progress of development](https://forums.spongepowered.org/t/wip-destinations/6917).

**Comment by FerusGrim** [comment]
I agree with @Mumfrey. He's also officially released [a library] for it. If we could somehow integrate this into Sponge, that would be pretty amazing.

[a library]: https://forums.spongepowered.org/t/paginated-lists-a-library-for-plugin-developers/6964

**Comment by RobertHerhold** [comment]
Although it probably would have to be modified a bit as far as providing a Pagination Service, code style, etc.
