### ISSUE TITLE
Represent Multiple World Respawn Locations

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#549]
As I've noticed in Forge, a `Player` can have multiple spawn locations varying based on the `World`'s dimension id. Should SpongeAPI present the possibility for this?

**Comment by Zidane** [comment]
Each world has its own spawn point in Sponge as each world is its own dimension id.

**Comment by gabizou** [comment]
> Each world has its own spawn point in Sponge as each world is its own dimension id.

Yes, but Players have uniquely a singular respawn location in Vanilla MC, whereas Forge adds the capability for several respawn locations (rather, one per dimension).

**Comment by ST-DDT** [comment]
IMO this is a missunderstanding.
In Vanilla each world can have multiple `Dimension`s. (World as WorldGroup/Universe)
In Sponge every `World` has exactly [one](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/World.java#L150) `Dimension`. (World as single Map/`World`)

So if forge adds multiple respawn points per world (1 spawn/`Dimension`) it is based on vanilla's naming conventions of world (=world group) `O(W * d)`. In Sponge every dimension of the world is its own `World`, thus you can have 1 spawn / `Dimension`(`World`)) `O(w)` with `w = W * d`, which is the exact same as forge does.

Or do you suggest adding multiple respawn points per world and dimension `O(n * W * d)`? 
How is decided which respawn is used then?

**Comment by Zidane** [comment]
What @gabizou is saying that if a person dies in the Nether (DIM-1), should he respawn in Overworld (WORLD) (which is Vanilla mechanics) or at Nether's spawn (as it has one in Bukkit/SpongeAPI).

As I said above, dimension doesn't really matter anymore as each world is its own dim id now. The question is to follow Vanilla mechanics or not. In this case, we'll follow Vanilla mechanics and a plugin is welcome to intercept the respawn event and put you elsewhere.
