### ISSUE TITLE
EntityChangeHealthEvent.getEntity() should return Living.

### ISSUE THREAD

**Issue by OscarOrSomething** [SpongePowered/SpongeAPI#553]
Since only Living objects have health, EntityChangeHealthEvent should have .getLiving instead of .getEntity

**Comment by Deamon5550** [comment]
There is a Living/Humam/PlayerChangeHealthEvent which would be the events thrown in practice. The EntityChangeHealth event exists simply to maintain a consistent hierarchy. However I can see how that may be confusing and misleading.

We could remove EntityChangeHealthEvent and let the LivingChangeHealthEvent be the top of the totem pole for that event hierarchy.

**Comment by OscarOrSomething** [comment]
That sounds good

**Comment by Zidane** [comment]
Going to keep it as is and the reasoning for this is the possibility that in the future Minecraft will move to an ECS-like system and therefore any Entity could have health. I'd rather keep the interface around and therefore prevent an API break.
