### ISSUE TITLE
setBlock for players and FakePlayers?

### ISSUE THREAD

**Issue by thomas15v** [SpongePowered/SpongeAPI#556]
Shouldn't we have a these methods in BlockVolume?
```java
/* Returns true if the block has been set */
boolean setBlock(Vector3i position, BlockState block, Player player);

boolean setBlock(Vector3i position, BlockState block, String fakePlayer /* Or PluginName */);

/* For Bulk Actions, Both arrays should have the same size */
boolean setBlock(Vector3i[] position, BlockState[] block, Player player);

boolean setBlock(Vector3i[] position, BlockState[] block, String fakePlayer);
```
These methods would than give of an event, so other plugins can deny the placement. With this plugins easily could modify blocks, without having to worry if other plugins agree with it.

**Comment by DDoS** [comment]
No, these shouldn't be in block volume as a block volume could be a buffer. There is no guarantee that a block volume contains the player placing the block. This should go in extent.

It seems to me like this could be made more generic. I don't really like this. Too specific.

**Comment by thomas15v** [comment]
It doesn't need to do the player blockplace animation. It just has to place the block for the player. So that it gives a correct event. Maybe a OfflinePlayer should fit better.

**Comment by DDoS** [comment]
To place a block, a player needs to be in the same volume as that block. Hence the block volume must also be an entity universe. This is a contradiction.

But, Extent extends both block volume and entity universe. This interface could accept these methods.

**Comment by DDoS** [comment]
These methods would be out of place in block volume: specifc methods for specific cases don't belong in a generic interface for generic usage.

**Comment by thomas15v** [comment]
Oh indeed this would fit better in the Extent class. I didn't really looked in to in what class it would fit.

**Comment by simon816** [comment]
So essentially what you're asking here is to include a `Cause` argument?
Something like
```java
boolean setBlock(Vector3i position, BlockState block, Cause customCause);
```

@SpongePowered/developers add this to Extent/Location?

**Comment by gabizou** [comment]
To be honest, I'd only want to bother seeing these sort of "fake" blocks being sent through to `Viewer`s, consider that it's their local world etc, that part is easy.

**Comment by JBYoshi** [comment]
@thomas15v Is the parameter:
- The player that should see the block change (as in a fake block), or
- The player the block should appear to be placed by (as in a cause to the "place block" event)?

**Comment by DarkArc** [comment]
@JBYoshi Do you mean "The block should appear to be placed by (as in a cause to the "place block" event)?"

I personally took this to be a request for methods to set a block, given a cause of player for automatic event handling.

@thomas15v Could you please clarify exactly what you want?

**Comment by JBYoshi** [comment]
@DarkArc I worded that part wrong. Changed to "The cause for the block change events".

**Comment by thomas15v** [comment]
@DarkArc 
What I want is basically making sure that plugins can block each other as well. So we don't end up like forge where setting blocks doesn't require any validation.

The thing is a changement of a block is mostly caused by a player. If a plugin is breaking a block because a player did some action, It should break the block in name of the player. 

And in case a player has nothing to do with this, it better gives the plugin name/object as cause, than other plugins can also figure out what caused the change.

What @simon816 proposed is basically exactly what I mean.

**Comment by ryantheleach** [comment]
If this happens, can we narrow the type of the cause to a PluginCause for the sake of sanity for anticheat plugins? that way it's impossible for plugins to provide a cause that isn't flagged as being somewhat involved by a plugin? But how would this work when checking the cause was caused by a player? Some sort of interface for PluginPlayerCauses?

**Comment by gabizou** [comment]
This is closely tied to #921, in fact, likely will be closed with #921.

**Comment by simon816** [comment]
Added in https://github.com/SpongePowered/SpongeAPI/commit/0985e72cc37dd1a58d5e45e5726935d2841aac52

**Comment by Sir-Will** [comment]
Is there a reason that his is only available in api 6 and not 5?

**Comment by ryantheleach** [comment]
Because 5 < 6 and we are up to 7?

5 is too far back now, unlikely to see it added.

It probably depended on other breaking changes, but it's far enough backwards that even if it wasn't a breaking change, I don't see it being added, so I'm not going to spend time to investigate on something that happened a year and a half ago.

**Comment by simon816** [comment]
@Sir-Will This was added just before the version 3 release and has not changed since. It's [still available](https://github.com/SpongePowered/SpongeAPI/blob/af4f1afcaabc1630236f0f78f7c5f68229cef631/src/main/java/org/spongepowered/api/world/extent/InteractableVolume.java#L178-L200) in the same interface.

**Comment by Sir-Will** [comment]
@simon816 hm, I thought it's not implemented as I'm getting `AbstractMethodError` using it. What else could cause that error?
```
Cause cause = Cause.of(NamedCause.simulated(event.player()));
fireLocation.getExtent().placeBlock(fireLocation.getBlockPosition(), BlockTypes.FIRE.getDefaultState(), Direction.DOWN, cause);

**Comment by simon816** [comment]
That's because the API is not implemented in the current builds. See https://github.com/SpongePowered/SpongeCommon/pull/86

**Comment by Sir-Will** [comment]
I'm confused, I thought you said it is implemented.
So it's implemented in the API but that API part is not implemented in SpongeCommon?

**Comment by simon816** [comment]
The methods have been defined in the API, but are not yet implemented in SpongeCommon
