### ISSUE TITLE
banPlayer() pardonPlayer()

### ISSUE THREAD

**Issue by frogocomics** [SpongePowered/SpongeAPI#558]
Lots of people on the Sponge Forums are discussing this, and I would like to bring this to GitHub. We need to be able to ban or pardon a Player from the <code>Server</code> class. The format should be like this:
```java
private Server server;
private String randomPlayer = "hfjkd:

@Inject private Logger logger;

private Logger getLogger() {
    return logger;
}

try {
    server.banPlayer(randomPlayer, "Is too random", "09-03-2050"); //banPlayer(String player, String     reason, String untilDate)
} catch(PlayerNonExistantException e) {
    getLogger().warn("That player does not exist");
}
```
<code>PlayerNonExistentException</code> may not be the best way to handle a non-existent event, so feel free to improve upon the code.
```java
public void banPlayer(String player, String reason, String untilDate) {
    //Convert player to an UUID
    //Check if the UUID exists on the Mojang servers
}
```

**Comment by simon816** [comment]
There already is a Ban API. See #412

**Comment by gabizou** [comment]
As @simon816 said, there is already a [`BanService`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/service/ban/BanService.java#L36) that you can use to ban players and users.
