### ISSUE TITLE
What is the "default" World?

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#566]
As the topic suggests, currently, we have no notion of a "default" world. Should we have one? Should we not?

**Comment by ST-DDT** [comment]
What do you consider as default world?
The first loaded world?
The world the player spawns in when he connects for the first time?

**Comment by Zidane** [comment]
server.properties defines default world.

I've yet to see a reason for the Server interface to have a setter for it.

**Comment by kamcio96** [comment]
Is it possible to change environment of default world? Eg to nether

**Comment by ST-DDT** [comment]
Worlds in Sponge are always linited to a single dimension. So if you are able to set it to a specific world you can choose whatever dimension just using the World object.
AFAIK in forge a world is a collection of dimensions. But in Sponge it is not.

**Comment by boformer** [comment]
@st-ddt I wonder how the getWorld(name) method works when there are 3 worlds (= Minecraft Dimensions) with the same name (overworld, nether and end).

**Comment by ST-DDT** [comment]
I guess this is a bug we should adress.
For example by adding `getWorld(String name, Dimension dimension)`

**Comment by Deamon5550** [comment]
@ST-DDT @boformer Actually the nether and end are currently named DIM1 and DIM-1 respectively. Perhaps they should be renamed to be world_nether and world_the_end by default. But I heavily disagree with a `getWorld(String name, Dimension dimension)` method.

**Comment by Zidane** [comment]
Each world must have a unique name. This is a non-issue.

**Comment by JBYoshi** [comment]
Shouldn't there be a getter method? In Bukkit I would just use `Bukkit.getWorlds().get(0)`, but since Sponge doesn't use a list (and a list actually doesn't even make sense), there ought to be an alternative.
