### ISSUE TITLE
ItemDropEvent should be concerned only about ItemStacks instead of Item (entities).

### ISSUE THREAD

**Issue by SupaHam** [SpongePowered/SpongeAPI#570]
At the moment, ItemDropEvent has one method, `Collection<Item> getDroppedItems()`. Notice Item and not ItemStack, this means that in order for a user to add an item to said event, he would need to be concerned about the entity itself rather than the ItemStack, which is what I think the event should only be concerned about, the server then processes the Collection of ItemStack and then creates Item entities out of them.

**Comment by gratimax** [comment]
Linking #348, it changed this mechanic a while back

**Comment by gratimax** [comment]
In IRC we seem to mostly have agreement that the best course of action would be to change the signature of `getDroppedItems` to `Collection<ItemStack> getDroppedItems()`. @SpongePowered/developers any objections?

**Comment by Zidane** [comment]
I'm confused as to why this was changed to the Item entity...

@gratimax change this back please.

**Comment by gratimax** [comment]
Fixed in 34e4379f297cc789cdd

**Comment by Aaron1011** [comment]
One of the main reasons for returning a Collection of `Item`s instead of `ItemStack`s is so that the plugin can manipulate the dropped item itself.

Without access to the actual `Item` entity, plugins wishing to modify the `Item` entity lack a good way to do so, instead relying on checking for `Item` entities one tick later.

I believe that this should be changed back.

**Comment by modwizcode** [comment]
I think the solution here was creating an ```Item addItem(ItemStack)``` method, not removing access to the Item entity.

**Comment by SupaHam** [comment]
@Aaron1011 I think that should be accessed another way some how, heck even create a new event that involves `ItemStack`s and not `Item`s. The event handling implemented in the server should NOT have to spawn entities, only to find out a plugin doesn't want any items to spawn. Then, you have how many ever instances of Item that were completely unnecessary.

**Comment by meguy26** [comment]
@Aaron1011 
I know this is closed but can you not just have two methods? Like getDroppedItems() and getDroppedItemsAsStacks()?

**Comment by me4502** [comment]
Two lists depending on each other's contents could be a bad idea

**Comment by meguy26** [comment]
@me4502 
True, I did not think of that.
