### ISSUE TITLE
 Allow generating a single tree at a single location

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeAPI#573]
Would also be good to be able to pass a custom Extent/some sort of proxy object to be able to record block changes performed. Bukkit had this as a BlockChangeDelegate.

**Comment by kenzierocks** [comment]
Tree as in sapling tree, or tree as in TreeMap?

**Comment by Deamon5550** [comment]
@kenzierocks sapling tree

**Comment by zml2008** [comment]
![Imgur](http://i.imgur.com/hO7v56O.png)
This kind of tree.

**Comment by Deamon5550** [comment]
This will be added with #734, you'll be able to fetch the PopulatorObject representing the tree and placed it where ever you want. For example `BiomeTreeTypes.OAK.getPopulatorObject().placeAd(...)`.
