### ISSUE TITLE
Player abilities data manipulator

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeAPI#575]
Currently, there is only a data manipulator for currently flying. These options are:

- walk speed
- fly speed
- can fly
- god mode? (the packet specification has a bunch of things. Also not sure if this is really something to put in API)

**Comment by Cybermaxke** [comment]
The walking speed is already handled by the attribute system, so it would make sense that the fly speed also is (a custom one). 
And the movement speed send by the abilities packet doesn't affect the movement speed anymore on the client due the attributes packet but still affects fov (field of view) modifier.

**Comment by gabizou** [comment]
We'll be making this into individual manipulators/values.

**Comment by gabizou** [comment]
Fixed with the several additions to data.
