### ISSUE TITLE
Add a default CommandExecutor for parent commands

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#579]
It would be nice to have an implementation of ``CommandExecutor`` which lists up the subcommands of a ``CommandSpec`` the source is permitted to use.

**Comment by zml2008** [comment]
This is probably going to end up as part of the help system once that goes in -- so that all the different ways to get command usage work together well.

**Comment by zml2008** [comment]
component of #548

**Comment by zml2008** [comment]
being combined into #548
