### ISSUE TITLE
Problems with the global biome populators

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/SpongeAPI#582]
So as it stands biomes have a series of populators, and these populators are defined per-biome. The biomes are defined globally which means that if you modify the populators of a particular biome it will have effect across all worlds. Now this isn't necessarily a bad thing however if someone is wanting to make a world generator which uses the default biomes but perhaps slightly modified. For example a skylands generator world which only wants to modify the y-levels that ores appear at would have negative side effects on the generation of the overworld as well.

**Some potential solutions:**
- Define the populators of biomes in the WorldGenerator rather than the BiomeType. The obvious solution.
- Allow a WorldGenerator to override the populators of specific biomes. A slightly messier solution as the biome's populators would now be defined in two places both of which would need to be checked.
- Allow the registration of new biomes. With this rather than editing the standard biomes the skylands generator would create its own new biomes with the modifications. Allowing the registration of new biomes is not a highly invasive change and is doable without client modifications. However there is an  implementation restriction of 256 biomes (and there are 63 vanilla ones) which should be kept in mind before we start requiring this as a solution to wanting to modify biomes.

Allowing the registration of new biomes is something we're going to want to allow anyway eventually. However in my opinion we'd be better off going with both the first and the third option in that case.

**Comment by ST-DDT** [comment]
> Allow the registration of new biomes

The idea is good but the purpose is bad.
Or at least if it used as the only solution to this issue. If we hint this solution to players they will waste the precious ids.

I would prefer solution two. Allow overwriting biome generators.
First of all having default populators for biomes is pretty nice, especially if you only want to change a single biome or want to remove only a specific populator. Usually you want the biome generators with all their features so the generator should use them unless specified else. The default populators should be immutable to avoid issues with other worlds that have not set overwrites.
So changes have to be made to the generator of the world directly.

**Comment by zml2008** [comment]
We could do something like create biome from existing biome, which is basically creates a copy of the biome. Then the biomes can share ids (I think -- well, at least to the client the ids are shared), which allows more than 256 biomes (restricted to vanilla biomes clientside currently though)

**Comment by gabizou** [comment]
From what I remember, [TerrainControl](http://dev.bukkit.org/bukkit-plugins/terrain-control/) used extra "biome id's" for extra biomes that weren't "vanilla" and the client would render those invalid biome id's as the default biome: "Plains" I believe. 

It is highly likely we can "spoof" biomes to use a vanilla biome id for coloring and various other biome related mechanics when creating "new" biomes, however, I do believe that we'd want to explicitly have the capability of registering new biomes, regardless of the 256 limitation. 

With this "spoofing" we could theoretically create unlimited biomes that have a "render" and "feel" of a like-vanilla biome but with vastly different populations and structures.

**Comment by Deamon5550** [comment]
We can spoof them client side but we still can't have more than 256 biomes on the server as that is a limitation of the chunk format.

**Comment by AlphaModder** [comment]
This seems very hacky... Couldn't we have a separate concept of Sponge Biomes for generator, and the actual biome saved and sent through the implementation, for the client. With the current Biome system being renamed to... idk, BiomeAppearence or something. This is probably not feasible, but I'll put it out there

**Comment by Zidane** [comment]
@Deamon5550 

Are biome ids ints? bytes? If ints, we could "reserve" a certain amount of ids and pack "Sponge Biome Ids" within them.

**Comment by ST-DDT** [comment]
The biomes are stored and transmitted as bytes.

**Comment by Deamon5550** [comment]
With #734 this is fixed by moving the definition of the `BiomeGenerationSettings` away from the type and to the world generator. Will close once that is merged.
