### ISSUE TITLE
Add User/offline player CommandElement to GenericArguments

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#583]
Use case: Ban command, mail command, lastseen command.

**Comment by zml2008** [comment]
I can see this being useful. However, I'd like for User to be fully implemented before I expose a command argument type for it.

**Comment by MattBDev** [comment]
I think this can be added as soon as #580 is ready to be pulled.

**Comment by MattBDev** [comment]
Will this be in Revision 2.1 since issue #580 will add further support of `User`?

**Comment by boformer** [comment]
I guess. When the UserStorage is implemented, this will be easy.

**Comment by MattBDev** [comment]
@boformer I was hoping one of the Sponge team members could just add the milestone to this so it isn't forgotten

**Comment by MattBDev** [comment]
I see a few issues with this being implemented:
1. Being Case-Sensitive
2. Suggestions could be very performance intensive.

**Comment by boformer** [comment]
@MattBDev The methods for that are in the ``UserStorage`` service: https://github.com/SpongePowered/SpongeAPI/blob/99c57e8231882e45cac627723d77b88454911464/src/main/java/org/spongepowered/api/service/user/UserStorage.java#L126

Adding the command elements is simple. The implementation of the service is harder.

**Comment by zml2008** [comment]
This would only do cached lookups -- we can't make network queries on the game/network threads.

**Comment by saladoc** [comment]
Well this could be limited to offline users that have connected to the server at least once.

**Comment by boformer** [comment]
Yep, it will only do cache lookups. If those lookups are too resource-intensive, the server could also only return online players.

Another solution would be to outsource the matcher methods to a third service that can be implemented by plugins (like permission service).

**Comment by boformer** [comment]
Nice Work :cookie:
