### ISSUE TITLE
Function "Item-despawn-rate"

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#584]
This feature has been in Spigot. I would like the same and on the sponge.

**Comment by gabizou** [comment]
Could you elaborate on what this "Function" does?

**Comment by Azatik** [comment]
Remove discarded items after a certain time.

**Comment by gabizou** [comment]
> Remove dropped items after a certain time.

That is something Minecraft already does... What are you wanting us to add?

**Comment by Azatik** [comment]
Really? Not seen.

**Comment by gabizou** [comment]
> There are no settings on the server Vanilla.

So you're talking about optimization settings that belong in the implementation that are already included [here](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/configuration/SpongeConfig.java#L71).

**Comment by Azatik** [comment]
Everything learned. Thank you.
