### ISSUE TITLE
Return method "deleteChunk".

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#586]
Return method "deleteChunk". It was deleted in: https://github.com/SpongePowered/SpongeAPI/commit/d661ad3a108d17aa24b71b1c62b9c7c980ef07ab
This issue is related to: https://github.com/SpongePowered/SpongeAPI/issues/574 and https://github.com/SpongePowered/SpongeAPI/issues/360.

Will be useful for trimming the world.

**Comment by Deamon5550** [comment]
This will be added with #574

**Comment by Azatik** [comment]
Hooray!
