### ISSUE TITLE
New event "PlayerFirstJoinEvent"

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#588]
Idea. Add "PlayerFirstJoinEvent". Triggered when the player joined for the first time.

**Comment by gabizou** [comment]
No. There is [JoinData](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulators/entities/JoinData.java) available for this. No need for an extra event or method to be added to [PlayerJoinEvent](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/entity/player/PlayerJoinEvent.java). Even if you wanted to store that someone is joining for the first time, you could check against your own list or whatever storage medium you desire.

**Comment by Azatik** [comment]
Okay.
