### ISSUE TITLE
Add ToolDurabilityChange event

### ISSUE THREAD

**Issue by TheAwesomeGem** [SpongePowered/SpongeAPI#593]
It should have the ItemStack that the durability changed, the player who is holding the itemstack, the previous value for the durability and the new value for the durability. It can also be cancelled to prevent durability change.

**Comment by AlphaModder** [comment]
Perhaps this should be one application of an "ItemDataChange" event?

**Comment by TheAwesomeGem** [comment]
Yes sure. Just anyway to keep track of durability changes and a way to prevent it.

**Comment by gabizou** [comment]
Closing in favor of #596
