### ISSUE TITLE
Recipes seem to have missed getting their factory builder methods moved to game registry.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#594]
Is this on purpose or should there be a game.getRegistry().getShapelessRecipeBuilder() ?

**Comment by RobertHerhold** [comment]
If there is not a method dedicated to that builder, it is probably provided by [GameRegistry#getBuilderOf](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/GameRegistry.java#L132).

**Comment by ryantheleach** [comment]
Could potentially be fixed by https://github.com/SpongePowered/SpongeAPI/issues/706 or Mumfrey's game registry cleanup (is there an issue, or pr or some way to track this?).

**Comment by modwizcode** [comment]
see https://github.com/SpongePowered/SpongeAPI/pull/717

**Comment by modwizcode** [comment]
Recipes.getShapelessRecipeBuilder? Texts works like this, so I don't see the problem with leaving it.

**Comment by gabizou** [comment]
Closing since this is now a `ResettableBuilder` and therefor can be easily built from the registry.
