### ISSUE TITLE
DataHolderEvents

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#596]
It would be amazing if we could have an event when a [`DataHolder`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/DataHolder.java) has a [`DataManipulator`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/DataManipulator.java) added or removed or modified. It would be helpful for things like [`ItemStack`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/inventory/ItemStack.java)s if their [`DurabilityData`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulators/items/DurabilityData.java) is changed for any reason (usually we would have a [`Cause`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/cause/Cause.java) for these kind of things).

Resolving this would eliminate the need for a `ToolDurabilityEvent` as suggested in #593. 

There are countless applications that can be useful for this, including:
- A sheep regrowing it's coat
- Entities becoming non-aggressive
- A Beacon's potion effects being changed
- A player renaming an entity

**Comment by boformer** [comment]
Sounds great!

**Comment by ryantheleach** [comment]
I just worry that this could cause a whole lot of events being created on modded servers if DataManipulators are created for ticking machines or pipes. Is there any chance of optimizing what events get signed up for, in order to reduce the amount of event spam?

**Comment by Deamon5550** [comment]
This would also cover #497

**Comment by ST-DDT** [comment]
To reduce the spam we should separate/subclass the event for entity/item/block targets.

Item targets also need the containing inventory in the event.

**Comment by simon816** [comment]
Does `ChangeDataHolderEvent` resolve this issue or is there still more to add?

**Comment by Zidane** [comment]
@simon816 

It does, closing (we'll add sub events for more direct actions)

**Comment by gabizou** [comment]
@Zidane I'm going to go ahead and re-open this as an issue for the various sub events with direct actions as there's some discussion I would like on where the events themselves would be located (somewhat partial to them being under the `api.event.data` package).

Currently, what I have in mind:
- [ ] Changing dye of a Sheep
- [ ] Renaming an entity with a `NameTag` item
- [ ] Changing a `MobSpawner` to use a different egg
- [ ] Perhaps updating a `CommandBlock`'s command?


I'm sure there are more that we'll be thinking of when adding the events and implementing them.

**Comment by ryantheleach** [comment]
When an entity catches on fire?
When a player starts crouching?

**Comment by Miclebrick** [comment]
When a player starts crouching, please :P

**Comment by ronaldburns** [comment]
Hoping for this. Would help to check food level changes

**Comment by JBYoshi** [comment]
Related to https://github.com/SpongePowered/SpongeCommon/issues/742. I started working on an implementation some time ago (see that issue), but I'm waiting for some bleeding changes to be (hopefully) merged into what will eventually be API 7. As `bleeding` is still for API 6, which is solely for Minecraft updates, the PR I need is still on hold.

**Comment by parlough** [comment]
Going to close this for now due to https://github.com/SpongePowered/SpongeAPI/pull/1728 - If anyone would still like changes or additions, please create a new issue.
