### ISSUE TITLE
The cause of a EntitySpawnEvent

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#597]
There is no way to get the cause of an EntitySpawnEvent.

**Comment by Deamon5550** [comment]
Causes have not yet been fleshed out and need an update. I have something planned for them and will get to them soon enough.

**Comment by Azatik** [comment]
Something like:
SpawnEggs;
Spawner;
Normal spawn.

**Comment by Deamon5550** [comment]
https://github.com/SpongePowered/SpongeAPI/blob/feature/replace-cause/src/main/java/org/spongepowered/api/event/cause/reason/EntitySpawnReasons.java#L33

**Comment by kashike** [comment]
Those look good to me, now it's just a matter of having accessors in the event.

**Comment by Azatik** [comment]
@Deamon5550 Possible to get entity of the cause of his spawn?

**Comment by Deamon5550** [comment]
We \*could\* do that but it would be outside the scope of adding these causes, better to bring it up again after causes are in.

**Comment by gabizou** [comment]
This has been added with 36ba40439d38eaade3833bd45048849742ff79d2, specifically in [SpawnCause](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/cause/entity/spawn/SpawnCause.java).
