### ISSUE TITLE
Dynamic Recipes

### ISSUE THREAD

**Issue by ZephireNZ** [SpongePowered/SpongeAPI#599]
Currently Sponge has two types of recipes Shaped and Shapeless. These have set pattern to search for, and a static return type.

This will work for _most_ recipes. However there are some recipes whose output depends on the items in the recipe itself, usually because they copy/add to the NBT of the item.

For example, when adding a pattern to a banner, the 'recipe' is the pattern of dye on the matrix - the location of the banner does not matter. It then adds the layer to the NBT of the item, and outputs that as the result. This is possible to represent as a collection of shaped recipes, but there would likely be millions of different recipes to add the list.

There's a couple different ways (some in conjunction) that we could approach this:
#1: Recipe that combines Shaped and Shapeless recipe

For the recipes that require a shape, and then an item extra (mainly just banners in vanilla), have a new recipe type that extends from both `ShapelessRecipe` and `ShapedRecipe`. It would have a shape just like shaped recipe that must be completed, and then remaining space is for the shapeless aspect.
#2: DataManipulator recipe

So the major way that these recipes differ is that they modify the data/durability of an item. A new recipe type could be specified, which targets a specific item (for example, a banner or a tool type). The recipe does not have a default output, but instead takes in a crafting inventory, and outputs the item with the manipulation (eg adding a layer or changing item durability).

This could end up being quite complex, but would also allow custom recipes to do the same manipulation of data that vanilla does.
#3: Custom recipes for the Vanilla

When I was researching for doing the implementation of recipes in Glowstone, I found that Vanilla had a short list of recipes that it performed dynamically. These are:
- Dying of leather armour
  - Changes the tag "display.color" to be the RGB value of the sum of all the dyes
- Copying of banners
  - Outputs a copy of a non-blank banner ("consuming" a banner)
- Banner creation (ie adding a layer)
  - Finds banner pattern from matrix, and adds a layer to the banner
- Copying of books
  - Copies book data, and increases generation by one
- Creation of firework charge
  - Looks to find gunpowder, plus modifier items to create a charge.
- Adding fade to charge
  - Looks for an existing charge, and then adds fade to it depending on modifiers
- Creation of firework
  - Finds charge(s), plus gunpower, plus paper to create firework
- Copying of maps
  - Creates a copy of a map ("consuming" a map page)
- Zooming of maps
  - Increases zoom level by one
- Repairing of tools/armour
  - Looks for two of the same item type, creates a new item with durabilities combined (plus extra)

However this seems like a very hardcoded solution, especially if mods add their own custom recipes similarly.

**Comment by ZephireNZ** [comment]
For reference, here's the PR that I'm currently submitting to Glowstone: GlowstoneMC/Glowstone#445

**Comment by ryantheleach** [comment]
@THDigi @drXor @haveric Would this be enough for RecipeManager2 to be implemented on Sponge, or is there something lacking?

I bet the hardest problem would be editing the existing dynamic recipes, or replacing them if they are accidentally removed.

**Comment by haveric** [comment]
I'm a bit behind on things, but from what I understand, removing/replacing the custom recipes is going to be difficult, but would be beneficial just for the sake of being able to identify which recipes shouldn't be modified (or as to what they are to avoid confusion such as the leather dying and repair recipes both using a leather helmet and having no indication they create something different)

The manipulation of the result is another thing. It would be great to have more control there, but there will likely still be things I'll be checking for manually during/before the craft that will affect the result.  My main concern here is whether there is enough similarity between how the custom recipes are created/used to whether it could be abstracted well or if it would just end up being individual re-implementations that could be customized.

I'm going to put some more thought into this and will probably be working on getting something working on Sponge in the next week or two.

Note: Latest source for RecipeManager is here: https://github.com/haveric/RecipeManager2 if anyone wants to investigate what I'm currently doing for anything (mainly the [flags section](https://github.com/haveric/RecipeManager2/tree/master/mods/bukkit/src/haveric/recipeManager/flags) ).

**Comment by Zidane** [comment]
@haveric 

Let me know when you start working on this. The team would love to collaborate to get recipes working in Sponge.

**Comment by gratimax** [comment]
You are able to add anything that implements [Recipe](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/recipe/Recipe.java#L47) to [RecipeRegistry](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/recipe/RecipeRegistry.java#L39), this includes any custom implementations. Then anything that uses data manipulators or the like is really just a utility on top of Recipe, just like Shaped/Shapeless recipes.

**Comment by ZephireNZ** [comment]
@gratimax If I'm following your reasoning, what's the point of having Shaped/Shapeless recipes then? The whole point is to make a standard for devs to create their own recipes, as well as to better expose the recipes in vanilla. Isn't that what this would help do?

**Comment by gratimax** [comment]
@ZephireNZ You can consider Recipe to be the base type. There are ingame recipes that look like shaped/shapeless recipes, but in the end everything still follows the Recipe contract. I mean, it's possible to implement shaped and shapeless recipes in the API, and that may be a good idea just to show that everything is from a base class. The point of those existing is to save on code. It is far more convenient to build a recipe than to code the logic for a shaped or shapeless recipe every time. There are a few that don't fit either, and one can use the base recipe type for that.

**Comment by ryantheleach** [comment]
The API already has shaped and shapeless, what is missing in the API is the concept of the remaining recipe types in vanilla and the ability to manipulate them. I think you are being awfully hasty closing this issue.

**Comment by gratimax** [comment]
I've explained multiple times that shaped and shapeless are two utilities on top of the base Recipe type. Everything else can be expressed as just something implementing Recipe. Seeing as how everything wanted by this issue is already expressive, I decided to close it.

In short, I'm sure you have some sort of concern but I am probably not understanding you. Perhaps you want a catalog of vanilla recipes? That's valid, but is to be a different issue altogether.

**Comment by haveric** [comment]
@gratimax What I take away from this is a need for a third utility that covers the custom recipes mentioned above. Currently, the custom recipes (banners, repairing, etc.) do not have one specific result, but instead modify the result based on ingredients. This allows for greater customization of a recipe without having to define every variation of ingredients in it.  They don't currently fit very well with either Shaped or Shapeless recipes in how they are currently being used.

**Comment by ZephireNZ** [comment]
To be fair, the current system can actually represent custom recipes with
any extra work. Unlike Bukkit, it requires passing in a crafting inventory
to get the result of a recipe.

Bit I still think another type of recipe to represent ones that modify
data, or even allow changing it, would be helpful.

**Comment by ryantheleach** [comment]
Yeah, I assume the ItemType returned is just as a placeholder / NEI compatible lookup for looking up recipes and or modifying them.

A catalog of the vanilla dynamic recipes would be useful, so maybe make a new issue for that. Unsure of what would be needed beyond that, as removing the recipes, and re-registering the modified versions should be easy enough.

**Comment by gratimax** [comment]
@haveric Are there any recipes that cannot be expressed by the [Recipe](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/recipe/Recipe.java#L47) contract? (Note that it returns a List of item types and result types...) If so, the contract needs to be changed.

@ZephireNZ If having to take in a GridInventory is a big deal, then Recipe can be extended with an abstract class that doesn't take a grid inventory and implements Recipe, but what does this give you? There isn't really any other way to compute the result or test a recipe...

@ryantheleach Yes, that's pretty much the point of the list of item types returned.

**Comment by ryantheleach** [comment]
After work today I'll flesh out my StoneSoup submission for CookBook some more, hopefully a good example + docs will help to clear some misconceptions up.

**Comment by parlough** [comment]
I'm fairly sure this is now easily possible with https://github.com/SpongePowered/SpongeAPI/pull/1582 now merged, correct @Faithcaio ?

So this is possible by implementing it yourself, but after talking to faith, it seems like he would like to make this even easier eventually.

**Comment by gabizou** [comment]
This has long been implemented with #1582. Closing.
