### ISSUE TITLE
Ability to get resource pack information from a player

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#600]
The API has a method to set/send a resource pack to a player, but doesn't have methods to get the status or hash from a player.

**Comment by AlphaModder** [comment]
@kashike The return status is handled by an event. It is up to plugins to store that information. It also contains the hash. https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/entity/living/player/PlayerResourcePackStatusEvent.java

**Comment by kashike** [comment]
@AlphaModder I must have missed that event somehow, cheers.
