### ISSUE TITLE
Add BlockActivationEvent, Be Consise with PlayerInteractBlockEvent

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeAPI#606]
One of the biggest issues CraftBukkit had for events was PlayerInteractEvent was used for things that involved no actual client digging/selecting/placing (interaction).

Ex. In Craftbukkit, the act of walking over BlockRedstone threw a PlayerInteractEvent with left...click....-_-.

Doesn't make sense huh? Especially with, MCP at least, calling that onBlockActivated. So, to fix this, I propose adding a BlockActivationEvent and keep PlayerInteractBlockEvent where it belongs: Digging, Selecting, Placing.

**Comment by gabizou** [comment]
It would seem interesting with figuring the random block updates due to these types of events.

**Comment by ryantheleach** [comment]
So a pressure plate would be block activated event caused by playersbutt.

As opposed to a player interact event where the player interacts with the pressure plate?

**Comment by Zidane** [comment]
@ryantheleach 

The block is activated and that may be by player...enderman...item....

@SpongePowered/developers 

We also need to modify PlayerInteractBlockEvent to provide the facing of the block.

**Comment by Zidane** [comment]
I've adjusted the API to have the facing of the block.
