### ISSUE TITLE
Make permission data (SubjectData) a part of the Data API and make every Subject a DataHolder

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#607]
This is an alternative to [zml's PR](https://github.com/SpongePowered/SpongeAPI/pull/603). 

I think Permission data should be handled like an other data. A permission ``Subject`` should be a data holder.

That also means that you can append custom data to a permission group, which will be inherited to the members of the group (e.g. ``ChatPrefixData``).

This would clean up the Permission API and add much more possibilities that the "key-value options" introduced by zml's PR.

**Comment by zml2008** [comment]
@gabizou do you think you could take a look at how this would work?

Would we have to change SubjectData instances to be immutable? (I already do this in PEX internally)
Would the data object be like Subject (calculated), or SubjectData (uncalculated) (and there are both data and transient SubjectDatas).
Would this work with non-data-holding objects?
Would it be able to handle two different SubjectData instances (transient and non-transient)?

**Comment by gabizou** [comment]
@zml2008 I don't think this is valid any longer, thoughts?

**Comment by zml2008** [comment]
Yeah, I agree. This would be nice to do, but permissions and data/value API work super differently internally so it wouldn't work at all imo.
