### ISSUE TITLE
Rename package "...api.util.command" to "...api.command"

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#608]
Commands are an important part of Sponge and Minecraft and not just a "utility".

This is a minor issue.

**Comment by progwml6** [comment]
breaking api compatibility for the sake of moving packages  is not something i think is a good idea

**Comment by boformer** [comment]
@progwml6 We also moved ``@Subscribe`` from ...api.util.event to ...api.event.

**Comment by ST-DDT** [comment]
IMO We are still early in this project so it does not matter that much. And a package rename is quite easy to solve as well.

[org.spongepowered.api.util.command](https://github.com/SpongePowered/SpongeAPI/tree/master/src/main/java/org/spongepowered/api/util/command)
We could probably move it to
[org.spongepowered.api.service.command](https://github.com/SpongePowered/SpongeAPI/tree/master/src/main/java/org/spongepowered/api/service/command)
as well

**Comment by progwml6** [comment]
@boformer we haven't moved stuff around post 2.0

**Comment by Zidane** [comment]
@progwml6 

While a 3.0 rev is destined for us, I see no merit in this PR. The only reason the other stuff being moved (besides making sense) was to help Mumfrey resolve the MixinEvent issue sanely.

**Comment by Zidane** [comment]
To further comment, I'd only make such a change RIGHT BEFORE the new revision. Not in the middle.
