### ISSUE TITLE
Allow command registration at any time

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeAPI#609]
Currently registering commands is not allowed after the server has started. However, @zml has said that it is in fact meant to be allowed.

See https://gist.github.com/kenzierocks/bed155d83a532f0d0457.

N.B.: I was told this was an API issue on IRC.

**Comment by zml2008** [comment]
I've created a test plugin that registers commands on preinit, init, serverabouttostart, serverstarting, and serverstarted. All of these commands work, so this is some other issue. Also you aren't allowed to return null as a CommandResult.
