### ISSUE TITLE
PlayerChatEvent recipient flexibility

### ISSUE THREAD

**Issue by mbax** [SpongePowered/SpongeAPI#612]
**Problem**
As it stands, if you wish to selectively show a message to players you must cancel the ```PlayerChatEvent``` and separately message those you wish to receive it. Selective message arrivals, and per-player customization of messages received, are an important function of many existing plugins on other platforms (See: Factions, VanishNoPacket, etc).

**Proposal**
I propose the creation of an API which would allow for:
* Customizing how each user views a message.
* Preventing particular players from receiving a message at all.
* Cover messages produced by the server including (but not limited to):
    * Chat messages
    * Join/quit messages
    * Death messages

**Related**
* [This (currently open) PR](https://github.com/SpongePowered/SpongeAPI/pull/530) proposes a recipient set. I believe this is a neat piece of it but I feel it would be better to have a complete solution pulled at once in case it's decided the best solution involves not having that ```Set```.
* [This (closed) PR](https://github.com/SpongePowered/SpongeAPI/pull/158/) proposes a more complete idea, but was shut down in favor of 'channels' which are never again mentioned. RIP channel mention.
* [This branch](https://github.com/SpongePowered/SpongeAPI/compare/feature/channels) that could use some love.
    * Whoosh! :heart: ```<@gratimax> wow I forgot about this branch
<@gratimax> just... flew over my head```

**Summary**
![We should take player-directed messages, and push them somewhere else!](http://i.imgur.com/eFA834Q.png)

**Comment by ZephireNZ** [comment]
This should apply to any event which trigger a message to be broadcast to players - such as player deaths.

**Comment by mbax** [comment]
@ZephireNZ that's probably a good plan.

**Comment by TheAwesomeGem** [comment]
I like this idea. Would be pretty time saving on a lot of different situation and I don't see any harm.

**Comment by modwizcode** [comment]
Ah yeah the channels idea I made and pushed off to gratimax. I miss that idea, wish it could get some love now that the API is more complete.

**Comment by gratimax** [comment]
I spent a while toying around with getting channels where I wanted them, and it was rather difficult. Eventually what I had was easily composable and made sense. However, I couldn't figure out the best way for channels to interact with each and replace each other without imposing a solution such as an integer order, which I don't consider a good option. Of course, this is more structured than just an event and more complicated too, but with that problem still there fundamentally I don't think channels will make it.

**Comment by Zidane** [comment]
@zml2008 is working on targets. I've addressed a few other concerns by standardizing messaging in a few events across the API.

**Comment by dredhorse** [comment]
@zml2008 took my Channel Implementation from a PR of Spout and implemented it. I haven't really looked into Sponge yet but I guess something similar could be implemented here too.

As he is already looking at it I guess we should see something soon.

To recap my idea at that time:

1) Player are always in the default channel
2) Player can be in several channels at the same time
3) Players can only talk in one channel at a time
4) Channel determines formatting / position of display of messages
5) Default Channel formatting was modifiable via the server config

So if you have something like Faction, the Faction Plugin would put the player on join in a "City" and "Faction" Channel and let him talk in the City Channel. He would use a specific command to talk in the Faction Channel or default channel. 

If you would have a second plugin also implementing something chat related it would just add its own channel. Of course all plugins would need to supply a way to set the active talking channel and / or it could be a general one which would allow choosing of channels.

Sponge would supply the means, the Plugins would do the managing. It shouldn't be to complicated or cater for too many corner-cases... there is always the way to cancel a chat event still.

**Comment by kashike** [comment]
@dredhorse I'm not sure that a player should __always__ be in the `default` channel (permission-based (permission to receive, permission to send) might be acceptable, though - may want to prevent a player from receiving messages in that channel, or remove them completely). The `default` channel should also be 'settable' (ex: I can replace the `default` channel with a `global` channel I create that has formatting, etc.)

**Comment by dredhorse** [comment]
default is the global channel, and it has formatting... and you need to be in the default channel so that you can receive messages from the server or from plugins.. so default channel is the serverwide normal formatted talk without any plugins and becomes a "side" channel when you install a chat plugin which moves the players into its own channels to talk.  How a plugin figures out in which channels a player is or in which channel the player is talking is up to the plugin.

The players will still get messages from the server or other plugins though. 

A point would be if players should be allowed to talk in the default channel, this could be done by permissions in the server config, but also be governed by a chat plugin.

**Comment by modwizcode** [comment]
@dredhorse can you link that original Spout PR?

**Comment by dredhorse** [comment]
WOW... I still found it... https://github.com/SpoutDev/Spout/pull/1985 but the link to the API doesn't work anymore.

I only have a more recent repo still https://github.com/dredhorse/SpoutAPI/tree/master/src/main/java/org/spout/api/chat
The above repo shows the state after @zml2008 implemented my PR (he did a rewrite of it, see also https://spoutcraft.org/threads/chatchannels.5052/page-2#post-75710 and the below). 

Original Thread kinda here https://spoutcraft.org/threads/chatchannels-reborn.7826/

**Comment by zml2008** [comment]
My WIP proposal is in PR #694
