### ISSUE TITLE
Inconsistent builder method prefixes

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeAPI#614]
We have a lot of builders in our API, and most of them define setters without any prefixes, so for example to set a message they would have `MyBuilder message(Text message)`. This is currently inconsistent in our API, for example the `CommandSpec.Builder` defines them with a `set` prefix. We should decide for one style and then use it for all builders in the API consistently. We could basically choose from one of these options:

- no prefix at all (as currently), e.g. `builder.message(Text message).build()`
- `set`-prefix, e.g. `builder.setMessage(Text message).build()`
- `with`-prefix, e.g. `builder.withMessage(Text message).build()`

**Comment by Zidane** [comment]
I say remove set and with.

**Comment by kashike** [comment]
I prefer builders without a prefix for setters.

**Comment by RobertHerhold** [comment]
Same, I prefer without the set prefix.

**Comment by AlphaModder** [comment]
I agree, no set prefix.

**Comment by zml2008** [comment]
sure, not java-enterprise-verbose but works for me
