### ISSUE TITLE
Allow listening for events without annotations

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeAPI#615]
Currently, the event system requires the use of annotations. This is quite inconvenient, especially for plugins implementing a kind of dynamic event registration, for example if all needed events are not known at compile time. This affects especially scripting plugins which would always need to add a separate event handler method for every event accessible through their scripting API.

As an example, [Pore](https://github.com/LapisBlue/Pore) uses dynamic event registration for calling Bukkit's events already, however currently it has to [generate classes at runtime](https://github.com/LapisBlue/Pore/blob/master/src/main/java/blue/lapis/pore/event/PoreListenerGenerator.java#L61-L134) to make that work. There should be an easy way to register events using a simple interface additionally instead of just using annotations, for example something like this:

```java
interface EventHandler<T> {
    void handleEvent(T event);
}

interface EventManager {
    // ...
    <T extends Event> void register(Object plugin, Class<T> eventClass, EventHandler<T> handler);
}

game.getEventManager().register(plugin, ServerStartedEvent.class, new EventHandler<ServerStartedEvent> {

    @Override
    public void handleEvent(ServerStartedEvent event) {
        // Do something
    }
});
```

The only thing missing here would be the `Order` of the event and `ignoreCancelled`, but that could be just added as additional overload for the registration method.

**Comment by Zidane** [comment]
@Minecrell 

Issue is we would have a chicken and egg problem...unless you would want lifecycle events to remain annotation-based.

**Comment by Minecrell** [comment]
@Zidane 
You mean like if I would want to register something like `PreInitializationEvent` without annotations?

**Comment by Zidane** [comment]
Yes

**Comment by Minecrell** [comment]
@Zidane 
This is not supposed to _replace_ the current annotation-based event system. Plugins still need to add a `@Plugin` class so they can just add the annotation-based handler there. This is only to help when you don't know exactly which events you will want to listen to at runtime, and obviously you do know that with the state events.

**Comment by Zidane** [comment]
@Minecrell 

Right but some may ask for whichever way to pull off not needing annotated events at all.

**Comment by Bammerbom** [comment]
I also need this for my Plugin.

**Comment by ST-DDT** [comment]
@Minecrell 
The `EventManager` should probably have some more wildcards.
`<T extends Event> void register(Object plugin, Class<T> eventClass, EventHandler<? super T> handler)`
or
`<T extends Event> void register(Object plugin, Class<? extends T> eventClass, EventHandler<T> handler)`

There is only one requirement to skip all event handler annotations for plugins.
The event handler (registration) must be accessible when creating the plugin instance, that way the registration of the event handlers could be done in the plugin constructor.
````java
public MyPlugin() {
    super();
    Game.getGame().getEventManager()
        .register(this, GameStateEvent.class, new GameStateEventHandler(this));
}
````
(Or via injecting the EventManager in the constructor directly)
