### ISSUE TITLE
No methods to control the PVP-status of the world.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#616]
No methods to control the PVP-status of the world.
Methods:
```
boolean getPVP();
void setPVP(boolean pvp);
```

**Comment by modwizcode** [comment]
Seems like an easily corrected problem.

**Comment by simon816** [comment]
I think this would be best represented as a gamerule since it is a rule for the world
Otherwise a getter/setter in WorldProperties.
@SpongePowered/developers which one?

**Comment by kashike** [comment]
It is probably best not to add custom gamerules.

**Comment by Deamon5550** [comment]
In vanilla whether PVP is allowed is a server setting not per world, so the implications of changing that need to be considered while implementing this.

**Comment by JBYoshi** [comment]
I know Bukkit was able to have per-world PVP settings, although I'm not sure whether it stored them per-world or not.

**Comment by gabizou** [comment]
I'm pretty sure it should just be an optional thing, i.e. it's defaulting to the global game rule, unless set.

**Comment by simon816** [comment]
In terms of implementation it's as simple as overwriting the method `canPlayersAttack()` in `EntityPlayerMP`
Adding custom game rules is easy too, there's `addGameRule` in `GameRules` class.

There's 3 ways to store this setting:
* In config file `config/sponge/worlds/...`
* In `level.dat` as custom key
* In game rules (uses `level.dat` too)  
This has the advantage of using the vanilla command `/gamerule` to configure it
