### ISSUE TITLE
Allow Health Scaling

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#618]
Currently, if we assign the maximum health of a player to, say, 200, there will be 100 hearts displayed on the client's screen. This is a ~~problem~~ feature! In all seriousness, we should likely have some sort of health scaling toggle much like [Bukkit] had.

[Bukkit]:https://github.com/Bukkit/Bukkit/blob/d3ab9468c3aed2a06c280bf6c9cea5108c736dcc/src/main/java/org/bukkit/entity/Player.java#L996

Thoughts would be appreciated.

My current thoughts would be to provide some sort of `ScalingHealthData` manipulator like so:

```java

public interface ScalingHealthData extends DoubleData<ScalingHealthData> {

    /**
     * Sets the scale of health from <code>0 -> scale </code>. 
     */
    ScalingHealthData setHealthScale(double scale);
 
    /**
     * Gets the health scale.
     */
    double getHealthScale();
}

```

**Comment by FerusGrim** [comment]
You mean to tell me you _don't_ approve of a wall of hearts?

**Comment by DDoS** [comment]
Makes sense to me...

**Comment by Aaron1011** [comment]
> Sets the scale of health from <code>0 -> scale </code>.

Is `0` intended to be 'normal' (a 1:1 ratio)? I think it would make more sense for `1` to represent the default scale. It would also allow for scaling down the player's health (e.g one client-side heart representing half a real heart).

**Comment by gabizou** [comment]
@Aaron1011 No, the scale is 0 -> scale such that the scale is the maximum displayed hearts. So normally, the scale is 0 -> 20.

**Comment by TheAwesomeGem** [comment]
This feature would be pretty good for a RPG server. This way, I don't have to make a custom max hp and current hp variables and get a ratio on it to put on the health and max health.

**Comment by ryantheleach** [comment]
I thought the main reason it was this way in bukkit, was due to integer health.

Now we have double health, couldn't you scale the damage instead using plugins?

**Comment by gabizou** [comment]
> Now we have double health and customizable max health, couldn't you scale the damage instead using plugins?

The problem with this is that a) Players will find it odd to see having more than just the 20 half hearts of health, if there is a slight deviation, they will question. When it comes to RPG plugins, usually they want players to have varying health based on multiple aspects, such as level, class, etc. Having to constantly recalculate all damages and health gains based on that for a "20 health scale" is much harder than you can imagine.

**Comment by ryantheleach** [comment]
Fair point. Still thinkpeople should seriously consider using non-20 health even if scaling is introduced as it provides UI feedback that their health is changed.

**Comment by gabizou** [comment]
> Fair point. Still thinkpeople should seriously consider using non-20 health even if scaling is introduced as it provides UI feedback that their health is changed.

The API shouldn't dictate how RPG plugins want to display their health. If an RPG plugin wants to always scale health on 20 hearts, so be it. We shouldn't be the ones to limit them.

**Comment by TheAwesomeGem** [comment]
My go-to guy is gabizou. We have similar projects on our mind and trust me, it would be pretty useful. No more having custom hp values and doing this. http://pastebin.com/z7xGn7ka

**Comment by Zidane** [comment]
@gabizou 

Get some traction on this and figure out what you are going to do.

**Comment by gabizou** [comment]
So far, my idea is to make a `HealthScalingData` such that it is applied to every `EntityPlayer` on construction and the values are read in from NBT (getting the data is exposed through an interfaced mixin). and then handle the processing in `HealthDataProcessor` etc. to where packets need to be handled.
