### ISSUE TITLE
(CommandSpec) Move to parent executor, if no matching children subcommands

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeAPI#620]
As it is right now, we can specify a Map of sub-commands, and register them all under one "main" command with #setChildren(). However, that does not leave the option to specify other arguments that are not sub-commands. For example, if I have a command registered to "/warp", and I have sub-commands for "/warp add", "/warp delete", etc. I cannot have just "/warp <insert warp name here>", as it will try to find the sub-command matching that argument. Even if I do:

``` java
CommandSpec mainWarpCommand = CommandSpec
		.builder()
		.setChildren(subCommands)
		.setExecutor(new WarpCommand())
		.build();
```
It will simply refer all "/warp *" commands to the WarpCommand class (which implements CommandExecutor). From there, one could theoretically check if the argument matched any subcommands and if not, return `CommandResult.empty()`, but there seems to be no way to actually execute the correct sub-command from there (Barring work-arounds with instantiating the CommandExecutor for the correct sub-command and calling execute()).

[Relevant class](https://github.com/SpongePowered/SpongeAPI/blob/7e8d39902264019f30d91bb6e894050be57165b5/src/main/java/org/spongepowered/api/util/command/dispatcher/SimpleDispatcher.java#L334)

I propose that there be some method to set the executor for a command given that no other sub-commands could be found matching that argument.

**Comment by AlphaModder** [comment]
`.setFallbackExecutor()` perhaps?

**Comment by RobertHerhold** [comment]
I think that would work.

**Comment by FerusGrim** [comment]
We don't necessarily need a new method, just alter the handling.

If a command parent has children, it doesn't make sense to use the parent's executor first.

**Comment by KieronWiltshire** [comment]
I think just setExecutor would be fine? I mean, the executor should only be called if the argument doesn't match any children anyway. which makes the .setFallbackExecutor quite useless?

**Comment by RobertHerhold** [comment]
Right, so it should:
* Look for any subcommands - execute if one is present
* Otherwise, execute the parent's executor

**Comment by KieronWiltshire** [comment]
yeah, it makes a lot more sense that way.

**Comment by Xemiru** [comment]
the one thing i didn't get to note is that CommandSpec has a method named `.setExecutor()` that we should be able to use as that fallback executor.

``` java
        public Builder setChildren(Map<List<String>, ? extends CommandCallable> children) {
            Preconditions.checkNotNull(children, "children");
            ChildCommandElementExecutor childDispatcher = new ChildCommandElementExecutor(this.executor);
            for (Map.Entry<List<String>, ? extends CommandCallable> spec : children.entrySet()) {
                childDispatcher.register(spec.getValue(), spec.getKey());
            }
            setArguments(childDispatcher);
            setExecutor(childDispatcher);
            return this;
        }
```

what `.setChildren()` does is create its own spec to set as the primary executor, which seems odd since `.setExecutor()` is there; considering they coexist within the same class this allows implication that it can be used in tandem for the children executor to fallback to the primary executor set with `setExecutor` should child arguments not be found.

modification of `setExecutor` should be able to solve this, however another method that might allow it to be more flexible is to allow the execution method within `CommandExecutor` to return a flag that tells the command to result to using the children command executors.

**Comment by Zidane** [comment]
Seems like order is a bit strange zml. Might be worth cleaning up the builder or having better docs.

**Comment by RobertHerhold** [comment]
I'd like this to be re-opened. ff35562 fixed setChildren() overriding setExecutor(), but I would still like to see functionality for using the default executor when a valid sub-command is not found. I see two options:

1.  Add a setDefaultExecutor() method, which will be used to no valid sub-commands are found
2. Automatically use the executor from setExecutor(), but this may have unintended consequences if developers *want* an error to be thrown if a player types in a command wrong.

I would be in favor of Option 1, as it allows more flexibility, and Option 2 forces developers into expecting their executor to be run if a player types a command in wrong. I would be willing to PR if we reach a consensus.

**Comment by boformer** [comment]
@RobertHerhold You mean when a subcommand was found, but the arguments don't match?

Right now, if no valid subcommand was found, the command is redirected to the fallback executor (that is your default executor). Isn't that what you want?

**Comment by Xemiru** [comment]
@RobertHerhold 
``` java
    @Override
    public CommandResult execute(CommandSource src, CommandContext args) throws CommandException {
        CommandMapping mapping = args.<CommandMapping>getOne(getUntranslatedKey()).orNull();
        if (mapping == null) {
            if (this.fallbackExecutor != null) {
                return this.fallbackExecutor.execute(src, args);
            } else {
                throw new CommandException(t("Invalid subcommand state -- no more than one mapping may be provided for child arg %s", getKey()));
            }
        }
        if (mapping.getCallable() instanceof CommandSpec) {
            CommandSpec spec = ((CommandSpec) mapping.getCallable());
            spec.checkPermission(src);
            return spec.getExecutor().execute(src, args);
        } else {
            final String arguments = args.<String>getOne(getUntranslatedKey() + "_args").or("");
            return mapping.getCallable().process(src, arguments).or(CommandResult.empty());
        }
    }
```

If you look at the block of code for execution of the subcommand handler, this functionality already exists at `if (this.fallbackExecutor != null) return this.fallbackExecutor.execute(src, args);`. There's no need for a `setDefaultExecutor()` method; the `setExecutor()` method, if it didn't already do that, would be easily made to conform to whatever `setDefaultExecutor()` implies it would do.

**Comment by RobertHerhold** [comment]
@boformer @Xemiru 
You're both right -- I think I just need to test my code a bit more... Thanks for clearing this up.

**Comment by zml2008** [comment]
just make the child command element an optional in the command args, or even firstParsing(childExecutor, string(...) /* or whatever other args used */)
