### ISSUE TITLE
Customization over subcommand error message

### ISSUE THREAD

**Issue by Xemiru** [SpongePowered/SpongeAPI#622]
Looking at the command handler for child commands, I've noticed there's no way to customize the error message should the command go wrong. It'll just say `Input command %s was not a valid subcommand!`, %s being the input. Its under my preference to be able to customize this error, usually giving it the heading of my plugin's name and a different message that uses more player-friendly terms, or even pass it to throw into a help menu.

**Comment by ryantheleach** [comment]
Wouldn't the fallback command executer be able to do this?

**Comment by zml2008** [comment]
possible component of #548

**Comment by zml2008** [comment]
being combined into #548
