### ISSUE TITLE
TabList maniplation

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#623]
With Bukkit, the player tab overlay can be manipulated into displaying players in a certain order using packets. Fake 'player' entries can be created using scoreboard teams, and a GameProfile populated with a skin signature can be used to provide a non-steve head.
As far as I can tell myself, there is no way to manipulate the [order](https://gist.github.com/kashike/2e67332fd8950f0716f8) items are displayed using the API alone.

@Minecrell might be able to expand upon the explanation of this issue.

**Comment by SonarBeserk** [comment]
Seemingly all tablist handling was basically clientside and the servers just used packets to craft it to look very specific. Even in normal bukkit, ordered tab lists worked shaky at best in my experience.

**Comment by simon816** [comment]
@SpongePowered/developers Accept this feature?

**Comment by ryantheleach** [comment]
At the very least the header and footer of the tablist should be able to be changed.

**Comment by simon816** [comment]
@ryantheleach Yeah that's already possible; there's get/setHeader and get/setFooter https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/player/tab/TabList.java#L39-L66

**Comment by ryantheleach** [comment]
Actually looking at the code it appears that everything needed for a plugin to do this is already in the API? The only thing missing *might* be a factory for making PlayerTabInfo objects to add to the tablist considering there is already setters for the gameprofile.

**Comment by kashike** [comment]
This is mine, just so people are aware.

**Comment by Aaron1011** [comment]
Merged in https://github.com/SpongePowered/SpongeAPI/commit/554453a4b9f410df62803737277bdd1a7a85456f.
