### ISSUE TITLE
Provide JSON dependency for plugins.

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeAPI#625]
Plugins will quite often need to work with JSON, especially when working with web services. We should provide a JSON dependency in SpongeAPI so plugins don't need to shade the same dependency over and over again. I think there are basically 2 options:

- **[GSON](https://github.com/google/gson):** This is included in Minecraft already so there would be no additional dependency to shade - there is basically no change for our implementation when we would provide this for plugin developers.
- **[Jackson](https://github.com/FasterXML/jackson)**
- **...?**

**Comment by RobertHerhold** [comment]
I vote Jackson. I've been using it forever and I love it.

**Comment by gratimax** [comment]
Personal preference shouldn't be a factor, I think that practicality here is more important. While I have used both and like both, Gson is shaded with Minecraft and does not need to be distributed further.

**Comment by Minecrell** [comment]
I agree with @gratimax here, we should try to keep our distribution as small as possible, if plugin authors want something special they can still package these dependencies together with their plugins.

**Comment by zml2008** [comment]
imo jackson is preferable because it provides more flexibility in how json is parsed and represented. Also take a look at configurate-json and configurate-gson.

**Comment by progwml6** [comment]
gson 2.2.4 is already in the classpath for both implementations use it

**Comment by gratimax** [comment]
I feel like you've closed this prematurely. Sure, Gson is on the classpath, but we haven't answered the question of if it should be an API dependency...

**Comment by jamierocks** [comment]
This comes with the assumption that every Minecraft implementation is bundled with GSON. :|

**Comment by Minecrell** [comment]
@jamierocks If not, they can just include it when implementing our API.

**Comment by jamierocks** [comment]
I was merely pointing out not to include GSON, because Minecraft has it. You should pick the one developers want...

**Comment by Minecrell** [comment]
@jamierocks This is pretty much personal preference. If plugin authors want to use a different library they are free to do so, but we provide GSON because we have it already available. We bundle quite a lot of dependencies already, there is no real need for 20MB+ JARs just to bundle every dependency a developer could ever need.
