### ISSUE TITLE
No method of getFoodData in the Human interface.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#626]
@gabizou 
No method of getFoodData in the Human interface.
For example, getHealthData is.

**Comment by ST-DDT** [comment]
Afaik this is covered by the data API.
https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulators/entities/FoodData.java

**Comment by Azatik** [comment]
This I saw, but could not take advantage of it. I do not know how.

**Comment by Deamon5550** [comment]
Documentation for the data api is pending, but if you want to get the FoodData from a human you can use the following snipet.

```java
Human huma;
FoodData food = human.getData(FoodData.class).get();
```

**Comment by Azatik** [comment]
Yea. Thank you:)
