### ISSUE TITLE
.runAsServer for game.getServer()

### ISSUE THREAD

**Issue by MikaalSky** [SpongePowered/SpongeAPI#629]
Having .broadcast is all fine and dandy, but when someone (like me) wants to use a command like, let's say, /playsound or maybe just a command from another plugin, it would just be simpler to go
```
game.getServer.runAsServer("playSound <sound> <player>");
```
than search for a way to basically recode that specific command over again.

**Comment by Deamon5550** [comment]
Perhaps a better solution would be adding a method to CommandSource to run a command as that source. For the console this would then be `game.getServer().getConsole().runCommandAs("playSound <sound> <player>");`.

**Comment by AlphaModder** [comment]
I assume in the future, we will be able to send commands from a commandsource, so we can use something like `game.getServer().getConsole().runCommand("say test");`.

**Comment by MikaalSky** [comment]
Yeah, going further down into getConsole makes much more sense, because we are, you know, using the console for this.

**Comment by zml2008** [comment]
game.getCommandDispatcher().execute(game.getServer().getConsole(), "command string");

**Comment by MikaalSky** [comment]
Correction:
game.getCommandDispatcher().process(game.getServer().getConsole(), "command string");

**Comment by ryantheleach** [comment]
Wouldn't it make more sense for the plugin itself be a commandSource if it's running commands?

Would allow for other plugins to check what's running it. Also Scripting plugins would probably have a use for it as well.

A remote console commandSource plugin could use the output to the commandSource to send back to a remote console.
