### ISSUE TITLE
Make MessageEvent more wide-spread

### ISSUE THREAD

**Issue by MikaalSky** [SpongePowered/SpongeAPI#632]
At the moment, MessageEvent (for some reason) only targets the Player Chat, not any of the other chat sources like command callbacks (Text.of()). If this would target Text.of() calls, then MessageEvent would work much better.

Possible uses would be for color coding chat messages, replacing "filtered" words, ect..

**Comment by boformer** [comment]
You want to call the event when a ``Text`` instance is created? That does not make sense.

It would make sense to fire an event when the ``CommandSource.sendMessage`` method is called. I guess that's what you mean.

**Comment by AlphaModder** [comment]
Not a good idea to do it for CommandSource.sendMessage, only when the Minecraft Server calls it. It's up to plugins to fire events when they do things. This is why setting a block in the world doesn't fire an event.

**Comment by boformer** [comment]
There should be a way to disable or modify messages sent by plugins, though.

**Comment by AlphaModder** [comment]
@boformer Why, exactly? Bukkit never had that capability, and it wasn't an issue. If a plugin provides an API, sure, but when would it be a good idea to mess with a plugin without telling it at all?

**Comment by boformer** [comment]
@alphamodder for example if you want to modify the color of the ouput so that all plugin messages have the same color.

Or to call a command silently.

**Comment by Xemiru** [comment]
it'd be better to fire the event when the message packet is about to be sent. probably need it to be a list of players regardless of whether or not its just one player, so as to not flood message events.

**Comment by zml2008** [comment]
imo it's not at all the duty of the sendMessage method to throw an event for the message. this takes away the opportunity for developers to throw alternate events that provide more specific information than simply the formatted text of the message. However, I can see more events that have messages inherit from MessageEvent (like join, quit events).

**Comment by Zidane** [comment]
@zml2008 

We'll keep this open to remember to make changes to the events to pull from MessageEvent
