### ISSUE TITLE
Overriding built-in commands

### ISSUE THREAD

**Issue by MikaalSky** [SpongePowered/SpongeAPI#633]
Right now, when I have this:
cmdService.register(this, new simpleTP(logger, game), "tp");
and I type /tp, it returns the default /tp code, not my plugin's TP.
I know the plugin *IS* running properly because /spongy:tp works.

If .register would override pre-registered commands, that would be great.

**Comment by MikaalSky** [comment]
@zml2008

**Comment by kashike** [comment]
If so, it would be a good idea to map the default Minecraft commands with the `minecraft:` prefix as Bukkit did, to allow for use if overwritten.

**Comment by AlphaModder** [comment]
@kashike I think that will work because of the Minecraft/Sponge fake PluginContainers.

**Comment by MikaalSky** [comment]
@kashike They are already mapped as minecraft:, just the minecraft prefixed commands are being prioritized.

**Comment by gabizou** [comment]
I think the best way to handle this is provide a configuration file that is populated by the overlapping commands and setting the "default" "plugin" to handle the command. In which case command registration still comes as a first come, first serve, but ultimately allows the server administrator to decide which plugin's `/tp` command is used.

**Comment by MattBDev** [comment]
I agree with @gabizou . I really wouldn't like it if I installed a plugin and it changed the default Minecraft command without my approval. I believe that Bukkit handled commands in a similar manner to what @gabizou is describing.

**Comment by MikaalSky** [comment]
Actually, the commands *DO* override the vanilla ones by default, but only if they are defined before the server starts.

**Comment by MattBDev** [comment]
I thought commands couldn't be defined after the server start? There is an issue for it: #609

**Comment by MikaalSky** [comment]
If they are defined at server start, they don't override anything. After server start, they don't define.

**Comment by zml2008** [comment]
you know which plugin's command is used in the event of a conflict is already configurable in the Sponge config, right?

and yeah, MC's commands are registered later to allow plugins to override them easily (or you could register late and MC's will have priority).

This issue seems invalid since everything here is user error.
