### ISSUE TITLE
add addChild(CommandCallable, String ...) to CommandSpec.Builder

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#635]
This will simplify the registration of subcommands.

**Comment by Xemiru** [comment]
isn't it a **builder**? it should probably return the builder itself; unregistering the subcommand from the builder or command isn't necessary considering you can just not register it at all. in most cases there's no reason to have a command thats flexible to where it has to constantly add or remove a single subcommand.

**Comment by boformer** [comment]
@Xemiru You are right, it should return the builder...
