### ISSUE TITLE
Plugin Prefix preceding every message sent to Players?

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeAPI#642]
So slf4j's Logger has a constructor that you can pass in a name that is displayed at the beginning of every log message, which is very convenient so that you don't have to keep outputting the same prefix at the beginning of each log. I think that there should be a configurable option for a plugin to, by default, append a prefix to the beginning of each message sent. I'm not sure how this should be executed, or if it is wanted at all. Any thoughts on this?

**Comment by Zidane** [comment]
If you use the provided logger given to you, such as via injection, it will have your plugin's id as the prefix.

    @Inject private Logger logger;
