### ISSUE TITLE
Change generic type bound in CommandCallable methods

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#645]
Currently, `CommandCallable#getHelp` and `CommandCallable#getShortDescription` return `Optional<Text>`. Since the default behavior of generics is to only allow the specified type, and not subclasses, usages that should be simple become cumbersome.

For example, the expression `Optional.of(Texts.of("Example help"))` *should* be valid as the return value for either of the aforementioned methods. However, the fact that `Texts.of(String)` returns `Text.Literal,` instead of `Text`, means that an unnecessary cast must be added, or a different builder method used.

Changing the generic type bound would allow code that's otherwise correct to compile.

**Comment by boformer** [comment]
So what do you want to change?

The return type of ``Texts.of("string")``?

**Comment by Deamon5550** [comment]
While you can simple return `Optional.<Text>of(Texts.of("Example help"))` it would be more intuitive to not require that I agree.

**Comment by Zidane** [comment]
I agree and approve.

**Comment by gratimax** [comment]
Fixed in  8cf40d9c571269666e54
