### ISSUE TITLE
[CommandSpec] Issue using default executor

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeAPI#646]
(This is copied directly from [this forum post.](https://forums.spongepowered.org/t/commandspec-issue-using-default-executor/7071))

As it is, if you execute a command and no matching sub-commands are found, the main executor is (theoretically) called. However, if I have a setup like [this](https://github.com/BlockLaunch/BLWarps/blob/better-commands/src/main/java/com/blocklaunch/blwarps/BLWarps.java#L137), it does not seem to be the case. I have one main command, "/warp", and 3 sub-commands, '/warp list", "/warp set", and "/warp delete". However, if I attempt to use "/warp mywarp", I expect it to use the default executor. This is apparently not the case, as the output I get is: "Input command mywarp was not a valid subcommand", and then it gives me the usage of /warp. I have tried to resolve this issue multiple times, and I have been repeatedly assured that this works. Any ideas?

Note: I am on Forge build 1371 and Sponge build 438, as recommended

**Comment by MikaalSky** [comment]
I'd assume that CommandSpec.builder() should have a .fallbackArguments() that contain just the default operation arguments.

**Comment by RobertHerhold** [comment]
I don't believe so. It should be fine as it is with .setArguments(). The issue is with using the default executor when a valid sub-command is not found, not not being able to retrieve arguments when the default executor is used rather than a sub-command's executor.
