### ISSUE TITLE
.set ... Safely(Location) doesn't do anything.

### ISSUE THREAD

**Issue by MikaalSky** [SpongePowered/SpongeAPI#648]
@ The Title

**Comment by gratimax** [comment]
Perhaps the specific implementation you are using doesn't work (which I doubt), but setLocationSafely is supposed to function just like setLocation in most cases, except for teleporting players into dangerous areas like lava.

**Comment by Zidane** [comment]
You need to check the optional you are getting in return. Its likely absent

Setting the location safely does a radius check and if no block is found, it won't set the location.

**Comment by MikaalSky** [comment]
You dont get it. I literally set a location on the ground and nothing happens.

**Comment by MikaalSky** [comment]
Nvm i get it :P

**Comment by Xemiru** [comment]
@MikaalSky for future reference, these types of issues seem implementation-specific. file an issue on the corresponding implementation's repository instead of the API, as an API issue only counts if there's something wrong with the method, in terms of its name, layout, sensibility, etc.
