### ISSUE TITLE
The operation after passing through the opening in the wall.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#651]
[IDEA]
The operation after passing through the opening in the wall.
Example: The player goes through the opening in the wall, and he had a message.
Something like the portal without teleportation.
Opening in wall:
[2015-05-07_20 00 02](https://cloud.githubusercontent.com/assets/10154956/7518329/b27f9ba4-f4f3-11e4-8cb8-1c9a565ea394.png)

**Comment by Xemiru** [comment]
this is more a job for a plugin. implementing this would mean the server is mindlessly wasting resources that it may never use.

**Comment by ST-DDT** [comment]
Yes this should defenitly handled by a plugin all alone. Example by listening to `PlayerMoveEvent`s.
Because the opening could have unlimited amounts of shapes.

**Comment by Azatik** [comment]
How will operate a teleportation API (https://github.com/SpongePowered/SpongeAPI/issues/504)?
