### ISSUE TITLE
PlayerDropItemEvent and method getDroppedItems().

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#654]
Method ```getDroppedItems()``` return ```Collection<ItemStack>```.
Why return a ```Collection<ItemStack>```, if at one time you can drop only one itemStack?

CODE returns always 1:
```
    @Subscribe
    public void drop (PlayerDropItemEvent event){
        Player player = event.getPlayer();
        Collection<ItemStack> droppedItems = event.getDroppedItems();
        int size = droppedItems.size();
        player.sendMessage(Texts.of("Drop - " + size));
    }
```

**Comment by gratimax** [comment]
You can drop multiple ItemStacks if you die.

**Comment by Azatik** [comment]
Especially dead, but it has not worked.

**Comment by gratimax** [comment]
Okay, then please file a bug issue on whatever implementation you're testing it on. The expected behavior is for player death to drop all items at once.
