### ISSUE TITLE
Add UUID command element to GenericArguments

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#655]
UUID arguments are useful for commands that are executed by text click actions.

**Comment by zml2008** [comment]
I feel like this is a bit overly generic -- are you trying to look up an entity? or are you trying to look up a player? I'm not sure of many use cases where you'd want to have a plain uuid -- I'm not particularly opposed to implementing a UUID command element, just think more specific command elements would be more helpful for you.

**Comment by boformer** [comment]
I have a custom data element that is referenced by an uuid.

I thought it might be useful to include such a command element in the sponge API.

**Comment by zml2008** [comment]
If you have a custom data element that is referenced by UUID, do you think it would be more appropriate to have it be referenced with a custom command element? or perhaps the eventual User command element? that way people using the command have tab completion & fancy stuff?

**Comment by boformer** [comment]
The command is executed by clicking on "hyperlinks" in chat. Tab completion is not needed. It would also be nice to have a way to exclude the command from help listings.

**Comment by MattBDev** [comment]
I don't think that a UUID command element would be too useful. In some ways I do see how in special cases that a UUID would be used when using a ban-manager or something that stores data. Yet I don't think many people would be typing a UUID in as a command argument. Many people would be using the username (even though it can change) and that can be used to get a `User` and then the UUID from that if needed.
Maybe a bit more of a reason or describing your command in detail will help give us a better idea why you feel this should be added.

**Comment by boformer** [comment]
I will just close this issue. People who want the element should be capable to implement it themselves with little work.
