### ISSUE TITLE
Boss Wither breaking block's his body.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#656]
Boss Wither breaking block's his body. I would like to catch and cancel the event.
And yet the event call the Boss Wither.
Boss Wither breaks Blocks:
https://youtu.be/tkzJi7vcvts

**Comment by Zidane** [comment]
Nice video

I see what you are asking for. No reason we couldn't support this.

**Comment by modwizcode** [comment]
Seems like a clear enough feature, does this currently send an event? I don't see an API issue here, this is an implementation shift probably, wither would just have to send block break events.

**Comment by ST-DDT** [comment]
IMO a EntityBreakBlock(Bulk)Event is enough. Everything else should be covered by the reason or cause system.

**Comment by Zidane** [comment]
We added explosion events to the API and I'm fairly sure the Wither invokes an explosion when breaking a block. You can check the cause and go from there.
