### ISSUE TITLE
Add game.getState()

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#657]
The method returns the [GameState](http://spongepowered.github.io/SpongeAPI/org/spongepowered/api/GameState.html).

This is useful when an object wants to register commands or other items.

**Comment by Zidane** [comment]
This is what the lifecycle events are for. Give me a usecase otherwise.

**Comment by boformer** [comment]
I have a library that registers a service + commands for other plugins.

During the initialization phase, a plugin passes the game instance to a static class of the library that registers the service instance.

The service also listens to state events (to register the service, commands etc.). If the service was initialized after an event occured, the service will not initialize correctly.

That's why I want the method that returns the GameState. The service can detect the state and throw an exception (or register the commands manually).

**Comment by Xemiru** [comment]
Seconding this; had a small discussion over this yesterday in IRC.
>not sure if you were describing my lib or you actually have your own; either way its needed

plus; it'd be much better to be able to retrieve the game state from the Game object instead of creating your own boolean to check whether or not it has passed; even if its just a miniscule variable.

**Comment by Zidane** [comment]
I have accepted this change and it will now be added. @Aaron1011 this is now on your list.

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeAPI/commit/ec1eb7913b3769d7f934a1cb96f3c17068e42e9f
