### ISSUE TITLE
Set time/day specifically for one player

### ISSUE THREAD

**Issue by KieronWiltshire** [SpongePowered/SpongeAPI#665]
I checked the Viewer class and saw that there were no methods for setting the time of day for an individual player. This would be a good feature in my opinion.

**Comment by ryantheleach** [comment]
Would this be better addressed by adding methods to viewer for dealing with time-of-day / weather?

**Comment by MattBDev** [comment]
I think this is partially a duplicate and should be merged with issue #393 since what is being requested cannot be added until that is resolved.

**Comment by gabizou** [comment]
Agreeing that this is going to be merged in with #393.
