### ISSUE TITLE
Fake name/skin API

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#666]
As seen in [SportBukkit](https://github.com/OvercastNetwork/SportBukkit)  (patches: [API](https://github.com/OvercastNetwork/SportBukkit/blob/real1.8/Bukkit/0029-Fake-name-and-skin-API.patch), [Server](https://github.com/OvercastNetwork/SportBukkit/blob/real1.8/CraftBukkit/0080-Fake-name-and-skin-API.patch)).

This API adds methods to control the name a `CommandSource` sees for a `Player`. A fake name, skin, or fake name and skin can be set on a `Player` for a 'viewing' `CommandSource`.
When getting a `Player` by name from the server, a `CommandSource` can be specified to specify which viewer the name is under.

```java
Player kashike;
Player zidane;

// Set the name Zidane sees for this player.
kashike.setFakeName(zidane, "Kitten");

// Set the skin Zidane sees for this player.
kashike.setFakeSkin(zidane, someSkinObject);

// This will return absent/null since there is no player named 'Kashike' on the server in Zidane's view.
game.getPlayer("Kashike", zidane)

// This will return the 'Kashike' player.
game.getPlayer("Kitten", zidane)

// This will return absent/null since there is no player named 'Kitten' on the server.
game.getPlayer("Kitten")

// Returns the player's default name
kashike.getName()
kashike.getName(null)

// Returns the player's name as seen by Zidane.
kashike.getName(zidane)

// Returns the player's default skin.
kashike.getSkin() -> normal skin

// Returns the player's skin as seen by Zidane.
kashike.getSkin(zidane) -> someSkinObject
```

This is semi-linked to https://github.com/SpongePowered/SpongeAPI/issues/623.

**Comment by MikaalSky** [comment]
Issue 666... Spooky.

**Comment by ryantheleach** [comment]
So in what ways do fakeNames differ from display names?

**Comment by kashike** [comment]
@ryantheleach fake name can be `Kitten`, while display name can be `§5Kitten` (colouring, formatting). The same way getName/getDisplayName differs.

**Comment by ZephireNZ** [comment]
As in, what's the difference between `Zidane` having a display name of `Kitten`, and `Zidane` having a fake name of `Kitten`?

**Comment by gabizou** [comment]
I had some thoughts about this being capable with Data API, possibly a `ArtificialPlayerAppearanceData` of sorts?

**Comment by ryantheleach** [comment]
Could it be PlayerAppearanceData, and if unset it defaults to the players normal skin?

That way, you could make it so you could assign Data to a Entitiy, for a viewer, in order to get your per player stuff happening?

**Comment by TheAwesomeGem** [comment]
@ryantheleach I like the sound of that!

**Comment by Xemiru** [comment]
pinging @simon816 as he was able to make some progress implementing the Human entity

**Comment by simon816** [comment]
Here's how I was able to change the skin of a human [[link](https://github.com/SpongePowered/SpongeCommon/pull/19/files#diff-02b669e9cfc6dfab4e27d9f597af0e09R131)]
and change the name [[link](https://github.com/SpongePowered/SpongeCommon/pull/19/files#diff-02b669e9cfc6dfab4e27d9f597af0e09R116)]

It requires some hacks with the player tab list. From some testing it was sometimes inconsistent whether the skin actually changed (could reduce the problem by sending packets with a bit more delay between them).
It is doable, but depends whether it should be supported in sponge directly.

**Comment by ryantheleach** [comment]
If I understand correctly, the only reason to remove them from the tablist is to clean the tablist of NPC's?

If you are changing a players name and appearance, wouldn't you want them in the tablist?

Also what happens on larger servers whose tablists fill the whole screen? Is it possible to fill the tablist up with blank entries to push the npc's off of the end of the list? Or is the list sorted alphabetically or something?

**Comment by nikosgram13** [comment]
The Skin API using uuid in method:
`https://sessionserver.mojang.com/session/minecraft/profile/<uuid>`

**Comment by kashike** [comment]
@ryantheleach that's not what this issue is. that's https://github.com/SpongePowered/SpongeAPI/issues/623

**Comment by ryantheleach** [comment]
@kashike I was replying to simons comment on requiring hacks with the playerlist.

as far as I am aware, this issue could use the same method, without the hacks ever being needed.

**Comment by simon816** [comment]
The player will need to be respawned on the client (like humans do) because it is not possible to change the skin/name of the player once spawned. The [tab list packet](http://wiki.vg/Protocol#Player_List_Item) (`0x38`) has an action to update the name but from what I can remember when testing it will only change the value in the tab list, not above the player's head.
I estimate the following actions need to be done:
1. Remove player from world
2. Remove from tab list
3. Set new name/skin for the player (sensitive to the player viewing this player)
4. Add to tab list
5. Spawn back in world

**Comment by kashike** [comment]
This is mine, just so people are aware.

**Comment by JBYoshi** [comment]
Wouldn't this be part of #945?

**Comment by kashike** [comment]
Exactly why I'm saying this is mine.

**Comment by ST-DDT** [comment]
Well. If you have a PR that fixes an issue you should link it (if possible bidrectional). So other can actually check.
Otherwise the intention of "this is mine" is not clear at all.

**Comment by Zidane** [comment]
Closing this as it is superceeded by data contexts.
