### ISSUE TITLE
CommandSpec: Fallback arguments if no child command found

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#668]
Right now the command executor only allows to register a fallback executor. The value of the setArguments builder method is ignored.

Use case: A warp command:

/warp add <name>
/warp remove <name>
/warp --> lists all warps (fallback executor)
/warp <name>  (fallback executor with arguments)

**Comment by TheAwesomeGem** [comment]
A way to specify fallback executor would be great.

**Comment by boformer** [comment]
There is the setExecutor method for that.
