### ISSUE TITLE
Vehicle-related events are missing

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#669]
```
[23:45:01] <Kashike> don't recall seeing an answer to my question earlier - vehicle events are missing, or?
[23:45:56] <@Zidane> Kashike, most likely yes
```

**Comment by simon816** [comment]
@kashike is this still an issue?

**Comment by kashike** [comment]
@simon816 As far as I can see, yes. There should also be a `Vehicle` interface to mark "vehicles".

**Comment by simon816** [comment]
Aren't all entities able to act as 'vehicles'? i.e. Entity A can ride on B, this is represented as `VehicleData` and `PassengerData`

**Comment by gabizou** [comment]
Isn't this handled with `MountEntityEvent` and `DismountEntityEvent`?

**Comment by kashike** [comment]
Are these implemented?
- Cancellable leave/exit vehicle
- Cancellable enter vehicle

**Comment by simon816** [comment]
@kashike whether they're implemented or not is something for SpongeCommon
In terms of the API,
> Cancellable leave/exit vehicle

`DismountEntityEvent`, it's not cancellable but that could be added
> Cancellable enter vehicle

`MountEntityEvent`

**Comment by me4502** [comment]
Is this still unresolved? Since this was merged, https://github.com/SpongePowered/SpongeAPI/pull/1340, DismountEntityEvent is cancellable. Are there any other vehicle events that need creation?
