### ISSUE TITLE
CustomInventoryBuilder should take Text.Translatable as name parameter

### ISSUE THREAD

**Issue by ConnorStone** [SpongePowered/SpongeAPI#672]
CustomInventoryBuilder uses

```java
CustomInventoryBuilder name(org.spongepowered.api.text.translation.Translatable name);
```
shouldn't this be

```java
CustomInventoryBuilder name(org.spongepowered.api.text.Text.Translatable name);
```

@zml2008 suggested creating this issue when I asked for help on the matter.

**Comment by Mumfrey** [comment]
I'm aware that there are a few places in Inventory API where `Translatable` has mistakenly been used instead of `Translation`, particularly in the `Inventory` interface itself. I will change these to `Translation` all at the same time.

**Comment by Bammerbom** [comment]
Item names can't be clickable etc.

**Comment by gabizou** [comment]
> Inventory names can't be clickable etc.

As shown with `DisplayNameData` and the [Flardians](https://github.com/SpongePowered/Sponge/blob/master/sdk/src/main/java/org/spongepowered/Flardians.java) plugin during the State of Sponge 3, Minecraft very well will render formatted text.

**Comment by Mumfrey** [comment]
Yes but the information is replicated to the client as a `String`. As I said above, I'm changing it to `Translation` because `Translatable` was used by mistake.

**Comment by simon816** [comment]
@Mumfrey add this to the minor issues list? I'm hoping to knock off a bunch of minor issues soon.
