### ISSUE TITLE
CommandException should not always lead to the Usage being displayed

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeAPI#674]
According to its javadoc, the `CommandException` class is intended for propagating an error to the `CommandSource`. It will print an error message supplied followed by the commands usage message.

Since there are plenty of use cases where a command was used correctly but the execution failed due to circumstances other than the supplied arguments. In those cases displaying the usage would be at best useless and at worst misleading.

In order to retain `CommandException`s as a preferable way to inform command users of errors and failures, I propose introducing a boolean flag `shouldDisplayUsage` defaulting to `false`.

**Comment by boformer** [comment]
Or only display the usage string if the exception was an instance of argumentParseException

**Comment by zml2008** [comment]
component of #548

**Comment by zml2008** [comment]
being combined into #548
