### ISSUE TITLE
Commands: Used alias

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeAPI#676]
In the process() and getSuggestions()  methods of the CommandCallable interface, add a way to gain the alias that is used.

**Comment by boformer** [comment]
First of all, I don't understand why the alias is important for the ``getSuggestions`` method. It should only return the usage string without the alias (The help system appends the alias).

For the process method: @zml2008 removed the ``parents`` list a while ago. I think it was quite useful. I propose to add it again.

**Comment by boformer** [comment]
I really recommend you to use the new commands API: https://docs.spongepowered.org/en/plugin/basics/commands.html

**Comment by Bammerbom** [comment]
Oh didn't know about it. I will try that when I am home.

**Comment by Bammerbom** [comment]
So, how do I get the used alias in the new system?

**Comment by ZephireNZ** [comment]
The whole point of the new system is that it does a lot of work for you. Tab complete is worked out based on the arguments you create, and so does the usage.

**Comment by Bammerbom** [comment]
Meh, so complex.

How would I for example return a list of homes?

**Comment by boformer** [comment]
@Bammerbom You have to write your own commandElement: http://spongepowered.github.io/SpongeAPI/org/spongepowered/api/util/command/args/CommandElement.html

The documentation for that is missing right now.

**Comment by Bammerbom** [comment]
I am messing around with it but don't understand how it works. So I guess I have to wait for the documentation. (Except if someone helps me :smile:  )

**Comment by Bammerbom** [comment]
Found out how it works, but still the same question.

"How to get the used alias?"

**Comment by ryantheleach** [comment]
What do you need/want the used alias for?

The only thing I can see wanting it for is displaying help text to the user.

**Comment by Bammerbom** [comment]
I have a /gamemode command with as alias /creative.

The code for them is 95% the same so I don't want to split them up. What I did before (bukkit) was check the used alias.

**Comment by zml2008** [comment]
Well, the executor may be similar. but command description, help text, and arguments are all different. You probably want to register multiple commands with perhaps a shared executor.

**Comment by Bammerbom** [comment]
I now made it on a way that it registers multiple commands for different aliases. I still don't think it looks that good in for example help lists but I have to do it this way then.

**Comment by ryantheleach** [comment]
Wouldn't all the aliases of a command be listed in a help list anyway?

**Comment by boformer** [comment]
@ryantheleach That depends on the help implementation.

**Comment by ryantheleach** [comment]
Can arguments be supplied for an alias?
like alias /creative to /gamemode 1 for instance?

**Comment by boformer** [comment]
you can make a command that creates a commandContext (put(mode, 1) and passes it to gamemode command executor.

**Comment by ryantheleach** [comment]
That's not what I was asking.

@boformer 
Bukkit's alias system : http://wiki.bukkit.org/Commands.yml#aliases

Is sponges alias system as powerful, or is it just a straight /alias = /command?

so @Bammerbom were you previously just straight aliasing /creative to /gamemode, or aliasing "/creative" to "/gamemode creative"

**Comment by zml2008** [comment]
Sponge doesn't have a command aliasing system at all like that.
The only thing end-user configurable is which plugin gets the undecorated command (/command as opposed to /<pluginname>:command) -- which is in sponge's global config

**Comment by Bammerbom** [comment]
@ryantheleach I was just aliasing /creative to /gamemode, and when the /gamemode command was runned it checks for the alias and executes the right code

**Comment by zml2008** [comment]
Up for review with #548, but for now seems unneeded
