### ISSUE TITLE
Text API: Replace function

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeAPI#678]
I need a replace function in the Text class. I want to replace a certain String (Regex support? I don't need it but maybe orders do) with a text object.

Example usage:

    //Don't replace it directly because this string is in a messages file.
    Text t = Texts.of("Welcome to the server: %Player");
    t.replace("%Player", Texts.builder("Bammerbom").color(TextColors.GREEN).onClick(TextActions.runCommand("tp Bammerbom")));

**Comment by Minecrell** [comment]
#639 is related to this

**Comment by boformer** [comment]
I would say #639 is exactly what you want.

**Comment by Bammerbom** [comment]
Didn't see that one. Closed because of duplicate.
