### ISSUE TITLE
AbstractDelegateExtent ?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#680]
People have discussed using an extent for arena relative co-ordinates, filtering and more.

It would be useful to have an AbstractDelegateExtent that by default delegated all methods to a specified parent.

This would allow people to only override the methods needed to redirect locations.

Thoughts?

**Comment by Zidane** [comment]
This would fall in-line with the ticket for the more useful extent hierarchy ticket.
