### ISSUE TITLE
Provide a way to access related Inventories, eg. Ender Chest Inventory

### ISSUE THREAD

**Issue by ghost** [SpongePowered/SpongeAPI#684]
Currently there is none, neither via the Player Interface or any of its superinterfaces, nor via Inventory queries.

**Comment by Mumfrey** [comment]
Actually in the same vein, a way to get a particular inventory *related* to another object would be useful. So I think I can solve this in a way which still remains quite generic. Let me see what I can come up with.

**Comment by ST-DDT** [comment]
To bring this up again.

Chest/Container blocks states may have an inventory.
The player has two or more inventories. The local and the ender chest.

The first part can basically covered by `InventoryHolder`.
The other part is quite difficult. To pick up the generic approach: Maybe this can be solved with some query like reference or key.

- `InventoryHolder#getInventory(InventoryKey) : Optional<Inventory>`
- `InventoryKey`s 
  - `ENDER_CHEST`
  - `MULE_CHEST`
  - `DEFAULT`
  - `BAGPACK` (Custom)
  - ...

The last point to consider is the horse/mule chest inventory part of the horse's main inventory or is it a separate inventory similar to the Player's ender chest. In the first case the `Player` is the sole exception to the 1 inventory per holder rule.

**Comment by ryantheleach** [comment]
I'd like to know how this could work with multiple universes. redirect the inventory that an event is affecting?

e.g. a plugin is completing a shop sale in a given universe, but the player is currently in the creative universe. multiworld plugins need to be able to cancel this, and direct it to the appropriate inventory / buffer.

**Comment by Zidane** [comment]
This was solved for the Player's inventory and their ender chest inventory a long time ago.
