### ISSUE TITLE
add PlayerChatTabCompleteEvent

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeAPI#689]
Use case:
conversation commands: using the chat as command and providing other than default player tab-completion

**Comment by Faithcaio** [comment]
This issue was about tab-completion in chat.
The commit adds an event for tab-completion in commands.

**Comment by gratimax** [comment]
@zml2008 while you added an event for command completion, @Faithcaio was asking for completion _no matter_ the given text, meaning that he wanted to complete normal chat text that was not specifically a command.

**Comment by Zidane** [comment]
I can add this event but need some details.

For starters, does hitting tab send your current chat text up to the server?
