### ISSUE TITLE
Spring clean Data API javadocs

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#693]
Most of the javadocs need some looking over and elaboration on their operations.

Feel free to reply with some specific examples where javadocs are missing or needing cleanup.

**Comment by SonarBeserk** [comment]
https://github.com/SpongePowered/SpongeAPI/issues/647 seems to be a related issue. Needs to have the documentation updated to be more clear.

**Comment by saladoc** [comment]
The docs of https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulator/MappedData.java explicitly refer to ItemStacks

**Comment by simon816** [comment]
@gabizou With the values API on the horizon, is this issue still needed?
Maybe posting comments on #685 would be more useful.
This seems like it could be covered by the minor issues list.

**Comment by ryantheleach** [comment]
The DataPriority JavaDocs could do with some hard examples of different data.

**Comment by ryantheleach** [comment]
Also DataManipulators state that you should check to see if the DataHolder is compatible before filling, but not what to return.

Optional.absent() or Optional.of(this)

**Comment by gabizou** [comment]
When #685 is merged, this will likely be bundled, unless needed.

**Comment by Zidane** [comment]
#685 was merged and brought upon new docs. They'll be slowly revised over time.
