### ISSUE TITLE
Ability to set Human skin using Property

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#695]
Currently, `SkinData` can only be set using a `UUID`. [I see no reason why a `Property` cannot be provided instead.](https://github.com/SpongePowered/SpongeCommon/commit/4f7f02d591dd33ea87050a77808bbb8f38be4c00#diff-02b669e9cfc6dfab4e27d9f597af0e09R142)

```
simon816 | maybe it could be part of the UserCache thing
 Kashike | is that an open PR?
simon816 | it was merged yesterday
 Kashike | Only issue is that the SpongeAPI `GameProfile` has no properties
 Kashike | and that there's no way to `put` an entry into it :P
simon816 | make an issue. Perhaps GameProfile could be a DataHolder
```

**Comment by gabizou** [comment]
What type of Property?

**Comment by kashike** [comment]
`com.mojang.authlib.properties.Property` or similar

**Comment by ST-DDT** [comment]
What additional data are included in there that are required/useful for setting the skin?
(From where would you get an instance of that?)

**Comment by Aaron1011** [comment]
Allowing a Property would allow setting the skin (and cape) directly, even if there isn't a player with them.

The catch is, the client won't accept them without a valid signature (also from the property) This meas that the skin must have been used by a player at one poit, AND the plugin must have already gotten the signature.

**Comment by kashike** [comment]
Correct, @Aaron1011. It is very easy to obtain a `Property` filled with the `name`, `value`, and `signature` to use in this case.

**Comment by ST-DDT** [comment]
And using an uuid only sets the skin (without the cape)? 
Or does using an uuid require that the player with that uuid must (have) be(en) online to work?

**Comment by Aaron1011** [comment]
@ST-DDT: The uuid of a `GameProfile` is independent of the `textures` property - any pair can be combined.

The value of the `textures` property itself is a b64-encoded json string, which contains (among other things) the profile skin and cape urls.

Vanilla requires this b64 blob to be signed - which means that you can't mix and match skins and capes. I could give a human Notch's skin and cape, or my skin and no cape -  but not my skin and Notch's cape, or Notch's skin and no cape.

**Comment by kashike** [comment]
This is mine, just so people are aware.

**Comment by Aaron1011** [comment]
@kashike: Was this addressed by your game profile changes?

**Comment by kashike** [comment]
@Aaron1011 It'll be addressed with contextual data.

**Comment by TheRaspPie** [comment]
+1 for this. While testing I encountered something strange:

Why does a PropertyMap require a key in `put` although it is already required while creating the `ProfileProperty` with a `GameProfileManager`? More strangely, if I create the property with name `"textures"` and set it with `put` with a **different** name (i.e. `"texture"`), it doesn't throw an exception! Also, if I set it on a `TabList`, it shows the right textures on the client.

**Comment by TheRaspPie** [comment]
Is there an update on this? I'm still using my little reflection hack. ;)

**Comment by JBYoshi** [comment]
Does [`SkinData`](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/SkinData.java) suffice?

**Comment by TheRaspPie** [comment]
Say, for example, you want to prepare multiple skins with one account in advance.
You could save the signature of each one of them without needing to have a live account associated with the skins at the point where you send them to the player.
With the current version of SkinData, you can't do that.

**Comment by ryantheleach** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/a3431307f06996321489b69664b16202e8806042 on Bleeding.

@Aaron1011 Does this cover this issue?

**Comment by Aaron1011** [comment]
Yes, this is now possible in bleeding.
