### ISSUE TITLE
Allow opening GUIs on the client.

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#696]
Currently, Sponge has support for interacting with inventories through the Inventory API. However, there's no way to open a specific window to a player (e.g. a crafting inventory, a chest, a brewing stand, or a window with a custom number of slots) using the API.

While the inventory API (correctly) allows plugins to work with an inventory without knowing specifically what it is, an API for opening windows would require exposing the [specific window types](http://wiki.vg/Inventory#Windows).

A related issue is filling out `InventoryClickEvent`, so that plugins can receive information about how a player has interacted with an open window.

**Comment by gabizou** [comment]
This is what I was hinting at for #682 since this would go hand in hand.

**Comment by KieronWiltshire** [comment]
It would also be nice to perhaps open interfaces such as the CommandBlock or sign interface.

**Comment by AlphaModder** [comment]
Command Block and Book GUIs are client-side only, and therefore not possible for the server to tell the client to open by any means.

**Comment by JBYoshi** [comment]
@AlphaModder Actually, the server can tell the client to open the GUI, and it can intercept the response and send it to plugins.

**Comment by AlphaModder** [comment]
@JBYoshi Yes, on all GUIs but those two. There is no packet sent to the client that will cause it to open a book or command block.

**Comment by Cybermaxke** [comment]
@AlphaModder You can open a book gui with packets, but it must be a written book (you cannot modify it) and the player must be holding the book item stack in his hand. (Can be tricked using other packets).

```java
playerNetServerHandler.sendPacket(new S3FPacketCustomPayload("MC|BOpen", new PacketBuffer(Unpooled.buffer())));
```

**Comment by AlphaModder** [comment]
@Cybermaxke Yes, I meant you can't open a virtual one with no book item in the way you can container & sign GUIs.

**Comment by gabizou** [comment]
Unfortunately, the biggest issue with books is that it's almost all controlled by the client, there's very little we can do to control what is shown in the book without doing some really hackish workarounds to "update" the current equipped slot with a book item, send the item to the client, and then hopefully, receive an event when the client actually closes the book, then finally, re-equip the original item that belonged in the slot (removing the artificial book).

**Comment by Cybermaxke** [comment]
@gabizou The item stack on the client can be reset directly afterwards you send the open book packet, so there is no need for checking the close packets and it won't look glitchy.

**Comment by ST-DDT** [comment]
@Cybermaxke Are you sure about this?
I remember an issue with one of my Bukkit plugins, that accidentally closed the (help) books by switching the currently held item. But this could have had other issues as well.

**Comment by Cybermaxke** [comment]
@ST-DDT Yes, I have tested it and you are unable to switch the currently held item once you have opened the gui.

**Comment by viveleroi** [comment]
This is an essential feature for my server so I'm voicing my support. Also discussed in https://github.com/SpongePowered/SpongeCommon/issues/443

**Comment by Zidane** [comment]
Closing this as its part of @simon816 's PR.
