### ISSUE TITLE
Scheduler Cleanup

### ISSUE THREAD

**Issue by FerusGrim** [SpongePowered/SpongeAPI#700]
This is being brought up as an issue because of [this topic].

At this point, I'm just curious if there are any plans for a Scheduler cleanup, or if it's necessary. It could be beneficial, if no changes are planned, to either suggest that it be made easier, or at least get a written-in-stone explanation of why the system is the way it is.

Or, obviously, if a change/cleanup _is_ planned, to hear what the solution is.

[this topic]: https://forums.spongepowered.org/t/sponge-sheduler-for-beginners/7411/2

**Comment by simon816** [comment]
#697

Any suggestions welcome :)

**Comment by FerusGrim** [comment]
Ha. I was looking through PRs a few days ago, and didn't notice anything about a Scheduler. I didn't think that this issue would coincide with such a recent one. My bad for not checking.
