### ISSUE TITLE
Provide a sub-command off /sponge to get a list of plugins

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#702]
It would be a huge plus to have a command (`/sponge plugins` or similar) to get a list of plugins currently active. It would be permission-based like the rest of the `/sponge` commands (currently only implemented in Sponge).
This command is helpful when helping users with issues (conflicting plugins, etc), and is much more reliable than someone manually typing a list of plugins (spelling issues, missing parts of a plugin name, etc)

@Zidane said he wasn't sure about adding this, but didn't specify a reason why (as far as I saw).

**Comment by gratimax** [comment]
This belongs on SpongeCommon since the implementation has the `/sponge` command, not the API.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/50
