### ISSUE TITLE
When using fromLegacy with a string that contains "& " it cuts the string at that point.

### ISSUE THREAD

**Issue by Buuz135** [SpongePowered/SpongeAPI#703]
As explained here https://github.com/Buuz135/ExtraChat/issues/27 when you have a string that contains & (& is the char used in fromLegacy) and a space after it it cuts the string at that point.

**Comment by gratimax** [comment]
While it may be valid, this is an issue for https://github.com/SpongePowered/SpongeCommon as the actual implementation lives in SpongeCommon and not the Sponge API. Please post it there instead and then we can reproduce, handle, and fix it.
