### ISSUE TITLE
Add a way to convert a String to an ItemStack / Entity

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeAPI#704]
- Add a way to convert a String like "minecraft:planks[variant=spruce]" to an ItemStack.
- Add a way to edit an existing ItemStack with strings like [variant=spruce]

The upper 2 are formats described like here:
https://docs.spongepowered.org/en/plugin/blocks/concepts.html

- Add a way to use 'vanilla' strings like {powered:1,CustomName:Powered Creeper} on an Entity
- Add a way to use 'vanilla' strings like {display:{Lore:["Wooden planks"]}} on an ItemStack

**Comment by ST-DDT** [comment]
How about something like this:
[DataParser](https://github.com/SpongePowered/SpongeAPI/compare/master...ST-DDT:DataParser#diff-13abca78bf8b20e8224630b9f96c86b9R55)

````java
public interface Parser<T> {
    Optional<? extends T> parse(Function<String, ?> input);
}
````

````java
public class Parsers {

    public static final Parser<AgeableData> AGEABLE_DATA_PARSER = null;

    // ...
    public static final Parser<Collection<DataManipulator<?>>> ENTITY_PARSERS = null;
    // ...
    public static final Parser<AuthorData> AUTHOR_DATA_PARSER = null;
    // ..
    public static final Parser<Collection<DataManipulator<?>>> ITEM_PARSERS = null;
}
````
With something like this on Common:
````java
DataManipulatorRegistry dmr = ...;
// Entity
List<Parser<? extends DataManipulator<?>>> entityParsers = new ArrayList<Parser<? extends DataManipulator<?>>>();

AGEABLE_DATA_PARSER = new SingleElementParser<Object, AgeableData>("age",
		Functions.compose(new SingleValueDataFunction<Integer, AgeableData>(dmr, AgeableData.class), ConversionFunctions.PARSE_INTEGER));
entityParsers.add(AGEABLE_DATA_PARSER);
// ...
ENTITY_PARSER = new CollectingParser<DataManipulator<?>>(entityParsers);

// Item
List<Parser<? extends DataManipulator<?>>> itemParsers = new ArrayList<Parser<? extends DataManipulator<?>>>();

AUTHOR_DATA_PARSER = new SingleElementParser<Object, AuthorData>("author",
		Functions.compose(new SingleValueDataFunction<Text, AuthorData>(dmr, AuthorData.class), ConversionFunctions.PARSE_TEXT));

itemParsers.add(AUTHOR_DATA_PARSER);
// ...
ITEM_PARSER = new CollectingParser<DataManipulator<?>>(itemParsers);
````

The Parser then could be wrapped in an `CommandElement` which converts the JSON `String` to a `Map<String,?>` (recursive) which could be wrapped in a `Function` and then passed to the `Parser`.
(The `Function` is only used to allow using `Config`s etc as well, it also allows some custom key/value remappings and default values)

**Comment by gabizou** [comment]
A few thoughts on this: 
* Minecraft has a particular section on how data is parsed from a string, but the strings themselves can be really long such that only a `CommandBlock` can execute them.
* The format for the strings are entirely implementation dependent and the overall format of them as well is entirely dependent.
* Custom data is made even more so interesting due to the nature of custom data being entirely ambiguous
* All of this still screams asking for support for something that is entirely implementation dependent and may/may not work between Minecraft versions (self evident with Mojang deprecating some tags in 1.9).

**Comment by gabizou** [comment]
Use `DataContainer`s and `DataTranslator`s.
