### ISSUE TITLE
[Proposal] Registry Component System

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/SpongeAPI#706]
The current `GameRegistry` is a nightmare, even cleaned up or split into modules, it still represents a messy API. 

I think that similar to the `Manipulator`s of the Data API, the `GameRegistry` could have a `<T extends Factory<?>> T getFactory(Class<T> clazz)` (or similar, my knowledge of parameterized generic methods isn't always right), method that will return instances of the factories used in the API, which is basically the point of GameRegistry, to represent a link between implementation and interface for instance creation. 

In the case of the Map API this might look something like this.

```java

public interface MapSpecificationFactory implements Factory<MapSpecification> {
  /**
   * Create a new virtual map with the next unused ID.
   */
  MapSpecification createVirtual();

  /**
   * Create a new virtual map with the specified ID, replacing existing stored
   * values if the ID is already used.
   */
 MapSpecification createVirtual(String id);

  ...
}
```

I welcome all opinions on this, maybe it's a terrible idea for some piece of programming wisdom I haven't learned yet. However I've found this strategy to be clean and convenient.

Pinging @SpongePowered/developers for input.

**Comment by ST-DDT** [comment]
IMO the GameRegistry just needs some more cleanup.
Spamming hundreds of factories all over the gameregistry will not help either.
My suggestions which parts should be moved to a sub interface/factory/registry...
* Statistics (as there are quite a lot methods) = 10% reduction
* MapSpecification  (as you suggested)

And my suggestions that should be cleaned up more / removed from the game registry
* Most builder methods = 50% reduction

**Comment by modwizcode** [comment]
MapSpecification and all of these still need factories, it's a requirement
for our system. I'm not talking about rebuilding this from the ground up,
I'm talking about a way to simplify the retrieval of implementation
instances from API interface classes.

**Comment by modwizcode** [comment]
See https://github.com/SpongePowered/SpongeAPI/pull/717
