### ISSUE TITLE
EntityDamageEvent Changes

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#707]
So, I've had some time to think about the long often misrepresented `EntityDamageEvent` that existed for quite some time with previous API's, and I think I'm on the verge of finding an appropriate solution for the following problem:

Skeleton shoots bow launching an arrow hitting a Player.

This is pretty plain and simple to understand what happens, but we need to look at it much deeper to fully understand what the final damage comes out to:

I'll give an order of how the damage is calculated:
1) Skeleton is shooting the arrow, by default it will apply say 3 damage to the Arrow
2) The bow, if enchanted applies a bonus amount of damage to the arrow, say 1.5 additional damage
The final raw damage of the arrow is now 4.5.

Now here comes the fun part:
The Player is hit with the arrow
1) The damage is modified based on the game difficulty, in this case, it's on `HARD` difficulty, so the damage is multiplied by 1.5 (damage is now 6.75)
2) Armor calculations are factored in, Say that the player has full iron armor, and the iron armor reduces the damage by 2 (damage is now at 4.75)
3) Potion effects add to resistances, so damage is reduced by multiplying damage by 20 and dividing by 25 (damage is now at 3.8)
4) Armor Enchantments reduce the damage by 20% for example (the damage is now at 3.04)
5) The Absorption potion effect is now factored in to find out how much actual health is removed from the entity, say we have an additional 2 health from absorption, (damage is now at 1.04)

The end result is a damage value of 1.04 damage dealt directly to the entity, where 4.5 damage originated.

The reason why I walked you through all of this is the following: I've been contemplating that we should have a LivingPreAttackEntityEvent of which we can trace the modifiers for the damage being dealt to the entity (in the case of the skeleton shooting, there's the modifier of the bow and the modifier base damage of the skeleton). After that event, we'd need a proper `WeightedCollection` to store the `DamageModifier`s and their `Function`s being applied to the incoming damage for an `EntityDamageEvent`. Considering the limitless possibilities of being able to identify the `DamageModifier`s and the `Cause` for each modifier, I do believe this would make an excellent change with Causes PR in the near future.

I'd like to hear some thoughts from the developer community.

**Comment by modwizcode** [comment]
Only one word describes this proposal, Awesome! I would like to hear more about why we are storing `Function`s applied. Also what is a `WeightedCollection`?

**Comment by AlphaModder** [comment]
This looks great! I don't understand the use of the `WeightedCollection`, though. Why are `DamageModifiers` weighted? Wouldn't a simple `ArrayList<DamageModifier> work? That way there's a set order, and you can insert a modifier in or rearrange it. I wonder if there are any other events that could benefit from a good look-over like this one?

**Comment by TheAwesomeGem** [comment]
I have the same question as AlphaModder. The idea seems fantastic for a RPG server though especially for us.

**Comment by DarkArc** [comment]
So breaking things into 2 pieces, the pre-calculation data, and the post calculation effect? Yes, that sounds absolutely fantastic! I need this data for so many things that I can't do with Sponge at the moment...

**Comment by gabizou** [comment]
Added in 36ba40439d38eaade3833bd45048849742ff79d2
