### ISSUE TITLE
Attempts to get the ItemType with the given ID and NAME

### ISSUE THREAD

**Issue by nikosgram13** [SpongePowered/SpongeAPI#709]
Something like this in future?

```java
/*
 * Attempts to get the ItemType with the given name.
 *
 * @param name of the ItemType to get.
 * @return the ItemType if found, or null.
 */
ItemTypes.getType("SPONGE");

/*
 * Attempts to get the ItemType with the given ID.
 *
 * @param id of the ItemType to get.
 * @return the ItemType if found, or null.
 */
ItemTypes.getType(19);
```
and
```java
/*
 * Attempts to get the BlockType with the given name.
 *
 * @param name of the BlockType to get.
 * @return the BlockType if found, or null.
 */
BlockTypes.getType("SPONGE");

/*
 * Attempts to get the BlockType with the given ID.
 *
 * @param id of the BlockType to get.
 * @return the BlockType if found, or null.
 */
BlockTypes.getType(19);
```

**Comment by AlphaModder** [comment]
As for string names, yes. However, we will *never* expose the numeric ids. They are an implementation detail, and will become unreliable soon anyway.

**Comment by simon816** [comment]
This is already possible with `GameRegistry`. No?
Oh and as @AlphaModder said, numeric IDs will not be exposed. They are a thing of the past now.

**Comment by Deamon5550** [comment]
You get items by name using [this method in GameRegistry](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/GameRegistry.java#L107).

An example would be `GameRegistry.getType(ItemType.class, "SPONGE")` which returns an `Optional<ItemType>`.

**Comment by nikosgram13** [comment]
Can I use this method and for the GameModes?

**Comment by simon816** [comment]
You can use it for any catelog type, see the list in [CatelogTypes](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/CatalogTypes.java)
