### ISSUE TITLE
Possible ways to compare Cataloged Types?

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeAPI#710]
Please note that this is *not* a best practice question. This is to clarify if plugins will horribly break if the wrong comparison method is used / people have a choice to use what they deem more readable.

Is it guaranteed that the identity check (`someBlock.getType() == BlockTypes.STONE`) will return the same as the equality check (`someBlock.getType().equals(BlockTypes.STONE)`) for cataloged types? 

When I asked this question on IRC a couple of weeks ago specifically aimed at `BlockType`s, the answer was 'yes'. Now I'm asking to clarify that this shall be true for all cataloged types over all implementations, so that the docs may accurately represent that stance.

**Comment by Xemiru** [comment]
This purely depends on whether or not `someBlock.getType()` returns `Blocktypes.STONE` and not a new instance that it implements on its own (which is a bad idea unless you're writing for mods). The answer is yes since it points to the same reference assuming the method _does_ return the former.

Because this is in the API, then it should be true across all implementations assuming all implementations follow the above rule to return the reference given by `BlockTypes`. Alternatively, if using this isn't a trusted way (I honestly still find it unreliable to use; it breaks if something changes), then one can also just use `someBlock.getType().getName()` and compare that to `BlockTypes.MATERIAL.getName()`.

**Comment by saladoc** [comment]
A little reminder that this question still stands. @gratimax already pointed out that no matter the answer, using `equals()` is to be preferred as a best practice. The docs will reflect that. Still open questions are:

1. Best practices aside, is it possible to use `==` for all `CatalogedType`s introduced by Sponge itself or will it break plugins?
2. Is the `id` supplied to the `GameRegistry#getType(Class, String)` method case sensitive? 
3. How can custom `CatalogedType`s be added to the game registry?

**Comment by ST-DDT** [comment]
May be a little late:

> Best practices aside, is it possible to use `==` for all `CatalogedType`s introduced by Sponge itself or will it break plugins?

Yes, this is possible for most `CatalogedType`s. Although i cannot guarantee it for all (future) catalog types/implementations. But `BlockType`s and `EntityType`s will work usually.

> Is the `id` supplied to the `GameRegistry#getType(Class, String)` method case sensitive?

Yes, but i'm pretty sure that this will change in the future. https://github.com/SpongePowered/SpongeAPI/pull/717

> How can custom CatalogedTypes be added to the game registry?

This is currently not possible API wise. Why would you like to do this?
Maybe this can be added with https://github.com/SpongePowered/SpongeAPI/pull/717

**Comment by ryantheleach** [comment]
Saying yes, then mentioning you can't guarantee it is a good way to get burned.

A better option would have been No, you can't guarantee it for future catalog types / implementations, it will likely cause bugs if you use == when you need .equals unless mentioned in the contract of the class, in which case the implementation is at fault.

**Comment by ST-DDT** [comment]
> Saying yes, then mentioning you can't guarantee it is a good way to get burned.

Yeah, you are right. Thanks for the reminder.

> It's like you didn't even read the original issue.

>> Now I'm asking to clarify that this shall be true for all cataloged types over all implementations, so that the docs may accurately represent that stance.

I always referred to those classes as enum like. So yes it would be nice if it could be added to the docs.
But I'm not sure anymore whether it is possible for the impl to fullfill that always.

**Comment by saladoc** [comment]
> This is currently not possible API wise. Why would you like to do this?
If a Plugin exposes a public API and implements a custom `CatalogedType` it may want to ease the work for everyone using it. If a custom type is added to the registry this allows for 
* Usage of `GameRegistry#getType()` instead of relying on a custom way of conversion
* by extension, this allows for the type to be used with existing structures working with `CatalogedType`s such as usage of `GenericArguments#catalogedElement()` 

> I always referred to those classes as enum like. So yes it would be nice if it could be added to the docs. I should have stated this more directly.

That's why I'm asking here. Sadly I have yet to receive a definitive response.

**Comment by ST-DDT** [comment]
I guess you could enforce the discussion by opening a PR with that changes to the javadocs.

If you need help with writing those javadocs i can offer my help.

**Comment by ST-DDT** [comment]
Suggestion for the `CatalogType`'s javadocs
> Represents a type of a catalog that can be used to identify types without using an `Enum`.

> Implementing classes must meet the following requirements for all its members including those which are not listed in the associated catalogue classes:
* Every pair that matches `a.equals(b)` must also match `a == b`
* Every pair that matches `a.getId().equals(b.getId())` must also match `a == b`
* The value of `a.getId()` identifies the reference uniquely and must remain the same while the Server is running or the `Client` is connected to a server
* The values referenced by catalogue classes must remain the same while the `Server` is running or the `Client` is connected to a server.
* The variables in catalogue classes may link to null if the given value is no longer valid and no appropriate alternative can be found. Thus two or more different variables can link to the same value.

**Comment by saladoc** [comment]
Sounds good so far, I can't really think of anything to change in the moment. Maybe we could include the bit about case insensitive IDs and force people to guarantee, that if there is an id "foo" in use, that there are no conflicting "Foo" or "FOO" IDs

**Comment by ST-DDT** [comment]
Here the updated version of my suggestion:
> Represents a type of a catalog that can be used to identify types without using an `Enum`.

> Implementing classes must meet the following requirements for all its members including those which are not listed in the associated catalogue classes:
* Every pair that matches the following: 
  * `a.equals(b)` must also match `a == b`
  * `a.getId().equalsIgnoreCase(b.getId())` must also match `a == b`
  * `a.getName().equalsIgnoreCase(b.getName())` must also match `a == b`
* The `GameRegistry#getType(Class, String)` method must serve all values independently from the case of the real id value.
  * It may or may not return the value for "well known aliases", if they do not conflict with other values
* The value of `a.getId()` identifies the reference uniquely and must remain the same and valid
* The values referenced by catalogue classes must remain the same and valid
* The variables in catalogue classes may link to null if the given value is no longer valid and no appropriate alternative can be found. Thus two or more different variables can link to the same value. It is also possible that one or more values are not listed in the catalogue classes.
* The variables in catalogue classes may not be renamed or removed after they have been fully added once. However they might be renamed shortly after their addition to better fit their content.

**Comment by ST-DDT** [comment]
@saladoc Anything left to discuss/change here?
Then we should proceed here and make a PR.
Would you like to start it or shall I do it?

**Comment by ryantheleach** [comment]
@saladoc seems to have been away from the IRC channgels and github for a little while, if you don't get a response maybe just start anyway.

**Comment by saladoc** [comment]
I'm currently tied up with real life stuff, so I'd be glad if you just
went ahead ;)

Am 19.07.2015 um 12:52 schrieb ST-DDT:

**Comment by Zidane** [comment]
@bloodmc made it where it would match case in-sensitive.
