### ISSUE TITLE
Permissions service: Getting group, prefix and suffix of a player

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeAPI#711]
I couldn't find a way to get this information of a player
- Primary permissions group the player is in
- A list of all permission groups a player is in
- Prefix of the player (or the prefix of the group the player is in)
- Suffix of the player (or the suffix of the group the player is in)

Am I blind or does the permissions service not contain this?

**Comment by kashike** [comment]
Why would a __permission__ service contain methods for dealing with __chat__ prefix and suffixes?

**Comment by Bammerbom** [comment]
Because the **permission** group has the prefix/suffix.

**Comment by ST-DDT** [comment]
Afaik the new API will not include an option to get the primary groups or chat stuff as it.
However you can iterate the parents of your subject and look for groups and hope that the first group is the primary group.
There is/has been a discussion to use the permission hierarchy to provide more stuff/data but without real hints what it looks like or contains.
Something like the data API for subjects.
As an alternative you can cast the service to something more specific like Pex which may cause other issues.

**Comment by Bammerbom** [comment]
I feel plugins like Vault comming if Sponge doesn't contain this.

**Comment by AlphaModder** [comment]
Yeah... no. It's a permissions API, chat formatting is not part of it. If plugins like Vault want to format chat via permissions, let them, but it's not a core part of the permissions system.

**Comment by Bammerbom** [comment]
And how about group names? Is that part of the API?

**Comment by AlphaModder** [comment]
@Bammerbom Yeah, that part I'm less clear on. It could be or not.

**Comment by Bammerbom** [comment]
I feel like groups is a must for the sponge api. 
I can understand prefixes and suffixes will not be implemented.

**Comment by AlphaModder** [comment]
@Bammerbom I'm with you on that one.

**Comment by ZephireNZ** [comment]
What you're describing, at least for groups, is exactly what `SubjectCollection` does.

You can get these 'groups' by name through the service, or get it from their subject with `Subject.getContainingCollection()`.

However AFAIK this doesn't support a subject being in more than one collection. More than likely this could be due to permisison clashes (eg if they have "-perm" in one group, and "perm" in another, do they have the permission?)

**Comment by ryantheleach** [comment]
I'd seriously consider treating your group membership tests as a simple permission test.

just test for "server.groups.groupname" or maybe even define it by a config.

That way it's up to the server owner what the "group" represents, and who inherits it.

There may be actual use cases like manipulating the group a player is in for timed promotions, but for the majority of usecases permissions or dynamic permissions are a lot more useful.

**Comment by zml2008** [comment]
The API supports all of the things the poster asked for:

- groups: Use the getParents() method -- we don't have a separation between primary and 'other' groups here really
- getting prefix/suffix: take a look at the org.spongepowered.api.service.permission.option.OptionSubject interface, do an instanceof check on a Subject instance -- we don't have dedicated prefix/suffix methods -- I suggest using options called `prefix` and `suffix`.

@ZephireNZ SubjectCollection is all subjects of a certain type -- so there is a subjectcollection for users, a subjectcollection for groups, etc.

@kashike @AlphaModder @ryantheleach I expect better from you than entirely ignoring the permissions API when commenting on issues relating to the permissions API. It's not even that hard to take a look at the relevant interfaces -- they are *conveniently* publicly posted to GitHub!

**Comment by ryantheleach** [comment]
I wasn't ignoring the group methods in the API.

Just a lot of the time people don't really *need* groups for plugins and I personally think it's an implementation detail that is handy to leak, as it is *usually* common amongst multiple permissions implementations.

There's very few instances that you truly need a permissions group, as opposed to checking whether a player has a certain permission, or getting all players with a certain permission. And by using a permission you gain the value of contexts and inheritance that server admin's can configure to their hearts content.

If you start using groups and you lock them into using a group for what should be a relatively easy permission test, complicating their permissions setup.

That said, the only real time I can see groups being useful is modifying group membership using the API, and thus modifying what permissions the player currently has.

**Comment by zml2008** [comment]
@ryantheleach Except that the parents option is almost as abstract (any subject can be passed as a parent (even another user, or a group that is not defined anywhere else)), while also explicitly tying into inheritance which makes life more convenient . 

I agree that in most cases groups are not necessary, but in some contexts it makes a lot of sense to be able to get the subject's parents, like in a chat plugin (which is what @Bammerbom appears to be working on) -- this means that server admins get a label that is automatically tied into the permissions inheritance structure rather than having to apply a separate permission to get the label.

**Comment by ZephireNZ** [comment]
Sorry - realised that I got it completely wrong, but forgot to update my comment to match, whoops.

While I think that it could be easier to have groups directly exposed, the current system fits much better with most of the systems we have in place around the API. You *could* look directly at inventory types, but instead you can ignore them and be generic and do 90% of the things people want to do.

If you wanted to do more complex things with the parent/group in question, you can always link into that plugin directly or use an API a la Vault to get more complex information. The system in SpongeAPI IMO is generic enough that the core parts of permissions are represented in a way that doesn't favour any particular way of doing permssions - as it should be.

**Comment by ryantheleach** [comment]
Wouldn't the players prefix be inherited from the group anyway? https://github.com/SpongePowered/SpongeAPI/commit/403b56d64a7d4ac5f04f031f083b4b7e813d177e

**Comment by zml2008** [comment]
HashMap lookups are O(1). What are you talking about?

**Comment by ryantheleach** [comment]
Was thinking about all the inheritance for all contexts, didn't realize it was possible / feasible to do it all ahead of time.

**Comment by zml2008** [comment]
Yeah, in PEX I basically cache all the data after the first lookup for a context combination, which makes everything afterwards pretty cheap.
