### ISSUE TITLE
Living is in Fire method?

### ISSUE THREAD

**Issue by nikosgram13** [SpongePowered/SpongeAPI#713]
Is there any way to check if a entity burned?

**Comment by simon816** [comment]
You say "burned", presumably that means you want to listen for when the entity dies. If so, you listen for the `EntityDeathEvent` and look at the cause of death. (Note: causes are being refactored, #712).

If the entity is alive and you want to check for whether it's burning, see whether the entity has [`IgniteableData`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulator/entity/IgniteableData.java) or [`FlamableData`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulator/entity/FlamableData.java)
There's also an event, [`EntityIgniteEvent`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/entity/EntityIgniteEvent.java) for when an entity is about to become ignited.

**Comment by nikosgram13** [comment]
This method is working.

```java
public void onPlayerChangeHealth(PlayerChangeHealthEvent event) {
	if (event.getCause().orNull() != null && event.getEntity().getData(FlamableData.class).orNull() != null) {
		event.setCancelled(true);
	}
}
```

But if a player hit him while burning, the Event will be canceled.

**Comment by simon816** [comment]
BTW `.orNull() != null` can be simplified to `.isPresent()`

> But if a player hit him while burning, the Event will be canceled.

That's exactly what your code is doing, so what's the problem?

Lets follow the code
1. if (event.getCause().orNull() != null)
    There is a cause of the player changing health
2. if (event.getEntity().getData(FlamableData.class).orNull() != null)
    The player (who's health just changed) is on fire
3. event.setCancelled(true);
    Cancel the changing of health

When a player gets hit, `PlayerChangeHealthEvent` is called. Therefore, a burning player will never change health when hit (or any other reason).

**Comment by ST-DDT** [comment]
I guess he wants to cancel fire damage, but he dont want to entity to stop burning.
Like an visual only effect.

**Comment by nikosgram13** [comment]
Exactly @ST-DDT. I want to use the Fire like an visual only effect.

**Comment by kenzierocks** [comment]
Then you probably want to just set the health change to nothing instead of
canceling.

**Comment by ST-DDT** [comment]
Dont guess.
He wants to know whether he should modify/cancel the passed event (`damageCause = entityburning`). Not how.
````
If damageCause = entityburning cancel event 
else do nothing.
````

**Comment by simon816** [comment]
OK I see. This looks like something that will be possible after the cause enhancements, #712, are added.
Here's some code
```java
public void onLivingDamage(LivingDamageEvent event) {
    Optional<DamageSource> optional = event.getCause().getFirst(DamageSource.class);
    if (optional.isPresent()) {
        if (optional.get().getDamageType() == DamageTypes.FIRE) {
            event.setCancelled(true);
        }
    }
}
```

**Comment by nikosgram13** [comment]
Ok, I will wait.. :smile:
