### ISSUE TITLE
LightningStrikeEvent Cancellable?

### ISSUE THREAD

**Issue by nikosgram13** [SpongePowered/SpongeAPI#715]
Is there any possibility of make the LightningStrikeEvent to can be cancelled?

**Comment by gabizou** [comment]
How would it be cancelable? The `Lightning` entity is already spawned and will strike. If you want to prevent the `Lightning` entity from spawning, by all means listen to `EntitySpawnEvent`, otherwise, I don't see what the aim is.

**Comment by nikosgram13** [comment]
Ok thanks :smile:
