### ISSUE TITLE
The Entities can be Categorized.

### ISSUE THREAD

**Issue by nikosgram13** [SpongePowered/SpongeAPI#716]
The Mojang separates the Entities in some categories. For example let's take the sheep which is classified in the category of Passive mobs.

We could create a method it could return the category classifies of the Entity.

Example:
```java
EntityTypes.SHEEP.getCategory(); //return the Passive category.
```
or
```java
entity.getType().getCategory();
```

Categories: http://minecraft.gamepedia.com/Mobs#List_of_mobs

**Comment by gratimax** [comment]
The categories that the Minecraft wiki describes are imposed based on behavior. That's okay, but it's definitely not how Mojang separates the entities (if you want to see how, take a peek into the hierarchy surrounding entities). We already _have_ categorizations based on types, so use instanceof.

**Comment by nikosgram13** [comment]
Ok, thanks :+1:
