### ISSUE TITLE
IntelliJ instructions incorrect

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#718]
> Search for the official Sponge API Maven artifact under Search by artifact, and click Add.

Doing this only results in Spongeapi:1.0 being displayed in the list, either the newer versions of spongeapi need to be added to the default repositories, or alternate instructions need to be added on this page, https://docs.spongepowered.org/en/plugin/basics/workspace/idea.html#gradle

**Comment by kenzierocks** [comment]
Isn't this a Docs issue?

**Comment by ryantheleach** [comment]
Yes, posted to the wrong issue tracker somehow. However doesn't it rely on re=publishing the API to fix if it's intended to be on the maven repo?

Moving to docs.
