### ISSUE TITLE
LICENCE.txt does not include a copyright

### ISSUE THREAD

**Issue by redxdev** [SpongePowered/SpongeAPI#720]
The MIT licence is somewhat nonsensical without a copyright line. Specifically, the following line in the MIT license makes no sense when there is no copyright in the document:

    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

The LICENSE.txt in this repository doesn't include a copyright line anywhere.

**Comment by kenzierocks** [comment]
If you look at the [code](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/Game.java) you'll notice there's an included copyright there.

**Comment by redxdev** [comment]
The code might, but the [license](https://github.com/SpongePowered/SpongeAPI/blob/master/LICENSE.txt) file makes no sense without the copyright line.

**Comment by modwizcode** [comment]
@Zidane opinion?

**Comment by Zidane** [comment]
I honestly see nothing wrong. Our license file shows our license and that header is in every file in SpongeAPI.

**Comment by Zidane** [comment]
Addressed in https://github.com/SpongePowered/SpongeAPI/commit/f913cf5296f95b0f9b3327f8198fe79e0e2c48a4
