### ISSUE TITLE
Texts#colorFromName(String) proposition

### ISSUE THREAD

**Issue by loganspeck** [SpongePowered/SpongeAPI#721]
I propose the following method be added to the class `org.spongepowered.api.text.Texts`:

`TextColor Texts#colorFromName(String name)` which will evaluate the provided `String` and return the corresponding `TextColor`. This will prove useful for serialization and deserialization of `TextColor`s. I would also suggest a `Texts#colorFromInt` but I believe the color codes are being phased out.

This method is something everyone will need and already are needing (myself). Instead of each plugin needing to create such a method(s) or creating more common libs, we should have it in `SpongeAPI`.

**Comment by zml2008** [comment]
Take a look at the gameregistry's getType method. This would look something like:
```java
@Inject private Game game;

public Optional<TextColor> getColor(String name) {
    return game.getRegistry().getType(TextColor.class, name.toUpperCase());
}
```
to get a TextColor by name.
