### ISSUE TITLE
Builders  Api  incoherent

### ISSUE THREAD

**Issue by Piratdu52** [SpongePowered/SpongeAPI#722]
When we construct a ParticuleEffectBuilder we must do this GameRegistery.getParticuleEffectBuilder(ParticleTypes.Type) for get the correct particle effect.
and when we want a Text we use myTextBuilder.builder("my String").

Why not unify this by making a Interface Builder for all existing builders ?

**Comment by MikaalSky** [comment]
Most things, like text, have Texts and such to allow for easy creation. Texts.of(<string>); pretty much slaps together a Text pretty quick.

**Comment by Piratdu52** [comment]
@MikaalSky  i don't understand why you say that. 

I ask for something like  EffectBuilder.builder(ParticleTypes.Type).build() insead of random scrap to unify creation of complex object through builders. Texts and ParticuleEffectBuilder are only an example of incoherence. And i think the best way to harmonize these is a common interface to all builders.

Why you say most things have a builder simplify creation ? To underline a difficulty to make it ?

**Comment by kenzierocks** [comment]
The only method you could put in an interface is `build`. I suppose it's doable, but it doesn't really help much.

**Comment by RafVDL** [comment]
If all builders would implement the `Builder` interface, all builders could be obtained using a method `gameRegistry.getBuilder(T builderClass)` (generic `<T extends Builder>`). The `GameRegistry` won't be full of `get*Builder()` methods.

**Comment by kenzierocks** [comment]
Sounds like that's doable with #717.

**Comment by Piratdu52** [comment]
Or maybe something like that new MyBuilder(GameRegister @nullable).builder(WhatTheBuilderNeed).build().

**Comment by modwizcode** [comment]
#717 will definitely cover this.
