### ISSUE TITLE
Direction Javadocs are contradictory

### ISSUE THREAD

**Issue by DDoS** [SpongePowered/SpongeAPI#726]
Example

Javadoc:

    <li>{@link #SOUTH} targeting towards +X</li>

Code:

    SOUTH(new Vector3d(0, 0, 1), Flag.CARDINAL)

**Comment by simon816** [comment]
There's a few mentions of incorrect Direction javadoc in the minor issues list
https://github.com/SpongePowered/SpongeAPI/issues/221#issuecomment-100763236
https://github.com/SpongePowered/SpongeAPI/issues/221#issuecomment-111585160
and also:
https://github.com/SpongePowered/SpongeAPI/issues/659
