### ISSUE TITLE
Add a way to show the Boss Bar to players

### ISSUE THREAD

**Issue by mcmonkey4eva** [SpongePowered/SpongeAPI#728]
In many servers, Boss Bar's are one of the 5 main ways to show data on-screen to players (Items, Action Bar, Scoreboards, Boss Bars, Titles). To not support even one of these is a tragedy.

Basically, it's a neat and fancy way of showing text at the top of the screen, as well as a nice progress bar (though the bar itself isn't guaranteed to function as expected in existing servers, mainly only the text matters).

How were these implemented in the past? https://bukkit.org/threads/tutorial-utilizing-the-boss-health-bar.158018/ or https://github.com/DenizenScript/Denizen-For-Bukkit/blob/master/src/main/java/net/aufdemrand/denizen/utilities/packets/BossHealthBar.java or a thousand other places.

What does it look like? Google it!
I mean, uh, here's a screenshot via google (It's the text at the top)
![Boss Bar](http://i.imgur.com/2Hqb744.png)

There's no way other than a boss bar to put text in that part of the screen. A boss bar is a must-have for any Minecraft API!

**Comment by Zidane** [comment]
Hmmm...

I had considered something like this before but due to my overwhelming TODO list it falls through closer to the bottom. I can also make the boss bar actually "work" too.

While I can't promise this will be done anytime soon (and I can't stress that part enough), I'll get around to it eventually.

**Comment by twizmwazin** [comment]
I've seen dozens of implementations of this in the Bukkit/Spigot ecosystem, although I have yet to see a fully functional open source implementation that is reliable.

**Comment by ryantheleach** [comment]
I'd hold off on this until at least the 1.9 snapshots being released, UI/Boss redesign was in the process and it may very soon be more difficult (or trivially easy) to manipulate multiple boss bars.

**Comment by gabizou** [comment]
> I'd hold off on this until at least the 1.9 snapshots being released, UI/Boss redesign is in the process and it may very soon be more difficult (or trivially easy) to manipulate multiple boss bars.

Considering 1.9 could be a long ways away, I don't see why we should hold back if the API is designed well enough to be able to handle the future changes from 1.9.

**Comment by AlphaModder** [comment]
For those who don't know, this is the image of the new boss bar features:
![Boss Bars](http://media.dinnerbone.com/uploads/2015-01/screenshots/19_14-32-30_OblsU19cfA.png)

**Comment by Aaron1011** [comment]
I think that the actual spawning of the boss entity (a Wither or EnderDragon) should be left up to plugins.

However, there should definitely be a way to spawn an entity on a single client. Showing a custom boss bar on Bukkit always required the use of NMS.

**Comment by ST-DDT** [comment]
So you would like to use some kind of Data Object/Manipulator you can offer to Entities?

How do you handle priorities?

How do you show different bars to different players close to each other? Can this be achieved by hiding the entity from the other player alone?

**Comment by ryantheleach** [comment]
I don't think the entity should exist in the world at all. Is it possible for them to "live" in a custom extent, or view?

**Comment by Aaron1011** [comment]
@ryantheleach: I'm not really sure what you mean. The only way to display a boss health bar to a client is to spawn in a boss mob.

While it might be possible to still represent the boss through the API, with an Extent or something else, I think a way to send an entity to one player specifically would be best. It eliminates the problem of having to deal with server-side logic acting on the entity.

**Comment by Zidane** [comment]
Do to a lengthy list of priorities and the fact that support for this will be far better in 1.9 AND the fact that many mods are holding out to update until 1.9...I'm going to push this issue off til then.

**Comment by kashike** [comment]
I'm going to work on this, since nobody else seems to have claimed it.

**Comment by kinggoesgaming** [comment]
@kashike stealing the nice bits for yourself aint ya? :wink:

**Comment by Zidane** [comment]
Closing as @kashike 's PR covers this.
