### ISSUE TITLE
Questions about FurnaceConsumeFuelEvent 

### ISSUE THREAD

**Issue by Piratdu52** [SpongePowered/SpongeAPI#731]
I try actually to implement FurnaceEvents, and I have so many questions...

So Firstly, what methods can modify an event (any event) and must affect the implementation ? Only setCancelled and setResult?

Secondly, FurnaceConsumeFuelEvent is an resultItemEvent. The result item is the burn item ?

Thirdly, FurnaceConsumeFuelEvent is not Cancelable. Why ? I know if I implement this, all cancelled consume fuel furnace will throw an FurnaceConsumeFuelEvent each tick, but it's can allow powerful stuff like allow only to use lava bucket as fuel if a diamond block is below the furnace.

**Comment by Piratdu52** [comment]
Fourthly, why not do an FurnaceCookingEvent ? It, will allow to speed up cooking or block cooking state.

**Comment by AlphaModder** [comment]
I feel like we should remove this event entirely and replace it with something like ItemDestroyEvent, with the furnace a reason for it's destruction.

**Comment by Piratdu52** [comment]
If you do this you will lost (or I don't understand something) a lot of information like block location and fuel remaining.

**Comment by AlphaModder** [comment]
@Piratdu52 If I pass the Furnace as the reason, surely you could get all that information from it?

**Comment by Piratdu52** [comment]
@AlphaModder Oh, this what I haven't understood... It's can work but a new user will have some difficulties to understand what event he must listen to listen... The FurnaceConsumeFuelEvent has the advantage of a clear name than it's functionality...

**Comment by Zidane** [comment]
New event framework changes this event entirely.
