### ISSUE TITLE
Sandboxing for plugins

### ISSUE THREAD

**Issue by Gaelan** [SpongePowered/SpongeAPI#732]
It would be awesome to have support for sandboxing of plugins. This would allow server admins to install plugins without worrying as much about vulnerabilites/backdoors. I was thinking that every plugin could have a list of rights, such as: Access Filesystem, Spawn Entities, Op Players. I think Java has the infrastructure necessary to do this (`SecurityManager`).

**Comment by kenzierocks** [comment]
One problem with SecurityManager is that Forge uses one. I'm not sure we can replace it.

**Comment by evilmidget38** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/master/fml/src/main/java/net/minecraftforge/fml/relauncher/FMLSecurityManager.java

**Comment by Gaelan** [comment]
In that case, we would need PR Forge to add support for sub-security manager delegation, I think.

**Comment by Deamon5550** [comment]
Really the only effect that sandboxing plugins will have is to create a false sense of security. It will always stand that you should **only** run plugins that you trust and that are from a reputable source. If you have sandboxing as an excuse for running any random plugin then sooner or later its going to bite you.

Better to not sandbox and encourage safe practices when selecting plugins to run.

**Comment by ST-DDT** [comment]
I agree with @Deamon5550 . Its far too easy to bypass any security measurements on plugin level. Either by infecting trusted plugins or other crazy stuff we can not imagine right now. (Example mixins)
The main issue is that some plugins might need elevated privileges and at some point you have to mark them as trusted to get them up and running to test them and at this point default users are asked "Plugin XY asks for elevated privileges. Bla Security Warning Open Port 22 Foo Bar Root Privileges Alter DNS Settings. Do you want to continue?"

After a while you can easily differentiate between "help offers" and real help the same way you do with e-mail spam. I usually decompile all plugins before i upload them to my server. (After decompiling i search for command executions, IO and OP) . But default plugin users cannot even understand the bad code if you show it to them, so this is no alternative.

The only thing we need is a platform where we can download safe plugins from. Something like Bukkit.

**Comment by Gaelan** [comment]
Really? Why don’t you think sandboxing works?

**Comment by twizmwazin** [comment]
@Gaelan No system is fool-proof. Malicious plugin developers will still attempt and successfully circumvent any security measure.

**Comment by sk89q** [comment]
Java has a huge ecosystem at runtime and it only takes someone discovering an unprotected class to bypass a sandbox. Instead, if you started with a Lua implementation that had no access to system resources, then sandboxing it is much easier because the only things available to Lua scripts are the things you personally provide.

Sun/Oracle hasn't had too much success preventing people from breaking out of their own sandbox given all the security problems that have occurred in the past with Java.

**Comment by Gaelan** [comment]
People will use plugins without auditing them no matter what. Requiring a Java 0-day (or unpatched Java) to do malicious stuff is better than making malicious stuff trivial.

**Comment by sk89q** [comment]
You can't just turn on a "sandbox" flag  -- you have to write a lot of your own code to do the sandbox which you have to maintain yourself.

**Comment by grum** [comment]
If you want to have sandboxing you cannot have reflection. Without reflection everything breaks (it shouldn't but it does).

**Comment by me4502** [comment]
IMO, reflection is way too important to remove.

**Comment by MattJohns** [comment]
Could you just enforce that no-one can do reflection except for the Sponge API?  After all if you want to go down the security / sandbox route, you don't want plugins doing reflection of any type really.
