### ISSUE TITLE
Add a way to simulate a player chatting

### ISSUE THREAD

**Issue by zml2008** [SpongePowered/SpongeAPI#733]
This would call the necessary events to take action as if a player had passed a given message to chat, throwing event & such (Would this work better with causes once those are added @gabizou)

This would add a method like:

``` java
/**
  * Simulate a player having chatted on the server. This will post the appropriate events, and handle commands as necessary
  *
  * @param input The input, as would be provided by this player
  * @return The event that has been thrown. Changes have no effect, this is simply to report back information
*/
PlayerChatEvent chat(String input); // Don't really think it makes sense to allow a Text here? dunno. Makes things more difficult for commands.
```

to `Player`

**Comment by FerusGrim** [comment]
Why wouldn't you have the method accept a Text? `PlayerChatEvent chat(Text input)`

After all, there's plenty of uses for it. I can see maybe having both of them, but that would break the standard that we currently have, of only accepting Text.

**Comment by ST-DDT** [comment]
@FerusGrim I guess because we want to be able to simulate what the player has entered in their chat window and that is just a String. Either a command in which case a `Text` is pretty useless or a chat message which then has to be check whether it is a legacy or json message.

However the method naming is bad. `chat()` sounds to much like chatting between players.

**Comment by FerusGrim** [comment]
@ST-DDT I suppose that makes sense. Though, I still believe it'd be a waste to not have the ability to bedazzle the message.

Maybe at least a `PlayerChatEvent#isSimulated`, so that plugins that use it can modify it afterwards?

**Comment by ST-DDT** [comment]
Is it possible for a player to send a real Json Message at all? If yes you can still convert the Text to a JSON String although this seems a little bit complicated.

Maybe just have two different input methods
* `simulateInput(String)` - Commands and Chat
* `simulateChat(Text)` - Chat only

But I have too few knowledge on the internals here whether this is even possible.

Regarding the `isSimulated()` method i am really not sure whether we should allow the plugin writers to treat messages differently whether its simulated or not.

**Comment by Zidane** [comment]
@zml2008 

Can you send a command as a CommandSource in SpongeAPI? If so, we already have support. Unless you want to make that easier to use.

**Comment by zml2008** [comment]
You can send a command, can't send chat though currently.

**Comment by Zidane** [comment]
@zml2008 

Though, you could send the command "say" with your message (or tellraw for something complex)

**Comment by zml2008** [comment]
Does that call events? I seem to remember it also using a different format for messages. 

Also, under that logic why do we have all this api when we have commands that can do the same things.

**Comment by Gaelan** [comment]
`/say` and normal chat *are* different:
`/say hi` --> `[SomeGuy47] hi`
`hi` --> `<SomeGuy47> hi`

**Comment by randombyte-developer** [comment]
@zml2008 Should be closed because it was added: https://github.com/SpongePowered/SpongeAPI/commit/e5a7785fd62359299580a321020165be37be8e47
