### ISSUE TITLE
Extent.getFullBlock() is a terrible method name

### ISSUE THREAD

**Issue by DDoS** [SpongePowered/SpongeAPI#736]
In Extent, we have:

    Location getFullBlock(Vector3i);
    Location getFullBlock(int, int, int);

These methods actually return a Location for the given position in the extent that was dereferenced. The Location can be used to do block related things, but since the merge with BlockLoc, it isn't exclusively used for that. This just makes the entire signatures weird and confusing. I suggest replacing them with:

    Location getLocation(Vector3i);
    Location getLocation(int, int, int);
    Location getLocation(Vector3d);
    Location getLocation(double, double, double);

These return a Location in the Extent, basically a pointer in 3D space. The integer variant work just like the old ones. The decimal ones can return sub-block locations, which BlockLoc didn't support, but Location does.

(Yes, I know I'm the one who added these methods in the first place, and I regret not thinking about them more thoroughly. :disappointed:)

**Comment by kashike** [comment]
:+1:

The existing method names are terrible.

**Comment by modwizcode** [comment]
:+1:
