### ISSUE TITLE
Add fine-grained block update/notify control

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/SpongeAPI#738]
**NOTE: This is about setting a block like sand, without an update to cause it to fall. Not about updating blocks on the client without changing the server**

Currently all `Block` (and `BlockSnapshot`) setting will perform a block update. Minecraft provides several levels of control in the flags used when setting blocks to control if the client should be notified and if the neighboring blocks should be notified. Plugins should have access to controlling these attributes when setting blocks.

The way I see this is just changing `Location`'s `setBlockType`, `setBlock` and `setBlockSnapshot` methods to have an extra version that accepts an enum representing the different flag configurations available for setting blocks. And modifying the corresponding `BlockVolume` methods to share the extra parameter.

**Comment by DDoS** [comment]
I suggest putting the extra method with the flags in Extent instead of BlockVolume, unless it is also applicable in a BlockBuffer. If it's only in a world, then it should not be in BlockVolume.

**Comment by modwizcode** [comment]
I feel it should be applicable in a BlockBuffer, unless a BlockBuffer is always used as a no update source.

**Comment by gabizou** [comment]
Another thing to consider is the use of `BlockState`s and `Location`, when offering new `DataManipulator`s to a `Location` is it going to always be updated and update the neighboring blocks?

**Comment by modwizcode** [comment]
@gabizou I really have no idea how to handle that, especially without modifying the Data API itself. It's not really defined in the API how that works as it is.

**Comment by gabizou** [comment]
> @gabizou I really have no idea how to handle that, especially without modifying the Data API itself. It's not really defined in the API how that works as it is.

As I said, one way to handle it is that any data transactions through `Location` are handled as "update neighbors and clients". Other methods from Extent/BlockVolume can use the `BlockState`s to further apply the flags.

**Comment by modwizcode** [comment]
Ah I see now that makes sense.

**Comment by Zidane** [comment]
Duplicates #619 

Please check open issues before making new ones @modwizcode ...

**Comment by modwizcode** [comment]
@Zidane I think you missed what this one was about, this about about block updates, like the `markBlockForUpdate(BlockPos)` interface that is currently not represented. This is critical for implementing worldedit, because some structures are built on triggered updates causing it to perform an action.

**Comment by gabizou** [comment]
@bloodmc Did you already add this to the API?

**Comment by bloodmc** [comment]
Fixed in https://github.com/SpongePowered/SpongeAPI/commit/947129f132f793615e346b19349e60b118f08865
