### ISSUE TITLE
SpongeAPI automated build not working

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeAPI#742]
This has happened in the past before, when the [API build](https://repo.spongepowered.org/maven/org/spongepowered/spongeapi/) does not reflect the current state of the GitHub repo. I noted this with the change of the Scheduler API. If you open the jar in an archiver, you will notice that all of the old classes are still there (AsynchronousScheduler, SynchronousScheduler, etc.) rather than the [new classes that have replaced them](https://github.com/SpongePowered/SpongeAPI/tree/master/src/main/java/org/spongepowered/api/service/scheduler). This has happened on more than one occasion in the past, at which times @progwml6 has fixed the issue. However, I am bringing this up again because it seems to be a recurring issue, and there should be something done to make the API build more stable. If you download the [full Sponge coremod build](https://repo.spongepowered.org/maven/org/spongepowered/sponge/) and open it in an archiver, you can see that the new classes are correctly compiled. It seems to be that the coremod builds are fine, but that the standalone API builds are not.

**Comment by progwml6** [comment]
The API should be cleaning before every build -- I will check the settings in the morning

**Comment by Zidane** [comment]
@progwml6 

Need a status update on this.

**Comment by progwml6** [comment]
Team city looks to be working properly

**Comment by ryantheleach** [comment]
Looking at the files in an archiver, the last time that 2.1-20150528.033129-93 was updated, was the 28th of may which matches the filename.

**Comment by progwml6** [comment]
Ignore the index page for the api use gradle/maven

I'm in the middle of rewriting part of how the indexer works with snapshots. It's tough as the libraries that are capable of gathering the needed metadata of info can be very tough to work with.
