### ISSUE TITLE
Add BookChangeEvent

### ISSUE THREAD

**Issue by mmonkey** [SpongePowered/SpongeAPI#743]
Just like SignChangeEvent.

**Comment by Guichaguri** [comment]
Are you talking about when a book gets signed?

**Comment by twizmwazin** [comment]
@Guichaguri I would think possibly after a book is edited before it is signed.

**Comment by mmonkey** [comment]
@Guichaguri @twizmwazin A BookChangeEvent would fire in both cases. There would probably be an isSigned() attribute.

**Comment by ST-DDT** [comment]
Maybe we should add a more generic event as well if any `DataManipulator` is applied or `DataHolder` is changed. Something like `DataChangeEvent`.

**Comment by gabizou** [comment]
Currently, #685 is adding a [`ValueChangeEvent`](https://github.com/SpongePowered/SpongeAPI/blob/feature/value-api/src/main/java/org/spongepowered/api/event/data/ValueChangeEvent.java#L29) which would solve this issue as you can type check for an `ItemStack` on the `getDataHolder` and as well type checking on the possible `Value`s for the [`getSuccessfulData()`](https://github.com/SpongePowered/SpongeAPI/blob/feature/value-api/src/main/java/org/spongepowered/api/data/DataTransactionResult.java#L96) will result in an understanding of what was added vs replaced/removed. In this case, it *is* possible we can further narrow down some events from this, such as `ItemStackValueChangeEvent` or something. The idea behind the event is that most base events, such as `EntityEvent` would extend `ValueChangeEvent`, if not `DataHolderEvent` and manually note the various events that are backed by value changes.

**Comment by JBYoshi** [comment]
Wouldn't a `BookSignedEvent` still be applicable?

**Comment by gabizou** [comment]
> Wouldn't a BookSignedEvent still be applicable?

It might not even be necessary at that point though since it is something REALLY specific.

**Comment by gabizou** [comment]
I believe that when a book is signed, the item changes entirely (since it not only changes NBT it also changes from the perspective of the `ItemType`, in which case, there is definitely an inventory event to be thrown. Closing as that is the ultimate solution.
