### ISSUE TITLE
Question: Add Data for Entity to SpawnEgg Item

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeAPI#749]
I have a question regarding the current data API.

I would like to create an `SpawnEgg` `ItemStack`.
It should spawn a black horse with armor and an armored Zombie as passenger.
Required data (assumption):
- `HorseData`
- `InventoryItemData`?
- `PassengerData`?
  - this references a `Entity` although it will only be spawned on use

I have found the `SpawnableData` but i can only set the `EntityType` (`HORSE`) there. Is there a way i can add the data manipulators for my entity to my `ItemStack`?

Is this feature/something like this supported by minecraft at all?
Or do I have to implement all myself

**Comment by ryantheleach** [comment]
It would be handy but it's yet another feature Sponge needs to support, and in the off chance that entity data might someday be native to spawneggs but in a different form I would be reluctant to see it in the API...

That said if I were to do this myself (assuming that custom data manipulators were done)  I'd probably attach either the data associated with mob spawner entities, EntityType type, @Nullable Collection<DataManipulator<?>> additionalProperties

Or the data associated with an "offline vehicle".

I'm really wondering if/how/can a given set of data can be saved under a different path/node using the Data API, as it seems like it could be useful in a lot of cases where you have very similar data in the same format being passed around, like a general Entity with extended properties like a passenger stack.

**Comment by ST-DDT** [comment]
> It would be handy but it's yet another feature Sponge needs to support, and in the off chance that entity data might someday be native to spawneggs but in a different form I would be reluctant to see it in the API...

Isnt this the main point of the Data API, to be independant from whatever change minecraft does to the internal data structure?

**Comment by Zidane** [comment]
This would need to be done via the plugin. All SpawnEggs know are the Entity(type) they will spawn. They have no knowledge of the data or the like.

Storing the data on the SpawnEgg (which SpawnableData would boil back to) would work but when spawning the SpawnEgg, Sponge would have to translate the data onto the Entity. This starts to get into uncomfortable territory where Sponge is concerned and sounds like a perfect niche plugin.
