### ISSUE TITLE
Have all services extend/implement a marker interface.

### ISSUE THREAD

**Issue by DotDashh** [SpongePowered/SpongeAPI#753]
How it'd work:

- If service has an interface, have that interface and only that interface extend the marker.
- If service doesn't have an interface, have the service class implement the marker.

Discuss below.

**Comment by Zidane** [comment]
@DotDashh 

As with any other issue, throw me a bone. What would be the usecase of having a master marker?

**Comment by zml2008** [comment]
yeah, I really don't think this is necessary -- the single thing that makes a service a service is that implementations of it are registered with the services manager. I can see you wanting to enumerate registered services, but requiring a specific superinterface doesn't really give much imo.

**Comment by Zidane** [comment]
@DotDashh 

Usecase? Otherwise, I would have to close this as I don't see any merit (yet).

**Comment by DotDashh** [comment]
Sorry for the late response. I had some hacky ideas in mind but those proved to be too error-prone.

Closing for now.
