### ISSUE TITLE
Discussion: Builder.reset() and from(X) everywhere or nowhere

### ISSUE THREAD

**Issue by ST-DDT** [SpongePowered/SpongeAPI#758]
While digging through the API I found lots of `Builder`s that have a `reset()` method but i also found a lot of `Builder`s that don't have such a method.
A few `Builder`s also provide a method `from(template)` which behaves quite similar while others have a method `getBuilderFrom(template)` to obtain a new templated builder.

**`Builder`s without `reset()`**
* org.spongepowered.api.effect.particle.ParticleEffectBuilder
* org.spongepowered.api.item.inventory.custom.CustomInventoryBuilder
* org.spongepowered.api.item.recipe.ShapedRecipeBuilder
* org.spongepowered.api.item.recipe.ShapelessRecipeBuilder
* org.spongepowered.api.util.command.CommandResult.Builder
* org.spongepowered.api.util.command.args.CommandFlags.Builder
* org.spongepowered.api.util.command.spec.CommandSpec.Builder
* ...

**`Builder`s with `reset()`**
* org.spongepowered.api.attribute.AttributeBuilder
* org.spongepowered.api.attribute.AttributeModifierBuilder
* org.spongepowered.api.data.ImmutableDataBuilder<H, E>
* org.spongepowered.api.item.FireworkEffectBuilder
* org.spongepowered.api.item.inventory.ItemStackBuilder
* org.spongepowered.api.item.merchant.TradeOfferBuilder
* org.spongepowered.api.potion.PotionEffectBuilder
* org.spongepowered.api.world.gen.populator.*.Builder
* ...

There should be a common decision for our entire project whether our builders should have a `reset()` method or not. 
The same for `from(template)` methods.
Is there a common practise or coding guideline?

Pro `reset()`/`from(tempalte)`
* Do not have to leak an entire service or the `GameRegistry` to a method where only a `Builder` is needed more than once.
* Lesser object creation and thus less garbage collection.

Cons:
* ?

**Comment by zml2008** [comment]
Yeah, I'm in favor of removing all these methods -- they're not really in line with how builders are typically used.

**Comment by DDoS** [comment]
Please don't change the BlockRay builder, it was designed with a different syntax to make it as short as possible. `BlockRay.from()` needs to stay.

**Comment by gabizou** [comment]
This was partially resolved with the addition of [`ResettableBuilder`](https://github.com/SpongePowered/SpongeAPI/commit/2a7c654fa599b3734e32e873e90dacb5fbeaf630), granted this has been modified over the proceeding commits to improve usability.

The `from` methods are all subjective for each builder such that it's not really within the realm of each builder to explicitly be able to accept the types of objects they build.

**Comment by gabizou** [comment]
This will require another extensive change of `ResettableBuilder` to be more generic.

**Comment by gabizou** [comment]
Resolving the remaining issue in #960.
