### ISSUE TITLE
VanishAPI & variants

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#760]
It's clear from looking at popular forks of the Minecraft code base that large servers will want various ways of manipulating the ways that entities interact with each other and the world.
- [x] Can an entity can be seen from a given players perspective.
   - https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulator/entity/InvisibilityData.java
- [x] Can an entity target another entity (AI)
   - https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulator/entity/TargetLivingData.java
- [x] Can an entity collide with another entity.
   - Touchy due to performance reasons. Probably shouldn't be an event?.
     Should it just default to whether an entity can see the entity?
   - https://github.com/SpongePowered/SpongeAPI/blob/411037993587ae6f46a875198efe13c766b745a0/src/main/java/org/spongepowered/api/event/entity/EntityCollisionWithEntityEvent.java
- [ ]  Can a block be placed in the space that an entity is occupying?
   - Should this also default to whether the entity can be seen by the player?
   - Should we even expose this otherwise?
   - Sub-class of https://github.com/SpongePowered/SpongeAPI/blob/411037993587ae6f46a875198efe13c766b745a0/src/main/java/org/spongepowered/api/event/entity/EntityCollisionWithBlockEvent.java ?
- [x] Can projectiles collide with a given entity?
   - (slightly harder, would this depend on whether the shooter can see the entity collided with? or should this be a new data manipulator / event)
   - Sub-Class of https://github.com/SpongePowered/SpongeAPI/blob/411037993587ae6f46a875198efe13c766b745a0/src/main/java/org/spongepowered/api/event/entity/EntityCollisionWithEntityEvent.java
- [ ] Whether a player effects spawning calculations for "naturally" spawning mobs, mob spawners.
   - Could easily be done with a new Data Manipulator. Should it distinguish between natural or mob spawners?
- [ ] Can a player affect the sleep calculation.
   - Could easily be done with a new Data Manipulator.

**Comment by gabizou** [comment]
This has been something I've poked @mbaxter about writing after #685 is merged.

**Comment by ryantheleach** [comment]
I was thinking of working on some implementation, but figured I'd make an issue about the API first in order to try to gauge what would be needed/wanted

**Comment by JBYoshi** [comment]
> Can an entity collide with another entity.
    Touchy due to performance reasons. Probably shouldn't be an event?. Should it just default to whether an entity can see the entity?

I would probably keep the event. Plugins might want to know when two entities collide.

> Can a block be placed in the space that an entity is occupying?

I would say to just make `BlockPlaceEvent` default to cancelled if the player is trying to place a block inside an entity.

> Can projectiles collide with a given entity?

I'd probably do a subclass of `EntityCollideWithEntityEvent`.

> Can a player affect the sleep calculation.

Already taken care of by #735.

**Comment by ryantheleach** [comment]
> I would say to just make BlockPlaceEvent default to cancelled if the player is trying to place a block inside an entity.

But then how do you get the entity that the block is in conflict with?

**Comment by JBYoshi** [comment]
...Oh. Whoops.

**Comment by Xemiru** [comment]
Could use causes and link to the conflicting entity.

**Comment by TheRaspPie** [comment]
bloodmc wanted to add `Result`s to Sponge like the one Bukkit had in `Event.Result`. Maybe BlockPlaceEvent would be a use case for this? @bloodmc

**Comment by wizjany** [comment]
Yea, force-allowing behavior like this is one of the things that a tri-state Result will be useful for. 

Also while I'm here, I'd like to note that 1.9 is adding team-based collision (scoreboard) rules.

**Comment by gabizou** [comment]
To summarize, all of this issue has been resolved, except the bother of whether Players are considered for sleep and nearby mob spawning. AI can already be tricked to not track the player, and collision detection has already been written in.

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/SpongeAPI/pull/735 and https://github.com/SpongePowered/SpongeCommon/pull/2581
