### ISSUE TITLE
Combining two or more Texts in a message

### ISSUE THREAD

**Issue by intronate67** [SpongePowered/SpongeAPI#764]
When sending players messages in game whether its p.sendMessage(Text) or through MessageSink and sending it to the whole server if you want to send two or more Texts you have set as variables you cannot add them together like ```p.sendMessage(text1 + text2)``` I think this should be implemented because the other way to add them is add them together into one text variable by doing 
**Current Way**
```java
Text text = Texts.builder("Hello World").build();
public void foobar(Player p){
    Text text2 = Texts.builder(text).append(Texts.builder("Hello World").build()).build();
    p.sendMessage(text2);
}
```

**Improved Way**
```java
Text text = Texts.builder("Hello World").build();
public void foobar(Player p){
    Text text2 = Texts.builder(" Test").build();
    p.sendMessage(text + text2);
}
```
I think this could help with readability and also help some developers who are transferring from CraftBukkit. Now obviously in this implementation it looks useless since the code is so short but in bigger messages like this one im using in my Bounty Plugin, it could be simplified to look a lot cleaner.
```java
Text text = Texts.builder().append(prefix).append(Texts.builder("Available Bounties: ").color(TextColors.AQUA).build()).build();
p.sendMessage(text);
Iterator iterator = BountyUtil.getUtil().availBounty.entrySet().iterator();
while (iterator.hasNext()) {
    Map.Entry pair = (Map.Entry)iterator.next();
    Text entries = Texts.builder().append(prefix)
    .append(Texts.builder(String.valueOf(pair.getKey() + " for $")).color(TextColors.AQUA).build())
    .append(Texts.builder(String.valueOf(pair.getValue())).build())
    .build();
    p.sendMessage(entries);
    iterator.remove(); // avoids a ConcurrentModificationException
}
```

**Comment by kenzierocks** [comment]
Your improved way will never compile with regular `javac`, there's no operator overloading.

**Comment by gratimax** [comment]
There are methods to make your life easier:

```java
Text text = Texts.of(prefix, TextColors.AQUA, "Available Bounties: ");
p.sendMessage(text);
Iterator iterator = BountyUtil.getUtil().availBounty.entrySet().iterator();
while (iterator.hasNext()) {
    Map.Entry pair = (Map.Entry)iterator.next();
    Text entries = Texts.of(
        prefix, 
        TextColors.AQUA, String.valueOf(pair.getKey()), " for $", 
        TextColors.WHITE, String.valueOf(pair.getValue()));
    p.sendMessage(entries);
    iterator.remove(); // avoids a ConcurrentModificationException
}
```

Please read the [documentation](https://docs.spongepowered.org/en/plugin/basics/text/text.html) to learn more.

**Comment by intronate67** [comment]
@kenzierocks My improved way was not meant to be able to compile it was a model for how i would like the Text API to be changed to make it easier. But now that gratimax showed me the methods its easy enought.

**Comment by ST-DDT** [comment]
@intronate67 There are also generics in java which also makes your life easier.

````java
Iterator<Map.Entry<String,Integer>> iterator = BountyUtil.getUtil().availBounty.entrySet().iterator(); 
while (iterator.hasNext()) { 
Map.Entry<String,Integer> pair = iterator.next();
````

Your combine method already exists.

````java
Text prefix = ...;
Text message = ...;
Text fullMessage = Texts.of( prefix, message);
````
