### ISSUE TITLE
BulkBlockEvent's getBlocks() method should either return some form of blocks or be renamed

### ISSUE THREAD

**Issue by SonarBeserk** [SpongePowered/SpongeAPI#767]
The current method name is misleading as it returns locations not direct block states. This is poor naming practice.

**Comment by kashike** [comment]
related: https://github.com/SpongePowered/SpongeAPI/issues/736

**Comment by ryantheleach** [comment]
BlockStates would be the incorrect type, it would more likely be BlockSnapshot or location.

**Comment by Zidane** [comment]
@SonarBeserk 

This will be covered or adjusted in the event refactor branch.
