### ISSUE TITLE
Clarify when events are fired

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#769]
Currently, there's not much (or any) documentation about which API methods might trigger an event being fired.

It should be made clear that API methods usually don't cause an event to be fired. Methods which do fire events should clearly state it in their javadocs.

**Comment by DDoS** [comment]
We could maybe have an annotation for that.

**Comment by ST-DDT** [comment]
@DDoS Why would you use an annotation for that? And what would be included in such an annotation?
IMO Javadocs are the perfect place for such information, because you can also add some comments describing in which order or at what time exactly the events are executed and what might happen if the event is cancelled.

**Comment by DDoS** [comment]
Annotations can be useful in may ways. They're more visible than javadocs and the information can be extracted and used by annotation processors at compile-time or at run-time (if they're retained).

If you're looking at indicating if a method fire an events then `@Fires(ChunkLoadEvent.class, ChunkPreGenerateEvent.class, ChunkPostGenerateEvent.class)` would work.

Also if the events change (deleted or renamed) then the code will break so the information has to be kept up-to-date.

**Comment by Zidane** [comment]
We won't do an annotation...we'll just make it so that any method that triggers an event takes a Cause object.

**Comment by Aaron1011** [comment]
@Zidane's solution work's well. Since `Event` now always has a `Cause`, any method that does not take ` Cause` should not be firing an event.

**Comment by simon816** [comment]
including `ServiceManager#setProvider`? it fires a `ChangeServiceProviderEvent` but I see no reason for a cause to be provided there (many other methods would need to be changed too)

**Comment by Zidane** [comment]
overloaded methods can be added then...but the Plugin firing it should ALWAYS be in the cause...period.
