### ISSUE TITLE
Add InventoryChangeEvent

### ISSUE THREAD

**Issue by Xemiru** [SpongePowered/SpongeAPI#774]
_enhancement_

With the events we have now, tracking if a player has attained a certain item would mean registering for all events that can relate to the aforementioned player's inventory having its contents modified. An `InventoryChangeEvent` would remove the need for the former, sizing it down to only checking one event for any change in inventory items.

_*Use Cases*_

* Minigames that depend on a player attaining a given item.
* An item banning plugin that prevents a given item from ever being obtained by a player.

**Comment by Zidane** [comment]
This changes with the new event framework. Everything is causes now.
