### ISSUE TITLE
Text builder coloring colors wrong text

### ISSUE THREAD

**Issue by premiumdeluxe** [SpongePowered/SpongeAPI#781]
So i made a /message command with different colors. I colored a part of the message and then appended other text to it with a different color. Then I appended another bit of text but i didn't color it. It colored the non-colored text to the first color.

This is the snippet of code:
![screenshot 2015-07-26 21 53 40](https://cloud.githubusercontent.com/assets/11151624/8897782/efc04460-33e0-11e5-9301-759f6b6bf0fe.png)

This is the resulting message:
![screenshot 2015-07-26 21 49 45](https://cloud.githubusercontent.com/assets/11151624/8897786/f4c08826-33e0-11e5-96c6-2f72e68f7279.png)

I know how to work around this but is it supposed to be like that? If not I just wanted to bring it up so it could be fixed.

**Comment by ST-DDT** [comment]
Its actually working as expected.

Because you appended the message inside the colored one.

The following works as you want it to:
````java
Text.builder("From ").color(GRAY)
append(Text.builder(playername).color(BLUE).build())
append(Text.builder(": ").build())
append(Text.builder(message).build())
.build()
````

PS: Please do not post images of code. Use pastebin or code tags. For short pieces of code like your you can also insert it plain.

**Comment by zml2008** [comment]
yeah, the Text API is designed to work in a non-linear manner, meaning each Text instance has attributes set on it that apply to the whole value, and are inherited by any children without overridden values.
