### ISSUE TITLE
ChangeClientSettingsEvent

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#786]
An event when `C15PacketClientSettings` is received would be helpful, before any existing data (such as locale) is changed - http://wiki.vg/Protocol#Client_Settings

**Comment by Zidane** [comment]
@kashike 

Post an example plugin for the usecase.

**Comment by kashike** [comment]
A few examples:
- storing the value in a database
- sending a message/link to the player when they change their locale
- giving the player an item

**Comment by Zidane** [comment]
I need to see an example plugin.

**Comment by kashike** [comment]
After talking with @Zidane, I've modified this issue a bit.

**Comment by gabizou** [comment]
Closing as it's handled in #933.
