### ISSUE TITLE
Generify Location's Extent

### ISSUE THREAD

**Issue by DDoS** [SpongePowered/SpongeAPI#788]
Location should have type `Location<T extends Extent>`. This would allow `T getExtent()` to return a concrete type, such as World. This would fix the common case of `(World) object.getLocation().getExtent()`. Currently it returns Extent which isn't all that useful.

**Comment by zml2008** [comment]
This seems pretty useful -- probably wouldn't have to increase verbosity much in most places too.

**Comment by DDoS** [comment]
I think the verbosity saved from casts and `instanceof` checks would compensate for the slightly longer type name.

**Comment by DDoS** [comment]
[Here](https://github.com/SpongePowered/SpongeAPI/commit/02473cb31fac)'s what the API looks like with generic locations.

@SpongePowered/developers Yes or no? Should we just replace Extent by World in Location, since that seems to be the most used type by far?

**Comment by kashike** [comment]
This seems pretty helpful, I think it is worth the verbosity?

**Comment by zml2008** [comment]
yeah, I think generifying Location is probably the best way to go. Would be great for stuff to use Extent wherever possible too, rather than World, so that we can do things like what WE does with treegen on bukkit -- sticking an Extent in between that allows capturing changes occurring.

**Comment by DDoS** [comment]
Well currently Extent is way too big of an interface to actually be useful, but that's another issue.

**Comment by DDoS** [comment]
Closing this, follow in the PR.
