### ISSUE TITLE
Support replaceable service providers

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#790]
The `ServiceManager` javadocs make numerous references to replaceable service providers, however, there's no way to actually specify this. The default `SimpleServiceManager` just treats all registered providers as unreplaceable.

Unless there's any reason for a service provider to be able to dynamically determine whether it's replaceable, the replaceability could simply be specified as a boolean parameter.

**Comment by gabizou** [comment]
Or perhaps through annotation?

**Comment by gabizou** [comment]
That way the SpongeAPI dependent service providers could be irreplaceable?

**Comment by ST-DDT** [comment]
> SpongeAPI dependent

So you bring up dependencies but limit this to sponge. Why are other impls/plugins not allowed to depend on some specific registered services?

**Comment by JBYoshi** [comment]
I would probably use a separate method to register it (e.g. `setProviderReplaceable()`).

**Comment by ryantheleach** [comment]
What happens if someone wants to split the events / commands into universes like perWorldPlugins used to do on bukkit? Letting the event service / command service be replaced by a decorating service would go a long way towards supporting those type of plugins.

I could also see it being useful for a way to apply cooldowns to commands without having the pre command event chain.

**Comment by Zidane** [comment]
I agree, @zml2008 I want this functionality but all SpongeAPI provided services implementations are irreplaceable. All plugin added ones are replaceable.

**Comment by Aaron1011** [comment]
@Zidane: Not all Sponge services are irreplaceable. The Sponge-provided `PermisisonService` *has* to be replaced to have a useful permissions service.

**Comment by Zidane** [comment]
@Aaron1011 

Then make it conditional. Use common sense...the Commands and Scheduler services cannot be replaced.

**Comment by gabizou** [comment]
Ok, so here's my take on this, the irreplaceable services will no longer be services as provided by the `ServiceManager`, but rather something accessible either form the `GameRegistry` or the `Game` itself. This would fall in line with a few other services that have been implemented and heavily relied on throughout the implementation. Thoughts?

**Comment by kashike** [comment]
That makes sense.

**Comment by ST-DDT** [comment]
@gabizou How can we decide which services are irreplaceable for an implementation?
Sponge might have other fixed services  then custom impls.

**Comment by Zidane** [comment]
@ST-DDT 

Services are provided by plugins. We bend this rule and provide Permissions OOBE due to Minecraft having a very basic permissions system as well as Economy due to sheer demand. Otherwise, they are for adding NEW features to the existing API, not replacing them. It is due to this concept that the Scheduler and Serialization were never meant to be services and will be addressed very soon.

**Comment by simon816** [comment]
I think all that's needed is to add a boolean parameter to `setProvider` called `replaceable`.

Also, related to services, I think it would be useful to return the previous service implementation if you're replacing an existing one. That way you can wrap services so you don't have to provide a complete and full solution to a service. For example the `UserStorageService` is what creates `User` objects, so a plugin implemented version will need to implement the entire User interface which is not a reasonable thing to expect. If they wrapped the Sponge service and just changed the bits they need it would be much better.

**Comment by gabizou** [comment]
@simon816 The latest API changes I made cemented that all services are replaceable. Changes are required to make services replaceable. Ideally, services that are registered should be configurable so that server admins can pick and choose which plugin's service is the "winner".

**Comment by Aaron1011** [comment]
Superceded by https://github.com/SpongePowered/SpongeAPI/issues/949
