### ISSUE TITLE
Obtain world "container" File

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#791]
An API method to obtain the `File` of the world "container" (server.properties `level-name` field for vanilla) would be helpful, since there is not currently a way to get it easily. It would return the (going by vanilla defaults) `world/` directory as a `File`.

`+zml | kashike: ok, talk to modwizcode|away about where that fits in best`
@modwizcode

**Comment by KieronWiltshire** [comment]
This is definitely something that needs to be added. My world-backup plugin heavily depends on it.

This is the way we currently do it:
https://github.com/Dracade/Ember/blob/master/src/com/dracade/ember/system/Backup.java#L61-L73

Also, doing:
```Java
String level = game.getServer().getWorlds().get(0).getName();
```
seems like a terrible way to do it.

**Comment by kashike** [comment]
@KieronWiltshire The snippet you have there does not get the `File` anyways, just a world name.

**Comment by KieronWiltshire** [comment]
Yeah I know

**Comment by simon816** [comment]
Accessing raw world data is a bad idea. Also, it's possible that some SpongeAPI implementation doesn't use the file system for world storage. Perhaps #751 could cover the things you need.

**Comment by kashike** [comment]
@simon816 Nobody said anything about accessing world data, we're talking about getting the directory that worlds are stored (in vanilla's case, the primary level). An implementation can return `Optional.absent()`, then.  #751 does not cover getting the `File` of the world container.

**Comment by modwizcode** [comment]
Originally it did till I removed it (or rather @FerusGrim did and I merged
into the PR.).

**Comment by kashike** [comment]
@modwizcode Any chance of it being re-added? :pray:

**Comment by modwizcode** [comment]
Sure. @Zidane gave me a tentative confirmation that exposing a file could
be allowed. I'd appreciate a more official confirmation before adding it
back to the PR.
