### ISSUE TITLE
Add ItemStack#getName()

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeAPI#792]
Add a way to get the name of an ItemStack.

I know there is a way to get the name of an ItemType, but what if I want to get name of "Dark oak wood planks", using the itemtype.getName() I would get "Oak wood planks".

**Comment by simon816** [comment]
There's `DisplayNameData`, is that what you're looking for?
`stack.getData(DisplayNameData.class)`

**Comment by JBYoshi** [comment]
No, this is for when there's no display name.

**Comment by Bammerbom** [comment]
That are only custom names right?

**Comment by JBYoshi** [comment]
Right. `DisplayNameData` is only for custom names.

**Comment by ST-DDT** [comment]
Do you need that info as a `String` as a `Text` as a serializable type reference?

In case you need it as a `Text`:

Are you trying to achieve something like [this](https://github.com/SpongePowered/SpongeCommon/pull/108/files#diff-c9d7cd27f2737b8ce29169fd34062682R116)?
(`itemtype.getTranslation()`)

That is part of [my PR](https://github.com/SpongePowered/SpongeAPI/pull/779) for `Texts.format(Text, Object...)`
Which adds an interface `TextRepresentable` that adds a `toText()` method. (To `ItemStack`s for example)

**Comment by Bammerbom** [comment]
Still is getItem().getTranslation() used, which means it is the name of the item TYPE.
Which means when I am holding dark oak wood planks, it still returns "Oak Wood Planks".

**Comment by ST-DDT** [comment]
I'll add that along with my `Texts.format(...)` PR. https://github.com/SpongePowered/SpongeAPI/pull/779

`ItemStack` is `Translateable`:
https://github.com/SpongePowered/SpongeAPI/pull/779/files#diff-4c2479ff4e36671c9caf62d8c72b0c6aR42

Implementation:
https://github.com/SpongePowered/SpongeCommon/pull/108/files#diff-c9d7cd27f2737b8ce29169fd34062682R119

Looks like this when obfuscated:
````java
return new SpongeTranslation(func_77973_b().func_77667_c((ItemStack)this) + ".name");
````

**Comment by ST-DDT** [comment]
This is fixed now. PR #779 has been merged.
`ItemStack.getTranslation()`
