### ISSUE TITLE
"CommandContext" args/callables

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#794]
As seen in [WorldEdit](https://github.com/sk89q/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/minecraft/util/commands/CommandContext.java) and [Intake](https://github.com/sk89q/Intake/blob/master/intake/src/main/java/com/sk89q/intake/argument/CommandContext.java#L223-L349), there's a nice class for working with command arguments. The Sponge API currently contains the [`CommandArgs`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/command/args/CommandArgs.java) class, which is a stack-based approach at this (see [Intake](https://github.com/sk89q/Intake/blob/master/intake/src/main/java/com/sk89q/intake/argument/ContextArgs.java)), where as this is an "index" based approach.
It'd be nice to have a similar class in the sponge api, as a class constructable by anyone in their command, and optionally an abstract class (implementing [`CommandCallable`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/command/CommandCallable.java) with an abstract method for dealing with the "CommandContext" instead of the raw `String`.)

@zml2008

**Comment by windy1** [comment]
@kashike Can this be closed?
