### ISSUE TITLE
Add a way to get the TPS

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeAPI#795]
Add a way to get the TPS (Ticks Per Second) of the server.

Server#getTPS()?

**Comment by modwizcode** [comment]
Can't you just use the scheduler to call a 1-tick interval repeating task and measure the difference between System.nanoTime() calls, multiply by 20 to get the number of ticks per second? For more accuracy use a longer interval like 20 ticks between updates and multiply by (20/number of ticks per interval). Shouldn't be too hard. It would be easy to add, but there are multiple ways to do this already at varying precisions and accuracies.

**Comment by Bammerbom** [comment]
I know it is possible on such a way, but I think it is better to add the method to the api.
It's an api and I think such methods should be in the api instead of every plugin having to make their own task etc.

**Comment by modwizcode** [comment]
Except the number can mean a lot of different things.

**Comment by progwml6** [comment]
Tps of the server or per world?

**Comment by JBYoshi** [comment]
@progwml6 They're the same. There's only one server thread, and each world gets one tick for each server tick.
