### ISSUE TITLE
Add api for interacting with bounding boxes

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#797]
It would be more than nice if we could access and do at least basic operations with entity aabb.
in forge we can simple use methods 
net.minecraft.world.World#getCollidingBoundingBoxes(Entity,AxisAlignedBB )
net.minecraft.world.World#findNearestEntityWithinAABB(Class , AxisAlignedBB, Entity)
net.minecraft.world.World#getEntitiesWithinAABB(Class,AxisAlignedBB)
but we can't do that with spongeapi, this can lead to ugly workarounds

- For now its impossible or at least very expensive to find
    - Player's targeted entity 
    - Nearby/Nearest entities around another

**Comment by zml2008** [comment]
Yeah, this would be super useful for working with entities.

**Comment by joshgarde** [comment]
It'd make porting over certain plugins from Bukkit easier.

**Comment by DDoS** [comment]
Forgot to close this when I merged the feature/aabb branch.
