### ISSUE TITLE
Provide dependencies provided by Minecraft in the API

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#798]
The API only provides [a small section](https://github.com/SpongePowered/SpongeAPI/blob/master/build.gradle#L20) of dependencies that are [provided by Minecraft](https://gist.github.com/kashike/0e40693ca200db04c187), requiring developers to specify the dependency manually.

**Comment by zml2008** [comment]
Keep in mind as well that not all client-side dependencies are used by the server, so that list would have to be verified against classes shaded into the server jar.

**Comment by kashike** [comment]
@zml2008 I probably should have been more specific - I don't mean to shade **all** dependencies, just ones that are commonly used: `commons-io`, `commons-codec`, `trove4j` are the ones that I see used often.

**Comment by simon816** [comment]
The API is not bound to vanilla's dependencies so it shouldn't be assumed that they should be available on all implementations.

**Comment by Techcable** [comment]
@simon816 
Custom ClassLoaders :)

**Comment by Minecrell** [comment]
We already provide the most important dependencies for plugin authors provided by Minecraft. As @simon816 already said, all additional dependencies that are actually not used by the API itself need to be present in all implementations; custom implementations will most likely not bundle the same dependencies as Minecraft. We should try to keep the amount of additional dependencies in SpongeAPI at minimum.

Regarding `commons-io`, `commons-codec` and `trove4j`: 
- `trove4j` was removed from Minecraft in 1.8.3
- `commons-io` and `commons-codec` have either quite small JAR sizes compared to the already included ones (so it's not a big deal to shade these in the plugin JAR if someone really needs them) and/or provide features that are already mostly available with the current dependencies.
