### ISSUE TITLE
PlayerJoinEvent: blank NewMessage gets sent anyway

### ISSUE THREAD

**Issue by Phroa** [SpongePowered/SpongeAPI#800]
```java
PlayerJoinEvent::setNewMessage(Texts.of(""))
```
sends a blank string in place of the message rather than removing the message completely. I feel that this should either be its behaviour, or the method should accept `null` to suppress the join message, if having `Texts.of("")` supported is important.

**Comment by simon816** [comment]
If anything, `null` would be better than empty string.
Unless I misunderstand `MessageSink`s, I believe you can set a sink with `event.setSink` to make the event broadcast nowhere.

**Comment by Zidane** [comment]
This has been changed with the new events framework.
