### ISSUE TITLE
Use Transform instead of Location

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#802]
In events like [`PlayerRespawnEvent`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/entity/player/PlayerRespawnEvent.java#L59), a [`Location`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/Location.java) can be set, but only the position is set in most cases:
- [MixinServerConfigurationManager#L311](https://github.com/SpongePowered/SpongeCommon/blob/47465e56f35d84f1832dd3eeca917ed52ed15e8d/src/main/java/org/spongepowered/common/mixin/core/server/MixinServerConfigurationManager.java#L311)
- [MixinEntity#L232](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/MixinEntity.java#L232)

conversation: https://korobi.io/network/esper/channel/spongedev/logs/2015/08/12/#L421-L488

**Comment by DDoS** [comment]
Should be fixed in https://github.com/SpongePowered/SpongeAPI/commit/635d3815295e0ca096701aff54b9d40b4c020c43, once the branch gets merged into master. If I missed anything tell me.

**Comment by kashike** [comment]
@wizjany
