### ISSUE TITLE
Missing convenience entity data methods

### ISSUE THREAD

**Issue by caseif** [SpongePowered/SpongeAPI#803]
While looking through Data 2.0, I noticed a few entity classes were missing data methods (convenience methods like `getHealthData`) which they should contain. The list is below.

- [`Ageable`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/Ageable.java)
    - `getBreedableData`
- [`Arrow`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/projectile/Arrow.java)
    - `getKnockbackData`
- [`ExperienceOrb`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/ExperienceOrb.java)
    - `getExperienceHolderData`
- [`Horse`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/animal/Horse.java)
    - `getSaddleData`
- [`ItemFrame`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/hanging/ItemFrame.java)
    - `getRotationalData`
- [`Pig`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/animal/Pig.java)
    - `getSaddleData`
- [`Player`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/player/Player.java)
    - `getFoodData` (this may belong in `Human`; I'm not entirely sure)
- [`Sheep`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/animal/Sheep.java)
    - `getDyeableData`
- [`ThrownPotion`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/projectile/ThrownPotion.java)
    - `getPotionEffectData`
- [`Wolf`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/animal/Wolf.java)
    - `DyeableData`
- [`ZombiePigman`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/monster/ZombiePigman.java)
    - `getAngerableData`

I'd be eager to create a pull request for these changes, but I'd like to first assert that they're valid concerns and allow for a discussion before starting work.

**Comment by gabizou** [comment]
A lot of these aren't guaranteed to exist from the get go. If an entity has the likely capability of having these data, that isn't 100% true all the time, in which case, they are not included in the interfaces themselves. Besides, the whole point of Data API is that you don't have to rely on the various entity interfaces to deal with the data. You just query with `entity.get(DyeableData.class)` and if the optional is present, well, you can manipulate it.

**Comment by gabizou** [comment]
> ItemFrame
> getRotationalData



> Player
> getFoodData (this may belong in Human; I'm not entirely sure)



> ThrownPotion
> getPotionEffectData



> Sheep
> getDyeableData

These I can see being added, but the rest, they're still optionally available.

**Comment by caseif** [comment]
Could you please clarify in regard to `ExperienceOrb`/`ExperienceHolderData` and `ZombiePigman`/`AngerableData`? To my understanding, experience orbs should always contain a value for experience (even if 0), and zombie pigmen should always have an anger level.

**Comment by gabizou** [comment]
`ExperienceHolderData` doesn't apply because it doesn't have the notion of "level"s. It only contains a value of the total experience it holds, so quite possibly, I'll be adding another `DataManipulator` and/or `Key` for an `ExperienceStoredData` or something. All of these changes are being bundled in [feature/data](https://github.com/SpongePowered/SpongeAPI/tree/feature/data) branch currently. With regards to `ZombiePigmen`, I meant to include them.

**Comment by caseif** [comment]
Fair enough. Am I clear to start a PR?

**Comment by gabizou** [comment]
As I said before, these sort of changes are going to be bundled in [feature/data](https://github.com/SpongePowered/SpongeAPI/tree/feature/data).

**Comment by gabizou** [comment]
Actually, @caseif, `ItemFrame`s, when they have no `ItemStack`, they have no `RotationalData` to associate themselves with. So, that's not going to be an "accessor" in this case. 

As with `ThrownPotion`, the thing is that the `Projectile` doesn't actually store the potion effects, but rather the `ItemStack` that is in the `RepresentedItemData` manages the potion effects being applied and rendered. 

`Sheep`s already have [`getDyeData()`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/animal/Sheep.java#L40), so no changes needed.

I've added the following:
`Human#getFoodData()`,
`ZombiePigman#getAngerableData()`
`Arrow#getKnockbackData()`,
`ExperienceOrb#getExpOrbData()`

The rest are not applicable, or not guaranteed to exist at all times.

**Comment by ryantheleach** [comment]
>RotationalData to associate themselves with. So, that's not going to be an "accessor" in this case.

Testing in 1.8.8 that doesn't appear to be the case. punching and replacing an item in an itemframe keeps it's orientation.

**Comment by gabizou** [comment]
> Testing in 1.8.8 that doesn't appear to be the case. punching and replacing an item in an itemframe keeps it's orientation. But there's no guarantee that this will always be true.

It's storing a cached value, but the point is that regardless whether an `ItemStack` is retained, the value shouldn't be considered to just remain "cached" and then magically break when it is no longer cached.
