### ISSUE TITLE
BlockRay not working properly with Players

### ISSUE THREAD

**Issue by mcglonelevi** [SpongePowered/SpongeAPI#805]
I am trying to get the block that a player has their crosshair over.  It appears that instead of starting from the player's "eye level", the BlockRay appears to start from their feet.  Is this expected behavior?  I am using this line of code that was modified from the code example in the comment in BlockRay.java:

Iterator<BlockRayHit> block = BlockRay.from(player).filter(BlockRay.ONLY_AIR_FILTER).iterator();

Here is the result (pretend pumpkin snowman is a player):

![image](https://cloud.githubusercontent.com/assets/7388208/9285398/83892ece-42b3-11e5-8202-d95df164f99e.png)

**Comment by JBYoshi** [comment]
This is because eye location hasn't been implemented yet.

**Comment by mcglonelevi** [comment]
Thanks for the quick reply.

**Comment by JBYoshi** [comment]
It should work now that `EyeLocationData` has been implemented.
