### ISSUE TITLE
Fix GameDictionary

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeAPI#806]
There is a slight problem with the `GameDictionary` API. In Forge, an ore is represented by an `ItemStack`, while in SpongeAPI, only the `ItemType` is relevant. This can lead to some confusion; for example, an item stack containing an ink sack would pass for "gemLapis". They have the same `ItemType`, but not the same data (dye color). This should be fixed.

**Comment by Azatik** [comment]
I opened the topic for the metadata (sub id)
https://github.com/SpongePowered/SpongeAPI/issues/610

**Comment by JBYoshi** [comment]
Status?

**Comment by Zidane** [comment]
@JBYoshi 

This isn't a priority. If you choose to address this you can but it won't be for a while.

**Comment by CrystalMageX** [comment]
@JBYoshi @Zidane This sounds like a dupe bug waiting to be abused when paired with a Shop/Magic plugin/mod. I don't think **dupe bugs** should be **low priority**.

For example: Consider two chest-shops, one selling ink sacks for $5, and another buying lapis for $20. If a player were to buy an ink sack, and trick the lapis shop that depends on checking for "gemLapis," they would have **made $15 out of thin air!**

**Comment by JBYoshi** [comment]
@CrystalMageX I'll get to work on it.
