### ISSUE TITLE
Differentiate between flying capability and flying state

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#810]
The server is able to control two facets of flying on the client:

 * The ability to toggle flying on and off
 * Whether or not the client is currently flying

From what I can tell, `FlyingData` only includes the latter, though it's not very clear at the moment. It should be modified to allow both to be controlled.

**Comment by gabizou** [comment]
More than likely we'll have to add either a singular `PlayerCapabilityData` or multiple  manipulators for the various "capabilities". This would likely resolve #575.

**Comment by gabizou** [comment]
Clarified and fixed in 286f1ddbb2da9b2c6085a2984e07702c9ab
