### ISSUE TITLE
Sponge Contrib - Centralized Unstable API

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeAPI#818]
## The Problem
Not so long ago, there was a very popular API known as Bukkit. However, arguably one of its greatest flaws was that it tried too hard to minimize API breakage. This lead to many mods circumventing the API. Which intern lead to numerous stability issues, to the point where the "NMS" portion of the API had to be versioned via modifying the packaging. 

This is a fantastic case of treating the symptom, not the problem. Rather than addressing the core issue "people want to use features which may be removed in future versions of Minecraft." The API completely refused to support these desirable features.

Due to the aggressive stance, and the incompatibly issues -- caused by the repackaging -- on portions of NMS code which changed in insignificant ways, various abstraction libraries, and APIs were written to enhance Bukkit. These were not centralized however, and varied greatly from project to project, or in the worst case, things were written purely using NMS code. I don't think I have to tell anyone that code duplication, and wide scale API circumvention should never be desirable traits.

Regardless of Bukkit's problems though, this aggressive API practice lead to a arguably highly stable API. However, we can do better!

## Sponge Contrib Proposal
Now, enter 2015, and what I'm proposing as "Sponge Contrib". Sponge Contrib would be a new additional repository in the Sponge ecosystem, which would be shaded into the fully compiled Sponge jar, or distributed with the Sponge jar as an external library which could be easily dropped into the lib folder.

### How it works
Trusted community members and core devs would be added to a dedicated team, and given strict guide lines about how to write their APIs. These guide lines would have to adapt as the project goes forward and new problems are encountered of course, however, my initial proposal is to have the following guidelines:
- All APIs must be fully packaged under org.spongepowered.contrib.*
- All APIs must include their name followed by their numeric version number in the package such that the format is the following:
````
org.spongepowered.contrib.<my api>.<version number>
````
- All APIs must include their implementation in a package such that the format is the following
````
org.spongepowered.contrib.<my api>.internal
````
- All APIs must not create any additional dependencies on Sponge. Thus, all content must come from an existing Sponge dependency.
- All APIs which depend on Forge must clearly state this.
- Any breaking changes to an interface, which would cause a behavior change -- except where to correct a previously erroneous behavior -- must result in a new version number.
- No API is to be initialized before being requested.
- There shall be no publicly accessible static data, or methods

Before, I continue, I want to take the time to explain the reasoning behind a few of these guidelines. Firstly, since these APIs are considered to be unstable, maintaining as much binary compatibly as possible is a must. Thus, the packages containing the externally facing interface definitions are versioned -- at a visually intrusive level (the package, as apposed to the class). It also follows that, to maintain code reuse and keep binary size to a minimum, the implementation of said interfaces should be kept in a separate package which is version independent.

The points about initialization, and static data, shall likely become more clear later on, as the system is described. However, the idea is to not directly call out to any Contrib classes, nor have anything preinitialized as this undermines the version safety, and may impact the runtime performance of servers not making use of any Contrib APIs.

### Sponge Contrib API Design Guidelines & Contrib API Manager
The Contrib API design guidelines boil down to one main rule, make all APIs have next to 0 runtime impact where not used.

Thus, a new system, very similar to the services system must be created (perhaps piggybacking on the services API/sharing some code). It would be effectively the same, let's take a look at the service API:
```` java
Optional<MyInterface> optMine = game.getServiceManager().provide(MyInterface.class);
````

This is the exact concept we want to have with Contrib. However, the service system would also be handling initialization. To get this to work, I'm proposing that, in this case, MyInterface would look something like this:
````java
@ImplementedBy(impl = MyInterfaceImpl.class)
public interface MyInterface {
  void helloWorld();
  Bob createBobFactory(); // Factory for creating Bob objects
}
````

The "Contrib API Manager" would then use reflection to find and initialize the default constructor of MyInterfaceImpl, if all goes well, and MyInterfaceImpl implements MyInterface, and the API Manager would return an Optional<MyInterface> containing the created instance, and hold onto the initialized object. 

On the flip side, if things went badly, the null value would be stored, and we would still return an absent optional. This prevents overhead from repeated failed initializations, and their respective exceptions.

It's important to note that, these stored objects should be seen as a kind of gateway to the Contrib API, effectively factories, or objects containing useful methods (think a static utility class), being *effectively* Singletons which *must pass checks* before being accessed. Thus, if a class was not found in this version of Contrib, the plugin would know that the dependency failed, and handle that behavior responsibly -- we hope.

## Putting it all together
So what this gives us, is the ability to have a checked system, where things can be versioned, broken/removed safely with minimal impact, and clearly designated as instable. Additionally, this can be seen as a staging ground for APIs which we may want to bring into the main SpongeAPI repository. This allows our community to share code, and develop APIs which are better as a whole, even for features which may not be in the next version of Minecraft -- while still maintaining an API with stability equal to that of Bukkit.

**Comment by Zidane** [comment]
Interesting proposal.

I've always been about use cases (as well as @bloodmc ). What did you have in mind to be in a contrib "un-safe" API package? Gives us a few some we can gauge priority on this issue please.

**Comment by gratimax** [comment]
I like this idea, but I think I see more use for in terms of cleaning up some of the more opinionated things in the API. No one can discount the usefulness of stuff like the newer command system or text formatting, but those sorts of APIs never fully sat right with me because I felt that they were perhaps too opinionated. They also didn't require any implementation-specific code as far as I know, meaning that they weren't really part of the base of the Sponge API. 

I think providing a curated 'contrib' repository and artifact is the perfect alternative here, but I guess it's a little different from the use case @DarkArc originally intended. Under this scheme I think it would be better to not explicitly version contrib APIs deemed stable. There is probably a place for a package like `org.spongepowered.contrib.dev` with versioned APIs as in the original suggestion, because I definitely see merit for that. In addition, it might be a better idea to distribute the contrib JAR as a dependency of the API JAR so that all plugins can have access to these useful APIs without much trouble. They do not need to touch anything in the `dev` package if they do not want to explicitly touch it.

I think my inspiration for this comes from the [django contrib packages](https://docs.djangoproject.com/en/1.8/ref/contrib/), which follow a similar philosophy. They are additional apis on top of 'core django', but are still bundled with every installation for convenience. Seems to work well for them, and it might work well for us too.

**Comment by wizjany** [comment]
Second @Zidane on use cases.
This isn't bukkit anymore. The majority of stuff that used to be done by accessing nms/obc will probably be accessible through the API. Other things will just mean converting your Sponge plugin to a Forge mod (that's basically what versioned packaging is...recompile each new version).

The only thing I can think of off the top of my head right now is packet handling and modification. And I think (although I've never looked into it much) that that sort of thing was mostly used because certain APIs were missing/lacking.

**Comment by ryantheleach** [comment]
One of the reasons why NMS was so highly wanted, was that larger servers wanted to have the latest gimics before it was available to everyone (Boss bars, holograms, Text, non listed particles, messing with weather / dimension properties, sending Out of Bounds values). Exposing a packet API in some form would allow those servers to continue pushing the boundaries, allowing SpongeAPI to catch up and mimic the stuff deemed stable or useful. 

In addition it seems like a great place for service interfaces to mature, Imagine if vault was being developed on sponge, they could version the interface, and continue to improve upon it until happy getting plugin feedback, then it could be added to sponge itself.

**Comment by DarkArc** [comment]
So, there are several different ways this could be used, and I don't think they're mutually exclusive of each other. 

@gratimax I fully understand where you're coming from with "opinionated APIs" that was one thing I felt could go here, if it was so desired. In that way, we can keep the core Sponge API a clean interaction API, and have a "standard library" of sorts which can also be used. 

As for your point about distributing this as a dependency of the API jar. I see this being developed essentially like a Forge/Sponge mod. You build against the latest Sponge/Forge, and APIs which use Forge specific features would note that in their documentation, or via some kind of annotation. Then you just use it with whatever runtime SpongeVanilla/SpongeForge you would like, and it should work provided no one is using a plugin which uses a Contrib API built off of Forge specific stuff on SpongeVanilla.

### Versioning
So, I do want to take some time, and talk about the versioning for a moment. The point is not API x may be unstable, consider this to be more a system of shared libraries -- or DLLs for windows people. We can have several different "versions" of this same library working in tandem, sharing a common implementation. For instance:
```` java
package org.spongepowered.contrib.bob.0;

public interface Bob {
  void foo(Bar b);
  void mc_1_8_stuff();
}
````

```` java
package org.spongepowered.contrib.bob.1;

public interface Bob {
  void foo();
}
````

It may very well make sense to allow both of these to function, it's just in the newer one, we wanted to change the behavior of foo a bit. We also realized, that mc_1_8_stuff wasn't going to work in our new 1.9 version of our API, so we tossed it. 

Now, because everything is versioned (and we're on 1.9), we can cleanly remove bob.0 without breaking bob.1.

This also helps with API evolution, rather than throwing a ton of @Depricated annotations everywhere or changing the behavior of some function foo, we can start fresh without breaking everything. 

For instance, let's say in the 1.9 version it made more sense for foo to do something completely different, than in the 1.8 version, but they both should still be called foo. We can either make that change silently, or we can make it quite visible by having versioning, and get the API via the API Manager to check to see if the interface the plugin is looking for is still supported (maybe we can have both behaviors of foo behind the two different interfaces in this case somehow by black magic).

Yes, I realize these are a lot of "maybe" cases, but I'd rather cover as many "Oops didn't think of thats" up front as possible.

Additionally, @gratimax if an API is completely based off of Sponge, I see no reason why it couldn't just stay at version 0. Since these things are handled at the package level, I don't really think anyone is going to care, as it's not like their code is becoming cluttered with MyClass_API_0 declarations, or something of that sort.

### Usage Cases
- Firstly, API evolution, this gives us a clear place to have new APIs evolve into something very stable, well tested, and well designed for Sponge API.
  - Think the evolution from common currency APIs from Register to Vault
- Secondly, as @gratimax pointed out, we can include things which are not critical to the API. This could be used as a clear place to put those "opinionated" APIs as he called them. 
- Thirdly, this gives us a nice place where we can share APIs that only make sense for some plugins, but we anticipate a variety of plugins being formed. 
  - Think of cases like Anticheat & NoCheatPlus as well as LogBlock, Hawkeye, CoreProtect, Prism, etc. In the case of the anti cheat systems, they could share common code about how they're determining different violations, even if they have completely different logic about how they process a violation, the definition of a violation, is not going to be any different, and the best approach could be stored here for all to use. In the same regard, logging plugins could stop reinventing the wheel, and keep various logging tools here to backtrack various things, while still having a various front ends, and database storage approaches.
- There are also cases for Packets beyond what Anticheat & NoCheatPlus like plugins would want to use. I can't think of many examples of this, but I can say that over the years there have been various packets sent to the server, that the server did nothing with. For instance, things like the "Difficulty" setting were sent off to the server. Information like this could be used by a plugin to create per-player difficulties. This is an example of something which, while unstable, and perhaps removed in a future version, could lead to a few interesting mods, at least for that version of MC. Considering we're also in the realm of Forge servers where versions last a bit longer, and the MC releases have slowed down over the years, this may be more applicable than it was for Bukkit.

I'm sure there are more use cases than these, but the use cases are effectively going to stem from and expand upon these points.

**Comment by gabizou** [comment]
Personally, I was going to try to investigate in a system like this, providing some "versioned" API's that weren't guaranteed to stick around beyond various versions (look at the unused potions that are completely removed in 1.9). What I could consider adding as well is that this can be referred to as "Incubation" of an API that could eventually make it's way into the main API. It's very much like gradle's incubating features, they're available, but they're not very well tested yet. I would be in favor of providing some form of "incubating" API library that would become the "standard" for various plugins to hook into, let alone provide some extra feature support without making the guarantees that they'll stick around the next version.

Additionally, it would help if there was a module framework for plugins to take advantage of (akin to how many plugins wrote compatibility layers for module loading for specific package versions).

**Comment by Zidane** [comment]
Closing this as,,,,

* We've proven that we do NOT let API go stale...if it must be broke, it'll be broke
* Deprecated annotation was made for a reason, if its marked as such we will get rid of it
* Our mantra of intelligent API design vs. API longevity means that there is no reason to version any parts of it, plugin developers need to be responsible and update to newer versions (if they so choose).
