### ISSUE TITLE
Relax ServiceReference.executeWhenPresent generics

### ISSUE THREAD

**Issue by Xfel** [SpongePowered/SpongeAPI#820]
Currently, the contract of the method looks like this:
```
    void executeWhenPresent(Predicate<T> run);
```
However, as T is only used as argument to the predicate, any `Predicate<? super T>` would work and allow a wider range of uses.

Also, I'm slightly confused why Predicate is used here at all instead of `org.spongepowered.api.util.Consumer`. I guess it's probably just because the method is older then the interface, so it would be possible to enhance this. As this is an api breaking change and not too important, it's probably not going to happen, but I wanted to inform about this.

**Comment by Bammerbom** [comment]
Spongeapi is not finished, so api breaking changes are allowed

**Comment by zml2008** [comment]
yeah, this is older code, but since we're in the process of moving to jdk8, this can be fixed up.

**Comment by Xfel** [comment]
Small reminder bump on this as the transition to java8 is currently in progress, and it'd be sad if this would be forgotten.

**Comment by Zidane** [comment]
@gabizou Is this still relevant?

**Comment by JBYoshi** [comment]
It hasn't been fixed yet. https://github.com/SpongePowered/SpongeAPI/blob/6a4f0ee198a69c5629ad230157e780d81826f3e5/src/main/java/org/spongepowered/api/service/ServiceReference.java#L61
