### ISSUE TITLE
Clarify where \n separator can be used for texts

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeAPI#821]
Allowing multiple lines to be displayed by the ```HoverAction.Text``` action, this can currently only be achieved by creating a item stack with a desired lore and name and it would be a lot easier if you can just create a hover action with an array of lines.

**Comment by Minecrell** [comment]
You should be able to use `\n` in Text instances.

**Comment by Cybermaxke** [comment]
Oh, I didn't know that. But it would still be nice to be able to use a array of text objects. Or having the possibility to easily split the text into an array by using a seperator.

**Comment by wizjany** [comment]
an array of texts isn't the same as an array of lines though. a text object could have any number (including 0) newlines.

**Comment by ST-DDT** [comment]
With my PR #808 you can easyly create an array of stuff you want to show and join them. Joining texts is already possible. 
````java
Texts.join(Texts.of("\n"), lines)
````
However splitting is not possible and in my opinion not desireable as well.

**Comment by Minecrell** [comment]
Why exactly do you need the texts separated for each line? If you're only interested in the content using `Texts.toPlain(Text)` and splitting the string then might make more sense.

**Comment by Cybermaxke** [comment]
Yeah, that could do the trick. And maybe adding clarification where the '\n' seperator can be used to define the next line. Because this won't work inside item lore for example.

**Comment by Minecrell** [comment]
I think it is kind of implementation-dependent where special characters like this can be used, at the end this can always change easily between Minecraft versions so I think as a general rule simply having the users testing it will be more reliable than adding it into the API.
