### ISSUE TITLE
Additional plugin metadata- author/description

### ISSUE THREAD

**Issue by varrix** [SpongePowered/SpongeAPI#822]
Are there any plans to expand the `@Plugin` annotation to incorporate an "author" and "description". This is something I would like to use for polling and sorting plugins to be displayed for more information in-game.

**Comment by wizjany** [comment]
related https://github.com/SpongePowered/SpongeAPI/issues/624

**Comment by Minecrell** [comment]
This is planned, however it depends on #624 being decided first.

**Comment by Zidane** [comment]
Closing since Minecrell's PR covers this + more.
