### ISSUE TITLE
GenericArgument.remainingJoinedStrings Strange Help Message

### ISSUE THREAD

**Issue by CrazyPyroEagle** [SpongePowered/SpongeAPI#825]
I've been using GenericArguments to create Arguments for my plugin commands, but the following arguments...

    GenericArguments.onlyOne(GenericArguments.player(Texts.of("Player"), game))
    GenericArguments.optional(GenericArguments.remainingJoinedStrings(Texts.of("Message")))

Ends up showing up as `<Player> [<Messageâ€|>]`when I trigger the not enough arguments message, even though I expected it to show up similarly to `<Player> [Message...]` or `<Player> [Message]`

**Comment by zml2008** [comment]
Something along the way isn't handling unicode properly... Is this in your server console or ingame, and which OS?

**Comment by JBYoshi** [comment]
@zml2008 I had a similar issue with the commands PR - that's why I initially changed the Unicode arrows. I fixed it by changing the Eclipse file encoding to UTF-8; I think the compiling system controls the Unicode stuff.

**Comment by zml2008** [comment]
yeah, iirc gradle sets the encoding correctly. So if @CrazyPyroEagle built with eclipse, it'd be wrong (someone who uses eclips may want to file a bug report, since this is sometimes caused by eclipse's brokenness)

**Comment by CrazyPyroEagle** [comment]
I'm indeed using Eclipse, although the bug also happens in-game. I don't know if this has anything to do with it, but I managed to write a small program that completely breaks the Eclipse console about a month ago.

    long count = 0;
        while (true) {
            System.out.printf("%,d", ++count);
            if (count % 50000 == 49999)
                System.out.println();
            else
                System.out.print(" ");
    }

**Comment by JBYoshi** [comment]
@CrazyPyroEagle Try going to Window>Preferences>General>Workspace and make sure Text File Encoding is set to Other>UTF-8.

**Comment by CrazyPyroEagle** [comment]
@JBYoshi As I said, it also happens in game.

**Comment by JBYoshi** [comment]
In that case, it would depend on the build script and the server. Updating the character encoding fixed my problem in the game as well as the workspace.

**Comment by CrazyPyroEagle** [comment]
Strangely enough this was indeed a character encoding.
What I don't understand is why the game chat displays bad text if the encoding is incorrect...

**Comment by JBYoshi** [comment]
@CrazyPyroEagle It's because the source code can be in multiple encodings, but the bytecode uses an encoding (UTF-16) that remains the same regardless of encodings specified at runtime.
