### ISSUE TITLE
Declare immutable collection types in the API

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/SpongeAPI#826]
# The motivation
The Bukkit API had many not so well designed parts.
When I used Bukkit, I never knew when objects would change their state.
For example: The inventory API. It was so terrible to use the contents of an `ItemStack` without cloning it. If someone modified an `ItemStack`'s content from a player's inventory, strange things would occur. The player had different inventories on the server and the client side and so on.
I could tell many more examples, but I think you got the point.

# The solution
Sponge did this a lot better. Most Javadoc comments declare when an object is mutable or immutable. Unfortunately, the collection types are still the ones from plain old Java, so the underlying type is not guaranteed to be immutable.
The solution to this would be using Guava collections like so:

```java
import com.google.common.collect.ImmutableCollection;

ImmutableCollection<Player> getOnlinePlayers();
ImmutableCollection<WorldProperties> getUnloadedWorlds();
ImmutableCollection<WorldProperties> getAllWorldProperties();
```
These are just three examples from the `Server` interface.
It would be easy to change because it won't break backwards compatibility as ImmutableCollection implements java.util.Collection.

# Conclusion
Maybe there could be performance concerns, but I think it doesn't matter. For example the `EntityDisplacedEvent` is created everytime when an entity is moved.

In the end, I think we should get our API well designed first and then try to optimize for performance in the implementation(s).

**Comment by wizjany** [comment]
This has been talked about before in other contexts, but one of the issues with ImmutableCollection is that it still has a remove method, and will happily throw big fat UnsupportedOperationExceptions all over if plugins try to modify collections that shouldn't be. The only difference is that you will get a deprecation warning if you have any code that calls those remove methods.

**Comment by ST-DDT** [comment]
IMO stating in the javadoc is enough.
A lot of methods already use or return ImmutabeX but forcing this by the API may block other collection implementations in the impl.
And there will always be the one that neither read javadocs nor care about deprecation warnings.

**Comment by kenzierocks** [comment]
Our API doesn't declare them as guava collections, but IIRC they are all
immutable.

>

**Comment by TheRaspPie** [comment]
Of course I didn't propose this to prevent plugin developers from using dirty hacks.
It should be there to protect the implementation from returning collections that could be modified after a period of time and to give the developers confidence that the contract really is enforced.

**Comment by JBYoshi** [comment]
Maybe add an `@Immutable` annotation that indicates that the return value is immutable?

**Comment by wizjany** [comment]
That is the same thing. The object still has a remove method, there are just warnings not to use it.

**Comment by TheRaspPie** [comment]
This solution is not perfect. We could of course write our own immutable collection interface and implementation, but that would be bad for compatibility. I think without losing backwards compatibility we can't do better.

Maybe we shouldn't adopt this at all, I just found it to be a good idea, because you <b>see</b> that it's immutable and expect that it can't be modified.
Of course this may be a problem for newcomers, but I think they should learn these concepts anyway. :P

The only <b>problem</b> I see is that <b>the implementation of the API is bound to a specific collection implementation</b>.

**Comment by wizjany** [comment]
backwards compatibility isn't really a huge deal right now anyway as the api is constantly changing still (just look at the refactor/event-names branch, for example).

**Comment by TheRaspPie** [comment]
@wizjany You're right.

If we don't change it, I will correct the places where it's not specified because now the Javadocs are incomplete for some functions.

**Comment by gabizou** [comment]
To be honest, after speaking with a few people, it's best we just stick to using the `java.util` collections in all signatures in the event we ever change away from guava or whatever else the case is. The returned collections may still very well be `ImmutableCollection`s in implementation, but that's what javadocs are for. Javadocs should document very well, but as everyone should be well aware, we're shoulder deep in massive changes with the [refactor/event-names](https://github.com/SpongePowered/SpongeAPI/compare/refactor/event-names) branch.

**Comment by gabizou** [comment]
It's been decided with @SpongePowered/developers that we're going to use only the Collections interfaces and javadoc things as either "immutable" or "unmodifiable". The reasoning is so that at later times we can easily change the return type (in the case that Guava does eventually change their collections, though how, I don't know or care), or we start using a different immutable collection implementation.

**Comment by TheRaspPie** [comment]
Ok, thank you.
