### ISSUE TITLE
API Clarification: EntityEnterPortalEvent

### ISSUE THREAD

**Issue by Gaelan** [SpongePowered/SpongeAPI#827]
When a survival player enters a nether portal, does `EntityEnterPortalEvent` fire before or after the delay?

**Comment by gabizou** [comment]
The act of an entity being *teleported* is a different event. The act of an `Entity` physically entering a portal is the event you've stated. There's a lot of changes especially with this with regards to clarification in the [refactor/event-names](https://github.com/SpongePowered/SpongeAPI/blob/refactor/event-names/src/main/java/org/spongepowered/api/event/entity/EntityPortalEvent.java) and the branch itself.

**Comment by Gaelan** [comment]
So, is there an event for overriding Portal behavior? (In my case, I’m working on a multiverse-type plugin and want to allow setting which worlds function as “Nethers” or “Ends” for which other worlds)

**Comment by gabizou** [comment]
> So, is there an event for overriding Portal behavior? (In my case, I’m working on a multiverse-type plugin and want to allow setting which worlds function as “Nethers” or “Ends” for which other worlds)

Yep, [DisplaceEntityEvent.Teleport](https://github.com/SpongePowered/SpongeAPI/blob/refactor/event-names/src/main/java/org/spongepowered/api/event/entity/DisplaceEntityEvent.java#L77-L81). There's also the [TeleporterAgent](https://github.com/SpongePowered/SpongeAPI/blob/refactor/event-names/src/main/java/org/spongepowered/api/world/TeleporterAgent.java#L30)
