### ISSUE TITLE
Lambda events? (no reflection event calls)

### ISSUE THREAD

**Issue by Soren025** [SpongePowered/SpongeAPI#828]
First off this isn't really java 8 specific but the idea came to me when the Java 8 announcement was made.

Event's as they are now if I am not mistaken get the method through reflection and call the method through reflection. Something I thought about was instead a method, declare a field of a functional interface (EventHandler<T> just so happens to work) like so

```Java
public class Listener {
    
    @Subscribe
    public final EventHandler<PlayerJoinEvent> onPlayerJoin = (event) -> { };
}
```

or even
```Java
public class Listener {
    
    @Subscribe
    public final EventHandler<PlayerJoinEvent> onPlayerJoin = this::actualOnPlayerJoin;

    // This method could be a static method in some utility store of listener implementations
    private void actualOnPlayerJoin(PlayerJoinEvent event) {

    }
}
```

The idea is you reflect the field when registering the listener so when the event is called, it calls the stored event handler interface as a direct call instead of calling a method through reflection.

The one thing however is this would require the use of something like https://github.com/jhalterman/typetools, a lib that is able to resolve generic types at runtime under certain cases, a declared lambda as shown above is one of such cases (tested it with reflected field and works).

**Comment by Minecrell** [comment]
The implementation does not call the event handlers using reflection, a dynamic event handler is generated at runtime that will call the event handler method directly, exactly like a normal method call would work.

**Comment by Soren025** [comment]
Oh didn't know that

**Comment by Minecrell** [comment]
However, registering lambda events is possible anyway:

```java
game.getEventManager().register(this, PlayerJoinEvent.class,
        event -> event.getEntity().sendMessage(Texts.of("Hello!")));

game.getEventManager().register(plugin, PlayerJoinEvent.class, this::onPlayerJoin);

public void onPlayerJoin(PlayerJoinEvent event) {
    event.getEntity().sendMessage(Texts.of("Hello!")));
}

**Comment by Soren025** [comment]
True but how do you unregisrer those

**Comment by Minecrell** [comment]
@Soren025 
```java
EventHandler<PlayerJoinEvent> handler = this::onPlayerJoin;
game.getEventManager().register(this, PlayerJoinEvent.class, handler);
game.getEventManager().unregister(handler);
```

**Comment by Soren025** [comment]
That works? Always thought that only worked for listener objects.

**Comment by Minecrell** [comment]
@Soren025 It is _supposed_ to work, couldn't tell for sure right now; however.

**Comment by JBYoshi** [comment]
I think `EventHandler` would need to be marked as `@FunctionalInterface` first. Not sure if that's been taken care of in the jdk8 branch though.

**Comment by kenzierocks** [comment]
`@FunctionalInterface` is just semantics, you don't need it for anything.

**Comment by JBYoshi** [comment]
@kenzierocks Never mind then. I had trouble once with lambdas and custom code and wasn't sure why, but I just checked and found out that lambdas only work with functional *interfaces*. (I thought it worked with abstract classes as well, so long as they only had a single abstract method. Apparently not.)
