### ISSUE TITLE
Post Great Event Refactor Changes

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeAPI#830]
So as of yesterday, the Great Event Refactor landed in master and its been a game changer in how events are used in the API.

Obviously with refactor that massive, things will fall by the wayside. The following is a list that will be expanded upon as people mention them so we can get things fixed.

- [x] Need to specify that GameClientConnectionEvent.Authenticate is async. Thanks @wizjany
- [x] Need to adjust the events for Player in the player package. Many of those don't fit ActionTarget and should be addressed.
- [x] Death events replaced by DestructEntity, but DestructEntity is not subclassed and there is no way to set death messages now.
- [x] BlockDamageSource has getBlockState which returns a BlockSnapshot which has a getState which actually returns a BlockState. Kind of awkward wording: blockDamageSource.getBlockState().getState()
- [x] HarvestEntityEvent should occur after DestructEntityEvent. Note in Javadocs.
- [x] CollideBlockEvent has no javadocs explaining the events

**Comment by Zidane** [comment]
@bloodmc ^

**Comment by wizjany** [comment]
Death events replaced by DestructEntity, but DestructEntity is not subclassed and there is no way to set death messages now.

**Comment by wizjany** [comment]
BlockDamageSource has getBlockState which returns a BlockSnapshot which has a getState which actually returns a BlockState. Kind of awkward: blockDamageSource.getBlockState().getState()

**Comment by gabizou** [comment]
HarvestEntityEvent should occur after DestructEntityEvent. Note in Javadocs.

**Comment by ZephireNZ** [comment]
CollideBlockEvent has no javadocs explaining the events
