### ISSUE TITLE
Missing damage sources

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeAPI#831]
according to  http://minecraft.gamepedia.com/Damage#Natural_damage
in a [DamageSources](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/cause/entity/damage/source/DamageSources.java) class are currently missing types Lightning, Anvil, Suffocation, Thorns, Cactus contact

**Comment by wizjany** [comment]
``` * A static collection of various {@link DamageSource}s that remain static, or
 * otherwise "ambiguous" with regards to the actual source```

Lightning is an EntityDamageSource with the Lightning entity, Anvil is a FallingBlockDamageSource with the anvil entity, suffocation is a BlockDamageSource where the block is the one covering the head of the damagee, etc.

**Comment by gabizou** [comment]
Thanks @wizjany for answering the question.

@NeumimTo There's a little bit of a difference from some of the `DamageSource`s from MC and our own. To help facilitate understanding, there's `DamageType`s that have been added to help further understand what type of damage is being done.
