### ISSUE TITLE
Translation API usage

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/SpongeAPI#832]
Normally one would translate text using `Texts.of(Translation translation, Object... args)`.
The `Translation` interface defines the following method: `get(Locale locale, Object... args)`.
This method translates an id to a `String`.

Why is it a `String`? Can't we just return a `Text` to have the flexibility to add color codes in the config (for example). We could also read JSON oder XML from a config file and translate that into `TextAction`s. The possibilities with this are endless.

My proposal is this:
Beside this method from `Texts`:

```java
public static Text.Translatable of(Translation translation, Object... args)
```

provide this method too:

```java
public static Text of(Function<CommandSource, Text> translation)
```

This allows for the most flexibility while keeping the convenience that other users want.
We could even implement the first method with the second one:

```java
public static Text of(Translation translation, Object... args) {
    of(sender -> translation.get(sender.getLocale(), args));
}
```

What's cool with this, we could send every player a message with his own name.

I added the `getLocale()` method on `CommandSender`. This would be very useful in other ways, as you could send localized text to the console depending on the language of the operating system.

For the following I didn't want to open a new issue, so I create it here:
Maybe we could also add a `MessageSinks.toNone()`. Then we could simply cancel all messages from a `MessageEvent`.

**Comment by ST-DDT** [comment]
There is a problem with your player function.
There is no real possibility to get the player object and pass it to the Text.
However your suggestion with the 
`Translation#get(Locale, Object...) : Text` sounds nice. If nobody objects I would like to add that to my TextFormatExt PR. But I will check the side effect in a cuple of hours first.

**Comment by TheRaspPie** [comment]
@ST-DDT What do you mean with "There is no real possibility to get the player object and pass it to the Text."?
Of course there is.
The passed function is simply called for each `CommandSource` in the `MessageSink` to determine its specific message.
A translation means sending specific messages to players. The function I proposed would handle that in a more generic way and would eliminate the need for:

```java
for (Player player : server.getOnlinePlayers()) {
    player.sendMessage(Texts.of("Your player name is ", RED, Texts.of(source -> source.getName())));
}
```

If we didn't have that, we couldn't do a specific message in a `MessageEvent` without removing all `CommandSource`s from the `MessageSink` and sending our own messages. I think we shouldn't let people use such "hacks".

**Comment by ST-DDT** [comment]
First of all using a function at that location/example does not really make much sense.

Why don`t you do it that way?
````java
for (Player player : server.getOnlinePlayers()) {
    player.sendMessage(Texts.of("Your player name is ", RED, Texts.of(source.getName())));
}
````
Or
````java
Text template = Texts.of("Your player name is ", RED, Texts.placeholder("0"));
for (Player player : server.getOnlinePlayers()) {
    player.sendMessage(Texts.format(template, player.getName()));
}
````

Adding a `PlayerAwareText` requires recursive search for this class. The `Text.Placeholder`s are not limited to `Player`s.

**Comment by TheRaspPie** [comment]
Consider the `PlayerJoinEvent`.
You cannot call `setNewMessage(Text)` with a `Text` that is player-specific otherwise.
Then you would have to do

```java
event.setSink(MessageSinks.toNone);
for (Player player : server.getOnlinePlayers()) {
    player.sendMessage(player.getName());
}
```

I don't think the API was intended to use like that.

A translation with fixed parameters fulfills the same purpose except using the current player's data in the `Text` message.
I think this method is needed because `Text` combined with a `MessageSink` can target multiple `CommandSource`s. If we then don't add support for per-sender custom messages, I think we make the plugin developer's life hardier than it has to be.

**Comment by ST-DDT** [comment]
Sorry I don't get you.
If a player joins I usually show the name of the player who joined.
But I don't show my own name to me.
````java
event.setNewMessage(Texts.of("Player "+event.getJoined().getName()+" has joined"));
// event.setNewMessage(Texts.format(template, event.getJoined()))
event.setSink(Sinks.allOnline());
````

**Comment by TheRaspPie** [comment]
The `PlayerJoinEvent` was a bad example for this.
But consider the following example:

Imagine a PvP server. When a player joins, I want to send every player on the server a message with the relative position of the joined player.

I could do the following:
```java
@Listener
public void onPlayerJoin(PlayerJoinEvent event) {
    event.setSink(MessageSinks.toNone());

    Player joined = event.getSourceEntity();
    for (Player player : event.getGame().getServer()) {
        if (player != joined) {
            player.sendMessage(Texts.of("The joined player ", joined.getName(), " is ", calculateDistance(joined, player), " blocks away from you."));
        }
    }
```

or one could write:
```java
@Listener
public void onPlayerJoin(PlayerJoinEvent event) {
    Player joined = event.getSourceEntity();
    Set<CommandSource> recipients = event.getSink().getRecipients().stream()
                                                                      .filter(rec -> rec != joined)
                                                                      .filter(rec -> rec instanceof Player)
                                                                      .collect(Collectors.toSet());
    event.setSink(MessageSinks.to(recipients));
    event.setNewMessage(Texts.of("The joined player ", joined.getName(), " is ", Texts.of(source -> calculateDistance(joined, (Player) source)), " blocks away from you."));
}
```

If we would add `add` and `remove` methods to `MessageSink` and `MessageSinks.toAllOnlinePlayers()`, we could even write:
`event.setSink(MessageSinks.toAllOnlinePlayers().remove(joined));`

**Comment by ST-DDT** [comment]
Okay that part is clear.
But how or where do you convert the `SmartText` into a plain `Text`? (On the implementation side)

`SpongePlayer.java`
````java
public void sendMessage(Text message) {
// Do magic to convert the `SmartText` into a plain `Text`
// Recursivly searching for the `FunctionalText`
}
````
-------------------------------------------------------
However i thing i found a possible solution to this problem.
You can already do this without changing anything in the API.

You could implement a `TargetAwareFormattingMessageSink`

````java
private final Map<String, Object> params;

@Override
public Text transformMessage(CommandSource target, Text text) {
	params.put("target" , target);
	return Texts.format(text, params);
}
````

and a `DistanceCalculator` (you could also inline this one)

````java
public class DistanceCalculator implements TextRepresentable {

	private final Player joined;
	private final Map<String,?> params;

	// Simple version
	public Text toText() {
		return Texts.of(calculateDistance(joined, (Player) params.get("target")));
	}

	// Hardcore version
	public Text toText() {
		Player target = (Player) params.get("target");
		return Texts.of(target.getLocale().getNumberFormat().format(calculateDistance(joined, target)));
	}
}
````

And you could use it like this:
````java
@Listener
public void onPlayerJoin(PlayerJoinEvent event) {
	final Player joined = event.getSourceEntity();

	Map<String,Object> params = Maps.newHashMap();
	params.put("distance", new DistanceCalculator(joined, params));
	
	event.setSink(new TargetAwareFormattingMessageSink(params));
	event.setNewMessage(Texts.of("The joined player ", joined, " is ", Texts.placeholder("distance"), " blocks away from you."));
}
````

That way could can even configure the `Text` content.
````java
Text  joinTemplate = Texts.json().from(config.get("joinTemplate"));
// Texts.of("The joined player ", Texts.placeholder("joined"), " is ", Texts.placeholder("distance"), " blocks away from you.");
event.setNewMessage(joinTemplate);
````

However I'm not sure whether `MessageSink`s are meant to be used that way.

**Comment by TheRaspPie** [comment]
@ST-DDT
I also discovered not long ago that `MessageSink` has an overridable method `transformMessage`.

<b>But:</b>
I don't want to create a new class everytime I want to send a player-specific message.
So I would just add this method for convenience.

To answer your question related to the implementation:
When the message is sent to the recipients of the `MessageSink`, the `SmartText` (as you called it) is evaluated and the function is called with the current `CommandSource`.

If you call `Player#sendMessage` then the function would just be called once.

**Comment by ST-DDT** [comment]
@TheRaspPie 

With my suggestion you only have to implement the `TargetAwareFormattingMessageSink` and the `DistanceCalculator` once.

>To answer your question related to the implementation:
When the message is sent to the recipients of the MessageSink, the SmartText (as you called it) is evaluated and the function is called with the current CommandSource.

> If you call Player#sendMessage then the function would just be called once.

@gratimax Suggested something similar: https://gist.github.com/gratimax/9aa7ecc33467e0ddfd0b.
But IMO that suggestion has the drawback, that its not easily serializable, and its difficult to pass multiple params to the `TextArgs`.

My current implementation of `Texts.format()` can do the same as @gratimax's suggestion.
You only have a slight overhead for lazy formating elements, but this could be fixed with a `LazyTextElement` interface and three lines of code in `Texts.format(...)`

I currently work on that feature.

**Comment by TheRaspPie** [comment]
@ST-DDT
What @gratimax suggested, can be used in composition with my proposal.
My proposal actually added a method to the `Texts` class so one doesn't have to do the loop manually.
Also the resulting `Text` can be used in any `MessageEvent`.

Yeah, the serialization actually is a big problem. But I don't think we can really do that, because `Text` isn't static, but dependant on the current context.

Look, for example, in `TextActions.executeCallback`. This can't be serialized, either.

**Comment by ST-DDT** [comment]
@TheRaspPie 

> Yeah, the serialization actually is a big problem. But I don't think we can really do that, because `Text` isn't static, but dependant on the current context.

Currently `Text` is very static/immutable and very easily serializable.

> My proposal actually added a method to the `Texts` class so one doesn't have to do the loop manually.
Also the resulting `Text` can be used in any `MessageEvent`.

Which is effectively the same as `Texts.format(...)` does for you.

> Look, for example, in `TextActions.executeCallback`. This can't be serialized, either.

Yes, but IMO you would use `Texts.format(...)` to replace a placeholder with a Text connected to that `TextAction`.

**Comment by TheRaspPie** [comment]
Then we could also replace a placeholder with `Texts.of(Function<CommandSource, Text>)`.
That would be the same situation as `TextActions.executeCallback(Consumer<CommandSource>)`.

**Comment by TheRaspPie** [comment]
Who developed the Text API? I think @Minecrell designed the Translation API?
Maybe they could state on this.

**Comment by TheRaspPie** [comment]
@gratimax As you're experimenting with the Templating API, this may be good to enhance its flexibility so that plugins can pass a closure to a `TextTemplate` that specifies how the `TextArg`s will be calculated depending on the `CommandSource` the message is sent to. This method could return a `Text` that internally handles it's content lazily.
The only problem I see with this, as @ST-DDT stated, is the serialization. A `Text` wouldn't necessarily represent pure JSON text (as specified by Mojang) anymore.
Maybe we could make `SerializableText` a subinterface of `Text` so that every `Texts.of()` would give back only serializable text. This is just an experimental idea to see what others think. I would have more ideas how to realize this, but at the moment I'm too tired. I'll describe it tomorrow,

**Comment by JBYoshi** [comment]
Problem: What if a `SerializableText` contains a non-serializable `Text`?

**Comment by TheRaspPie** [comment]
It cannot contain one... `TextBuilder` can only produce SerializableText.

**Comment by ST-DDT** [comment]
> Who developed the Text API?

There have been multiple iterations. I tried to participate on all of them. But a lot of other people did that as well. Have a look at the history to get a better overview on this.

If the current Text API is not capable of doing something important it must evolve.

@TheRaspPie If a serializable `Text.Literal` cannot contain your non-serializable `TextTemplate` then you cannot use your `TextTemplate` anywhere.

I solved this issue for my PR by stripping/replacing the not serializable part. IMO this is better than throwing an `Exception`. In most cases you want to load a `Text` message from a file, then you can replace the templates/placeholders with your customizations. But you probably won't write it to the file again.

**Comment by TheRaspPie** [comment]
@ST-DDT

**Comment by TheRaspPie** [comment]
@ST-DDT I'm talking about the serialization to disk.
But I also think that won't be an issue as there is already `Text.Translatable` and `Text.Selectors`.
So I would add Text.RecipientSensitive that contains `Text` depending on the `CommandSender`.
That may also eliminate the need for `MessageSink.transformMessage`. I think `MessageSink`s should only be a collection of recipients. Else if you want to manipulate the recipient list, you create a new `MessageSink`, deleting the custom behaviour a plugin may have previously added.

**Comment by TheRaspPie** [comment]
I think this may be closed because we now have `TextTemplate`s which cover messages which are customized per receiver/locale in a cleaner way.
