### ISSUE TITLE
Make Game.getServer() Optional

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeAPI#833]
This is in preparation for 1.9: https://twitter.com/SeargeDP/status/638736531105185792
(I haven't confirmed that the `DedicatedServer` object is the one that no longer exists, but I think that's what he means.)

**Comment by TheRaspPie** [comment]
It returned an Optional<Server> a while ago... But then someone came along and changed it to Server.
I don't know why and it makes no sense to me, as when plugins are initialized, the Server isn't started yet (I think).

**Comment by JBYoshi** [comment]
@TheRaspPie It was changed in commit 58356b363572a69ce6f0ef85e3d5717df1631f13. In 1.8 the `DedicatedServer` is always available, though not always used.

**Comment by kashike** [comment]
@JBYoshi I believe you mean `IntegratedServer` - `DedicatedServer` is not part of the client.

**Comment by kenzierocks** [comment]
A small reminder that FG merges server and client jars, for this reason.

**Comment by Mumfrey** [comment]
A small reminder that implementation details of the vanilla platform do not necessarily represent other implementations, nor guarantee the behaviour of even the vanilla platform in the future.

**Comment by JBYoshi** [comment]
@kashike Yeah, I meant `IntegratedServer`.

**Comment by JBYoshi** [comment]
Status?

**Comment by Zidane** [comment]
@JBYoshi 

I'm closing this as we can't know for sure what'll end up happening in 1.9 until release. We'll revisit then.

**Comment by JBYoshi** [comment]
I did some testing with the latest snapshot (15w50a), Eclipse, and VisualVM, and I've confirmed that the `IntegratedServer` may be `null`. Here's how I did it:

1. Add the **client** JAR to Eclipse.
2. `MinecraftServer` is one of the few nonobfuscated class names. Open it.
3. Open the type hierarchy of `MinecraftServer`. There should be one subclass; this is `IntegratedServer`. Note the obfuscated name.
4. Start an instance of the snapshot. Open VisualVM and connect to it.
5. Load a singleplayer world. Open the Sampling tab in VisualVM and search for the obfuscated name for `IntegratedServer` (step 3). You will see one result.
6. Now connect to a server. The `IntegratedServer` object will disappear.

**Comment by JBYoshi** [comment]
[Quote from](https://forums.spongepowered.org/t/psa-major-api-breakages-over-the-last-month/10296/8) Zidane on the Sponge forums:
> @JBYoshi

Optional can be unpopular and since Server will be used quite a lot...we'll be keeping it as is.

> To mitigate the possibility of null, this method will throw an un-checked exception as well as a `hasServer` will be added so you can check.
