### ISSUE TITLE
Slim down the Extent class

### ISSUE THREAD

**Issue by DDoS** [SpongePowered/SpongeAPI#838]
Right now this class is very bloated. It has methods that shouldn't be there. This includes player simulation (block interact and dig) and block power and flammability information.

I suggest moving the player simulation to a PlayerSimulator, which can be obtained from World using a getter. Internally this would just be our current simulated player in the implementation. In would implement and API class with the simulation methods.

Block power and flammability should be part of the data API, as a Property. @gabizou comment?

This would remove 20 methods from Extent, which is 195 lines of code out of 530, or 36.8% of the code.

**Comment by gabizou** [comment]
> Block power and flammability should be part of the data API, as a Property. @gabizou comment?

I thought I already removed them from Extent and Location? I did create some properties for them, but the `Direction`al properties are where properties are somewhat awkward, I'm thinking of a `getProperty(Direction, Class<T extends Property<?, ?>>)` method to add to the [`LocationCompositeValueStore`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/extent/LocationCompositeValueStore.java).

**Comment by DDoS** [comment]
Well what can I remove? They are still there.

**Comment by DDoS** [comment]
Fixed in d0bc2725 (and 2e0fb489)
