### ISSUE TITLE
BlockRay.from(Entity ...).end() incorrectly returns absent

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeAPI#841]
Primarily for @DDoS 

So I decided to use BlockRay's functionality to determine the interaction point when digging blocks. When I break a block, I call BlockRay.from(playerEntity).end() which should return the spot hit from my eye location to the block. I verified that I'm getting the eye location data.

**Comment by Bammerbom** [comment]
Probarly implementation issue, not an api issue

**Comment by DDoS** [comment]
You need to add an "only air" filter. Else it just passes through all blocks without finding a mismatch to stop on.

**Comment by Zidane** [comment]
@DDoS 

Thanks for making me feel dumb as usual. Will give this a shot when I get home this evening.

**Comment by Zidane** [comment]
@DDoS 

Still getting an absent

http://pastie.org/pastes/10415902/text

blockRay.end().get()

**Comment by DDoS** [comment]
If you're tracing without any block in sight (the default range being 1000 hits), you will get absent. Also block tracing won't be fully accurate until I implement block AABBs, which is waiting on Properties.
