### ISSUE TITLE
Delete & Copy world methods causing crash

### ISSUE THREAD

**Issue by prowakizashi** [SpongePowered/SpongeAPI#843]
Hello,

Using the methods  Server.deleteWorld() and Server.copyWorld() cause a crash. Is it a known problem ? Or maybe I don't use it in the good way.

I saw a previous Issue about these features which was closed. I hoped it would work :(.

**Comment by AlphaModder** [comment]
I believe those methods are not implemented in Sponge's current version yet, along with much of the API. You'll have to wait until they are to test whatever you're using them for.

**Comment by ST-DDT** [comment]
Can you post a stacktrace of your crash?
Usually if something is not implemented that is used by plugins then the server does not crash.

**Comment by Bammerbom** [comment]
1. This is an implementation issue, not an api issue.

2. Probarly not implemented.

**Comment by prowakizashi** [comment]
Indeed, this is an implementation issue, the methods are not implemented. It doesn't cause a crash but an error. I was tired, I guess, sorry.

I will wait until they are implemented :).
Thanks
