### ISSUE TITLE
Change execute method on TaskBuilder

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/SpongeAPI#844]
Currently, `TaskBuilder`'s `execute` method takes a `Runnable`. The problem with this is that one cannot use the `Task` that's executing the `Runnable` to i.e. cancel it.

I'd suggest changing the method signature to the following:
```java
TaskBuilder execute(Consumer<? super Task> executor);
```

With this approach we have full access to the executing `Task` context object.

**Comment by JBYoshi** [comment]
Why not have both `Runnable` and `Consumer` support?

**Comment by TheRaspPie** [comment]
This would also be an option. We could just make the method with `Runnable` a default method like this:

```java
default TaskBuilder execute(Runnable runnable) {
    return execute(task -> runnable.run());
}
```

**Comment by ST-DDT** [comment]
Sounds like a nice addition.
This would simplify the task cancellation.
Is there anything else besides the task cancellation, you could do with the task?
Because if you only need it for the cancellation you could probably solve that with a boolean return statement as well. (Supplier)

**Comment by TheRaspPie** [comment]
You could of course get the properties of the `Task` like name, delay, interval, check for asynchronous execution and get the issuing plugin.
I think that some plugins may have a use for it, i.e. to reschedule a task with the same issuing plugin without having direct access to a plugin instance.

I don't know if we should use three methods that do the same thing.
Maybe @gabizou could state on that.

**Comment by ST-DDT** [comment]
> I don't know if we should use three methods that do the same thing.

The supplier was just an example if there were no other use cases than cancelling.

> I think that some plugins may have a use for it, i.e. to reschedule a task with the same issuing plugin without having direct access to a plugin instance.

You don't have to store the plugin in each task anymore, this is probably one of the most noticeable changes, however if you have to cast the plugin all the time most of the pros will be destroyed by the reduced readability.

Maybe the method should be changed to:
````java
<T> T getOwningPlugin();
````

However I'm not sure whether I would use it due to readability reasons anyway.

> You could of course get the properties of the Task like name, delay, interval, check for asynchronous execution and get the issuing plugin.

IMO its very unlikely that the task needs details such as `delay` or `interval` or check for `asynchronous execution`.
If you need the `delay`/`interval` to reschedule, then you could have used a repeating task in the first place or you have strange logic involved in your code.

**Comment by TheRaspPie** [comment]
What if for example you want to register a listener if a task ends?
Then you'd need the plugin instance, but you won't cast it to the specific class as the `EventManager` just requires an `Object`.

I don't think that we would need to have something like that:
`Task#toBuilder`. What's really the problem here is that we sometimes want to create a new `TaskBuilder` or access existing tasks.
Therefore it would be useful to just add a `SchedulerService getScheduler()` method to the `Task` interface as it's bound to a specific scheduler anyway.

**Comment by Zidane** [comment]
I like the changes proposed here. @simon816 can you make the additions when you have time?

**Comment by TheRaspPie** [comment]
@Zidane Which proposed changes? There are multiple conflicting ones...

**Comment by Zidane** [comment]
@TheRaspPie 

The original changes to have task available in the execute method.

**Comment by simon816** [comment]
Added in https://github.com/SpongePowered/SpongeAPI/commit/9ae1a308a3e140074f57687fe245d2d3f785eb46
