### ISSUE TITLE
Consistent providing of global access

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/SpongeAPI#845]
# Why is global state bad?

In SpongeAPI there's no concept of global access to the `Server` reference like in Bukkit.
Instead, we use Dependency Injection and let the injector inject the dependencies we need into the constructor or a field.
Normally, this is a good thing - it helps keeping the code clean and separates different parts - if it is done consistently.

In the API, there are many places where this concept was broken in favor of usability:
For instance look at the `MessageSinks` class. There are two different ways one could get the currently logged in players.

Here you need a `Server` reference somehow, i.e. by calling `Game#getServer`.
```java
List<Player> players = server.getOnlinePlayers();
```

Here you don't need one:
```java
@SuppressWarning("unchecked")
List<Player> players = (List<Player>) MessageSinks.toAllPlayers().getRecipients();
```

Of course the second solution is pretty ugly, but it works!
The first solution requires the `Server` context and the second one does not.
Therefore the `MessageSinks` class must hold any static state which is bad for reasoning in a multi-threaded environment.

# The situation with Minecraft

As you noticed, I said <b>multithreaded</b> environment. But Minecraft still lives in its single-threaded world in which we don't have to think about race conditions or deadlocks.

So my question is:
Why do we do the half thing and let people pass the `Game` object to every new listener?
If even many classes in API rely on getting initialized by the server implementation through reflection, we can make the `Game` object - and other objects that are always there - globally available.

Bukkit had its `Bukkit` class which provided the static `getServer()` method to get the current running server instance and static equivalents to all methods on `Server` for convenient access.

And to be honest: The developers will get tired of passing objects anyway and create their own singleton in main class.

This is not particularly bad for small plugins which can be rewritten in hours or days.
Of course, big plugins like WorldGuard may want to pass the objects around to get better decoupling, but it should be the plugin's own decision.
We shouldn't force them to not use global state, particularly because we also use singletons in the implementation ourselves.

EDIT: The other option would of course be to remove all global state completely and fully rely on Dependency Injection. In the end, the decision is made by @gabizou anyway.

**Comment by JBYoshi** [comment]
I don't believe the `MessageSinks.toAll()` case was intended.

**Comment by AlphaModder** [comment]
It's not impossible that cleanroom clients/servers wishing to implement Sponge are multithreaded, so we can't count on running on a single thread. Another question is, where is MessageSinks's implementation getting it's Server anyway? Surely it still needs to call `getOnlinePlayers` on some level? Seems to me that when someone actually tries to implement that method, they'd bring up the issue of it needing a `Server`.

**Comment by ST-DDT** [comment]
Even in multithreaded environments. There shouldn't ever be more than one `Server` at a time.

**Comment by JBYoshi** [comment]
Right. They get it by getting the singleton "official" `Server` implementation (`MinecraftServer.getServer()`).

**Comment by simon816** [comment]
It actually may throw an NPE if called too early (before the server is started), because `getConfigurationManager()` will return null.

This was discussed __long__ ago, I doubt we will change the design pattern now (e.g. see #134)

**Comment by TheRaspPie** [comment]
@AlphaModder Right, the implementation will need to have a `Server` object or some player list. This on the other hand implies that global state MUST be used to implement SpongeAPI.
Any implementation must hook into the pseudo-enum classes and replace the `public static final NAME = null` fields with actual objects.
So if we already rely heavily on that state, why can't we just also make the `Game` object statically available? Or at least provide a method like `getGame()`. We don't really need the duplicated static methods Bukkit had in its `Bukkit` class.

**Comment by ryantheleach** [comment]
@ST-DDT That kind of blanket statement makes me wonder how realms works... Whether it has a codebase where multiple servers *could* be running, or whether they are seperated into seperate JVM's.

**Comment by ST-DDT** [comment]
@ryantheleach Please excuse me for not scrying any possible/unlikly future and not stating the obvious.

The minecraft server code that is officially released has way to many static components to be useful for a many server/jvm setups. So it either has to run on multiple jvms or you have to rewrite the entire MC server code. From my experience companies usually try to avoid such kind of development, since its very expensive. Especially since you don't have the community and the excessive snapshot testing. In comparison systems running in separate containers (Docker, VMs.. etc) or far easier to create and scale. We use a system like that in our company too and it just works. It creates virtual servers on the fly and it destroys them if they are no longer needed.

But that is just an assumption, lets get back to the facts.

The SpongeAPI in its current state itself does not support multi-server setup.
Reasons: Game.getServer()  returns a single instance. The service system does not support multiple servers. Events are not totally suited to support multi server setups. Plugins don't have the ability to support multi server setup in one jvm, due to missing server references etc, static references...
Of course this could change, but that is a) a future change and b) IMO not likely to happen (because it complicates the simple plugin creation).

**Comment by Sleaker** [comment]
I just want to point out that using a MessageStinks.toAll() statically, vs server.getOnlinePlayers() has nothing to do with whether or not either of the methods being called/used are compatible in a Multi-threaded environment. Static access does not inherently invalidate multi-threaded use cases, just like the usage of server.getAllPlayers() doesn't immediately validate multi-threaded use cases.  The fact that you have to use MinecraftServer.getServer() even invalidates the argument simply on the basis that it's also using static access to begin with.

The request for consistency across the API is the only thing that should really be considered here, and if Sponge actually want's to keep allowing MessageSinks to pull a list of players to send messages to, or if it should be forced back onto the server.

**Comment by JBYoshi** [comment]
My only proposal for fixing this issue is to remove `MessageSink.getRecipients()`.

**Comment by ST-DDT** [comment]
You kind of need that method to allow Mods/OPs to eavedrop into conversations that may run privately.
Or at least you need to be able to remove or add a certain player to that (copied) sink.

For example:
BadGuy: `/pm AnotherPlayer You are an ****` 
the server/mod may want to punish the BadGuy for sending this
````java
@Listener
public void onChat(ChatEvent) {
    if (!event.getSink().getRecipients().contains(adminPlayer)) {
        adminPlayer.sendMessage(event.getMessage());
    }
}
````

**Comment by JBYoshi** [comment]
Maybe the `MessageSinks` methods could be moved into `Server`?

**Comment by Sleaker** [comment]
@JBYoshi - how? MessageSinks are stateful in the given example. you can't move that off to the server. The server doesn't track who is getting what messages.

**Comment by JBYoshi** [comment]
@Sleaker Not `MessageSink`, `MessageSink`**`s`**.

**Comment by TheRaspPie** [comment]
This issue isn't just about `MessageSinks`. That was just an example. There may be other places where such things happen, but it may not be so obvious. An example would be the many Factory classes for classes like `Text`, `CustomInventory` etc. Why do we need an external factory for `Text` if it's really pure and really doesn't need any implementation detail?

**Comment by JBYoshi** [comment]
Mojang's JSON is an implementation detail.

**Comment by simon816** [comment]
As of https://github.com/SpongePowered/SpongeAPI/commit/3dceade464ef176549570aeacef2b42baed93270 there is now a global `Sponge` class which satisfies the concerns here.
