### ISSUE TITLE
Weather effect entitys

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/SpongeAPI#855]
To spawn in lightning with forge you would need to do 
```
world.addWeatherEffect(lightningBolt);
```
Sponge has no way to call this method yet, meaning that spawning a lightning bolt with the default spawn entity method will only spawn the damage entity, and not the actual strike,

Spongeforge workaround
```
		Optional<Entity> lightningBolt = target.getWorld().createEntity(EntityTypes.LIGHTNING, target.getLocation().getPosition());
		if(lightningBolt.isPresent())
			target.getWorld().spawnEntity(lightningBolt.get(), Cause.empty());
		//spawn the strike
		((net.minecraft.world.World)target.getWorld()).addWeatherEffect((net.minecraft.entity.Entity) lightningBolt.get());
```

**Comment by clienthax** [comment]
Implemented under
https://github.com/SpongePowered/SpongeAPI/pull/865
https://github.com/SpongePowered/SpongeCommon/pull/191

**Comment by Zidane** [comment]
Implemented in https://github.com/SpongePowered/SpongeCommon/pull/191
