### ISSUE TITLE
[idea] Add a method to save a chunk.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#856]
Add a method to save a chunk.
Example: `chunk.save()`

**Comment by ST-DDT** [comment]
This could be hard to implement since you always save entire region files and saving other chunks as well.
Developers will not expect that.

**Comment by varrix** [comment]
As for them not expecting that, couldn't documentation solve the "not knowing" aspect of such a method?

**Comment by ST-DDT** [comment]
Sure documentation can solve a lot of things.

Lets try to create the documentation it help the team to decide on the use of this PR and help them add it.

How can the plugin author determine which chunks are saved and which are not?
Remember the API has no clue about region files and stuff alike. Returning a list of chunks that have been saved as well may be an option as well. Any other ideas?

What method signature have you thought of?

**Comment by Zidane** [comment]
I need more information.

Why do you want to save an individual Chunk? What would be a use case?

**Comment by Azatik** [comment]
Later I will try to describe the problem.

**Comment by Azatik** [comment]
I wrote code
```
    @Listener
    public void onPlayerDeath(DestructEntityEvent event) {
        if (event.getTargetEntity() instanceof Player == false) {
            return;
        }
        Player player = (Player) event.getTargetEntity();
        Location loc = player.getLocation();
        loc.setBlockType(BlockTypes.BEDROCK);
        Text msg = Texts.of("You died.");
    }
```

The problem was this:
The player died;
The unit is installed;
The player sees that he is;
Press button "Respawn";
The player comes to the place of death;
No block.

I would like to solve it by chunk.save(). But the problem did not show himself.

I started to test. I wrote the command "/kill" many times.
I found that the block does not appear in only one point.
This point in the The End, where a player is appear when jumping into the portal.

**Comment by varrix** [comment]
@Azatik 
I am unsure what the issue you're describing is.

    @Listener
    public void onPlayerDeath(DestructEntityEvent event) {
        if (!(event.getTargetEntity() instanceof Player)) {
            return;
        }

        Player player = (Player) event.getTargetEntity();
        Location loc = player.getLocation();
        loc.setBlockType(BlockTypes.BEDROCK);
        Text msg = Texts.of("You died.");

        player.sendMessage(msg);
    }

Worked perfectly fine for me: http://prntscr.com/8nwpo7

**Comment by Azatik** [comment]
No errors.

**Comment by gabizou** [comment]
I don't think that has anything to do with the chunk but rather Minecraft defaulting to wiping the obsidian platform each time you enter the end. Try placing something else, falling through the void, going back to the end, and seeing if it is still there. (Don't place the block in code, just place it by hand.).

**Comment by Azatik** [comment]
@gabizou Your assumptions are correct. This protection obsidian platform.

**Comment by varrix** [comment]
@Azatik 
If it's that important to have this functionality, you could store the blocks and every time a player goes through it wait a couple ticks and set those blocks.

**Comment by Azatik** [comment]
@varrix good idea.

**Comment by Zidane** [comment]
I don't want to just expose saving of a chunk...Worlds do this. I'd need a valid usecase.
