### ISSUE TITLE
OwnableData vs TameableData

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeAPI#857]
Currently the definitions of those `DataManipulator`s is somewhat redundant. Both represent values that are identical in Minecraft, as the tamer of an entity is also considered its owner. Thus they cannot be both retained in their current form (even with the changes proposed on #850).

**Option 1: Remove TameableData**
This would make taming implicit: If `OwnableData` is present on a tameable Entity, it is tamed. 

**Option 2: Remove OwnableData**
A different approach would retain `TameableData` and make it store the tamer. Taming will also become implicit, Since the owner ID in `TameableData` is optional, this would allow for tamed animals to be ownerless. This approach would require a new data manipulator to store the player represented by a player `Skull`, since `TameableData` would not be applicable.

**Option 3: Change TameableData**
`TameableData` will only store a `Boolean` denoting if the animal is currently tame. There is no longer a stored UUID for the tamer, only for the owner (reflecting minecraft internal naming).
With this approach, `OwnableData` and `TameableData` are fully independent of each other, ~~as is the underlying data in the NBT representation.~~ The problem with this solution is that wolves and ocelots are only considered tamed if they have an owner

I'll perform whatever changes are agreed upon in #850 and implement them in SpongePowered/SpongeCommon#178

**Comment by ST-DDT** [comment]
I have a question regarding option 3:
If `TameableData` is set to false, does this also remove the owner?
And if an owner is set in `OwnableData` will this set tamed to true?

**Comment by saladoc** [comment]
No, those values are (should be) totally independent.

**Comment by Aaron1011** [comment]
@saladoc: One issue with option 3 is that the values aren't really independent, at least for `EntityTameable` subclasses. Only the owner UUID is stored to NBT, and its presence or absence implies the tamed state.

**Comment by saladoc** [comment]
@Aaron1011 Are you sure? In the EntityTameable class those are stored as separate values. I assumed they get written to NBT the same way.

**Comment by saladoc** [comment]
After having thought about it it seems to me that everything relating to taming entities should be handled by `TameableData`. This would basically eliminate the need for `OwnableData` since it would now only apply to skulls. For Skulls however it would be a different matter as they would not be *owned*, but merely represent a player. I will therefore, if noone objects, change my PR to 
* remove all effects of OwnableData on `EntityTameable`s and `EntityHorse`s
* rename `OwnableData` to `RepresentedPlayerData` and have it store a `GameProfile` again

**Comment by gabizou** [comment]
Alright @saladoc go ahead and make the changes or let me know if I need to.

**Comment by saladoc** [comment]
I'll do it ;)
