### ISSUE TITLE
Transform toString does not contain position

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#858]
[`Transform`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/Transform.java)'s [`toString`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/Transform.java#L408) method does not contain the [`position`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/Transform.java#L62).

**Comment by Rain336** [comment]
But Location gets added which has the [position](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/Location.java#L697)

**Comment by DDoS** [comment]
toString() should use getLocation() because location is lazily generated by that method. Using the variable means it can be null.

**Comment by Zidane** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/0818ebcea8deefa7287c9011b8fef6b11950aae4

@DDoS . Thanks again for that.
