### ISSUE TITLE
Add Plugin Instance to Guice Injection

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeAPI#864]
This is a feature I've seen before in Forge mods:

```
@Instance
public static MyPlugin instance;
```

Would be nice to re-create this functionality since I've seen multiple people set their instance all over the place.

**Comment by saladoc** [comment]
[The guice injector for plugins allows you to inject your plugin instance as a Singleton](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/guice/SpongePluginGuiceModule.java#L63)

So they could just go

    @Inject 
    private MyPlugin plugin

and just inject the plugin wherever needed.

**Comment by Zidane** [comment]
Totally didn't realize that @saladoc.

Thanks for the notice!

**Comment by JBYoshi** [comment]
Wait... does this work with `static` fields?

**Comment by Zidane** [comment]
@JBYoshi  @saladoc 

This doesn't work for statics. That is a requirement for this.

**Comment by Kiskae** [comment]
@Zidane It can be implemented by calling `requestStaticInjection(<PluginClass>)` within the `configure()` method of the guice plugin module

**Comment by Kiskae** [comment]
As a follow up, I did testing on the injection order and using `requestStaticInjection` causes resolving at that exact moment for any instances that need to be injected into static variables.
This means that if the plugin needs an instance that isn't yet available during the `configure()` call will cause a CreationException. I believe `requestStaticInjection` is handled by the parent injector, so any objects made available for the individual plugins would not be available.

**Comment by Minecrell** [comment]
I don't really like the idea of having modifiable instance field in the class which can be modified by every other class, seems like very bad design.

Generally, this doesn't seem much harder to setup and won't expose a public field:
```java
private static MyPlugin instance;

public static MyPlugin getInstance() {
    return instance;
}

public MyPlugin() {
    instance = this;
}
```

**Comment by Zidane** [comment]
After thinking about it, I agree that this is a little unsafe and does smell of bad design. I'm aware FML allows it but that doesn't mean its okay.
