### ISSUE TITLE
new interface Located, implemented by both LocatedSource and Entity

### ISSUE THREAD

**Issue by vorburger** [SpongePowered/SpongeAPI#866]
I found myself writing some helper code which I wanted to work for both a LocatedSource and an Entity (see https://github.com/vorburger/SwissKnightMinecraft/commit/b7ba52ca2e699058707e1d9f98ef1f40ea126838#diff-8284ad004f85958defdff90728651876L42 for background). 

Both LocatedSource and Entity have a Location and a World, but share no common interface. So I sent a wish for built-in Duck Typing in Java (https://en.wikipedia.org/wiki/Duck_typing#In_Java), alas the magic fairy didn't grant my wish, so instead I'm filing this proposal - thus how about:

    interface Located {
        Location getLocation();
        World getWorld();
    }

    interface LocatedSource extends Located, CommandSource

    interface Entity extends Located, ...

Close if this is stupid for some reason, or +1 if this would be useful (I'll send a PR).

If there already is an interface for something that is a Location in a World, perhaps that could be used.

**Comment by AlphaModder** [comment]
`Located` sounds sorta strange. `Localizable`, perhaps?

**Comment by JBYoshi** [comment]
@AlphaModder `Localizable` sounds a bit like internationalization (localization). Maybe `InWorld`? In that case, `Location` could also implement it.

**Comment by Deamon5550** [comment]
> If there already is an interface for something that is a Location in a World, perhaps that could be used.

Location is already a 'location in a world'...

Your spawn helper could just be changed to take a Location<World> as a parameter with no World parameter and called as

```java
Entity entity = ...;
SpawnHelper.spawn(EntityType.class, entity.getLocation());

LocatedSource source = ...;
SpawnHelper.spawn(EntityType.class, source.getLocation());
```

**Comment by vorburger** [comment]
@Deamon5550 I see.. tx! (Applied in https://github.com/vorburger/SwissKnightMinecraft/commit/cf55c33e53f19e34abe13f1c5af7f5bc599fa4b3)
