### ISSUE TITLE
Eclipse compile error

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeAPI#867]
https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/command/args/GenericArguments.java#L1127

"Type mismatch: cannot convert from List<Object> to Iterable<String>"

From what I can tell, Eclipse is interpreting the lambda as returning an `Object` instead of a `String`.

**Comment by Zidane** [comment]
@bloodmc uses Eclipse and isn't getting that error.

Are you out of date @JBYoshi ?

**Comment by JBYoshi** [comment]
...Apparently not. Will report back once the updates finish.

**Comment by JBYoshi** [comment]
Yep, updating fixed it. Thanks!

**Comment by simon816** [comment]
I just encountered the same error. For reference, here's the eclipse bug report https://bugs.eclipse.org/bugs/show_bug.cgi?id=463728

It's fixed in Eclipse 4.5.1 ('Mars.1')
