### ISSUE TITLE
Add asExtent/asAnotherExtent/etc to Location

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeAPI#868]
@bloodmc originally reported this

Given a Location such as

```
Location<World> myWorldLoc;
```

To get a Chunk object at that location, he must do:

```
myWorldLoc.getChunk(pos);
```

This is a tad cumbersome, especially since if we do the reverse:

```
Location<Chunk> myChunkLoc

myWorldLoc = myChunkLoc.getExtent().getWorld();
```

...is just as annoying. I'm thinking we can make this a tad bit simpler by adding a helper method to Location:

```
<O extends Extent> asExtent(Class<O> clazz);
```

What this would do is take the Location object and based on the Extent passed in it would convert the Location's Extent to it at that position.

What do you think @DDoS ?

**Comment by DDoS** [comment]
Can you give an example use?

**Comment by ryantheleach** [comment]
Wouldn't it also need to be optional? Some extents might not be able to contain a location.

**Comment by Zidane** [comment]
@ryantheleach 

Correct.
