### ISSUE TITLE
Missing Property for isSolidCube()

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeAPI#874]
`BlockType.isSolidCube()` was [removed recently](https://github.com/SpongePowered/SpongeCommon/commit/ade5be54710210537b554035a2f3ecf27855c01e#diff-d179e73cf2eb09c7ce3e959a06ce846eL110) to be replaced with a `Property`, but I can't find any property for it. What happened to it?

@gabizou

**Comment by simon816** [comment]
I'm going to take a guess and say it's `MatterProperty`

**Comment by JBYoshi** [comment]
@simon816 Nope. `MatterProperty` says what type of block it is (solid, liquid, or gas). The implementation code basically says:
```java
if (block == Blocks.air) {
    return GASEOUS;
}
if (block instanceof BlockLiquid) {
    return LIQUID;
}
return SOLID;
```

Glass, for example, would be `SOLID`, but `isSolidBlock()` would return `false`. (`isSolidBlock()` basically returns whether you could place an attachable block, such as a torch, on that block type. You can't place torches on glass.)

**Comment by JBYoshi** [comment]
@gabizou Thanks!
