### ISSUE TITLE
DataQueryable Interface Proposal

### ISSUE THREAD

**Issue by me4502** [SpongePowered/SpongeAPI#878]
(This is probably full of mistakes - I may or may not be drunk)

The data API by @gabizou is very useful and and allows for the complete abstraction of data.

My proposal is to use a SQL-Like query system on interfaces.

My proposed interface would be something like DataQueryable, and things that store items containing data implement it.

This can include a chunk, where you can query for the DataHolders, which are blocks, tile entities and entities.
The same can be done for an inventory, which would just include itemstacks.

This would not just be limited to the standard 'get all with this data' query, it would allow more complex matching such as, 'all with this data, with this key being X, but not including that data'

I'll probably elaborate when I can think clearly.

Edit:

This was also meant to be used like the Java 8 Streams API.

**Comment by ST-DDT** [comment]
Sounds like an nice idea, but please don't add things like SQL-strings to the API.
SQL has the heavy drawback, that it must be parsed (and each server does this differently), its not type safe and thus will cause errors during runtime.

> This was also meant to be used like the Java 8 Streams API.

Something like this?
````java
chunk.query(Living.class) // <- I assume you will and should never search for Entities, Blocks and TileEntities at the same time.
    .filter(input -> !input.supports(Keys.AGE))
    .filter(Matcher.eq(Keys.HEALTH, Keys.MAX_HEALTH).negate())
    .forEach(input -> input.remove());
````

This is already possible for chunks, but using the same queries everywhere would be nice.
IIRC the inventory API has already something similar but a far light weighted.

PS: Please note that implementing a `Stream` like API yourself is a PITA². 
(I did this already for one of my projects.)

**Comment by me4502** [comment]
Yeah, something like that.

By SQL-Like, I meant capabilities like that of SQL, definitely not a syntax like SQL.

**Comment by gabizou** [comment]
@me4502 Can you please provide some code examples of what this would add and usages?
