### ISSUE TITLE
Replace java.io.File with java.nio.file.Path

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeAPI#880]
In Java 7+ we have the [`java.nio.file.Path`](https://docs.oracle.com/javase/tutorial/essential/io/pathClass.html) class as a more modern replacement for `java.io.File`. It's generally more abstracted and has some additional options, but at the end both APIs have their advantages and disadvantages. In most APIs this is not commonly used yet, but Oracle generally [recommends using the newer `Path` class instead of `File` for newer projects](https://docs.oracle.com/javase/tutorial/essential/io/legacy.html).

When working with the Path API you'll always need a `File` object from time to time, for that there is `Path.toFile()` and `File.toPath()` which allows mixing these APIs.

While we can easily support both for dependency injection we should probably decide which API to use in Sponge and internally for the implementation. I personally prefer the newer Path API because in some fields it is much easier to work with.

**Comment by progwml6** [comment]
the nio apis when used properly can also be much faster than the older java io apis

**Comment by zml2008** [comment]
I prefer working with the Path API -- and for Configurate 3.0 (the java8 update) I'm switching over to using primarily that file API.
