### ISSUE TITLE
Add support for generating all missing chunks in a world within WorldBorder

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/SpongeAPI#882]
Currently, there is no way for a plugin to "pre-generate" their world in order to improve performance for players. I suggest we add an option similar to the WorldBorder plugin for Bukkit that allowed a plugin to fill all missing chunks within a WorldBorder. More info can be found here
http://dev.bukkit.org/bukkit-plugins/worldborder/pages/commands-and-permissions/#w-the-fill-command

@DDoS can you add support for this?

**Comment by JBYoshi** [comment]
Might not be a good idea, though... unless you change the border size, you'll end up having to generate 14 *trillion* chunks.

**Comment by Azatik** [comment]
Good Idea.

@JBYoshi Adequate administrator will not allow this.

**Comment by liach** [comment]
How about the function of removing existing chunks far enough that will not be loaded when the player is at the border?

**Comment by bloodmc** [comment]
@JBYoshi As @Azatik stated, the intended use is for admins that know what they are doing by setting a reasonable WorldBorder limit. A server that has no limit is asking for trouble.

**Comment by DDoS** [comment]
I'll try and make this non-blocking with proper output to the console so the admin can shutdown the server normally, stoping the process, if he accidentally uses a border that is too large.

**Comment by boformer** [comment]
Isn't this something that could be handled by a plugin?

All that is needed is a ``generateChunk(x,z)`` method.

**Comment by bloodmc** [comment]
Many things in our API can be handled by a plugin but that doesn't mean it shouldn't be added.
