### ISSUE TITLE
Maven API Repository out of date.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeAPI#884]
I set up my project through Grade/Maven using the 2.1 API Snapshot, but that hasn't seemed to been updated in a long time. The last update was on 13 Sept 2015. 
(Info from https://repo.spongepowered.org/maven/org/spongepowered/spongeapi/)

I'm not sure if the Maven Repository is (supposed to be) on a CI Server or not, but the binaries are far ahead of the API, causing things to break, and I'm not sure what to do. (other than building from source and using that)

From what I can tell, SpongeForge is now hosted on the Minecraft Forge file server. Has the maven repository been migrated there as well?

**Comment by simon816** [comment]
The `2.1-SNAPSHOT` is up to date
https://repo.spongepowered.org/maven/org/spongepowered/spongeapi/2.1-SNAPSHOT/maven-metadata.xml

**Comment by gravityfox** [comment]
That is really odd, because I'm not getting blasted with the update.

**Comment by gravityfox** [comment]
Alright, I give up, I deleted my gradle caches and it decided it wanted to redownload. Yay...
