### ISSUE TITLE
FishingEvent.Stop vs FishingEvent.Finish?

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeAPI#885]
I'm working on implementing some events. `FishingEvent.Stop` is implemented, but `FishingEvent.Finish` is not. Since `FishingEvent.Finish` is not documented, what is it for?

**Comment by Kiskae** [comment]
I imagine its a 'finally' event. So the calling order is Start -> [Hook | Stop] -> Finish

**Comment by Aaron1011** [comment]
I'm currently working on implementing and improving `FishingEvent`. It should be done soon.
