### ISSUE TITLE
Create a Way to get a Vector with the Direction a Entity is Facing

### ISSUE THREAD

**Issue by hsyyid** [SpongePowered/SpongeAPI#888]
There are two ways this could be done (that seem the most logical):

**Option 1:**
Extract some of the logic from BlockRay, and make it available to plugins, specifically the code to convert an entity's pitch and yaw to a vector pointing in the proper direction.

**Option 2:**
Modify getRotation()

**Comment by DDoS** [comment]
`Transform.getRotationAsQuaternion().getDirection()`

**Comment by ryantheleach** [comment]
Which is great for people who understand what a Quaternion is, or that they need to get the Transform first, this could be a lot easier to access.

**Comment by DDoS** [comment]
A Quaternion is just a representation of a rotation. Don't bother with the 4D complex number magic inside, all that matters is the class API. If all you know that a Quaternion has useful rotation stuff, it's easy to find the solution.

**Comment by hsyyid** [comment]
Thanks
