### ISSUE TITLE
Document interchangability of plugin instance and plugin container

### ISSUE THREAD

**Issue by Xfel** [SpongePowered/SpongeAPI#892]
Currently, the PluginManager.fromInstance method is implemented in a way (in SpongeCommon) that it will directly return the passed object if it is an instance of PluginContainer. This means that most API methods taking a plugin instance also work when passing the corresponding PluginContainer, which saves the need for a map lookup. Now, however, I'm not sure this will work in any case; and it's not documented, but I propose to change this to be mandatory. Writing code like this one: https://github.com/SpongePowered/SpongeCommon/pull/200/files#diff-f20b6463a294676a67754232f9e63f61R135
is a bit unnecessairy as the getInstance() on the plugin container could simply be omitted.

**Comment by simon816** [comment]
So what you're asking is for `PluginManager#fromInstance` to mention it will return the same `PluginContainer` object if the container is passed into the method?
Or are you asking for methods with `Object plugin` to document in `@param plugin` that the object can be a `PluginContainer` also?

FYI Just did a quick search and there's about 30 `Object plugin` arguments in the API currently

**Comment by Zidane** [comment]
In api-8, plugin container is required everywhere.
