### ISSUE TITLE
Method to determine if calling from "main" thread

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#897]
A method added to `Game` or `Server` to determine if the current thread is the main thread will be useful, as well as not requiring the plugin dev to figure it out by thread name (thread names are an implementation detail).
similar: https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/Server.java#L805-L817

**Comment by simon816** [comment]
Should be already possible with `game.getPlatform().getExecutionType()`

**Comment by kashike** [comment]
`MinecraftServer.getServer().isCallingFromMinecraftThread()` / `Minecraft.getMinecraft().isCallingFromMinecraftThread()` is what we want a check for, not the platform/execution type.

also, as a note: [getEffectiveSide](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/common/FMLCommonHandler.java#L193-L201) does not cover all cases and will return wrongly in certain cases.

**Comment by gabizou** [comment]
Without presenting any valid use cases, closing this for now.

**Comment by kashike** [comment]
An example use case, as seen in Bukkit plugins, is checking the thread before processing something:
```java
        if (Sponge.getGame().getPlatform().isMainThread()) {
            executor.submit(runnable);
        } else {
            runnable.run();
        }
```

**Comment by gabizou** [comment]
@kashike That code is not a valid use case. Having `isMainThread()` is just asking for people who don't understand how to sanely handle their own threads to make their threads async with poor architecture for re-capturing the main thread.

**Comment by Deamon5550** [comment]
Not having this method isn't going to stop plugins from writing terrible threading code, but it sure does help when writing more abstract threading infrastructure like the linked issue from @kashike just now. I don't see the harm now.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeAPI/commit/f247c803524f44f2dc1431c976dca87c5789d2e9
