### ISSUE TITLE
Cancellable death event

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#898]
Before processing a death, call an event that will allow plugins to cancel the death. Plugins would be responsible for ensuring the entity can be alive (teleporting to safety, setting health, etc), and sponge would do validation post-event (check health, etc) and either allow the cancel, or ignore it.

**Comment by Deamon5550** [comment]
For most (all?) causes of death there is already an event other than the death event that is thrown and is cancellable eh? eg. if they walk into a cactus and die before the death event theres going to be a damage event thrown, so if you want them to not die the correct thing would be to cancel the cause event not the symptom event so to speak.

**Comment by wizjany** [comment]
i feel like this has come up so many times and it's the same thing every time.

**Comment by gabizou** [comment]
@wizjany And practically, the reasonings are all well understood, I'm having the understanding that people seriously are saddled with their previous experiences of "oh, this person is considered dead, i'll just cancel it and respawn them somewhere." when in reality this should be achieved without having the death actually occur and have some intelligent design to handling damage that will kill you.

**Comment by kashike** [comment]
@Deamon5550 That does, however, assume that there **was damage**.

@gabizou explained it for the most part - the point of this is to prevent the death logic from being processed, and allow the plugin/mod to handle it accordingly.

**Comment by wizjany** [comment]
Don't even know where these previous experiences would be coming from. Bukkit's death event wasn't cancellable, and forge has a "Death" event for fatal damage which is cancellable, and a "Drops" event when the entity actually dies, that only prevents drops when cancelled. there has never been a way to bring entities back to life after they are flagged for death.

Even if you want to change "death logic" there are other events to handle various aspects of it (respawning, drops, death message, etc).

**Comment by kenzierocks** [comment]
@kashike There's always damage for a death. `/kill` would be done as a full health damage.

**Comment by ryantheleach** [comment]
What actually happens in the minecraft engine on death? If the death never occurs at all, then plugins need a way of firing off all (most? some?) of that logic that would have occurred. From what I can tell 99% of usecases for cancelling death is really just not showing the death screen to the client. 

Is there a way to build that into the API?

**Comment by gabizou** [comment]
I believe that with the discussion, the death event shouldn't be cancellable. @Zidane, do you agree?

From what I gather, the death event is already when the game has processed the act of dying. There is enough processing with regards to how death is handled such that if a plugin wishes to "cancel" it, they should just listen for the `DamageEntityEvent` and cancel if the final "health" of the entity will reach the point where death is inevitable and simply handle their own logic accordingly.

**Comment by kashike** [comment]
@gabizou To clarify, this is a request for a **new** cancellable "pre-death event", that is called **before** any death logic is processed, and before death event. Cancelling the "death event" is not what this is for.

**Comment by gabizou** [comment]
Still, the only event that is thrown before a death event is a `DamageEntityEvent`.

**Comment by gabizou** [comment]
@kashike I think it best that plugins just listen to the `DamageEntityEvent` and calculate if the entity is going to die, and if it will, cancel. That's the easiest way to get around it and avoids confusion of a "cancellable" death event.

**Comment by ryantheleach** [comment]
What about an event for when the player receives the death screen? It's not cancelling death, the death still happens. It's cancelling the death GUI and providing an instant respawn location?

**Comment by wizjany** [comment]
er, is that even sent by the server?

**Comment by bloodmc** [comment]
After much thought, having DestructEntityEvent.Death cancellable would cause far more issues than help. As gabizou stated above, if you want a "pre" death event then simply listen to DamageEntityEvent and check if health is 0 , and if so cancel the damage. This is far more efficient than cancelling a death event and rolling back things like health, position etc.. With that said, I do see a benefit of having "non-living" entity deaths cancellable since you wouldn't be able to determine if the non-living entity would destruct during the DamageEntityEvent. We would need a new sub interface since I can't make the base DestructEntityEvent be cancellable.

**Comment by simon816** [comment]
I think the only thing we could do to assist people checking if an entity _will_ die is adding a method to `DamageEntityEvent` called `willCauseDeath()` which just does a simple subtraction to determine if the entity would die.

**Comment by Zidane** [comment]
@simon816 

I agree and thought of doing that as well. Simplest solution imo.

**Comment by Deamon5550** [comment]
And then you can use some of those fancy new event filters (#927) to make it even simpler hehe

**Comment by kashike** [comment]
The only required change to make this work is to make `DestructEntityEvent.Death` extend `Cancellable`, since `DestructEntityEvent.Death` is of type `TargetLivingEvent`. Forge fires the `LivingDeathEvent` for [`EntityLivingBase`](https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch#L68-L70), [`EntityPlayer`](https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch#L124-L126), and [`EntityPlayerMP`](https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/entity/player/EntityPlayerMP.java.patch#L50-L52), which is mapped to `DestructEntityEvent.Death`.

**Comment by Zidane** [comment]
@kashike 

Again, we are not supporting cancellable death events. This decision is final.

**Comment by kenzierocks** [comment]
Do we care about canceling mods using `setDead`? Or is that also under `DamageEntityEvent`?
