### ISSUE TITLE
Run event in case of cancellation.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeAPI#900]
I'm writing a plugin to the graves.
If a player dies in a private area, it will not break the grave.
How to allow the player to break the grave in a private area?
![2015-11-04_20 59 19](https://cloud.githubusercontent.com/assets/10154956/10944110/4d599dc2-8339-11e5-803a-f3dfe1bba4da.png)

**Comment by Zidane** [comment]
A question: What do you define as a "private area"?

**Comment by Zidane** [comment]
Also, the Listener annotation has:

https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/Listener.java#L59

Simply specify it as false and you'll get cancelled events.

**Comment by Azatik** [comment]
Private area - Anti Grief plugin

**Comment by Azatik** [comment]
How to use "ignoreCancelled()"

**Comment by kenzierocks** [comment]
`@Listener(ignoreCancelled=true)`. Read up on annotations :)

**Comment by Azatik** [comment]
I will write in a different way.
I want execute an event when his cancels other plugin.

**Comment by Zidane** [comment]
So, just to decipher this:

You only want to handle this event if it was cancelled via the AntiGrief plugin?

**Comment by Azatik** [comment]
Allow to break blocks on the territory of the World Guard (any Anti Grief Plugin).

**Comment by Zidane** [comment]
@Azatik 

Then what you want to do is adjust your Order to POST as well as ignoreCancelled = false

https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/Order.java#L111

Then, if your criteria is met, setCancelled(false)

**Comment by Azatik** [comment]
I understood.I write the result of sixteen hours.

**Comment by Azatik** [comment]
<h4>Report.</h4>

I created two events.
EventBreakBlock:
```
public class EventBreakBlock {   
    @Listener
    public void onEventBreakBlock(ChangeBlockEvent.Break event) {
        if (event.getCause().first(Player.class).isPresent()) {
            Player player = (Player) event.getCause().first(Player.class).get();
            Text msg = Texts.of(TextColors.DARK_RED, "Action prohibited.");
            player.sendMessage(msg);
            event.setCancelled(true);
            }
        }
    }
```

EventBreakBlockAllow:
```
public class EventBreakBlockAllow {
    @Listener(ignoreCancelled=false, order = POST)
    public void onEventBreakBlockAllow(ChangeBlockEvent.Break event) {
        if (event.getCause().first(Player.class).isPresent()) {
            Player player = (Player) event.getCause().first(Player.class).get();
            Text msg = Texts.of(TextColors.DARK_GREEN, "Action allow.");
            player.sendMessage(msg);
            event.setCancelled(false);
        }
    }
}
```

Result:
![2015-11-04_23 12 13](https://cloud.githubusercontent.com/assets/10154956/10947482/f81db184-8349-11e5-822b-123210857917.png)

**Comment by gabizou** [comment]
@Azatik you don't need to cast with `event.getCause().first(Player.class).get()` since passing the class will already make the return type a `Player`. I'll test locally and see if I can reproduce.

**Comment by gabizou** [comment]
@Azatik I ran locally and the event isn't cancelled, so the break is occurring. I'm not seeing the problem in this case.

**Comment by Azatik** [comment]
@gabizou It works fine.
Mini Problem: output message "Action prohibited." from event EventBreakBlock.

**Comment by gabizou** [comment]
@Azatik yes, because the listener executed, and cancelled the event. Of course, the second listener will un-cancel it such that it's now not cancelled. This is why it's important for world protection plugins to not only have a listener for the early events to check protections, but a secondary post listener that checks if the event is still cancelled. 

Your act of un cancelling the event in POST however is probably bad practice as at that point you're in a race condition of whichever listener gets the event first in the chain.

**Comment by Azatik** [comment]
@gabizou There are better variants?

**Comment by gabizou** [comment]
Could use [`BEFORE_POST`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/Order.java#L102). `POST` is intended for block monitoring plugins like Prism where they just log the activities etc.

**Comment by gabizou** [comment]
Otherwise, this isn't an issue it seems.

**Comment by Azatik** [comment]
I agree.
