### ISSUE TITLE
SpongeAPI's very own Color class

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#901]
So far, we've been using `java.awt.Color` for any color type that could be 16 million colors. However, the biggest issue is that `Color` can easily be extended, let alone the fact that it's `java.awt`. The largest issue is having to constantly convert between `DyeColor`, `Color`, and soon, `MapColor` which honestly is more of a pain to have to write static util methods to convert between the three.

**Comment by gabizou** [comment]
@Zidane I'm leaving the decision on adding this up to you, just give me the go ahead and it'll be done ;)

**Comment by Zidane** [comment]
I agree, you have a go.

**Comment by Deamon5550** [comment]
Finally...

**Comment by gabizou** [comment]
This will be closed with #903, all discussion should take place there.

**Comment by Zidane** [comment]
No need to have this open when there is a PR.
