### ISSUE TITLE
HideFlags api

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeAPI#905]
Add a way to apply "HideFlags" to an item.

Information about HideFlags: http://minecraft.gamepedia.com/Tutorials/Command_NBT_Tags#Items

**Comment by gabizou** [comment]
@Zidane thoughts on how this might be expanded to "hide" stuff from other mods? Rather, do you have an idea on whether it *could*?

**Comment by JBYoshi** [comment]
@gabizou It should work with mod items as well.

**Comment by gabizou** [comment]
@JBYoshi The question is whether it will. Mods do funny things ;)

**Comment by Bammerbom** [comment]
I think most mods use lores, and if they don't it is in the "others" catogory.

**Comment by me4502** [comment]
I'm looking at adding this, I've got two different options for doing it.

The first one is the simplest, which is having a data manipulator that has a field for each of the hide-able items. The drawback is mods adding extra hide-able things, such as power levels for IC2, etc.

The second idea is to make a psudo-enum, that has a list of hide-able items, and a datamanipulator that has isHidden(HideableItem), or whatever, and a setHiden(HideableItem, boolean hidden)

**Comment by Aaron1011** [comment]
@me4502: I don't think it's worth considering mod-add flags, since we'd have no way of detecting them. At best, we'd be able to see that a particular bit was set, but we wouldn't know any information about it beyond that.

**Comment by gabizou** [comment]
Yeah, just focus on the vanilla bit mask.
