### ISSUE TITLE
(De)serializing itemstacks/inventories

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeAPI#906]
Add a way to serialize and deserialize itemstacks and inventories using the SerializationService.

**Comment by gabizou** [comment]
[`ItemStackBuilder#fromContainer(DataContainer)`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/inventory/ItemStackBuilder.java#L112).

Inventories are a whole separate thing and something that the `SerializationService` will probably not handle, as discussed with @Mumfrey: Inventories are transactional, and while their contents are easily serializable, serializing the transactions to reconstruct an inventory is the tricky if not impossible part.

**Comment by Bammerbom** [comment]
The problem is I need to store a player's inventory to the config, and restore it later on.
Would the best way to do that be just serializing all itemstacks and save them with the according slot?
What would be the best way to convert a slot to text?

**Comment by gabizou** [comment]
Well, until the inventory part is resolved, one way you can go about it is query for each `Slot` and get the coordinate of it and serialize the itemstack and the coordinate.

**Comment by gabizou** [comment]
Closing this as `ItemStack`s are `DataSerializable` already and considering all the information available in an `ItemStack`, it's quite possible that you can deserialize this any which way you want.
