### ISSUE TITLE
Add PotionSplashData

### ISSUE THREAD

**Issue by ZephireNZ** [SpongePowered/SpongeAPI#907]
Currently there's no way to make a potion be a splash potion. 

I suggest adding `PotionSplashData` - it would simply be a boolean, and would make it so any `PotionEffect`s added to a potion would be splash potions.

**Comment by gabizou** [comment]
Just to note, this is going to be likely marked deprecated as soon as 1.9 lands as splash potions are new item types in 1.9.

Am I correct in saying this, @Zidane?

**Comment by Zidane** [comment]
@gabizou 

I think so but I'd confirm with @Grum .

**Comment by ryantheleach** [comment]
Wouldn't applying the data manipulator to a potion type just return a potionsplash type?

**Comment by ZephireNZ** [comment]
Currently, splash potions are the same item as regular potions - their damage values determine what type they are.

This would abstract that out into a data manipulator.

As mentioned, 1.9 will make the splash potions their own item. In that case, we would have to alter the dataprocessors to instead change the item's type and deprecate the manipulators.

**Comment by ryantheleach** [comment]
Yeah, I just don't understand why you would need to deprecate them? Surely converting between potions and splash potions is still useful?

**Comment by grum** [comment]
Potions in 1.9 will be defined by their container: Items.POTION, Items.SPLASH_POTION and Items.LINGERING_POTION, their actual potion-type will be stuffed in NBT along with custom color (overrides) or any additional effects.

**Comment by ZephireNZ** [comment]
^ Using a data manipulator for potions after 1.9 doesn't really fit the contract of data manipulators. As the name suggests, they edit the data associated with a particular type, be it an entity, block or item. This makes sense in 1.8, where splash is additional data on top of potions. But in 1.9 splash is just another item type, and should be changed as such.

**Comment by ST-DDT** [comment]
IIRC Then we would have issues with stone/wood types as well.

**Comment by grum** [comment]
Correct, but that is for 1.10 :)

**Comment by ryantheleach** [comment]
Then I no longer understand why Data Manipulators were a good idea in the first place. I thought the entire point of having it this way was for situations like this?

**Comment by ZephireNZ** [comment]
Data manipulators for blocks are a bit grey as damage values for those are removed - but for items/entities they're a much better way of working with what would often require NBT fiddling.

**Comment by ST-DDT** [comment]
Maybe we should move away from the 1:1 mc block and item types and use more general approaches.

Dirt, Stone, Ore, Axe, Shovel...

**Comment by gabizou** [comment]
Ok, so the decision then is that the manipulator will be added solely for a Boolean toggle on a potion item.

**Comment by gabizou** [comment]
> Then I no longer understand why Data Manipulators were a good idea in the first place. I thought the entire point of having it this way was for situations like this?

Because, the level of abstraction that allows continuity and avoids the entire use of "damage" values all around, let alone representing various data that can be shared across multiple `DataHolder` types. This issue isn't about the reasoning for the Data API, this issue is closer to "How do we handle data that is being removed in the next release?". To which, a few of us have already spoken about this afternoon.
