### ISSUE TITLE
Mutable Explosions in Post Event.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#912]
https://github.com/SpongePowered/SpongeAPI/blob/6ec0106ae12c349729c5f6c08e51d5f3b696df80/src/main/java/org/spongepowered/api/event/world/ExplosionEvent.java#L57 ExplosionEvent.Post exposes the Explosion, which is mutable.
https://github.com/SpongePowered/SpongeAPI/blob/6ec0106ae12c349729c5f6c08e51d5f3b696df80/src/main/java/org/spongepowered/api/world/explosion/Explosion.java#L52 Yet it's exposed in the post event. 

Anything changing it at this stage, would likely not result in any world changes, yet anything reading the explosion afterwards would see the changes.

**Comment by ryantheleach** [comment]
One solution would be to only return a defensive copy to plugins whenever they request the explosion if it's past the point where the explosion can be safely mutated. But if this is indeed the case it needs careful documentation, and would seem counter to other parts of the API

**Comment by simon816** [comment]
I'm thinking making the `Explosion` interface immutable and only in `ExplosionEvent.Pre` is there a `setExplosion(Explosion explosion)` method.
