### ISSUE TITLE
No way to find the source of drops from DropItemEvent.Destruct

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#916]
DropItemEvent.Destruct fires once for the whole explosion, with a cause identifying it.

But there is no way to work out from what blocks/entities each of the drops originated from.

**Comment by gabizou** [comment]
If I'm understanding you correctly, you're looking for some sort of 
`Map<BlockSnapshot, List<ItemStackSnapshot>` for blocks and likewise for `EntitySnapshot`s?

**Comment by wizjany** [comment]
yes. need a way to figure which item(s) drops from which block/entity.

**Comment by gabizou** [comment]
@bloodmc I know it's partially viable to figure this out, at least in vanilla circumstances, but I'm not 100% sure with mods.

**Comment by simon816** [comment]
Shouldn't the event be fired for every block destroyed?
That way each block is known, and the cause can have the `Explosion` so you know it was caused by an explosion

**Comment by bloodmc** [comment]
@simon816 Yes, It would function just like a normal ChangeBlockEvent.Break but I haven't had a chance to refactor it all. I plan on doing it soon.

**Comment by simon816** [comment]
@bloodmc able to do this in the next 2 days?

**Comment by Azatik** [comment]
How to get a block of this event?
Event.getCause when the block broke:
`[onDropSign]Cause[{Name=Source, Object={EntityPlayerMP['azat'/409, l='world', x=115,00, y=63,00, z=286,00]}}]`

**Comment by windy1** [comment]
Can verify this is now possible.

```java
@Listener
public void onDropBlock(DropItemEvent.Destruct event, @First BlockSpawnCause cause) {
}
```
