### ISSUE TITLE
Way more attractive way to create items & more..

### ISSUE THREAD

**Issue by CreepsterLGC** [SpongePowered/SpongeAPI#917]
So I know that Sponge is still in development. However, today my plugin broke once again because 

> ItemStackBuilder.class

changed to

> ItemStack.Builder.class

So why not allowing developers to use ItemStack.create(..., ...); Same for other builders obviously. Having a .create(); function would keep plugins way more stable besides that fact that this is a waaay more beautiful way to code. I know that Sponge provides a huge compatibility with other mods but that doesn't mean that everything has to be that complicated as it is right now.

Think about new devs trying to get into Java / Sponge. Why not giving them a great and solid start with

> ItemStack.create(ItemTypes.DIAMOND, 64);

instead of

> game.getRegistry().createBuilder(ItemStack.Builder.class).itemType(ItemTypes.DIAMOND).quantity(64).build();

Also, you could allow developers to use ItemStack.create(String, Integer); trying to transform the String to an ItemType. If no type could be found it just returns null.

I just want to make developing with Sponge more enjoyable as it is right now.. Don't get me wrong but there are currently a bunch of functions which surely could be way easier! Thanks for your hard work though. I love Sponge!

Regards,
Creep

**Comment by simon816** [comment]
That would mean `ItemStack` would have to be a class and in the API almost everything should be an interface.

**Comment by ST-DDT** [comment]
> So why not allowing developers to use ItemStack.create(..., ...); Same for other builders obviously. Having a .create(); function would keep plugins way more stable

Builders don't change without a reason. The current change is caused to standardize the API and will probably never happen again. 

> that fact that this is a waaay more beautiful way to code

Yes, now its beautiful, but if MC ever changes its ItemStack feature then you might end with a dead API method, that everybody uses, with no way to revive that thing.

> Also, you could allow developers to use `ItemStack.create(String, Integer);` trying to transform the `String` to an `ItemType`. If no type could be found it just returns null.

Well, I'm pretty much against the "I accept a string and guess what it should be" way of dealing with it.
First of all what does that string include? `WOOL:5` or `WOOL:RED`? Are all subtypes supported or only a few? How about plugin ones? If we go in this direction I would prefer something like this `ItemStack.create(ItemType.of(String), int)`.

Also this will probably have different results for different server impls.

But in general I wouldn't put this to the API. Especially if it is that easy to write a plugin internal helper class for those features.

@simon816 
We have Java8 so we can add static methods to interface classes.

**Comment by kashike** [comment]
I'd personally like to see something like this, for all builders:
`ItemStack.Builder.start().itemType(ItemTypes.DIAMOND).quantity(64).build();`

**Comment by ST-DDT** [comment]
@kashike Yes, that sounds nice.

Or even shorter `ItemStack.builder().itemType(ItemTypes.DIAMOND).quantity(64).build()`

**Comment by CreepsterLGC** [comment]
Well, no matter what building an ItemStack gets changed to, the best way for devs is probably that they create their own little utils. I mean sh*t.. If its really that complicated then PLEASE feel free to forget about the suggestion and keep on creating functions where you need a cinema screen to keep them in one line.

**Comment by Zidane** [comment]
@CreepsterLGC 

Thanks for the feedback. I'll work with @gabizou a bit and figure out ways to "trim the fat". The consolidation of the builders was the first step.

**Comment by gabizou** [comment]
Closing with the recent additions provided by 3dceade464ef176549570aeacef2b42baed93270
