### ISSUE TITLE
player.sendMessage sends messages on different lines

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/SpongeAPI#925]
I get the reason behind it but it isn't javadoc'd and honestly I feel that `sendMessage(Text... messages)` should send it as one message and we should have a `sendMessages(Text... messages)` that sends it as multiple messages.

Tagging @gratimax and @Minecrell

**Comment by kashike** [comment]
I disagree - combining them should be up to the person sending the `Text`s.

**Comment by Deamon5550** [comment]
If `sendMessage` sends each Text in a new message then at a minimum I think it should be renamed to `sendMessages`. If there is a `sendMessage` then it should only send one message.

**Comment by Zidane** [comment]
I agree with @Deamon5550 and want the change made.

**Comment by kashike** [comment]
I'm not sure completely removing `sendMessage` was the best thing to do. It would have been better to change the signature and add `sendMessages`.

**Comment by simon816** [comment]
@Zidane should a singular sendMessage be added too?
