### ISSUE TITLE
Add Locales

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/SpongeAPI#929]
Right now the ability to get locales such as Klingon or Pirate is a bit of a PITA. I understand why we are using Java's locales but at the same time our goal is to make things simple for plugin developers so we should at least offer our own pre-defined locales for languages that Java's locales do not have by default.

Referencing my original issue: https://github.com/SpongePowered/SpongeForge/issues/419

**Comment by ST-DDT** [comment]
Shall I create a PR for this to push this forward?

**Comment by Minecrell** [comment]
@ST-DDT Thanks, but I have that already added locally.

**Comment by Minecrell** [comment]
Added in #988
