### ISSUE TITLE
Make Human accept Causes when opening/closing inventories

### ISSUE THREAD

**Issue by SocraticPhoenix** [SpongePowered/SpongeAPI#930]
## Proposition 
Currently the [Human] (https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/Human.java) Interface has methods for opening and closing inventories. I'd like to propose that those methods be changed so that they accept a Cause object, in addition to their already existing parameters.

## Reasoning 
Given that [InteractInventoryEvent](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/item/inventory/InteractInventoryEvent.java) extends CauseTracked, I feel that developers should be able to specify the reason they are closing/opening an inventory. For example, if a developer is designing an Inventory Menu utility, and wants to fire an event when the Player quits the menu, how is the developer going to know if the Player is quitting, or if the inventory has been closed from within his/her own code?

#### Note
Sorry if what I've said makes no sense, or I'm uniformed about some other, pre-existing solution. If either are true, please let me know in the comments.

**Comment by Zidane** [comment]
@SocraticPhoenix 

Good idea and makes sense :). It'll come in the Phase 1 AI framework branch :).

**Comment by simon816** [comment]
@Zidane Phase 1 AI framework came and went. Was this forgotten?

**Comment by TheRaspPie** [comment]
With this reasoning those methods could be added to all API methods that in turn fire events.
Maybe we can somehow abstract this out for every state-changing API method? (no idea how)

**Comment by SocraticPhoenix** [comment]
When this was created, CauseTracked was still a thing. But yes, I do agree with your point @TheRaspPie. But it would certainly be difficult to update to, and the default cause also needs to be an option.

**Comment by Aaron1011** [comment]
Merged in https://github.com/SpongePowered/SpongeAPI/pull/1106.
