### ISSUE TITLE
Move all builders into their associated built interfaces

### ISSUE THREAD

**Issue by simon816** [SpongePowered/SpongeAPI#932]
The following builders are not following the new convention to have the builder interface within the target interface they build:

Data builders won't be changing:
~~`org.spongepowered.api.data.manipulator.DataManipulatorBuilder`~~
~~`org.spongepowered.api.data.manipulator.ImmutableDataManipulatorBuilder`~~
~~`org.spongepowered.api.data.value.ValueBuilder`~~
~~`org.spongepowered.api.data.DataTransactionBuilder`~~
~~`org.spongepowered.api.data.ImmutableDataBuilder`~~
~~`org.spongepowered.api.service.persistence.DataBuilder`~~

PaginationBuilder doesn't "build" an object in the same way other builders do
~~`org.spongepowered.api.service.pagination.PaginationBuilder`~~

* [ ] `org.spongepowered.api.entity.ai.task.AITaskBuilder`
* [x] `org.spongepowered.api.item.inventory.transaction.InventoryTransactionBuilder`
* [x] `org.spongepowered.api.text.selector.SelectorBuilder`
* [x] \(`org.spongepowered.api.text.title.TitleBuilder`)
* [x] \(`org.spongepowered.api.text.TextBuilder`)
* [x] `org.spongepowered.api.util.ban.BanBuilder`
* [x] `org.spongepowered.api.world.WorldBuilder`

**Comment by gabizou** [comment]
Data related stuff will stay as is.

**Comment by simon816** [comment]
OK I'll remove them from the list

**Comment by Minecrell** [comment]
Actually, what is with the AI task builders?

**Comment by gabizou** [comment]
`AITaskBuilder` will not be moving into `AITask` as that makes some assumptions that all `AITask`s can be built given certain conditions.
