### ISSUE TITLE
Ghasts so problem with ghast fireballs and ghast :/

### ISSUE THREAD

**Issue by Cleardragonf** [SpongePowered/SpongeAPI#935]
![image](https://cloud.githubusercontent.com/assets/13158079/11449715/e0f4793a-9545-11e5-88e8-30850fd767a4.png)

This is what happens when a ghast shoots a fireball and it explodes....no known ways to fix have tried everything but there is no known fact.  Please assist

**Comment by gabizou** [comment]
Can you clarify what the issue is exactly in an issue on the SpongeCommon repo?

**Comment by simon816** [comment]
This is from the thread https://forums.spongepowered.org/t/solved-explosion-types/10028/
I'll open an issue on SpongeCommon as I can confirm what was discussed there.
