### ISSUE TITLE
Add a way to parse Date/Time using GenericArguments

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/SpongeAPI#939]
Same reasoning as #937, but we need a standardized way to specify the times in our `/tempban` commands.

~~My suggestion for a format would be https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_LOCAL_DATE_TIME . (You can still use a date format by adding it to the current date)~~ See below for new format.

**Comment by ryantheleach** [comment]
I'm not entirely sure you do need a standardized way across plugins, and the fact it needs to be human friendly pretty much rules out any of the formal standards.

I'd highly suggest using durations, they are time zone independent, and people already understand them. Worst comes to worst the user needs to do some math to convert a date to a duration, or you can offer an alternative command that accepts a date.

**Comment by CrystalMageX** [comment]
How about instead of the ISO format, let's use like `10Y5M3W2d12h9m13s` representing "10 years, 5 months, 3 weeks, 2 days, 12 hours, 9 minutes, and 13 seconds," and allow any part of it to be omitted, and typed in any order. 

That would be much more **human friendly**. On the other hand, it would something that I just made up and is **not standardized**, so it would be another thing to remember.

**Comment by Deamon5550** [comment]
In my opinion this is not something we should provide, there are many many different standards for dates, times, date-times, durations, etc. Rather than try and support them all I think we should just leave this up to plugins and they can use whatever date parsing that they want (there are many libraries both standard and not for parsing times).

**Comment by Zidane** [comment]
I agree with @Deamon5550 , this needs to be left up to plugins. Everyone has their preference.
