### ISSUE TITLE
Getter and Setter for Entity Velocity

### ISSUE THREAD

**Issue by Gamecube762** [SpongePowered/SpongeAPI#942]
A much valued and needed feature for many plugins and developers. With this, many cool features can be made: Jump-pads, Jetpacks, Barriers, Tornadoes, Water Fountains, Pseudo Gravity, and more!

**Comment by ST-DDT** [comment]
You can already get it using [`VelocityData`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/manipulator/mutable/entity/VelocityData.java).
````java
entity.get(VelocityData.class)
````

**Comment by gabizou** [comment]
This is already available through the Data API methods.

```java
entity.offer(Keys.VELOCITY, new Vector3d(-1.0d, 200.0d, 0.0d));
```

**Comment by Gamecube762** [comment]
Ah, thank you, I'll have to look more into the Data API then.
