### ISSUE TITLE
"Chat channels"

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#943]
A feature I'm currently working on requires the ability to send a different message per-receiver in message-related events (`ClientConnectionEvent.Join`, for example), however with the current message sink-based system I have no way to control this from the implementation, since the message sink controls that. I basically need:
```java
        channel.sendMessage(new BiFunction<Text, CommandSource, Text>() {
            /**
             * @param text The original message
             * @param viewer The viewer of the message
             * @return The message that the viewer will see
             */
            @Override
            public Text apply(Text text, CommandSource viewer) {
                return Texts.of("Some text specific to ", viewer.getName());
            }
        });
```
The result of the function would be inserted into a template/format, as defined by the channel, or sent alone if no template/format is defined.

I talked to @gratimax and @ST-DDT a bit about this - gratimax suggested something like chat channels, which would depend on a text formatting PR (https://github.com/SpongePowered/SpongeAPI/pull/808 and/or https://github.com/SpongePowered/SpongeAPI/pull/835) being pulled.

**Comment by ST-DDT** [comment]
I could imagine the following setup (using my PR #808)
**`MessageEvent`**
````java
void setTemplate(Text);
````
**`MessageSink`**
````java
// This method would no longer be overridable
// Since all customizations should be done using Placeholders and their Transformers
 public final void sendMessage(Text template, Function<String,?> context) { 
    for (CommandSource target : getRecipients()) {
        target.sendMessage(Texts.formatBuilder().with("target", target).with(context).apply(template));
    } 
}
````
**Example usage**
Plugin: Add group prefix:
````java
Text template = event.getTemplate();
// template = ${sender}: ${message}
template= Texts.formatBuilder()
        .with("sender", Texts.of(
                Texts.placeholder(Transformers.valueForKey("sender").map(myPlugin::getGroupPrefix)),
                Texts.placeholder("sender")))
        .apply(template);
// template = ${myPlugin.getGroupPrefix(sender)}${sender}: ${message}
event.setTemplate(template);
````

Server code:
````java
MessageEvent event = new MessageEvent(....)
Sponge.postEvent(event);
event.getMessageSink().sendMessage(event.getTemplate, KeyValueFunction.builder()
        .set("sender", event.getSender())
        .set("senderDisplayNameForFn", sender::getDisplayNameFor)
        .set("message", event.getMessage())
        .build());
````

Here an example with the join event:
````java
Text joinMessage = Texts.placeholder(
        Transformers.valueForKey("senderDisplayNameForFn")
        .join("target", (fn, target) -> Texts.of(
                new SpongeTranslation("multiplayer.player.joined.renamed"), 
                fn.apply(target)
        ))
);
// Alternative:
Text joinMessage = Texts.placeholder(
        Transformers.valueForKey("sender")
        .join("target", (sender, target) -> Texts.of(
                new SpongeTranslation("multiplayer.player.joined.renamed"), 
                sender.getDisplayNameFor(target)
        ))
);

event.setTemplate(joinMessage);
````
However it won't be easy for plugins to add a group prefix in there in this example. (unless they change the join message template themselves.)

**Comment by kashike** [comment]
Do note that this isn't just for message events, it is for all chat.

**Comment by ST-DDT** [comment]
Yes, but most chats (events) work the same. 
* One sender
* One message
* n targets

**Comment by ryantheleach** [comment]
I thought that this could be accomplished by having a message sink transform the message when it sends it to each player?

**Comment by kashike** [comment]
@ryantheleach re-read the original comment

**Comment by ST-DDT** [comment]
The issue with MessageSinks is that  you cannot remove or add recipents without replacing the message sinks and thus any context and formatting methods that are required are lost.

**Comment by ryantheleach** [comment]
Unless you chain or wrap them creating a pipeline.

**Comment by kashike** [comment]
Closed in https://github.com/SpongePowered/SpongeAPI/commit/3699c1e59aa6de3b9afd978607ff0293c384ea2c
