### ISSUE TITLE
Timings should use the plugin id

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#946]
Currently, timings are currently using the plugin name in many places ([here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/SpongeTimingsFactory.java#L91), [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/SpongeTimingsFactory.java#L93), [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/SpongeTimingsFactory.java#L191), [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/SpongeTimingsFactory.java#L193), [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/TimingsExport.java#L166), and [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/TimedEventListener.java#L57) - though I may have missed one). To be consistent, we should be returning the plugin id instead - we can provide the plugin name [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/TimingsExport.java#L166) to provide a friendly name that can be used, if necessary.

**Comment by ST-DDT** [comment]
Isn't that an implementaion issue and thus belongs in Common?

But I agree returning the id (or the plugin instance) everywhere would be better than a none-unique? name.

**Comment by kashike** [comment]
I could have sworn I made this in common. Oooooooooooops.
https://github.com/SpongePowered/SpongeCommon/issues/307
