### ISSUE TITLE
ServiceManager refactor

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeAPI#949]
Following the cleanup of services, `ServiceManager` needs some additional changes:

- [ ] Allow indicating whether a service should be replaceable (all Sponge services will be). This has potential repercussions for `ServiceReference`
- [ ] Way to get all registered services from the service manager, allow with their associated `PluginContainer`

**Comment by gabizou** [comment]
Closed in https://github.com/SpongePowered/SpongeAPI/commit/af8c2904846c133e8f84602a0e8532ade07318ac
