### ISSUE TITLE
ProjectileHitEvent ?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#953]
Is there an event for when a projectile hits or collides with an entity? I was trying to implement arrows bouncing off of slimes back at the person who fired the arrow, but realized that the https://github.com/SpongePowered/SpongeAPI/blob/e429b6b6e9945bfe1c2566c54ff6016508149e2a/src/main/java/org/spongepowered/api/event/entity/CollideEntityEvent.java as it currently stands, just allows you to filter what entities are being affected/considered during a collision, and doesn't tell you what is colliding with the entities, unless it's hidden inside a cause.

**Comment by DarkArc** [comment]
You should be able to use InteractEntityEvent and check for a Cause of Projectile.class.

**Comment by bloodmc** [comment]
@ryantheleach https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java#L470

**Comment by ryantheleach** [comment]
If it wasn't working 12 days ago it's working now.
