### ISSUE TITLE
Add a way to force non-bed spawns with RespawnLocationData

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/SpongeAPI#955]
Hello all, I've been working on a Graveyards plugin and have noticed that currently with [RespawnLocationData](https://jd.spongepowered.org/org/spongepowered/api/data/manipulator/mutable/entity/RespawnLocationData.html), there is no way to force a non-bed spawn location.  Whenever I offer a non-bed location it is rejected and the player is told that their home bed was missing or obstructed and they are respawned at the default spawn point in the world.  I've been told that forge had a force spawn position flag, is there anyway would could implement a similar feature in sponge?

Thanks!

**Comment by JBYoshi** [comment]
Something like `/spawnpoint`?

**Comment by Zerthick** [comment]
@JBYoshi yes, I'm trying to essentially have the same functionality as ```/spawnpoint```.  I suppose I could just have the console execute the command on the player whenever I want the spawnpoint to change, that just didn't seem like a really clean solution.

**Comment by gabizou** [comment]
This sounds like something the implementation should handle maybe? Or possibly a dual map of locations based on beds and another one based on non bed locations?

**Comment by Zerthick** [comment]
@gabizou Right, I wasn't sure if this merited a change in the API itself, or could just be delegated to an implementation detail.  Either way, I think it's something we should support.  Since you can only have one spawnpoint per world anyway, why not just have a single map of spawnpoints, keyed by UUID and Location as they are now, and just have some sort of flag for forcing non-bed locations, or should there even be a flag at all, should non-bed spawns just be enforced by default?  Not sure.

**Comment by simon816** [comment]
Since forced spawn is a thing in both vanilla and forge I think it would be good to represent it in some way in the API.

In forge, it's represented as two Maps, a `Map<Integer, BlockPos>` for positions and `Map<Integer, Boolean>` for forced spawns. So in the API it could be just like that or maybe a `MapValue<UUID, Tuple<BlockPos, Boolean>`?

**Comment by Zerthick** [comment]
That's seems like a good solution, it's clean and easy to set/unset.  I like the idea of keeping it all in one map, rather that splitting the flags into a separate one.

**Comment by ST-DDT** [comment]
Isn't it possible to overwrite it in the death/respawn event?
[RespawnPlayerEvent](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/event/entity/living/player/RespawnPlayerEvent.java#L56)
If using that event it should overwrite any setting/limitation anyway,

If you are referring to setting that outside of the death/respawn event, then there are several things to consider.
The `World`/area the `Player` is currently in as it might affect the respawn location.
(For example arena worlds/areas)
Those will also collide with any "force" flag set.

> So in the API it could be just like that or maybe a
`MapValue<UUID, Tuple<BlockPos, Boolean>>`?

Use the Data API for that.

**`DefaultSpawnData`**
* `getLocation() : Value<Location>`
* `isForced() : Value<Boolean>`

**Comment by ryantheleach** [comment]
Do you mean Location<? extends Extent> or Location<World>? Wouldn't it be better to use a Vector3d/Transformation + world?

After reading the initial issue, I would have been expecting a event to be fired with enough information, that I could either force the spawn at the previous bed location by listening and working out that it was a failed bed spawn, find the original bedspawn of the player, and force the bed spawn to happen by setting the location back to the original bed location found on the player data.

>Since forced spawn is a thing in both vanilla and forge
I don't really understand the need for multiple forced spawn locations, or how Vanilla already has a concept of it past using enderportals after the dragon fight.
