### ISSUE TITLE
Add from(T) to ResettableBuilder

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#960]
Currently, #758 is partially resolved where all builders are inherently resettable (and they're even simplified), but now comes the question on whether builders should have a `from(T)` method, whether it can be intrinsically extended so that there's more generic builder types to allow such `from` methods.

Currently, it's very usable for the cases:

- `ItemStack`
- `ItemStackSnapshot`
- `EntitySnapshot`
- `BlockSnapshot`
- `TradeOffer`
- `ParticleEffect`
- `Explosion`
- `FireworkEffect`

There are bound to be others, but of course, the question remains that usually, builders are not modifiable in that elements cannot be removed once added to a builder (unless `reset()` is called), so the use cases of these `from(T)` methods would involve strictly adding onto the builder.

**Comment by ST-DDT** [comment]
> so the use cases of these from(T) methods would involve strictly adding onto the builder.

IIRC `from(T)` was also intended as starting point in the game registry.
IMO `from(T)` should include the `reset()` call. Because the merge would be really ugly to specify. Although I agree that you can state in the javadocs that `from(T)` does not call `reset()` internally, but to clarify that I would call the method `addFrom(T)` or `setFrom(T)`. But it still does not feel well that way.

**Comment by simon816** [comment]
An alternative approach would be to have `builder()` on the interface, in the same way that [`Text.builder()`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/Text.java#L201) is. Either way, it should be consistent

**Comment by JBYoshi** [comment]
@simon816 That would conflict with the static `builder()` method.
```java
public interface ItemStack {
    static interface Builder { /* ... */ }
    static Builder builder() { return Sponge.getRegistry().createBuilder(Builder.class); }
    Builder builder() { return ItemStack.builder().from(this); }
}

**Comment by ST-DDT** [comment]
@JBYoshi You can rename either the static or the instance method easily. (as long as it before Beta)

**Comment by Zidane** [comment]
@ST-DDT 

I'll stress that beta doesn't mean we are done breaking...it means we'll try to keep it to a minimal :P.
