### ISSUE TITLE
Zombies breaking door

### ISSUE THREAD

**Issue by Cleardragonf** [SpongePowered/SpongeAPI#962]
When i place them infront of oak doors they dont break down the doors...kinda would like this as it would allow players to have monsters interact with blocks around them

**Comment by JBYoshi** [comment]
What difficulty are you on? Zombies can only break doors on Hard/Hardcore.

**Comment by Cleardragonf** [comment]
hard.  Still not working even double checked

**Comment by JBYoshi** [comment]
I've been testing, and I found that the ability to break doors is controlled by an NBT tag `CanBreakDoors`. If set to 1, it allows the zombie to break doors. I've set up a command block mechanism to check if it's possible for a zombie with `CanBreakDoors` to be spawned, and I'll report back with what happened.

**Comment by Cleardragonf** [comment]
Thank you, if i could get the code for that it would be awesome because from it i'm hoping to find a way to implement them for breaking blocks or irondoors etc :+1:

**Comment by JBYoshi** [comment]
`CanBreakDoors` only works for wooden door blocks. You can't use it to have other blocks broken.

**Comment by ST-DDT** [comment]
@Cleardragonf In order to allow you zombies to break iron doors you have to write your own AI-class/overwrite the existing AI-class.

If you have access to minecrafts decompiled sources then have a look at `net.minecraft.entity.ai.EntityAIBreakDoor`.

**Comment by Zidane** [comment]
Closing this as its a non-API issue.
