### ISSUE TITLE
Redirect messages in message events to alternate outputs.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#963]
https://www.reddit.com/r/minecraftsuggestions/comments/3do0n4/chat_warnings_like_you_can_only_sleep_at_night/

Players have multiple streams / sinks / channels of chat, represented by [ChatTypes](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/chat/ChatTypes.java).

Is it possible to redirect messages to players to an alternate ChatType?

I would have thought that the MessageSinks would contain this responsibility, however the method responsible is marked final, and MessageSinks deal with CommandSources not players.

**Potential usecases** :  Making messages from staff / admins show to users, regardless of their chat preferences by setting it to System, "fixing" vanilla warnings to display in the action slot instead of clogging chat, redirecting chat to the action bar whilst a plugin has focus via a conversationapi like conversation.

**Comment by kenzierocks** [comment]
CommandSources can be players.

**Comment by ryantheleach** [comment]
For the record, this is the closest I could currently approximate, has several issues.

1. Messages in game for "can't sleep monsters nearby" don't seem to fire MessageSinkEvents.
2. Removing the players from the sink, would cause logging plugins to assume the player never received the message, should the event have been cancellable instead, it would also indicate that the message never arrived, which is simply not true, it's just been delivered by an alternate means.

```
package TopSuggestion;

import org.spongepowered.api.command.CommandSource;
import org.spongepowered.api.entity.living.player.Player;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.Order;
import org.spongepowered.api.event.command.MessageSinkEvent;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.text.Text;
import org.spongepowered.api.text.chat.ChatTypes;
import org.spongepowered.api.text.sink.MessageSink;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Plugin(id = "ChatRedirect", name = "ChatRedirect", version = "0.1-SNAPSHOT")
public class ChatRedirect {

    @Listener(order = Order.LATE)
    public void onChatEvent(MessageSinkEvent event){
        MessageSink oldSink = event.getSink();
        Iterable<CommandSource> recipients = event.getSink().getRecipients();
        List<Player> players = new ArrayList<Player>();
        Set<CommandSource> sources = new HashSet<CommandSource>();
        recipients.forEach(commandSource -> {
            if(commandSource instanceof Player){
                players.add((Player) commandSource);
            } else {
               sources.add(commandSource);
            }
        });
        event.setSink(new MessageSink() {
            @Override
            public Iterable<CommandSource> getRecipients() {
                return sources;
            }

            @Override
            public Text transformMessage(CommandSource target, Text text) {
                return oldSink.transformMessage(target, text);
            }
        });

        players.forEach(player -> {
            player.sendMessage(ChatTypes.ACTION_BAR, oldSink.transformMessage(player, event.getMessage()));
        });
    }
}

```

**Comment by Zidane** [comment]
@kashike does your PRs/etc cover this already?

**Comment by kashike** [comment]
@Zidane Yup, this is possible in bleeding.
