### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by captincreeper1** [SpongePowered/SpongeAPI#968]
Ok i am trying to install permissionsex on sponge 1.8 and cannot i have created the files and gives me a bunch of errors whenever i type a command when it is installed then fine when it is not installed please help.

**Comment by JBYoshi** [comment]
Post your issue either on the [PermissionsEx thread on the Sponge forums](https://forums.spongepowered.org/t/permissionsex-v2-0/) or as a GitHub issue on [the PermissionsEx repository](https://github.com/PEXPlugins/PermissionsEx/issues). Also, make sure to include the errors you get when running the commands.
