### ISSUE TITLE
BlockFromToEvent-style event

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#973]
Bukkit has a [BlockFromToEvent](https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/event/block/BlockFromToEvent.java) that is called when water & lava try to mix together to form stone/cobblestone/obsidian.
This event, when cancelled:
- does not cause any block changes
- does not send any effects (sounds, particles)

This is somewhat doable with `NotifyNeighborBlockEvent`, but not all cases are handled. To fully do what a **single** event does in Bukkit someone would need to subscribe to `NotifyNeighborBlockEvent`, a `ScheduledBlockUpdate` event, and possibly more.

**Comment by me4502** [comment]
Isn't this the same as https://jd.spongepowered.org/3.0.0/org/spongepowered/api/event/block/ChangeBlockEvent.Modify.html ?

**Comment by Maxqia** [comment]
ChangeBlockEvent.Pre + NamedCause.LIQUID_FLOW should do this (dunno about the dragon egg part though)

**Comment by parlough** [comment]
I believe this can be handled with other events and the improvements of cause and contexts. If the dragon egg needs more special handling, a different issue can be opened with more specific features as well due to its unique behavior.
