### ISSUE TITLE
Support for Portals

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/SpongeAPI#975]
Been talking over what would be required for a fully-featured portal api. Here's some features/requirements that should be considered when someone takes a whack at it.

Portals should be ...
- managed through a service
- persistent
- able to be enabled/disabled
- have dependent blocks which trigger a check if the portal is still valid
- are dependent on a plugin being loaded (no plugin no portal (don't delete it just disable))
- be represented by a PopulatorObject
- target either a relative position (think nether) or an absolute position (think end)
  - can target either another portal or a non-portal 'landing zone'
  - extry / exit zones
- support clumping targets so multiple portals can target a single portal in the other dimension (how the nether does it)
- behavior must be dependent on the dimension (so a portal type can do different things in different dimensions)
- support for delays before activating
- Add some additional portal events with phases for entering the portal, just before activation, and upon arrival.
- have cake

Any other suggestions are welcome.

**Comment by JBYoshi** [comment]
How would it work with mods? Usually mods (along with vanilla Minecraft itself) hardcode the "from" and "to" dimension IDs.

> * have cake

CAKE! CAKE! CAAAAAKE!!!!! :cake:

**Comment by ST-DDT** [comment]
IIRC this has been a previous issue on this topic: https://github.com/SpongePowered/SpongeAPI/issues/504

Portals 
* have an entry zone
* have an exit zone
* may be limited to specific dimensions or behave differently across dimensions
* may be constructable/destructible by normal users or admin users
* may require a target portal building
* may require some kind of permission
* may prepare the target location (clear space, place portal etc)
* may be instantly or may be triggered after an interval
* may cause sounds, particles, potion effects or spawned monsters
* may mess with your inventory, require payment
* may require a manual teleport confirmation
* can be mono directional or bidirectional

**Comment by Deamon5550** [comment]
>    have an entry zone
    have an exit zone
    may be limited to specific dimensions or behave differently across dimensions

added

>    may be constructable/destructible by normal users or admin users
    may require some kind of permission
    may cause sounds, particles, potion effects or spawned monsters
    may mess with your inventory, require payment
    may require a manual teleport confirmation

All of these extra effects / alternate triggering condiditions / permissions are better handled through some better portal events which pre and post phases.

>    may require a target portal building
    may prepare the target location (clear space, place portal etc)

Covered by targeting either another portal or a non-portal landing space.

>    may be instantly or may be triggered after an interval

Added, we can fix the nether portals lack of a delay at the same time heh.

>    can be mono directional or bidirectional

A bidirectional is just two portals targeting each other, no need for special handling since they could even be many-to-one (as the nether portals are)

**Comment by Tzky** [comment]
What about one-to-many? I imagine this as a random choice of an exit node. Or should we leave this up to plugins?

**Comment by Deamon5550** [comment]
yeah if there was an event just before the entity was teleported then it could have a field for which portal is targeted, and you could use this to change the targeted portal.

**Comment by Zidane** [comment]
Update @Deamon5550 ?

**Comment by gabizou** [comment]
Not sure what the point of the API resulted in, but PortalAgents are exposed, and with mods, we aren't able to take advantage of over half of these issues. Going to close as the PortalAgent can be created by plugins to manage their own portals with entry and exit points, and our events are powerful as is to modify portal teleportation. Unless other objections are brought up, I'll keep the issue closed.
