### ISSUE TITLE
Add Excludes to Cause Filtering

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeAPI#981]
Currently, [Cause Filtering](https://github.com/SpongePowered/SpongeAPI/tree/master/src/main/java/org/spongepowered/api/event/filter/cause) has these neat filtering annotations, but it would help to possibly allow adding "excludes" to further ignore other class instances so the following can happen:
What would happen normally:
```java
@Listener
public void onInteract(InteractBlockEvent event, @First Monster monster) {
 if (monster instanceof Zombie) {
  // zombie do stuff
 } else if (monster instanceof Enderman) {
  Enderman // do stuff
 }
}
```
Versus:

```java
@Listener
public void onInteract(InteractBlockEvent event, @First({Zombie.class, Enderman.class}) Monster monster) {
 // you know you have either the first Zombie or the first Enderman.
}
```

**Comment by Deamon5550** [comment]
Added in f694c59b9d6f79e91ef3778e4c7935fe17f73850
