### ISSUE TITLE
Introduce a UserStorage.size() method.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#983]
Having a UserStorage.size() method would prevent @JamesTheCoder from needing to get the entire collection of user profiles at launch. He is trying to keep track of a unique count of players that have logged into the server, so I suggested getting the amount of player profiles in the UserStorage instead of keeping a config file full of UUID.

However it's marked as being resource intensive in the javadocs, so if it were possible to get the count, instead of the full list of game profiles, it would save a lot of effort on the servers part.

**Comment by JBYoshi** [comment]
Actually, I think `UserStorage` may also involve other cached information relating to users, not just the list of players who have joined the server. In particular, I believe `UserStorage` caches data for players who tried to log in but failed (such as being blocked by the whitelist).

**Comment by gabizou** [comment]
The issue with telling the size is that since the service is meant to act as a cache, it's not guaranteed to say "how many users" total, but more of "how many users recently queried".

**Comment by JamesTheCoder** [comment]
Testing shows the same, as the list does not hold after a server restart.

**Comment by ryantheleach** [comment]
Ok, sure. so how can you get the total number of players that the game has records for?

**Comment by gabizou** [comment]
You kinda can't.

**Comment by ryantheleach** [comment]
Can't in API or can't in implementation?

**Comment by gabizou** [comment]
Since user data is managed by the UserStorageService, it's up to the service whether it will support it. Counting the list of player files in a specific world isn't enough though for some cases, other plugins may say that it's too expensive or just dynamically not caring whether the user's info is actually stored.

**Comment by JamesTheCoder** [comment]
Any recommendations for how to store this then? Code example would be great, as I can't get node.getList() to work from the config.
