### ISSUE TITLE
Potion effect events

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#985]
There are a few [`PotionEffect`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/effect/potion/PotionEffect.java) related events that would be useful:
- `Add` -  called when a potion effect is applied
  - cancelling would prevent the effect from being applied/added
- `Expire` - called when a potion effect on an entity expires
  - cancelling this event is a bit more involved:
    - when cancelling, set the duration on the event to `Integer.MAX_INT` it cancelled, otherwise to `0`
  - having a `setDuration` (and `getDuration`) to change the duration would be helpful as well, to provide more accurate durations
- `Extend` - called when an existing potion effect is extended/upgraded
  - cancelling would prevent the extension/upgrade from taking place, and leave the original (active) effect active
- `Remove` - called when a potion effect is removed
  - cancelling would prevent the effect from being removed

**Comment by AlphaModder** [comment]
I don't think we should make Expire cancellable, considering that odd logic. Just allow plugins to give the effect back upon expiration so that we don't make any assumptions about the duration.
Does `Remove` specifically not include `Expire`?

**Comment by kashike** [comment]
Making `Expire` cancellable is a clean solution, since it's just giving back the same effect with the duration specified in the event (defaulting to `Integer.MAX_VALUE` when cancelled).
`Remove` is when the effect is removed - by manually removing it (plugin, mod, vanilla), etc.

**Comment by AlphaModder** [comment]
@kashike Alright, If you think. The `MAX_VALUE` thing seems a bit odd, though.

**Comment by ryantheleach** [comment]
It's the sanest out of the alternatives.

**Comment by gabizou** [comment]
Not going to have a cancellable `Expire` event.

**Comment by ImMorpheus** [comment]
Added (in the same class) by https://github.com/SpongePowered/SpongeAPI/commit/42cb3fb68940f105c890dcee4c4a76dbd5625402
