### ISSUE TITLE
GameStoppingServerEvent not firing

### ISSUE THREAD

**Issue by TypicalDarkness** [SpongePowered/SpongeAPI#992]
For some reason this doesn't fire:
```java
@Listener void onServerStop(GameStoppingServerEvent e) {}
```
Tested on SpongeForge 979.

**Comment by JBYoshi** [comment]
This is an implementation issue, not an API issue.

**Comment by TypicalDarkness** [comment]
Where do I have to post it then?

**Comment by JBYoshi** [comment]
Post the issue on the SpongeForge repository.

**Comment by TypicalDarkness** [comment]
As you probably saw I already posted it there but then removed it for whatever reason.
