### ISSUE TITLE
GenericArguments.Vector3d

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeAPI#993]
Moved from: https://github.com/SpongePowered/SpongeCommon/issues/373

Using Generic Arguments.Vector3d does not support commands using 

``/command ~ ~ ~``

``/command ~1 ~1 ~1`` however works. as does ``/command ~0 ~0 ~0`` ,  ``/command ~+1 ~+1 ~+1`` and ``/command ~-1 ~-1 ~-1``

Inserting 
```
if(arg.isEmpty()) arg = "0";
```

after line https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L1059

Fixes the issue.

**Comment by zml2008** [comment]
This has been fixed in d50ee1da1ca9877fe16fecd717efe6659c2f5a0e
