### ISSUE TITLE
Provide getters for event data

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeAPI#998]
Things directly related that are **always present** should have a getter, even if it's just a `default` method pulling from the `Cause`:
```java
default X getX() {
    return this.getCause().first(X.class).get();
}
```

**Comment by gabizou** [comment]
Could you elaborate what data is always present?

**Comment by Deamon5550** [comment]
The thing about causes is that we *cannot* guarantee that anything will always be there.
