### ISSUE TITLE
Wrapped MessageChannel

### ISSUE THREAD

**Issue by ZephireNZ** [SpongePowered/SpongeAPI#999]
I think there should be an easy way to wrap an existing sink, primarily to transform a message after all previous transformations have been applied.

For example, when a player sends a message, the vanilla channel's transformations would be to add "(PLAYER)" to the start of the message.

A chat channel plugin could then add the room name "{CHANNEL1}" on top of that, followed by "[RANK]" from the permissions plugin.

The only existing implementation of this is `DelegateMutableMessageChannel`, however this makes a copy of the receiver list, meaning that channels such as `TO_PLAYERS` will not work.

While plugins could individually implement, its much simpler to add to the API, with a corresponding convenience method such as `MessageChannel wrapped(MessageChannel first, MessageTransformer... next)` or something similar.

**Comment by ZephireNZ** [comment]
@kashike

**Comment by Zidane** [comment]
@ZephireNZ 

Is this still an issue with API 4?

**Comment by ZephireNZ** [comment]
Actually I think I missed the `CombinedMessageChannel` which came with the original implementation.

You could give it the original channel, and then your own "transforming" channel, and it would do the same as my wrapped method above.

**Comment by ZephireNZ** [comment]
Actually, ignore that, it looks like it works on a set rather than a list, causing problems if the order is changed.

**Comment by kashike** [comment]
Is https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/channel/impl/DelegateMessageChannel.java not what you're after? Just extend and override the `transformMessage` message, the `delegate` field provides the original channel.

**Comment by ZephireNZ** [comment]
Good point. Looks like that was added later on. There's no convenience method, but that's still enough to satisfy me haha :)
